### ISSUE TITLE
the way cinder-endpoint to deploy provisioner that the image standalone-cinder-provisioner not support

### ISSUE THREAD

**Issue by jianglingxia** [kubernetes/cloud-provider-openstack#100]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug
> Uncomment only one, leave it on its own line: 
>
> /kind bug
> /kind feature

**What happened**:
I use the cinder-endpoint way to deploy the provisioner,but found the image that quay.io/external_storage/standalone-cinder-provisioner:latest not updated and not supproted! then I plan to make a image use the master branch code,and clone the cloud-provider-openstack code then command the make,but found need glide,then install glide and make again,but found the log,can help me or I maybe wrong in some place,thanks

[INFO]	--> Fetching k8s.io/apiextensions-apiserver
[INFO]	--> Fetching k8s.io/kube-openapi
[INFO]	--> Fetching k8s.io/kubernetes
[WARN]	Unable to checkout golang.org/x/net
[ERROR]	Update failed for golang.org/x/net: Cannot detect VCS
[WARN]	Unable to checkout golang.org/x/crypto
[ERROR]	Update failed for golang.org/x/crypto: Cannot detect VCS
[WARN]	Unable to checkout golang.org/x/sys
[ERROR]	Update failed for golang.org/x/sys: Cannot detect VCS
[WARN]	Unable to checkout golang.org/x/text
[ERROR]	Update failed for golang.org/x/text: Cannot detect VCS
[WARN]	Unable to checkout google.golang.org/genproto
[ERROR]	Update failed for google.golang.org/genproto: Cannot detect VCS
[WARN]	Unable to checkout golang.org/x/time
[ERROR]	Update failed for golang.org/x/time: Cannot detect VCS
[WARN]	Unable to checkout google.golang.org/grpc
[ERROR]	Update failed for google.golang.org/grpc: Cannot detect VCS

**What you expected to happen**:
can provider a new image ?
**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- openstack-cloud-controller-manager version:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by jianglingxia** [comment]
/assign @dims 
thanks very much

**Comment by jianglingxia** [comment]
[root@controller:/paasdata/cloud-provider-openstack-master]$ glide --version
glide version v0.13.1
[root@controller:/paasdata/cloud-provider-openstack-master]$ go version
go version go1.9.2 linux/amd64
[root@controller:/paasdata/cloud-provider-openstack-master]$ ls
bindep.txt  cmd      devstack  examples    glide.yaml  LICENSE   manifests  pkg        staging  vendor
cluster     contrib  docs      glide.lock  hack        Makefile  OWNERS     README.md  tools
[root@controller:/paasdata/cloud-provider-openstack-master]$ make
pip install Mercurial
Collecting Mercurial
  Downloading http://1.1.1.1/pypi/packages/23/9f/79296aac5577fd2c9de7d754cb64807faf26cf02f4423ba2ac36cbebf053/mercurial-4.3.3.tar.gz (5.5MB)
    100% |████████████████████████████████| 5.5MB 12.5MB/s
    Complete output from command python setup.py egg_info:
    running egg_info
    creating pip-egg-info/mercurial.egg-info
    writing pip-egg-info/mercurial.egg-info/PKG-INFO
    writing top-level names to pip-egg-info/mercurial.egg-info/top_level.txt
    writing dependency_links to pip-egg-info/mercurial.egg-info/dependency_links.txt
    writing manifest file 'pip-egg-info/mercurial.egg-info/SOURCES.txt'
    Python headers are required to build Mercurial but weren't found in /usr/include/python2.7/Python.h

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-FiMj5A/Mercurial/
make: *** [depend] Error 1
can help me?

**Comment by dims** [comment]
install mercurial using apt : `apt install mercurial` and then re-run make

**Comment by dims** [comment]
please see PR - https://github.com/kubernetes/cloud-provider-openstack/pull/104

/close
