### ISSUE TITLE
Cinder CSI: volumes stuck for ever in deleted nodes

### ISSUE THREAD

**Issue by zetaab** [kubernetes/cloud-provider-openstack#1003]
/kind bug

**The binaries affected**:

- [ ] openstack-cloud-controller-manager
- [x] cinder-csi-plugin
- [ ] k8s-keystone-auth
- [ ] client-keystone-auth
- [ ] octavia-ingress-controller
- [ ] manila-csi-plugin
- [ ] manila-provisioner
- [ ] magnum-auto-healer
- [ ] barbican-kms-plugin

**What happened**:

I renamed my kubernetes node names (deleted old ones and created new ones). However, now the volumes are still stuck in old named nodes and says "attached". CSI-attacher cannot delete the volumeattachment objects because node does not exist.

**What you expected to happen**:

I expect that volumeattachment object could be deleted if node where it was attached does not exist anymore

**How to reproduce it**:

1. create cluster
2. make some csi volumes with cinder
3. delete nodes
4. recreate nodes with new name

**Anything else we need to know?**:

```
I0401 14:06:39.029738       1 request.go:530] Throttling request took 1.142016254s, request: PATCH:https://100.64.0.1:443/apis/storage.k8s.io/v1beta1/volumeattachments/csi-5887bc6d1d415be7aa745ac28d7a9644c3497152b7bb860d3ce5e6a1c6f2f1c1
I0401 14:06:39.045731       1 csi_handler.go:439] Saved detach error to "csi-5887bc6d1d415be7aa745ac28d7a9644c3497152b7bb860d3ce5e6a1c6f2f1c1"
I0401 14:06:39.045774       1 csi_handler.go:99] Error processing "csi-5887bc6d1d415be7aa745ac28d7a9644c3497152b7bb860d3ce5e6a1c6f2f1c1": failed to detach: rpc error: code = NotFound desc = ControllerUnpublishVolume Instance not found
I0401 14:06:39.046042       1 controller.go:141] Ignoring VolumeAttachment "csi-5887bc6d1d415be7aa745ac28d7a9644c3497152b7bb860d3ce5e6a1c6f2f1c1" change
I0401 14:06:39.229755       1 request.go:530] Throttling request took 1.314132779s, request: PATCH:https://100.64.0.1:443/apis/storage.k8s.io/v1beta1/volumeattachments/csi-89d47330cf387f5cf4f2d39020aba52814912b3b14134e38b06fe9be3d75e255
I0401 14:06:39.238415       1 csi_handler.go:439] Saved detach error to "csi-89d47330cf387f5cf4f2d39020aba52814912b3b14134e38b06fe9be3d75e255"
I0401 14:06:39.238448       1 csi_handler.go:99] Error processing "csi-89d47330cf387f5cf4f2d39020aba52814912b3b14134e38b06fe9be3d75e255": failed to detach: rpc error: code = NotFound desc = ControllerUnpublishVolume Instance not found
```

How to fix this:
- when deleting volumeattachment ignore instance not found error

**Comment by zetaab** [comment]
I solved this manually:
1) create nodes again with old names
2) detach all volume attachments
3) drain old nodes
4) delete old nodes

blaah...

**Comment by lingxiankong** [comment]
I suppose this one has something to do with #1004

**Comment by ramineni** [comment]
@zetaab this behavior is changed in latest release 1.18 . Now, if the node is not found, it will return without any error assuming its already detached. https://github.com/kubernetes/cloud-provider-openstack/blob/master/pkg/csi/cinder/controllerserver.go#L217

I suppose this should solve your issue.

**Comment by zetaab** [comment]
I updated to 1.18 and all zombie volumeattachments and pvcs was gone
