### ISSUE TITLE
Support to launch specified binary in local-up-cluster.sh, like: cinder-provisioner and so on

### ISSUE THREAD

**Issue by kiwik** [kubernetes/cloud-provider-openstack#101]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind feature

**What happened**:
We have several binaries in repo:
- openstack-cloud-controller-manager
- cinder-provisioner
- cinder-csi-plugin
- cinder-flex-volume-driver
- k8s-keystone-auth

Now local-up-cluster.sh only support to launch and config **openstack-cloud-controller-manager**, is there any plan to support launching all of these above binaries in local-up-cluster.sh? That will help OpenLab to reduce the complexity of automation script, like: https://github.com/theopenlab/openlab-zuul-jobs/blob/master/playbooks/cloud-provider-openstack-acceptance-test-keystone-authentication-authorization/run.yaml#L86-L88 and https://github.com/theopenlab/openlab-zuul-jobs/blob/master/playbooks/cloud-provider-openstack-acceptance-test-keystone-authentication-authorization/run.yaml#L92-L98

**What you expected to happen**:
We can control to launch specified binary with some environment variables in local-up-cluster.sh, like: EXTERNAL_CLOUD_PROVIDER_BINARY do now.

**How to reproduce it (as minimally and precisely as possible)**:
NA

**Anything else we need to know?**:
NA

**Environment**:
- openstack-cloud-controller-manager version:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by dims** [comment]
i am thinking we should have like a pre/post hooks in local-up-cluster.sh as local-up-cluster is in main k/k and should not know about binaries that are not in the main repo. so basically we can have scripts in our repo and need to set something in local-up-cluster.sh to call them
