### ISSUE TITLE
Export variable in driver.go

### ISSUE THREAD

**Issue by yuquan-wang** [kubernetes/cloud-provider-openstack#1015]
**Is this a BUG REPORT or FEATURE REQUEST?**:
 feature request

**What you expected to happen**:

Export following variable in driver.go
```
ids *identityServer
cs  *controllerServer
ns  *nodeServer
```
We have a special usage for cinder-csi, so we need to develop our own csi based on this project, we want to make use of above variables in our own csi, would you mind export those variables.
In aws-ebs-driver we can make use of that directly, really appreciate if this project also support it.

**Comment by jichenjc** [comment]
maybe you can submit a PR directly or add some function to return that such as 
Getxxx() 
{
        return *csiDriver
}
？

**Comment by yuquan-wang** [comment]
@jichenjc sure, no problem. 
I just want to confirm with you guys that the change is acceptable before i submit a PR.

**Comment by lingxiankong** [comment]
Thanks for reporting this issue.

If the purpose is to create your own csi based on this project, the recommended way is to make a fork and do your own change. 

With that said, I don't think this is a reasonable feature request for us. I am closing this issue, but you are welcome to open a new one if you need any assistance for cinder-csi-plugin.

/close
