### ISSUE TITLE
[cinder-csi-plugin] node server should not use openstack credentials by default

### ISSUE THREAD

**Issue by kayrus** [kubernetes/cloud-provider-openstack#1020]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind feature

**What happened**:

Cinder CSI node server tries to create an openstack client based on cloud-config, when usually this is not necessary, since all openstack related communications are done on csi controller side.

**What you expected to happen**:

I expect CSI cinder node server not to use openstack credentials, when it is not necessary and respect the https://github.com/kubernetes/kubernetes/blob/08e1fd3bb947faf465e8a67d5c7106dbd10840c0/pkg/apis/core/types.go#L1607 and https://github.com/kubernetes/kubernetes/blob/08e1fd3bb947faf465e8a67d5c7106dbd10840c0/pkg/apis/core/types.go#L1664..L1670 API. So when ephemeral storage is requested, user must provide secret reference via pod manifest or storage manifest.

In addition, node server manifest should not refer to secrets. The node server configuration should be done via configMap. See discussion here: https://github.com/kubernetes/cloud-provider-openstack/pull/861#issuecomment-585645374

**Anything else we need to know?**:

https://github.com/kubernetes-csi/external-attacher/pull/38

https://kubernetes-csi.github.io/docs/secrets-and-credentials.html

openstack client is used in functions listed below:
* nodePublishEphermeral
* nodeUnpublishEphermeral
* NodeStageVolume
* NodeUnstageVolume
* NodePublishVolume
* NodeUnpublishVolume

/cc @rfranzke

**Comment by jichenjc** [comment]
just to confirm, the overall idea is to use secret or related info to avoid usage of cloud-config, but still need the provided secret to do communication with openstck side(in other words ,the mechanism of communication between CSI node + openstack is not changed, how to provide cloud definition will be changed, correct?)

**Comment by kayrus** [comment]
Initial idea was to start nodeserver without secrets. It may be required by security purpose. Additionally, follow CSI spec and configure openstack client from secrets, provided in storageclass manifest when possible.

For now I'm confident that secrets are required by ephemeral inline storage. Nodeserver may work fine without secrets and ephemeral storage support.

The rest functions are:
* NodeStageVolume
* NodeUnstageVolume
* NodePublishVolume
* NodeUnpublishVolume

I haven't managed to clarify their purpose. But it would be fine if it is nodeserver just return an error, when openstack API operation is not possible.

**Comment by ramineni** [comment]
we need to use openstack credentials for some of the operations in nodeserver . As per the https://kubernetes-csi.github.io/docs/secrets-and-credentials.html , 
`secret is required at the "per driver" granularity (not different "per CSI operation" or "per volume"), then the secret SHOULD be injected directly in to CSI driver pods via standard Kubernetes secret distribution mechanisms during deployment.` This is the way we are doing it currently , so it is fine.

IIUC, secrets needs to be provided per storageclass only when needed credentials per volume/per operation 
`If a CSI Driver requires secrets "per CSI operation" or "per volume" or "per storage pool", the CSI spec allows secrets to be passed in for various CSI operations. Cluster admins can populate such secrets by creating Kubernetes Secret objects and specifying the keys in the StorageClass or SnapshotClass objects` (Ref: https://kubernetes-csi.github.io/docs/secrets-and-credentials.html)

**Comment by kayrus** [comment]
See an azure node controller for reference: https://github.com/kubernetes-sigs/aws-ebs-csi-driver/blob/master/deploy/kubernetes/base/node.yaml
It doesn't have secrets

**Comment by puck** [comment]
It looks to me like node servers needed secrets for ephemeral storage, but ephemeral storage was removed in https://github.com/openshift/openstack-cinder-csi-driver-operator/pull/76 . Does this mean the requirement to have secrets on the nodes is gone?
