### ISSUE TITLE
Create a periodic job for e2e conformance test and upload results to test grid

### ISSUE THREAD

**Issue by dims** [kubernetes/cloud-provider-openstack#103]
Now that we have the e2e conformance test run against PR(s), we need a CI job that runs the same thing periodically (6 hours? 12 hours?) Here are some notes:

- We need a periodic job for Kubernetes/Kubernetes master against cloud-provider-openstack master (so we know if we break something)
- We need a periodic job for Kubernetes/Kubernetes release-1.10 branch against cloud-provider-openstack master (se we make sure we don't break any one who wants to use our code against the last release)
- Need to create a GCS bucket and upload files for each run, so we can display the results in kubernetes test-grid. See details in [1]

Nits:
- test_results.html is empty as the junit xml file is under kubernetes directory (it's junit_01.xml)

Links:
- [1] https://docs.google.com/document/d/1lGvP89_DdeNO84I86BVAU4qY3h2VCRll45tGrpyx90A/edit?ts=5a8486c1

**Comment by kiwik** [comment]
@dims please add privilege for @animationzl and I, we can not access to the google doc.
OpenLab have periodic pipeline, can run the job, we should consider the resource usage for all of the periodic jobs, beside e2e conformance job, there are some other sdk periodic jobs in OpenLab.

**Comment by kiwik** [comment]
Work item:
- Update periodic pipeline setting to run per 12 hours in OpenLab
- Add a new job to run Kubernetes/Kubernetes latest release (1.10) against cloud-provider-openstack master in OpenLab (current e2e conformance job have supported run k8s master against cloud-provider-openstack master)
- Update .zuul.yaml to add above two jobs into periodic pipeline in this repo
- Support to upload test result to GCS, and report result in kubernetes test-grid
- Fix the empty test_result.html issue

**Comment by kiwik** [comment]
Hi @dims , could you help to finish this work item?

- Support to upload test result to GCS, and report result in kubernetes test-grid

I have prepared a post hook in https://github.com/theopenlab/openlab-zuul-jobs/blob/master/playbooks/cloud-provider-openstack-acceptance-test-e2e-conformance/post.yaml#L10-L12 , but I can not understand well how to set config in kubernetes side.

**Comment by dims** [comment]
Ack. the python script itself is here https://github.com/kubernetes/test-infra/blob/master/testgrid/conformance/upload_e2e.py

Though we have to figure out if there is a community GCS bucket we could use
