### ISSUE TITLE
[cinder-csi-plugin] Availability zone can not be resolved with configdrive

### ISSUE THREAD

**Issue by mape90** [kubernetes/cloud-provider-openstack#1030]
**What happened**:
Deployments with metadata drive will fail to resolve availability zone.

Cinder CSI still uses its own metadata implementation that only works with metadata service and not with configdrive.

**What you expected to happen**:
VMs with configdrive only would be able to get their metadata.

**How to reproduce it**:
VM has only configdrive and not metadata service on network.

**Anything else we need to know?**:

package "k8s.io/cloud-provider-openstack/pkg/util/metadata" implements correct and functional metadata service. So there is no need for CSI own metadata implementation. Whole openstack_metadata.go could be removed.

When metadata is needed it could be fetched with:
`md, err := metadata.Get(ns.Cloud.GetMetadataOpts().SearchOrder)`

Also the default search order should be ConfigDriveID and then MetadataID. As detecting missing device is fast but missing metadata service will take until request timeouts.

**Environment**:
- openstack-cloud-controller-manager(or other related binary) version: master
- OpenStack version: -
- Others: -

/kind bug

**Comment by lingxiankong** [comment]
@mape90 May I ask which cinder-csi-plugin version you are using? At least from release v1.18, the cinder csi has already used `k8s.io/cloud-provider-openstack/pkg/util/metadata`, see https://github.com/kubernetes/cloud-provider-openstack/blob/release-1.18/pkg/csi/cinder/nodeserver.go#L563, and search order can also be customized, https://github.com/kubernetes/cloud-provider-openstack/blob/release-1.18/docs/using-cinder-csi-plugin.md#deploy

**Comment by mape90** [comment]
@lingxiankong I have checked master and v1.18 code. Both use only mounter and openstack.IMetaData. Neither of those implements access to config drive.

The whole function could be rewritten as
```
func getNodeID(order string) (string, error){
	md, err := metadata.Get(searchOrder)
	if err != nil {
		return "", err
	}
	
	return md.UUID, nil
}
```
Bigger problem is the availability zone where mounter can not provide it and it would be odd if it would. But whole metadata access could be rewritten with that util/metadata.

**Comment by lingxiankong** [comment]
Isn't https://github.com/kubernetes/cloud-provider-openstack/blob/master/pkg/csi/cinder/nodeserver.go#L609-L634 what you are pursuing? Could you provide some error log we could investigate?

**Comment by mape90** [comment]
That only either uses mounter to read /var/lib/cloud/data/instance-id or it uses metadata service. It never uses config drive. Then when comes time to fetch availability zone it only uses metadata service. 

I currently do not have logs. But by following the execution path you can see that nothing ever access the config drive. It should mount device with label "config-2"

Reason why most of the people are not seeing this issue is that by default modern Openstack setups DHCP and MetadataService to basically all netowrks so you will always be able to get it. However if you setup the network without DHCP so then only way to get network configuration is via configdrive as VM can not even setup its interfaces as there is not service for providing IPs.

**Comment by lingxiankong** [comment]
> That only either uses mounter to read /var/lib/cloud/data/instance-id or it uses metadata service. It never uses config drive. Then when comes time to fetch availability zone it only uses metadata service.
> 
> I currently do not have logs. But by following the execution path you can see that nothing ever access the config drive. It should mount device with label "config-2"
> 
> Reason why most of the people are not seeing this issue is that by default modern Openstack setups DHCP and MetadataService to basically all netowrks so you will always be able to get it. However if you setup the network without DHCP so then only way to get network configuration is via configdrive as VM can not even setup its interfaces as there is not service for providing IPs.

I see your point now @mape90 , you are right, the data source is only coming from metadata service, not config drive.

**Comment by jichenjc** [comment]
I think it can be tested by using force config drive flag in deploy action in nova
the question I have is ` /var/lib/cloud/data/instance-id` actually comes from config drive? config-2 label disk will be honored and create the file above by cloud-init?

**Comment by mape90** [comment]
I think that /var/lib/cloud/data/instance-id is generated by cloud-init from the metadata it gets. And it gets it either via config drive or via metadata service. So using mouter to fetch that file do not give anything extra. As metadata would have the same information. 

We are deploying VMs with configdrive only (no metadata service is available for VM) and those also populate that instance-id -file.

**Comment by jichenjc** [comment]
sorry about the question so we are proposing following (if search order is config drive and then metadata?) 
1) use cloud-init generated file id
2) use config-2
3) use metadata service

we are missing config-2 in code so you want to add it?

**Comment by mape90** [comment]
What I would propose is that just use util/metadata/metadata.go for nodeID, AvailabilityZone and getting Devicepath (Workaround for Nova Hyper-V).

This would simplify code and reduce replicated code as whole  csi/cinder/openstack/openstack_metadata.go could be deleted. Also we would not need to use mounter for getting nodeid as same information can be provided by metadata package.

So we could reduce 3 cases to one case with same functionality.

function call:
`md, err := metadata.Get(ns.Cloud.GetMetadataOpts().SearchOrder)`
would return metadata struct with UUID and AZ.

**Comment by ramineni** [comment]
@mape90 Its on the list for quite sometime now to reduce the duplicate code . +1 on the same. Would you like to take it up?

**Comment by celiawa** [comment]
We met this issue, metadata service is unreachable, so all the csi-cinder-nodeplugin pods failed to start. 

`# kubectl logs -f csi-cinder-nodeplugin-5nvmm -c node-driver-registrar -nkube-system
I0609 03:39:47.044360       1 main.go:110] Version: 
I0609 03:39:47.044489       1 main.go:120] Attempting to open a gRPC connection with: "/csi/csi.sock"
I0609 03:39:47.044527       1 connection.go:151] Connecting to unix:///csi/csi.sock
I0609 03:39:47.046016       1 main.go:127] Calling CSI driver to discover driver name
I0609 03:39:47.048428       1 node_register.go:54] Starting Registration Server at: /registration/cinder.csi.openstack.org-reg.sock
I0609 03:39:47.048833       1 node_register.go:61] Registration Server started at: /registration/cinder.csi.openstack.org-reg.sock
I0609 03:39:48.625019       1 main.go:77] Received GetInfo call: &InfoRequest{}
I0609 03:40:18.641993       1 main.go:87] Received NotifyRegistrationStatus call: &RegistrationStatus{PluginRegistered:false,Error:RegisterPlugin error -- plugin registration failed with err: rpc error: code = Internal desc = retrieving availability zone from MetaData service failed with error Get http://169.254.169.254/openstack/latest/meta_data.json: dial tcp 169.254.169.254:80: i/o timeout,}
E0609 03:40:18.642091       1 main.go:89] Registration process failed with error: RegisterPlugin error -- plugin registration failed with err: rpc error: code = Internal desc = retrieving availability zone from MetaData service failed with error Get http://169.254.169.254/openstack/latest/meta_data.json: dial tcp 169.254.169.254:80: i/o timeout, restarting registration container.`

**Comment by celiawa** [comment]
We met this issue, metadata service is unreachable, so all the csi-cinder-nodeplugin pods failed to start.

#kubectl logs -f csi-cinder-nodeplugin-5nvmm -c node-driver-registrar -nkube-system
I0609 03:39:47.044360 1 main.go:110] Version:
I0609 03:39:47.044489 1 main.go:120] Attempting to open a gRPC connection with: "/csi/csi.sock"
I0609 03:39:47.044527 1 connection.go:151] Connecting to unix:///csi/csi.sock
I0609 03:39:47.046016 1 main.go:127] Calling CSI driver to discover driver name
I0609 03:39:47.048428 1 node_register.go:54] Starting Registration Server at: /registration/cinder.csi.openstack.org-reg.sock
I0609 03:39:47.048833 1 node_register.go:61] Registration Server started at: /registration/cinder.csi.openstack.org-reg.sock
I0609 03:39:48.625019 1 main.go:77] Received GetInfo call: &InfoRequest{}
I0609 03:40:18.641993 1 main.go:87] Received NotifyRegistrationStatus call: &RegistrationStatus{PluginRegistered:false,Error:RegisterPlugin error -- plugin registration failed with err: rpc error: code = Internal desc = retrieving availability zone from MetaData service failed with error Get http://169.254.169.254/openstack/latest/meta_data.json: dial tcp 169.254.169.254:80: i/o timeout,}
E0609 03:40:18.642091 1 main.go:89] Registration process failed with error: RegisterPlugin error -- plugin registration failed with err: rpc error: code = Internal desc = retrieving availability zone from MetaData service failed with error Get http://169.254.169.254/openstack/latest/meta_data.json: dial tcp 169.254.169.254:80: i/o timeout, restarting registration container.

**Comment by jichenjc** [comment]
looks like this is something we need a fix, I can try to provide a quick fix (not with refactory the code to merge all metadata services...)

**Comment by ramineni** [comment]
@celiawa metadata service is not available in your env?

**Comment by ramineni** [comment]
> looks like this is something we need a fix, I can try to provide a quick fix (not with refactory the code to merge all metadata services...)

@jichenjc lets get this done fully refactored, let me know if you could do it or I can take it up.

**Comment by jichenjc** [comment]
@ramineni please take this if you can, glad to provide any comments on your PR :)

**Comment by celiawa** [comment]
We met this in two conditions. One is the metadata service is disabled in the lab. The other is the metadata service is enabled but we're not using dhcp but static ip, so no route table to 169.254.169.254 is added.

**Comment by jichenjc** [comment]
no matter metadata is disabled or not reachable, if you enable both in search order for configdrive and metadata, then it should be ok if the code is updated

the problem I see is if you use metadata service (from openstack side) , then no config drive will be created and if it's not reachable by dhcp, problem might occur

**Comment by celiawa** [comment]
We didn't set search-order in cloud-conf. And it used the default order search-order = configDrive,metadataService.

I saw below in my lab, does that mean config drive is also enabled.
[root@tesla-cb0434-csd1-csd1-control-01 ~]# cd /dev/disk/by-label
[root@tesla-cb0434-csd1-csd1-control-01 by-label]# ls
1@bcmt-baseos-20  config-2
[root@tesla-cb0434-csd1-csd1-control-01 by-label]# ll
total 0
lrwxrwxrwx. 1 root root 10 Jun 10 08:42 1@bcmt-baseos-20 -> ../../vda1
lrwxrwxrwx. 1 root root  9 Jun 10 01:57 config-2 -> ../../sr0

From below code in release 1.18, as our metadata server is unreachable, and as AZ can't be resolved with configdrive, so we can't get zone, and it returned with error. 
https://github.com/kubernetes/cloud-provider-openstack/blob/release-1.18/pkg/csi/cinder/nodeserver.go
`zone, err := getAvailabilityZoneMetadataService(ns.Metadata)
if err != nil {
return nil, status.Error(codes.Internal, fmt.Sprintf("retrieving availability zone from MetaData service failed with error %v", err))
}`

But the code in 1.17, doesn't return when failed to get zone.  
`zone, err := getAvailabilityZoneMetadataService(ns.Metadata)
topology := &csi.Topology{Segments: map[string]string{topologyKey: zone}}`

We don't use topology volumes. Could we use cinder plugin 1.17 though we use k8s 1.18 for our usage.
