### ISSUE TITLE
[octavia-ingress-controller] The loadbalancer is PENDING_UPDATE and Floating IP is not allocated

### ISSUE THREAD

**Issue by yotsapon** [kubernetes/cloud-provider-openstack#1052]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
/kind bug
> /kind feature

**What happened**:
I try to apply ingress but it looks like the status of loadbalancer is PENDING_UPDATE and the floating IP is not allocated. I am trying to delete ingress but the loadbalacer can't be removed as well. 

![image](https://user-images.githubusercontent.com/46857257/80788783-42d74600-8bb4-11ea-891a-d3d1190fa5b6.png)

![image](https://user-images.githubusercontent.com/46857257/80789939-b0d13c80-8bb7-11ea-8b0a-e7e5e5fc363b.png)

**What you expected to happen**:
I expected that after I create ingress. The loadbalacer should be ACTIVE status.

**Anything else we need to know?**:

**Environment**:
- openstack-cloud-controller-manager: v1.18.0
- octavia-ingress-controller: v1.18.0
- kubernetes: v1.16.8

**Comment by lingxiankong** [comment]
what's the Octavia version?

**Comment by yotsapon** [comment]
> what's the Octavia version?
I have asked the provider they told me that it's "Stable Train". I am not sure this is what you expect or not.

**Comment by lingxiankong** [comment]
seems your cloud doesn't support [batch member update](https://docs.openstack.org/api-ref/load-balancer/v2/index.html#batch-update-members), could you please check? You can also directly send HTTP request to verify.

**Comment by kayrus** [comment]
@yotsapon you can enable verbose JSON request/response logging for better understanding on what is going on: `--v=6`

**Comment by yotsapon** [comment]
> seems your cloud doesn't support [batch member update](https://docs.openstack.org/api-ref/load-balancer/v2/index.html#batch-update-members), could you please check? You can also directly send HTTP request to verify.

The provider told me that their Openstack Cloud doesn't support provider type Octavia. Thank you for your advice.

**Comment by yotsapon** [comment]
> @yotsapon you can enable verbose JSON request/response logging for better understanding on what is going on: `--v=6`

Thank you for your recommendation.
