### ISSUE TITLE
[cinder-csi-plugin] unable to detach cinder volume when node crashes/shutdown

### ISSUE THREAD

**Issue by amitbhatia1987** [kubernetes/cloud-provider-openstack#1056]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
 /kind bug
> /kind feature

**What happened**:
Pod is running on a node with volume using cinder-csi and when node goes down/crashes then pod moves to another node but stuck in "ContainerCreating" state as cinder volume is unable to detach from the crashed node and reattach on the new node where pod is shifted.  

**What you expected to happen**:
When node crashes and pod moves to another healthy node then cinder csi should call volumedetach and then volumeattach on new node where pod moved.

**How to reproduce it**:
Deploy cinder csi 
create a volume (pv & pvc)
create a pod with cinder pvc
shutdown the node/stop the network on the node where pod is running
pod will move to new node and remains in "ContainerCreating" state 

**Anything else we need to know?**:

**Environment**:
- openstack-cloud-controller-manager(or other related binary) version:  v0.0.0-master+$Format:%h$
- cinder.csi.openstack.org version: 1.1.0
- OpenStack version: Train
- Others:

**Comment by ramineni** [comment]
@amitbhatia1987 which cinder-csi image version are you using? is it 1.18? or latest

**Comment by amitbhatia1987** [comment]
Its v1.1.0 which is mentioned here (https://github.com/kubernetes/cloud-provider-openstack/blob/master/docs/using-cinder-csi-plugin.md)

**Comment by jichenjc** [comment]
is this something should be handled by upper layer?
seems CSI cinder only used in grpc to accept request from above layer?

or there are some event missed handle in CSI cinder so that whole process is blocked..

**Comment by ramineni** [comment]
@amitbhatia1987 Im asking the version used in manifest file for deploying the plugin. But Its fine. Could you clarify few things , from the openstack side , is the volume still attached to node . If the volume is detached from openstack side, it should work fine I suppose. From csi, if its already attached to different node, it will throw error as its not expected.  IMO detach cant be called from csi, as we wont be sure that is expected or not

**Comment by amitbhatia1987** [comment]
I was expecting when node crashes csi should invoke volumedetach so that it can be re-attached to another node where pod is moved

**Comment by ramineni** [comment]
@amitbhatia1987 could you share container logs of cinder-csi ?

**Comment by ramineni** [comment]
@amitbhatia1987 when the pods are evicted , its the responsibility of CO/external-attacher sidecar to initiate the unpublish volume on node. If its is called from the CO side , plugin would initiate the same . If you are seeing any error in the calls related to that , we can fix the issue . If its not at all called, I believe its outofscope for this project.

**Comment by johnyb79** [comment]
Hi ,

We are suffering from similar problem - it happens randomly after node power off/on.
Details below - but the main question is if there is some graceful way to recover from "status is detaching" state, so without data loss? I aiming here to the production level solution.


docker images | grep -i csi
/csi/node-driver-registrar                                v1.1.0              ac600e3a2ccd        3 months ago        71.3MB
/csi/csi-resizer                                          v0.3.0              ac6c108281b1        3 months ago        97.3MB
/csi/cinder-csi-plugin                                    v1.17.0             08e406993f07        4 months ago        194MB
/csi/csi-snapshotter                                      v1.2.2              3fd37ea4a27a        6 months ago        98.8MB
/csi/csi-provisioner                                      v1.4.0              59cf39a91efa        6 months ago        105MB
/csi/csi-attacher                                         v2.0.0              325e151614b2        6 months ago        97.4MB


---------------- Problematic pod

# kubectl get pod  -n nbam | grep  -i cfat
cfat-master-cfat-57b884cd45-dq9kk              0/1     ContainerCreating   0          6h47m

# kubectl describe pod cfat-master-cfat-57b884cd45-dq9kk  -n nbam 


Events:
  Type     Reason              Age                       From                           Message
  ----     ------              ----                      ----                           -------
  Warning  FailedAttachVolume  18m (x44315 over 6h48m)   attachdetach-controller        AttachVolume.Attach failed for volume "pvc-6070e307-091a-48cd-b123-358b02ee3330" : rpc error: code = Internal desc = ControllerPublishVolume Attach Volume failed with error disk d2a0a416-6696-442a-b93f-19eb7b376db5 is attached to a different instance (c085eedb-6846-4a33-a787-dfa183a7f213)
  Warning  FailedMount         3m53s (x169 over 6h25m)   kubelet, node-2003-control-02  (combined from similar events): Unable to attach or mount volumes: unmounted volumes=[cfat-backup cfat-repo], unattached volumes=[bcmt-path cfat-backup-cluster docker-socket cfat-master-cfat-token-5wnm6 cfat-backup cfat-repo helm-home certs host-timezone kubectl ncm-secret helm-cli ncm-cli helm3-cli]: timed out waiting for the condition
  Warning  FailedAttachVolume  3m2s (x45833 over 6h48m)  attachdetach-controller        AttachVolume.Attach failed for volume "pvc-df7ac3af-66d1-482e-a8ed-3b02c5a3cde6" : volume attachment is being deleted




---------------- Problematic pvc


# kubectl get pv,pvc | grep cfat
persistentvolume/pvc-df7ac3af-66d1-482e-a8ed-3b02c5a3cde6   50Gi       RWO            Delete           Bound    nbam/cfat-master-cfat-repo                                              cinder-az-nova            14d




# kubectl get volumeattachments.storage.k8s.io  | grep pvc-df7ac3af-66d1-482e-a8ed-3b02c5a3cde6
csi-95f4ef5cb2b525a243c760af9cf45f1376c487a49312733b0be2eba32bb5b334   cinder.csi.openstack.org   pvc-df7ac3af-66d1-482e-a8ed-3b02c5a3cde6   node-2003-control-03   true       4d1h
csi-ac1d7c21eb540c6aaf68494ec62a1bdddc24097e7b993bff5b7fe85355bf5402   cinder.csi.openstack.org   pvc-df7ac3af-66d1-482e-a8ed-3b02c5a3cde6   node-2003-control-02   false      4h39m
csi-cd836d5ca230a14f6746468f1e5c51680fb45c482df816d561e40c302c366680   cinder.csi.openstack.org   pvc-df7ac3af-66d1-482e-a8ed-3b02c5a3cde6   node-2003-control-01   false      4d


---------------- On node-2003-control-03 volume couldn't detach:


# kubectl describe volumeattachments.storage.k8s.io  csi-95f4ef5cb2b525a243c760af9cf45f1376c487a49312733b0be2eba32bb5b334

Name:         csi-95f4ef5cb2b525a243c760af9cf45f1376c487a49312733b0be2eba32bb5b334
Namespace:    
Labels:       <none>
Annotations:  csi.alpha.kubernetes.io/node-id: c085eedb-6846-4a33-a787-dfa183a7f213
API Version:  storage.k8s.io/v1
Kind:         VolumeAttachment
Metadata:
  Creation Timestamp:             2020-06-29T12:32:20Z
  Deletion Grace Period Seconds:  0
  Deletion Timestamp:             2020-06-29T12:35:37Z
  Finalizers:
    external-attacher/cinder-csi-openstack-org
  Resource Version:  6817146
  Self Link:         /apis/storage.k8s.io/v1/volumeattachments/csi-95f4ef5cb2b525a243c760af9cf45f1376c487a49312733b0be2eba32bb5b334
  UID:               9f0ba5f2-470f-4b4f-8077-13198dbc09c8
Spec:
  Attacher:   cinder.csi.openstack.org
  Node Name:  node-2003-control-03
  Source:
    Persistent Volume Name:  pvc-df7ac3af-66d1-482e-a8ed-3b02c5a3cde6
Status:
  Attached:  true
  Attachment Metadata:
    Device Path:  /dev/vdg
  Detach Error:
    Message:  rpc error: code = Internal desc = ControllerUnpublishVolume Detach Volume failed with error can not detach volume pvc-df7ac3af-66d1-482e-a8ed-3b02c5a3cde6, its status is detaching
    Time:     2020-07-03T13:45:23Z
Events:       <none>





---------------- On node-2003-control-01 & node-2003-control-01 volume couldn't attach , as:

#1

# kubectl describe volumeattachments.storage.k8s.io  csi-ac1d7c21eb540c6aaf68494ec62a1bdddc24097e7b993bff5b7fe85355bf5402
Name:         csi-ac1d7c21eb540c6aaf68494ec62a1bdddc24097e7b993bff5b7fe85355bf5402
Namespace:    
Labels:       <none>
Annotations:  csi.alpha.kubernetes.io/node-id: 148a746e-6b1d-4afb-937c-72764ed87167
API Version:  storage.k8s.io/v1
Kind:         VolumeAttachment
Metadata:
  Creation Timestamp:             2020-07-03T09:07:41Z
  Deletion Grace Period Seconds:  0
  Deletion Timestamp:             2020-07-03T09:35:29Z
  Finalizers:
    external-attacher/cinder-csi-openstack-org
  Resource Version:  6817827
  Self Link:         /apis/storage.k8s.io/v1/volumeattachments/csi-ac1d7c21eb540c6aaf68494ec62a1bdddc24097e7b993bff5b7fe85355bf5402
  UID:               38428ed2-6467-4903-a3ee-dee8372a9832
Spec:
  Attacher:   cinder.csi.openstack.org
  Node Name:  node-2003-control-02
  Source:
    Persistent Volume Name:  pvc-df7ac3af-66d1-482e-a8ed-3b02c5a3cde6
Status:
  Attach Error:
    Message:  rpc error: code = Internal desc = ControllerPublishVolume Attach Volume failed with error disk 98278513-ec99-4b2c-85e7-38fbb87f9e0a is attached to a different instance (c085eedb-6846-4a33-a787-dfa183a7f213)
    Time:     2020-07-03T09:32:38Z
  Attached:   false
  Detach Error:
    Message:  rpc error: code = Internal desc = ControllerUnpublishVolume Detach Volume failed with error can not detach volume pvc-df7ac3af-66d1-482e-a8ed-3b02c5a3cde6, its status is detaching
    Time:     2020-07-03T13:46:40Z
Events:       <none>


#2

# kubectl describe volumeattachments.storage.k8s.io  csi-cd836d5ca230a14f6746468f1e5c51680fb45c482df816d561e40c302c366680
Name:         csi-cd836d5ca230a14f6746468f1e5c51680fb45c482df816d561e40c302c366680
Namespace:    
Labels:       <none>
Annotations:  csi.alpha.kubernetes.io/node-id: a6dfd879-c103-436d-bda2-3d36cf46d382
API Version:  storage.k8s.io/v1
Kind:         VolumeAttachment
Metadata:
  Creation Timestamp:             2020-06-29T13:20:14Z
  Deletion Grace Period Seconds:  0
  Deletion Timestamp:             2020-07-03T09:07:52Z
  Finalizers:
    external-attacher/cinder-csi-openstack-org
  Resource Version:  6820621
  Self Link:         /apis/storage.k8s.io/v1/volumeattachments/csi-cd836d5ca230a14f6746468f1e5c51680fb45c482df816d561e40c302c366680
  UID:               d98e4813-3566-47f7-911a-801a1c88d5f6
Spec:
  Attacher:   cinder.csi.openstack.org
  Node Name:  node-2003-control-01
  Source:
    Persistent Volume Name:  pvc-df7ac3af-66d1-482e-a8ed-3b02c5a3cde6
Status:
  Attach Error:
    Message:  rpc error: code = Internal desc = ControllerPublishVolume Attach Volume failed with error disk 98278513-ec99-4b2c-85e7-38fbb87f9e0a is attached to a different instance (c085eedb-6846-4a33-a787-dfa183a7f213)
    Time:     2020-07-03T09:06:35Z
  Attached:   false
  Detach Error:
    Message:  rpc error: code = Internal desc = ControllerUnpublishVolume Detach Volume failed with error can not detach volume pvc-df7ac3af-66d1-482e-a8ed-3b02c5a3cde6, its status is detaching
    Time:     2020-07-03T13:52:01Z
Events:       <none>

**Comment by khangfsf** [comment]
You can use cinder-csi-plugin v1.19.0 with magnum-auto-healer, it resolved this issue in my lab.

**Comment by jichenjc** [comment]
@amitbhatia1987 can you help to check whether above comment can fix your issue? Then we can close this ..

**Comment by johnyb79** [comment]
Thanks ! In my case  - to my big surprise I found a cronjob that was deleting volumes... , but next time it is not that case, I'll for sure check this out.

**Comment by balleon** [comment]
> 
> 
> Thanks ! In my case - to my big surprise I found a cronjob that was deleting volumes... , but next time it is not that case, I'll for sure check this out.

@johnyb79 Can you share it?

**Comment by lingxiankong** [comment]
see #1354

/close
