### ISSUE TITLE
[cinder-csi-plugin] Support needed for Cinder API v2

### ISSUE THREAD

**Issue by maateen** [kubernetes/cloud-provider-openstack#1059]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
> /kind bug
/kind feature

**What happened**:

Our Openstack provider provides only Cinder v1, v2 API. But it seems that cinder-csi-plugin is supporting only v3 currently.

**What you expected to happen**:

Cinder CSI plugin supports cinder v2 API. Or, at least please specify any old version of this plugin on the document which one supports v2 API.

**How to reproduce it**:

**Anything else we need to know?**:

**Environment**:
- openstack-cloud-controller-manager(or other related binary) version: latest
- OpenStack version:
- Others:

**Comment by maateen** [comment]
This issue is similar to #751 but that issue is closed already without any solution to this problem.

**Comment by jichenjc** [comment]
@maateen 
https://docs.openstack.org/api-ref/block-storage/index.html
indicated the v2 is deprecated
no reason for CSI to support it as far as I can tell
so maybe the provideres need to be updated if it's only v1/v2

**Comment by lingxiankong** [comment]
I agree with @jichenjc, we don't intend to add support for something that is deprecated.
