### ISSUE TITLE
[cinder-csi-plugin] Failed to GetOpenStackProvider: Post "https://identity.XXXX/v3/auth/tokens" net/http: TLS handshake timeout

### ISSUE THREAD

**Issue by yotsapon** [kubernetes/cloud-provider-openstack#1060]
**Is this a BUG REPORT or FEATURE REQUEST?**:
 /kind bug

**What happened**:
Trying to apply csi-cinder-controllerplugin but one of containers named "cinder-csi-plugin" is CrashLoopBackOff. I have checked logs inside it shows error below.
![image](https://user-images.githubusercontent.com/46857257/81496888-212d3b80-92e5-11ea-9b5a-cd6973e692a3.png)

**What you expected to happen**:

**How to reproduce it**:

**Anything else we need to know?**:
These are docker image version that I am applying.
image: quay.io/k8scsi/csi-attacher:v2.1.1
image: quay.io/k8scsi/csi-provisioner:v1.4.0
image: quay.io/k8scsi/csi-snapshotter:v1.2.2
image: quay.io/k8scsi/csi-resizer:v0.4.0
image: docker.io/k8scloudprovider/cinder-csi-plugin:v1.18.0
image: quay.io/k8scsi/csi-node-driver-registrar:v1.2.0
image: docker.io/k8scloudprovider/cinder-csi-plugin:v1.18.0

Cloud Config as shown in picture. This cloud config is the same one using with OCCM.
![image](https://user-images.githubusercontent.com/46857257/81496969-a9134580-92e5-11ea-899a-077e1f3303a6.png)

**Environment**:
- Kubernetes : v1.18.2
- Openstack-cloud-controller-manager version: v1.18.0

**Comment by kayrus** [comment]
@yotsapon it looks like this node has issues with network connectivity. do other nodes work fine? Can you run `curl -v %keystone_url%` from this node?

**Comment by yotsapon** [comment]
> @yotsapon it looks like this node has issues with network connectivity. do other nodes work fine? Can you run `curl -v %keystone_url%` from this node?

I have tested  the connection randomly on worker nodes to get Auth Token from https://identity.XXXX/v3/auth/tokens. It works fine.

**Comment by jichenjc** [comment]
@yotsapon have you set CA ? you are using https and I didn't see ca set

**Comment by yotsapon** [comment]
> @yotsapon have you set CA ? you are using https and I didn't see ca set
> 
> https://github.com/kubernetes/cloud-provider-openstack/blob/master/docs/using-cinder-csi-plugin.md
> check `ca-file`

Before I found this issues I upgraded K8S from v1.16.8 to v1.18.2 and it used to work before without ca-file. I also checked with the cloud provider they told that the certificates of  https://identity.XXXX/v3/auth/tokens was generated by Let's encrypted. Do I still need to add ca-file if it worked without ca-file before?

**Comment by jichenjc** [comment]
um... not sure, my env is https so I have to provide a ca file in order to communicate with openstack side 

but this is not a CSI question from my understanding, as @kayrus pointed out
 you might want to try normal openstack operation before try CSI

**Comment by Jacob310** [comment]
> @yotsapon have you set CA ? you are using https and I didn't see ca set
> 
> https://github.com/kubernetes/cloud-provider-openstack/blob/master/docs/using-cinder-csi-plugin.md
> check `ca-file`

Sorry - how do you do this?

**Comment by yotsapon** [comment]
> > @yotsapon it looks like this node has issues with network connectivity. do other nodes work fine? Can you run `curl -v %keystone_url%` from this node?
> 
> I have tested on the worker where the cinder plugin running and randomly tested on other worker nodes to get Auth Token from https://identity.XXXX/v3/auth/tokens by using curl. It works fine.

The issues was fixed now. The root cause of this problem came from some setting in proxy. Thanks for pointing out the root cause.

**Comment by phongvu0403** [comment]
@yotsapon Hi, can I ask you a question? I am facing this problem with Kubernetes version 1.19.9. I provisioned my cluster using Kubespray. What setting did you change in proxy? Thank you!

**Comment by phongvu0403** [comment]
I also use cinder-csi-plugin with Kubernetes version 1.20.7. That is fine. I don't know how to make it work with Kubernetes version 1.19.9

**Comment by phongvu0403** [comment]
@jichenjc Can you give me a clue? Thanks in advance!
