### ISSUE TITLE
[cinder-csi-plugin] req.GetVolumePath() is used for device path

### ISSUE THREAD

**Issue by mape90** [kubernetes/cloud-provider-openstack#1065]
**What happened**:
In nodeserver.go NodeGetVolumeStats() and NodeExpandVolume() functions use req.GetVolumePath() for finding path of device. This should never be trusted as only the node can know actual device path.

This can cause situations where device given by this do not exists or is totally different device.

**What you expected to happen**:
Those functions should query actual device using function
devicePath, err := getDevicePath(volumeID,  ns.Mount)

**How to reproduce it**:
**Anything else we need to know?**:

 /kind bug

**Comment by jichenjc** [comment]
@mape90 do we know how it will impact end user ? just to get some further understanding about the impact...thanks

**Comment by mape90** [comment]
Impact for end user is that eventually volume paths given by cinder and actually present on node will be different. In lucky case those resize and stats will just fail. In worst case those actions will be done to random volumes. 

For example user1 wants to resize its volume1. However node has placed volume2 owned by user2 to the path that is present in volume1 volumeattachment information. So now nodeserver will try to resize volume2 instead of volume1.

The problem is that req.GetVolumePath() gives the path that is generated by Cinder when it attaches volume to node. However this do not always map to what device kernel will select.

So you may end up situation where
Cinder thinks volume mappings are
Vol1 == /dev/vdb
Vol2 == /dev/vdc
Vol3 == /dev/vdd
However actually they are:
Vol1 == /dev/vdb
Vol2 == /dev/vdd
Vol3 == /dev/vdc

So vol2 and Vol3 are now swapped and if that device path is trusted then all actions will be also swapped. Usually what happens is that kernel "skips" one character. However later when new device is attached then it might get this "skipped" path and now cinder paths are pointing to wrong volumes.

This issue has been in CInder CSI previously at attaching. Where mounting was done by trusting the device path. What then caused volumes to be attached to wrong pods or attaching failed as Cinder CSI wasn't able to find the device as kernel has named it differently.

**Comment by ramineni** [comment]
@mape90 This issue is addressed in csi long time back by getting the device path explicitly and not trusting the path given by cinder, https://github.com/kubernetes/cloud-provider-openstack/blob/master/pkg/csi/cinder/nodeserver.go#L363 , NodeExpandVolume is called using the path where the volume is staged, so it should get right path . Are you facing any issue / error ?

**Comment by mape90** [comment]
Yes other parts are doing it correctly and not trusing the path. However NodeExpandVolume is called by kubelet and it gets its info from volumeattachment that has the incorrect path as that info was given by attacher who has no way of knowing the actual path as it is running on different node.

I can try to generate the issue, but I need to figure out how to easily get path on node and nova to be different. As this is generally only visible in real environments where multiple applications managed same time and volumes are attached and detached about same time.

**Comment by jichenjc** [comment]
ok, thanks for the detailed info , I think I knew the question you mentioned, I knew this cinder issue before and that's the reason why nova ignore the /dev/xxxx, we should use real device instead of anything from cinder/nova side

**Comment by jichenjc** [comment]
/assign

let me give a try

**Comment by ramineni** [comment]
@jichenjc First, if you could reproduce the issue would be good. From the spec , I see that NodeExpandVolume is called using the path where the volume is staged/published, so we can understand better from where it is getting the path.

**Comment by jichenjc** [comment]
yes, what I plan to do is use /dev/sdz to attach (maybe do some hacking) as well and see what happened there... thanks for the reminder

**Comment by jichenjc** [comment]
@ramineni I tried to reproduce but failed 
then I searched the web find many issues there 
so we should avoid using the volume from cinder anytime ,which means this is a valid issue that many folks had before..

https://github.com/openshift/openshift-ansible/issues/12060
https://github.com/kubernetes/kubernetes/issues/33128

**Comment by ramineni** [comment]
@jichenjc Have you tried specifically or ExpandVolume usecase ? because others will work fine as its already fixed as I mentioned before https://github.com/kubernetes/cloud-provider-openstack/blob/master/pkg/csi/cinder/nodeserver.go#L363

**Comment by jichenjc** [comment]
yes, I knew this , because of my local env is corrupt for expand (can't expand and don't know why)
so I can't test the expand feature , not sure how to test using NodeGetVolumeStats?

**Comment by jichenjc** [comment]
and I guess if I can find a way to find volume stats here
https://github.com/kubernetes/cloud-provider-openstack/issues/1064
then I can also test this

**Comment by jichenjc** [comment]
```
 nodeserver.go:511] NodeExpandVolume: called with args {VolumeId:64e5369c-51f1-4a8a-8e9b-47de293f817f VolumePath:/var/lib/kubelet/pods/10654bb5-e5d2-487f-bbea-b42fc149f5a5/volumes/kubernetes.io~csi/pvc-11fce7dc-e465-41da-95f1-d8a1268fe474/mount CapacityRange:required_bytes:2147483648  StagingTargetPath:/var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-11fce7dc-e465-41da-95f1-d8a1268fe474/globalmount VolumeCapability:mount:<fs_type:"ext4" > access_mode:<mode:SINGLE_NODE_WRITER >  XXX_NoUnkeyedLiteral:{} XXX_unrecognized:[] XXX_sizecache:0}
```

```
/dev/vdd on /var/lib/kubelet/pods/10654bb5-e5d2-487f-bbea-b42fc149f5a5/volumes/kubernetes.io~csi/pvc-11fce7dc-e465-41da-95f1-d8a1268fe474/mount type ext4 (rw,relatime,data=ordered)

```

so we are using mount path directly instead of using /dev/vdx ... @mape90 @ramineni 
if you agree I think we can close this issue as the path is from mount place directly from my test

**Comment by jichenjc** [comment]
/close

per above comments, if you have question and different suggestion, feel free to reopen
