### ISSUE TITLE
[cinder-csi-plugin] [manila-csi-plugin] Release helm charts

### ISSUE THREAD

**Issue by strigazi** [kubernetes/cloud-provider-openstack#1066]
Will the two charts be released in a repository?
I think the best option is github package like ingress-nginx. I am not sure how compatible is with this git repo that has many components.

https://github.com/kubernetes/ingress-nginx/tree/master/charts/ingress-nginx#tldr

/kind feature

**Comment by atsai1220** [comment]
I can't for the life of me figure out the correct path to give my App Catalog for this Helm Chart. The chart is referenced here: https://github.com/kubernetes/cloud-provider-openstack/blob/master/docs/using-cinder-csi-plugin.md#deploy

**Comment by lingxiankong** [comment]
@tomaaron Hi Tom, do you something about this?

**Comment by lingxiankong** [comment]
Just found @brtknr already proposed a PR https://github.com/kubernetes/cloud-provider-openstack/pull/1067 for this
