### ISSUE TITLE
[occm] cloud-init?

### ISSUE THREAD

**Issue by ivomarino** [kubernetes/cloud-provider-openstack#1072]
/kind feature

a generic question regarding `openstack-cloud-controller-manager`, I currently use it to scale new nodes on OpenStack, all fine so far. I was wondering how it would be possible to specify the `cloud-init` to be used when creating the VM, the one that then creates `/etc/cloud/cloud.cfg`. Thanks in advance for any feedback.

**Comment by lingxiankong** [comment]
Hi @ivomarino, what do you mean by 'scale new nodes on OpenStack using OCCM'? Could you please describe more about your use case so that we could understand better for your requirements? Thanks.

**Comment by ivomarino** [comment]
hi @lingxiankong, what I need to do is to specify which `cloud-config` should be used for the new spawned worker node, the `cloud-config` in OpenStack that generates `/etc/cloud/cloud.cfg`. I basically need to run `apt-get install ...` to install salt minion when the node has been created and boots up for the first time (before joining the K8s cluster). Or I need to be able to trigger a one-liner like that via `ssh` once the worker node has been created. Thanks;)

**Comment by lingxiankong** [comment]
Hi @ivomarino , I don't think OCCM is responsible for creating Nova VMs (or injecting user data via cloudinit), it only gets the VM information before configuring the Kubernetes worker nodes.

**Comment by ivomarino** [comment]
@lingxiankong thans for this info so far;) think we can close this then. P.S. do you know if it's possible to trigger an event (or command) after a new node has been added to K8s? thanks

**Comment by lingxiankong** [comment]
@ivomarino it depends on how the worker node is added to the cluster and if you could control that.

**Comment by ivomarino** [comment]
@lingxiankong via webhook call to the OpenStack API as far as I know

**Comment by lingxiankong** [comment]
> @lingxiankong via webhook call to the OpenStack API as far as I know

So you can pass the user data when creating Nova VM.

**Comment by ivomarino** [comment]
@lingxiankong oks, but K8s needs to do that in some way, right?
