### ISSUE TITLE
[occm] Add annotation to allow for selecting of a LoadBalancer in case of multiple LoadBalancers within the same cluster

### ISSUE THREAD

**Issue by jeff-hillman** [kubernetes/cloud-provider-openstack#1074]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
> /kind bug

/kind feature

**What happened**:
RE: Kubernetes issue [91306](https://github.com/kubernetes/kubernetes/issues/91306)

In the case of having multiple LoadBalancer in the same cluster (OCCM and MetalLB), when a Service type LoadBalancer is requested (or a service exposed as that type), both LBs will try to satisfy the request.  Even setting OCCM specific annotations, such as service.beta.kubernetes.io/openstack-internal-load-balancer, does not single out a specific LB.

Per the k8s team, it is suggested that the LBs provide a specific annotation or label that will allow them to be specified in the service, so that a choice can be made between them.

A similar bug will be filed for MetalLB.

**What you expected to happen**:
An annotation or label or some other mechanism that allows one to select or specify the LoadBalancer to be used for the Service.

**How to reproduce it**:
Deploy charmed Kubernetes inside of Openstack Train with Octavia enabled and configured. Deploy Openstack Integrator into the same model and relate it to kubernetes master with loadbalancer relation. This will automatically install openstack-controller-manager for LoadBalancer requests.

Install MetalLB 0.9.3 via manifest following installation guide on MetalLB site.

Deploy a POD and either expose it as type LoadBalancer or create a service in the manifest.

**Anything else we need to know?**:

**Environment**:
- openstack-cloud-controller-manager(or other related binary) version: v1.15.0
- OpenStack version: Train
- Others: MetalLB 0.9.3

**Comment by lingxiankong** [comment]
Hi @jeff-hillman , i'm wondering why you need to run multiple loadbalancer controllers for a single cluster?
