### ISSUE TITLE
Document what languages plugins can be written in

### ISSUE THREAD

**Issue by flaper87** [kubernetes/cloud-provider-openstack#108]
This issue is to discuss (and then document) our willingness to host plugins that are written in other programming languages.

There are cases when using a different programming language would make the implementation cleaner, simple and more stable. An example of this can be found in the following discussion related to the CSI plugin: https://github.com/kubernetes/cloud-provider-openstack/issues/95#issuecomment-380024052

- Is it ok for us to host/test code that is not Go?
- Would the current members and reviewers feel comfortable with maintaining such code?
- Can we provide testing pipelines for such code?

Starting this issue to have a broader discussion on this topic. I'll make sure to document the consensus.

**Comment by j-griffith** [comment]
@flaper87 My only concern here is mixing code and therefore models could be a bit confusing.  I added some comments here #95 

It seems to me that if we want to use the brick extension we could just use a client container with an attach entrypoint and call the attach from the node server.  At least for now this seems like the fastest/easiest path to implementing this.  Even if it's a temporary stop-gap and it means we don't have to add any python code or anything.

So we'd just add a client container and execute against it directly from the nodesever.
