### ISSUE TITLE
Wrong help documentation

### ISSUE THREAD

**Issue by wyyxd2017** [kubernetes/cloud-provider-openstack#1083]
#Wrong help documentation
https://github.com/kubernetes/cloud-provider-openstack/blob/master/docs/getting-started-provider-dev.md#docker
how to run Docker v1.12,the url https://yum.dockerproject.org/repo/main/centos/7 is invalid

**Comment by ramineni** [comment]
@wxyxd2017 Document seems outdated, Docker 1.12 is old , you could follow the instructions from here , https://kubernetes.io/docs/setup/production-environment/container-runtimes/#docker

Thanks for reporting, we will get the document updated soon here .
