### ISSUE TITLE
csi-cinder-driver v1.18 release deploy failed

### ISSUE THREAD

**Issue by jianglingxia** [kubernetes/cloud-provider-openstack#1085]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
> /kind bug
> /kind feature

**What happened**:
i deploy the csi-cinder-driver in k8s v1.17.4, 
used the  yaml in website
https://github.com/kubernetes/cloud-provider-openstack/tree/release-1.18/manifests/cinder-csi-plugin

but the controller plugin has one container can not run,the logs cinder-plugin is 

I0602 11:00:22.577796       1 openstack.go:236] TenantName:
I0602 11:00:22.577801       1 openstack.go:237] TrustID:
I0602 11:00:22.577807       1 openstack.go:238] DomainID:
I0602 11:00:22.577812       1 openstack.go:239] DomainName:
I0602 11:00:22.577818       1 openstack.go:240] TenantDomainID:
I0602 11:00:22.577824       1 openstack.go:241] TenantDomainName:
I0602 11:00:22.577830       1 openstack.go:242] UserDomainID:
I0602 11:00:22.577836       1 openstack.go:243] UserDomainName:
I0602 11:00:22.577842       1 openstack.go:244] Region:
I0602 11:00:22.577848       1 openstack.go:245] CAFile:
I0602 11:00:22.577859       1 openstack.go:246] UseClouds: false
I0602 11:00:22.577867       1 openstack.go:247] CloudsFile:
I0602 11:00:22.577874       1 openstack.go:248] Cloud:
I0602 11:00:22.577881       1 openstack.go:249] ApplicationCredentialID:
I0602 11:00:22.577888       1 openstack.go:250] ApplicationCredentialName:
I0602 11:00:22.577892       1 openstack.go:88] Block storage opts: {0 false}
I0602 11:00:22.577990       1 openstack.go:497] Using user-agent cinder-csi-plugin/v1.18.0 gophercloud/2.0.0

can anyone help?

**What you expected to happen**:

**How to reproduce it**:

**Anything else we need to know?**:

**Environment**:
- openstack-cloud-controller-manager(or other related binary) version:
- OpenStack version:
- Others:

**Comment by jianglingxia** [comment]
@ramineni  thanks

**Comment by ramineni** [comment]
@jianglingxia Is the secret updated with your env cloud-config file? 
https://github.com/kubernetes/cloud-provider-openstack/blob/release-1.18/manifests/cinder-csi-plugin/csi-secret-cinderplugin.yaml

**Comment by jianglingxia** [comment]
yes,
the cloud.conf content is like this

[Global]
username=admin
password=aopc
auth-url=https://1.1.11.1:5000/v2.0/
tenant-id=70267e8daaa54baa8a68a765a85b6d38


[Metadata]
search-order=configDrive,metadataService

then i base64 it and used the result to replace the secrt.yaml and create the secret
base64 -w 0 cloud.conf

my step is :
1)create the secret 
cloud-config                                     Opaque                                1      167m
2) create the rbac
3) create the controller plugin

[root@paas-controller-3:/home/ubuntu/cinder-csi]$ kubectl get po -n kube-system -o wide -w                              
NAME                                READY   STATUS             RESTARTS   AGE     IP           NODE         NOMINATED NODE   READINESS GATES
coredns-f589df4f5-w5vln             1/1     Running            0          3d19h   172.30.0.2   188.1.1.11   <none>           <none>
csi-cinder-controllerplugin-0       4/5     CrashLoopBackOff   27         117m    172.30.0.6   188.1.1.8 

only one container can not run,but other container log is 
like the attacher log is  the container running but the logs print that ,is normal?
[root@paas-controller-3:/home/ubuntu/cinder-csi]$ tail -f /paasdata/op-log/csi-cinder/cinder_sts_csi-attacher.log 
W0602 12:35:10.161460       1 connection.go:172] Still connecting to unix:///var/lib/csi/sockets/pluginproxy/csi.sock
W0602 12:35:20.157790       1 connection.go:172] Still connecting to unix:///var/lib/csi/sockets/pluginproxy/csi.sock
W0602 12:35:30.157783       1 connection.go:172] Still connecting to unix:///var/lib/csi/sockets/pluginproxy/csi.sock
W0602 12:35:40.157804       1 connection.go:172] Still connecting to unix:///var/lib/csi/sockets/pluginproxy/csi.sock
W0602 12:35:50.157789       1 connection.go:172] Still connecting to unix:///var/lib/csi/sockets/pluginproxy/csi.sock
W0602 12:36:00.157989       1 connection.go:172] Still connecting to unix:///var/lib/csi/sockets/pluginproxy/csi.sock
W0602 12:36:10.157781       1 connection.go:172] Still connecting to unix:///var/lib/csi/sockets/pluginproxy/csi.sock
W0602 12:36:20.157781       1 connection.go:172] Still connecting to unix:///var/lib/csi/sockets/pluginproxy/csi.sock
W0602 12:36:30.157906       1 connection.go:172] Still connecting to unix:///var/lib/csi/sockets/pluginproxy/csi.sock
W0602 12:36:40.158496       1 connection.go:172] Still connecting to unix:///var/lib/csi/sockets/pluginproxy/csi.sock

the provisioner is 
[root@paas-controller-3:/home/ubuntu/cinder-csi]$ tail -f /paasdata/op-log/csi-cinder/cinder_sts_csi-provisioner.log 
W0602 12:37:13.860136       1 connection.go:170] Still connecting to unix:///var/lib/csi/sockets/pluginproxy/csi.sock
W0602 12:37:23.860130       1 connection.go:170] Still connecting to unix:///var/lib/csi/sockets/pluginproxy/csi.sock
W0602 12:37:33.860156       1 connection.go:170] Still connecting to unix:///var/lib/csi/sockets/pluginproxy/csi.sock
W0602 12:37:43.860122       1 connection.go:170] Still connecting to unix:///var/lib/csi/sockets/pluginproxy/csi.sock
W0602 12:37:53.860136       1 connection.go:170] Still connecting to unix:///var/lib/csi/sockets/pluginproxy/csi.sock
W0602 12:38:03.860114       1 connection.go:170] Still connecting to unix:///var/lib/csi/sockets/pluginproxy/csi.sock
proxy/csi.sock
W0602 12:37:43.860122       1 connection.go:170] Still connecting to unix:///var/lib/csi/sockets/pluginproxy/csi.sock
W0602 12:37:53.860136       1 connection.go:170] Still connecting to unix:///var/lib/csi/sockets/pluginproxy/csi.sock
W0602 12:38:03.860114       1 connection.go:170] Still connecting to unix:///var/lib/csi/sockets/pluginproxy/csi.sock

**Comment by ramineni** [comment]
@jianglingxia Could you share o/p of kubectl describe pod csi-cinder-controllerplugin-0 and also logs of cinder-csi-plugin container

**Comment by jianglingxia** [comment]
ok.

[root@paas-controller-3:/home/ubuntu/cinder-csi]$ kubectl describe pod csi-cinder-controllerplugin-0 -n kube-system
Name:         csi-cinder-controllerplugin-0
Namespace:    kube-system
Priority:     0
Node:         188.1.1.8/188.1.1.8
Start Time:   Tue, 02 Jun 2020 14:05:07 +0800
Labels:       app=csi-cinder-controllerplugin
              controller-revision-hash=csi-cinder-controllerplugin-557cd76fc
              statefulset.kubernetes.io/pod-name=csi-cinder-controllerplugin-0
Status:       Running
IP:           172.30.0.7
IPs:
  IP:           172.30.0.7
Controlled By:  StatefulSet/csi-cinder-controllerplugin
Containers:
  csi-attacher:
    Container ID:  docker://f885530775031d3ec61075ea9f5e8c2fdc175fe55b5eab6d35e0c54c088af62f
    Image:         quay.io/k8scsi/csi-attacher:v2.1.1
    Image ID:      docker://sha256:b5c006a0055658f28d0643a1636f725cf2c982fc47bf64d6cdaddefbda6857c7
    Port:          <none>
    Host Port:     <none>
    Args:
      --csi-address=$(ADDRESS)
      --timeout=3m
    State:          Running
      Started:      Tue, 02 Jun 2020 14:05:54 +0800
    Ready:          True
    Restart Count:  0
    Environment:
      ADDRESS:  /var/lib/csi/sockets/pluginproxy/csi.sock
    Mounts:
      /var/lib/csi/sockets/pluginproxy/ from socket-dir (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from csi-cinder-controller-sa-token-4k72l (ro)
  csi-provisioner:
    Container ID:  docker://7034621de3b8952f4295e9f6a152f228ada339f760bfad6d89b402d8da0f6f46
    Image:         quay.io/k8scsi/csi-provisioner:v1.4.0
    Image ID:      docker://sha256:2130c4e026a538046333e953b06743a8a9a74e1b5fec5c5cdde0e1ddc03bd4a4
    Port:          <none>
    Host Port:     <none>
    Args:
      --csi-address=$(ADDRESS)
      --timeout=3m
    State:          Running
      Started:      Tue, 02 Jun 2020 14:05:54 +0800
    Ready:          True
    Restart Count:  0
    Environment:
      ADDRESS:  /var/lib/csi/sockets/pluginproxy/csi.sock
    Mounts:
      /var/lib/csi/sockets/pluginproxy/ from socket-dir (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from csi-cinder-controller-sa-token-4k72l (ro)
  csi-snapshotter:
    Container ID:  docker://3dfbfec944ed274892c324333263f010151ff9adb3d7c610ca2ba4f11c799235
    Image:         quay.io/k8scsi/csi-snapshotter:v1.2.2
    Image ID:      docker://sha256:538dbe77c2f97c4087bb777ac3bb5661fcd010cda9db854dd1e868c5ee6683ad
    Port:          <none>
    Host Port:     <none>
    Args:
      --csi-address=$(ADDRESS)
    State:          Running
      Started:      Tue, 02 Jun 2020 14:05:56 +0800
    Ready:          True
    Restart Count:  0
    Environment:
      ADDRESS:  /var/lib/csi/sockets/pluginproxy/csi.sock
    Mounts:
      /var/lib/csi/sockets/pluginproxy/ from socket-dir (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from csi-cinder-controller-sa-token-4k72l (ro)
  csi-resizer:
    Container ID:  docker://3d5a15c6aa45b838b6b5ba1d255b77792873aa3bd80a4c0596e115986f53a25a
    Image:         quay.io/k8scsi/csi-resizer:v0.4.0
    Image ID:      docker://sha256:b9520a8f4c9f73d6d6c62010a26afc33eff4fb0d196a74ad152c941bdb6e5b56
    Port:          <none>
    Host Port:     <none>
    Args:
      --csi-address=$(ADDRESS)
    State:          Running
      Started:      Tue, 02 Jun 2020 14:05:57 +0800
    Ready:          True
    Restart Count:  0
    Environment:
      ADDRESS:  /var/lib/csi/sockets/pluginproxy/csi.sock
    Mounts:
      /var/lib/csi/sockets/pluginproxy/ from socket-dir (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from csi-cinder-controller-sa-token-4k72l (ro)
  cinder-csi-plugin:
    Container ID:  docker://c1d2949948585e336cff4e79d598277fef082247dc89de770ee1edf0118f7f72
    Image:         docker.io/k8scloudprovider/cinder-csi-plugin:v1.18.0
    Image ID:      docker://sha256:952ed3f9ebc9168ca6e1d746f1c5c775f074634c6e88c386be80cd615dd712d9
    Port:          <none>
    Host Port:     <none>
    Args:
      /bin/cinder-csi-plugin
      --nodeid=$(NODE_ID)
      --endpoint=$(CSI_ENDPOINT)
      --cloud-config=$(CLOUD_CONFIG)
      --cluster=$(CLUSTER_NAME)
    State:          Terminated
      Reason:       Completed
      Exit Code:    0
      Started:      Tue, 02 Jun 2020 14:06:46 +0800
      Finished:     Tue, 02 Jun 2020 14:06:46 +0800
    Last State:     Terminated
      Reason:       Completed
      Exit Code:    0
      Started:      Tue, 02 Jun 2020 14:06:15 +0800
      Finished:     Tue, 02 Jun 2020 14:06:16 +0800
    Ready:          False
    Restart Count:  3
    Environment:
      NODE_ID:        (v1:spec.nodeName)
      CSI_ENDPOINT:  unix://csi/csi.sock
      CLOUD_CONFIG:  /etc/config/cloud.conf
      CLUSTER_NAME:  kubernetes
    Mounts:
      /csi from socket-dir (rw)
      /etc/config from secret-cinderplugin (ro)
      /var/run/secrets/kubernetes.io/serviceaccount from csi-cinder-controller-sa-token-4k72l (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             False 
  ContainersReady   False 
  PodScheduled      True 
Volumes:
  socket-dir:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:     
    SizeLimit:  <unset>
  secret-cinderplugin:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  cloud-config
    Optional:    false
  csi-cinder-controller-sa-token-4k72l:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  csi-cinder-controller-sa-token-4k72l
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason     Age               From                Message
  ----     ------     ----              ----                -------
  Normal   Scheduled  105s              default-scheduler   Successfully assigned kube-system/csi-cinder-controllerplugin-0 to 188.1.1.8
  Normal   Pulled     59s               kubelet, 188.1.1.8  Container image "quay.io/k8scsi/csi-attacher:v2.1.1" already present on machine
  Normal   Created    59s               kubelet, 188.1.1.8  Created container csi-attacher
  Normal   Started    58s               kubelet, 188.1.1.8  Started container csi-attacher
  Normal   Pulled     58s               kubelet, 188.1.1.8  Container image "quay.io/k8scsi/csi-provisioner:v1.4.0" already present on machine
  Normal   Created    58s               kubelet, 188.1.1.8  Created container csi-provisioner
  Normal   Started    57s               kubelet, 188.1.1.8  Started container csi-provisioner
  Normal   Pulled     57s               kubelet, 188.1.1.8  Container image "quay.io/k8scsi/csi-snapshotter:v1.2.2" already present on machine
  Normal   Pulled     56s               kubelet, 188.1.1.8  Container image "quay.io/k8scsi/csi-resizer:v0.4.0" already present on machine
  Normal   Started    56s               kubelet, 188.1.1.8  Started container csi-snapshotter
  Normal   Created    56s               kubelet, 188.1.1.8  Created container csi-snapshotter
  Normal   Created    55s               kubelet, 188.1.1.8  Created container csi-resizer
  Normal   Started    54s               kubelet, 188.1.1.8  Started container csi-resizer
  Normal   Pulled     54s               kubelet, 188.1.1.8  Container image "docker.io/k8scloudprovider/cinder-csi-plugin:v1.18.0" already present on machine
  Normal   Created    6s (x4 over 54s)  kubelet, 188.1.1.8  Created container cinder-csi-plugin
  Normal   Started    6s (x4 over 53s)  kubelet, 188.1.1.8  Started container cinder-csi-plugin
  Warning  BackOff    4s (x5 over 50s)  kubelet, 188.1.1.8  Back-off restarting failed container



and the logs

[root@paas-controller-3:/home/ubuntu/cinder-csi]$ docker ps -a |grep csi-cinder-controllerplugin-0
6ee4f298b7bc        952ed3f9ebc9                                                                                   "/bin/cinder-csi-p..."   About a minute ago   Exited (0) About a minute ago   


[root@paas-controller-3:/home/ubuntu/cinder-csi]$ docker logs 7881e517692b
I0602 06:09:08.613557       1 driver.go:57] Driver: cinder.csi.openstack.org version: 1.2.0
I0602 06:09:08.613628       1 driver.go:91] Enabling controller service capability: LIST_VOLUMES
I0602 06:09:08.613638       1 driver.go:91] Enabling controller service capability: CREATE_DELETE_VOLUME
I0602 06:09:08.613644       1 driver.go:91] Enabling controller service capability: PUBLISH_UNPUBLISH_VOLUME
I0602 06:09:08.614041       1 driver.go:91] Enabling controller service capability: CREATE_DELETE_SNAPSHOT
I0602 06:09:08.614058       1 driver.go:91] Enabling controller service capability: LIST_SNAPSHOTS
I0602 06:09:08.614069       1 driver.go:91] Enabling controller service capability: EXPAND_VOLUME
I0602 06:09:08.614074       1 driver.go:91] Enabling controller service capability: CLONE_VOLUME
I0602 06:09:08.614084       1 driver.go:103] Enabling volume access mode: SINGLE_NODE_WRITER
I0602 06:09:08.614099       1 driver.go:113] Enabling node service capability: STAGE_UNSTAGE_VOLUME
I0602 06:09:08.614106       1 driver.go:113] Enabling node service capability: EXPAND_VOLUME
I0602 06:09:08.614758       1 openstack.go:88] Block storage opts: {0 false}
W0602 06:09:08.923171       1 main.go:121] Failed to GetOpenStackProvider: Post "https://1.1.15.1:5000/v2.0/tokens": x509: certificate signed by unknown authority

**Comment by ramineni** [comment]
>> Failed to GetOpenStackProvider: Post "https://1.1.15.1:5000/v2.0/tokens": x509: certificate signed by unknown authority

Looks to me as cert issues while connecting to openstack . `ca-file` parameter needs to updated here?  https://github.com/kubernetes/cloud-provider-openstack/blob/master/docs/using-openstack-cloud-controller-manager.md#global

you need to check , if able to connect to openstack from the node 188.1.1.8 ? using curl may be

**Comment by jianglingxia** [comment]
i modify the code and make cinder-csi-plugin but i donot know how to build images?can you help me ? i found the code not provider the dockerfile,thanks 
[root@LIN-FE325E0FEA1 cloud-provider-openstack]# make cinder-csi-plugin
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
CGO_ENABLED=0 GOOS=linux go build \
	-ldflags "-w -s -X 'k8s.io/cloud-provider-openstack/pkg/version.Version='" \
	-o cinder-csi-plugin \
	cmd/cinder-csi-plugin/main.go
go: downloading github.com/cespare/xxhash v1.1.0
go: extracting github.com/cespare/xxhash v1.1.0

**Comment by ramineni** [comment]
@jianglingxia you could refer document here , https://github.com/kubernetes/cloud-provider-openstack/blob/master/docs/getting-started-provider-dev.md#only-build-image

`make image-cinder-csi-plugin` will build the image

**Comment by jianglingxia** [comment]
really thanks,and find the docs
but i exec the step  the log print :provide a source image with `from` prior to commit?

[root@LIN-FE325E0FEA1 cloud-provider-openstack]# export ARCH=amd64
[root@LIN-FE325E0FEA1 cloud-provider-openstack]# 
[root@LIN-FE325E0FEA1 cloud-provider-openstack]# 
[root@LIN-FE325E0FEA1 cloud-provider-openstack]# make image-cinder-csi-plugin

Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).

Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
make build-cmd-cinder-csi-plugin
make[1]: Entering directory '/media/B/allcode/cinder-csi-1.18.0/src/k8s.io/cloud-provider-openstack'

Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
CGO_ENABLED=0 GOOS=linux go build \
	-ldflags "-w -s -X 'k8s.io/cloud-provider-openstack/pkg/version.Version='" \
	-o cinder-csi-plugin \
	cmd/cinder-csi-plugin/main.go
CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build \
	-ldflags "-w -s -X 'k8s.io/cloud-provider-openstack/pkg/version.Version='" \
	-o cinder-csi-plugin-amd64 \
	cmd/cinder-csi-plugin/main.go
make[1]: Leaving directory '/media/B/allcode/cinder-csi-1.18.0/src/k8s.io/cloud-provider-openstack'
cp -r cluster/images/cinder-csi-plugin /tmp/tmp.JJuvfL1lu5
cp cinder-csi-plugin-amd64 /tmp/tmp.JJuvfL1lu5/cinder-csi-plugin
docker build --build-arg ALPINE_ARCH=amd64 --build-arg ARCH=amd64 --build-arg DEBIAN_ARCH=amd64 --pull -t build-cinder-csi-plugin-amd64 -f /tmp/tmp.JJuvfL1lu5/cinder-csi-plugin/Dockerfile.build /tmp/tmp.JJuvfL1lu5/cinder-csi-plugin
Sending build context to Docker daemon 31.66 MB
Step 1/5 : ARG DEBIAN_ARCH=amd64
Please provide a source image with `from` prior to commit
Makefile:248: recipe for target 'image-cinder-csi-plugin' failed
make: *** [image-cinder-csi-plugin] Error 1

**Comment by jianglingxia** [comment]
i find the web the reason,someone said that the problem is docker version is tow low

need use docker 17.05.0-ce (2017-05-04) my docker version id 17.03.2-ce，
 Allow using build-time args (ARG) in FROM #31352 
is right? you occure the problem?

**Comment by ramineni** [comment]
@jianglingxia FROM is specified already here https://github.com/kubernetes/cloud-provider-openstack/blob/master/cluster/images/cinder-csi-plugin/Dockerfile#L16 , so it should be able to download. You could try updating docker version and check.
Recommended docker versions are listed here , https://kubernetes.io/docs/setup/production-environment/container-runtimes/#docker

**Comment by ramineni** [comment]
@jianglingxia can we close this bug? looks like this is env issue.

**Comment by jianglingxia** [comment]
yeah,resoved thanks
