### ISSUE TITLE
Consider building with docker multi-stage build

### ISSUE THREAD

**Issue by sbueringer** [kubernetes/cloud-provider-openstack#1089]
**Is this a or FEATURE REQUEST?**:

/kind feature

**What happened**:
I saw in other upstream Kubernetes repositories that often the go build is executed via Docker multi-stage build (example [cluster-api-provider-openstack](https://github.com/kubernetes-sigs/cluster-api-provider-openstack/blob/master/Dockerfile)). cloud-provider-openstack uses a local `go build` which uses the currently available Go version.

**What you expected to happen**:
I would have thought that multi-stage build is also used in cloud-provider-openstack

I think it's better to build with a well-defined golang version so it's clear with which version 
the cloud-provider-openstack is build. Currently it depends on the local Go version of whoever 
is building the image. Just an suggestion, wdyt?

**Comment by jichenjc** [comment]
+1 on the suggestion :)

**Comment by jichenjc** [comment]
/assign

let me try this ..
