### ISSUE TITLE
[manila-csi-plugin] how to install CSI Manila driver

### ISSUE THREAD

**Issue by lw8008** [kubernetes/cloud-provider-openstack#1090]
Hi Team,

It's a general question.
As far as i know, if we use Manila driver, we should have auth file to connect openstack with certain region and tenant.

in your install guide https://github.com/kubernetes/cloud-provider-openstack/blob/master/docs/using-manila-csi-plugin.md
It mentioned about those in "Secrets, authentication" section, but i can't find which yaml file i can fill in?

Could you pls guide me?

Thanks
Adam

**Comment by gman0** [comment]
Hi Adam, sourcing OpenStack credentials into CSI Manila is done using a k8s Secret. Please take a look at [examples](https://github.com/kubernetes/cloud-provider-openstack/tree/master/examples/manila-csi-plugin) and a template secrets yaml [here](https://github.com/kubernetes/cloud-provider-openstack/blob/master/examples/manila-csi-plugin/nfs/secrets.yaml). This Secret object then needs to be referenced from your [storage class](https://github.com/kubernetes/cloud-provider-openstack/blob/master/examples/manila-csi-plugin/nfs/dynamic-provisioning/storageclass.yaml).

**Comment by ramineni** [comment]
@lw8008 hope your issue is solved.
@gman0 Do you think anything needs to be updated in documentation for better clarity?

**Comment by gman0** [comment]
@ramineni yes, I'm planning to revamp the docs

**Comment by ramineni** [comment]
closing this issue.
Revamp of docs can be tracked as separate issue if required.

/close
