### ISSUE TITLE
[cinder-csi-driver] delete statefulset pod then new pod remounted failed with  blkid returns invalid output

### ISSUE THREAD

**Issue by jianglingxia** [kubernetes/cloud-provider-openstack#1098]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:
i deploy a statefulset with replicas one used cinder pvc ,then running 
second,i delete the pod and the new replicas pod remount pvc but failed:

web-0              1/1     Running             0          4d23h   172.30.0.1   18.1.1.1   <none>           <none>
web-0              1/1     Terminating         0          4d23h   172.30.0.17   18.1.1.1   <none>           <none>
web-0              0/1     Terminating         0          4d23h   <none>        18.1.1.1   <none>           <none>
web-0              0/1     Pending             0          4s      <none>        18.1.1.1   <none>           <none>
web-0              0/1     ContainerCreating   0          4s      <none>        18.1.1.1   <none>           <none>

the web-0 pod logs :
Events:
  Type     Reason                  Age                From                     Message
  ----     ------                  ----               ----                     -------
  Normal   Scheduled               2m8s               default-scheduler        Successfully assigned default/web-0 to 188.1.1.11
  Normal   SuccessfulAttachVolume  104s               attachdetach-controller  AttachVolume.Attach succeeded for volume "pvc-c9947920-991c-41cf-b08e-648ad67b6eb4"
  Warning  FailedMount             24s (x8 over 95s)  kubelet, 188.1.1.11      MountVolume.MountDevice failed for volume "pvc-c9947920-991c-41cf-b08e-648ad67b6eb4" : rpc error: code = Internal desc = failed to get disk format of disk /dev/disk/by-id/virtio-c14a81a4-3d68-4288-9: blkid returns invalid output: /dev/disk/by-id/virtio-c14a81a4-3d68-4288-9: UUID="27b52caf-ec56-489e-91e6-4f3d003b43c2" TYPE="ext4"
  Warning  FailedMount             5s                 kubelet, 188.1.1.11      Unable to attach or mount volumes: unmounted volumes=[www]

the ds node-plugin logs :
I0611 09:04:39.526996       1 mount_linux.go:405] Attempting to determine if disk "/dev/disk/by-id/virtio-c14a81a4-3d68-4288-9" is formatted using blkid with args: ([-p -s TYPE -s PTTYPE -o export /dev/disk/by-id/virtio-c14a81a4-3d68-4288-9])
I0611 09:04:39.544355       1 mount_linux.go:408] Output: "/dev/disk/by-id/virtio-c14a81a4-3d68-4288-9: UUID=\"27b52caf-ec56-489e-91e6-4f3d003b43c2\" TYPE=\"ext4\"\n", err: <nil>
E0611 09:04:39.546005       1 utils.go:83] GRPC error: rpc error: code = Internal desc = failed to get disk format of disk /dev/disk/by-id/virtio-c14a81a4-3d68-4288-9: blkid returns invalid output: /dev/disk/by-id/virtio-c14a81a4-3d68-4288-9: UUID="27b52caf-ec56-489e-91e6-4f3d003b43c2" TYPE="ext4"

**What you expected to happen**:
the new pod can running 

**How to reproduce it**:

**Anything else we need to know?**:

**Environment**: k8s v1.17  csi-cinder-driver v1.18 release version
- openstack-cloud-controller-manager(or other related binary) version:
- OpenStack version:
- Others:

**Comment by jianglingxia** [comment]
@ramineni  can you see the problem ? thanks

**Comment by jichenjc** [comment]
@jianglingxia please follow the issue template to indicate this is a cinder CSI issue

**Comment by jianglingxia** [comment]
hi, i found the logs print :
the blkid command output not same with the command result in k8s.io/utils go code 

Output: "/dev/disk/by-id/virtio-c14a81a4-3d68-4288-9: UUID=\"27b52caf-ec56-489e-91e6-4f3d003b43c2\" TYPE=\"ext4\"\n", err: <nil>

but i exec the command in my minion

[root@paas-controller-1:/home/ubuntu]$ blkid -p -s TYPE -s PTTYPE -o export /dev/disk/by-id/virtio-c14a81a4-3d68-4288-9
DEVNAME=/dev/disk/by-id/virtio-c14a81a4-3d68-4288-9
TYPE=ext4

**Comment by jianglingxia** [comment]
@ramineni  jichenjc  can see the issue? is maybe pod reschedule other node have some problem? thanks

**Comment by kayrus** [comment]
@jianglingxia `blkid` is executed inside the nodeplugin daemonset container. can you show your daemonset manifest?
@ramineni I think this is a good example of why using `exec` in go is not a good idea. ref https://github.com/kubernetes/cloud-provider-openstack/pull/861#discussion_r359881506
