### ISSUE TITLE
[cinder-csi-plugin] Error deploying cinder-csi-plugin using chart

### ISSUE THREAD

**Issue by blackwith** [kubernetes/cloud-provider-openstack#1108]
**Is this a BUG REPORT or FEATURE REQUEST?**:
 /kind bug

**What happened**:
```Error: unable to build kubernetes objects from release manifest: error validating "": error validating data: ValidationError(StatefulSet.spec): missing required field "serviceName" in io.k8s.api.apps.v1.StatefulSetSpec```

**What you expected to happen**:
install the Chart

**How to reproduce it**:
helm install --namespace kube-system cinder-csi ./charts/cinder-csi-plugin

**Anything else we need to know?**:
No

**Environment**:
- k8s version : 
```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.4", GitCommit:"c96aede7b5205121079932896c4ad89bb93260af", GitTreeState:"clean", BuildDate:"2020-06-18T17:02:08Z", GoVersion:"go1.13.12", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.2", GitCommit:"59603c6e503c87169aea6106f57b9f242f64df89", GitTreeState:"clean", BuildDate:"2020-01-18T23:22:30Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by ramineni** [comment]
Its being addressed as part of https://github.com/kubernetes/cloud-provider-openstack/pull/1105
