### ISSUE TITLE
[manila-csi-plugin] Lots of RBAC issues when manually installing without helm

### ISSUE THREAD

**Issue by cohomology** [kubernetes/cloud-provider-openstack#1109]
/kind bug

**What happened**:

I tried to install manila-csi-plugin exactly according to the documentation, but I got lots of permission/RBAC errors afterwards, which I could only circumvent by applying the `cluster-admin` role to the service account `openstack-manila-csi-controllerplugin`.

- I could start the nodeplugin container of the controllerplugin, when applying "system:persistent-volume-provisioner"
- I could never start the snapshotter container. I get lots of:
```
github.com/kubernetes-csi/external-snapshotter/pkg/client/informers/externalversions/factory.go:117: Failed to list *v1alpha1.VolumeSnapshotClass:volumesnapshotclasses.snapshot.storage.k8s.io is forbidden: User "system:serviceaccount:kube-system:openstack-manila-csi-controllerplugin" cannot list resource "volumesnapshotclasses" in API group "snapshot.storage.k8s.io" at the cluster scope
E0625 16:35:49.814460       1 reflector.go:126] github.com/kubernetes-csi/external-snapshotter/pkg/client/informers/externalversions/factory.go:117: Failed to list *v1alpha1.VolumeSnapshotContent: volumesnapshotcontents.snapshot.storage.k8s.io is forbidden: User "system:serviceaccount:kube-system:openstack-manila-csi-controllerplugin" cannot list resource "volumesnapshotcontents" in API group "snapshot.storage.k8s.io" at the cluster scope
```

**What you expected to happen**:
Should work without errors

**How to reproduce it**:

**Anything else we need to know?**:

**Environment**:
- openstack-cloud-controller-manager(or other related binary) version:
- OpenStack version:
- Others:

**Comment by cohomology** [comment]
I guess that `https://github.com/kubernetes/cloud-provider-openstack/blob/master/manifests/manila-csi-plugin/csi-controllerplugin-rbac.yaml` deploys the role config always in the default namespace.

**Comment by ramineni** [comment]
@cohomology In documentation its already mentioned to first deploy rbacs of both nodeplugin and controller plugin.
kubectl create -f csi-controllerplugin-rbac.yaml
kubectl create -f csi-nodeplugin-rbac.yaml ,
Ref: https://github.com/kubernetes/cloud-provider-openstack/blob/master/docs/using-manila-csi-plugin.md
Are you saying you are facing issues after that as well?

**Comment by cohomology** [comment]
Yes, because I (as a total beginner) deployed accidently into another namespace. The rbac files are only working for the default namespace. Finding this error is not trivial for a non-expert.

**Comment by ramineni** [comment]
@cohomology good to see, issue is resolved. 
Your contributions to update the documentation to make it better is much welcome.
