### ISSUE TITLE
[cinder-csi-plugin] different cloud-config locations in provided Helm charts

### ISSUE THREAD

**Issue by eumel8** [kubernetes/cloud-provider-openstack#1116]
**BUG REPORT**: different cloud-config locations in provided Helm charts

/kind bug

**What happened**:

We started few months ago to use Helm charts manifests provided by [1]. After switch to the new Helm chart it seems cloud-config location has changed (back?) from /etc/config/cloud.conf to /etc/kubernetes/cloud-config [2]

[1] https://github.com/kubernetes/cloud-provider-openstack/blob/master/manifests/cinder-csi-plugin/cinder-csi-controllerplugin.yaml#L99
[2] https://github.com/kubernetes/cloud-provider-openstack/blob/master/charts/cinder-csi-plugin/templates/controllerplugin-statefulset.yaml#L96

**What you expected to happen**:

Expectation would be to follow the new location for external cloud providers in /etc/config/cloud.conf or a hint in the documentation.

**How to reproduce it**:

install the manifest chart and then switch to the new chart

**Anything else we need to know?**:

Just a question: What's the plan for 1.19? Switch to one chart and retire the old manifests? Or switch complete to Operator approach?

**Environment**:
- openstack-cloud-controller-manager(or other related binary) version: 1.18
- OpenStack version: unknown
- Others:

**Comment by ramineni** [comment]
@eumel8 Thanks for reporting this . 
Manual installation through manifests mandates you to create a secret first , cloud-config which is then mounted to container to the path /etc/config/cloud.conf .
But with the helm, looking at manifests , it directly mounts the hostpath /etc/kubernetes onto container , so mandates to store the cloud-config in that location , else location needs to be changed , https://github.com/kubernetes/cloud-provider-openstack/blob/master/charts/cinder-csi-plugin/templates/controllerplugin-statefulset.yaml#L109

But I do see its updated here in , https://github.com/kubernetes/cloud-provider-openstack/blob/master/docs/using-cinder-csi-plugin.md#deploy , that it assumes cloud-config gets stored in that location.

**Comment by ramineni** [comment]
> Just a question: What's the plan for 1.19? Switch to one chart and retire the old manifests? Or switch complete to Operator approach?

NO, we wont be retiring the manifests . 
Manual deployment  and also through helm both will be supported in future releases.

**Comment by eumel8** [comment]
@ramineni thx for the hints so far

**Comment by ramineni** [comment]
@eumel8 Are you ok with closing this issue ? 
As both the mechanisms are different how cloud-config is handled , changing the mount path of volume inside container doesnt really have effect, as it will be handled by container .

**Comment by eumel8** [comment]
thanks @ramineni 
I put this information in our notes.
