### ISSUE TITLE
[cinder-csi-plugin] Cannot delete PV and the volumeattachment

### ISSUE THREAD

**Issue by celiawa** [kubernetes/cloud-provider-openstack#1121]
**Is this a BUG REPORT or FEATURE REQUEST?**:
 /kind bug

**What happened**:
I reported a issue https://github.com/kubernetes/cloud-provider-openstack/issues/944
when we use cinder-csi-plugin: 1.16.

This issue still happened when using cinder-csi-plugin: 1.17.  After did helm delete, some PV hang in Terminating

`NAME                                       CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS        CLAIM                             STORAGECLASS     REASON   AGE
pvc-a3fe69d3-44bd-4ab6-bfba-b4f773d62a7c   1Gi        RWO            Delete           Terminating   default/datadir-neo-cneo-core-1   cinder-az-nova            11h
`

From csi-provisioner log,  this pv pvc-a3fe69d3-44bd-4ab6-bfba-b4f773d62a7c was deleted at 18:44:58.054715

`I0716 18:44:09.781692       1 event.go:255] Event(v1.ObjectReference{Kind:"PersistentVolume", Namespace:"", Name:"pvc-a3fe69d3-44bd-4ab6-bfba-b4f773d62a7c", UID:"1f5c4cd8-afba-48d7-a857-c2c64d08e5c4", APIVersion:"v1", ResourceVersion:"12738567", FieldPath:""}): type: 'Warning' reason: 'VolumeFailedDelete' rpc error: code = Internal desc = DeleteVolume failed with error Cannot delete the volume "99749c12-9d7b-4b41-b8bc-1e18c80f29d2", it's still attached to a node
I0716 18:44:25.781942       1 controller.go:1311] delete "pvc-a3fe69d3-44bd-4ab6-bfba-b4f773d62a7c": started
E0716 18:44:25.878480       1 controller.go:1334] delete "pvc-a3fe69d3-44bd-4ab6-bfba-b4f773d62a7c": volume deletion failed: rpc error: code = Internal desc = DeleteVolume failed with error Cannot delete the volume "99749c12-9d7b-4b41-b8bc-1e18c80f29d2", it's still attached to a node
W0716 18:44:25.878568       1 controller.go:936] Retrying syncing volume "pvc-a3fe69d3-44bd-4ab6-bfba-b4f773d62a7c", failure 5
I0716 18:44:25.878717       1 event.go:255] Event(v1.ObjectReference{Kind:"PersistentVolume", Namespace:"", Name:"pvc-a3fe69d3-44bd-4ab6-bfba-b4f773d62a7c", UID:"1f5c4cd8-afba-48d7-a857-c2c64d08e5c4", APIVersion:"v1", ResourceVersion:"12738567", FieldPath:""}): type: 'Warning' reason: 'VolumeFailedDelete' rpc error: code = Internal desc = DeleteVolume failed with error Cannot delete the volume "99749c12-9d7b-4b41-b8bc-1e18c80f29d2", it's still attached to a node
E0716 18:44:25.880231       1 controller.go:954] error syncing volume "pvc-a3fe69d3-44bd-4ab6-bfba-b4f773d62a7c": rpc error: code = Internal desc = DeleteVolume failed with error Cannot delete the volume "99749c12-9d7b-4b41-b8bc-1e18c80f29d2", it's still attached to a node
I0716 18:44:57.878819       1 controller.go:1311] delete "pvc-a3fe69d3-44bd-4ab6-bfba-b4f773d62a7c": started
I0716 18:44:58.049459       1 controller.go:1339] delete "pvc-a3fe69d3-44bd-4ab6-bfba-b4f773d62a7c": volume deleted
I0716 18:44:58.054614       1 controller.go:1385] delete "pvc-a3fe69d3-44bd-4ab6-bfba-b4f773d62a7c": persistentvolume deleted
I0716 18:44:58.054715       1 controller.go:1387] delete "pvc-a3fe69d3-44bd-4ab6-bfba-b4f773d62a7c": succeeded
`

The volumeattachment failed to delete at ControllerUnpublishVolume Volume not found

`[root@norton-bcmt-control-01 ~]# kubectl describe volumeattachments csi-835d59b7d8114a87fb04bf505f5adaef5cd7aea4faa20c4c08bfbbab379d32a5
Name:         csi-835d59b7d8114a87fb04bf505f5adaef5cd7aea4faa20c4c08bfbbab379d32a5
Namespace:
Labels:       <none>
Annotations:  csi.alpha.kubernetes.io/node-id: 056cacb4-860c-4a1e-9b75-ef5e8bb6d827
API Version:  storage.k8s.io/v1
Kind:         VolumeAttachment
Metadata:
  Creation Timestamp:             2020-07-16T15:48:10Z
  Deletion Grace Period Seconds:  0
  Deletion Timestamp:             2020-07-16T18:43:59Z
  Finalizers:
    external-attacher/cinder-csi-openstack-org
  Resource Version:  12884290
  Self Link:         /apis/storage.k8s.io/v1/volumeattachments/csi-835d59b7d8114a87fb04bf505f5adaef5cd7aea4faa20c4c08bfbbab379d32a5
  UID:               ca3339c6-9be7-4184-b30c-246b36e98251
Spec:
  Attacher:   cinder.csi.openstack.org
  Node Name:  norton-bcmt-worker-03
  Source:
    Persistent Volume Name:  pvc-a3fe69d3-44bd-4ab6-bfba-b4f773d62a7c
Status:
  Attached:  true
  Attachment Metadata:
    Device Path:  /dev/vde
  Detach Error:
    Message:  rpc error: code = NotFound desc = ControllerUnpublishVolume Volume not found
    Time:     2020-07-17T02:59:41Z
Events:       <none>`

**What you expected to happen**:
The PV are deleted.

**How to reproduce it**:
Helm delete, and openstack detach volumes tooks long time.

**Environment**:
cinder-csi-plugin: 1.17

**Comment by ramineni** [comment]
@celiawa We have backported some fixes related to it , unpublishvolume doesnt fail if volume is not found.
Could you try with image v1.17.1 , which includes those fixes?

k8scloudprovider/cinder-csi-plugin:v1.17.1

**Comment by celiawa** [comment]
@ramineni  Thanks for you reply. Can you tell us how to get the source code of cinder-csi-plugin:v1.17.1. We need to build the cinder-csi-plugin image with our base image.

**Comment by ramineni** [comment]
@celiawa you could get it from the release branch , https://github.com/kubernetes/cloud-provider-openstack/tree/release-1.17 
should have latest commit of backport fixes

**Comment by celiawa** [comment]
@ramineni, Thanks, will build and try.

**Comment by jichenjc** [comment]
@celiawa has this been fixed ? if so, we can close this issue..

**Comment by ramineni** [comment]
/close
pls reopen if still facing issue.
