### ISSUE TITLE
[cinder-csi-plugin][occm] cinder-csi-plugin pod access openstack through occm

### ISSUE THREAD

**Issue by celiawa** [kubernetes/cloud-provider-openstack#1122]
Please add the affected binary name in the title unless multiple binaries are affected, e.g.

* openstack-cloud-controller-manager (occm)
* cinder-csi-plugin

/kind feature

When using cinder csi, it requires all the nodes has the external interface. Is it possible that the cinder-csi-plugin pod access the openstack url through the occm pod which is running on the node with external interface.
If yes, how can we configure for the cinder-csi.

Thanks.

**Comment by jichenjc** [comment]
can I know further info about this question? 
e.g you are suggesting all CSI pods instead talk to openstack directly, talk to OCCM and let OCCM do the proxy? what's the use case and reason behind it?
