### ISSUE TITLE
[client-keystone-auth] Snap doesn't support local files for e.g. OS_CACERT

### ISSUE THREAD

**Issue by sabaini** [kubernetes/cloud-provider-openstack#1128]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
/kind bug

**What happened**:

Running `kubectl` (any subcommand) with keystone integration via client-keystone-auth snap results in :

```
An error occurred: failed: Cannot read CA file: open /home/someuser/tls/root_ca.crt: permission denied
```
And corresponding apparmor messages:

```
audit: type=1400 audit(1595426719.726:311816): apparmor="DENIED" operation="open" profile="snap.client-keystone-auth.client-keystone-auth" name="/home/someuser/tls/root_ca.crt" pid=5660 comm="client-keystone" requested_mask="r" denied_mask="r" fsuid=3620 ouid=3620
```

**What you expected to happen**:

Kubectl should return successfully

**How to reproduce it**:

1. Install kubectl snap
1. Install client-auth-keystone snap
1. Export OS_CACERT=/home/someuser/tls/root_ca.crt
1. Run kubectl

**Anything else we need to know?**:

The client-auth-keystone snap runs in strict confinement. To be able to access OS_CACERTs in user homes it'd need to support the snap :home plug (currently only supports the :network  plug)

**Environment**:

client-keystone-auth  v1.14.0+git36.e163280
kubectl               1.18.6

**Comment by lingxiankong** [comment]
@sabaini I don't think this is the client-keystone-auth issue, I'm not sure who is maintaining client-keystone-auth snap, but maybe you should ask help from them.

**Comment by sabaini** [comment]
@lingxiankong The snapcraft.yaml file that defines the snap is part of this repository, this led me to believe that the snap is maintained here.

**Comment by lingxiankong** [comment]
> @lingxiankong The snapcraft.yaml file that defines the snap is part of this repository, this led me to believe that the snap is maintained here.

@sabaini Sorry for the confusion, as far as I know, that file has never been tested and I am not sure if there is someone actually maintain that.

I would suggest you build the binary by yourself, should be as easy as one command: `GOOS=linux BUILD_CMDS="client-keystone-auth" make build`. You are also welcome to fix if you want.

**Comment by lingxiankong** [comment]
BTW, client-keystone-auth is also included in the release, please check https://github.com/kubernetes/cloud-provider-openstack/releases

**Comment by lingxiankong** [comment]
The snapcraft.yaml file has been removed from the repo and is not going to be supported.
