### ISSUE TITLE
[occm] report incorrect error info when LB is not enabled

### ISSUE THREAD

**Issue by jichenjc** [kubernetes/cloud-provider-openstack#1132]
**Is this a BUG REPORT or FEATURE REQUEST?**:

 /kind bug
> /kind feature

**What happened**:

see following info in logs on a non-LB env
```
E0724 08:02:43.205462       1 openstack.go:894] Failed to create an OpenStack LoadBalancer client: failed to find load-balancer v2 endpoint for region RegionOne: No suitable endpoint could be found in the service catalog.
E0724 08:02:43.207681       1 core.go:90] Failed to start service controller: the cloud provider does not support external load balancers

```

I didn't have lb section in my configuration file and according to 
https://github.com/kubernetes/cloud-provider-openstack/blob/master/pkg/cloudprovider/providers/openstack/openstack.go#L875
we should not report error

I doubt it will not satisfy even the configuration section is not set due to 
https://github.com/kubernetes/cloud-provider-openstack/blob/master/pkg/cloudprovider/providers/openstack/openstack.go#L585

**What you expected to happen**:

**How to reproduce it**:

**Anything else we need to know?**:

**Environment**:
- openstack-cloud-controller-manager(or other related binary) version:
- OpenStack version:
- Others:

**Comment by lingxiankong** [comment]
Hi @jichenjc, Service controller is one of the basic components of Kubernetes cloud controller manager, I'm not sure it makes sense to deploy OCCM but with load balancing service available in your environment.

**Comment by jichenjc** [comment]
@lingxiankong it's not about whether no LB or with LB
it's the code logic has some problem and https://github.com/kubernetes/cloud-provider-openstack/blob/master/pkg/cloudprovider/providers/openstack/openstack.go#L875 has wrong checking...

**Comment by lingxiankong** [comment]
I don't quite understand, what's wrong with that check?

**Comment by jichenjc** [comment]
```
if reflect.DeepEqual(os.lbOpts, LoadBalancerOpts{}) {
		klog.V(4).Info("LoadBalancer section is empty/not defined in cloud-config")
		return nil, false
	}
```

the logic here is : if you don't have LB defined, return nil and no error reported
but the actual output is the code went to https://github.com/kubernetes/cloud-provider-openstack/blob/master/pkg/cloudprovider/providers/openstack/openstack.go#L894 and report error

**Comment by lingxiankong** [comment]
> ```
> if reflect.DeepEqual(os.lbOpts, LoadBalancerOpts{}) {
> 		klog.V(4).Info("LoadBalancer section is empty/not defined in cloud-config")
> 		return nil, false
> 	}
> ```
> 

Do you mean this check is not doing what we expect?

**Comment by jichenjc** [comment]
> > ```
> > if reflect.DeepEqual(os.lbOpts, LoadBalancerOpts{}) {
> > 		klog.V(4).Info("LoadBalancer section is empty/not defined in cloud-config")
> > 		return nil, false
> > 	}
> > ```
> 
> Do you mean this check is not doing what we expect?

exactly , I think it's not reporting correct error due to link I provided above...
https://github.com/kubernetes/cloud-provider-openstack/blob/master/pkg/cloudprovider/providers/openstack/openstack.go#L585
