### ISSUE TITLE
Adding Octavia Load Balancer Instances with more than one listener fails [octavia]

### ISSUE THREAD

**Issue by frittenlab** [kubernetes/cloud-provider-openstack#1133]
kind bug

**What happened**:

I tried to create an Octavia Load Balancer service using the Nginx Helm Chart. The service should create to ports. Port 80 and port 443 to serve web traffic. The Load Balancer gets created and the floating ip address is added. Then the contoller tries to add the security group which fails with:

  ```
I0724 15:41:50.136235       1 openstack_loadbalancer.go:1327] Creating floating IP  for loadbalancer 698e741a-72d7-416d-860d-b578b4f73404
I0724 15:41:50.136286       1 openstack_loadbalancer.go:1335] creating floating ip with opts {Description:Floating IP for Kubernetes external service default/webapp-svc from cluster wfrfzpwr9w FloatingNetworkID:8bb661f5-76b9-45f1-9ef9-eeffcd025fe4 FloatingIP: PortID:c3031138-07c7-406b-a0a4-5e20e030ad39 FixedIP: SubnetID: TenantID: ProjectID:}

I0724 15:42:01.977854       1 controller.go:742] Finished syncing service "default/webapp-svc" (3m40.04233468s)
E0724 15:42:01.977897       1 controller.go:244] error processing service default/webapp-svc (will retry): failed to ensure load balancer: failed when reconciling security groups for LB service default/webapp-svc: failed to update security group for port 359adbda-037b-4f4a-aacb-1b38c701c969: Bad request with: [PUT https://api.dbl.cloud.XXXX.net:9696/v2.0/ports/359adbda-037b-4f4a-aacb-1b38c701c969], error message: {"NeutronError": {"message": "Invalid input for security_groups. Reason: Duplicate items in the list: 'a64d339c-6a3c-4134-ae9a-02fb025af11a'.", "type": "HTTPBadRequest", "detail": ""}}
```

**What you expected to happen**:

I expect the Load Balancer and the security group to be created. 

**How to reproduce it**:

Create a service with two or more external ports. Creating a service with one port works without a problem.

**Environment**:
- openstack-cloud-controller-manager(or other related binary) version: latest (The other versions did not work at all)
- OpenStack version: Queens 
- Kubernetes 1.18.6

**Comment by lingxiankong** [comment]
1. I don't think this issue has something to do with octavia-ingress-controller as the title describes.
2. Could you please provide your OpenStack cloud provider configuration? From the error log, I can see it's because the security group creation failed, if you are using Octavia, `manage-security-groups` option is not needed.

**Comment by frittenlab** [comment]
Sorry I was away for a few days. Here is my cloud config:

```
[LoadBalancer]
use-octavia=true
manage-security-groups=true
floating-network-id="8bb661f5-76b9-45f1-9ef9-eeffcdds6367"
create-monitor=true
monitor-delay=60s
monitor-timeout=30s
monitor-max-retries=5
```

Yes I am using manage-security-groups. Otherwise the Octavia Load Balancer will not have any security groups. Or am I missing something here? I belive I tried creating a Load Balancer without the option manage-security-groups and the Load Balancer gets created without a problem. But the service is not reachable.

**Comment by frittenlab** [comment]
I tried to remove the option manage-security-groups. As expected the services are not reachable and all requests that hit the service IP are responded with an HTTP 503.

**Comment by frittenlab** [comment]
I tried to configure the two high ports necessary for the nginx ingress controller manually. If I do that I can can reach the nginx default backend. I then tried to create an ingress rule with a service. That service is also not reachable.

**Comment by frittenlab** [comment]
@lingxiankong How does the creation of the security groups work? If I remove the option:

manage-security-groups

from my cloud configuration.

**Comment by lingxiankong** [comment]
> I tried to remove the option manage-security-groups. As expected the services are not reachable and all requests that hit the service IP are responded with an HTTP 503.

Can you check if you have already created the security group for all your nodes to make sure the ports 30000-32767 are open to the node subnet CIDR?

**Comment by frittenlab** [comment]
Thanks for your support. Are there any plans on adding the feature manage-security-groups to Octavia. This worked fine for us with the neutron load balancer. For the moment it is ok to add the port range 30000 - 32767 to the node security groups. But it is not the ideal solution. We are opening all the node ports even the ones which are not in use. If no one if planning on working on this and you agree we would create a PR for this. What do you think?

**Comment by lingxiankong** [comment]
> But it is not the ideal solution. We are opening all the node ports even the ones which are not in use.

Why? Those ports are only open to the node's own subnet, not to the public.

**Comment by frittenlab** [comment]
Ok I added new rule just containing the nodes subnet this works. Before I had a rule referencing the Remote Security Group. Which did not work. Thank you again for your support.
