### ISSUE TITLE
[docs] Provide Minimum user permissions documentation

### ISSUE THREAD

**Issue by VariableDeclared** [kubernetes/cloud-provider-openstack#1134]
> /kind bug

**What happened**:
When looking at the docs they show that it is required to add an Openstack user to the configuration for the cloud provider, but not roles/permissions that user should have.

**What you expected to happen**:
A table or json file giving a breakdown of minimum permissions for a user to have in order to use the cloud provider without issues.

**How to reproduce it**:
NA

**Anything else we need to know?**:
NA

**Environment**:
NA

**Comment by jichenjc** [comment]
are you looking for what kind of policy should be enabled for the user so that he/she is eligible to execute openstack API through cloud provider?or something else?

and with `application ID` it should be also a good approach instead of using userid/password directly

**Comment by VariableDeclared** [comment]
Hey @jichenjc, docs describing minimum permissions a user on a project can have for the cloud provider would be great.

**Comment by jichenjc** [comment]
um... maybe different components has different requirements
for example, CSI-cinder might request capability to mount a volume while LB might need create LB and other resources , so this is only eligible to each sub-project of CPO

**Comment by jichenjc** [comment]
/reopen

@raafatseif FYI
