### ISSUE TITLE
[Manila-CSI-Plugin] Unable to mount NFS volume after dynamic provision

### ISSUE THREAD

**Issue by JPRbrs** [kubernetes/cloud-provider-openstack#1136]
> /kind Feature

**What happened**:
When trying to use the examples in the dynamic-provisioning folder, the NFS is correctly created in OpenStack but it is not mounted in the pod. The cause is that Openstack provides several export locations (IP + path) but Manila CSI is selecting one with an IP which does not belong to the Kubernetes Cluster Network Interface.

**What you expected to happen**:
NFS volume is mounted in the node and then in the pod

**How to reproduce it**:
Deploy CSI NFS driver (https://github.com/kubernetes-csi/csi-driver-nfs) and Manila NFS plugin. Deploy manifests in examples/nfs/dynamic-provisioning

**Anything else we need to know?**:
Is there anyway we can tell Manila CSI which subnet to use when choosing the export location? I've tried with nfs-shareClient and shareNetworkID but neither of them worked

**Comment by tombarron** [comment]
Thank you for reporting this issue, which seems to me genuine.  Do you need selection from export locations in different address families (IPv6, IPv4) or is the address-family the same?  We need to figure out what information is needed to choose, who has that information, and whether it would be the manila-csi plugin itself or its helper node-plugin (in this case nfs-csi) that would be doing the selection.

**Comment by JPRbrs** [comment]
Thanks for the answer @tombarron, I only need to use IPv4 IPs. After looking into the code base, I reckon passing the subnet in CIDR notation as an optional parameter to ChooseExportLocation function in pkg/csi/manila/util/manila.go  would be ideal. Perhaps adding an extra parameter to the Controller Service volume parameters (storage class for dynamically provisioned volumes) would be the perfect place to add it. What do you think?

**Comment by JPRbrs** [comment]
Hello again @tombarron Would it make sense to add a new parameter to NodeVolumeContext struct in pkg/csi/manila/options/shareoptions.go with the CIDR formatted IP for the subnet so it can be used by buildVolumeContext function in pkg/csi/manila/nodeserver.go and in turn it can be passed to ChooseExportLocation through GetChosenExportLocation in pkg/csi/manila/util/manila.go?

The only problem I see is that I cannot find any reference to the IP where the NFS share is exposed...

**Comment by gman0** [comment]
@JPRbrs Yes that would be the place for it, although I'm wondering if `exportLocationSubnet` won't change throughout the cluster's lifetime (volume parameters in StorageClass are immutable) or it can change over time? If so, we'd need to inject this address through some other means, e.g. a ConfigMap.

**Comment by gman0** [comment]
Another question: does it make sense for this parameter to be a list of addresses?

**Comment by JPRbrs** [comment]
@gman0 I think the ConfigMap would be an excellent approach for the cases where the exportLocationSubnet changes. I my particular case, once the cluster is created this address doesn't change, but it might be different for other people depending on how their OpenStack and networking is configured.

I'm not an expert in Go but I'd love to help in as much as I can, how can we handle this so I can offer all possible help from my side?

**Comment by tombarron** [comment]
Export locations can change though it's not a likely or frequent thing.
A list of addresses makes sense to me -- JPRbrs can do a list with one member.

**Comment by JPRbrs** [comment]
Thanks @gman0 @tombarron, any pointers on how to use a config map to pass that info to the volume context? I couldn't find examples on the code. Any assistance will be welcome

**Comment by gman0** [comment]
@JPRbrs Preferably we would expose the ConfigMap [as a volume](https://kubernetes.io/docs/tasks/configure-pod-container/configure-pod-configmap/#populate-a-volume-with-data-stored-in-a-configmap) (i.e. regular files). That way we can avoid having Kubernetes-specific code in the driver. We're still bolting down the specifics with the csi-manila guys though.

**Comment by JPRbrs** [comment]
Many thanks, I'll keep an eye on this thread and will update if make any
progress

**Comment by gman0** [comment]
@JPRbrs I'm doing some tests locally and I just want to make sure we're on the same page: the actual error I'm getting is a connection timeout.

Logs from the CSI NFS node plugin:
```
E0810 17:17:40.587481       1 mount_linux.go:139] Mount failed: exit status 32
Mounting command: mount
Mounting arguments: -t nfs <server IP>:<share path> <mount path>
Output: mount.nfs: Connection timed out

E0810 17:17:40.589482       1 utils.go:50] GRPC error: rpc error: code = Internal desc = mount failed: exit status 32
```

It takes a while for it to time out...

Is this what you're getting?

**Comment by JPRbrs** [comment]
Thanks Robert, that's exactly what I'm seeing.

Let me know if I can be of any help
