### ISSUE TITLE
[manila-csi-plugin] Snapshot creation failed because of insufficient permissions

### ISSUE THREAD

**Issue by Fedosin** [kubernetes/cloud-provider-openstack#1142]
> /kind bug

**What happened**:
When creating a manila snapshot, we got the following message about missing permissions: 
I0520 00:27:19.431196       1 snapshot_controller.go:200] updating VolumeSnapshotContent[snapcontent-a93535d3-000c-45c2-b1da-a19bb7b3f12d] error status failed volumesnapshotcontents.snapshot.storage.k8s.io "snapcontent-a93535d3-000c-45c2-b1da-a19bb7b3f12d" is forbidden: User "system:serviceaccount:manila-csi:openstack-manila-csi-controllerplugin" cannot update resource "volumesnapshotcontents/status" in API group "snapshot.storage.k8s.io" at the cluster scope

**What you expected to happen**:
Serviceaccount openstack-manila-csi-controllerplugin has the permission.

**How to reproduce it**:
1. Install manila csi plugin using helm charts
2. Create volumesnapshotclass
2. Create volumesnapshot

**Comment by ramineni** [comment]
@Fedosin which snaphotter sidecar version are you using?

**Comment by gman0** [comment]
csi-snapshotter v2 needs this RBAC rule, but we're still on v1

**Comment by ramineni** [comment]
@gman0 exactly , currently manila-csi-plugin doesnt support v1beta1, so with current snapshotter version , it shouldn't throw error.
So Im wondering if 2.0.0 is used, then there should also include snapshot-controller etc and some setup changes as well

@Fedosin if you are using this , you might need to lower version 1.2.2 as per manifests which should work seamlessly . Let us know if you are facing issue using the manifests here , https://github.com/kubernetes/cloud-provider-openstack/tree/master/manifests/manila-csi-plugin

**Comment by ramineni** [comment]
/close
pls reopen if facing issue on current supported version. Thanks.
