### ISSUE TITLE
why the os-initialize_connection Initiator not same VM caused the volume always attaching

### ISSUE THREAD

**Issue by jianglingxia** [kubernetes/cloud-provider-openstack#115]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
> /kind bug
> /kind feature

**What happened**:
the standalone cinder provisioner created the pv and volume,but the volume always attaching,I found the cinder api.log is the os-initialize_connection Initiator not same VM! the place I not corrected ?thanks!

[root@localhost:/etc/iscsi]$ kubectl get po
NAME                                             READY     STATUS    RESTARTS   AGE
standalone-cinder-provisioner-5d85c99899-w6vx7   1/1       Running   0          1h

[root@localhost:/etc/iscsi]$ kubectl get sc
NAME                 PROVISIONER
standard (default)   openstack.org/standalone-cinder

[root@localhost:/etc/iscsi]$ kubectl get secret
NAME                    TYPE                                  DATA      AGE
default-token-dl44v     kubernetes.io/service-account-token   3         10d
standard-cephx-secret   kubernetes.io/rbd                     1         1d

[root@localhost:/etc/iscsi]$ kubectl get pvc
NAME              STATUS    VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS   AGE
keystone-sc-pvc   Bound     pvc-b4b87e3b-3e72-11e8-a4fc-4c09b4b0c25b   1Gi        RWO            standard       37m

the cinder volume status:
![image](https://user-images.githubusercontent.com/25783555/38668534-b5ae370c-3e76-11e8-99a2-4010e7f6b164.png)

the cinder api.log
![image](https://user-images.githubusercontent.com/25783555/38668621-e173e210-3e76-11e8-87f6-253c78e1de27.png)

and the cinder volume.log
![image](https://user-images.githubusercontent.com/25783555/38668757-2f2fcd20-3e77-11e8-8397-bd32c536eabd.png)
![image](https://user-images.githubusercontent.com/25783555/38668795-45ced8b4-3e77-11e8-97b2-75ffe7d7238a.png)
![image](https://user-images.githubusercontent.com/25783555/38668993-cdd8843a-3e77-11e8-9f07-3277083ab767.png)

**What you expected to happen**:
the volume attached the vm success
**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**: k8sv1.8.5
- openstack-cloud-controller-manager version:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by jianglingxia** [comment]
/assign @dims 
thanks very much

**Comment by jianglingxia** [comment]
I review the code the iqn is the same code 
// ConnectCinderVolume retrieves connection information for a cinder volume.
// Depending on the type of volume, cinder may perform setup on a storage server
// such as mapping a LUN to a particular ISCSI initiator.
func ConnectCinderVolume(vs *gophercloud.ServiceClient, volumeID string) (VolumeConnection, error) {
	opt := volumeactions.InitializeConnectionOpts{
		Host:      "localhost",
		IP:        "127.0.0.1",
		Initiator: initiatorName,
	}
	var rcv rcvVolumeConnection
	err := volumeactions.InitializeConnection(vs, volumeID, &opt).ExtractInto(&rcv)
	if err != nil {
		glog.Errorf("failed to initialize connection :%v", err)
		return VolumeConnection{}, err
	}
	glog.V(3).Infof("Received connection info: %v", rcv)
	return rcv.ConnectionInfo, nil
}

**Comment by jianglingxia** [comment]
![image](https://user-images.githubusercontent.com/25783555/38712298-48305926-3efd-11e8-8766-3b76381cbc89.png)
this is my vm iqn ，really thanks @FengyunPan2  wait for your reply!

**Comment by jianglingxia** [comment]
I found that I create the storageclass not set the type is iscsi or rbd ，so default use the iscsi,but I create the secret is ceph-rbd keyring,then I re-do it follow two way:
1、use rbd
[root@localhost:/home/ubuntu/yaml-baremetal]$ cat sc-rbd.yaml
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: standard
  annotations:
    storageclass.beta.kubernetes.io/is-default-class: "true"
  labels:
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: EnsureExists
provisioner: openstack.org/standalone-cinder
parameters:
  type: rbd
create the pvc ,but pv log Warning  ProvisioningFailed    26s               openstack.org/standalone-cinder standalone-cinder-provisioner-5d85c99899-w6vx7 2601eb81-3e6e-11e8-9fac-0242ac110002  Failed to provision volume with StorageClass "standard": Successfully re-authenticated, but got error executing request: Resource not found

is that my backend the volumeType value is none?not rbd or iscsi?
![image](https://user-images.githubusercontent.com/25783555/38723017-63a305a2-3f32-11e8-8333-03272a1ae280.png)
thanks for your advice @FengyunPan2  @dims

**Comment by edisonxiang** [comment]
Hi @jianglingxia, could you please paste your pod.yaml?
The initiatorName is usually different in the host vm and the containers in the host vm.

**Comment by jianglingxia** [comment]
yeah,thanks ;but I have occur two problem:
1)I create the storageclass not set the type,then provisioner can create pv and volume;but the volume not attached the vm caused the pod not running;this way default use the iscsi?but I use the ceph rbd keyring to create the named xx-cephx-secret not use the iscsi key
2)if I set the type rbd in storageclass ,the provisioner cannot create pv and volume,

Warning ProvisioningFailed 26s openstack.org/standalone-cinder standalone-cinder-provisioner-5d85c99899-w6vx7 2601eb81-3e6e-11e8-9fac-0242ac110002 Failed to provision volume with StorageClass "standard": Successfully re-authenticated, but got error executing request: Resource not found
[root@localhost:/home/ubuntu/yaml-baremetal]$ cat pod.yaml
apiVersion: v1
kind: Pod
metadata:
  name: mysql
  labels:
    name: mysql
spec:
  containers:
    - resources:
        limits :
          cpu: 0.5
      image: gcr.io/google_containers/nginx:1.7.9
      imagePullPolicy: Never
      name: mysql
      ports:
        - containerPort: 3306
          name: mysql
      volumeMounts:
          # name must match the volume name below
        - name: pvol
          # mount path within the container
          mountPath: /mnt
  volumes:
    - name: pvol
      persistentVolumeClaim:
        claimName: keystone-sc-pvc

**Comment by edisonxiang** [comment]
hey @jianglingxia, your first problem is very important, because it depends on what you want to use.
iscsi and rbd are very different in volume workflow. ```parameters: type``` in storageclass.yaml will be passed into cinder here. 
https://github.com/kubernetes/cloud-provider-openstack/blob/master/pkg/volume/cinder/cinder_util.go#L185

You could find the cinder type in your env:)
$ cinder type-list
$ cinder extra-specs-list

**Comment by jianglingxia** [comment]
thank you @edisonxiang  I found my env no the rbd volume type,so I have add one backend with rbd,if the backend success to create a volume with rbd, then maybe I can do on k8s follow things:
1)create the standalone cinder
2)create a storageclass with para type:rbd
3)create a secret with ceph keyring,and named storageclass name + -cephx-secret
4)create a pvc 
then pv and volume dynamic created,and attaching status
the last to create a pod，if no problem the pod running and volume attached the vm，all place is right?thanks!

**Comment by edisonxiang** [comment]
@jianglingxia yep, actually the volume will be attached to the pod:)

**Comment by jianglingxia** [comment]
your mean that the volume directs attached the pod？not IAAS sceneo first attached the vm then attached the pod?really thanks! @edisonxiang

**Comment by edisonxiang** [comment]
@jianglingxia No, you are right, first attached the vm then attached the pod.
I just meant the final status for the volume is attached to the pod:)

**Comment by jianglingxia** [comment]
I have created the ceph backend, and the pv and volume can dynamic create but the pod not running and the volume is attaching,the log hint the rbd image lock another node ?but not   lock,why?thanks
@edisonxiang @FengyunPan2 
![image](https://user-images.githubusercontent.com/25783555/38861002-1a9fab32-4264-11e8-90e3-3f4338848af7.png)
![image](https://user-images.githubusercontent.com/25783555/38861030-2697c898-4264-11e8-9b0b-432bec856e40.png)

**Comment by jianglingxia** [comment]
and the minion df -h can see the /dev/sdc1              97M  5.4M   92M   6% /var/lib/ceph/osd/ceph-0
![image](https://user-images.githubusercontent.com/25783555/38866579-efcf0a3c-4273-11e8-91ed-313b83a51021.png)

**Comment by jianglingxia** [comment]
@edisonxiang @FengyunPan2 really thanks for your review the problem
the pod not running that the kubelet lot hint  
![image](https://user-images.githubusercontent.com/25783555/38913614-3963415a-430e-11e8-8306-4402625505c1.png)
![image](https://user-images.githubusercontent.com/25783555/38913630-4f7bd0f6-430e-11e8-91b5-3bcf17c642b3.png)
but in my minion has the file
![image](https://user-images.githubusercontent.com/25783555/38913641-66ce9450-430e-11e8-8be1-dbf8e59fa98b.png)

**Comment by jianglingxia** [comment]
thanks all ,the pod has running and attached success,
but one questione that in standalone cinder sceneo the volume always attaching?not changed to in-use?
![image](https://user-images.githubusercontent.com/25783555/38917280-dd0791ea-431c-11e8-953a-5774e5944d03.png)
![image](https://user-images.githubusercontent.com/25783555/38917289-e8e218c8-431c-11e8-9b72-eb3ead11e989.png)

and the doc https://github.com/kubernetes/cloud-provider-openstack/blob/master/docs/using-cinder-standalone-provisioner.md workflow no in-use status,thanks!
