### ISSUE TITLE
All tests fail saying that they can't find the go 1.15 binary.

### ISSUE THREAD

**Issue by phiphi282** [kubernetes/cloud-provider-openstack#1161]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
/kind bug
> /kind feature

**What happened**:
I made a [pull request](https://github.com/kubernetes/cloud-provider-openstack/pull/1160) and all tests failed saying that they can't find the go 1.15 binary.

**What you expected to happen**:
The tests should be successfully getting a go binary.

**How to reproduce it**:
Run `/retest` in my [pull request](https://github.com/kubernetes/cloud-provider-openstack/pull/1160).

**Anything else we need to know?**:

**Environment**:
- openstack-cloud-controller-manager(or other related binary) version:
- OpenStack version:
- Others:

**Comment by jichenjc** [comment]
@phiphi282 I got exactly same issue to you on my PR
I believe it's openlab CI issue and need their help , @lingxiankong @ramineni where to ask for help? thanks

**Comment by phiphi282** [comment]
Tests should work now again. Wanted to create pr but one was already created by @ramineni theopenlab/openlab-zuul-jobs/pull/971. :)
