### ISSUE TITLE
[occm] Support for haproxy loadbalancer service provider

### ISSUE THREAD

**Issue by piequi** [kubernetes/cloud-provider-openstack#1164]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind feature

**What happened**:
Our hosting provider that offers openstack cloud environments as a service, only provides neutron-lbaas with haproxy service provider for loadbalancerv2.
Setting `lb-provider=haproxy` and `use-octavia=false` in the cloud configuration file for occm just worked fine (although documentation says that we can use either `amphora` or `octavia` values). A loadbalancer service got created correctly and is working as expected.

**What you expected to happen**:
I was expecting some errors in occm pods when deploying a loadbalancer service in k8s.

**How to reproduce it**:
Set `lb-provider=haproxy` and `use-octavia=false` in cloud.conf file for occm when neutron-lbaas uses haproxy service provider then deploy a loadbalancer service in k8s.

**Anything else we need to know?**:
Only the documentation needs to be updated apparently. Please tell me if there is anything to do to validate this more precisely.

**Environment**:
- openstack-cloud-controller-manager(or other related binary) version: docker.io/k8scloudprovider/openstack-cloud-controller-manager:latest
- OpenStack version: v18 Rocky with Neutron LBaaS v2 extension

**Comment by lingxiankong** [comment]
Neutron-LBaaS has been deprecated since stable/queens and its support is no longer maintained in openstack-cloud-controller-manager. Please see more information here https://github.com/kubernetes/cloud-provider-openstack/blob/master/docs/using-openstack-cloud-controller-manager.md
