### ISSUE TITLE
[cinder-csi-plugin] Cannot create PV

### ISSUE THREAD

**Issue by Chivolta** [kubernetes/cloud-provider-openstack#1177]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
/kind bug
> /kind feature

**What happened**:
During dynamic provisioning, I'm getting:

I0831 14:51:24.479149       1 utils.go:80] GRPC call: /csi.v1.Controller/CreateVolume
I0831 14:51:24.479204       1 utils.go:81] GRPC request: name:"pvc-a0a25f6e-e43e-45ed-b1b9-4be078fd23fd" capacity_range:<required_bytes:1073741824 > volume_capabilities:<mount:<fs_type:"ext4" > access_mode:<mode:SINGLE_NODE_WRITER > > parameters:<key:"availability" value:"az1-sse2" > parameters:<key:"volume_type" value:"gp-ssd" >
I0831 14:51:24.479399       1 openstack_volumes.go:108] OpenStack Request URL: GET test:13776/v3/86055269bb0c4f70a1c97976c54a5977/volumes/detail?name=pvc-a0a25f6e-e43e-45ed-b1b9-4be078fd23fd
I0831 14:51:24.479434       1 openstack_volumes.go:108] OpenStack Request Headers:
I0831 14:51:24.479440       1 openstack_volumes.go:108] Accept: application/json
I0831 14:51:24.479446       1 openstack_volumes.go:108] User-Agent: cinder-csi-plugin/latest gophercloud/2.0.0
I0831 14:51:24.479452       1 openstack_volumes.go:108] X-Auth-Token: ***
I0831 14:51:24.549426       1 openstack_volumes.go:108] OpenStack Response Code: 200
I0831 14:51:24.549548       1 openstack_volumes.go:108] OpenStack Response Headers:
I0831 14:51:24.549569       1 openstack_volumes.go:108] Content-Length: 15
I0831 14:51:24.549579       1 openstack_volumes.go:108] Content-Type: application/json
I0831 14:51:24.549589       1 openstack_volumes.go:108] Date: Mon, 31 Aug 2020 14:51:24 GMT
I0831 14:51:24.549599       1 openstack_volumes.go:108] Openstack-Api-Version: volume 3.0
I0831 14:51:24.549609       1 openstack_volumes.go:108] Server: Apache
I0831 14:51:24.549618       1 openstack_volumes.go:108] Vary: OpenStack-API-Version
I0831 14:51:24.549626       1 openstack_volumes.go:108] X-Compute-Request-Id: req-42e65425-0975-4350-a277-fbe7e02c029c
I0831 14:51:24.549636       1 openstack_volumes.go:108] X-Openstack-Request-Id: req-42e65425-0975-4350-a277-fbe7e02c029c
I0831 14:51:24.549789       1 openstack_volumes.go:108] OpenStack Response Body: {
I0831 14:51:24.549802       1 openstack_volumes.go:108]   "volumes": []
I0831 14:51:24.549814       1 openstack_volumes.go:108] }
I0831 14:51:24.550064       1 openstack_volumes.go:75] OpenStack Request URL: POST test:13776/v3/86055269bb0c4f70a1c97976c54a5977/volumes
I0831 14:51:24.550106       1 openstack_volumes.go:75] OpenStack Request Headers:
I0831 14:51:24.550116       1 openstack_volumes.go:75] Accept: application/json
I0831 14:51:24.550126       1 openstack_volumes.go:75] Content-Type: application/json
I0831 14:51:24.550136       1 openstack_volumes.go:75] User-Agent: cinder-csi-plugin/latest gophercloud/2.0.0
I0831 14:51:24.550146       1 openstack_volumes.go:75] X-Auth-Token: ***
I0831 14:51:24.550228       1 openstack_volumes.go:75] OpenStack Request Body: {
I0831 14:51:24.550240       1 openstack_volumes.go:75]   "volume": {
I0831 14:51:24.550251       1 openstack_volumes.go:75]     "availability_zone": "az1-sse2",
I0831 14:51:24.550261       1 openstack_volumes.go:75]     "description": "Created by OpenStack Cinder CSI driver",
I0831 14:51:24.550272       1 openstack_volumes.go:75]     "metadata": {
I0831 14:51:24.550283       1 openstack_volumes.go:75]       "cinder.csi.openstack.org/cluster": "kubernetes"
I0831 14:51:24.550295       1 openstack_volumes.go:75]     },
I0831 14:51:24.550306       1 openstack_volumes.go:75]     "name": "pvc-a0a25f6e-e43e-45ed-b1b9-4be078fd23fd",
I0831 14:51:24.550316       1 openstack_volumes.go:75]     "size": 1
I0831 14:51:24.550327       1 openstack_volumes.go:75]   }
I0831 14:51:24.550338       1 openstack_volumes.go:75] }
I0831 14:51:24.592339       1 openstack_volumes.go:75] OpenStack Response Code: 404
I0831 14:51:24.592390       1 openstack_volumes.go:75] OpenStack Response Headers:
I0831 14:51:24.592397       1 openstack_volumes.go:75] Content-Length: 114
I0831 14:51:24.592403       1 openstack_volumes.go:75] Content-Type: application/json
I0831 14:51:24.592409       1 openstack_volumes.go:75] Date: Mon, 31 Aug 2020 14:51:24 GMT
I0831 14:51:24.592415       1 openstack_volumes.go:75] Openstack-Api-Version: volume 3.0
I0831 14:51:24.592421       1 openstack_volumes.go:75] Server: Apache
I0831 14:51:24.592427       1 openstack_volumes.go:75] Vary: OpenStack-API-Version
I0831 14:51:24.592433       1 openstack_volumes.go:75] X-Compute-Request-Id: req-921afc53-c488-46be-88b4-170897fcbe27
I0831 14:51:24.592438       1 openstack_volumes.go:75] X-Openstack-Request-Id: req-921afc53-c488-46be-88b4-170897fcbe27
I0831 14:51:24.592611       1 openstack_volumes.go:75] OpenStack Response Body: {
I0831 14:51:24.592622       1 openstack_volumes.go:75]   "itemNotFound": {
I0831 14:51:24.592630       1 openstack_volumes.go:75]     "code": 404,
I0831 14:51:24.592644       1 openstack_volumes.go:75]     "message": "Volume type 50e93175-8574-44a3-aa18-0c54b4e36a8a could not be found."
I0831 14:51:24.592657       1 openstack_volumes.go:75]   }
I0831 14:51:24.592667       1 openstack_volumes.go:75] }
I0831 14:51:24.592722       1 controllerserver.go:127] Failed to CreateVolume: Resource not found
E0831 14:51:24.592756       1 utils.go:84] GRPC error: rpc error: code = Internal desc = CreateVolume failed with error Resource not found

**What you expected to happen**:
Volume is created.

**How to reproduce it**:

**Anything else we need to know?**:
Volumes are listing:
I0831 15:12:47.579949       1 utils.go:80] GRPC call: /csi.v1.Controller/ListVolumes
I0831 15:12:47.579996       1 utils.go:81] GRPC request:
I0831 15:12:47.580179       1 openstack_volumes.go:87] OpenStack Request URL: GET test:13776/v3/86055269bb0c4f70a1c97976c54a5977/volumes/detail
I0831 15:12:47.580240       1 openstack_volumes.go:87] OpenStack Request Headers:
I0831 15:12:47.580249       1 openstack_volumes.go:87] Accept: application/json
I0831 15:12:47.580258       1 openstack_volumes.go:87] User-Agent: cinder-csi-plugin/latest gophercloud/2.0.0
I0831 15:12:47.580266       1 openstack_volumes.go:87] X-Auth-Token: ***
I0831 15:12:47.751164       1 openstack_volumes.go:87] OpenStack Response Code: 200
I0831 15:12:47.751242       1 openstack_volumes.go:87] OpenStack Response Headers:
I0831 15:12:47.751252       1 openstack_volumes.go:87] Content-Type: application/json
I0831 15:12:47.751260       1 openstack_volumes.go:87] Date: Mon, 31 Aug 2020 15:12:47 GMT
I0831 15:12:47.751268       1 openstack_volumes.go:87] Openstack-Api-Version: volume 3.0
I0831 15:12:47.751277       1 openstack_volumes.go:87] Server: Apache
I0831 15:12:47.751308       1 openstack_volumes.go:87] Vary: OpenStack-API-Version,Accept-Encoding
I0831 15:12:47.751317       1 openstack_volumes.go:87] X-Compute-Request-Id: req-66ce02b4-212c-47e2-a4a8-075fd2b986f2
I0831 15:12:47.751326       1 openstack_volumes.go:87] X-Openstack-Request-Id: req-66ce02b4-212c-47e2-a4a8-075fd2b986f2
I0831 15:12:47.753339       1 openstack_volumes.go:87] OpenStack Response Body: {
I0831 15:12:47.753354       1 openstack_volumes.go:87]   "volumes": [
I0831 15:12:47.753363       1 openstack_volumes.go:87]     {
I0831 15:12:47.753372       1 openstack_volumes.go:87]       "attachments": [
I0831 15:12:47.753396       1 openstack_volumes.go:87]         {
I0831 15:12:47.753405       1 openstack_volumes.go:87]           "attached_at": "2020-05-22T05:28:52.000000",
I0831 15:12:47.753415       1 openstack_volumes.go:87]           "attachment_id": "b1a6705e-6489-4eed-8c8b-260fb32b4ed4",
I0831 15:12:47.753423       1 openstack_volumes.go:87]           "device": "/dev/vda",
I0831 15:12:47.753432       1 openstack_volumes.go:87]           "host_name": "test.test.test",
I0831 15:12:47.753440       1 openstack_volumes.go:87]           "id": "cb39b67e-a2d9-47bb-a1c4-fe5c72a0ec92",
I0831 15:12:47.753449       1 openstack_volumes.go:87]           "server_id": "508b0628-1072-4ac8-b794-102d20d8060d",
I0831 15:12:47.753475       1 openstack_volumes.go:87]           "volume_id": "cb39b67e-a2d9-47bb-a1c4-fe5c72a0ec92"
I0831 15:12:47.753484       1 openstack_volumes.go:87]         }
I0831 15:12:47.753493       1 openstack_volumes.go:87]       ],
I0831 15:12:47.753502       1 openstack_volumes.go:87]       "availability_zone": "az1-sse2",
I0831 15:12:47.753511       1 openstack_volumes.go:87]       "bootable": "true",
I0831 15:12:47.753520       1 openstack_volumes.go:87]       "consistencygroup_id": null,
I0831 15:12:47.753529       1 openstack_volumes.go:87]       "created_at": "2020-05-22T05:22:00.000000",
I0831 15:12:47.753537       1 openstack_volumes.go:87]       "description": "",
I0831 15:12:47.753547       1 openstack_volumes.go:87]       "encrypted": false,
I0831 15:12:47.753556       1 openstack_volumes.go:87]       "id": "cb39b67e-a2d9-47bb-a1c4-fe5c72a0ec92",
I0831 15:12:47.753564       1 openstack_volumes.go:87]       "links": [

**Environment**:
- openstack-cloud-controller-manager(or other related binary) version:
- OpenStack version:
- Others:

**Comment by jichenjc** [comment]
@Chivolta which version of CSI cinder you are using ? and I think you are using a volume type ,`gp-ssd` , correct? 

https://github.com/kubernetes/cloud-provider-openstack/blob/master/pkg/csi/cinder/nodeserver.go#L146  says volume type not supported but I need double check this 

can you help to confirm that volume type gp-ssd and volume type 50e93175-8574-44a3-aa18-0c54b4e36a8a exist?

**Comment by Chivolta** [comment]
@jichenjc I'm using latest version: cinder-csi-plugin.
Yes, I'm using gp-ssd. 
Volume type 50e93175-8574-44a3-aa18-0c54b4e36a8a does not exist.
I'm using also other availability zone than nova.

openstack volume type list
+--------------------------------------+-------------+-----------+
| ID                                   | Name        | Is Public |
+--------------------------------------+-------------+-----------+
| 87e97c81-b9b0-499a-8c53-58035453cb76 | multiattach | True      |
| 9f1b069e-c0ee-4c1c-88ef-8ee2eb69f9f8 | gp-ssd      | True      |
| 88495390-d577-4646-9d20-d4862b74138e | gp-hdd      | True      |
| 2cebe2f8-1115-4952-98aa-a8f750052a17 | io-nvme     | True      |
+--------------------------------------+-------------+-----------+

**Comment by jichenjc** [comment]
@Chivolta which version are you using ? see my test result below, the question here is 
`volume_type` is missing in your logs , are you using latest one or which version are you working on ?

```
I0902 03:45:20.004180       1 utils.go:79] GRPC call: /csi.v1.Controller/CreateVolume
I0902 03:45:20.004244       1 utils.go:80] GRPC request: name:"pvc-dc3e4134-f04b-4361-a84e-592f4e71124e" capacity_range:<required_bytes:1073741824 > volume_capabilities:<mount:<fs_type:"ext4" > access_mode:<mode:SINGLE_NODE_WRITER > > parameters:<key:"type" value:"magnumtype" >
I0902 03:45:20.004503       1 openstack_volumes.go:108] OpenStack Request URL: GET https://hdc-prod-cloud.hursley.ibm.com:8776/v3/07962130d7044e3c84e1825859d5bef9/volumes/detail?name=pvc-dc3e4134-f04b-4361-a84e-592f4e71124e
I0902 03:45:20.004531       1 openstack_volumes.go:108] OpenStack Request Headers:
I0902 03:45:20.004536       1 openstack_volumes.go:108] Accept: application/json
I0902 03:45:20.004550       1 openstack_volumes.go:108] User-Agent: cinder-csi-plugin/latest gophercloud/2.0.0
I0902 03:45:20.004556       1 openstack_volumes.go:108] X-Auth-Token: ***
I0902 03:45:20.335821       1 openstack_volumes.go:108] OpenStack Response Code: 200
I0902 03:45:20.335926       1 openstack_volumes.go:108] OpenStack Response Headers:

I0902 03:45:20.335926       1 openstack_volumes.go:108] OpenStack Response Headers:
I0902 03:45:20.335943       1 openstack_volumes.go:108] Content-Length: 15
I0902 03:45:20.335948       1 openstack_volumes.go:108] Content-Type: application/json
I0902 03:45:20.335953       1 openstack_volumes.go:108] Date: Wed, 02 Sep 2020 03:45:20 GMT
I0902 03:45:20.335958       1 openstack_volumes.go:108] Openstack-Api-Version: volume 3.0
I0902 03:45:20.335962       1 openstack_volumes.go:108] Server: Apache/2.4.29 (Ubuntu)
I0902 03:45:20.336010       1 openstack_volumes.go:108] Vary: OpenStack-API-Version
I0902 03:45:20.336027       1 openstack_volumes.go:108] X-Compute-Request-Id: req-aaa5195a-abbb-42d2-a330-c22ab04f9e10
I0902 03:45:20.336036       1 openstack_volumes.go:108] X-Openstack-Request-Id: req-aaa5195a-abbb-42d2-a330-c22ab04f9e10
I0902 03:45:20.336171       1 openstack_volumes.go:108] OpenStack Response Body: {
I0902 03:45:20.336190       1 openstack_volumes.go:108]   "volumes": []
I0902 03:45:20.336195       1 openstack_volumes.go:108] }
I0902 03:45:20.336465       1 openstack_volumes.go:75] OpenStack Request URL: POST https://hdc-prod-cloud.hursley.ibm.com:8776/v3/07962130d7044e3c84e1825859d5bef9/volumes
I0902 03:45:20.336530       1 openstack_volumes.go:75] OpenStack Request Headers:
I0902 03:45:20.336540       1 openstack_volumes.go:75] Accept: application/json
I0902 03:45:20.336546       1 openstack_volumes.go:75] Content-Type: application/json
I0902 03:45:20.336550       1 openstack_volumes.go:75] User-Agent: cinder-csi-plugin/latest gophercloud/2.0.0
I0902 03:45:20.336555       1 openstack_volumes.go:75] X-Auth-Token: ***
I0902 03:45:20.336626       1 openstack_volumes.go:75] OpenStack Request Body: {
I0902 03:45:20.336640       1 openstack_volumes.go:75]   "volume": {
I0902 03:45:20.336661       1 openstack_volumes.go:75]     "description": "Created by OpenStack Cinder CSI driver",
I0902 03:45:20.336677       1 openstack_volumes.go:75]     "metadata": {
I0902 03:45:20.336682       1 openstack_volumes.go:75]       "cinder.csi.openstack.org/cluster": "kubernetes"
I0902 03:45:20.336692       1 openstack_volumes.go:75]     },
I0902 03:45:20.336697       1 openstack_volumes.go:75]     "name": "pvc-dc3e4134-f04b-4361-a84e-592f4e71124e",
I0902 03:45:20.336702       1 openstack_volumes.go:75]     "size": 1,
I0902 03:45:20.336706       1 openstack_volumes.go:75]     "volume_type": "magnumtype"
I0902 03:45:20.336711       1 openstack_volumes.go:75]   }
I0902 03:45:20.336743       1 openstack_volumes.go:75] }
```

**Comment by jichenjc** [comment]
this is your request body
```
I0831 14:51:24.550228 1 openstack_volumes.go:75] OpenStack Request Body: {
I0831 14:51:24.550240 1 openstack_volumes.go:75] "volume": {
I0831 14:51:24.550251 1 openstack_volumes.go:75] "availability_zone": "az1-sse2",
I0831 14:51:24.550261 1 openstack_volumes.go:75] "description": "Created by OpenStack Cinder CSI driver",
I0831 14:51:24.550272 1 openstack_volumes.go:75] "metadata": {
I0831 14:51:24.550283 1 openstack_volumes.go:75] "cinder.csi.openstack.org/cluster": "kubernetes"
I0831 14:51:24.550295 1 openstack_volumes.go:75] },
I0831 14:51:24.550306 1 openstack_volumes.go:75] "name": "pvc-a0a25f6e-e43e-45ed-b1b9-4be078fd23fd",
I0831 14:51:24.550316 1 openstack_volumes.go:75] "size": 1
I0831 14:51:24.550327 1 openstack_volumes.go:75] }
```

**Comment by jichenjc** [comment]
I am not aware cinder az is related to cinder volume type...

**Comment by ramineni** [comment]
@Chivolta Could you share your pvc and storageclass yamls you are using ?

**Comment by Chivolta** [comment]
```
[root@test ~]# cinder version-list
WARNING:cinderclient.shell:API version 3.60 requested,
WARNING:cinderclient.shell:downgrading to 3.59 based on server support.
Client supported API versions:
Minimum version 3.0
Maximum version 3.60

Server supported API versions:
+------+------------+----------------------+-------------+---------+
| Id   | Status     | Updated              | Min Version | Version |
+------+------------+----------------------+-------------+---------+
| v2.0 | DEPRECATED | 2017-02-25T12:00:00Z |             |         |
| v3.0 | CURRENT    | 2018-07-17T00:00:00Z | 3.0         | 3.59    |
+------+------------+----------------------+-------------+---------+
```

PVC:
```
  volumeClaimTemplates:
  - metadata:
      name: www-test
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: csi-cinder-sc-retain
      resources:
        requests:
          storage: 1Gi
```
I'm trying a lot of combination of SC configuration.

```
[root@test ~]# kubectl describe sc csi-cinder-sc-retain
Name:            csi-cinder-sc-retain
IsDefaultClass:  No
Annotations:     kubectl.kubernetes.io/last-applied-configuration={"allowVolumeExpansion":true,"apiVersion":"storage.k8s.io/v1","kind":"StorageClass","metadata":{"annotations":{"meta.helm.sh/release-name":"cinder-csi","meta.helm.sh/release-namespace":"kube-system"},"creationTimestamp":"2020-08-31T15:11:54Z","labels":{"app.kubernetes.io/managed-by":"Helm"},"managedFields":[{"apiVersion":"storage.k8s.io/v1","fieldsType":"FieldsV1","fieldsV1":{"f:allowVolumeExpansion":{},"f:metadata":{"f:annotations":{".":{},"f:kubectl.kubernetes.io/last-applied-configuration":{},"f:meta.helm.sh/release-name":{},"f:meta.helm.sh/release-namespace":{}},"f:labels":{".":{},"f:app.kubernetes.io/managed-by":{}}},"f:parameters":{".":{},"f:availability":{}},"f:provisioner":{},"f:reclaimPolicy":{},"f:volumeBindingMode":{}},"manager":"kubectl","operation":"Update","time":"2020-08-31T15:11:54Z"}],"name":"csi-cinder-sc-retain","resourceVersion":"920208","selfLink":"/apis/storage.k8s.io/v1/storageclasses/csi-cinder-sc-retain","uid":"943dfe53-3474-461f-b8c3-fd43165b997c"},"parameters":{"volume_type":"gp-ssd"},"provisioner":"cinder.csi.openstack.org","reclaimPolicy":"Retain","volumeBindingMode":"Immediate"}
,meta.helm.sh/release-name=cinder-csi,meta.helm.sh/release-namespace=kube-system
Provisioner:           cinder.csi.openstack.org
Parameters:            volume_type=gp-ssd
AllowVolumeExpansion:  True
MountOptions:          <none>
ReclaimPolicy:         Retain
VolumeBindingMode:     Immediate
Events:                <none>
```

**Comment by ramineni** [comment]
@Chivolta The parameters of storage class , it should be type = gp-ssd , not volume_type. Code recongnizes type parameter.
https://github.com/kubernetes/cloud-provider-openstack/blob/master/pkg/csi/cinder/controllerserver.go#L64

**Comment by Chivolta** [comment]
It works!!!! Thank you @ramineni
