### ISSUE TITLE
[cinder-csi-plugin] upgrade charts to 1.19 after 1.19 GA

### ISSUE THREAD

**Issue by jichenjc** [kubernetes/cloud-provider-openstack#1183]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
> /kind bug
> /kind feature

**What happened**:
need upgrade charts to 1.19 for cinder-csi-plugin

**What you expected to happen**:

**How to reproduce it**:

**Anything else we need to know?**:

**Environment**:
- openstack-cloud-controller-manager(or other related binary) version:
- OpenStack version:
- Others:

**Comment by ramineni** [comment]
fixed in https://github.com/kubernetes/cloud-provider-openstack/pull/1199
/close
