### ISSUE TITLE
[cinder-csi-plugin] Failed to mount volume to pod on HyperV VM

### ISSUE THREAD

**Issue by peterrosell** [kubernetes/cloud-provider-openstack#1192]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug

**What happened**:
The volume is not mounted to the pod and got error message, `Unable to find Device path for volume`. After changing the log level of the node plugin to `-v=4` I get this in the log:
```
I0908 22:19:22.200863       1 mount.go:178] Failed to find device for the volumeID: "9dc29d58-3d78-47ff-b976-043d7e0be5b5" by serial ID
I0908 22:19:22.311823       1 metadata.go:187] Attempting to fetch metadata from http://169.254.169.254/openstack/latest/meta_data.json
I0908 22:19:23.940241       1 metadata.go:219] Found disk metadata for volumeID "9dc29d58-3d78-47ff-b976-043d7e0be5b5". Bus: "scsi", Address: "0:0:0:2"
I0908 22:19:23.940333       1 metadata.go:236] expecting to find one disk path for volumeID "9dc29d58-3d78-47ff-b976-043d7e0be5b5", found 0: []
I0908 22:19:23.940345       1 metadata.go:242] Could not retrieve device metadata for volumeID: "9dc29d58-3d78-47ff-b976-043d7e0be5b5"
E0908 22:19:23.940353       1 utils.go:84] GRPC error: rpc error: code = Internal desc = Unable to find Device path for volume
```
I can see in Openstack that the volume is created in the correct availability zone and attached to the node. The disk shows up on the node as `dev/sdc` and the PVC get bound to a PV.
When looking in the code at https://github.com/kubernetes/cloud-provider-openstack/blob/master/pkg/util/metadata/metadata.go#L223
I see that it search for a disk with pattern `/dev/disk/by-path/*-%s-%s", device.Bus, device.Address`
The metadata in openstack gives this info about the disk `{"type": "disk", "serial": "9dc29d58-3d78-47ff-b976-043d7e0be5b5", "bus": "scsi", "address": "0:0:0:2", "tags": []}`
and that will make the pattern compile to `/dev/disk/by-path/*-scsi-0:0:0:2`
when looking on that path on the node I see that `/dev/sdc` has another pattern
`acpi-VMBUS:00-vmbus-8d38ceb678f042ddb67407c98652e9d1-lun-2 -> ../../sdc`

**What you expected to happen**:
Expected behavior is that the volume is mounted to the pod. 

**How to reproduce it**:
Created a new cluster with Magnum. Use the [manifests](https://github.com/kubernetes/cloud-provider-openstack/tree/master/manifests/cinder-csi-plugin) in this repo to deploy the cinder-csi-plugin. I also enabled Topology support (`--feature-gates=Topology=true` as argument to csi-provisioner). Otherwise the volume didn't end up in the correct availabilty zone and it failed. Create a storage class.
Create a PVC using that storageclass and create a pod that mounts that PVC.
See below for the environment to use.

**Environment**:
- openstack-cloud-controller-manager(or other related binary) version:
- OpenStack version: Stein
- Openstack hypervisor: Hyper-V
- OS image: fedora-coreos 32.20200809.3.0
- Magnum: Train
- Kubernetes: 1.18.2
- Cloud-provider: 1.18.0
- Images (via the manifests):
  - docker.io/k8scloudprovider/cinder-csi-plugin:latest
  - quay.io/k8scsi/csi-provisioner:v1.6.0

**Comment by jichenjc** [comment]
it tried to get device here first
https://github.com/kubernetes/cloud-provider-openstack/blob/master/pkg/csi/cinder/nodeserver.go#L543

then get from here
https://github.com/kubernetes/cloud-provider-openstack/blob/master/pkg/util/mount/mount.go#L150

do you have simliar things created in `/dev/disk/by-id` from your env? 

maybe that will us clue what to be added..

**Comment by peterrosell** [comment]
On a node I have these links in the directory `/dev/disk/by-path`. This is a newly started server without any volume mounted. When a volume is mounted it follows the same pattern.
```
[core@k8s-qjdh2zyfn2fh-master-2 by-path]$ ls -al
total 0
drwxr-xr-x. 2 root root 160  9 sep 14.36 .
drwxr-xr-x. 8 root root 160  9 sep 14.36 ..
lrwxrwxrwx. 1 root root   9  9 sep 14.37 acpi-VMBUS:00-vmbus-0936c61183c34c30a11d258f594097a0-lun-0 -> ../../sda
lrwxrwxrwx. 1 root root  10  9 sep 14.37 acpi-VMBUS:00-vmbus-0936c61183c34c30a11d258f594097a0-lun-0-part1 -> ../../sda1
lrwxrwxrwx. 1 root root  10  9 sep 14.37 acpi-VMBUS:00-vmbus-0936c61183c34c30a11d258f594097a0-lun-0-part2 -> ../../sda2
lrwxrwxrwx. 1 root root  10  9 sep 14.37 acpi-VMBUS:00-vmbus-0936c61183c34c30a11d258f594097a0-lun-0-part3 -> ../../sda3
lrwxrwxrwx. 1 root root  10  9 sep 14.37 acpi-VMBUS:00-vmbus-0936c61183c34c30a11d258f594097a0-lun-0-part4 -> ../../sda4
lrwxrwxrwx. 1 root root   9  9 sep 14.37 acpi-VMBUS:00-vmbus-0936c61183c34c30a11d258f594097a0-lun-1 -> ../../sdb
```

**Comment by peterrosell** [comment]
This page points to that the naming (vmbus) is related to Hyper-V. https://docs.microsoft.com/en-us/virtualization/hyper-v-on-windows/reference/hyper-v-architecture.

when I mount a volume to the instance i Openstack it shows like this in the `by-path` directory.
```
lrwxrwxrwx. 1 root root   9 10 sep 09.47 acpi-VMBUS:00-vmbus-0936c61183c34c30a11d258f594097a0-lun-2 -> ../../sdc
```
The output from the metadata service looks like this:
```json
{
  "uuid": "a83ade9d-d3a5-4fe5-b6df-7f5e1bc6b86c",
  "hostname": "k8s-qjdh2zyfn2fh-master-2.openstack.example.",
  "name": "k8s-qjdh2zyfn2fh-master-2",
  "launch_index": 0,
  "availability_zone": "linux",
  "random_seed": "rz7...pSUSwdI=",
  "project_id": "184b60d4cd2c41899f33111f31d2c878",
  "devices": [
    {
      "type": "disk",
      "serial": "8896961b-0fa3-4158-8059-c59d9c8c000a",
      "bus": "scsi",
      "address": "0:0:0:1",
      "tags": []
    },
    {
      "type": "disk",
      "serial": "f9e79588-a3f5-4255-9522-a7ef463f06f2",
      "bus": "scsi",
      "address": "0:0:0:2",
      "tags": []
    }
  ]
}
```
I'm quite new to Openstack and Hyper-V so I'm not sure if it's correct to just use the number from `address` and map it to a regex like `.*lun-<address-number>$`

**Comment by jichenjc** [comment]
I missed the point `Hyper-V` at beginning of the issue , I guess that's the key factor here, thanks for pointing that out ~

basically, I guess (not 100% sure) no one tried hyper-v before on CPO, seems it's just naming convention from kvm perspective on existing code while hyper-v using different device format, maybe we can add the hyper-v format into code then return if we find it , the question here is it might need further test on other aspects regarding hyper-v

**Comment by peterrosell** [comment]
I missed that the code you referred to searched for `by-id` and not `by-path`.
In the directory `by-id` I see the this info: (new machine so new ids, the disk mounted by kube is `sdb`)
```
[core@k8s-qjdh2zyfn2fh-node-1 by-id]$ ls -la
total 0
drwxr-xr-x. 2 root root 400 10 sep 11.55 .
drwxr-xr-x. 8 root root 160 10 sep 09.25 ..
lrwxrwxrwx. 1 root root   9 10 sep 12.02 scsi-14d5346542020202078a0cc6cd981ba42b2aedb7172d4a5a1 -> ../../sdb
lrwxrwxrwx. 1 root root   9 10 sep 12.02 scsi-14d53465420202020ee5ab126e91311ea85b6b7c51510a9d1 -> ../../sda
lrwxrwxrwx. 1 root root  10 10 sep 12.02 scsi-14d53465420202020ee5ab126e91311ea85b6b7c51510a9d1-part1 -> ../../sda1
lrwxrwxrwx. 1 root root  10 10 sep 12.02 scsi-14d53465420202020ee5ab126e91311ea85b6b7c51510a9d1-part2 -> ../../sda2
lrwxrwxrwx. 1 root root  10 10 sep 12.02 scsi-14d53465420202020ee5ab126e91311ea85b6b7c51510a9d1-part3 -> ../../sda3
lrwxrwxrwx. 1 root root  10 10 sep 12.02 scsi-14d53465420202020ee5ab126e91311ea85b6b7c51510a9d1-part4 -> ../../sda4
lrwxrwxrwx. 1 root root   9 10 sep 12.02 scsi-36002248078a0cc6cd981db7172d4a5a1 -> ../../sdb
lrwxrwxrwx. 1 root root   9 10 sep 12.02 scsi-360022480ee5ab126e913b7c51510a9d1 -> ../../sda
lrwxrwxrwx. 1 root root  10 10 sep 12.02 scsi-360022480ee5ab126e913b7c51510a9d1-part1 -> ../../sda1
lrwxrwxrwx. 1 root root  10 10 sep 12.02 scsi-360022480ee5ab126e913b7c51510a9d1-part2 -> ../../sda2
lrwxrwxrwx. 1 root root  10 10 sep 12.02 scsi-360022480ee5ab126e913b7c51510a9d1-part3 -> ../../sda3
lrwxrwxrwx. 1 root root  10 10 sep 12.02 scsi-360022480ee5ab126e913b7c51510a9d1-part4 -> ../../sda4
lrwxrwxrwx. 1 root root   9 10 sep 12.02 wwn-0x6002248078a0cc6cd981db7172d4a5a1 -> ../../sdb
lrwxrwxrwx. 1 root root   9 10 sep 12.02 wwn-0x60022480ee5ab126e913b7c51510a9d1 -> ../../sda
lrwxrwxrwx. 1 root root  10 10 sep 12.02 wwn-0x60022480ee5ab126e913b7c51510a9d1-part1 -> ../../sda1
lrwxrwxrwx. 1 root root  10 10 sep 12.02 wwn-0x60022480ee5ab126e913b7c51510a9d1-part2 -> ../../sda2
lrwxrwxrwx. 1 root root  10 10 sep 12.02 wwn-0x60022480ee5ab126e913b7c51510a9d1-part3 -> ../../sda3
lrwxrwxrwx. 1 root root  10 10 sep 12.02 wwn-0x60022480ee5ab126e913b7c51510a9d1-part4 -> ../../sda4
```
I also now noticed that the `serial` value of the device in the meta-data contains the volume's id that Openstack specifies and not the serial number of the disk.
```json
{
  "uuid": "1c1d5532-fc34-4ba7-bf8f-7181ced3dcee",
  "hostname": "k8s-qjdh2zyfn2fh-node-1.openstack.example.",
  "name": "k8s-qjdh2zyfn2fh-node-1",
  "launch_index": 0,
  "availability_zone": "linux",
  "random_seed": "cfRwi....XlMI=",
  "project_id": "184b60d4cd2c41899f33111f31d2c878",
  "devices": [
    {
      "type": "disk",
      "serial": "a55a17fe-fd36-43df-a5bf-100256c92c52",
      "bus": "scsi",
      "address": "0:0:0:1",
      "tags": []
    }
  ]
}
```
So that's why it doesn't match. I don't know if this is a bug in the Hyper-V integration with the meta-data server or if it's a correct behavior. Do you have any knowledge about how the meta data server works and integrates with the disks?

**Comment by jichenjc** [comment]
I knew metadata server mechanism and API behind it ,but I don't know the Hyper-V integraiton and whether there's anything special to KVM, so I need check more here or maybe someone already know it can comment

**Comment by peterrosell** [comment]
I read thru the code even more and followed the flow of how a device path is found. I ended up at this comment:
```
	// Nova Hyper-V hosts cannot override disk SCSI IDs. In order to locate
	// volumes, we're querying the metadata service. Note that the Hyper-V
	// driver will include device metadata for untagged volumes as well.
```
https://github.com/kubernetes/cloud-provider-openstack/blob/master/pkg/util/metadata/metadata.go#L204

In the log of the nodeplugin I get several lines like this for 30 seconds before it continues to find the device path from the metadata server.
```
I0908 22:19:22.200863       1 mount.go:178] Failed to find device for the volumeID: "9dc29d58-3d78-47ff-b976-043d7e0be5b5" by serial ID
```

So I guess that the serial value can't be used on Hyper-V and instead the nodeplugin try to find it via the metadata server.
The problem here is that our disks don't matches `*-scsi-0:0:0:2` (values from metadata).
I created a customer version that handled the format `*-lun-<address-id>` and then the volume got mounted correctly into the pod. Here is a branch of the code, https://github.com/pagero/cloud-provider-openstack/commit/41d0b12a54642af09acce3639b118f0ee3078523.
I'm not sure about the format of the soft link. I have manually tested to create up to 17 volumes to a node and it follows the implemented pattern. It would be good to have find some documentation about the naming of the soft link and how it relates to address before creating a PR.

**Comment by peterrosell** [comment]
I went a bit further down the rabbit hole and looked into udev in systemd which is responsible for creating the soft links in `/dev/disk/by-path` and found this method that generates the link. https://github.com/systemd/systemd/blob/c6552f7cd574a693d921176796057b50ced2b4f5/src/udev/udev-builtin-path_id.c#L375
The code generates a name that ends with `vmbus-<guid>-<lun>` where `lun` is build up from `"lun-"<lun-number>`.

A volume/disk shows up as a system device on this path `/sys/devices/LNXSYSTM:00/LNXSYBUS:00/ACPI0004:00/VMBUS:00/216abb18-f151-45cc-a3b5-a981b815575a/host0/target0:0:0/0:0:0:2`
and the link in `by-path` is created like this `acpi-VMBUS:00-vmbus-216abb18f15145cca3b5a981b815575a-lun-2`.

Looking into the storage driver it look like max luns is 255 so the implementation I did in my branch. Ref. https://github.com/torvalds/linux/blob/master/drivers/scsi/storvsc_drv.c#L404

**Comment by jichenjc** [comment]
@peterrosell thanks for detailed analysis, I see no reason to not include the fix in your local branch in the master , as it add special check to Hyper-V devices because of its special generate rules and won't affect other platform such as KVM .. so can you help to make a PR with your local branch? Thanks

**Comment by ramineni** [comment]
> 36002248078a0cc6cd981db7172d4a5a1

@peterrosell Where exactly  volume ID: `9dc29d58-3d78-47ff-b976-043d7e0be5b5` is mounted ? could you paste again which file in `by-id` corresponds to this volume  ?  It would be good to add one for HyperV here as did for other hypervisors, https://github.com/kubernetes/cloud-provider-openstack/blob/master/pkg/util/mount/mount.go#L150

**Comment by peterrosell** [comment]
The problem is that the id that shows up under `by-id` is the serial number of the disk and that's what you expect to be in the metadata's `devices/serial`, but it isn't. It contains the Openstack uuid of the volume. Instead I tried to use the last number in the address and concatenate it with `lun`, but that doesn't always seem to work.
I have now got an answer from hosting company's Openstack provider and they have looked at this PR and said that I shall use `/sys/bus/scsi/devices/<metadata:devices/address>` instead, but the address in that directory is `4:0:0:0` and the metadata shows `0:0:0:0` so they don't match. Searching for `0:0:0:0` (`find /sys | grep 0:0:0:0`) doesn't find anything. I will return a question to them and hope for a better suggestion or if someone here have the ultimate solution. :-)

This is how it looks when I have mounted two SCIS disks (`/dev/sdc`, `/dev/sdd`).
**Metadata**
```
peterr-cinder:/dev/disk$ curl -s http://169.254.169.254/openstack/latest/meta_data.json | jq '.'
{
  "uuid": "5a2e77f7-2b1f-4aa9-90f1-d827e98b6e6a",
  "public_keys": {
    "deploy-key": "ssh-rsa ..."
  },
  "keys": [
    {
      "name": "deploy-key",
      "type": "ssh",
      "data": "ssh-rsa ..."
    }
  ],
  "hostname": "peterr-cinder.openstack.example.",
  "name": "peterr-cinder",
  "launch_index": 0,
  "availability_zone": "linux",
  "random_seed": "...",
  "project_id": "184b60d4cd2c41899f33111f31d2c878",
  "devices": [
    {
      "type": "disk",
      "serial": "dfb229e3-2370-4ace-a880-f35ede11cb0b",
      "bus": "ide",
      "address": "0:0",
      "tags": []
    },
    {
      "type": "disk",
      "serial": "3e55d7c5-05f0-4bb1-96c8-7633ee23075d",
      "bus": "scsi",
      "address": "0:0:0:0",
      "tags": []
    },
    {
      "type": "disk",
      "serial": "f9e79588-a3f5-4255-9522-a7ef463f06f2",
      "bus": "scsi",
      "address": "0:0:0:1",
      "tags": []
    }
  ]
}
```

**by-id**
```
peterr-cinder:/dev/disk$ ls -al by-id
total 0
drwxr-xr-x 2 root root 460 Sep 25 07:48 .
drwxr-xr-x 8 root root 160 Sep 25 06:50 ..
lrwxrwxrwx 1 root root   9 Sep 25 06:51 scsi-14d534654202020204e158ef4fefb11eaabb8b9ebe280f7a0 -> ../../sdb
lrwxrwxrwx 1 root root  10 Sep 25 06:51 scsi-14d534654202020204e158ef4fefb11eaabb8b9ebe280f7a0-part1 -> ../../sdb1
lrwxrwxrwx 1 root root  11 Sep 25 06:51 scsi-14d534654202020204e158ef4fefb11eaabb8b9ebe280f7a0-part14 -> ../../sdb14
lrwxrwxrwx 1 root root  11 Sep 25 06:51 scsi-14d534654202020204e158ef4fefb11eaabb8b9ebe280f7a0-part15 -> ../../sdb15
lrwxrwxrwx 1 root root   9 Sep 25 06:51 scsi-14d5346542020202056acbaecfefb11eaa4868724fbebad4c -> ../../sda
lrwxrwxrwx 1 root root   9 Sep 25 07:48 scsi-14d534654202020208307db64d0d08148859c36b3edb7d683 -> ../../sdd
lrwxrwxrwx 1 root root   9 Sep 25 07:42 scsi-14d53465420202020a0794cfec480d74faf0df496c60345a6 -> ../../sdc
lrwxrwxrwx 1 root root   9 Sep 25 06:51 scsi-3600224804e158ef4fefbb9ebe280f7a0 -> ../../sdb
lrwxrwxrwx 1 root root  10 Sep 25 06:51 scsi-3600224804e158ef4fefbb9ebe280f7a0-part1 -> ../../sdb1
lrwxrwxrwx 1 root root  11 Sep 25 06:51 scsi-3600224804e158ef4fefbb9ebe280f7a0-part14 -> ../../sdb14
lrwxrwxrwx 1 root root  11 Sep 25 06:51 scsi-3600224804e158ef4fefbb9ebe280f7a0-part15 -> ../../sdb15
lrwxrwxrwx 1 root root   9 Sep 25 06:51 scsi-36002248056acbaecfefb8724fbebad4c -> ../../sda
lrwxrwxrwx 1 root root   9 Sep 25 07:48 scsi-3600224808307db64d0d036b3edb7d683 -> ../../sdd
lrwxrwxrwx 1 root root   9 Sep 25 07:42 scsi-360022480a0794cfec480f496c60345a6 -> ../../sdc
lrwxrwxrwx 1 root root   9 Sep 25 06:51 wwn-0x600224804e158ef4fefbb9ebe280f7a0 -> ../../sdb
lrwxrwxrwx 1 root root  10 Sep 25 06:51 wwn-0x600224804e158ef4fefbb9ebe280f7a0-part1 -> ../../sdb1
lrwxrwxrwx 1 root root  11 Sep 25 06:51 wwn-0x600224804e158ef4fefbb9ebe280f7a0-part14 -> ../../sdb14
lrwxrwxrwx 1 root root  11 Sep 25 06:51 wwn-0x600224804e158ef4fefbb9ebe280f7a0-part15 -> ../../sdb15
lrwxrwxrwx 1 root root   9 Sep 25 06:51 wwn-0x6002248056acbaecfefb8724fbebad4c -> ../../sda
lrwxrwxrwx 1 root root   9 Sep 25 07:48 wwn-0x600224808307db64d0d036b3edb7d683 -> ../../sdd
lrwxrwxrwx 1 root root   9 Sep 25 07:42 wwn-0x60022480a0794cfec480f496c60345a6 -> ../../sdc
```

**by-path**
```
peterr-cinder:/dev/disk$ ls -al by-path
total 0
drwxr-xr-x 2 root root 180 Sep 25 07:48 .
drwxr-xr-x 8 root root 160 Sep 25 06:50 ..
lrwxrwxrwx 1 root root   9 Sep 25 06:51 acpi-VMBUS:01-vmbus-00000000000088990000000000000000-lun-0 -> ../../sdb
lrwxrwxrwx 1 root root  10 Sep 25 06:51 acpi-VMBUS:01-vmbus-00000000000088990000000000000000-lun-0-part1 -> ../../sdb1
lrwxrwxrwx 1 root root  11 Sep 25 06:51 acpi-VMBUS:01-vmbus-00000000000088990000000000000000-lun-0-part14 -> ../../sdb14
lrwxrwxrwx 1 root root  11 Sep 25 06:51 acpi-VMBUS:01-vmbus-00000000000088990000000000000000-lun-0-part15 -> ../../sdb15
lrwxrwxrwx 1 root root   9 Sep 25 06:51 acpi-VMBUS:01-vmbus-00000001000088990000000000000000-lun-0 -> ../../sda
lrwxrwxrwx 1 root root   9 Sep 25 07:42 acpi-VMBUS:01-vmbus-081161c84c2c4d1fa27d97e9f783f277-lun-0 -> ../../sdc
lrwxrwxrwx 1 root root   9 Sep 25 07:48 acpi-VMBUS:01-vmbus-081161c84c2c4d1fa27d97e9f783f277-lun-1 -> ../../sdd
```

**/sys/bus/scsi/devices**
```
peterr-cinder:/dev/disk$ ls -al /sys/bus/scsi/devices/
total 0
drwxr-xr-x 2 root root 0 Sep 25 06:50 .
drwxr-xr-x 4 root root 0 Sep 25 06:50 ..
lrwxrwxrwx 1 root root 0 Sep 25 06:50 2:0:0:0 -> ../../../devices/LNXSYSTM:00/LNXSYBUS:00/PNP0A03:00/device:07/VMBUS:01/00000000-0000-8899-0000-000000000000/host2/target2:0:0/2:0:0:0
lrwxrwxrwx 1 root root 0 Sep 25 06:50 3:0:0:0 -> ../../../devices/LNXSYSTM:00/LNXSYBUS:00/PNP0A03:00/device:07/VMBUS:01/00000001-0000-8899-0000-000000000000/host3/target3:0:0/3:0:0:0
lrwxrwxrwx 1 root root 0 Sep 25 07:42 4:0:0:0 -> ../../../devices/LNXSYSTM:00/LNXSYBUS:00/PNP0A03:00/device:07/VMBUS:01/081161c8-4c2c-4d1f-a27d-97e9f783f277/host4/target4:0:0/4:0:0:0
lrwxrwxrwx 1 root root 0 Sep 25 07:48 4:0:0:1 -> ../../../devices/LNXSYSTM:00/LNXSYBUS:00/PNP0A03:00/device:07/VMBUS:01/081161c8-4c2c-4d1f-a27d-97e9f783f277/host4/target4:0:0/4:0:0:1
lrwxrwxrwx 1 root root 0 Sep 25 06:50 host0 -> ../../../devices/pci0000:00/0000:00:07.1/ata1/host0
lrwxrwxrwx 1 root root 0 Sep 25 06:50 host1 -> ../../../devices/pci0000:00/0000:00:07.1/ata2/host1
lrwxrwxrwx 1 root root 0 Sep 25 06:50 host2 -> ../../../devices/LNXSYSTM:00/LNXSYBUS:00/PNP0A03:00/device:07/VMBUS:01/00000000-0000-8899-0000-000000000000/host2
lrwxrwxrwx 1 root root 0 Sep 25 06:50 host3 -> ../../../devices/LNXSYSTM:00/LNXSYBUS:00/PNP0A03:00/device:07/VMBUS:01/00000001-0000-8899-0000-000000000000/host3
lrwxrwxrwx 1 root root 0 Sep 25 06:50 host4 -> ../../../devices/LNXSYSTM:00/LNXSYBUS:00/PNP0A03:00/device:07/VMBUS:01/081161c8-4c2c-4d1f-a27d-97e9f783f277/host4
lrwxrwxrwx 1 root root 0 Sep 25 06:50 target2:0:0 -> ../../../devices/LNXSYSTM:00/LNXSYBUS:00/PNP0A03:00/device:07/VMBUS:01/00000000-0000-8899-0000-000000000000/host2/target2:0:0
lrwxrwxrwx 1 root root 0 Sep 25 06:50 target3:0:0 -> ../../../devices/LNXSYSTM:00/LNXSYBUS:00/PNP0A03:00/device:07/VMBUS:01/00000001-0000-8899-0000-000000000000/host3/target3:0:0
lrwxrwxrwx 1 root root 0 Sep 25 07:43 target4:0:0 -> ../../../devices/LNXSYSTM:00/LNXSYBUS:00/PNP0A03:00/device:07/VMBUS:01/081161c8-4c2c-4d1f-a27d-97e9f783f277/host4/target4:0:0
```

**Comment by lingxiankong** [comment]
/close

See decision in the PR.
