### ISSUE TITLE
[manila-csi-plugin] Unable add Helm repo for manila-csi

### ISSUE THREAD

**Issue by JPRbrs** [kubernetes/cloud-provider-openstack#1193]
/kind bug

**What happened**: I'm unable to add the helm repo for manila-csi-plugin following instructions in  [github pages readme](https://github.com/kubernetes/cloud-provider-openstack/blob/gh-pages/README.md)

> Error: Looks like "https://kubernetes.github.io/cloud-provider-openstack" is not a valid chart repository or cannot be reached: Failed to fetch https://kubernetes.github.io/cloud-provider-openstack/index.yaml : 404 Not Found

**What you expected to happen**: Helm repo is installed when issuing the following command:

`helm repo add cpo https://kubernetes.github.io/cloud-provider-openstack`

**How to reproduce it**:
issue the command below:
`https://github.com/kubernetes/cloud-provider-openstack/blob/gh-pages/README.md`

**Anything else we need to know?**:
As stated in the official [documentation](www.helm.sh/docs/topics/chart_repository) A valid chart repository must have an index file but I've noticed that the index.yaml file was recently removed in [PR 1191](https://github.com/kubernetes/cloud-provider-openstack/pull/1191), can that be the cause?

**Environment**:
- Helm: Client: &version.Version{SemVer:"v2.14.1", GitCommit:"5270352a09c7e8b6e8c9593002a73535276507c0", GitTreeState:"clean"}

**Comment by gman0** [comment]
@jichenjc @brtknr Can you guys please have a look?

**Comment by jichenjc** [comment]
not helm expert but took a quick look and the official doc did indicate it need index.yaml
and #1191 we created an index.html and removed empty index.yaml
so maybe that's the root cause 

@brtknr I noticed you link #1190 can solve this issue but it only do the bump version
will that help or we still need create index.yaml?
