### ISSUE TITLE
[manila-csi-plugin] Update csi-snapshotter sidecar to v2

### ISSUE THREAD

**Issue by gman0** [kubernetes/cloud-provider-openstack#1194]
manila-csi-plugin currently uses csi-snapshotter v1.2.2. Its support ends with Kubernetes v1.20.0. We'll need to update csi-snapshotter to v2 before CPO's v1.20.0 release.

/cc @tombarron @gouthampacha @Fedosin

**Comment by jichenjc** [comment]
#974 might be good thing to refer to

**Comment by gman0** [comment]
@jichenjc Yes, thanks!
