### ISSUE TITLE
[occm] Unknown attributes for argument listener_.listener

### ISSUE THREAD

**Issue by dirien** [kubernetes/cloud-provider-openstack#1196]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:
Installed the occm on a k3s cluster, i  get following error message in the  logs

`I0910 22:09:01.209287       1 event.go:291] "Event occurred" object="kube-system/traefik" kind="Service" apiVersion="v1" type="Warning" reason="SyncLoadBalancerFailed" message="Error syncing load balancer: failed to ensure load balancer: failed to create listener for loadbalancer 73e6cb61-0339-40eb-a5b8-47eb8fbc1627: Bad request with: [POST https://xxx:9876/v2.0/lbaas/listeners], error message: {\"debuginfo\": null, \"faultcode\": \"Client\", \"faultstring\": \"Unknown attributes for argument listener_.listener: timeout_member_connect, timeout_member_data, timeout_tcp_inspect, timeout_client_data\"}"
`

**What you expected to happen**:

The Listenere gets created

**Environment**:
- openstack-cloud-controller-manager(or other related binary) version:  latest
- OpenStack version:
- Others:

**Comment by lingxiankong** [comment]
May I know the Octavia service release version?

**Comment by dirien** [comment]
hi @lingxiankong , thanks for the help:

`| RegionOne   | load-balancer  | 2.0     | CURRENT    `

strangely, using the cloud provider works for k8s

**Comment by lingxiankong** [comment]
Not that version, can you send HTTP request to Octavia service like the following and paste the output?

```
http get http://127.0.0.1/load-balancer/ X-Auth-Token:$token
```

**Comment by dirien** [comment]
GET  https://xxx:9876/v2.0/lbaas/loadbalancers

response:

{
    "loadbalancers": [
        {
            "provider": "octavia",
            "description": "",
            "admin_state_up": true,
            "pools": [
                {
                    "id": "b1a91f54-84de-4af8-93c3-fec17af7a114"
                }
            ],
            "created_at": "2019-07-09T12:38:49",
            "provisioning_status": "ACTIVE",
            "updated_at": "2020-09-04T16:20:20",
            "vip_qos_policy_id": null,
            "vip_network_id": "007bedbf-dc21-459b-807e-af503c5db400",
            "listeners": [
                {
                    "id": "9b751c60-cd7c-4bb1-9aed-02657a0cfcdf"
                }
            ],
            "vip_port_id": "b6cbe63f-8c7d-4662-9449-0a143ddc0bff",
            "flavor_id": "",
            "vip_address": "xxxx",
            "vip_subnet_id": "6c9e92bb-e0bc-40d9-94d2-68f0db146196",
            "project_id": "11eb1152f1db4b32835fa823b9df3c05",
            "id": "c634b084-444b-474b-968f-6b0ccd309547",
            "operating_status": "ONLINE",
            "name": "testlb"
        },
....
...
  ],
    "loadbalancers_links": []
}
