### ISSUE TITLE
[cinder-csi-plugin] avoid default size in ephemeral disk 

### ISSUE THREAD

**Issue by jichenjc** [kubernetes/cloud-provider-openstack#1201]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
> /kind bug
> /kind feature

**What happened**:

**What you expected to happen**:

https://github.com/kubernetes/cloud-provider-openstack/blob/master/pkg/csi/cinder/nodeserver.go#L136

will default to 1 if no capacity is given, this is inconsistent to 
https://github.com/kubernetes/cloud-provider-openstack/blob/master/pkg/csi/cinder/nodeserver.go#L63 and doesn't make sense

we should report error instead of use default value if capacity not given

**How to reproduce it**:

**Anything else we need to know?**:

**Environment**:
- openstack-cloud-controller-manager(or other related binary) version:
- OpenStack version:
- Others:

**Comment by ramineni** [comment]
@jichenjc capacity_range is an optional parameter , so plugin may choose the default size if not specified . We are using default volume in CreateVolume here , https://github.com/kubernetes/cloud-provider-openstack/blob/master/pkg/csi/cinder/controllerserver.go#L59 , the same is being followed in ephemeral for consistency . So , I dont think we should raise error here.

**Comment by jichenjc** [comment]
I misread the capability and capactiy... you are right, but we need some doc update for this .. 
to indicate 1 will be default value :)

**Comment by ramineni** [comment]
> I misread the capability and capactiy... you are right, but we need some doc update for this ..
> to indicate 1 will be default value :)

+1 , eventhough its updated here https://github.com/kubernetes/cloud-provider-openstack/blob/master/examples/cinder-csi-plugin/inline/inline-example.yaml#L18 , but I also think its better to add it explicitly in docs. Thanks.

**Comment by ramineni** [comment]
Closing this. Doc update can be added a separate PR.
/close

**Comment by jichenjc** [comment]
@ramineni please note for normal create from PVC, seems no possibility to use defualt value...
```
The PersistentVolumeClaim "csi-pvc-cinderplugin" is invalid: spec.resources[storage]: Required value
```

```--- a/examples/cinder-csi-plugin/nginx.yaml
+++ b/examples/cinder-csi-plugin/nginx.yaml
@@ -16,8 +16,6 @@ spec:
   accessModes:
   - ReadWriteOnce
   resources:
-    requests:
-      storage: 1Gi
   storageClassName: csi-sc-cinderplugin
```
