### ISSUE TITLE
[k8s-keystone-auth] Implement a tracing http roundtripper client

### ISSUE THREAD

**Issue by niedbalski** [kubernetes/cloud-provider-openstack#1207]
Affected binary:  k8s-keystone-auth

/kind feature

**What happened**:

Due to the following bug https://bugs.launchpad.net/charm-kubernetes-worker/+bug/1892067, we
identified that the current log tracing levels aren't enough to diagnose  issues in the communication
to the keystone endpoints.

In particular,  this line https://github.com/kubernetes/cloud-provider-openstack/blob/master/pkg/identity/keystone/keystone.go#L281 doesn't logs any error during the authorization
phase.

Also, would be very helpful to have http connection level tracing in order to see when a connection
is started, finished and or any timeouts ocurred, increasing the logging levels that can be useful when diagnosing issues in the communication to the keystone endpoints at the http level.

**What you expected to happen**:

* We would like to be able to see why an authentication failed in the kslog , why a token authorization failed,
and be able to enable trace level debugging for the http client.

**Comment by kayrus** [comment]
Relates to #993 and #867
