### ISSUE TITLE
[octavia-ingress-controller] support for https backends

### ISSUE THREAD

**Issue by dr4Ke** [kubernetes/cloud-provider-openstack#1221]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
> /kind bug
/kind feature

**What happened**:
Can't use https backends.

**What you expected to happen**:
Would be nice to have similar annotations to allow HTTPS backends, in passthrough or terminated HTTPS form. Similar to the `nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"` used with [ingress-nginx](https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/annotations/#backend-protocol).

Octavia loadbalancers supports traffic to HTTPS backends in two ways:
- [TERMINATED-HTTPS with backend re-encryption](https://docs.openstack.org/octavia/latest/user/guides/basic-cookbook.html#deploy-a-load-balancer-with-backend-re-encryption)
- [HTTPS passthrough](https://docs.openstack.org/octavia/latest/user/guides/basic-cookbook.html#deploy-a-non-terminated-https-load-balancer)

**How to reproduce it**:
N/A

**Anything else we need to know?**:

**Environment**:
- openstack-cloud-controller-manager(or other related binary) version: 1.19.0
- OpenStack version: Train
- Others:

**Comment by lingxiankong** [comment]
Terminated HTTPS is already supported, see https://github.com/kubernetes/cloud-provider-openstack/blob/master/docs/octavia-ingress-controller/using-octavia-ingress-controller.md#enable-tls-encryption.

**Comment by ramineni** [comment]
Feel free to reopen if it doesnt solve the issue.

/close

**Comment by jouvin** [comment]
Hi,

I'm facing the same need as described in this issue and unfortunately https://github.com/kubernetes/cloud-provider-openstack/issues/1221#issuecomment-751426024 is not about the support for https backends (aka SSL passthrough) but the opposite and more standard, TLS-terminated load balancers which speak http to the backend.

Is SSL passthrough supported by octavia-ingress-controller (as said in the issue it seems to be supported by Octavia itself) and in this case what is the annotation to do it?
