### ISSUE TITLE
[cinder-csi-plugin] Helm repo add is not working

### ISSUE THREAD

**Issue by andelhie** [kubernetes/cloud-provider-openstack#1244]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
 /kind bug
> /kind feature

**What happened**:
Tried to add the helm repo per the doc 

**What you expected to happen**:
The helm repo should be added

**How to reproduce it**:
```
helm repo add cpo https://kubernetes.github.io/cloud-provider-openstack
```

**Anything else we need to know?**:
I got this error.
```
Error: looks like "https://kubernetes.github.io/cloud-provider-openstack" is not a valid chart repository or cannot be reached: failed to fetch https://kubernetes.github.io/cloud-provider-openstack/index.yaml : 404 Not Found
```

**Environment**:
- Others: Helm version.BuildInfo{Version:"v3.3.4", GitCommit:"a61ce5633af99708171414353ed49547cf05013d", GitTreeState:"clean", GoVersion:"go1.14.9"}

**Comment by lingxiankong** [comment]
@brtknr Could you please take a look? Same error for me.

**Comment by jichenjc** [comment]
I guess it's caused by 
https://github.com/kubernetes/cloud-provider-openstack/pull/1191

and I remember we had a PR fixed it but failed to find where it is ..

**Comment by jichenjc** [comment]
https://github.com/kubernetes/cloud-provider-openstack/issues/1202 is the simliar bug

**Comment by brtknr** [comment]
The issue has been addressed, index.yaml was generated this morning: https://github.com/kubernetes/cloud-provider-openstack/blob/gh-pages/index.yaml so this should work now. Please close the issue.

**Comment by lingxiankong** [comment]
@andelhie Hi, could you try again and see if it works? Thanks.

**Comment by andelhie** [comment]
@lingxiankong looks to be working again thank you all.
