### ISSUE TITLE
Use the right subnet for security group rules with octavia and loadbalancer.openstack.org/class

### ISSUE THREAD

**Issue by dr4Ke** [kubernetes/cloud-provider-openstack#1251]
Currently, the security group attached to the cluster nodes allows the **default** subnet CIDR.

https://github.com/kubernetes/cloud-provider-openstack/blob/5888bc5002720525d9bedca42da3d0ccbd76ac25/pkg/cloudprovider/providers/openstack/openstack_loadbalancer.go#L2247

When using the `loadbalancer.openstack.org/class` annotation, one can specify other subnets, see configuration below. In this case, the security group should allow the **class** subnet, when it is defined, rather than the **default** one. Similarly than when selecting the LB subnet:

https://github.com/kubernetes/cloud-provider-openstack/blob/5888bc5002720525d9bedca42da3d0ccbd76ac25/pkg/cloudprovider/providers/openstack/openstack_loadbalancer.go#L2342

Configuration:
``` ini
[LoadBalancer]
use-octavia            = true
subnet-id              =  DEFAULT_SUBNET_ID
floating-network-id    = DEFAULT_FLOATING_ID
lb-method              = ROUND_ROBIN
create-monitor         = true
monitor-delay          = 60s
monitor-timeout        = 30s
monitor-max-retries    = 5
manage-security-groups = true

[LoadBalancerClass "class1"]
floating-network-id = CLASS1_FLOATING_ID
subnet-id = CLASS1_SUBNET_ID

[LoadBalancerClass "class2"]
subnet-id = CLASS2_SUBNET_ID
```

**Comment by lingxiankong** [comment]
Hi, not sure if you already have, but please have a look at the description for option `manage-security-groups` in https://github.com/kubernetes/cloud-provider-openstack/blob/master/docs/using-openstack-cloud-controller-manager.md,  when `use-octavia` is enabled, `manage-security-groups` should be false.

**Comment by dr4Ke** [comment]
Hi. I did, indeed. But I find it weird. How do you filter access to the nodeports if you don't manage security groups? I don't like very much the idea of all nodeports being exposed, even though it's only for the subnet.

This page says that it's not supported to manage security groups with octavia, yet it is still possible to do. I guess we should disable it completely for octavia or support it correctly.

**Comment by dr4Ke** [comment]
I may be a little paranoid, but I imagine something like a human error (or just not enough knowledge) leading to expose an internal service (a DB, for example) through a nodePort service inside a cluster. This DB should not be accessed from anywhere else than the cluster itself, by an app exposing a frontend (preferably with end-to-end TLS). Now the DB is accessible from the openstack subnet too, and nothing prevents it.

**Comment by lingxiankong** [comment]
> I may be a little paranoid, but I imagine something like a human error (or just not enough knowledge) leading to expose an internal service (a DB, for example) through a nodePort service inside a cluster. This DB should not be accessed from anywhere else than the cluster itself, by an app exposing a frontend (preferably with end-to-end TLS). Now the DB is accessible from the openstack subnet too, and nothing prevents it.

I need to understand better about your tenant deployment model. If you don't trust all the apps running in the same subnet, why not just splitting them in different subnets?

**Comment by lingxiankong** [comment]
When using Octavia, the goal is to allow amphora (in the same subnet of work nodes) to access the NodePort.

**Comment by greenren** [comment]
Hi, I'm also trying to set up security groups for Octavia to access specific NodePorts. Still figuring out what's possible from the cloud provider, so this discussion is quite useful.

I thought this PR did allow for this functionality: https://github.com/kubernetes/cloud-provider-openstack/pull/491  In the example both `use-octavia` and `manage-security-groups` are true. Am I missing something, @lingxiankong?

**Comment by dr4Ke** [comment]
For now, this controller considers that it's our responsibility to allow access to all nodeports from the LB subnet(s).

**Comment by dr4Ke** [comment]
> > I may be a little paranoid, but I imagine something like a human error (or just not enough knowledge) leading to expose an internal service (a DB, for example) through a nodePort service inside a cluster. This DB should not be accessed from anywhere else than the cluster itself, by an app exposing a frontend (preferably with end-to-end TLS). Now the DB is accessible from the openstack subnet too, and nothing prevents it.
> 
> I need to understand better about your tenant deployment model. If you don't trust all the apps running in the same subnet, why not just splitting them in different subnets?

Well, we have already several subnets in our tenant. One is dedicated to the cluster nodes, another to the publicly exposed load balancers, and another to a private network shared with other tenants for internally published services. I know it's a bit uncommon.

Nevertheless, I think if we had correct security groups management, it would allow any kind of deployment and be more secure by default. If we had the time, we'd try to implement that in a PR. Unfortunately, we're on a tight schedule at this time.

**Comment by lingxiankong** [comment]
> One is dedicated to the cluster nodes,

Do you mean all your tenants are using one single subnet for the k8s cluster nodes?

**Comment by dr4Ke** [comment]
No, we have a k8s cluster in one tenant. Its nodes are on a private subnet. We deploy a LB to the service in another network in this tenant. This network is then used by other tenants to access the service through the loadbalancer instead of using a floating IP in the public network.

**Comment by lingxiankong** [comment]
> No, we have a k8s cluster in one tenant. Its nodes are on a private subnet. 

OK, so why it's not acceptable to open 30000-32767 to this private subnet?
