### ISSUE TITLE
openstack-cloud-controller-manager does not print the current version

### ISSUE THREAD

**Issue by Denissa89** [kubernetes/cloud-provider-openstack#1253]
/usr/local/bin/openstack-cloud-controller-manager --version.
Gives a blank line, although a binary version is expected
version: 1.19.0, linux-amd64

**Comment by lingxiankong** [comment]
can't reproduce. Please provide more information, e.g. steps to reproduce.

BTW, the path of occm is `/bin/openstack-cloud-controller-manager` inside the container.

**Comment by Denissa89** [comment]
`wget https://github.com/kubernetes/cloud-provider-openstack/releases/download/v1.19.0/cloud-provider-openstack-v1.19.0-linux-amd64.tar.gz
tar -xzf cloud-provider-openstack-v1.19.0-linux-amd64.tar.gz && cd linux-amd64
./openstack-cloud-controller-manager --version`
