### ISSUE TITLE
[occm] CrashLoopBackOff runtime: mlock of signal stack failed: 12

### ISSUE THREAD

**Issue by jah23** [kubernetes/cloud-provider-openstack#1257]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:
CrashLoopBack with error;
```
runtime: mlock of signal stack failed: 12
runtime: increase the mlock limit (ulimit -l) or
runtime: update your kernel to 5.3.15+, 5.4.2+, or 5.5+
fatal error: mlock failed
```

**What you expected to happen**:
I expect it should run.

**How to reproduce it**:
Install charmed-kubernetes in Openstack.

**Anything else we need to know?**:
There seems to be a lot of similar issues with Go1.14 on Focal. The reported kernel version 5.4.0-48-generic #52-Ubuntu, which I understand *is* patched for the memory issue.

**Environment**:
- openstack-cloud-controller-manager: v.1.18.0
- OpenStack version: bionic-ussuri
- Others: charmed-kubernetes-519 (with openstack-integrator-81)

**Comment by lingxiankong** [comment]
Have you tried v1.19.1 which is using Go 1.15?

**Comment by jah23** [comment]
Thanks. I expect this would solve it, but it is not so easy to test. Problem here appears to be not with occm, sorry. It is the cdk_addons snap (from openstack-integrator) which is pinning the version to 1.18.0

**Comment by lingxiankong** [comment]
OK, thanks for confirming @jah23, so do you mind we closing this issue for now?

**Comment by jah23** [comment]
Yes closing this. I raised with the cdk-addons folk. Many thanks!
