### ISSUE TITLE
[occm] examples for cloud-controller use deprecated API flags

### ISSUE THREAD

**Issue by oz123** [kubernetes/cloud-provider-openstack#1258]
* openstack-cloud-controller-manager (occm)

/kind bug

**What happened**:

The files:
```
manifests/controller-manager/openstack-cloud-controller-manager-pod.yaml
manifests/controller-manager/openstack-cloud-controller-manager-ds.yaml
```

Use the command line option `--address` which is actually deprecated, and should be replaced
with `--bind-address`.

**What you expected to happen**:
The manifests should use the newer options.

Will you accept a PR for fixing this?

**Comment by lingxiankong** [comment]
I didn't even find `--address` in https://kubernetes.io/docs/reference/command-line-tools-reference/cloud-controller-manager/? Is this a valid option?

**Comment by oz123** [comment]
The logs say it's deprecated and should be replaced with `--bind-address`. That's why the issue.

**Comment by lingxiankong** [comment]
ok, thanks for the info, feel free to propose a PR please
