### ISSUE TITLE
[cinder-csi-plugin] doc is seriously broken

### ISSUE THREAD

**Issue by berndbausch** [kubernetes/cloud-provider-openstack#1268]
/kind bug

**What happened**:

Several issues with the documentation page.
- From https://github.com/kubernetes/cloud-provider-openstack/blob/master/docs/cinder-csi-plugin/using-cinder-csi-plugin.md#multi-attach-volumes on, lots of formatting errors. 
- Multi-attach doesn't appear in the TOC.
- Sections "*Running Sanity Tests*" and "*Using CSC Tool*" are missing entirely.

**What you expected to happen**:

A fix of the above.

**How to reproduce it**:

Browse to https://github.com/kubernetes/cloud-provider-openstack/blob/master/docs/cinder-csi-plugin/using-cinder-csi-plugin.md and click on the [Sanity Tests](https://github.com/kubernetes/cloud-provider-openstack/blob/master/docs/cinder-csi-plugin/using-cinder-csi-plugin.md#running-sanity-tests) and [Using the CSC](https://github.com/kubernetes/cloud-provider-openstack/blob/master/docs/cinder-csi-plugin/using-cinder-csi-plugin.md#using-csc-tool) links.

**Anything else we need to know?**:

Same problems in version 1.19. 

Version 1.18 seems to be OK, but doesn't have a TOC (I have not looked at it in depth).

**Environment**:
- openstack-cloud-controller-manager(or other related binary) version: master
- OpenStack version: n/a
- Others:

**Comment by ramineni** [comment]
@berndbausch should be fixed by this PR https://github.com/kubernetes/cloud-provider-openstack/pull/1254
