### ISSUE TITLE
[cinder-csi-plugin] request for "how it works" documentation

### ISSUE THREAD

**Issue by berndbausch** [kubernetes/cloud-provider-openstack#1269]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> /kind feature

**What happened**:

n/a

**What you expected to happen**:

I am playing with the CSI plugin and, miraculously, got it to work. A second setup, however, doesn't work. When creating a PVC, no APIs are issued to my OpenStack cloud. 

I look at the containers' logs, but since I don't know what is supposed to happen, it's hard to get any clue. In order to troubleshoot the situation, it would be great to have an overview of how the various parts, i.e. the containers in the controller and the nodeplugin pods, play together. How is the creation of a volume claim handled, from *kubectl apply* to Cinder volume creation. 

**How to reproduce it**:

n/a

**Anything else we need to know?**:

I am not running a production system and am just trying to learn.
**Environment**:
- openstack-cloud-controller-manager(or other related binary) version: 1.19
- OpenStack version: Ussuri
- Others:

**Comment by lingxiankong** [comment]
I would recommend you to read https://kubernetes-csi.github.io/docs/, the question you were asking is not cinder-csi-plugin specific.
