### ISSUE TITLE
Use node-role label "worker" for pool members when available

### ISSUE THREAD

**Issue by dr4Ke** [kubernetes/cloud-provider-openstack#1270]
To my knowledge, this should be done in `openstack-cloud-controller-manager` and `octavia-ingress-controller`.

**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
> /kind bug
/kind feature

**What happened**:

In a v1.19 kubernetes cluster, all nodes are considered members except those which have the `node-role.kubernetes.io/master` label.

**What you expected to happen**:

The `node-role.kubernetes.io/worker` label could be used to add only workers to the pool.

**How to reproduce it**:

I'm using rancher v2.5 to deploy a v1.19 kubernetes cluster. I don't really know how other installation means use labels.

**Anything else we need to know?**:

I would do something like:
- check for `node-role.kubernetes.io/worker` label existence in the cluster, then use only these nodes
- if not present, use all nodes except those with `node-role.kubernetes.io/master` label

I guess this way it will not affect anyone relying on the `master` role.

**Environment**:
- openstack-cloud-controller-manager(or other related binary) version: v1.19.0
- OpenStack version: train
- Others:

**Comment by lingxiankong** [comment]
For openstack-cloud-controller-manager, the nodes (load balancer members) are passed from the official cloud-controller-manager when creating external load balancers. If you want to customize the load balancer members, you can consider using `ServiceNodeExclusion` feature gate.

For octavia-ingress-controller, what we could do is to copy the way that cloud-controller-manager gets the nodes.
