### ISSUE TITLE
Missing git tags for v1.18.1, v1.18.2

### ISSUE THREAD

**Issue by bgagnon** [kubernetes/cloud-provider-openstack#1275]
According to the [release procedure](https://github.com/kubernetes/cloud-provider-openstack/blob/master/release-procedure.md), Git tags should be pushed to GitHub before the container images are pushed to DockerHub.

On https://hub.docker.com/r/k8scloudprovider/openstack-cloud-controller-manager/tags, there are Docker image tags for `v1.18.1` and `v1.18.2` but no tags in Git.

Furthermore, there are no Docker `LABEL` entries on the images themselves that could help identify the Git SHA1 that was used to build them.

**Comment by bgagnon** [comment]
Related issue: #1184

**Comment by lingxiankong** [comment]
Thanks @bgagnon for raising this issue, I've also realized that I forgot to create new tags when uploading those images. 

/assign

**Comment by lingxiankong** [comment]
All done.
