### ISSUE TITLE
[k8s-keystone-auth] Should be unauthorized if extra info is nil

### ISSUE THREAD

**Issue by yylt** [kubernetes/cloud-provider-openstack#1288]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
/kind bug
> /kind feature

**What happened**:

Authorize passed even if the user group is "system:unauthenticated",

auth policy configure

```
[
      {
        "resource_permissions": [
          {
            "*/['clusters','namespaces']": ["get","list"]
          }
     },
      {
        "users":{
          "roles":["admin"],
          "projects": ["Admin"],
          "domains": ["service"]
        },
        "resource_permissions": [
          {
            "*/['storageclasses']": [
              "list",
              "get",
              "create"
              ]
          }
        ]
      }
]

$curl -k -v -XGET  -H "Accept: application/json;as=Table;v=v1beta1;g=meta.k8s.io, application/json" -H "User-Agent: kubectl/v1.16.6 (linux/amd64) kubernetes/8f01573" -H "Authorization: Bearer xxx" 'https://10.222.0.1:443/apis/apps/v1/namespaces?limit=500'

< HTTP/1.1 200 OK
< Cache-Control: no-cache, private
< Content-Type: application/json
< Date: Fri, 18 Sep 2020 10:02:15 GMT
< Transfer-Encoding: chunked
```

**What you expected to happen**:

Authorize should be rejected if the token which seted in http header is not recognized by keystone

**How to reproduce it**:

**Anything else we need to know?**:

**Environment**:
- openstack-cloud-controller-manager(or other related binary) version:
- OpenStack version:
- Others:

**Comment by lingxiankong** [comment]
> if the token which seted in http header is not recognized by keystone

If the token is not correct, it should fail early at the authentication phase.

**Comment by yylt** [comment]
> > if the token which seted in http header is not recognized by keystone
> 
> If the token is not correct, it should fail early at the authentication phase.

correct, but apiserver also support '--anonymous-auth' option,  so the group `system:unauthenticated` will see at authorize step

**Comment by lingxiankong** [comment]
Looked at your policy config again:

```
      {
        "resource_permissions": [
          {
            "*/['clusters','namespaces']": ["get","list"]
          }
     },
```

You have this `resource_permissions` defined but without `users`, so that means any user (including those in system:unauthenticated group) is able to access clusters/namespaces.

**Comment by yylt** [comment]
yes， but keystone-auth-policy should handle user which belong to system:unauthenticated group?

It maybe had exceed it's duty

**Comment by lingxiankong** [comment]
> yes， but keystone-auth-policy should handle user which belong to system:unauthenticated group?
> 
> It maybe had exceed it's duty

The policy definition is whitelist based, keystone-auth just does the things it's told to. If `--anonymous-auth` is supported in your cluster but it's intended to not allow an unauthenticated user to access the cluster resource, you need to design the policy definition on purpose.

/close
