### ISSUE TITLE
[k8s-keystone-auth]Policy rule matching is flawed and The authorization process needs to be optimized

### ISSUE THREAD

**Issue by Bevisy** [kubernetes/cloud-provider-openstack#1308]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug

**What happened**:
1. When the namespace in the authorization request is nil, getAllowed(nsDef, ns) will always pass the verification.
2. When the kubernetes cluster turns on anonymous authentication, the authentication will always pass, but the authorization request will not include the extra field, and keystone-auth will still perform authorization verification for such requests.

**What you expected to happen**:
1. the policy rules like `exampe/daemonsets:*` will pass the request which its namespace is nil like `namespace  , resource: daemonsets , verb: list`, so the client will get all of daemonsets in the cluster.
2. Every authenticated request will go through a complete authorization, which is not necessary

**Comment by lingxiankong** [comment]
Can you provide the full policy definition in your test for us to reproduce? and the actual and expected result?

**Comment by Bevisy** [comment]
> Can you provide the full policy definition in your test for us to reproduce? and the actual and expected result?

Policy rule like 
```json
"resource_permissions": [
          {
            "testns/![ 'podTemplates', 'pods', 'replicaSets', 'replicationControllers', 'resourceQuotas', 'secrets', 'selfSubjectAccessReviews', 'serviceAccounts', 'services', 'statefulSets']": ["*"]
          }
]
```
Open apiserver anonymous authentication，make sure authentication always success.
Then send request like:
`curl -k -s -v -XGET  -H "Accept: application/json;as=Table;v=v1beta1;g=meta.k8s.io, application/json" -H "User-Agent: kubectl/v1.16.6 (linux/amd64) kubernetes/8f01573"  'https://10.110.1.8:6443/apis/apps/v1/daemonsets?limit=500'`
Actually we only want daemonsets under testns to be accessible, but we cloud get all of daemonsets in k8s cluster.
