### ISSUE TITLE
[barbican-kms-plugin] failed to create connection to unix socket: /var/lib/kms/kms.sock

### ISSUE THREAD

**Issue by vscripcaru** [kubernetes/cloud-provider-openstack#1313]
/kind bug

Having followed exactly the steps describing the installation and configuration of the barbican-kms-plugin, I end-up with failing cluster not being able to communication with the api-server as the pods can get hold of their secrets.
While the docker container starting the kms plugin creates the required socket, the api server complains as follows:

{"log":"W1113 22:20:33.910655       1 clientconn.go:1208] grpc: addrConn.createTransport failed to connect to {/var/lib/kms/kms.sock  \u003cnil\u003e 0 \u003cnil\u003e}. Err :connection error: desc = \"transport: Error while dialing dial unix /var/lib/kms/kms.sock: connect: no such file or directory\". Reconnecting...\n","stream":"stderr","time":"2020-11-13T22:20:33.910933456Z"}
{"log":"E1113 22:20:41.715033       1 grpc_service.go:76] failed to create connection to unix socket: /var/lib/kms/kms.sock, error: dial unix /var/lib/kms/kms.sock: connect: no such file or directory\n","stream":"stderr","time":"2020-11-13T22:20:41.715617674Z"}
{"log":"W1113 22:20:41.715152       1 clientconn.go:1208] grpc: addrConn.createTransport failed to connect to {/var/lib/kms/kms.sock  \u003cnil\u003e 0 \u003cnil\u003e}. Err :connection error: desc = \"transport: Error while dialing dial unix /var/lib/kms/kms.sock: connect: no such file or directory\". Reconnecting...\n","stream":"stderr","time":"2020-11-13T22:20:41.715683614Z"}

The single-node K8s cluster is running on a Ubuntu VM. The openstack controller is running also on a Ubuntu VM.

ubuntu@security1:~$ sudo docker version
Client: Docker Engine - Community
 Version:           19.03.12
 API version:       1.40
 Go version:        go1.13.10
 Git commit:        48a66213fe
 Built:             Mon Jun 22 15:45:44 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.12
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.10
  Git commit:       48a66213fe
  Built:            Mon Jun 22 15:44:15 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683

ubuntu@security1:~$ hostnamectl
   Static hostname: security1
         Icon name: computer-vm
           Chassis: vm
        Machine ID: 64f81fe96f0148f69588af87c4f7c3bd
           Boot ID: a58eca5a096a40b9be8a114462f0c7c8
    Virtualization: kvm
  Operating System: Ubuntu 20.04.1 LTS
            Kernel: Linux 5.4.0-52-generic
      Architecture: x86-64

ubuntu@security1:~$ kubeclt verison
kubeclt: command not found
ubuntu@security1:~$ kubeclt version
kubeclt: command not found
ubuntu@security1:~$ kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.8", GitCommit:"9f2892aab98fe339f3bd70e3c470144299398ace", GitTreeState:"clean", BuildDate:"2020-08-13T16:12:48Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.8", GitCommit:"9f2892aab98fe339f3bd70e3c470144299398ace", GitTreeState:"clean", BuildDate:"2020-08-13T16:04:18Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
ubuntu@security1:~$

Hope this is about a config setting I'm overlooking.

**Comment by vscripcaru** [comment]
As a heads-up on this item, the issue was happening due to no volume definition within the K8s api-server for the unix socket. 
Once the proper paths were added, the traffic started flowing the way it should. 
Although this doesn't seem to be a bug in implementation, an additional comment or two to the process description might be useful (even though this would fit better the K8s.io KMS plugin configuration description).

**Comment by Miguelixxx** [comment]
I am doing a deployment with the barbican plugin and it gives me the same error.
Kubernetes version: 1.20.6
Openstack Version: ussuri

I have created the mounts in apiserver, but it remains the same. The documentation has not been updated for a long time
