### ISSUE TITLE
openstack cinder storageclass does not provide ReadWriteMany accessmode

### ISSUE THREAD

**Issue by josedev-union** [kubernetes/cloud-provider-openstack#1315]
invalid AccessModes [ReadWriteMany]: only AccessModes [ReadWriteOnce] are supported

**Comment by frittenlab** [comment]
To use ReadWriteMany volumes you will also need a multi attach volume type in openstack. If you run the command:

`openstack volume type list`

You should be able to see the available volume types. We have two types and one of them supports multi attach. I created a separate storage class to support ReadWriteMany volumes which references the volume type id:

`kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: read-write-many
provisioner: cinder.csi.openstack.org
parameters:
  type: b9a45f96-37cc-4e0b-888d-c1j8969
`

You will also need to use these versions of the images:

`k8scloudprovider/openstack-cloud-controller-manager:v1.19.2
k8scloudprovider/cinder-csi-plugin:v1.19.0
`

There is more information here:

[multi-attach-volumes](https://github.com/ramineni/cloud-provider-openstack/blob/953450377f722274295c7a27536c9afa772f1bc7/docs/using-cinder-csi-plugin.md#multi-attach-volumes)

**Comment by jichenjc** [comment]
yeah, we support multiple attach feature which is added recently
@josedev-union please check above comments and see whether it works for you
then we can close this issue, thanks

**Comment by josedev-union** [comment]
that is cool 👍

**Comment by andy-vm** [comment]
Hi @jichenjc may I double confirm if [openstack-cloud-controller-manager](https://github.com/kubernetes/cloud-provider-openstack/blob/master/docs/openstack-cloud-controller-manager/using-openstack-cloud-controller-manager.md) is required to enable RWX for cinder?

I installed latest cinder-csi-plugin but still not able to have RWX, RWO works

thanks

**Comment by tipmg** [comment]
Hello, @jichenjc 
I installed latest cinder-csi-plugin and check logs openstack-cinder-csi-nodeplugin:
`Enabling volume access mode: SINGLE_NODE_WRITER`
Also I checked the source code and found it.
<img width="638" alt="Screenshot 2023-11-30 at 12 36 12 PM" src="https://github.com/kubernetes/cloud-provider-openstack/assets/19558804/83a6f69c-6587-4d74-9901-0d5c12744142">
Please reopen this Issue.
