### ISSUE TITLE
[k8s-keystone-auth] Invalid serviceaccount tokens are validated against keystone

### ISSUE THREAD

**Issue by strigazi** [kubernetes/cloud-provider-openstack#1318]
/kind bug

All invalid serviceaccount tokens go through keystone while they should stop in the api.
(There shoudn't be any invalid tokens, but even when they do they shouldn't load keystone.)

The rate is very high. In a cluster I see issues: 60,000 per 5 minutes.

I don't know if there is a way to distinguish the requests.

Any suggestions?

Logs from k8s-keystone-auth:
```
I1123 08:46:38.108206       1 authorizer.go:197] Authorization failed, user: &user.DefaultInfo{Name:"system:serviceaccount:kube-system:calico-node", UID:"", Groups:[]string{"system:serviceaccounts", "system:serviceaccounts:kube-system", "system:authenticated"}, Extra:map[string][]string(nil)}, attributes: authorizer.AttributesRecord{User:(*user.DefaultInfo)(0xc000b33f00), Verb:"watch", Namespace:"", APIGroup:"", APIVersion:"v1", Resource:"nodes", Subresource:"", Name:"", ResourceRequest:true, Path:""}
```

Logs from apiserver:
```
E1123 08:49:14.135141       1 webhook.go:109] Failed to make webhook authenticator request: the server has asked for the client to provide credentials
E1123 08:49:14.135180       1 authentication.go:104] Unable to authenticate the request due to an error: [invalid bearer token, Token has been invalidated, the server has asked for the client to provide credentials]

```

**Comment by strigazi** [comment]
cc @lingxiankong 

Who is maintaining the webhook now?

**Comment by lingxiankong** [comment]
Hi @strigazi, i do not fully understand the issue, could you please provide an example of what operation are you doing, what's expected, and what's the actual behavior?

**Comment by strigazi** [comment]
"what's expected, and what's the actual behavior" The current expected behaviour can flood keystone with invalid requests. This was an attempt to discuss an improvement.
