### ISSUE TITLE
Unable to see nodeplugin pods in openshift 4

### ISSUE THREAD

**Issue by arunabhabanerjee** [kubernetes/cloud-provider-openstack#1321]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
> /kind bug

**What happened**:
I deployed cinder-csi-pluging using manifest file, The deployment was successful but I don't see any nodeplugin pods are running.

**What you expected to happen**:
cinder-csi-plugin deployment must successful.

oc get all -n openshift-openstack-cinder-csi-driver
NAME                                READY   STATUS    RESTARTS   AGE
pod/csi-cinder-controllerplugin-0   5/5     Running   0          68m

NAME                                    TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)     AGE
service/csi-cinder-controller-service   ClusterIP   172.30.67.231   <none>        12345/TCP   68m

NAME                                   DESIRED   CURRENT   READY   UP-TO-DATE   AVAILABLE   NODE SELECTOR   AGE
daemonset.apps/csi-cinder-nodeplugin   0         0         0       0            0           <none>          68m

NAME                                           READY   AGE
statefulset.apps/csi-cinder-controllerplugin   1/1     68m

**How to reproduce it**:
oc adm new-project openshift-openstack-cinder-csi-driver --node-selector=""
oc create -f manifest/csi-secret-cinderplugin.yaml
oc -f manifest/ apply

**Anything else we need to know?**:

**Environment**:
- openstack-cloud-controller-manager(or other related binary) version:
- OpenStack version: 4.5.19
- Others:

**Comment by arunabhabanerjee** [comment]
Error:

41s         Warning   FailedCreate       daemonset/csi-cinder-nodeplugin           Error creating: pods "csi-cinder-nodeplugin-" is forbidden: unable to validate against any security context constraint: [provider restricted: .spec.securityContext.hostNetwork: Invalid value: true: Host network is not allowed to be used spec.volumes[0]: Invalid value: "hostPath": hostPath volumes are not allowed to be used spec.volumes[1]: Invalid value: "hostPath": hostPath volumes are not allowed to be used spec.volumes[2]: Invalid value: "hostPath": hostPath volumes are not allowed to be used spec.volumes[3]: Invalid value: "hostPath": hostPath volumes are not allowed to be used spec.containers[0].securityContext.hostNetwork: Invalid value: true: Host network is not allowed to be used spec.containers[1].securityContext.privileged: Invalid value: true: Privileged containers are not allowed capabilities.add: Invalid value: "SYS_ADMIN": capability may not be added spec.containers[1].securityContext.hostNetwork: Invalid value: true: Host network is not allowed to be used]

**Comment by arunabhabanerjee** [comment]
Issue resolved after adding SCC privilege to SA.

**Comment by lingxiankong** [comment]
Seems it's related to permission settings in openshift rather than the cinder csi itself.

/close
