### ISSUE TITLE
[k8s-keystone-auth] doesn't works with psp policies

### ISSUE THREAD

**Issue by niedbalski** [kubernetes/cloud-provider-openstack#1322]
**What happened**:

Using the following pod security policy https://pastebin.ubuntu.com/p/xT7ZwsPgPH/ , container with
this deployment  https://github.com/kubernetes/cloud-provider-openstack/blob/master/examples/webhook/keystone-deployment.yaml,won't start as is missing the runAsUser security 

**What you expected to happen**:

Should work with PSP policies

**Environment**:
- OpenStack version: Ussuri

**Comment by lingxiankong** [comment]
Could you please check your paste to correct the format? I'm not very clear what's defined in the PodSecurityPolicy.

**Comment by jichenjc** [comment]
not expert in this area, just curious 
is `https://pastebin.ubuntu.com/p/xT7ZwsPgPH/ ` contains default PSP for all pods? 
otherwise, how do we expect the manifest be modified to adopt for the unique things pasted above? 
@niedbalski

**Comment by rptaylor** [comment]
Yes it would be great if the charts for the CSI drivers included defined PSPs that allow them to run.
On clusters which enable the PSP admission controller for enhanced security, the CSI deployment can only run if it is installed in the kube-system namespace, which has a PSP that allows everything (incl. privileged pods). That is not ideal for security, or for keeping different services isolated in separate namespaces.

Here is an example of the errors seen when trying to deploy openstack-cinder-csi chart v1.2.14:
```
$ kubectl -n openstack-cinder-csi get events
LAST SEEN   TYPE      REASON         OBJECT                                              MESSAGE
3m20s       Warning   FailedCreate   statefulset/openstack-cinder-csi-controllerplugin   create Pod openstack-cinder-csi-controllerplugin-0 in StatefulSet openstack-cinder-csi-controllerplugin failed error: pods "openstack-cinder-csi-controllerplugin-0" is forbidden: PodSecurityPolicy: unable to admit pod: [spec.volumes[2]: Invalid value: "hostPath": hostPath volumes are not allowed to be used]
3m20s       Warning   FailedCreate   daemonset/openstack-cinder-csi-nodeplugin           Error creating: pods "openstack-cinder-csi-nodeplugin-" is forbidden: PodSecurityPolicy: unable to admit pod: [spec.securityContext.hostNetwork: Invalid value: true: Host network is not allowed to be used spec.volumes[0]: Invalid value: "hostPath": hostPath volumes are not allowed to be used spec.volumes[1]: Invalid value: "hostPath": hostPath volumes are not allowed to be used spec.volumes[2]: Invalid value: "hostPath": hostPath volumes are not allowed to be used spec.volumes[3]: Invalid value: "hostPath": hostPath volumes are not allowed to be used spec.volumes[5]: Invalid value: "hostPath": hostPath volumes are not allowed to be used spec.containers[2].securityContext.privileged: Invalid value: true: Privileged containers are not allowed spec.containers[2].securityContext.capabilities.add: Invalid value: "SYS_ADMIN": capability may not be added spec.containers[2].hostPort: Invalid value: 9808: Host port 9808 is not allowed to be used. Allowed ports: [] spec.containers[2].securityContext.allowPrivilegeEscalation: Invalid value: true: Allowing privilege escalation for containers is not allowed]
```

So preferably the Helm chart would include a PSP that defines all the requirements and privileges needed for the CSI driver to run (host network, hostpath volumes, etc). There could be an optional value that determines whether the PSP should be created (although I think it should not do any harm to create the PSP on clusters which don't have the PSP admission controller enabled).

**Comment by lingxiankong** [comment]
@rptaylor I think you are asking for https://github.com/kubernetes/cloud-provider-openstack/pull/1338

**Comment by niedbalski** [comment]
@lingxiankong please check this reference for https://github.com/kubernetes/kube-state-metrics/pull/1034/files kube-state-metrics.

**Comment by lingxiankong** [comment]
@niedbalski The manifest here https://github.com/kubernetes/cloud-provider-openstack/blob/master/examples/webhook/keystone-deployment.yaml is just an example of how to deploy keystone-auth service, the actual deployment varies between different environments. Please don't rely on that for production without modification.
