### ISSUE TITLE
[occm] Wildcard floating ip subnet selection for LoadBalancer services

### ISSUE THREAD

**Issue by dkistner** [kubernetes/cloud-provider-openstack#1328]
**Is this a BUG REPORT or FEATURE REQUEST?**: feature

/kind feature

**What happened**:
As of today the Openstack cloud-controller-manager can be configured to select floating ips for services of type Loadbalancer from a specified floating ip subnet of a floating network.

Floating networks can consist of multiple subnets with different purposes e.g. subnets which are routable via the internet and subnets routable in internal networks.

To ensure that per default all LoadBalancer services (with/without a`LoadBalancerClass`) end up with a floating ip of the correct subnets the cloud-controller-manager need to be configured with a fixed floating ip subnet.
This approach is bad as floating ip subnets can exhaust and users wouldn't be able to create additional LoadBalancer services without annotating them  (`loadbalancer.openstack.org/floating-subnet-id="another-fip-subnet"`) to use a different floating subnet.

**What you expected to happen**:
It would be handy to give the cloud-controller-manager the ability to select floating ip subnets based on a regular expression matching on their name. This would eliminate the need to configure a specific floating ip subnet. The cloud-controller-manager could consider for the selection of a floating ip, all floating subnets whose name match on the configured regex.
It would be required to loop over all matched floating subnets to find a subnet which has free a floating ip for a new LoadBalancer service.

If all floating subnets are allocated it need to fail as well. But it would help users to create new LoadBalancer services without annotating services or without the need to re-configure the cloud-controller-manager in order to create new LoadBalancer services when an administrator of the respective Openstack environment adds new floating subnets.

My proposal is to add an additional option, e.g. `floating-subnet-name-prefix`, in the `[LoadBalancer]` and `[LoadBalancerClass ...]` sections of the cloud provider config, which is used to the cloud-controller-manager.
An example cloud-provider-config could look like this:
```
[LoadBalancer]
floating-network-id="my-fip-network"
floating-subnet-name-prefix="fip-internet" # All floating subnet which match on "fip-internet*" are considered for selecting a floating ip

[LoadBalancerClass "internal"]
floating-network-id="my-fip-network"
floating-subnet-name-prefix="fip-internal"  # All floating subnet which match on "fip-internal*" are considered for selecting a floating ip
```

The cloud-controller-manager could then look up all matching floating subnets in the floating network as described above to allocate a floating ip for a LoadBalancer service.

**Comment by kayrus** [comment]
@lingxiankong could you please give your feedback on this proposal?

**Comment by kayrus** [comment]
@lingxiankong kindly ping. cc @jichenjc, your feedback will be appreciated as well

**Comment by zuzzas** [comment]
Would suit some of our use cases as well. 

One minor nitpick. I think the field should be named `floating-subnet-name-regex` instead. It'll be clear that we accept regex.

**Comment by dkistner** [comment]
I mean the `floating-subnet-name-prefix` property name is just a proposal. We can for sure call ist `floating-subnet-name-regex`.

Are there also other opinions on that? cc @jichenjc , @lingxiankong

**Comment by lingxiankong** [comment]
Instead of `name-prefix`, I'd recommend using tag (e.g. `floating-subnet-tags`) when choosing subnet.
