### ISSUE TITLE
[manila-csi-plugin] PV/PVC can't created

### ISSUE THREAD

**Issue by lw8008** [kubernetes/cloud-provider-openstack#1329]
**What happened**:
I'm following below manifest to deploy manila CSI:
https://github.com/kubernetes/cloud-provider-openstack/tree/master/manifests/manila-csi-plugin
https://github.com/kubernetes/cloud-provider-openstack/blob/master/examples/manila-csi-plugin/nfs/secrets.yaml
https://github.com/kubernetes/cloud-provider-openstack/blob/master/examples/manila-csi-plugin/nfs/dynamic-provisioning/storageclass.yaml

I only change 
env MANILA_SHARE_PROTO to "NFS"  and FWD_CSI_ENDPOINT to "unix:///tmp/csi.sock"
in csi-nodeplugin.yaml & csi-controllerplugin.yaml.

The pods can start success:
> kubectl get po
NAME                                      READY   STATUS    RESTARTS   AGE
openstack-manila-csi-controllerplugin-0   3/3     Running   0          47m
openstack-manila-csi-nodeplugin-4fwhm     2/2     Running   0          44m
openstack-manila-csi-nodeplugin-9h9m7     2/2     Running   0          44m
openstack-manila-csi-nodeplugin-cmdhl     2/2     Running   0          44m
openstack-manila-csi-nodeplugin-fl4df     2/2     Running   0          44m
openstack-manila-csi-nodeplugin-mv6r2     2/2     Running   0          44m
openstack-manila-csi-nodeplugin-vl7dv     2/2     Running   0          44m

But failed with PV/PVC creation:
> kubectl get pvc
NAME                STATUS    VOLUME   CAPACITY   ACCESS MODES   STORAGECLASS     AGE
new-nfs-share-pvc   Pending                                      csi-manila-nfs   8s

> kubectl describe pvc new-nfs-share-pvc
Name:          new-nfs-share-pvc
Namespace:     default
StorageClass:  csi-manila-nfs
Status:        Pending
Volume:
Labels:        <none>
Annotations:   volume.beta.kubernetes.io/storage-provisioner: nfs.manila.csi.openstack.org
Finalizers:    [kubernetes.io/pvc-protection]
Capacity:
Access Modes:
VolumeMode:    Filesystem
Mounted By:    <none>
Events:
  Type    Reason                Age                From                         Message
  ----    ------                ----               ----                         -------
  Normal  ExternalProvisioning  13s (x2 over 23s)  persistentvolume-controller  waiting for a volume to be created, either by external provisioner "nfs.manila.csi.openstack.org" or manually created by system administrator

**What you expected to happen**:
1. from the doc, seems we need provide --fwdendpoint, should i use "unix:///tmp/csi.sock"(it's the default --endpoint)?
2. NFS creation should be handle by container provisioner in pod controllerplugin pod, is that correct? but i didn't see any useful info for logs.

> kubectl logs openstack-manila-csi-controllerplugin-0 -c provisioner
I1202 02:58:03.731914       1 csi-provisioner.go:121] Version: v2.0.2-0-g0c6347dbf
I1202 02:58:03.731997       1 csi-provisioner.go:135] Building kube configs for running in cluster...
I1202 02:58:03.740683       1 connection.go:153] Connecting to unix:///var/lib/kubelet/plugins/manila.csi.openstack.org/csi-controllerplugin.sock
W1202 02:58:13.740831       1 connection.go:172] Still connecting to unix:///var/lib/kubelet/plugins/manila.csi.openstack.org/csi-controllerplugin.sock

3. Could u pls guide me how to debug the issue and make it works?

**Anything else we need to know?**:
K8s 1.17.13

**Comment by gman0** [comment]
@lw8008 

1. Deploy [nfs-csi](https://github.com/kubernetes-csi/csi-driver-nfs) driver.
2. Please observe (manila-csi):
   * [csi-controllerplugin.yaml](https://github.com/kubernetes/cloud-provider-openstack/blob/master/manifests/manila-csi-plugin/csi-controllerplugin.yaml): _hostPath_ volume definition [here](https://github.com/kubernetes/cloud-provider-openstack/blob/c4d0329c1c2126ff88925e45acb2a4ae86990e89/manifests/manila-csi-plugin/csi-controllerplugin.yaml#L111-L114) and its mount [here](https://github.com/kubernetes/cloud-provider-openstack/blob/c4d0329c1c2126ff88925e45acb2a4ae86990e89/manifests/manila-csi-plugin/csi-controllerplugin.yaml#L101-L102) both need to be configured to `/var/lib/kubelet/plugins/csi-nfsplugin`.
   * [csi-nodeplugin.yaml](https://github.com/kubernetes/cloud-provider-openstack/blob/master/manifests/manila-csi-plugin/csi-nodeplugin.yaml): the same thing as above. _hostPath_ volume definition [here](https://github.com/kubernetes/cloud-provider-openstack/blob/c4d0329c1c2126ff88925e45acb2a4ae86990e89/manifests/manila-csi-plugin/csi-nodeplugin.yaml#L96-L99) and its mount [here](https://github.com/kubernetes/cloud-provider-openstack/blob/c4d0329c1c2126ff88925e45acb2a4ae86990e89/manifests/manila-csi-plugin/csi-nodeplugin.yaml#L85-L86) also needs to be configured to `/var/lib/kubelet/plugins/csi-nfsplugin`.
3. In both manifests, `--fwdendpoint` needs to be configured to nfs-csi Node plugin's socket: `unix:///var/lib/kubelet/plugins/csi-nfsplugin/csi.sock`.
4. Deploy manila-csi.

manila-csi relies on nfs-csi, to which it forwards all node-related operations, e.g. mounting NFS volumes.

**Comment by lw8008** [comment]
@gman0 

I got "{"code": 400, "message": "Share network must be set when the driver_handles_share_servers is true."}}" when create PV now.
Could u pls let me know how to assgin share network in the storageclass?

I've tried below but not work：
---
kind: StorageClass
metadata:
  name: csi-manila-nfs
provisioner: manila.csi.openstack.org
parameters:
  # Manila share type
  type: default
  share-network: k8scl01

  csi.storage.k8s.io/provisioner-secret-name: csi-manila-secrets
  csi.storage.k8s.io/provisioner-secret-namespace: kube-system
  csi.storage.k8s.io/node-stage-secret-name: csi-manila-secrets
  csi.storage.k8s.io/node-stage-secret-namespace: kube-system
  csi.storage.k8s.io/node-publish-secret-name: csi-manila-secrets
  csi.storage.k8s.io/node-publish-secret-namespace: kube-system

**Comment by gman0** [comment]
@lw8008 it's in the docs: https://github.com/kubernetes/cloud-provider-openstack/blob/master/docs/manila-csi-plugin/using-manila-csi-plugin.md#controller-service-volume-parameters

There is no "share-network" parameter. You can use `shareNetworkID` parameter to set the share network ID when provisioning new shares.

**Comment by lw8008** [comment]
Thank @gman0  it works like a charm.

I met another issue when try snapshot:

Follow https://kubernetes.io/blog/2019/12/09/kubernetes-1-17-feature-cis-volume-snapshot-beta/ 
I've installed snapshot CRD and controller.

> kubectl get ds -n kube-system
NAME                              DESIRED   CURRENT   READY   UP-TO-DATE   AVAILABLE   NODE SELECTOR            AGE
csi-nfs-node                      6         6         6       6            6           <none>                   2d
openstack-manila-csi-nodeplugin   6         6         6       6            6           <none>                   58m

> kubectl get statefulset -n kube-system
NAME                                    READY   AGE
openstack-manila-csi-controllerplugin   1/1     24h
snapshot-controller                     1/1     97m

But when i try to follow https://github.com/kubernetes/cloud-provider-openstack/tree/master/examples/manila-csi-plugin/nfs/snapshot to create snapshot, it not really create a snapshot:

4> kubectl describe volumesnapshot new-nfs-share-snap
Name:         new-nfs-share-snap
Namespace:    default
Labels:       <none>
Annotations:  <none>
API Version:  snapshot.storage.k8s.io/v1beta1
Kind:         VolumeSnapshot
Metadata:
  Creation Timestamp:  2020-12-23T07:06:51Z
  Generation:          1
  Resource Version:    95243013
  Self Link:           /apis/snapshot.storage.k8s.io/v1beta1/namespaces/default/volumesnapshots/new-nfs-share-snap
  UID:                 f544a198-bc20-4318-a42c-eb809d5616fa
Spec:
  Source:
    Persistent Volume Claim Name:  new-nfs-share-pvc
  Volume Snapshot Class Name:      csi-manila-nfs
Events:                            <none>

Here is the log from "kubectl logs -n kube-system snapshot-controller-0 -f"
I1223 07:19:37.905657       1 reflector.go:255] Listing and watching *v1.VolumeSnapshot from github.com/kubernetes-csi/external-snapshotter/client/v4/informers/externalversions/factory.go:117
E1223 07:19:37.907399       1 reflector.go:138] github.com/kubernetes-csi/external-snapshotter/client/v4/informers/externalversions/factory.go:117: Failed to watch *v1.VolumeSnapshot: failed to list *v1.VolumeSnapshot: the server could not find the requested resource (get volumesnapshots.snapshot.storage.k8s.io)

Could you pls guide me how to debug this issue?

**Comment by ramineni** [comment]
@lw8008 Is the issue resolved?
Can you make sure you have installed volumesnapshots.snapshot.storage.k8s.io CRD , https://github.com/kubernetes-csi/external-snapshotter/blob/master/client/config/crd/snapshot.storage.k8s.io_volumesnapshots.yaml 

And also, could you let us know the versions of external-snapshoter, snapshot-controller and manila-csi-plugin you are using in your env

**Comment by lw8008** [comment]
I was using wrong CRD, it works now.
Thanks.
