### ISSUE TITLE
[occm] octavia stopped working with custom provider driver

### ISSUE THREAD

**Issue by notandy** [kubernetes/cloud-provider-openstack#1356]
**Is this a BUG REPORT or FEATURE REQUEST?**: Bug

/kind bug

**What happened**:
Cloud provider could not be initialized: could not init cloud provider "openstack": Unsupported LoadBalancer Provider: f5

The pull request #1344 introduced an allow-list of supported octavia provider plugins that breaks existing setups using octavia provider plugins that are _not_ amphora based. In our case, we use the F5 provider plugin which is fully compatible with occm:
https://github.com/sapcc/octavia-f5-provider-driver
`lb-provider=f5`

**What you expected to happen**:
occm is supposed to use what the customer/admin has configured.

Custom provider plugins shouldn't be inferred by occm since customers could use a vendor provider plugin (e.g. Juniper has closed-source provider plugin, and many more:
https://docs.openstack.org/octavia/latest/admin/providers/index.html  

**How to reproduce it**:
cloud-config.conf:
```
[LoadBalancer]
lb-provider=f5
```

**Anything else we need to know?**:
I suggest following solutions:

1. Revert #1344 as is doesn't add any benefit.
2. Instead of returning an error, just print a warning that the provider plugin has not been tested/supported.

**Environment**:
- openstack-cloud-controller-manager(or other related binary) version:
- OpenStack version: Queens

**Comment by jichenjc** [comment]
or maybe an option to list supported provider and by default include supported provider
then up to admin to add supported list considering you know the impact?

**Comment by notandy** [comment]
Hi!
> or maybe an option to list supported provider and by default include supported provider
> then up to admin to add supported list considering you know the impact?

Excuse me, do you mean to make the supported provider list configurable?

**Comment by jichenjc** [comment]
yes, that's the proposal , not sure @lingxiankong might have further comments?

**Comment by lingxiankong** [comment]
Checking if the configured provider (`lb-provider`) is supported in Octavia during OCCM initialization would be a good idea.

**Comment by notandy** [comment]
> Checking if the configured provider (`lb-provider`) is supported in Octavia during OCCM initialization would be a good idea.

This is reasonable, although my issue concerns the breaking change that for existing occm deployment with customer `lb-provider`, that the PR #1344 breaks the occm by panicing due to unsupported driver. So I am asking how to proceed if to remain compatibility.

1. OCCM should not break just because a custom `lb-provider` is set
2. making the provider-list configurable just introduces a burden to the administrator to adapt the `cloud-config.conf`, I don't see a benefit in it.

So my inital request is about not making the "unsupported" case critical, the question how the unsupported case is detected (either via hardcoded list or via octavia api call that checks if the provider is supported) is secondary

**Comment by ialidzhikov** [comment]
+1 for this issue. occm@v1.20.0 breaks the compatibility with #1344. Can we get in https://github.com/kubernetes/cloud-provider-openstack/pull/1357?
