### ISSUE TITLE
Add Snapshot support to Cinder/CSI

### ISSUE THREAD

**Issue by j-griffith** [kubernetes/cloud-provider-openstack#136]
/kind feature

We're getting close to a consensus for the Snapshots spec in CSI:
    https://github.com/container-storage-interface/spec/pull/207

Of course we'll want to implement this in the CSI driver here when it lands, but also in the meantime we'll need to implement the provider layer as well.

So, might as well start implementing an openstack_snapshots pkg and at least roughing in the CSI implementation.

**Comment by FengyunPan2** [comment]
/featrue
Nice featrue!
