### ISSUE TITLE
[occm]  2 OCCM instances from different K8s clusters configure the same load balancer instance

### ISSUE THREAD

**Issue by Payback159** [kubernetes/cloud-provider-openstack#1371]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
/kind bug
> /kind feature

**What happened**:

We have 2 Kubernetes clusters installed in 2 different projects within an OpenStack landscape. Both Kubernetes clusters are running OCCM version v1.18.2.

We have the services in both clusters rolled out via LoadBalancer Type, Namespace Name is the same and the Service Name is the same.

As a result, in OpenStack, the same load balancer instance was managed by 2 different Kubernetes OCCM.

**What you expected to happen**:
We actually expected the OCCM to somehow prefix or postfix the requested load balancer instances or use other mechanisms, like referencing to the id, to make them uniquely identifiable.

**How to reproduce it**:

Install 2 different K8s clusters with OCCM in the same OpenStack landscape.
Then deploy a service of LoadBalancer type with the same name and in the same namespace in both clusters.

**Anything else we need to know?**:

The OCCMs were rolled out with different credentials for the OpenStack API.

**Environment**:
- openstack-cloud-controller-manager(or other related binary) version: v1.18.2
- OpenStack version: Ussuri
- Others:

**Comment by lingxiankong** [comment]
What's the option `--cluster-name` configured for kube-controller-manager for the two clusters? I guess they are the same, please set different values for different clusters.

**Comment by Payback159** [comment]
Hello @lingxiankong  , thanks for the tip. The flag seems to have slipped through when I was searching the documentation.
Solved the problem. :-)
