### ISSUE TITLE
helm repo is out of date 

### ISSUE THREAD

**Issue by rptaylor** [kubernetes/cloud-provider-openstack#1376]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:
Installed the helm repo for cloud provider openstack according to: https://kubernetes.github.io/cloud-provider-openstack/
Only old chart versions were available.

**What you expected to happen**:
To helm install latest versions of charts.

**How to reproduce it**:
```
$ helm search repo cpo
NAME                    	CHART VERSION	APP VERSION	DESCRIPTION                   
cpo/openstack-cinder-csi	1.2.2        	v1.19.0    	Cinder CSI Chart for OpenStack
cpo/openstack-manila-csi	0.2.1        	v1.19.0    	Manila CSI Chart for OpenStack
```
This shows the helm repo is hosting openstack-cinder-csi v1.2.2, but that version is from September.

**Anything else we need to know?**:

**Comment by lingxiankong** [comment]
same for me, @brtknr not sure if you are still maintaining the Charts, could you please take a look?

**Comment by brtknr** [comment]
hello, branch automatic kubernetes branch protection means that the github actions cannot publish new charts to gh-pages automatically when a new release is cut. You need to disable branch protection on gh-pages branch manually temporarily and re-run chart releaser action. I am happy to do this but will need additional privileges on this repo. The other option is to change the k8s-bot policy on this repo itself to stop enabling branch protection... it is rather annoying that it re-enables it automatically.

**Comment by lingxiankong** [comment]
Let's see if https://github.com/kubernetes/cloud-provider-openstack/pull/1378 could fix this.

**Comment by rptaylor** [comment]
Now I see
```
$ helm search repo cpo
NAME                    	CHART VERSION	APP VERSION	DESCRIPTION                   
cpo/openstack-cinder-csi	1.2.13       	v1.20.0    	Cinder CSI Chart for OpenStack
cpo/openstack-manila-csi	1.0.5        	v1.20.0    	Manila CSI Chart for OpenStack
```
if that is the latest version it seems to be fixed.

**Comment by rptaylor** [comment]
It looks like 1.3.1 was released at least 15 days ago in git, but not in the chart repo. Is there expected to be a delay?

**Comment by brtknr** [comment]
@rptaylor things dont get released from master branch, only release-* branch, in this case, the release-1.20.0 branch. Otherwise the app version would need to be master branch which is bad. If there are bug fixes you want on the release branch, please feel free to backport otherwise install the chart from master branch manually.

**Comment by lingxiankong** [comment]
I would assume this is fixed, thanks for your help @brtknr 

/close

**Comment by rptaylor** [comment]
I was excited to see cinder 1.4.9 is released in the 1.22 branch, though not showing up in the Helm repo yet:
```
$ helm search repo cpo
NAME                                  	CHART VERSION	APP VERSION	DESCRIPTION                                  
cpo/openstack-cinder-csi              	1.3.8        	v1.21.0    	Cinder CSI Chart for OpenStack               
cpo/openstack-cloud-controller-manager	1.0.1        	v1.21.0    	Openstack Cloud Controller Manager Helm Chart
cpo/openstack-manila-csi              	1.1.2        	v1.21.0    	Manila CSI Chart for OpenStack             
```
Looking forward to using it when it is published to the Helm repo.

**Comment by lingxiankong** [comment]
Hi @brtknr, any chance you can help to take a look?

**Comment by brtknr** [comment]
Hmm this seems to suggest that the release was successful https://github.com/kubernetes/cloud-provider-openstack/runs/3347434137?check_suite_focus=true

**Comment by brtknr** [comment]
Also the index.yaml was published correctly https://github.com/kubernetes/cloud-provider-openstack/commit/e5b66e4f98f28a157659ed502e09587f82695b9e

**Comment by brtknr** [comment]
Maybe you forgot to run helm repo update

**Comment by rptaylor** [comment]
Wow, it's hard to believe Helm never automatically checks for updates, you really have to manually update every time??
Anyway yes it shows up now, thanks for checking.
