### ISSUE TITLE
Node registration fails if nova AZ value has ' '

### ISSUE THREAD

**Issue by jichenjc** [kubernetes/cloud-provider-openstack#1379]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
/kind bug
> /kind feature

**What happened**:

inspired by 

https://github.com/kubernetes/cloud-provider-openstack/pull/1364

```
Unable to register node "ocpcic-x45pc-master-0" with API server: Node "ocpcic-x45pc-master-0" is invalid: metadata.labels: Invalid value: "Default Group": a valid label must be an empty string or consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyValue',  or 'my_value',  or '12345', regex used for validation is '(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])?')
```

we suffered above issue with similar pattern, so I think we might consider do same thing to #1364 
**What you expected to happen**:

**How to reproduce it**:

**Anything else we need to know?**:

**Environment**:
- openstack-cloud-controller-manager(or other related binary) version:
- OpenStack version:
- Others:

**Comment by jichenjc** [comment]
The issue should be related to label `topology.kubernetes.io/zone`

**Comment by lingxiankong** [comment]
As per discussion in https://github.com/kubernetes/cloud-provider-openstack/pull/1380, it has been decided we don't solve this issue for now but add a note in the documentation.

We will come back here if we hear more feedback in the future.
