### ISSUE TITLE
[occm] How to correctly set the cluster-name for the occm only.

### ISSUE THREAD

**Issue by danmikita** [kubernetes/cloud-provider-openstack#1386]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind feature

**What happened**:
The name of the created lbaas references the "cluster-name" from the startup flags of the daemon set.

**What you expected to happen**:
I expected the cluster-name flag to reference the name of the cluster from the kubernetes-controller-manager `--cluster-name=` flag.

**How to reproduce it**:
Change the `--cluster-name=` flag on the kubernetes controller manager startup arguments and see that the daemonset still defaults to "kubernetes" as the cluster-name.

**Anything else we need to know?**:
My current solution is to set the --cluster-name in the daemon-set manifest.

**Comment by lingxiankong** [comment]
OCCM is using cluster name configured in kubernetes-controller-manager. Could you provide the detailed steps of you operation?

**Comment by vs49688** [comment]
Reopening, I've just hit this too.
I have three clusters (k0s-built) in the same tenant. Each cluster has different `--cluster-name=` values on their `kube-controller-manager`s.

I'd expect load balancers to be created with unique names, but they're still created using the default `kubernetes`. And now the three clusters continuously fight over who owns the LBs.

**Comment by lingxiankong** [comment]
the cloud controller manager is a separate binary and has its own parameters, you have to specify different cloud names for different CCMs.
