### ISSUE TITLE
[cinder-csi-plugin] Migrate in-tree cloud-provider metrics for cinder plugin

### ISSUE THREAD

**Issue by Jiawei0227** [kubernetes/cloud-provider-openstack#1392]
**Is this a BUG REPORT or FEATURE REQUEST?**:
> Uncomment only one, leave it on its own line: 
>
> /kind bug
/kind feature

**What happened**:
Current for in-tree cinder volume usage, we can get the cloud-provider related metrics from the legacy-cloud-provider package[1]. To fully support CSI migration, we should evaluate if these metrics are still essential and are being consumed by any components. If not, we might need to deprecate them. If yes, we should come up with a plan on how to include them in the CSI driver.

[1] https://github.com/kubernetes/kubernetes/blob/e161051c8366c6c90502f1a4ef06da2f01db2264/staging/src/k8s.io/legacy-cloud-providers/openstack/openstack_metrics.go#L35

**What you expected to happen**:

**How to reproduce it**:

**Anything else we need to know?**:

**Environment**:
- openstack-cloud-controller-manager(or other related binary) version:
- OpenStack version:
- Others:

**Comment by jichenjc** [comment]
https://github.com/kubernetes/cloud-provider-openstack/pull/1236 merged recently
so we will add CSI metrics soon 

/assign

**Comment by jichenjc** [comment]
First , we need expose the http endpoint of the CSI containers
through /metrics 

https://github.com/kubernetes/cloud-provider-openstack/pull/1398 is doing that by adding an http endpoint and by doing that , we can achieve 

```
# kubectl get pods  -n kube-system -o wide
NAME                            READY   STATUS    RESTARTS   AGE   IP           NODE        NOMINATED NODE   READINESS GATES
csi-cinder-controllerplugin-0   6/6     Running   0          6s    172.17.0.3   127.0.0.1   <none>           <none>
csi-cinder-nodeplugin-2j5gg     3/3     Running   0          6s    127.0.0.1    127.0.0.1   <none>           <none>
kube-dns-58fd9b49f7-ffn4b       3/3     Running   0          59s   172.17.0.2   127.0.0.1   <none> 

oot@jjtest1:~/go/src/github.com/cloud-provider-openstack/manifests# kubectl run -i --tty curl1 --image=curlimages/curl --restart=Never
 -- sh
If you don't see a command prompt, try pressing enter.
/ $ curl 172.17.0.3:8080/metrics
# HELP process_start_time_seconds [ALPHA] Start time of the process since unix epoch in seconds.
# TYPE process_start_time_seconds gauge
process_start_time_seconds 1.6124993369e+09
```

then after above is done,
we can keep adding openstack api calls metrics by referring to implementation 
https://github.com/kubernetes/cloud-provider-openstack/blob/master/pkg/metrics/metrics_api.go
and keep adding stuffs like how many openstack calls we did ..

**Comment by ramineni** [comment]
@jichenjc Thanks. Got it. I'm wondering if we are adding only openstack api call metrics, cant we use uniform way of retrieving metrics or same endpoint for metrics . Right now we have different ways of retrieving metrics, so may be it would less confusing if we can expose metrics with same endpoint or extension of the same. not sure if this is possible?

**Comment by jichenjc** [comment]
@ramineni I agree we need use same endpoint for all openstack calls, but seems we can't assume CSI metrics  come from Cloud provider container endpoint? the /metrics are consistent across all containers

**Comment by ramineni** [comment]
@jichenjc I meant some extension like https://localhost:10258/metrics/csi etc?
