### ISSUE TITLE
[Cinder-csi-plugin] Gate failure

### ISSUE THREAD

**Issue by jichenjc** [kubernetes/cloud-provider-openstack#1393]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
/kind bug
> /kind feature

**What happened**:
take https://logs.openlabtesting.org/logs/84/1384/a2a6c42d771b29e4a364b78145904ec971e28072/cloud-provider-openstack-e2e-test-csi-cinder/cloud-provider-openstack-e2e-test-csi-cinder/6c151f9/job-output.txt.gz
as example (other PR has simliar issues)

seeing 
```
2021-01-30 11:04:04.017934 | ubuntu-focal-citynetwork | + /home/zuul/src/k8s.io/kubernetes/cluster/kubectl.sh -n kube-system logs pod/csi-cinder-controllerplugin-0 -c cinder-csi-plugin
2021-01-30 11:04:04.224680 | ubuntu-focal-citynetwork | Error from server: Get "https://ubuntu-focal-citynetwork-citynetwork-openlab-0000148684:10250/containerLogs/kube-system/csi-cinder-controllerplugin-0/cinder-csi-plugin": dial tcp: lookup ubuntu-focal-citynetwork-citynetwork-openlab-0000148684 on 127.0.0.1:53: no such host
```

```
home/zuul/pkg/mod/k8s.io/kubernetes@v1.20.0/test/e2e/storage/testsuites/volumes.go:192 Unexpected error: <*errors.errorString | 0xc0009204d0>: { s: "failed to get logs from exec-volume-test-dynamicpv-p4km for exec-container-dynamicpv-p4km: an error on the server (\"unknown\") has prevented the request from succeeding (get pods exec-volume-test-dynamicpv-p4km)", } failed to get logs from exec-volume-test-dynamicpv-p4km for exec-container-dynamicpv-p4km: an error on the server ("unknown") has prevented the request from succeeding (get pods exec-volume-test-dynamicpv-p4km) occurred /home/zuul/pkg/mod/k8s.io/kubernetes@v1.20.0/test/e2e/framework/util.go:738
```
not sure it's plugin or openlab issue, open here for tracking

**What you expected to happen**:

**How to reproduce it**:

**Anything else we need to know?**:

**Environment**:
- openstack-cloud-controller-manager(or other related binary) version:
- OpenStack version:
- Others:

**Comment by ramineni** [comment]
@jichenjc are you working on it?

**Comment by jichenjc** [comment]
No ,feel free to assign yourself :) @ramineni

**Comment by chrigl** [comment]
Created PRs

* https://github.com/theopenlab/openlab-zuul-jobs/pull/1101
* https://github.com/theopenlab/openlab-zuul-jobs/pull/1103

**Comment by chrigl** [comment]
/close

See: https://github.com/kubernetes/cloud-provider-openstack/pull/1401 all tests passed \o/
