### ISSUE TITLE
[cinder-csi-plugin] Tracking CSIMigration with Topology Support

### ISSUE THREAD

**Issue by chrigl** [kubernetes/cloud-provider-openstack#1397]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

> Uncomment only one, leave it on its own line: 
>
> /kind bug
> /kind feature

**What happened**:

Our CSIMigration tests don't run with topology support enabled. Thanks to @jsafrane for discovering and fixing a missing implementation in `csi-translation-lib` :) (see https://github.com/kubernetes/kubernetes/pull/98311)

For documentation purposes. This is the error message showing up in container `csi-provisioner` of pod `csi-cinder-controllerplugin-0`.

```
I0201 11:04:31.306297       1 event.go:282] Event(v1.ObjectReference{Kind:"PersistentVolumeClaim", Namespace:"topology-3380", Name:"pvc-pbqb5", UID:"8d14863d-5505-402d-b8e8-748f789b0119", APIVersion:"v1",  ResourceVersion:"85642445", FieldPath:""}): type: 'Warning' reason: 'ProvisioningFailed' failed to provision volume with StorageClass "topology-3380-cinder-scdbmqm": error generating accessibility requirements: topology map[topology.cinder.csi.openstack.org/zone:es1] from selected node "k8s-node-2" is not in requisite: [map[failure-domain.beta.kubernetes.io/zone:es1]]
```

**What you expected to happen**:

Test should pass. Topology labels shoud be translated from in-tree storage class to csi-cinder-style storage class.

**How to reproduce it**:

* Make sure CSIMigration is enabled in your cluster
* Enable Topology in container `csi-provisioner`
```
kubectl -n kube-system patch --type=json -p '[{"op": "add", "path": "/spec/template/spec/containers/1/args/-", "value": "--feature-gates=Topology=true"}]' statefulset/csi-cinder-controllerplugin
```
* run kubernetes e2e tests like
```
/root/kubernetes/test/bin/e2e.test \
  -kubeconfig=/etc/kubernetes/admin.conf \
  -provider=openstack \
  -storage.migratedPlugins=kubernetes.io/cinder \
  -report-dir="$log_dir" \
  -ginkgo.noColor \
  -ginkgo.focus="\[sig-storage\]\sIn-tree\sVolumes\s\[Driver:\scinder\]\s\[Testpattern:\sDynamic\sPV\s\(delayed\sbinding\)\]\stopology\sshould\sprovision\sa\svolume\sand\sschedule\sa\spod\swith\sAllowedTopologies"
```

**Anything else we need to know?**:

There are pending Backports to supported Kubernetes versions

* https://github.com/kubernetes/kubernetes/pull/98608
* https://github.com/kubernetes/kubernetes/pull/98609
* https://github.com/kubernetes/kubernetes/pull/98610

We need to wait for:

* merge of https://github.com/kubernetes/kubernetes/pull/98610
* updated version of `csi-provisioner`

For us to do:

* update the `csi-provisioner` container in pod `csi-cinder-controllerplugin` to fixed version
* enanble topology in `csi-cinder-controllerplugin`

**Environment**:
- openstack-cloud-controller-manager(or other related binary) version:
- OpenStack version:
- Others:

**Comment by chrigl** [comment]
Just to give an update. We are still waiting for a release of `external-provisioner` (https://github.com/kubernetes-csi/external-provisioner/issues/563). In the meanwhile, I created a custom image, including the fix of @jsafrane , and successfully tested CSIMigration+Topology with it.

**Comment by ramineni** [comment]
@chrigl Any update on this?
