### ISSUE TITLE
This node <name> is registered without the cloud taint. Will not process.

### ISSUE THREAD

**Issue by xmik** [kubernetes/cloud-provider-openstack#140]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug

**What happened**:
A k8s node was initialized, but then cloud-provider-openstack says that it will not process:
```
ERROR: logging before flag.Parse: I0425 15:47:59.280128 1 openstack.go:628] Claiming to support Zones
ERROR: logging before flag.Parse: I0425 15:47:59.280101 1 node_controller.go:344] Adding node label from cloud provider: beta.kubernetes.io/instance-type=312048105
ERROR: logging before flag.Parse: I0425 15:47:59.553145 1 node_controller.go:371] Adding node label from cloud provider: failure-domain.beta.kubernetes.io/region=RegionOne
ERROR: logging before flag.Parse: I0425 15:48:00.355632 1 node_controller.go:392] Successfully initialized node k8s-testing-workstation-master-1 with cloud provider
ERROR: logging before flag.Parse: I0425 15:48:00.355658 1 node_controller.go:297] This node k8s-testing-workstation-master-1 is registered without the cloud taint. Will not process.
ERROR: logging before flag.Parse: I0425 15:48:00.357463 1 node_controller.go:297] This node k8s-testing-workstation-master-1 is registered without the cloud taint. Will not process.
```

**What you expected to happen**:
I expected cloud-provider-openstack to proceed after successful initialization of a node.

**How to reproduce it (as minimally and precisely as possible)**:
1. Deployed new k8s cluster (1 master node, 1 worker node).  Essential Pods are running: kube-apiserver, kube-scheduler, kube-controller-manager, kube-proxy. They are managed by kubelet, their manifests are in `/etc/kubernetes/manifests`.
1. Add taints to all 2 nodes:
```
$ kubectl taint nodes k8s-testing-workstation-master-1 node.cloudprovider.kubernetes.io/uninitialized=true:NoSchedule
node "k8s-testing-workstation-master-1" tainted
$ kubectl taint nodes k8s-testing-workstation-worker-1 node.cloudprovider.kubernetes.io/uninitialized=true:NoSchedule
node "k8s-testing-workstation-worker-1" tainted
$ kubectl describe node | grep Taints
Taints:             node.cloudprovider.kubernetes.io/uninitialized=true:NoSchedule
Taints:             node.cloudprovider.kubernetes.io/uninitialized=true:NoSchedule
```
2. Add a Pod manifest for cloud-provider-openstack into `/etc/kubernetes/manifests`, so that it is managed by kubelet too.
4. The Pod with cloud-provider-openstack is running. Log messages as above. And the taints are unset:
```
$ kubectl describe node | grep Taints
Taints:             <none>
Taints:             <none>
```

**Anything else we need to know?**:
Commandline options set:
```
containers:
  - name: openstack-cloud-controller-manager
    image: docker.io/k8scloudprovider/openstack-cloud-controller-manager:latest
    args:
      - /bin/openstack-cloud-controller-manager
      - --bind-address=0.0.0.0
      - --address=0.0.0.0
      - --cluster-name=k8s-testing
      - --cluster-cidr=10.33.0.0/16
      - --cloud-config=/srv/kubernetes/openstack.conf
      - --cloud-provider=openstack
      - --kubeconfig=/etc/kubernetes/master-kubeconfig.yaml
      - --kube-api-content-type=application/vnd.kubernetes.protobuf
      - --leader-elect=false
      - --profiling=false
      - --port=10253
      - --secure-port=0
      - --use-service-account-credentials=false
      - --v=2
      - --loglevel=2
```

**Environment**:
- openstack-cloud-controller-manager version:
```
/bin/openstack-cloud-controller-manager --version
Kubernetes v0.0.0-master+$Format:%h$
```
from docker image: `docker.io/k8scloudprovider/openstack-cloud-controller-manager:latest`.(Is there any tagged version?)
- OS (e.g. from /etc/os-release): Ubuntu 16.04
- Kernel (e.g. `uname -a`):  `Linux k8s-testing-workstation-master-1 4.4.0-45-generic #66-Ubuntu SMP Wed Oct 19 14:12:37 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
`
- Install tools: Private saltstack files + terraform
- Others:
   * no authorization/authentication set
   * k8s 1.10.1

**Comment by gonzolino** [comment]
AFAIK this is not a bug, but just an information by the node-controller.
After it starts it finds the nodes with the uninitialized taints, initializes them and removes the taint.
Afterwards, the node controller will regularly look through nodes to find nodes with the uninitialized taint. For nodes which do not have the taint (like those it already processed), it will log the message you mentioned.

**Comment by xmik** [comment]
Thanks, @gonzolino, you are right!

I tested today using docker image `k8scloudprovider/openstack-cloud-controller-manager:v0.1.0` and it works fine.
