### ISSUE TITLE
[cinder-csi-plugin] Enable testsuite for VolumeExpansion

### ISSUE THREAD

**Issue by chrigl** [kubernetes/cloud-provider-openstack#1405]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

> Uncomment only one, leave it on its own line: 
>
> /kind bug
> /kind feature

**What happened**:

We don't run the testsuite for volume expansion.

**What you expected to happen**:

We *do* run this testsuite

**How to reproduce it**:

**Anything else we need to know?**:

See https://github.com/kubernetes/cloud-provider-openstack/pull/1320#issuecomment-776533432

**Environment**:
- openstack-cloud-controller-manager(or other related binary) version:
- OpenStack version:
- Others:

**Comment by ramineni** [comment]
@chrigl its enabled before , but had to revert back , https://github.com/kubernetes/cloud-provider-openstack/pull/975 . not sure if its still the case

**Comment by chrigl** [comment]
I think, I need some more testing for this task. Sure, the PR did pass, and in general expansion works, but I ran into some "error_extending" errors on citynetworks site. Unfortunately in this case, there is nothing a customer-user (no matter if human or csi-cinder-controllerplugin) is able to do about. Detaching in this case is also not possible. The only way to get the volume out of this state is to remove the compute instance the volume is attached to.

For now, I think running this the volume expansion testsuite for each PR would lead to "orphaned" volumes, what in turn would let us run in out-of-quota issues again. Beside that, the test runs become more brittle again.

**Comment by ramineni** [comment]
/close

Tests are enabled now.
