### ISSUE TITLE
[cinder-csi-plugin] Run Kubernetes e2e tests in CI

### ISSUE THREAD

**Issue by jsafrane** [kubernetes/cloud-provider-openstack#1407]
/kind feature

PRs against cinder-csi-plugin should run kubernetes/kubernetes [e2e tests for testing CSI drivers](https://github.com/kubernetes/kubernetes/tree/master/test/e2e/storage/external). The only input is a yaml manifest file, which tells the tests what features the driver supports (topology, snapshots, ...) to filter out unimplemented features.

I can see ginkgo + Kubernetes e2e.test compiled in `cloud-provider-openstack-acceptance-test-csi-cinder` CI job, so it should be just matter of running them with the right arguments + yaml manifest.

Benefit: it has good coverage of CSI features, as SIG-storage requires tests there for newly added features.

**Comment by ramineni** [comment]
@jsafrane we do have e2e tests, https://github.com/theopenlab/openlab-zuul-jobs/blob/master/playbooks/cloud-provider-openstack-e2e-test-csi-cinder/run.yaml , is it not what you are talking about.

Though right now, its not full fledged , we are adding more test suites. But we do have limitation  from openlab side , as cloud doesnt support online resize etc.

**Comment by jsafrane** [comment]
You can disable certain features in the yaml manifest, however, the tests indeed don't have a capability for online resize. You can either disable `controllerExpansion` / `nodeExpansion` completely or skip some tests with `ginkgo --skip`.

IMO it's far better to re-use Kubernetes tests than having something custom, because you get better feature coverage.

**Comment by chrigl** [comment]
The test suite we run already is the kubernetes one, but calling those from a separate binary. But I am totally with you to go the obvious way of using the e2e.test!

/assign

**Comment by ramineni** [comment]
@jsafrane @chrigl  we are Importing the E2E test suite as a library  and running the tests . so its the same . I dont think any change is required in this, https://kubernetes-csi.github.io/docs/functional-testing.html#importing-the-e2e-test-suite-as-a-library

**Comment by chrigl** [comment]
After playing around with the e2e.test binary, I agree with @ramineni  and think we should stick with what we have. I ported the config and got the exact same tests running. So IMHO it's not worth the effort.

**Comment by jsafrane** [comment]
Is there any parseable output of job-output.txt?

The only available result today https://logs.openlabtesting.org/logs/98/1398/90476d0e8d5643a54444b6c178ef5f59a68825aa/cloud-provider-openstack-acceptance-test-csi-cinder/cloud-provider-openstack-acceptance-test-csi-cinder/07c0414/ says:

`FAIL! -- 7 Passed | 22 Failed | 0 Pending | 95 Skipped`

When I run upstream tests with the manifest from the previous comment, I get quite different numbers:
`48 pass, 139 skip`

**Comment by chrigl** [comment]
I think we are talking about `cloud-provider-openstack-e2e-test-csi-cinder`. I know naming things is hard.

We do upload the [junit file](https://logs.openlabtesting.org/logs/65/1365/c332a9343b85f3639b410f8b2e15fb1af2719a91/cloud-provider-openstack-e2e-test-csi-cinder/cloud-provider-openstack-e2e-test-csi-cinder/cd12859/logs/kubernetes/junit_01.xml) for this tests. I will prepare including e2e.log. And for sure, my pasted test-file was wrong /o\... or being more precise, that was the one I tested in non-CI environment. We are not able to test topology at the moment in CI.

**Comment by chrigl** [comment]
e2e.log should come in the next test-runs: https://github.com/theopenlab/openlab-zuul-jobs/pull/1124

**Comment by jsafrane** [comment]
The linked junit has 29 passed tests, which is 19 test less than what I can get with kubernetes/kubernetes suite. For example,I miss topology. Some tests can run even with cluster in a single zone.

**Comment by jsafrane** [comment]
These tests are not running:
```
 Dynamic PV (block volmode)] multiVolume [Slow] should access to two volumes with different volume mode and retain data across pod recreation on different node [LinuxOnly]
 Dynamic PV (block volmode)] multiVolume [Slow] should access to two volumes with different volume mode and retain data across pod recreation on the same node [LinuxOnly]
 Dynamic PV (block volmode)] multiVolume [Slow] should access to two volumes with the same volume mode and retain data across pod recreation on different node [LinuxOnly]
 Dynamic PV (block volmode)] multiVolume [Slow] should access to two volumes with the same volume mode and retain data across pod recreation on the same node [LinuxOnly]
 Dynamic PV (block volmode)] multiVolume [Slow] should concurrently access the single read-only volume from pods on the same node
 Dynamic PV (block volmode)] multiVolume [Slow] should concurrently access the single volume from pods on the same node [LinuxOnly]
 Dynamic PV (default fs)] fsgroupchangepolicy (Always)[LinuxOnly], pod created with an initial fsgroup, new pod fsgroup applied to volume contents
 Dynamic PV (default fs)] fsgroupchangepolicy (Always)[LinuxOnly], pod created with an initial fsgroup, volume contents ownership changed in first pod, new pod with different fsgroup applied to the volume contents
 Dynamic PV (default fs)] fsgroupchangepolicy (Always)[LinuxOnly], pod created with an initial fsgroup, volume contents ownership changed in first pod, new pod with same fsgroup applied to the volume contents
 Dynamic PV (default fs)] fsgroupchangepolicy (OnRootMismatch)[LinuxOnly], pod created with an initial fsgroup, new pod fsgroup applied to volume contents
 Dynamic PV (default fs)] fsgroupchangepolicy (OnRootMismatch)[LinuxOnly], pod created with an initial fsgroup, volume contents ownership changed in first pod, new pod with different fsgroup applied to the volume contents
 Dynamic PV (default fs)] fsgroupchangepolicy (OnRootMismatch)[LinuxOnly], pod created with an initial fsgroup, volume contents ownership changed in first pod, new pod with same fsgroup skips ownership changes to the volume contents
 Dynamic PV (default fs)] volumeIO should write files of various sizes, verify size, validate content [Slow][LinuxOnly]
 Dynamic PV (delayed binding)] topology should provision a volume and schedule a pod with AllowedTopologies
 Dynamic PV (filesystem volmode)] multiVolume [Slow] should access to two volumes with the same volume mode and retain data across pod recreation on different node [LinuxOnly]
 Dynamic PV (filesystem volmode)] multiVolume [Slow] should access to two volumes with the same volume mode and retain data across pod recreation on the same node [LinuxOnly]
 Dynamic PV (filesystem volmode)] multiVolume [Slow] should concurrently access the single read-only volume from pods on the same node
 Dynamic PV (filesystem volmode)] multiVolume [Slow] should concurrently access the single volume from pods on the same node [LinuxOnly]
 Dynamic PV (immediate binding)] topology should provision a volume and schedule a pod with AllowedTopologies
```

For example. the whole fsGroup feature is not tests. Not that I'd expect it to fail - it depends more on the filesystem (ext4) than Cinder, but it shows how useful is to revisit the tests from time to time to get coverage of new features.

The same for multivolume tests - they ensure that a volume can be attached/detached to/from the same node / different nodes without issues. We had some races in this area in Kubernetes (looong ago) and who knows, maybe the drivers have similar ones.

**Comment by chrigl** [comment]
```
Ran 50 of 166 Specs in 2612.556 seconds
SUCCESS! -- 50 Passed | 0 Failed | 0 Pending | 116 Skipped
--- PASS: Test (2612.56s)
PASS
ok  	command-line-arguments	2612.631s
```
