### ISSUE TITLE
[cinder-csi-plugin] Test enabling / disabling CSI migration with a running application

### ISSUE THREAD

**Issue by jsafrane** [kubernetes/cloud-provider-openstack#1409]
To make sure that CSI migration works as expected, please test (manually):

1. Install Kubernetes on OpenStack with the CSI driver installed + CSI migration disabled (e.g. Kubernetes 1.20, where the migration is disabled by default).
2. Run some workloads (StatefulSets?) that uses some volume(s).
3. Enable the CSI migration.
4. Check that the workloads still work with the volumes.
5. Disable the CSI migration.
6. Check that the workloads still work with the volumes.

Note that enabling / disabling migration is not straightforward! There is a specific order in which the alpha feature gates must be enabled/disabled in Kubernetes components, see https://github.com/kubernetes/community/blob/master/contributors/design-proposals/storage/csi-migration.md#upgradedowngrade-migrateunmigrate-scenarios for details!

CI job for this is nice to have.

**Comment by jsafrane** [comment]
@jsafrane will test with OpenShift / Kubernetes 1.20, keeping unassigned to get more tests with other Kubernetes vendors or even vanilla Kubernetes.

**Comment by jsafrane** [comment]
With OpenStack 4.7 (= Kubernetes 1.20) on a 3 node cluster I ran 10 StatefulSets, each with 3 replicas (=30 Pods) and enabled / disabled the CSI migration of Cinder. Apart from obvious downtime during draining nodes (to enable/disable the migration), I did not find anything obviously wrong.

**Comment by chrigl** [comment]
With Kubernetes 1.20, I ran a 5 node cluster spread across three availability zones (where compute and storage AZ are the same). I enabled Topology support in `csi-cinder-controllerplugin`, with a custom build of `csi-provisioner` (because we wait for a release).

```
kubectl get nodes --show-labels
NAME            STATUS   ROLES                  AGE   VERSION   LABELS
control-plane   Ready    control-plane,master   18d   v1.20.2   beta.kubernetes.io/arch=amd64,beta.kubernetes.io/instance-type=b7c4fa0b-7960-4311-a86b-507dbf58e8ac,beta.kubernetes.io/os=linux,failure-domain.beta.kubernetes.io/region=fra,failure-domain.beta.kubernetes.io/zone=ix1,kubernetes.io/arch=amd64,kubernetes.io/hostname=control-plane,kubernetes.io/os=linux,node-role.kubernetes.io/control-plane=,node-role.kubernetes.io/master=,node.kubernetes.io/instance-type=b7c4fa0b-7960-4311-a86b-507dbf58e8ac,topology.cinder.csi.openstack.org/zone=ix1,topology.kubernetes.io/region=fra,topology.kubernetes.io/zone=ix1
worker-es1-1    Ready    <none>                 18d   v1.20.2   beta.kubernetes.io/arch=amd64,beta.kubernetes.io/instance-type=b7c4fa0b-7960-4311-a86b-507dbf58e8ac,beta.kubernetes.io/os=linux,failure-domain.beta.kubernetes.io/region=fra,failure-domain.beta.kubernetes.io/zone=es1,kubernetes.io/arch=amd64,kubernetes.io/hostname=worker-es1-1,kubernetes.io/os=linux,node.kubernetes.io/instance-type=b7c4fa0b-7960-4311-a86b-507dbf58e8ac,topology.cinder.csi.openstack.org/zone=es1,topology.kubernetes.io/region=fra,topology.kubernetes.io/zone=es1
worker-es1-2    Ready    <none>                 18d   v1.20.2   beta.kubernetes.io/arch=amd64,beta.kubernetes.io/instance-type=b7c4fa0b-7960-4311-a86b-507dbf58e8ac,beta.kubernetes.io/os=linux,failure-domain.beta.kubernetes.io/region=fra,failure-domain.beta.kubernetes.io/zone=es1,kubernetes.io/arch=amd64,kubernetes.io/hostname=worker-es1-2,kubernetes.io/os=linux,node.kubernetes.io/instance-type=b7c4fa0b-7960-4311-a86b-507dbf58e8ac,topology.cinder.csi.openstack.org/zone=es1,topology.kubernetes.io/region=fra,topology.kubernetes.io/zone=es1
worker-ix2-1    Ready    <none>                 18d   v1.20.2   beta.kubernetes.io/arch=amd64,beta.kubernetes.io/instance-type=b7c4fa0b-7960-4311-a86b-507dbf58e8ac,beta.kubernetes.io/os=linux,failure-domain.beta.kubernetes.io/region=fra,failure-domain.beta.kubernetes.io/zone=ix2,kubernetes.io/arch=amd64,kubernetes.io/hostname=worker-ix2-1,kubernetes.io/os=linux,node.kubernetes.io/instance-type=b7c4fa0b-7960-4311-a86b-507dbf58e8ac,topology.cinder.csi.openstack.org/zone=ix2,topology.kubernetes.io/region=fra,topology.kubernetes.io/zone=ix2
worker-ix2-2    Ready    <none>                 16d   v1.20.2   beta.kubernetes.io/arch=amd64,beta.kubernetes.io/instance-type=b7c4fa0b-7960-4311-a86b-507dbf58e8ac,beta.kubernetes.io/os=linux,failure-domain.beta.kubernetes.io/region=fra,failure-domain.beta.kubernetes.io/zone=ix2,kubernetes.io/arch=amd64,kubernetes.io/hostname=worker-ix2-2,kubernetes.io/os=linux,node.kubernetes.io/instance-type=b7c4fa0b-7960-4311-a86b-507dbf58e8ac,topology.cinder.csi.openstack.org/zone=ix2,topology.kubernetes.io/region=fra,topology.kubernetes.io/zone=ix2
```

I created 5 StatefulSets of 2 Pods upfront without CSIMigration, then I added 2 more with CSIMigration.

In total, I enabled and disabled CSIMigration 50 times, without spotting issues. Topology worked like a charm (thanks @jsafrane ).

**Comment by ramineni** [comment]
@jsafrane @chrigl could we close this now? Any more tests pending?

**Comment by jsafrane** [comment]
I think we're fine, two independent vendors tested it 
/close
