### ISSUE TITLE
high failure ratio of cloud-provider-openstack-acceptance-test-keystone-authentication-authorization

### ISSUE THREAD

**Issue by jichenjc** [kubernetes/cloud-provider-openstack#1415]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
/kind bug
> /kind feature

**What happened**:

cloud-provider-openstack-acceptance-test-keystone-authentication-authorization has high failure ratio now
https://github.com/kubernetes/cloud-provider-openstack/pull/1390
https://github.com/kubernetes/cloud-provider-openstack/pull/1398
https://github.com/kubernetes/cloud-provider-openstack/pull/1365

**What you expected to happen**:

**How to reproduce it**:

**Anything else we need to know?**:

**Environment**:
- openstack-cloud-controller-manager(or other related binary) version:
- OpenStack version:
- Others:

**Comment by jichenjc** [comment]
@lingxiankong do you know this is related to previous gate issue (node name not updated) ?
I didn't go to detail until now ...

**Comment by lingxiankong** [comment]
No clue yet, I checked the log the other day, the k8s cluster was installed successfully but there was some failure in API server, I may need to do another sleep debug when I get time.

**Comment by jichenjc** [comment]
ok, I don't have enough info for me to take a look , so let me know anything I can help :)

**Comment by jichenjc** [comment]
I have a successful run now , so close this
