### ISSUE TITLE
[cinder-csi-plugin] Invalid input for field/attribute metadata when creating Volume

### ISSUE THREAD

**Issue by cxl253386709** [kubernetes/cloud-provider-openstack#1435]
[cinder-csi-plugin] Cannot create Volume 

**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
/kind bug 
> /kind feature

**What happened**:
Hi there.I received an error when  I tried to deploy a test deployment in my Openstack environment,and the pvc's status is Pending.
The messages are as follows:
ProvisioningFailed    2s (x10 over 8m34s)       cinder.csi.openstack.org_openstack-cinder-csi-controllerplugin-0_e6c80eba-3859-4751-8cf6-366ae770f27b  failed to provision volume with StorageClass "csi-sc-cinderplugin": rpc error: code = Internal desc = CreateVolume failed with error Bad request with: [POST http://10.0.39.212:8776/v3/6a177e8a5b5e41b9b714180d8af1e95b/volumes], error message: {"badRequest": {"message": "Invalid input for field/attribute metadata. Value: {u'cinder.csi.openstack.org/cluster': u'kubernetes'}. u'cinder.csi.openstack.org/cluster' does not match any of the regexes: '^[a-zA-Z0-9-_:. ]{1,255}$'", "code": 400}}
 
**What you expected to happen**:
The pvc's status should be Bound

**How to reproduce it**:
follow the instructions here :https://github.com/kubernetes/cloud-provider-openstack/blob/master/docs/cinder-csi-plugin/using-cinder-csi-plugin.md

**Anything else we need to know?**:
I think the plugin and storageclass have been correctly installed and configed. 
kubectl get all -n cinder
NAME                                          READY   STATUS    RESTARTS   AGE
pod/openstack-cinder-csi-controllerplugin-0   6/6     Running   0          25h
pod/openstack-cinder-csi-nodeplugin-55758     3/3     Running   1          25h
pod/openstack-cinder-csi-nodeplugin-q94vq     3/3     Running   0          25h

NAME                                            TYPE        CLUSTER-IP   EXTERNAL-IP   PORT(S)   AGE
service/openstack-cinder-csi-controllerplugin   ClusterIP   None         <none>        <none>    25h

NAME                                             DESIRED   CURRENT   READY   UP-TO-DATE   AVAILABLE   NODE SELECTOR   AGE
daemonset.apps/openstack-cinder-csi-nodeplugin   2         2         2       2            2           <none>          25h

NAME                                                     READY   AGE
statefulset.apps/openstack-cinder-csi-controllerplugin   1/1     25h

[root@k8s-master-1 ~]# kubectl get sc
NAME                   PROVISIONER                RECLAIMPOLICY   VOLUMEBINDINGMODE   ALLOWVOLUMEEXPANSION   AGE
csi-cinder-sc-delete   cinder.csi.openstack.org   Delete          Immediate           true                   25h
csi-cinder-sc-retain   cinder.csi.openstack.org   Retain          Immediate           true                   25h
csi-sc-cinderplugin    cinder.csi.openstack.org   Delete          Immediate           false                  24h

[root@k8s-master-1 ~]# kubectl get csidrivers.storage.k8s.io
NAME                       ATTACHREQUIRED   PODINFOONMOUNT   MODES                  AGE
cinder.csi.openstack.org   true             true             Persistent,Ephemeral   25h

**Environment**:
- openstack-cloud-controller-manager(or other related binary) version:1.2.14
- OpenStack version: R
- Others:

**Comment by jichenjc** [comment]
@cxl253386709 this is NOT a CSI plugin issue, instead, your openstack version is too old (you didn't provide but I think it's fairly old from context) 


please check 
https://github.com/openstack/cinder/commit/534fa38f4cb364cb6584c273be8ae2580fabe627

metadata spec defined 
https://github.com/openstack/cinder/commit/534fa38f4cb364cb6584c273be8ae2580fabe627#diff-996fe25274e0ffcac2007c48a09ef1eec43fee39a3972f47b0795f8c368774d0R189

your `'^[a-zA-Z0-9-_:. ]{1,255}$'"` is not same to current code `^[a-zA-Z0-9-_:. /]{1,255}$'` 

so the solution is to add this into your existing openstack code (find that file and line)
then retry again

**Comment by cxl253386709** [comment]
Thank you for the solution.that should be the case
