### ISSUE TITLE
Add supported version of openstack into doc

### ISSUE THREAD

**Issue by jichenjc** [kubernetes/cloud-provider-openstack#1438]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
> /kind bug
 /kind feature

**What happened**:
per https://github.com/kubernetes/cloud-provider-openstack/issues/1435 , I only found we mentioned openstack API https://github.com/kubernetes/cloud-provider-openstack/blob/master/docs/cinder-csi-plugin/using-cinder-csi-plugin.md#driver-config but no openstack version 

in some old openstack version is might lead to some problem so I think we need tell what's our recommendataion and manage expectation of users... @lingxiankong @ramineni thoughts?

**What you expected to happen**:

**How to reproduce it**:

**Anything else we need to know?**:

**Environment**:
- openstack-cloud-controller-manager(or other related binary) version:
- OpenStack version:
- Others:

**Comment by lingxiankong** [comment]
I think we support all *Maintained* versions of OpenStack(https://releases.openstack.org/), don't we?

**Comment by jichenjc** [comment]
not sure we did test for it ?it's just a statement, we can update the doc? 
anyway, we should also say what has been  tested in our gate CI to deliver clear info..

**Comment by ramineni** [comment]
@jichenjc ya, ideally it should work for all Maintained versions of openstack. 
In openlab , we do test only with latest version of Openstack I suppose.

Im not sure if adding in doc would be good idea. As we dont test all in CI and certain features may need more later microversion .version etc. Im not sure we could generalize for all plugins/all features supported.

**Comment by jichenjc** [comment]
if so , how about provide such info and clearly share those kind of information? @ramineni
