### ISSUE TITLE
Setup a CI job to push latest images to dockerhub

### ISSUE THREAD

**Issue by dims** [kubernetes/cloud-provider-openstack#144]
have `make images` to build images, we need to push them probably when our conformance tests pass.

https://hub.docker.com/u/k8scloudprovider/

**Comment by flaper87** [comment]
@dims I'm interested in helping with this but I'm not familiar with our current CI environment for the cloud provider. Any links/docs I can follow to help to get this done?

**Comment by dims** [comment]
@flaper87 we can do it under openlab which is our usual zuul environment. https://github.com/theopenlab/openlab-zuul-jobs

please join #askopenlab, there's a few of us who can help ( Ruichen, zhuli, liusheng and mrhillsman ) 

essentially we'll have to run something like

```
DOCKER_USERNAME=myid DOCKER_PASSWORD=xyz123 REGISTRY=docker.io/k8scloudprovider VERSION=latest make upload-images
```

**Comment by flaper87** [comment]
Running these tests after conformance job passes sounds good to me. I'd assume we'd run them as part of the `post.yaml` operations.

**Comment by mrhillsman** [comment]
@flaper87 have you been able to verify this, if yes, can we close out this issue?

**Comment by flaper87** [comment]
This seems to work fine! I see images being updated by the periodic conformance test!
