### ISSUE TITLE
[openstack-cloud-controller-manager] LoadBalancer creation fails with „Pools must be named when creating a fully populated loadbalancer“

### ISSUE THREAD

**Issue by morremeyer** [kubernetes/cloud-provider-openstack#1441]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:

A deployment with the currently tagged `latest` version (`k8scloudprovider/openstack-cloud-controller-manager@sha256:b2282327cbfb24d5fc12e6fab0f0176f2a6f0a9876ab8499a8e71dad0e4878f9`) can’t create octavia loadbalancers. as the validation fails.

Downgrading to `v1.20.2` fixed the issue.

```
Warning  SyncLoadBalancerFailed  9m35s (x5 over 70m)   service-controller  Error syncing load balancer: failed to ensure load balancer: error creating loadbalancer kube_service_kubernetes_kube-system_ingress-ingress-nginx-controller: error creating loadbalancer [OMITTED VERBOSE DATA HERE]: Bad request with: [POST https://de-cgn.stage.openstack.get-cloud.io:9876/v2.0/lbaas/loadbalancers], error message: {"faultcode": "Client", "faultstring": "Validation failure: Pools must be named when creating a fully populated loadbalancer.", "debuginfo": null}
```

**What you expected to happen**:

Octavia Loadbalancer is created without any errors.

**How to reproduce it**:

Use the cloud-controller-manager with the image `k8scloudprovider/openstack-cloud-controller-manager@sha256:b2282327cbfb24d5fc12e6fab0f0176f2a6f0a9876ab8499a8e71dad0e4878f9` with 

```ini
[LoadBalancer]
use-octavia=true
```

in the `/etc/config/cloud.conf` with OpenStack ussuri.

Create a service of type LoadBalancer, then check the cloud-controller-manager logs.

**Anything else we need to know?**:

I think this is related to @notandy's change in #1365. 

**Environment**:
- openstack-cloud-controller-manager(or other related binary) version: Docker image, `k8scloudprovider/openstack-cloud-controller-manager@sha256:b2282327cbfb24d5fc12e6fab0f0176f2a6f0a9876ab8499a8e71dad0e4878f9`
- OpenStack version: ussuri

**Comment by notandy** [comment]
The initial change included named pools, I had to remove it due to review. Will amend a fix shortly.

**Comment by morremeyer** [comment]
@notandy Thanks a lot! And please take your time, we can obviously stay on the released version for now :)

**Comment by notandy** [comment]
@lingxiankong just wanted to push a pr -_-

**Comment by lingxiankong** [comment]
> @lingxiankong just wanted to push a pr -_-

I didn't see you have assigned to yourself, thought you are not available for a fix.

**Comment by notandy** [comment]
> > @lingxiankong just wanted to push a pr -_-
> 
> 
> 
> I didn't see you have assigned to yourself, thought you are not available for a fix.

That's fine, I tested your quickfix, lgtm.

**Comment by azerbe** [comment]
Can you please release a quickfix for this? This issue is a month old and the image with the "latest" tag hasn't been rebuild so far.

**Comment by lingxiankong** [comment]
@azerbe we didn't realize the latest tag OCCM image hasn't been updated for so long, I will see what I can do.

**Comment by lingxiankong** [comment]
> Can you please release a quickfix for this? This issue is a month old and the image with the "latest" tag hasn't been rebuild so far.

Should be fine now, please try again.

**Comment by azerbe** [comment]
Thanks!
