### ISSUE TITLE
[cinder-csi-plugin] New cinder volumes are created when ephemeral volume fails to attach

### ISSUE THREAD

**Issue by creatica-soft** [kubernetes/cloud-provider-openstack#1444]
[cinder-csi-plugin] If an ephemeral volume fails to attach for any reason, cinder-csi-plugin will keep creating new volumes

> /kind bug

**What happened**:
If an ephemeral volume fails to attach for any reason, cinder-csi-plugin will keep creating new volumes. To stop it, I have to delete the deployment and then manually delete all these volumes from openstack. The current limit of the number of volumes in centos guest seems to be 26 from vda to vdz. So new volumes fail to attach after that limit.

**What you expected to happen**:
The plugin will try to attach the same volume.

**How to reproduce it**:
Same as in #1403

**Anything else we need to know?**:
This is a continuation from #1403.

**Environment**:
- openstack-cloud-controller-manager(or other related binary) version: 1.20.2
- OpenStack version: Pike
- Others: k8s 1.19.6

**Comment by ramineni** [comment]
@creatica-soft In what state the volume is after attach failed?

**Comment by creatica-soft** [comment]
@ramineni It is available. It fails to mount because the number of scsi devices on a single bus, i.e. scsi controller exceeds 32 (well, 26 in this case: letters from a to z). Scsi controllers are not hot-pluggable in KVM, so a reboot is required for the VM even when a controller is added dynamically. But then in order to reboot, one would need to drain the node, at which point all the volumes will be unmounted and the an extra scsi controller would not be required. So not sure if KVM will remove it prior to reboot or not - haven't tested this.

**Comment by ramineni** [comment]
@creatica-soft we are planning to deprecate Inline ephemeral volumes feature in favor of generic ephemeral volumes.
please check https://github.com/kubernetes/cloud-provider-openstack/issues/1493 for more details.

Suggest to use generic ephemeral volumes instead.

**Comment by ramineni** [comment]
Inline ephemeral volumes feature is deprecated from 1.24. Please use generic ephemeral volumes instead
