### ISSUE TITLE
[all] Dev guide for CPO

### ISSUE THREAD

**Issue by jichenjc** [kubernetes/cloud-provider-openstack#1451]
**Is this a BUG REPORT or FEATURE REQUEST?**:

We don't have a dev guide which is fine,but currently there are logs 
such as 1/2/3/4/5 level exist, maybe need some quick definition on this

> Uncomment only one, leave it on its own line: 
>
> /kind bug
> /kind feature

**What happened**:

**What you expected to happen**:

**How to reproduce it**:

**Anything else we need to know?**:

**Environment**:
- openstack-cloud-controller-manager(or other related binary) version:
- OpenStack version:
- Others:

**Comment by lingxiankong** [comment]
The logging has already been defined in Kubernetes: https://github.com/kubernetes/community/blob/master/contributors/devel/sig-instrumentation/logging.md

**Comment by jichenjc** [comment]
I will close this one and compare with existing code to see whether we follow that guide or not :)
thanks for point me the dev guide
