### ISSUE TITLE
[cinder-csi-plugin] --nodeid option is ignored by the driver

### ISSUE THREAD

**Issue by Fedosin** [kubernetes/cloud-provider-openstack#1453]
/kind bug

**What happened**:
Now the binary provides an option called "[--nodeid](https://github.com/kubernetes/cloud-provider-openstack/blob/master/cmd/cinder-csi-plugin/main.go#L77-L78)" that allows to set node ID for the driver. Normally it is set to `spec.nodeName` like in this [chart](https://github.com/kubernetes/cloud-provider-openstack/blob/master/charts/cinder-csi-plugin/templates/nodeplugin-daemonset.yaml#L68-L71).
Unfortunately this value is ignored by the driver, because in reality it fetches node id from [metadata](https://github.com/kubernetes/cloud-provider-openstack/blob/5c287c5f5e4e05ab73a92c853fa5ab34b4ce795d/pkg/csi/cinder/nodeserver.go#L448).
On the other hand Manila CSI driver does it [right](https://github.com/kubernetes/cloud-provider-openstack/blob/27b6fc483451b6df2112a6a4a40a34ffc9093635/pkg/csi/manila/nodeserver.go#L314).

Because of this inconsistency we have next results:

```sh
❯ kubectl get csinode mfedosin-rgrmg-worker-0-bmwx4 -oyaml
...
spec:
  drivers:
  - name: manila.csi.openstack.org
    nodeID: mfedosin-rgrmg-worker-0-bmwx4
    topologyKeys: null
  - allocatable:
      count: 256
    name: cinder.csi.openstack.org
    nodeID: 5934efa7-8169-4490-bf10-922f159c5ad4
    topologyKeys:
    - topology.cinder.csi.openstack.org/zone
```

**What you expected to happen**:
Either `--nodeid` option is deprecated or node id should be the same as specified in `--nodeid`.

**How to reproduce it**:
Deploy Cinder CSI driver and set `--nodeid` like in the [example](https://github.com/kubernetes/cloud-provider-openstack/blob/master/charts/cinder-csi-plugin/templates/nodeplugin-daemonset.yaml#L68-L71).
Execute `kubectl get csinode <nodename> -oyaml` to make sure that `nodeID` is different from `spec.nodeName`.

**Comment by jichenjc** [comment]
I guess we should keep the node ID function and honor it ? 
though not sure whether it will lead to side effect if we set the node name instead of get from metadata

seems we should be consistent for CSI in openstack (which is same to manila)

**Comment by ramineni** [comment]
@Fedosin you are right. node-id values seems to be ignored. Could you provide some additional details?
Are the 2 values different ? one retrieved by metadata service and spec.nodeName . Ideally both should be same. spec.nodeName should contain the node name where the nodeplugin is deployed.

Im thinking whether we could directly use --node-id field or not. Could you share what are the values of both . Thanks

**Comment by Fedosin** [comment]
@ramineni hi! yes, they are different... You can see an example in the issue description. For instance, `spec.nodeName` is `mfedosin-rgrmg-worker-0-bmwx4` and the metadata value is `5934efa7-8169-4490-bf10-922f159c5ad4`.

**Comment by Fedosin** [comment]
I think we can consider next solutions:
1. Deprecate --node-id for cinder-csi-plugin and always use the id value from metadata.
2. Start using --node-id for real and stop fetching the value from metadata.
3. Make --node-id optional. If it's set, then use the provided value, otherwise get the id from metadata.

**Comment by jichenjc** [comment]
>     3\. alue, otherwise get the id from metadata.

looks like 3 is consistent to current behaivor and flexible..

**Comment by ramineni** [comment]
> @ramineni hi! yes, they are different... You can see an example in the issue description. For instance, `spec.nodeName` is `mfedosin-rgrmg-worker-0-bmwx4` and the metadata value is `5934efa7-8169-4490-bf10-922f159c5ad4`.

@Fedosin But the difference is only one is returning name and other is returning id of the same node right? 
I meant `5934efa7-8169-4490-bf10-922f159c5ad4` is the ID of this same node with name `mfedosin-rgrmg-worker-0-bmwx4` ?

**Comment by ramineni** [comment]
@Fedosin @jichenjc I suppose we cant use the node-id field which is set to nodeName in nodeGetInfo as this value is used in controllerPublishVolume later where we query the instance details by ID. So it would fail in that case.

Deprecate the value seems the way to me.
