### ISSUE TITLE
[manila-csi-plugin] allow share volume expansion

### ISSUE THREAD

**Issue by ppeereb1** [kubernetes/cloud-provider-openstack#1475]
/kind feature

**What happened**:
I'm trying to extend a pvc with the manila storageclass but i'm unable to do so, allowVolumeExpansion is set to true in the SC.
Extending a Manila share seems not possible in current situation. While is is possible in Openstack:
https://docs.openstack.org/manila/latest/admin/shared-file-systems-share-resize.html

I couldn't find any reference in the code to extend a pvc for manila, is it not yet implemented?

Regards,
Paul

**Environment**:
- OpenStack version: train

**Comment by gman0** [comment]
Yes, it's not implemented yet but is on our roadmap. Coming soon. If you'd like to take this you're welcome to do so of course.
