### ISSUE TITLE
pvc resize size difference

### ISSUE THREAD

**Issue by jamessewell** [kubernetes/cloud-provider-openstack#1490]
* cinder-csi-plugin

> /kind bug

**What happened**:

I resized a 1GB partition to 10GB, then to 50GB.

Everything works as expected - but I'm only seeing a size of 16GB in my pod mounted filesystem (it did get bigger - just not by the full amount).

```
17m         Normal    Resizing                     persistentvolumeclaim/mslam                    External resizer is resizing volume pvc-e65bf845-7757-49d7-a61d-db224d4ec725
17m         Normal    FileSystemResizeRequired     persistentvolumeclaim/mslam                    Require file system resize of volume on node
16m         Normal    FileSystemResizeSuccessful   persistentvolumeclaim/mslam                    MountVolume.NodeExpandVolume succeeded for volume "pvc-e65bf845-7757-49d7-a61d-db224d4ec725"
```

**What you expected to happen**:

The new PVC size would match the mounted filesystem size at 50GB

**Comment by jichenjc** [comment]
this is weird, what version of CPO you are using? 
and maybe helpful if you check cinder logs as well ...

**Comment by lingxiankong** [comment]
Will open again with more info provided.
