### ISSUE TITLE
[cinder-csi-plugin] In-line ephemeral volumes are dangerous

### ISSUE THREAD

**Issue by jsafrane** [kubernetes/cloud-provider-openstack#1493]
/kind bug

Ephemeral in-line CSI volumes as implemented in the Cinder CSI driver are very limited, hard to use and can be even dangerous in some environments.

The main issues are:
* An user may create as many pods with ephemeral in-line CSI volumes as they want, with any size. There is no way how to restrict them, either with Kubernetes quota or with any other mechanism.
* The CSI driver on *all* nodes require credentials to OpenStack to create, attach, detach and delete volumes. If a regular user can escape its Pod / Container boundaries and break into the host, they can steal these cloud credentials. For that reason, some security constrained deployments put Pods that have credentials to the cloud to master nodes or some dedicated infrastructure nodes, where regular users can't run any Pods. This is not possible with this driver, all nodes must have the credentials.
* kube-controller-manager does not track these volumes, therefore it is not possible to detach and delete volumes from the nodes in case the driver / kubelet dies.

There is already an issue to support Generic Ephemeral Volumes, introduced in Kubernetes 1.19, which are far superior for *persistent* storage like Cinder and should not require any changes in the CSI driver. IMO we should deprecate support of the ephemeral volume support here and eventually even remove the code.

**Comment by jichenjc** [comment]
+1 to deprecate this feature ,see the Generic ephemeral volumes tracked 
https://github.com/kubernetes/cloud-provider-openstack/issues/1448

so maybe something we can consider after that PR is fixed

**Comment by ramineni** [comment]
@jsafrane Is it something being discussed in sig-storage as well to deprecate CSI Inline Volumes in favor of generic ephemeral volumes ?

**Comment by kayrus** [comment]
Relates to #1020
cc @rfranzke

**Comment by ramineni** [comment]
Im ok to deprecate the feature in favor of generic ephemeral volumes. May be we could do in early next cycle?
/cc @jichenjc @lingxiankong wdyt?

**Comment by lingxiankong** [comment]
> Im ok to deprecate the feature in favor of generic ephemeral volumes. May be we could do in early next cycle? /cc @jichenjc @lingxiankong wdyt?

Yep, agree :-)

**Comment by jichenjc** [comment]
>>Im ok to deprecate the feature in favor of generic ephemeral volumes. May be we could do in early next cycle?

+1 to me :)

**Comment by kayrus** [comment]
I don't think that deprecating is a proper solution. Ephemeral volumes are used in other clouds and other clouds somehow solved the issues listed in #1493 and in #1020. IMHO we have to solve underlying problems instead of cutting off the hand.
I have a use case for ephemeral storage and now I need to switch to STS with PVC template. Unfortunately STS has some disadvantages over deployments.
