### ISSUE TITLE
Document how to setup RBAC with Keystone Authentication

### ISSUE THREAD

**Issue by dims** [kubernetes/cloud-provider-openstack#15]
_From @dims on March 16, 2018 21:50_

See note from Saverio on his blog post : https://cloudblog.switch.ch/2018/02/02/openstack-keystone-authentication-for-your-kubernetes-cluster/
```
I will be correctly authenticated by keystone that will verify my identity, but I will have no authorization to do anything:
```

_Copied from original issue: dims/openstack-cloud-controller-manager#87_

**Comment by dims** [comment]
cc @zioproto

**Comment by dims** [comment]
cc @Fedosin

**Comment by dims** [comment]
_From @zioproto on March 19, 2018 9:17_

How can I assign this to me ? I will propose a PR for the documentation.

**Comment by dims** [comment]
We need to test/try what we have in https://github.com/kubernetes/cloud-provider-openstack/tree/master/cluster/addons/rbac

**Comment by zioproto** [comment]
@dims I tested  https://github.com/kubernetes/cloud-provider-openstack/tree/master/cluster/addons/rbac. It works for me.

I deploy both files with my ansible playbook:
https://github.com/zioproto/k8s-on-openstack/tree/cloud-provider-openstack/roles/k8s-rbac/files

I am able to run a simple nginx deployment with a few pods.

I still have to test persistent volumes and LBaaS.
