### ISSUE TITLE
[OCCM] occm version not displayed correctly since 1.21 release

### ISSUE THREAD

**Issue by ramineni** [kubernetes/cloud-provider-openstack#1502]
**Is this a BUG REPORT or FEATURE REQUEST?**:
occm version not displayed correctly on using refactored cloudprovider code from k/k 1.21 release
> Uncomment only one, leave it on its own line: 
>
> /kind bug
> /kind feature

**What happened**:

**What you expected to happen**:

**How to reproduce it**:

**Anything else we need to know?**:

**Environment**:
- openstack-cloud-controller-manager(or other related binary) version:
- OpenStack version:
- Others:

**Comment by lingxiankong** [comment]
ref: https://github.com/kubernetes/cloud-provider-openstack/pull/1440#discussion_r620822121

**Comment by ramineni** [comment]
raised issue in cloudprovider repo for the same , https://github.com/kubernetes/cloud-provider/issues/49

**Comment by MPV** [comment]
Would it be worth peeking at how they did it for the AWS provider — would it work for us here too?

https://github.com/kubernetes/cloud-provider-aws/pull/317

**Comment by jichenjc** [comment]
looks like the problem can be solved by using there example

the only question I am having is following 
```

# ./openstack-cloud-controller-manager-amd64 --version
Kubernetes v1.17.0-426-g033052e-dirty


on master branch
#  git describe
v1.17.0-427-g11155c9

# git checkout v1.23.1
Note: checking out 'v1.23.1'.

# git describe
v1.23.0-4-g1b5899e
```

so `git describe` looks like search for latest tag it can reach, we are using 1.17 now
so I guess everytime we do a release is create a release branch then tag on that branch
thus master branch can reach 1.17 ? 
if we accept this, then I can submit a PR for this @ramineni @lingxiankong @MPV

**Comment by lingxiankong** [comment]
> so I guess everytime we do a release is create a release branch then tag on that branch

Yeah, we should change this.

I think this method could be good workaround for now.
