### ISSUE TITLE
[cinder-csi-plugin] After node restart, in describe pod - FailedMount: Unable to attach or mount volumes

### ISSUE THREAD

**Issue by itayrin** [kubernetes/cloud-provider-openstack#1507]
/kind bug

**What happened**:
Talking about cinder-csi version 1.17.1

A node in the cluster got restarted for some reason (let's say power outage of compute node). Some pod that was on it that had an attached pv, was probably moved and got back again to the restarted node. However, it is stuck on status 'ContainerCreating'.
When running 'kubectl describe po nac-pm-crmq-crmq-0' and it shows - 'Warning  FailedMount  15s    kubelet, cb0125-worker-02  Unable to attach or mount volumes: unmounted volumes=[data], unattached volumes=[... volume names ...]: timed out wait
ing for the condition'.

**What you expected to happen**:
k8s should move the pod with the pv successfully from node to node (deattach and attach successfully).

**How to reproduce it**:
Generall;y I would say just reboot a node that has pods with pvc's on it - but - It didn't happen to every pod on the node even though they had pv's, also it doesn't happen on every reboot. But it did happen in my company at various different setups.  So I'm not sure that a plain restart will be enough but could be.

**Anything else we need to know?**:
**the steps I've tried to do to fix it:**

1. node 'worker-02' restarted for some reason (let's say power outage of compute node)
2. This was long ago so maybe im mistaken, but as I remember - after restart pod came back to worker-02 but was unable to attach volume even though volume is in place (correct device) in openstack and in k8s.
3. as I read in community, I saw that shutting down the node may help, so I shutdown the node where the pod was
4. pod moved to other node ('worker-01), status was crashloopbackoff probably because of internal app issue
5. I turned on the first node
6. as the pod is in crashloopbackoff, I deleted it again
7. it moved automatically to worker-2 (im not sure why, didnt seem to have any configuration causing this) and always does return there
8. **again unable to attach, this time the volume got stuck at 'worker-01'. It's unmounted but still attached there.** So k8s couldn't make the volume be de-attached.
9. could not find any logs in openstack (cinder on controller, nova on computes), could not find anything in logs in controllerplugin pod, nodeplugin pod... /var/log/messages in both worker nodes
10. note - volumeattachments.storage.k8s.io still points at /dev/vdv at worker-01.
11. de-attached volume from openstack
12. volumeattachments.storage.k8s.io still shows the same as before, even though at openstack horizon volume shows "available"
13. after some time of no change, I deleted the pod and ran - 'kubectl describe po nac-pm-crmq-crmq-0' and it still shows - 'Warning  FailedMount  15s    kubelet, cb0125-worker-02  Unable to attach or mount volumes: unmounted volumes=[data], unattached volumes=[nac-pm-crmq-crmq-token-cl6n7 config-volume config-volume-tmp data log ssl-file]: timed out wait
ing for the condition'
14. deleted the volumeattachments.storage.k8s.io. After some time of no change deleted again the pod.
15. same error.

17. tried to helm upgrade to csi-cinder 1.20.3, didn't succeed yet. need change in a lot of charts (naming problems mainly)

**Environment**:
- openstack-cloud-controller-manager(or other related binary) version:
- OpenStack version: Rocky
[root@cb0125-control-01 ~]# helm ls | grep csi-
csi-cinder                      22              Thu Apr 29 01:36:59 2021        DEPLOYED        csi-cinder-1.17.3                       v1.17.0

Relevant image versions:
cinder-csi-plugin - v1.17.1 with charts of 1.17.3
node-driver-registrar v.1.1.0
csi-resizer v0.3.0
csi-snapshotter v1.2.2
csi-provisioner v1.4.0
csi-attacher v2.0.0

Will be happy to get any help or advice about this, Thanks

**Comment by itayrin** [comment]
If any info that you think that's important is missing, please advise

**Comment by lingxiankong** [comment]
I think it's duplicate with https://github.com/kubernetes/cloud-provider-openstack/issues/1354

**Comment by itayrin** [comment]
Could be, except the WAs offered in that thread don't help me, I think. I tried shutting off the node, draining it, deleting it from the k8s cluster - in every step of the above I waited for the pod to come back and each time returned to the same state.
Tried bringing back the node, problem persists.

Checked again /var/log/messages on the 'problematic' node, worker-02:

`
May  4 08:23:44 cb0125-worker-02 kubelet: I0504 08:23:44.152417    4967 reconciler.go:209] operationExecutor.VerifyControllerAttachedVolume started for volume "pvc-dbccdc97-6182-4ac4-8d20-0093216b956c" (UniqueName: "kubernetes.io/csi/cinder.csi.openstack.org^41b2883e-b485-4172-89ee-92a6233a1903") pod "nac-pm-crmq-crmq-0" (UID: "2b087dbc-9da0-4c66-9094-809f2d6b3d44")
May  4 08:23:44 cb0125-worker-02 kubelet: E0504 08:23:44.157101    4967 nestedpendingoperations.go:270] Operation for "\"kubernetes.io/csi/cinder.csi.openstack.org^41b2883e-b485-4172-89ee-92a6233a1903\"" failed. No retries permitted until 2021-05-04 08:25:46.157065002 -0700 PDT m=+814.090503185 (durationBeforeRetry 2m2s). Error: "Volume not attached according to node status for volume \"pvc-dbccdc97-6182-4ac4-8d20-0093216b956c\" (UniqueName: \"kubernetes.io/csi/cinder.csi.openstack.org^41b2883e-b485-4172-89ee-92a6233a1903\") pod \"nac-pm-crmq-crmq-0\" (UID: \"2b087dbc-9da0-4c66-9094-809f2d6b3d44\") "
`

**Comment by henro001** [comment]
I recently observed very similar issue. It started after we migrated to CSI cinder plugin. If a node is rebooted the pod will never come back with the following error 

`Unable to find Device path for volume`

I see an API request from kubelet to delete the attachment during reboot, but if the node dies this will obviously not happen. 
When the node comes back up, the above error is observed. In openstack, the volume is not attached, and on the node, the block device does not exist.

However there is a stale `volumeattachment.storage.k8s.io` with incorrect information. 
This is easily reproducible.
I found several manual workarounds for this (some are safe but painful, some potentially unsafe), but the most straightforward and safest is the following:

1. scale down the statefulset to 0
2. wait until `volumeattachment.storage.k8s.io` are deleted (check with `kubectl get  volumeattachment   --no-headers | wc -l`)
3. scale back up to desired number

I am still looking for actual solution for this but this is good enough for now.

Observed in Kubernetes: 
v1.18.10
v1.19.9

cinder-csi-plugin:v1.18.0

**Comment by ucs69** [comment]
Hi,
In our company our clusters K8S is hosted to OpenStack Plateform.
So we use cloud provider openstack and csi cinder.
Our storageclass use the "kubernetes.io/cinder" csi.
During long time we have suffer when the volume stay with bad state (detaching, deleting, creating, reserved for example).
But since we changed max_pool_size setting to 50 instead of 5 in cinder.conf we have significantly reduce the number of bad volume state.
