### ISSUE TITLE
Cinder package has its own openstack pkg implementation

### ISSUE THREAD

**Issue by j-griffith** [kubernetes/cloud-provider-openstack#151]
/kind improvement

Currently we seem to have 3 implementations of OpenStack providers in the repo:
./cloudprovider/providers/openstack
./csi/cinder/openstack
./provider/openstack

That means we're duplicating a number of things unnecessarily, not to mention there are some bug fixes/updates that don't propagate to all of the packages.

Ideally, we'd have a single top level provider package (provider/openstack) and Cinder plugins would import and use those instead of having their own implementations.  Same for the cloudprovider/provider/openstack, so perhaps consider cleaning up and improving the provider/openstack package and having each of the sub packages import/use that base.

**Comment by yuanying** [comment]
Agree.

My classification is that...
-   cinder-csi-plugin: (for nova instance)
    -   has own provisioner in own package `pkg/csi/cinder/controllerserver.go`
    -   has own attacher in own package `pkg/csi/cinder/controllerserver.go`
    -   has own mounter in own package `pkg/csi/cinder/nodeserver.go`
-   cinder-flexvolume: (for baremetal/novaless)
    -   has no provisioner.
    -   has own attacher in own package `pkg/flexvolume`
    -   has own mounter in own package `pkg/flexvolume` (only RBD?)
-   cinder-provisioner: (for baremetal/novaless)
    -   has own provisioner in own package `pkg/volume/cinder/provisioner`
    -   has no attacher (use in-tree iSCSI/RBD)
    -   has no mounter (use in-tree iSCSI/RBD)

And also it seems that this repository has a lot of copied dead source code for volume plugin such as:
-   `pkg/volume/cinder/*.go`
-   `pkg/cloudprovider/providers/openstack/openstack_volumes.go`

So my suggestion is
-   Share provisioner code for all volume plugins.
-   Share attacher/mounter code for bare metal volume plugins.
-   Share attacher/mounter code for volume plugins for VMs.

Thoughts?

**Comment by dims** [comment]
@yuanying go for it!!! the code was all over the place in different repositories, the first step was to bring them all into the same repository and get them working, now the next step is to do exactly what you and john are talking about. So please go for it.

Note that the pkg/cloudprovider/providers/openstack/openstack_volumes.go is not dead code, we will have to figure out a way to support the previously in-tree provider (probably start it from openstack-controller-manager)

**Comment by yuanying** [comment]
@dims Yes, I'll do!

> Note that the pkg/cloudprovider/providers/openstack/openstack_volumes.go is not dead code, we will have to figure out a way to support the previously in-tree provider (probably start it from openstack-controller-manager)

My understanding is that external cloud provider (not CSI Plugin) can't mount and provide volume for Pod, only can provisioning volumes. Right? (or is there any other volume plugin mechanism?)
So you mean openstack-controller-manager will have [external-provisioner](https://github.com/kubernetes-incubator/external-storage) for cinder volume? 

I think it's better to split external-provisioner from openstack-controller-manager. I mean we should have 2 cinder provisioner (cinder-standalone and cinder-nova) out of openstack-controller-manager.

What do you think?

**Comment by xlucas** [comment]
Any update on this ? I think #312 is a consequence of code duplication among openstack providers that can be solved a more durable way by refactoring the code (or the fix will be another bit of duplicated code from ./cloudprovider/providers/openstack to handle BlockStorageOpts).
