### ISSUE TITLE
Restructure Cinder plugins

### ISSUE THREAD

**Issue by j-griffith** [kubernetes/cloud-provider-openstack#152]
/kind improvement
Looking at the structure of the Cinder CSI packages, trying to utilize the same plugin/package for both the standalone Cinder case and the full Cloud use case is a bit wonky.  It may be worth considering doing some consolidation and restructuring of the package to leverage shared code where possible and keep the different use cases explicitly unique.

**Comment by aglitke** [comment]
Is this the same as #170 ?

**Comment by j-griffith** [comment]
Yep, it's a duplicate

**Comment by j-griffith** [comment]
Duplicate of #170
