### ISSUE TITLE
[helm] appVersion attributes in release-1.21 are set to `latest`

### ISSUE THREAD

**Issue by gman0** [kubernetes/cloud-provider-openstack#1525]
/kind bug

**What happened**:

`appVersion` attributes in Helm charts in release-1.21 branch are set to `latest`.

`appVersion` is used as an image tag in various Pods, e.g. https://github.com/kubernetes/cloud-provider-openstack/blob/release-1.21/charts/openstack-cloud-controller-manager/templates/daemonset.yaml#L33 .

**What you expected to happen**:

`appVersion` should be pinned to a concrete version, not floating `latest`.

I can work on a PR.

**Comment by ramineni** [comment]
fixed by #1526 
/close
