### ISSUE TITLE
[OCCM]use prometheus metrics to replace legacy one? 

### ISSUE THREAD

**Issue by jichenjc** [kubernetes/cloud-provider-openstack#1534]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
> /kind bug
/kind feature

**What happened**:
https://github.com/kubernetes/cloud-provider-openstack/blob/master/pkg/metrics/metrics_reconcile.go#L23
is using legacy metrics, can we move to prometheus (more up-to-date)

**What you expected to happen**:

**How to reproduce it**:

**Anything else we need to know?**:

**Environment**:
- openstack-cloud-controller-manager(or other related binary) version:
- OpenStack version:
- Others:

**Comment by jichenjc** [comment]
@seanschneeweiss can you help to provide some comments?

**Comment by seanschneeweiss** [comment]
I think that most metrics were migrated to `legacyregistry` as part of the [KEP-1209: Metrics Stability Framework](https://github.com/kubernetes/enhancements/tree/master/keps/sig-instrumentation/1209-metrics-stability).

As far as I understand it, we are already using Prometheus wrapped behind the `k8s.io/component-base/metrics` package.
Most other cloud providers are also creating metrics similar to us.
E.g. [this PR](https://github.com/kubernetes/kubernetes/pull/81534/files#diff-9029521db5debda28618b2bbbb7b02c7a130cf1099674c5945837b08abc77ced) moves from Prometheus to `k8s.io/component-base/metrics`.

Not sure if we should move "back".

**Comment by ramineni** [comment]
@jichenjc Can we close this?

**Comment by jichenjc** [comment]
ok, let's close this
