### ISSUE TITLE
[all] Consider switching to (mirroring to) GCR

### ISSUE THREAD

**Issue by ialidzhikov** [kubernetes/cloud-provider-openstack#1540]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind feature
/sig cloud-provider
/area provider/openstack

**What happened**:

Currently cloud provider openstack related images are maintained in Docker Hub. 

In some environments we face Docker Hub rate limits while pulling OCCM or the Cinder CSI driver:

```
  Normal   Pulling    12s              kubelet            Pulling image "docker.io/k8scloudprovider/cinder-csi-plugin:v1.19.0"
  Warning  Failed     11s              kubelet            Failed to pull image "docker.io/k8scloudprovider/cinder-csi-plugin:v1.19.0": rpc error: code = Unknown desc = Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
  Warning  Failed     11s              kubelet            Error: ErrImagePull
```

Last year Docker Hub restricted the amount of image pulls for anonymous and free users. From https://www.docker.com/increase-rate-limits:

> On November 20, 2020, rate limits anonymous and free authenticated use of Docker Hub went into effect. Anonymous and Free Docker Hub users are limited to 100 and 200 container image pull requests per six hours.

After this announcement multiple projects switched to GCR. For example as a mitigation to the Docker Hub rate limits, Istio provides official mirrors to GCR - see https://istio.io/latest/blog/2020/docker-rate-limit/.

I am not sure why cloud provider openstack maintains the images in Docker Hub, probably there are multiple reasons that I am not aware of. From outside, as user of the cloud provider openstack images, it looks a little bit confusing. Currently main K8s components are maintained under GCR (for example `k8s.gcr.io/kube-apiserver`, `k8s.gcr.io/kube-controller-manager`, etc.). I see that K8s CSI sidecars relatively recently switched to GCR as well (`k8s.gcr.io/sig-storage/csi-provisioner`, `k8s.gcr.io/sig-storage/csi-attacher`, etc.). I see that the AWS EBS CSI driver is maintained under `k8s.gcr.io` as well - `k8s.gcr.io/provider-aws/aws-ebs-csi-driver`.
I am not sure whether there is central initiative to maintain the images in the official K8s GCR. But it would be great if cloud provider openstack images are maintained in GCR as well. In this way end users won't need to tackle Docker Hub rate limit issues.

Generally it would be great if maintainers can provider information about:
- Is there a central initiative that is pushing projects under git.k8s.io to use the K8s GCR?
- Is there a plan for cloud provider openstack to maintain its images in GCR or to provide official mirror to GCR?

**Comment by lingxiankong** [comment]
I am not aware of any official announcement describing that kubernetes images should be maintained in GCR (please correct if I missed something). We are very happy to switch to GCR if there is mechanism could be easily integrated with CI or even manual process sounds great.

For production environment, I would recommend mirroring the images on your private image registry to work around the rate limit concern.

**Comment by jichenjc** [comment]
I am suffering this as well so I have to wait long time ... so if we can move away from docker hub and use repo with out pull limit will be great.. @lingxiankong is it a big burden and effort for us to move to GCR (e.g CI dependency, code repo etc ? )

**Comment by lingxiankong** [comment]
As I said:

> We are very happy to switch to GCR if there is mechanism could be easily integrated with CI or even manual process sounds great.

As far as I know, GCR is not free, maybe kubernetes community has some contract with google, but I'm not sure.

**Comment by ramineni** [comment]
adding the comment here for doc reference .
https://github.com/kubernetes/cloud-provider-openstack/issues/1753#issuecomment-1026420268

**Comment by mdbooth** [comment]
This is also a potential governance issue, btw: how is access to the dockerhub repo managed?

**Comment by mdbooth** [comment]
I've submitted https://github.com/kubernetes/test-infra/pull/28817 to run the builds.

**Comment by ialidzhikov** [comment]
@mdbooth does it mean that we can now pull the OCCM and cinder-csi-driver images from GCR?

**Comment by mdbooth** [comment]
Not immediately, but hopefully the next release will be available from registry.k8s.io.

**Comment by ialidzhikov** [comment]
Thanks! I will reopen the issue until the images are available in `registry.k8s.io`.

/reopen

**Comment by ialidzhikov** [comment]
@zetaab I now see that there are many available versions available versions (v1.24.6, v1.25.5, v1.26.2) in GCR - ref https://github.com/kubernetes/k8s.io/blob/main/k8s.gcr.io/images/k8s-staging-provider-os/images.yaml
Is it possible to push the images openstack-ccm and cinder-csi-driver for 1.23 and 1.22? I see that release-v1.23 and release-v1.22 branches have even unreleased changes (ref https://github.com/kubernetes/cloud-provider-openstack/tree/release-1.23 and https://github.com/kubernetes/cloud-provider-openstack/tree/release-1.22).

**Comment by zetaab** [comment]
@ialidzhikov the official support policy in k8s is last 3 minors. Also release-1.23 and release-1.22 are both missing CI pipelines, at least I am not volunteer to start building releases manually or backport CI pipelines to that old releases.

**Comment by ialidzhikov** [comment]
Okay, thanks!
