### ISSUE TITLE
OCCM: doc about nginx-ingress-controller setup

### ISSUE THREAD

**Issue by jichenjc** [kubernetes/cloud-provider-openstack#1541]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
/kind bug
> /kind feature

**What happened**:

https://github.com/kubernetes/cloud-provider-openstack/blob/master/docs/openstack-cloud-controller-manager/expose-applications-using-loadbalancer-type-service.md

we mentioned
```
proxy-protocol: "True"
real-ip-header: "proxy_protocol"
set-real-ip-from: "0.0.0.0/0"
```

but I can't find them in nginx doc (instead, I can see real_ip_header etc )
so where to update those configurations? @lingxiankong ?

**What you expected to happen**:

**How to reproduce it**:

**Anything else we need to know?**:

**Environment**:
- openstack-cloud-controller-manager(or other related binary) version:
- OpenStack version:
- Others:

**Comment by lingxiankong** [comment]
The config options are for nginx itself not for nginx-ingress-controller, in the doc, when installing nginx-ingress-controller by manifests, it just says `Create a config map for customizing NGINX configuration` and actually by default the file content is empty. It's up to the deployer to customize the config based on e.g. https://docs.nginx.com/nginx-ingress-controller/configuration/global-configuration/configmap-resource/#summary-of-configmap-keys.

How to customize nginx is not in the scope of our doc, but it's necessary to mention some required options to work properly with openstack-cloud-controller-manager.

**Comment by jichenjc** [comment]
thanks, I think it's clear
