### ISSUE TITLE
Octavia Ingress Controller example uses cluster admin for ClusterRoleBinding

### ISSUE THREAD

**Issue by relaxdiego** [kubernetes/cloud-provider-openstack#1574]
**Is this a BUG REPORT or FEATURE REQUEST?**: BUG

> /kind bug

**What happened**:

The Octavia Ingress Controller example assigns cluster admin to the service account for the controller as per https://github.com/kubernetes/cloud-provider-openstack/blob/a5e2b9333bf42dff4da896d4efc43cd7ce8c4956/docs/octavia-ingress-controller/using-octavia-ingress-controller.md

**What you expected to happen**:

The document should use a more restricted cluster role since it will also become the basis for production deployments at some point. There are the `system:cloud-controller-manager` and `system:cloud-node-controller` roles and either of those might be useful but I haven't dived deeper into them yet.

**How to reproduce it**:

Just follow the document: https://github.com/kubernetes/cloud-provider-openstack/blob/a5e2b9333bf42dff4da896d4efc43cd7ce8c4956/docs/octavia-ingress-controller/using-octavia-ingress-controller.md

**Environment**:
- openstack-cloud-controller-manager(or other related binary) version: openstack-integrator, wallaby, charm rev 89
- OpenStack version: ussuri

**Comment by jichenjc** [comment]
@lingxiankong FYI
