### ISSUE TITLE
[occm v1.21.0] Cloud provider cannot be empty

### ISSUE THREAD

**Issue by k-s-dean** [kubernetes/cloud-provider-openstack#1581]
/kind bug
**What happened**:
Pod fails to start

**What you expected to happen**:
Pod to start.

**How to reproduce it**:
pull pod version v1.20.0

**Anything else we need to know?**:
```
--cloud-provider cannot be empty
Error: --cloud-provider cannot be empty
Usage:
  cloud-controller-manager [flags]
```

```
      --cloud-provider string                    The provider for cloud services. Empty string for no provider.
```

**Environment**:
- openstack-cloud-controller-manager version: v1.20.0
- OpenStack version: Wallaby

**Comment by lingxiankong** [comment]
Please provide more detailed info. How did you run the openstack-cloud-controller-manager? Can you share the manifest file or command?

**Comment by lingxiankong** [comment]
Please reopen with more details.
