### ISSUE TITLE
[occm] Periodically sync LoadBalancer Services

### ISSUE THREAD

**Issue by squ94wk** [kubernetes/cloud-provider-openstack#1597]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind feature

**What happened**:

When I change something about an Octavia Load Balancer that is managed my OCCM, it's not automatically reconciled to the desired state by OCCM.

An example case is deleting a pool belonging to the LB.

**What you expected to happen**:

The pool is automatically recreated after a short time.

**How to reproduce it**:

Manually delete a LB's pool and wait (in vain).

**Anything else we need to know?**:

After a restart of OCCM the desired state is restored, because OCCM syncs all services initially.

One use case we're running into with this is switching a LB from TCP to Proxy Protocol.
OCCM currently doesn't replace the pools with ones with the desired protocol, which would be another interesting feature for us but is out-of-scope.
So we could delete the pools ourselves and have them be reconciled.
But this would require a restart of OCCM, which isn't ideal.

CSI already has periodic syncs through external-attacher etc..

**Environment**:
- openstack-cloud-controller-manager(or other related binary) version: v1.21.0
- OpenStack version: ?
- Others: K8s 1.20.8

**Comment by lingxiankong** [comment]
Load balancer reconciliation should be part of cloud controller manager functions, I didn't notice there is such mechanism though. Have you ever heard there is any cloud provider supports this?
