### ISSUE TITLE
nodeplugin-daemonset chart template - imagePullPolicy is defined multiple times

### ISSUE THREAD

**Issue by Happy2C0de** [kubernetes/cloud-provider-openstack#1598]
[cinder-csi-plugin] `imagePullPolicy` is specified multiple times in `nodeplugin-daemonset.yaml` chart templates.

See: 

https://github.com/kubernetes/cloud-provider-openstack/blob/905e989d20357f6d7836e3311b430f377f52a451/charts/cinder-csi-plugin/templates/nodeplugin-daemonset.yaml#L40

https://github.com/kubernetes/cloud-provider-openstack/blob/905e989d20357f6d7836e3311b430f377f52a451/charts/cinder-csi-plugin/templates/nodeplugin-daemonset.yaml#L86

**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
/kind bug
> /kind feature

**What happened**:
Helm is not able to validate the corresponding templates because it has multiple `imagePullPolicy` definitions.

**What you expected to happen**:
Only, a single `imagePullPolicy` should be defined per container, ideally configurable with helm.

**How to reproduce it**:
Run helm with validation enabled.

**Anything else we need to know?**:
-

**Environment**:
- openstack-cloud-controller-manager(or other related binary) version:
- OpenStack version:
- Others:

**Comment by Happy2C0de** [comment]
Is there somebody who can take over this fix and who already signed the CLA?

**Comment by ramineni** [comment]
@Happy2C0de Fixed in #1602 .

**Comment by Happy2C0de** [comment]
Very cool. Thanks for the quick reply 👍
