### ISSUE TITLE
[cinder-csi-plugin] Duplicate tolerations key in chart template nodeplugin-daemonset.yaml

### ISSUE THREAD

**Issue by Happy2C0de** [kubernetes/cloud-provider-openstack#1608]
[cinder-csi-plugin] Duplicate tolerations key in `nodeplugin-daemonset.yaml`, analogous to #1599 

https://github.com/kubernetes/cloud-provider-openstack/blob/2155ee9bc6e9376459a971672d936dd17678a022/charts/cinder-csi-plugin/templates/nodeplugin-daemonset.yaml#L16-L17

https://github.com/kubernetes/cloud-provider-openstack/blob/2155ee9bc6e9376459a971672d936dd17678a022/charts/cinder-csi-plugin/templates/nodeplugin-daemonset.yaml#L128

Once I locally fixed it, it worked.

**Note:**
Add the existing tolerations into the default `values.yaml`, see L16:
```
      tolerations:
        - operator: Exists
```

**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
/kind bug
> /kind feature

**What happened**:
Error when deploying the chart with Flux2 (uses Kustomize underneath). Yaml validation failed because of duplicate key.

**What you expected to happen**:
Deploy cinder-csi-plugin chart without any issues with Flux2/Kustomize v4.

**How to reproduce it**:
Install chart with flux >= 0.16.1

**Anything else we need to know?**:
See #1599 

**Environment**:
- openstack-cloud-controller-manager(or other related binary) version: 
- OpenStack version:
- Others:

**Comment by ramineni** [comment]
Looks like we need to keep the validation as part of CI . Thanks for reporting the issue.

**Comment by ramineni** [comment]
Fixed as part of #1609
