### ISSUE TITLE
[openlab CI/CD] Testing resources risk raised.

### ISSUE THREAD

**Issue by bzhaoopenstack** [kubernetes/cloud-provider-openstack#1610]
We had received a sad news https://github.com/theopenlab/openlab/issues/801 .

So much thanks for citynetwork support in these years.

But seems,  cloud-provider-openstack project is relied on the resources providered by citynetwork heavily. So we think this would be a disaster for cloud-provider-openstack usual works/testing. All master env includes zuul, nodepool, web are in citynetwork too. So openlab is drop down now, we are trying to recover it. We are so apologize for this.

We have several options for this:
1. Does cloud-provider-openstack team have any other X86 resources? We can add it into our X86 resource pool after we recover openlab env.
2. If no any other X86 resource from yours, we can only use several X86 resource in switch cloud. The performance is not good compare with the ones in citynetwork.
3. If above 2 are not accept, you and us can consider drop openlab from testing pool towards X86 resources.

**Comment by gouthampacha** [comment]
@fghaas: o/ Hi, adding you to this request; to confirm theopenlab/openlab#801 - and to check if we can explore other avenues, with City Network Cloud.

**Comment by bzhaoopenstack** [comment]
@fghaas @gouthampacha @all, Hi guys, openlab had been recovered. Please see whether the switch cloud can fit your testing requirements. Thanks

**Comment by ramineni** [comment]
@bzhaoopenstack Thanks . Closing this issue as its resolved now.
