### ISSUE TITLE
[cinder-csi-plugin] node-driver-registrar prestop hook not working

### ISSUE THREAD

**Issue by jlyheden** [kubernetes/cloud-provider-openstack#1617]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:

When I install cinder-csi using the helm chart, the node-driver-registrar fails to invoke the prestop hook due to /bin/sh not being present in the container image.

```
$ kubectl get events -n cinder-namespace | grep FailedPreStopHook
17m         Warning   FailedPreStopHook   pod/openstack-cinder-csi-nodeplugin-zsr2n           Exec lifecycle hook ([/bin/sh -c rm -rf /registration/cinder.csi.openstack.org /registration/cinder.csi.openstack.org-reg.sock]) for Container "node-driver-registrar" in Pod "openstack-cinder-csi-nodeplugin-zsr2n_cinder-csi(30888613-f9e1-48fd-8aca-efe5639daa4f)" failed - error: command '/bin/sh -c rm -rf /registration/cinder.csi.openstack.org /registration/cinder.csi.openstack.org-reg.sock' exited with 126: , message: "OCI runtime exec failed: exec failed: container_linux.go:380: starting container process caused: exec: \"/bin/sh\": stat /bin/sh: no such file or directory: unknown\r\n"
```

**What you expected to happen**:

No warnings when applying the helm chart

**How to reproduce it**:

```
$ helm install cinder-csi cpo/openstack-cinder-csi
```

**Anything else we need to know?**:

**Environment**:
- openstack-cloud-controller-manager(or other related binary) version: Helm chart version 1.4.6
- OpenStack version: don't know
- Others: K8s 1.20.7

**Comment by ramineni** [comment]
@jlyheden looks like preStop is no longer required. could be removed . (https://github.com/kubernetes-csi/node-driver-registrar/pull/61) 
Ill update the charts
