### ISSUE TITLE
Dependency on k8s.io/kubernetes is causing issues

### ISSUE THREAD

**Issue by ebilling** [kubernetes/cloud-provider-openstack#1633]
/kind bug

This affects users of the cloud-provider-openstack package by external users (specifically k8s.io/kops)

**What happened**:
When pulling libraries that depend on this repo, the versions cannot be resolved for k8s.io/kubernetes, leading to the need to add replace statements for a large number of other libraries.

go: k8s.io/kops@v1.21.1 requires
        k8s.io/cloud-provider-openstack@v1.21.0 requires
        k8s.io/kubernetes@v1.21.0 requires
        k8s.io/api@v0.0.0: reading k8s.io/api/go.mod at revision v0.0.0: unknown revision v0.0.0

see https://github.com/kubernetes/kops/blob/master/go.mod

k8s.io/kubernetes says that they will not fix it, because no one is supposed to depend on them as a library.

**What you expected to happen**:

This library should isolate its dependencies so as to prevent this issue for others.  This can be done by creating sub-modules or splitting the test drivers into a separate repository.

**How to reproduce it**:

Use Kops or try to use this library from another package and run 'go get'

**Comment by pinaki124** [comment]
@lingxiankong Yes, this issue is still valid:

go: k8s.io/kops@v1.21.1 requires
        k8s.io/cloud-provider-openstack@v1.21.0 requires
        k8s.io/kubernetes@v1.21.0 requires
        k8s.io/api@v0.0.0: reading k8s.io/api/go.mod at revision v0.0.0: unknown revision v0.0.0

**Comment by ramineni** [comment]
@pinaki124 you need to wait for stable release of kops (as its already fixed there), we dont have current plans and backport the same.

**Comment by ramineni** [comment]
/close

already fixed in kops
