### ISSUE TITLE
[manila-csi-plugin] Add manila jobs to test-infra 

### ISSUE THREAD

**Issue by ramineni** [kubernetes/cloud-provider-openstack#1635]
**Is this a BUG REPORT or FEATURE REQUEST?**:
This issue is to track the progress of manila jobs to be added to test-infra 
Parent-issue: #1613
> Uncomment only one, leave it on its own line: 
>
> /kind bug
> /kind feature

**What happened**:

**What you expected to happen**:

**How to reproduce it**:

**Anything else we need to know?**:

**Environment**:
- openstack-cloud-controller-manager(or other related binary) version:
- OpenStack version:
- Others:

**Comment by ramineni** [comment]
manila sanity tests - https://github.com/kubernetes/test-infra/pull/23520

**Comment by gman0** [comment]
https://github.com/kubernetes/test-infra/pull/23878
https://github.com/kubernetes/cloud-provider-openstack/pull/1656

**Comment by ramineni** [comment]
>> After discussion with @ramineni, she pointed out that CSI e2e tests actually should run in a multi-node environment in order for a CSI driver to be eligible for GA graduation.

Re-wording my intent here again ,  IMO its always recommended to use to production env setup in CI instead of going with local cluster if it can be done . As discussed with @gman0 I understand that there is no as such issues/bottle neck to use multi node , so I suggest we should go with that setup instead. 

@gman0 we don't maintain status as such for our plugins (alpha, beta, GA) AFAIK . This is one of the criteria we have come across while driving CSI migration , that's one of the reason we have started migrating the jobs to multi node setup thereafter. So I suggest not to go back again to use local-up-cluster.sh or other unless its a necessity to run the jobs.

**Comment by gman0** [comment]
We don't have CSI sanity tests currently enabled right?

**Comment by ramineni** [comment]
@gman0 we have them added here , https://github.com/kubernetes/test-infra/blob/master/config/jobs/kubernetes/cloud-provider-openstack/provider-openstack-presubmits-release-master-config.yaml#L125 . Are they not getting triggered?

**Comment by ramineni** [comment]
@gman0 And also, do you have plans to enable other e2e test suites for this release. IMO its good to have when you are bumping sidecars , to see no breakage is there.

**Comment by gman0** [comment]
@ramineni yes of course, I'm just busy with other things at the moment.

**Comment by gman0** [comment]
I think we can close this? Most of the e2e test suites have been integrated to manila-csi, with the exception of FsGroupChangePolicyTestSuite that I still need to get around to look at. See notes here https://github.com/kubernetes/cloud-provider-openstack/pull/1762#issuecomment-1019997426.

**Comment by ramineni** [comment]
@gman0 +1
