### ISSUE TITLE
[occm] Idiosyncratic yaml in helm values

### ISSUE THREAD

**Issue by ouroboros8** [kubernetes/cloud-provider-openstack#1637]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:
Currently the `controllerExtraArgs` key takes a string argument which is parsed as a YAML template and inserted into the daemonset manifest.

**What you expected to happen**:
`controllerExtraArgs` should take a list of extra arguments. This is less confusing to users (the list of args is just a list, not a template of a list) and makes the templating more robust.

**Anything else we need to know?**:
This is quite easy to fix (I'm happy to raise a PR to do so) but will likely break users' current `values.yaml` files. Since the issue is minor, I'd welcome advice on whether a PR would be useful.

**Comment by lingxiankong** [comment]
@ouroboros8 Thanks for reporting this issue, please feel free to submit a PR, given this will be a backward-incompatible change, we need to bump the Chart major version.
