### ISSUE TITLE
[k8s-keystone-auth] did anyone use k8s-keystone-auth for authorization

### ISSUE THREAD

**Issue by Betterme001** [kubernetes/cloud-provider-openstack#1641]
[k8s-keystone-auth] 

I notice that k8s k8s-keystone-auth can be Kubernetes webhook for  authentication and authorization. I guess it is offen used for authentication, but how dose it work for authorization . I summarize three ways to use k8s-keystone-auth.
1.  Just use k8s-keystone-auth to authentication , use RBAC for authorization with user ID/project ID in Keystone.
2. Use k8s-keystone-auth for authentication and authorization, we need config policy in key stone auth policy configmap for every user or project. but the problem is that if we want bind a role to a user ,we must assign a admin/member role to a user in openstack, but the user may not need to manage objects in openstack.
3. We just config admin role of  openstack in policy configmap for k9s-keystone-auth, the admin role of openstack has cluster_admin role in k3s. other users is authorised by k8s RBAC.

I advise 1 and 3 way,  which way  do you use k8s-keystone-auth ?

**Comment by jichenjc** [comment]
@lingxiankong did your cloud use this function?
@ramineni did OCP use this ?

**Comment by lingxiankong** [comment]
@Betterme001 Thanks for bringing up this discussion.

As you said, k8s-keystone-auth is quite flexible and the two authorization modes (RBAC and webhook) can be used in parallel based on your business requirements.

I don't fully understand your concerns in option 2, I'd appreciate if you could elaborate more.

> but the problem is that if we want bind a role to a user ,we must assign a admin/member role to a user in openstack, but the user may not need to manage objects in openstack.

**Comment by lingxiankong** [comment]
> @lingxiankong did your cloud use this function?

We do.

**Comment by Betterme001** [comment]
> but the problem is that if we want bind a role to a user ,we must assign a admin/member role to a user in openStack, but the user may not need to manage ob

Um, I misunderstood, I thought I had to  assign a role admin member for the user in openStack before I assign a  role in k8s-keystone-auth policy. In fact , I can just bind  a user name without admin/member role in openStack  to a role in k8s-keystone-auth policy.

I am confused that If we don't use the role(openStack admin/member)  in k8s-keystone-auth policy, what is the necessity of using k8s-keystone-auth for authorization? we can just use k8s RBAC with k8s-keystone-auth authentication.

So I don't think every user with openStack role need role in k8s, every user with k8s role need role in openStack , maybe we just assign a few user with both openStack role and k8s role , for example, admin in openStack may need cluster_admin in k8s.

**Comment by lingxiankong** [comment]
> what is the necessity of using k8s-keystone-auth for authorization?

Because with k8s-keystone-auth, the openstack users could have access to the k8s cluster without having k8s cluster credentials. Please have a look at the concept and workflow of kubernetes webhook authn and authz.

> admin in openStack may need cluster_admin in k8s.

Why? Normally the openstack admin user is not necessarily the k8s cluster admin.
