### ISSUE TITLE
[occm] occm doesn't handle correctly passwords using dollar sign

### ISSUE THREAD

**Issue by sergiomanso** [kubernetes/cloud-provider-openstack#1647]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:

openstack-cloud-controller-manager fails to authenticate when the specified openstack tenant password is using a dollar sign

**What you expected to happen**:

occm to succeed to authenticate with the following configuration

[Global]
region=RegionOne
username=username
password=password$n#1
auth-url=https://openstack.cloud:5000/v3
tenant-id=14ba698c0aec4fd6b7dc8c310f664009
domain-id=default
ca-file=/etc/kubernetes/ca.pem

**How to reproduce it**:

1. Create a tenant password that includes the dollar sign on it
2. Establish the cloud config and create its kubernetes secret
3. Deploy occm daemonset
4. occm should report a "Authentication failed." message

**Anything else we need to know?**:

The workaround found for this issue was to include double quotes around the password.

[Global]
region=RegionOne
username=username
password="password$n#1"
auth-url=https://openstack.cloud:5000/v3
tenant-id=14ba698c0aec4fd6b7dc8c310f664009
domain-id=default
ca-file=/etc/kubernetes/ca.pem

**Environment**:
- openstack-cloud-controller-manager v1.18.0
- VIO (VMware Integrated OpenStack)
- Charmed Kubernetes 1.21 (using openstack-integrator charm v140)

**Comment by jichenjc** [comment]
I don't have env to try myself. but I suspect we are using code from https://github.com/gophercloud/gophercloud/
so mostly this kind of special string handling should be done in gophercloud?

**Comment by lingxiankong** [comment]
I think it's not `$` but `#` made the authentication failed because `#` is used for comments. If that's part of the config value, it should be enclosed in double quotes, which is not a workaround but a correct solution.
