### ISSUE TITLE
manila nfs dynamic provisioning not working

### ISSUE THREAD

**Issue by sdputurn** [kubernetes/cloud-provider-openstack#1653]
issue: after following the deployment guide of manila nfs CSI. and trying the dynamic_provisioning example, pvc are not woking. pvc is getting stack at:
```  Normal  ExternalProvisioning  3m36s (x103 over 28m)  persistentvolume-controller  waiting for a volume to be created, either by external provisioner "nfs.manila.csi.openstack.org" or manually created by system administrator```

how to reproduce:
1. follow the steps  to deploy manila csi plugin. Use helm to deploy - helm install ./charts/manila-csi-plugin
2. run all yams in example folder - https://github.com/kubernetes/cloud-provider-openstack/tree/master/examples/manila-csi-plugin/nfs/dynamic-provisioning
3. pvc "new-nfs-share-pvc" get stuck in pending state
4. logs in manila node plugin and controller plugin shows below error:

kubectl logs manila-nfs-openstack-manila-csi-nodeplugin-74r2c nfs-nodeplugin --tail=10
W0927 19:15:44.731561       1 builder.go:88] still connecting to unix:///var/lib/kubelet/plugins/csi-nfsplugin/csi.sock
W0927 19:15:45.731202       1 builder.go:88] still connecting to unix:///var/lib/kubelet/plugins/csi-nfsplugin/csi.sock
W0927 19:15:46.730517       1 builder.go:88] still connecting to unix:///var/lib/kubelet/plugins/csi-nfsplugin/csi.sock

kubectl logs manila-nfs-openstack-manila-csi-controllerplugin-0 nfs-provisioner --tail=10
W0927 19:13:05.815748       1 connection.go:172] Still connecting to unix:///var/lib/kubelet/plugins/nfs.manila.csi.openstack.org/csi-controllerplugin.sock
W0927 19:13:15.816312       1 connection.go:172] Still connecting to unix:///var/lib/kubelet/plugins/nfs.manila.csi.openstack.org/csi-controllerplugin.sock
W0927 19:13:25.816022       1 connection.go:172] Still connecting to unix:///var/lib/kubelet/plugins/nfs.manila.csi.openstack.org/csi-controllerplugin.sock
W0927 19:13:35.815939       1 connection.go:172] Still connecting to unix:///var/lib/kubelet/plugins/nfs.manila.csi.openstack.org/csi-controllerplugin.sock

**Comment by gouthampacha** [comment]
Hi @sdputurn, have you installed the nfs node plugin? is it in a healthy state? https://github.com/kubernetes-csi/csi-driver-nfs

**Comment by sdputurn** [comment]
thanks @gouthampacha after deploying nfs node plugin the manila csi services started coming up. PVC events are progressing. currently provisioning is failing due to - {"badRequest": {"code": 400, "message": "Share network must be set when the driver_handles_share_servers is true."}}

can you please help me how to fix this error?

**Comment by sdputurn** [comment]
got this fixed by adding shareNetworkID in the storageclass properties. but this parameter is given as option in the docs.

**Comment by gouthampacha** [comment]
> got this fixed by adding shareNetworkID in the storageclass properties. but this parameter is given as option in the docs.

@sdputurn - yes, shareNetworkID would be required when the manila share type's ``driver_handles_share_servers`` extra-spec is set to True; i've fixed the wiki that the documentation links to call this out: https://wiki.openstack.org/wiki/Manila/Concepts#share_network
