### ISSUE TITLE
gate failure: devstack not able to install

### ISSUE THREAD

**Issue by jichenjc** [kubernetes/cloud-provider-openstack#1663]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
> /kind bug
> /kind feature

**What happened**:

https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/cloud-provider-openstack/1585/openstack-cloud-csi-cinder-e2e-test/1447442829453299712/build-log.txt

```
TASK [install-devstack : Git checkout devstack] ********************************
fatal: [34.150.152.244]: FAILED! => {
    "changed": false,
    "cmd": "/usr/bin/git ls-remote https://opendev.org/openstack/devstack -h refs/heads/stable/wallaby",
    "rc": 128
}

STDERR:

fatal: unable to access 'https://opendev.org/openstack/devstack/': server certificate verification failed. CAfile: none CRLfile: none


```

**What you expected to happen**:

**How to reproduce it**:

**Anything else we need to know?**:

**Environment**:
- openstack-cloud-controller-manager(or other related binary) version:
- OpenStack version:
- Others:

**Comment by jichenjc** [comment]
trying to follow GIT_SSL_NO_VERIFY=1 to skip verification through #1664 now

**Comment by lingxiankong** [comment]
@ramineni @lingxiankong which approach do you prefer?

**Comment by jichenjc** [comment]
opendev.org is official website, github is mirror
so I prefer official site ...

**Comment by lingxiankong** [comment]
> opendev.org is official website, github is mirror so I prefer official site ...

Well, I agree with you. I would suggest we go for this PR as a temporary workaround.

**Comment by jichenjc** [comment]
@lingxiankong can you help to merge #1664 ? thanks
