### ISSUE TITLE
[cinder-csi-plugin]: "Could not determine device path" reported in NodeExpandVolume during PVC resize

### ISSUE THREAD

**Issue by zhoudayongdennis** [kubernetes/cloud-provider-openstack#1695]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
/kind bug
> /kind feature

**What happened**:

cinder csi resize functionality issue as below basic step:
a. apply the pvc, and corresponding pv and pvc created successfully
b. apply the pod referred to that pvc, and corresponding pod created and pv attached to node successfully
c. stop the pod and edit the pvc with larger size
d. the pv size got increased successfully
e. restart the pod, but in pending status with below error message.

  Warning  FailedMount  3s (x561 over 18h)   kubelet, bcmt-ovs-dc01-worker-44  MountVolume.MountDevice failed while expanding volume for volume "pvc-80e64357-8af0-4a18-8bd6-c325e94d19f6" : MountVolume.NodeExpandVolume failed : Expander.NodeExpand failed to expand the volume : rpc error: code = Internal desc = Could not determine device path: exit status 127

**What you expected to happen**:
the pvc should be resized and mounted to pod and pod should be up

**How to reproduce it**:
here was the detail steps with out in local test bed. FYI

[root@control-0 denis-files]# kubectl get sc
NAME                                PROVISIONER                    AGE

cinder-az-nova (default)            cinder.csi.openstack.org       562d

[root@control-0 denis-files]# kubectl describe sc cinder-az-nova
Name:            cinder-az-nova
IsDefaultClass:  Yes
Annotations:     kubectl.kubernetes.io/last-applied-configuration={"allowVolumeExpansion":true,"apiVersion":"storage.k8s.io/v1","kind":"StorageClass","metadata":{"annotations":{"storageclass.kubernetes.io/is-default-class":"true"},"name":"cinder-az-nova"},"parameters":{"availability":"nova"},"provisioner":"cinder.csi.openstack.org"}
,storageclass.kubernetes.io/is-default-class=true
Provisioner:           cinder.csi.openstack.org
Parameters:            availability=nova
AllowVolumeExpansion:  True
MountOptions:          <none>
ReclaimPolicy:         Delete
VolumeBindingMode:     Immediate
Events:                <none>

[root@control-0]# cat test-pvc.yml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    volume.beta.kubernetes.io/storage-provisioner: cinder.csi.openstack.org
  finalizers:
  - kubernetes.io/pvc-protection
  name: server-test
  namespace: ncms
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: cinder-az-nova
  volumeMode: Filesystem
[root@control-0]# kubectl apply -f test-pvc.yml
persistentvolumeclaim/server-test created
[root@control-0]# kubectl get pvc -n ncms
NAME                          STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS     AGE
server-test                   Bound    pvc-80e64357-8af0-4a18-8bd6-c325e94d19f6   5Gi        RWO            cinder-az-nova   2s
[root@control-0]# kubectl describe pvc -nncms server-test
Name:          server-test
Namespace:     ncms
StorageClass:  cinder-az-nova
Status:        Bound
Volume:        pvc-80e64357-8af0-4a18-8bd6-c325e94d19f6
Labels:        <none>
Annotations:   kubectl.kubernetes.io/last-applied-configuration:
                 {"apiVersion":"v1","kind":"PersistentVolumeClaim","metadata":{"annotations":{"volume.beta.kubernetes.io/storage-provisioner":"cinder.csi.o...
               pv.kubernetes.io/bind-completed: yes
               pv.kubernetes.io/bound-by-controller: yes
               volume.beta.kubernetes.io/storage-provisioner: cinder.csi.openstack.org
Finalizers:    [kubernetes.io/pvc-protection]
Capacity:      5Gi
Access Modes:  RWO
VolumeMode:    Filesystem
Mounted By:    <none>
Events:
  Type    Reason                 Age   From                                                                                         Message
  ----    ------                 ----  ----                                                                                         -------
  Normal  ExternalProvisioning   17s   persistentvolume-controller                                                                  waiting for a volume to be created, either by external provisioner "cinder.csi.openstack.org" or manually created by system administrator
  Normal  Provisioning           17s   cinder.csi.openstack.org_csi-cinder-controllerplugin-0_a204725c-bfe4-463f-8d3a-27ff7e5ef9f9  External provisioner is provisioning volume for claim "ncms/server-test"
  Normal  ProvisioningSucceeded  16s   cinder.csi.openstack.org_csi-cinder-controllerplugin-0_a204725c-bfe4-463f-8d3a-27ff7e5ef9f9  Successfully provisioned volume pvc-80e64357-8af0-4a18-8bd6-c325e94d19f6
[root@control-0]# cat test-pod.yml
apiVersion: v1
kind: Pod
metadata:
  annotations:
    kubernetes.io/psp: bcmt-ip-man-psp
  name: pod-test
  namespace: ncms
spec:
  containers:
  - args:
    - sleep
    - infinity
    image: bcmt-registry:5000/busybox
    imagePullPolicy: IfNotPresent
    name: pod-test
    ports:
    - containerPort: 9090
      protocol: TCP
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /data
      name: storage-volume
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  restartPolicy: Always
  schedulerName: default-scheduler
  volumes:
  - name: storage-volume
    persistentVolumeClaim:
      claimName: server-test
[root@control-0]# kubectl apply -f test-pod.yml
pod/pod-test created
[root@control-0]# kubectl get pods -nncms | grep test
pod-test                                  1/1     Running   0          13s
[root@control-0]# kubectl describe pods -nncms pod-test
Name:         pod-test
Namespace:    ncms
Priority:     0
Node:         bcmt-ovs-dc01-worker-34/172.16.3.47
Start Time:   Wed, 10 Nov 2021 13:30:06 +0100
Labels:       <none>
Annotations:  kubectl.kubernetes.io/last-applied-configuration:
                {"apiVersion":"v1","kind":"Pod","metadata":{"annotations":{"kubernetes.io/psp":"bcmt-ip-man-psp"},"name":"pod-test","namespace":"ncms"},"s...
              kubernetes.io/psp: bcmt-ip-man-psp
              podpreset.admission.kubernetes.io/podpreset-mount-local-time: 2687
Status:       Running
IP:           172.16.4.116
IPs:
  IP:  172.16.4.116
Containers:
  pod-test:
    Container ID:  docker://01e43c41862e505b23f21144b6fd5c958979ab30e1840f2ec0a9b2a67542ee6b
    Image:         bcmt-registry:5000/busybox
    Image ID:      docker-pullable://bcmt-registry:5000/busybox@sha256:08d34be80b4fb5bab312f9ca05c0afd88e43ba1681387ccce6e3b027c12dad42
    Port:          9090/TCP
    Host Port:     0/TCP
    Args:
      sleep
      infinity
    State:          Running
      Started:      Wed, 10 Nov 2021 13:30:17 +0100
    Ready:          True
    Restart Count:  0
    Environment:    <none>
    Mounts:
      /data from storage-volume (rw)
      /etc/localtime from host-timezone (ro)
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-lkbxp (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             True 
  ContainersReady   True 
  PodScheduled      True 
Volumes:
  storage-volume:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  server-test
    ReadOnly:   false
  host-timezone:
    Type:          HostPath (bare host directory volume)
    Path:          /etc/localtime
    HostPathType:  
  default-token-lkbxp:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-lkbxp
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 180s
                 node.kubernetes.io/unreachable:NoExecute for 180s
Events:
  Type    Reason                  Age   From                              Message
  ----    ------                  ----  ----                              -------
  Normal  Scheduled               21s   default-scheduler                 Successfully assigned ncms/pod-test to bcmt-ovs-dc01-worker-34
  Normal  SuccessfulAttachVolume  17s   attachdetach-controller           AttachVolume.Attach succeeded for volume "pvc-80e64357-8af0-4a18-8bd6-c325e94d19f6"
  Normal  Pulling                 10s   kubelet, bcmt-ovs-dc01-worker-34  Pulling image "bcmt-registry:5000/busybox"
  Normal  Pulled                  10s   kubelet, bcmt-ovs-dc01-worker-34  Successfully pulled image "bcmt-registry:5000/busybox"
  Normal  Created                 10s   kubelet, bcmt-ovs-dc01-worker-34  Created container pod-test
  Normal  Started                 10s   kubelet, bcmt-ovs-dc01-worker-34  Started container pod-test

[root@control-0]#  kubectl delete pods -nncms pod-test
pod "pod-test" deleted
[root@control-0]# kubectl get pods -nncms | grep test
[root@control-0]# kubectl get pvc -nncms
NAME                          STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS     AGE
server-test                   Bound    pvc-80e64357-8af0-4a18-8bd6-c325e94d19f6   5Gi        RWO            cinder-az-nova   2m7s
[root@control-0]# kubectl edit pvc server-test -nncms
persistentvolumeclaim/server-test edited
[root@control-0]# kubectl get pvc -nncms server-test
NAME          STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS     AGE
server-test   Bound    pvc-80e64357-8af0-4a18-8bd6-c325e94d19f6   5Gi        RWO            cinder-az-nova   2m59s
[root@control-0]# kubectl get pv | grep -i test
pvc-80e64357-8af0-4a18-8bd6-c325e94d19f6   7Gi        RWO            Delete           Bound         ncms/server-test                                 cinder-az-nova                    3m12s
[root@control-0]# kubectl describe pvc -nncms server-test
Name:          server-test
Namespace:     ncms
StorageClass:  cinder-az-nova
Status:        Bound
Volume:        pvc-80e64357-8af0-4a18-8bd6-c325e94d19f6
Labels:        <none>
Annotations:   kubectl.kubernetes.io/last-applied-configuration:
                 {"apiVersion":"v1","kind":"PersistentVolumeClaim","metadata":{"annotations":{"volume.beta.kubernetes.io/storage-provisioner":"cinder.csi.o...
               pv.kubernetes.io/bind-completed: yes
               pv.kubernetes.io/bound-by-controller: yes
               volume.beta.kubernetes.io/storage-provisioner: cinder.csi.openstack.org
Finalizers:    [kubernetes.io/pvc-protection]
Capacity:      5Gi
Access Modes:  RWO
VolumeMode:    Filesystem
Mounted By:    <none>
Conditions:
  Type                      Status  LastProbeTime                     LastTransitionTime                Reason  Message
  ----                      ------  -----------------                 ------------------                ------  -------
  FileSystemResizePending   True    Mon, 01 Jan 0001 00:00:00 +0000   Wed, 10 Nov 2021 13:32:08 +0100           Waiting for user to (re-)start a pod to finish file system resize of volume on node.
Events:
  Type     Reason                    Age    From                                                                                         Message
  ----     ------                    ----   ----                                                                                         -------
  Normal   ExternalProvisioning      4m16s  persistentvolume-controller                                                                  waiting for a volume to be created, either by external provisioner "cinder.csi.openstack.org" or manually created by system administrator
  Normal   Provisioning              4m16s  cinder.csi.openstack.org_csi-cinder-controllerplugin-0_a204725c-bfe4-463f-8d3a-27ff7e5ef9f9  External provisioner is provisioning volume for claim "ncms/server-test"
  Normal   ProvisioningSucceeded     4m15s  cinder.csi.openstack.org_csi-cinder-controllerplugin-0_a204725c-bfe4-463f-8d3a-27ff7e5ef9f9  Successfully provisioned volume pvc-80e64357-8af0-4a18-8bd6-c325e94d19f6
  Warning  ExternalExpanding         94s    volume_expand                                                                                Ignoring the PVC: didn't find a plugin capable of expanding the volume; waiting for an external controller to process this PVC.
  Normal   Resizing                  94s    external-resizer cinder.csi.openstack.org                                                    External resizer is resizing volume pvc-80e64357-8af0-4a18-8bd6-c325e94d19f6
  Normal   FileSystemResizeRequired  94s    external-resizer cinder.csi.openstack.org                                                    Require file system resize of volume on node
[root@control-0]# kubectl apply -f test-pod.yml
pod/pod-test created
[root@control-0]# kubectl get pods -nncms | grep test
pod-test                                  0/1     ContainerCreating   0          62s
[root@control-0]# kubectl describe pods -nncms pod-test
Name:         pod-test
Namespace:    ncms
Priority:     0
Node:         bcmt-ovs-dc01-worker-44/172.16.3.57
Start Time:   Wed, 10 Nov 2021 13:34:35 +0100
Labels:       <none>
Annotations:  kubectl.kubernetes.io/last-applied-configuration:
                {"apiVersion":"v1","kind":"Pod","metadata":{"annotations":{"kubernetes.io/psp":"bcmt-ip-man-psp"},"name":"pod-test","namespace":"ncms"},"s...
              kubernetes.io/psp: bcmt-ip-man-psp
              podpreset.admission.kubernetes.io/podpreset-mount-local-time: 2687
Status:       Pending
IP:           
IPs:          <none>
Containers:
  pod-test:
    Container ID:  
    Image:         bcmt-registry:5000/busybox
    Image ID:      
    Port:          9090/TCP
    Host Port:     0/TCP
    Args:
      sleep
      infinity
    State:          Waiting
      Reason:       ContainerCreating
    Ready:          False
    Restart Count:  0
    Environment:    <none>
    Mounts:
      /data from storage-volume (rw)
      /etc/localtime from host-timezone (ro)
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-lkbxp (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             False 
  ContainersReady   False 
  PodScheduled      True 
Volumes:
  storage-volume:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  server-test
    ReadOnly:   false
  host-timezone:
    Type:          HostPath (bare host directory volume)
    Path:          /etc/localtime
    HostPathType:  
  default-token-lkbxp:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-lkbxp
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 180s
                 node.kubernetes.io/unreachable:NoExecute for 180s
Events:
  Type     Reason                  Age                From                              Message
  ----     ------                  ----               ----                              -------
  Normal   Scheduled               65s                default-scheduler                 Successfully assigned ncms/pod-test to bcmt-ovs-dc01-worker-44
  Normal   SuccessfulAttachVolume  61s                attachdetach-controller           AttachVolume.Attach succeeded for volume "pvc-80e64357-8af0-4a18-8bd6-c325e94d19f6"
  Warning  FailedMount             24s (x7 over 56s)  kubelet, bcmt-ovs-dc01-worker-44  MountVolume.MountDevice failed while expanding volume for volume "pvc-80e64357-8af0-4a18-8bd6-c325e94d19f6" : MountVolume.NodeExpandVolume failed : Expander.NodeExpand failed to expand the volume : rpc error: code = Internal desc = Could not determine device path: exit status 127
[root@bcmt-ovs-dc01-control-0 denis-files]# kubectl get pods -nncms -owide | grep test
pod-test                                  0/1     ContainerCreating   0          98s    <none>         bcmt-ovs-dc01-worker-44   <none>           <none>

[cloud-user@worker-44 ~]$ lsblk
NAME   MAJ:MIN RM  SIZE RO TYPE MOUNTPOINT
sr0     11:0    1  478K  0 rom  
vda    253:0    0  150G  0 disk 
â””â”€vda1 253:1    0  150G  0 part /
vdb    253:16   0  150G  0 disk /data0
vdc    253:32   0 27.4T  0 disk /var/lib/kubelet/pods/57dcf577-a49c-4cec-b7dd-7241d9e1428b/volumes/kubernetes.io~csi/pvc-0b7a6323-abe6-409d-9a3b-d2ff217b67c0/mount
vdd    253:48   0    7G  0 disk /var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-80e64357-8af0-4a18-8bd6-c325e94d19f6/globalmount
[root@worker-44 ~]# cd /var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-80e64357-8af0-4a18-8bd6-c325e94d19f6/globalmount
[root@control-0 ~]# kubectl get volumeattachment | grep c325e94d19f6
csi-d17b4e5166ab8791a954fd333f8a05be45e002f4668908abc61cac6674dc41fa   cinder.csi.openstack.org   pvc-80e64357-8af0-4a18-8bd6-c325e94d19f6   bcmt-ovs-dc01-worker-44   true       18h
[root@control-0 ~]# kubectl get volumeattachment csi-d17b4e5166ab8791a954fd333f8a05be45e002f4668908abc61cac6674dc41fa -oyaml
apiVersion: storage.k8s.io/v1
kind: VolumeAttachment
metadata:
  annotations:
    csi.alpha.kubernetes.io/node-id: 235d80af-f8fb-4100-81ea-dc5ed1b38bf9
  creationTimestamp: "2021-11-10T12:34:35Z"
  finalizers:
  - external-attacher/cinder-csi-openstack-org
  name: csi-d17b4e5166ab8791a954fd333f8a05be45e002f4668908abc61cac6674dc41fa
  resourceVersion: "512749565"
  selfLink: /apis/storage.k8s.io/v1/volumeattachments/csi-d17b4e5166ab8791a954fd333f8a05be45e002f4668908abc61cac6674dc41fa
  uid: b99ec67a-0226-4a90-8a57-f4f82fb31ca6
spec:
  attacher: cinder.csi.openstack.org
  nodeName: bcmt-ovs-dc01-worker-44
  source:
    persistentVolumeName: pvc-80e64357-8af0-4a18-8bd6-c325e94d19f6
status:
  attached: true
  attachmentMetadata:
    DevicePath: /dev/vdd
[cloud-user@worker-44 ~]$ mount | grep -i pvc-80e64357-8af0-4a18-8bd6-c325e94d19f6
/dev/vdd on /var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-80e64357-8af0-4a18-8bd6-c325e94d19f6/globalmount type ext4 (rw,relatime,seclabel,data=ordered)

**Anything else we need to know?**:

**Environment**:
- openstack-cloud-controller-manager(or other related binary) version:
- OpenStack version:
Rocky
- Others:

**Comment by zhoudayongdennis** [comment]
https://github.com/kubernetes/cloud-provider-openstack/issues/1065

checked the device path in corresponding volumeattachment, and seems no issue, so confused why reporting such kind of device related error message?

**Comment by jichenjc** [comment]
@zhoudayongdennis which version you are using ? latest or some stable releases?
I knew we had some improvement on this functions overtime, so just want to make sure your version first

**Comment by zhoudayongdennis** [comment]
@jichenjc, here was the source package we downloaded for rebuild in local.

https://github.com/kubernetes/cloud-provider-openstack/archive/v1.17.0.tar.gz

**Comment by jichenjc** [comment]
thanks for the info, as you are using 1.17 and we are already 1.22
I remember some changes done related to expand volume (need find it )but not sure it's helping you
so if ok, can you help try latest release ?

**Comment by zhoudayongdennis** [comment]
@jichenjc,

not sure whether it was env issue, so want to ask for help why reporting such kind of error message and what's potential problem for further check?

**Comment by ramineni** [comment]
@zhoudayongdennis According to this , stop pod doesn't seem to be required step, https://github.com/kubernetes/cloud-provider-openstack/blob/master/docs/cinder-csi-plugin/examples.md#volume-expansion-example.  Could you follow this and check if its the same issue being seen in that case too.

**Comment by ramineni** [comment]
closing this issue . @zhoudayongdennis feel free to reopen once you have additional info on this issue.
