### ISSUE TITLE
Test internal and external LBaaS scenarios with Octavia

### ISSUE THREAD

**Issue by dims** [kubernetes/cloud-provider-openstack#17]
_From @dims on February 7, 2018 18:59_

Test internal and external LBaaS scenarios with Octavia

_Copied from original issue: dims/openstack-cloud-controller-manager#71_

**Comment by zetaab** [comment]
@lingxiankong if you have openstack with octavia, could you test this as well?

**Comment by lingxiankong** [comment]
@zetaab I've already tested that before. The only bug I found has been fixed in v1.10.0

**Comment by zetaab** [comment]
So then I think this can be closed, if we found bugs in future -> new issue
