### ISSUE TITLE
[octavia-ingress-controller] Include CA certs into Barbican secret

### ISSUE THREAD

**Issue by hedinasr** [kubernetes/cloud-provider-openstack#1700]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
> /kind bug
> /kind feature

**What happened**:

When you enable TLS encryption on an ingress, the secret created in Barbican does not contain the CA certificates, which can produce SSL problems like this:

```
$ curl https://mydomain.com
 
curl: (60) SSL certificate problem: unable to get local issuer certificate
```

**What you expected to happen**:

The Barbican secret created by the controller should contains all the certificates found in the Kubernetes secret.

**How to reproduce it**:

Create a Let's Encrypt certificate (using `acme.sh`) and use the full chain certificate to create the Kubernetes secret.

```shell
kubectl create secret tls mydomain.com --key=mydomain.com.key --cert=fullchain.cer
```

Then use this secret to create an Ingress with TLS encryption.

```shell script
$ cat <<EOF | kubectl apply -f -                   
---                                                
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: test-octavia-ingress
  annotations:
    kubernetes.io/ingress.class: "openstack"
    octavia.ingress.kubernetes.io/internal: "false"
spec:                           
  tls:                                             
    - secretName: mydomain.com                       
  rules:                                           
    - host: mydomain.com                            
      http:                                        
        paths:                                     
        - path: /
          pathType: Exact                          
          backend:                                 
            service:                               
              name: webserver                      
              port:                                
                number: 8080                       
EOF
```

And then, 

```shell
curl https://mydomain.com
```

**Anything else we need to know?**:

We can verify that the Ingress is only returning the client certificate with the following command.

```
openssl s_client -connect mydomain.com:443 -showcerts
```

**Environment**:
- openstack-cloud-controller-manager(or other related binary) version:
- OpenStack version:
- Others:

**Comment by lingxiankong** [comment]
Hi @hedinasr, thanks for reporting this issue, could you please provide more detailed steps to help us understand how to reproduce, e.g. How you generated the certificates? How you created the Barbican secretes, etc.

**Comment by hedinasr** [comment]
I updated the issue, let me know if you want more detail.

**Comment by lingxiankong** [comment]
Thanks for the update.
