### ISSUE TITLE
[occm] Grafana dashboard

### ISSUE THREAD

**Issue by MPV** [kubernetes/cloud-provider-openstack#1701]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind feature

**What happened**:

There's great [metrics](https://github.com/kubernetes/cloud-provider-openstack/blob/master/docs/metrics.md) — would anyone be up for sharing (and/or collaborating on) a pre-made Grafana dashboard?

**What you expected to happen**:

- No references/code in this repo referring to a Grafana dashboard
- No published Grafana dashboard for OCCM available here: https://grafana.com/grafana/dashboards/?search=openstack

**How to reproduce it**:

1. Create a Grafana dashboard
2. Ship it in this repo and/or publish it to https://grafana.com/grafana/dashboards

**Comment by jichenjc** [comment]
+1 to the feature 

just for education purpose 
not sure the deliverables should be put here or to https://grafana.com/grafana/dashboards though?

**Comment by MPV** [comment]
> not sure the deliverables should be put here or to https://grafana.com/grafana/dashboards though?

Maybe both? 

To be able to improve upon what's published on Grafana.com, it's nice persisting/basing it off a repo.
