### ISSUE TITLE
[All] Check that img tag `latest` is built from `master` branch

### ISSUE THREAD

**Issue by gman0** [kubernetes/cloud-provider-openstack#1702]
/kind bug

**What happened**:

Helm charts in https://github.com/kubernetes/cloud-provider-openstack/tree/master/charts have `appVersion` set to `latest`. By default, images used in the charts use this as an image tag. Images are being pulled from https://hub.docker.com/r/k8scloudprovider .

It seems images tagged `latest` aren't built from `master` branch (at least in the case of manila-csi, found here https://github.com/kubernetes/cloud-provider-openstack/issues/1697 ).

**What you expected to happen**:

Please check `latest` is being built from `master`.

**How to reproduce it**:

**Anything else we need to know?**:

**Environment**:
- openstack-cloud-controller-manager(or other related binary) version:
- OpenStack version:
- Others:

**Comment by lingxiankong** [comment]
Confirming with openlab engineers. 

I suspect there is a background task running periodically to sync the latest image tag (which haven't updated for a long time since openlab CI had issues) from huawei container registery to cpo dockerhub,

**Comment by gman0** [comment]
@lingxiankong thank you for the info! Once more details are known, can we either update it by pointing it to `master` branch, or remove if it's not possible? It's very confusing for users when they expect to actually get the latest image and they end up with something entirely else.

**Comment by lingxiankong** [comment]
@gman0 The job has been removed. The history is, OpenLab, which is sponsored by Huawei, is not allowed to access Docker Hub in its project configuration, so we changed to use the Huawei Container Registry service and the OpenLab engineer created a periodic task to sync images to Docker Hub daily.

As most of our CI jobs have been migrated to k8s infra, we should consider building the latest images in the job directly.

**Comment by gman0** [comment]
That sounds good, thanks.

**Comment by ramineni** [comment]
> As most of our CI jobs have been migrated to k8s infra, we should consider building the latest images in the job directly.

@lingxiankong Agree. We used to have inside e2e-conformance job, is it required to do that? I suppose we could have separate periodic task to sync the images . wdyt?

**Comment by lingxiankong** [comment]
> @lingxiankong Agree. We used to have inside e2e-conformance job, is it required to do that? I suppose we could have separate periodic task to sync the images . wdyt?

No, it's not required and you are right, we could definitely create another CI job to build latest image tag daily. Could you please help to create an issue and assign to me?

**Comment by ramineni** [comment]
> > @lingxiankong Agree. We used to have inside e2e-conformance job, is it required to do that? I suppose we could have separate periodic task to sync the images . wdyt?
> 
> No, it's not required and you are right, we could definitely create another CI job to build latest image tag daily. Could you please help to create an issue and assign to me?

@lingxiankong Thanks. Issue: https://github.com/kubernetes/cloud-provider-openstack/issues/1707
