### ISSUE TITLE
[occm] No way to specify internal network UUID in configuration

### ISSUE THREAD

**Issue by kralicky** [kubernetes/cloud-provider-openstack#1712]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
> /kind bug

/kind feature

**What happened**:
if `internal-network-name` is set to the internal network's UUID instead of its actual name, the CCM will not assign an InternalIP to nodes which have a floating IP attached.

**What you expected to happen**:
There is no documented alternative key named `internal-network-id` or similar, but since Openstack APIs usually always accept name or UUID interchangeably (UUIDs are preferred and names will do best-effort lookup), I expected the UUID to work the same way. I did not notice any related errors at first, because they were logged as info messages at a high verbosity level. [This error](https://github.com/kubernetes/cloud-provider-openstack/blob/9b8de65448e7872ac4e83c7342e498127155253b/pkg/openstack/instances.go#L542) clued me in to the issue, and replacing the UUID with the name fixed the problem.

**How to reproduce it**:
In cloud.conf:
```
[Networking]
internal-network-name = <internal network's UUID>
```

**Anything else we need to know?**:
I would be happy to contribute and add this feature! 

**Environment**:
- openstack-cloud-controller-manager(or other related binary) version: latest/master
- OpenStack version: Xena
- Others:

**Comment by lingxiankong** [comment]
> I would be happy to contribute and add this feature

Thanks for providing help :-) We could definitely support network ID, but I'd assume that may bring more changes than expected.
