### ISSUE TITLE
[octavia-ingress-controller] Ingress for same hostname results in multiple load balancer instances and different IPs to access them

### ISSUE THREAD

**Issue by kleini** [kubernetes/cloud-provider-openstack#1713]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
/kind bug
> /kind feature

**What happened**:
The octavia-ingress-controller always creates a separate load balancer for every ingress. It is not possible to have different URL paths for the same hostname configured in different ingresses.

**What you expected to happen**:
octavia-ingress-controller matches same hostnames and creates the URL paths on the same load balancer.

**How to reproduce it**:
Create two ingresses with same hostname but different URL path.

**Anything else we need to know?**:

**Environment**:
- openstack-cloud-controller-manager(or other related binary) version: v1.20.0
- OpenStack version: Victoria
- Others: v1.21.0 for kube_tag, octavia_ingress_controller_tag

**Comment by kleini** [comment]
❯ kubectl get ingresses
    NAME                      CLASS    HOSTS         ADDRESS       PORTS   AGE
    testo-octavia-ingress-1   <none>   foo.bar.com   10.50.2.181   80      3m9s
    testo-octavia-ingress-2   <none>   foo.bar.com   10.50.3.185   80      56s
    
    ❯ openstack loadbalancer list
    +--------------------------------------+---------------------------------------------------------------------------------+----------------------------------+----------------+---------------------+------------------+----------+
    | id                                   | name                                                                            | project_id                       | vip_address    | provisioning_status | operating_status | provider |
    +--------------------------------------+---------------------------------------------------------------------------------+----------------------------------+----------------+---------------------+------------------+----------+
    | 41228cde-6692-4710-a98c-e14b82e01c8c | kube_ingress_3adc3990-ef0a-41e0-9627-dd17ac167e5d_testo_testo-octavia-ingress-1 | 0da28f0c33fe41038c9e418e2f0050bd | 192.168.71.48  | ACTIVE              | ONLINE           | octavia  |
    | 3af1610c-d47a-46a9-90ad-97744f1228d7 | kube_ingress_3adc3990-ef0a-41e0-9627-dd17ac167e5d_testo_testo-octavia-ingress-2 | 0da28f0c33fe41038c9e418e2f0050bd | 192.168.71.89  | ACTIVE              | ONLINE           | octavia  |
    +--------------------------------------+---------------------------------------------------------------------------------+----------------------------------+----------------+---------------------+------------------+----------+

**Comment by lingxiankong** [comment]
> It is not possible to have different URL paths for the same hostname configured in different ingresses.

I am sure I understand this, could you please give us an example and describe the issue? From your paste, I can see there are 2 Ingresses created and 2 corresponding load balancers, and this is the expected behavior.

**Comment by kleini** [comment]
An example would be the following two ingress definitions:

    apiVersion: networking.k8s.io/v1
    kind: Ingress
    metadata:
    name: testo-octavia-ingress-1
    annotations:
        kubernetes.io/ingress.class: "openstack"
        octavia.ingress.kubernetes.io/internal: "false"
    spec:
    rules:
    - host: foo.bar.com
        http:
        paths:
        - path: /hostname-1
            pathType: Prefix
            backend:
            service:
                name: hostname-echo-svc-1
                port:
                number: 8080

and

    apiVersion: networking.k8s.io/v1
    kind: Ingress
    metadata:
    name: testo-octavia-ingress-2
    annotations:
        kubernetes.io/ingress.class: "openstack"
        octavia.ingress.kubernetes.io/internal: "false"
    spec:
    rules:
    - host: foo.bar.com
        http:
        paths:
        - path: /hostname-2
            pathType: Prefix
            backend:
            service:
                name: hostname-echo-svc-2
                port:
                number: 8080

As both have the same hostname, I would like to have both of them to be realized in the same octavia load balancer, and they should be therefore reachable under the same IP.

It would be furthermore very helpful, if even different hostnames could be realized in the same load balancer if it is the HTTP protocol. The client will tell, through the Host header, which hostname they want to request. This would then be the vhost integration.

**Comment by jichenjc** [comment]
then why not rewrite the ingress to avoid such ? looks like it's doable 
not sure how to correctly distinguish the different ingress to same LB from doc below ..
https://github.com/kubernetes/cloud-provider-openstack/blob/master/docs/octavia-ingress-controller/using-octavia-ingress-controller.md

**Comment by kleini** [comment]
How should I avoid different services behind different paths? That is the nature of micro services to have a lot of them, each one taking over a part of your whole web application. I am not certain, how to rewrite the ingress in that way? Each application is deployed on its own, managed by its own team.
And furthermore, the vhost requirement still remains. If you want to display other web content safely within your web application, you require other domain names to utilize browser sandbox separations.

**Comment by jichenjc** [comment]
um... looks like https://github.com/kubernetes/cloud-provider-openstack/blob/master/docs/openstack-cloud-controller-manager/expose-applications-using-loadbalancer-type-service.md#sharing-load-balancer-with-multiple-services is a similar answer to your question 

might need same pattern to think about how to do this

**Comment by kleini** [comment]
@jichenjc that sounds good. Will try that and post my experiences.

**Comment by jichenjc** [comment]
/reopen 

thanks for the quick answer, I think that info is trying to provide you a pattern about services usage but it doesn't cover Ingress use case, I only want to check with you whether that LB (directly with service) is an acceptable way then think about how we can perform on ingress side... 
so reopen this for additional discussion

**Comment by lingxiankong** [comment]
@kleini Thanks for the feedback. Yes, this is a valid feature request. Just as @jichenjc mentioned, we have already implemented a similar feature for openstack-cloud-controller-manager, but things will be a little bit different in the ingress controller.

We definitely need someone's bandwidth to think about the design and bring it up to the team for discussion, given this is a big feature, ideally we need a draft design to start with.

**Comment by ReggieCarey** [comment]
There is some confusion.  In the documentation it is written:

"The octavia-ingress-controller could solve all the above problems in the OpenStack environment by creating a single load balancer for multiple [NodePort](https://kubernetes.io/docs/concepts/services-networking/service/#type-nodeport) type services in an Ingress."

This says to me that a single LB will be created and used by multiple backends.  That does not appear to be what's happening.

**Comment by lingxiankong** [comment]
> There is some confusion. In the documentation it is written:
> 
> "The octavia-ingress-controller could solve all the above problems in the OpenStack environment by creating a single load balancer for multiple [NodePort](https://kubernetes.io/docs/concepts/services-networking/service/#type-nodeport) type services in an Ingress."
> 
> This says to me that a single LB will be created and used by multiple backends. That does not appear to be what's happening.

Please read the sentence again and do some testing, the octavia-ingress-controller does appear to be what is said here.

**Comment by kleini** [comment]
I would like to do so. But everything visible from documentation is a loadbalancer for a service. And if you have multiple services in your kubernetes, you will have a lot of loadbalancers.
