### ISSUE TITLE
[manila-csi-plugin] Context deadline exceeded when creating volumes

### ISSUE THREAD

**Issue by GlassOfWhiskey** [kubernetes/cloud-provider-openstack#1714]
/kind feature

The default timeout (15s) for external-provisioner and external-snapshotter pods is way too short for the majority of real scenarios. This causes the volume creation operation to get stuck in a retry loop for a long time, returning DeadlineExceeded errors, until it manages to complete the volume creation under 15s.

The suggestion is: increase the timeout parameter for provisioner and snapshotter sidecar containers to 3 minutes, as in the `cinder-csi-plugin` manifests. This would be compatible OOTB with the majority of OpenStack architectures

**Comment by gman0** [comment]
+1, I agree. The next step (or as a part of this issue) would be to get rid of the internal check-and-wait loops that manila-csi currently has, and only rely on external-provisioner/snapshotter's retries.

**Comment by jacksgt** [comment]
It seems to me like these timeouts are not even configurable, is that correct?

/reopen
