### ISSUE TITLE
Openstack cloud controller manager sends external DNS queries to resolve openstack at an interval of 5minutes

### ISSUE THREAD

**Issue by amshankaran** [kubernetes/cloud-provider-openstack#1718]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
> /kind bug
> /kind feature

**What happened**:
OCCM sends 2 external DNS queries to resolve openstack at an interval of 5 minutes.
number of queries generated = 2 * number of nodes in the cluster
(in my cluster with 6 nodes 24 queries, 12 A queries 12 AAAA queries) 

**What you expected to happen**:
Why these DNS queries were generated? I don't see any parameter defines 5 minutes except "--node-status-update-frequency". Are these queries generated to get the node status from openstack.
I could see the first query itself getting resolved  (response received), then why do we need the second query? Is there any parameter defines the number of queries? 

**How to reproduce it**:

**Anything else we need to know?**:

**Environment**:
- openstack-cloud-controller-manager(or other related binary) version: v1.21.0
- OpenStack version:
- Others:

**Comment by jichenjc** [comment]
@lingxiankong do you happen to know the answer?

**Comment by lingxiankong** [comment]
Could you please provide some logs?

**Comment by amshankaran** [comment]
![dns packet capture](https://user-images.githubusercontent.com/21239791/146134812-c29b6278-e483-4a74-9921-55d7b3783b00.jpg)
Please find the attached dns packet capture. I don't have logs now, I'll collect and share the same for the openstack-cloud-controller-manager pods. If any other logs requires do let me know

**Comment by amshankaran** [comment]
[openstack-cloud-controller-manager-t9dr8-pod.log](https://github.com/kubernetes/cloud-provider-openstack/files/7725030/openstack-cloud-controller-manager-t9dr8-pod.log)

**Comment by amshankaran** [comment]
Hi Is there any findings on this ticket?

**Comment by lingxiankong** [comment]
Hi @amshankaran thanks for providing the logs. From the log, I assume the domain name in the DNS queries is your OpenStack Keystone service endpoint. The k8s cloud controller manager has a component to periodically synchronize the node status (especially the node addresses) from OpenStack, the default interval is 5m, as you can see from the log, `--node-status-update-frequency="5m0s"`. To verify, you can change `--v=4` in OCCM container command to see the API interactions.

**Comment by amshankaran** [comment]
Hi @lingxiankong, thanks for your clarification. just one more information required, I could see the first query itself getting resolved (response received), then why do we need the second query? Is there any parameter defines the number of queries (as 2)?

**Comment by lingxiankong** [comment]
What do you mean by `the second query`? Have you checked the debug log of openstack-cloud-controller-manager?

**Comment by amshankaran** [comment]
[log_v_6.txt](https://github.com/kubernetes/cloud-provider-openstack/files/7860343/log_v_6.txt)
Hi @lingxiankong, As I mentioned in the  bug description, i could see 24 DNS queries. (My cluster has 6 nodes), 12 A queries 12 AAAA queries. So 2 A queries and 2 AAAA queries for one node. (check the packet capture image attached)
Please find the attached log. I could see two GET requests. One for the instance another one for the os_interface. Is this as per design? Will it create two DNS request?

**Comment by lingxiankong** [comment]
> One for the instance another one for the os_interface

Yes.

> Will it create two DNS request?

AFAIK, this is the default behavior of dual-protocol DNS queries.

**Comment by lingxiankong** [comment]
Close this issue as per my reply.

/close
