### ISSUE TITLE
[octavia-ingress-controller][OCCM] consider support of Gateway API

### ISSUE THREAD

**Issue by jichenjc** [kubernetes/cloud-provider-openstack#1730]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
> /kind bug
/kind feature

**What happened**:
https://gateway-api.sigs.k8s.io/ has been there for a while and it's supposed to be replace ingress object with CRDs defined, we should adopt this feature and consider enhance in various places in order to make CPO able to support it..

**What you expected to happen**:

**How to reproduce it**:

**Anything else we need to know?**:

**Environment**:
- openstack-cloud-controller-manager(or other related binary) version:
- OpenStack version:
- Others:

**Comment by jichenjc** [comment]
the Gateway API already enter into Beta ...

**Comment by iverly** [comment]
Hello there,

Gateway API has been in GA since October 31, 2023.

Is there any news regarding Gateway API support?

**Comment by dulek** [comment]
I'll be frank here, I don't think CPO currently has resources available to develop a new, complicated feature. We would gladly accept and help with contributions adding it, but I don't think developing Gateway API is on a plate of anyone at the moment.
