### ISSUE TITLE
[manila-csi-plugin] question on manila csi pluin

### ISSUE THREAD

**Issue by jichenjc** [kubernetes/cloud-provider-openstack#1731]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
> /kind bug
> /kind feature

**What happened**:

2 questions I got from mail directly , @gman0 maybe you can be helpful to this ?

```
Recently I tested the deployment of manila-csi-plugin by following some of your manifests, however there are some points not so clear to me.
1. How to set the FWD-NODEPLUGIN path/dir?
I only see at my end there are two dirs with the csi.sock file, i.e., /var/lib/kubelet/plugins/manila.csi.openstack.org and /var/lib/kubelet/plugins/cinder.csi.openstack.org

2. To use a manila share in a container, don't we need to install some ceph client packages at first, such as ceph-common, libcephfs, ceph-fuse, etc.?
I searched the web including those implementations at CERN but nowhere mentions we need to do that. I doubt if the container can mount the share/volume without those client tools. 
```

**What you expected to happen**:

**How to reproduce it**:

**Anything else we need to know?**:

**Environment**:
- openstack-cloud-controller-manager(or other related binary) version:
- OpenStack version:
- Others:

**Comment by gman0** [comment]
Hi @jichenjc, the docs still seem to be a bit unclear about deployment and need to be improved...

For CephFS with Manila, users are expected to deploy manila-csi-plugin _and_ [ceph-csi-cephfs](https://github.com/ceph/ceph-csi).

> 1. How to set the FWD-NODEPLUGIN path/dir?

This path then needs to be set to ceph-csi-cephfs Node Plugin socket.

> 2. To use a manila share in a container, don't we need to install some ceph client packages at first, such as ceph-common, libcephfs, ceph-fuse, etc.?

No, all these packages are available from within ceph-csi-cephfs. When manila-csi-plugin receives a request to mount a volume, it forwards this request to ceph-csi-cephfs node plugin, which is then able to handle all the CephFS-specific stuff.

Hopefully this makes it clearer to the user.

**Comment by jichenjc** [comment]
@gman0 thanks :)

I replied to mail to him and share the link along with the slack info 
so hopefully this can be helpful 

will close if he agree or we can close in a few days

**Comment by ermingpei** [comment]
Thank @jichenjc.  @gman0 has answered my above questions that are very helpful. Please close this ticket.

**Comment by jichenjc** [comment]
thanks for both of your help~
