### ISSUE TITLE
[cinder-csi-plugin] topology-aware provisioning broken when compute and volume AZs are distinct

### ISSUE THREAD

**Issue by gman0** [kubernetes/cloud-provider-openstack#1735]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:

* If `availability` is not set in storage class parameters, cinder-csi will use a zone supplied by the `CreateVolumeRequest.accessibility_requirements` as a volume AZ, if present:
   https://github.com/kubernetes/cloud-provider-openstack/blob/d46aa87534042ad1e26b812d1ef1aa140317a25e/pkg/csi/cinder/controllerserver.go#L73-L84
* If storage class doesn't specify any `allowedTopologies`, external-provisioner populates `accessibility_requirements` with aggregated cluster (compute) topology by default (see [--immediate-topology](https://github.com/kubernetes-csi/external-provisioner#other-recognized-arguments), and the [effect it has](https://github.com/kubernetes-csi/external-provisioner#topology-support)). That makes the ` != nil` condition above succeed, setting `volAvailability` to some compute AZ.
* If volume and compute AZs are distinct, cinder-csi will always make wrong choice when selection an AZ from `accessibility_requirements`, resulting in a volume provisioning error.

**What you expected to happen**:

* Helm chart could provide a switch to disable topology-aware provisioning altogether, so that `CreateVolumeRequest.accessibility_requirements` would never be populated, or
* Helm chart could provide a switch to run external-provisioner with `--immediate-topology=false`, or
* cinder-csi could check that if no `availability` volume parameter is supplied, and `ignore-volume-az=true` is set in cloud config, it should not consider zones from `accessibility_requirements` as volume AZs.

**How to reproduce it**:

Provision a volume in a cloud with distinct volume and compute AZs.

**Anything else we need to know?**:

**Environment**:
- openstack-cloud-controller-manager(or other related binary) version: v1.22.0, external-provisioner v2.2.0
- OpenStack version:
- Others:

**Comment by jichenjc** [comment]
>>>cinder-csi could check that if no availability volume parameter is supplied, and ignore-volume-az=true is set in cloud config, it should not consider zones from accessibility_requirements as volume AZs.

for this option, actually we are having this check here and use 
https://github.com/kubernetes/cloud-provider-openstack/blob/master/pkg/csi/cinder/controllerserver.go#L87

to set the param then 

https://github.com/kubernetes/cloud-provider-openstack/blob/master/pkg/csi/cinder/controllerserver.go#L696

to set the AZ info

so @gman0 is this your read code found issue or get from test result? Thanks

**Comment by gman0** [comment]
@jichenjc yes we have `ignore-volume-az=true` in our cloud config, and the creation fails with `Failed to run task cinder.scheduler.flows.create_volume.ScheduleCreateVolumeTask;volume:create: No valid backend was found. No weighed backends available`.

As far as I can tell, `ignoreVolumeAZ` is only used when forming the list of compute zones in which the volume shall be accessible:

https://github.com/kubernetes/cloud-provider-openstack/blob/d46aa87534042ad1e26b812d1ef1aa140317a25e/pkg/csi/cinder/controllerserver.go#L693-L706

You can ignore volume zones when specifying compute zones, but there is no way to ignore compute zones when setting `availability` parameter of the volume. I provided some options how this could be dealt with in my original post.

**Comment by jichenjc** [comment]
@gman0 you are right, I read the wrong code .. sorry about the confusion, will submit a PR for this

**Comment by gman0** [comment]
> Helm chart could provide a switch to disable topology-aware provisioning altogether, so that CreateVolumeRequest.accessibility_requirements would never be populated, or

There already is: `csi.provisioner.topology`.

Disabling it solves our issues for the time being, so I'm closing this issue. Thanks for the efforts and sorry for the noise.
