### ISSUE TITLE
[occm] Disable openlab jobs and create new jobs in GCP infra

### ISSUE THREAD

**Issue by lingxiankong** [kubernetes/cloud-provider-openstack#1752]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind feature

**What happened**:
The reason we keep the occm openlab jobs is to make sure we build new jobs to replace them, however, keeping those jobs doesn't help anything and only cause confusion for contributors.

Let's remove all those openlab jobs and using this issue to track the job migration task.

**What you expected to happen**:

**How to reproduce it**:

**Anything else we need to know?**:

**Environment**:
- openstack-cloud-controller-manager(or other related binary) version:
- OpenStack version:
- Others:

**Comment by ramineni** [comment]
+1, we can start by removing zuul jobs in the repo, causing lot of failures on PR creating confusion for new contributors.

**Comment by ramineni** [comment]
@lingxiankong we already have tracking issue open here , https://github.com/kubernetes/cloud-provider-openstack/issues/1613 ,
as openlab jobs are removed now, we can close this issue?

**Comment by lingxiankong** [comment]
Yes, thanks for finding that one. Let's close this and use #1613 to track the migration.
