### ISSUE TITLE
[cinder-csi-plugin] Can't attach multiattach volume to two different worker nodes

### ISSUE THREAD

**Issue by lianzxu** [kubernetes/cloud-provider-openstack#1778]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:

I created a storage class with openstack volume type "multiattach". I also created two pods on two different worker nodes by node-selector. The volume is meant to be mounted to both pods. But this volume couldn't attach to the second worker node. PV and PVC were created without problem.

Here are the errors when pods were being created:

  Warning  FailedAttachVolume  89s (x19 over 32m)  attachdetach-controller  AttachVolume.Attach failed for volume "ccd-1-ddf2467e-6d3c-43f7-b881-9e00e30dfc68" : rpc error: code = Internal desc = [ControllerPublishVolume] Attach Volume failed with error failed to attach bfb9d95c-8233-4a53-8753-3aaf6dab798f volume to b3a48ced-41f9-4779-af81-443c0f51693e compute: **volume isn't in available state so we can not attach it**. status: bfb9d95c-8233-4a53-8753-3aaf6dab798f %!!(MISSING)!(MISSING)(EXTRA string=in-use)

After I manually attached the volume to the second node on openstack, the pod was able to created successfully.

openstack --os-compute-api-version 2.60 server add volume b3a48ced-41f9-4779-af81-443c0f51693e bfb9d95c-8233-4a53-8753-3aaf6dab798f

**What you expected to happen**:

Multiattach volume is attached to both worker nodes with k8s manifest.

**How to reproduce it**:

**Create storage class:**

apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: network-block1
parameters:
  availability: nova
  type: "multiattach"
  multiattach: "True"
allowVolumeExpansion: true
provisioner: cinder.csi.openstack.org
reclaimPolicy: Delete
volumeBindingMode: Immediate

**Create PVC:**

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: dynamicpvc
spec:
  storageClassName: network-block1
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi

**Create two pods:**

apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: liantest1
  name: liantest1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: liantest1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: liantest1
    spec:
      volumes:
      - name: pvctest
        persistentVolumeClaim:
          claimName: dynamicpvc
      containers:
      - image: nginx
        name: nginx
        resources: {}
        volumeMounts:
        - name: pvctest
          mountPath: /liantestpath
      nodeSelector:
        rad: test

apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: liantest2
  name: liantest2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: liantest2
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: liantest2
    spec:
      volumes:
      - name: pvctest
        persistentVolumeClaim:
          claimName: dynamicpvc
      containers:
      - image: nginx
        name: nginx
        resources: {}
        volumeMounts:
        - name: pvctest
          mountPath: /liantestpath
      nodeSelector:
        rad: workflow

**Anything else we need to know?**:

Did I miss anything in my manifests? 

**Environment**:
- openstack-cloud-controller-manager(or other related binary) version: openstack-cloud-controller-manager:v1.21.0-6-513da3aa
- OpenStack version: openstack 3.18.0
- Kubernetes:
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.1", GitCommit:"841a4f4f3d4528aa284171074e00503faea18496", GitTreeState:"clean", BuildDate:"2021-08-31T06:59:53Z", GoVersion:"go1.16.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.1", GitCommit:"841a4f4f3d4528aa284171074e00503faea18496", GitTreeState:"clean", BuildDate:"2021-08-31T06:52:44Z", GoVersion:"go1.16.4", Compiler:"gc", Platform:"linux/amd64"}

**Comment by ramineni** [comment]
@lianzxu could you share the o/p of  `openstack volume type list` and volume show of bfb9d95c-8233-4a53-8753-3aaf6dab798f

**Comment by lianzxu** [comment]
**openstack volume type list**
+--------------------------------------+-------------+-----------+
| ID                                   | Name        | Is Public |
+--------------------------------------+-------------+-----------+
| 64e1b605-1d59-4fa7-afbb-3cb9baf0d0c6 | multiattach | True      |
+--------------------------------------+-------------+-----------+



 **openstack volume show bfb9d95c-8233-4a53-8753-3aaf6dab798f**
+--------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Field                          | Value                                                                                                                                                                                                                                                                                                               |
+--------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| attachments                    | [{'id': 'bfb9d95c-8233-4a53-8753-3aaf6dab798f', 'attachment_id': '10d2c388-002b-40bb-8821-aecf43536dfc', 'volume_id': 'bfb9d95c-8233-4a53-8753-3aaf6dab798f', 'server_id': 'b3a48ced-41f9-4779-af81-443c0f51693e', 'host_name': '*********', 'device': '/dev/vdg', 'attached_at': '2022-02-02T14:20:02.000000'}] |
| availability_zone              | nova                                                                                                                                                                                                                                                                                                                |
| bootable                       | false                                                                                                                                                                                                                                                                                                               |
| consistencygroup_id            | None                                                                                                                                                                                                                                                                                                                |
| created_at                     | 2022-02-01T18:22:39.000000                                                                                                                                                                                                                                                                                          |
| description                    | Created by OpenStack Cinder CSI driver                                                                                                                                                                                                                                                                              |
| encrypted                      | False                                                                                                                                                                                                                                                                                                               |
| id                             | bfb9d95c-8233-4a53-8753-3aaf6dab798f                                                                                                                                                                                                                                                                                |
| migration_status               | None                                                                                                                                                                                                                                                                                                                |
| multiattach                    | True                                                                                                                                                                                                                                                                                                                |
| name                           | ccd-1-ddf2467e-6d3c-43f7-b881-9e00e30dfc68                                                                                                                                                                                                                                                                          |
| os-vol-host-attr:host          | **********@3par#Sandlot                                                                                                                                                                                                                                                                                           |
| os-vol-mig-status-attr:migstat | None                                                                                                                                                                                                                                                                                                                |
| os-vol-mig-status-attr:name_id | None                                                                                                                                                                                                                                                                                                                |
| os-vol-tenant-attr:tenant_id   | 7176a19a24cf4602b7b0c19bb9ee653f                                                                                                                                                                                                                                                                                    |
| properties                     | cinder.csi.openstack.org/cluster='kubernetes'                                                                                                                                                                                                                                                                       |
| replication_status             | None                                                                                                                                                                                                                                                                                                                |
| size                           | 1                                                                                                                                                                                                                                                                                                                   |
| snapshot_id                    | None                                                                                                                                                                                                                                                                                                                |
| source_volid                   | None                                                                                                                                                                                                                                                                                                                |
| status                         | in-use                                                                                                                                                                                                                                                                                                              |
| type                           | multiattach                                                                                                                                                                                                                                                                                                         |
| updated_at                     | 2022-02-02T14:20:10.000000                                                                                                                                                                                                                                                                                          |
| user_id                        | 06fc8f67adb64b678abb3d143e17b617                                                                                                                                                                                                                                                                                    |

**Comment by jichenjc** [comment]
@lianzxu I didn't see your storageclass definition
can you confirm you followed https://github.com/kubernetes/cloud-provider-openstack/blob/master/docs/cinder-csi-plugin/features.md#multi-attach-volumes ?

**Comment by jichenjc** [comment]
@lianzxu what's the version of openstack ? `OpenStack version: openstack 3.18.0` seems weird to me 
the reason for this ask is to search `volume isn't in available state so we can not attach it` comes from

as you mentioned, run `openstack --os-compute-api-version 2.60 server add volume b3a48ced-41f9-4779-af81-443c0f51693e bfb9d95c-8233-4a53-8753-3aaf6dab798f` again can attach the volume makes me guess that first attach didn't go through the microversion 2.60 which we added here:

https://github.com/kubernetes/cloud-provider-openstack/blob/master/pkg/csi/cinder/openstack/openstack_volumes.go#L192
otherwise it should be same to the API you used unless we are facing a race ..

so can you help confirm the openstack version you are using Stein/Train etc version and maybe some error logs in nova/cinder side for the attachment during the 2nd attach then it might be helpful

**Comment by ramineni** [comment]
@jichenjc  +1 . @lianzxu the error seems to be come from openstack itself

**Comment by lianzxu** [comment]
@jichenjc 

I am sorry Openstack version is 19.0.3. 

I am new to Openstack. I searched online about the cinder logs and nova logs. On storage server at /var/log/cinder I could find cinder-volume.log but somehow not cinder-api.log. Do you have any idea where I should look? cinder-volume.log does not provide much information for debugging. 

Thank you for your help.

**Comment by jichenjc** [comment]
>>> somehow not cinder-api.log

I assume you are not using all-in-one (devstack) ,instead, some openstack distro? if so 
usually cinder-api is at controller node, and you should be able to find at /var/log/cinder/*.log 
@lianzxu

**Comment by jichenjc** [comment]
@lianzxu seems cinder-api only return 200 which doesn't help (all success)

as mentioned in previous note I want to find `volume isn't in available state so we can not attach it` comes from , and I am thinking it might comes from the nova log which should give some info, I can't find this error in `19.0.0` version by searching `so we can` but no lucky not find it 

so are you able to find this error in nova related logs? Thanks

**Comment by lianzxu** [comment]
@ramineni 

I couldn't find any useful info on nova either. We were looking from Openstack end. Maybe the ticket can be closed. Thanks.

**Comment by jichenjc** [comment]
/close

please reopen if you have further findings.. thanks
