### ISSUE TITLE
[occm] Document which information is exposed by "cloud-node" controller

### ISSUE THREAD

**Issue by jacksgt** [kubernetes/cloud-provider-openstack#1779]
/kind feature

The Openstack Cloud Controller Manager (occm) allows enabling an integration with the Openstack VMs through the "cloud-node" controller.
Unfortunately, it is not documented anywhere which information exactly will be exposed by the controller and where it will be exposed (i.e. in which annotations of the `node` resource).
I think it would be really helpful to have this documentation.

**Comment by jichenjc** [comment]
>>>allows enabling an integration with the Openstack VMs through the "cloud-node" controller.

@jacksgt not sure I am follow this , just for education purpose, could you please point some where of the code or give some example on the plan / requirement here? thanks

**Comment by jacksgt** [comment]
Hello @jichenjc , thanks for your question.
I would like to have some documentation what the "cloud-node" controller of "openstack-cloud-controller-manager" does.
There is [extensive documentation](https://github.com/kubernetes/cloud-provider-openstack/blob/master/docs/openstack-cloud-controller-manager/using-openstack-cloud-controller-manager.md) how to use the "service" controller, but it is not clear what I should expected when I run `occm --controllers=cloud-node` (the same applies for the "cloud-node-lifecycle" controller).

In the end, the documentation should state something like:
* the cloud-node controller will add the annotation `example.com/example` to all your nodes
* the cloud-node controller will set the `.status.foo.bar` field on all nodes.
* ...

**Comment by jichenjc** [comment]
ok, it depends on your purpose of generic cloud provider or OCCM 

https://github.com/kubernetes/cloud-provider/blob/master/app/controllermanager.go#L393
is the place where cloud-node is defined so I think if you want to update generic things,
that repo might be better places

if it's for OCCM only, we might only want to focus on OCCM unique updates of annotation and fields
the more doc the health of the repo so please let us know what stuffs you want to add

**Comment by lingxiankong** [comment]
The node controller is not specific to openstack-cloud-controller-manager, it's a common thing for all the cloud controllers.

/close
