### ISSUE TITLE
[occm] the load balancer listener pool is inconsistent updated

### ISSUE THREAD

**Issue by FlorinPeter** [kubernetes/cloud-provider-openstack#1795]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
/kind bug
> /kind feature

**What happened**:
We observed on a k8s service with 4 ports that a load balancer listener pool were updated on every reconcile loop.

**What you expected to happen**:
That the pool is not updated if the current member are unchanged

**How to reproduce it**:
Create a service with 4 exposed node ports

**Anything else we need to know?**:
PR for this issue already opened https://github.com/kubernetes/cloud-provider-openstack/pull/1793

**Environment**:
- openstack-cloud-controller-manager version: 1.23

**Comment by FlorinPeter** [comment]
closed as the issue was on OpenStack API side

**Comment by databus23** [comment]
We are also experiencing this issue. I'm not convinced this is an openstack API problem. We had to backport the PR to 1.23 to get a handle in serious production outages with ccm 1.23
