### ISSUE TITLE
[occm] Node ExternalIP not being added

### ISSUE THREAD

**Issue by vowywowy** [kubernetes/cloud-provider-openstack#1818]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug

**What happened**:
Attempting to switch from in-tree cloud provider to occm. The nodes don't have external IP's as revealed with `kubectl get nodes -o wide`:
```
NAME                             STATUS   ROLES                      AGE   VERSION   INTERNAL-IP   EXTERNAL-IP   OS-IMAGE             KERNEL-VERSION     CONTAINER-RUNTIME
tf-rancher-cluster-demo-test-1   Ready    controlplane,etcd,worker   58m   v1.21.5   10.0.0.9      <none>        Ubuntu 18.04.6 LTS   5.4.0-91-generic   docker://20.10.11
tf-rancher-cluster-demo-test-2   Ready    controlplane,etcd,worker   27d   v1.21.5   10.0.0.13     <none>        Ubuntu 18.04.6 LTS   5.4.0-91-generic   docker://20.10.11
tf-rancher-cluster-demo-test-3   Ready    controlplane,etcd,worker   27d   v1.21.5   10.0.0.18     <none>        Ubuntu 18.04.6 LTS   5.4.0-91-generic   docker://20.10.11
```

The name of the single floating network is specified under `public-network-name` in the `cloud.conf` and when logging verbosity is increase to `--v=4`, occm is detecting the floating IPs (relevant `instances.go` entries):
```
...
I0324 19:55:31.297534       1 instances.go:72] openstack.Instances() called
I0324 19:55:31.297569       1 instances.go:131] NodeAddressesByProviderID () called
I0324 19:55:31.297898       1 instances.go:116] NodeAddresses(tf-rancher-cluster-demo-test-1) called
I0324 19:55:31.633329       1 instances.go:123] NodeAddresses(tf-rancher-cluster-demo-test-1) => [{InternalIP 10.0.0.9} {ExternalIP 10.102.2.147}]
...
```

**What you expected to happen**:
The actual node resources have external IPs

**How to reproduce it**:
I don't believe I'm doing anything out of the ordinary. This is a plain install from scratch with no other workloads.

**Anything else we need to know?**:
N/A

**Environment**:
- openstack-cloud-controller-manager(or other related binary) version: 1.23 (using the chart)
- OpenStack version: Queens
- Others: k8s, os, and kernel versions are in the above snippets

**Comment by jichenjc** [comment]
do you have floating ip set and which version you are using ? 

```
$ kubectl get nodes -o wide
NAME   STATUS   ROLES                  AGE   VERSION   INTERNAL-IP   EXTERNAL-IP    OS-IMAGE             KERNEL-VERSION       CONTAINER-RUNTIME
m2     Ready    control-plane,master   16d   v1.23.4   10.0.0.40     172.24.4.241   Ubuntu 18.04.6 LTS   4.15.0-167-generic   docker://20.10.12

# nova list 

`...
| f40cf042-3788-414d-8f06-efbd58e09da5 | m2   | ACTIVE | -          | Running     | private=10.0.0.40, fd81:d720:65dd:0:f816:3eff:fe85:4f98, 172.24.4.241       
...

$ kubectl get pod openstack-cloud-controller-manager-5n8fg -n kube-system -o yaml | grep image
    image: docker.io/k8scloudprovider/openstack-cloud-controller-manager:latest
```

**Comment by vowywowy** [comment]
I was on `1.23`, but I just switched to `latest` and there is no change.

Yes, the nodes have floating IPs:
```
+--------------------------------------+--------------------------------+--------+------------+-------------+----------------------------------------------------------+
| ID                                   | Name                           | Status | Task State | Power State | Networks                                                 |
+--------------------------------------+--------------------------------+--------+------------+-------------+----------------------------------------------------------+
| e5817584-7fc5-4900-a1ff-d6c7f01227e9 | tf-rancher-cluster-demo-test-1 | ACTIVE | -          | Running     | tf-rancher-cluster-demo-test-net=10.0.0.9, 10.102.2.147  |
| 816972e2-3b6e-4b9f-b69e-ec834573db2f | tf-rancher-cluster-demo-test-2 | ACTIVE | -          | Running     | tf-rancher-cluster-demo-test-net=10.0.0.13, 10.102.2.100 |
| 1815fbe4-5a8e-4a78-a256-b022c3435e66 | tf-rancher-cluster-demo-test-3 | ACTIVE | -          | Running     | tf-rancher-cluster-demo-test-net=10.0.0.18, 10.102.2.84  |
+----------------------------------------------------------------------------------------------------------------------------------------------------------------------+
```
And in horizon:
![image](https://user-images.githubusercontent.com/14022915/160126090-606cf653-41e5-463b-8b0e-9bdc6c13863e.png)

**Comment by jichenjc** [comment]
um... I think there might be some pre-condition not satisfied

can you enable v==5 first then check whether there are any suspected logs might worth a look?

https://github.com/kubernetes/cloud-provider/blob/master/controllers/node/node_controller.go#L323
is the code that set the node address, there are multiple checks and I guess some might break the logic in updating the ip...

**Comment by jichenjc** [comment]
@vowywowy so, can you help paste full log of OCCM with --v = 4 so it might contains more info? Thanks

**Comment by vowywowy** [comment]
Thanks for these messages! They ended up sending me down a rabbit hole to the solution.
As you can probably guess based on the naming, everything here is terraform/rancher/rke. When I switched the cluster resource to stop using the in-tree cloud provider, somehow kubelet ended up with the flag `--cloud-provider=` which is obviously not correct.

For anyone in the same position as me, **instead** of doing this to the `rancher_cluster` resource:
```tf
resource "rancher_cluster" "example" {
  rke_config {
	cloud_provider {}
	# cloud_provider {
	#   openstack_cloud_provider {
	#     ...
	#   }
	# }
    ...
  }
  ...
}
```
**do this:**
```tf
resource "rancher_cluster" "example" {
  rke_config {
	cloud_provider { name = "external" } # <-- very important "name" attribute
	# cloud_provider {
	#   openstack_cloud_provider {
	#     ...
	#   }
	# }
    ...
  }
  ...
}
```
The `name` field has poor documentation, and is only semi-alluded to in the rke provider (_not_ the rancher2 provider). If you want to use an out-of-tree cloud provider, you have to name it `external`.

Thanks again @jichenjc! Closing, since this was just user error.

**Comment by jichenjc** [comment]
ok, glad it's solved :)  and yes, seems it's user input instead of OCCM
