### ISSUE TITLE
[all] Release image is built from /home/lingxian

### ISSUE THREAD

**Issue by mdbooth** [kubernetes/cloud-provider-openstack#1825]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:
I noticed the following in a (uninteresting) stack trace from `docker.io/k8scloudprovider/openstack-cloud-controller-manager:v1.23.0`:

```
k8s.io/klog/v2.stacks(0x1)
        /home/lingxian/go/pkg/mod/k8s.io/klog/v2@v2.30.0/klog.go:1038 +0x8a
k8s.io/klog/v2.(*loggingT).output(0x30993c0, 0x3, 0x0, 0xc00040b110, 0x0, {0x259149c, 0x1}, 0xc00028c080, 0x0)
        /home/lingxian/go/pkg/mod/k8s.io/klog/v2@v2.30.0/klog.go:987 +0x5fd
k8s.io/klog/v2.(*loggingT).printf(0x16, 0x8, 0x0, {0x0, 0x0}, {0x1df473e, 0x2b}, {0xc00028c080, 0x1, 0x1})
        /home/lingxian/go/pkg/mod/k8s.io/klog/v2@v2.30.0/klog.go:753 +0x1c5
k8s.io/klog/v2.Fatalf(...)
        /home/lingxian/go/pkg/mod/k8s.io/klog/v2@v2.30.0/klog.go:1532
main.cloudInitializer(0xc00000e820)
        /home/lingxian/go/src/k8s.io/cloud-provider-openstack/cmd/openstack-cloud-controller-manager/main.go:84 +0xee
```

This release image seems to have been built from @lingxiankong's local environment. If so, this does not follow good practise. It exposes the release maintainer to the risk of accidentally leaking local data in release builds. It exposes the project to the risk of non-reproducible builds if the release maintainer's environment was not clean when they did the build. It exposes the project to the risk of non-reproducible builds due to use of an un-versioned toolchain in the release maintainer's local environment.

**What you expected to happen**:
Release images should be built from a clean checkout of a release tag in a clean builder container.

This is a potential security issue.

**Comment by jichenjc** [comment]
this is valid bug, but seems nothing can be done as it's already released
so guess we can start from 1.24 on this? 

and seems need a release process doc which I didn't find (yet)

**Comment by lingxiankong** [comment]
The existing release process can be found here https://github.com/kubernetes/cloud-provider-openstack/blob/master/release-procedure.md, but I don't think it's up to date. I will update the doc with the steps I was following.

**Comment by chrigl** [comment]
/close

@zetaab added a github action to build release images. I would consider this task to be fixed by that. Please re-open if necessary.
