### ISSUE TITLE
[cinder-csi-plugin, occm] Unable to multiattach PV across pods on different nodes 

### ISSUE THREAD

**Issue by madeinindiadot** [kubernetes/cloud-provider-openstack#1827]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
/kind bug - Unable to multiattach PV across pods on different nodes
> /kind feature

**What happened**:
Trying to attach PV to multiple pods in a kubernetes cluster on multiple worker nodes, we are using openstack for worker node VMs 
storage class is set to "multiattach=<is> True"
But when we are using a deployment to attach across multiple worker nodes, it fails with error 

**What you expected to happen**:
Should be able to attach to all the pods across all worker nodes 

**How to reproduce it**:
1. Create SC
2. Create PVC
3. Attach PVC to deployment and create it 
4. Scale up the pods, so that it schedules on all worker nodes
5. Some pods will remain in containercreating state as the volume attachment fails

**Anything else we need to know?**:
we are using cinder.csi.openstack.org as CSIDriver based on occm

Error log
Events:
  Type     Reason              Age                From                     Message
  ----     ------              ----               ----                     -------
  Normal   Scheduled           29s                default-scheduler        Successfully assigned default/task-pv-deployment-77bcbf5fc6-48lph to workernode-2
  Warning  FailedAttachVolume  12s (x6 over 28s)  attachdetach-controller  AttachVolume.Attach failed for volume "pvc-07f4902c-3ee0-4de9-b1be-7dd4bc19da93" : rpc error: code = Internal desc = ControllerPublishVolume Attach Volume failed with error disk 5a7764f0-d30c-44ca-a05d-b939173116b3 is attached to a different instance (06d963d3-d576-41e1-9bf6-162e179e571f)

**Environment**:
- openstack-cloud-controller-manager(or other related binary) version:
- OpenStack version: 5.5.0
- Others: 
- kubernetes version 1.19.4, 1.23.1
- quay.io/k8scsi/csi-node-driver-registrar:v1.2.0
- quay.io/k8scsi/csi-attacher:v2.1.1
- quay.io/k8scsi/csi-provisioner:v1.4.0
- quay.io/k8scsi/csi-snapshotter:v1.2.2
- quay.io/k8scsi/csi-resizer:v0.4.0
- docker.io/k8scloudprovider/cinder-csi-plugin:v1.18.0
- docker.io/k8scloudprovider/openstack-cloud-controller-manager:v1.18.0

**Comment by jichenjc** [comment]
have you tried through this?
https://github.com/kubernetes/cloud-provider-openstack/blob/master/docs/cinder-csi-plugin/features.md#multi-attach-volumes
