### ISSUE TITLE
[cinder-csi-plugin] MAGNUM - Yoga Build -  Failed to list *v1beta1.VolumeAttachment: the server could not find the requested resource

### ISSUE THREAD

**Issue by nashford77** [kubernetes/cloud-provider-openstack#1845]
kubectl api-resources | grep storage
storageversions                                internal.apiserver.k8s.io/v1alpha1     false        StorageVersion
csidrivers                                     storage.k8s.io/v1                      false        CSIDriver
csinodes                                       storage.k8s.io/v1                      false        CSINode
csistoragecapacities                           storage.k8s.io/v1beta1                 true         CSIStorageCapacity
storageclasses                    sc           storage.k8s.io/v1                      false        StorageClass
volumeattachments                              storage.k8s.io/v1                      false        VolumeAttachment

E0503 02:17:21.354067       1 reflector.go:126] k8s.io/client-go/informers/factory.go:133: Failed to list *v1beta1.VolumeAttachment: the server could not find the requested resource
E0503 02:17:21.354177       1 reflector.go:126] k8s.io/client-go/informers/factory.go:133: Failed to list *v1beta1.CSINode: the server could not find the requested resource

So I know the issue - Yoga was build referring to the wrong driver - should be V1 not the beta version of v1, I am wondering if anyone can advise how to fix this so new cluster builds work and dont have ::

if I fix it manually, this won't be helpful each time i deploy a cluster. Any idea where this can be found in magnum to correct it ? 

kubectl get pods --all-namespaces
NAMESPACE     NAME                                         READY   STATUS             RESTARTS         AGE
kube-system   calico-kube-controllers-54799d958b-c4fxm     1/1     Running            0                55m
kube-system   calico-node-45dg5                            1/1     Running            0                53m
kube-system   calico-node-494n6                            1/1     Running            0                55m
kube-system   calico-node-hpl7s                            1/1     Running            0                53m
kube-system   coredns-56448757b9-bdpq5                     1/1     Running            0                55m
kube-system   coredns-56448757b9-glblk                     1/1     Running            0                55m
kube-system   csi-cinder-controllerplugin-0                4/5     CrashLoopBackOff   15 (3m27s ago)   55m  <---- 
kube-system   csi-cinder-nodeplugin-9zsl4                  2/2     Running            0                55m
kube-system   csi-cinder-nodeplugin-d9xmt                  2/2     Running            0                53m
kube-system   csi-cinder-nodeplugin-kfj6n                  2/2     Running            0                53m
kube-system   dashboard-metrics-scraper-67f57ff746-44s85   1/1     Running            0                55m
kube-system   k8s-keystone-auth-qr4kd                      1/1     Running            0                55m
kube-system   kube-dns-autoscaler-6d5b5dc777-tr9rk         1/1     Running            0                55m
kube-system   kubernetes-dashboard-7b88d986b4-xxwcs        1/1     Running            0                55m
kube-system   magnum-metrics-server-6c4c77844b-k6jz6       1/1     Running            0                55m
kube-system   npd-8jpm9                                    1/1     Running            0                53m
kube-system   npd-wc55z                                    1/1     Running            0                53m
kube-system   openstack-cloud-controller-manager-qw5t4     1/1     Running            0                55m

**Comment by nashford77** [comment]
I have also posted this question here: https://storyboard.openstack.org/#!/story/2010023

**Comment by nashford77** [comment]
This is actually due to the csi-snapshot sidecar - what version would work with what's shown here ?

**Comment by jichenjc** [comment]
it's not related to Yoga release, it's mostly a sidecar version you are you using

which CPO CSI you are using now?

**Comment by nashford77** [comment]
This is stock with Yoga MAGNUM. I didn't modify a thing. Magnum needs to be updated really as it uses very outdated sidecars for CSI seemingly - I managed to fix it with

csi_snapshotter_tag:
type: string
description: tag of csi snapshotter
default: v4.0.0

I know there are much newer but not in quay.io repo's. Either way this solved it for me but I am wondering when Magnum will update /magnum/drivers/k8s_fedora_coreos_v1/templates/kubecluster.yaml and the others.

**Comment by jichenjc** [comment]
I am not MAGNUM expert but curious on why it's related to CSI 

https://github.com/kubernetes/cloud-provider-openstack/blob/master/manifests/cinder-csi-plugin/cinder-csi-controllerplugin.yaml#L57 

we are using snapshot 5.0.1 now ,so I am not sure this bug is valid

**Comment by nashford77** [comment]
I agree - It's on their end for the templates being out of date. I am not good enough at Magnum either to re-write it to use modern CSI. They are pointing to quay.io as well notably which doesn't have higher than 4.0 which is the only reason i went with that. I would prefer current.

**Comment by jichenjc** [comment]
we seems not using quay as registry
anyway, please close this issue if you think it's not CPO's problem, thanks

**Comment by nashford77** [comment]
This is an issue with magnum templates being out of date with current versions.

**Comment by jouvin** [comment]
@nashford77 I'm struggling with the same problem in Yoga (that we upgraded to recently). Have you been able to fix the problem? Could you share what you did? It is not completly obvious from the issue discussion. I tried using more recent version of all the CSI components by playing with Magnum labels (and updating where MAgnum get them from...) but with no success so far...

**Comment by jouvin** [comment]
For the record I was able to fix it, see my email on openstack-discuss mailing list on March 17/18...
