### ISSUE TITLE
Update official images with newer base-image patch versions

### ISSUE THREAD

**Issue by kon-angelo** [kubernetes/cloud-provider-openstack#1847]
**Is this a BUG REPORT or FEATURE REQUEST?**:
Security Fixes

> Uncomment only one, leave it on its own line: 
>
> /kind bug
> /kind feature

**What happened**:
Image scanning tools report various critical vulnerability fixes coming from the outdated alpine base image. We see that the Dockerfile only uses minor version for the base image e.g. `alpine 3.15`. In the meantime alpine has released new patch releases that contain several fixes with the latest one (at the time of writing) being `3.15.4`. 

Is it possible to rebuild and upload the official images to the public registries using the latest base images ? 

**What you expected to happen**:

**How to reproduce it**:

**Anything else we need to know?**:

**Environment**:
- openstack-cloud-controller-manager(or other related binary) version:
- OpenStack version: 1.22.X, 1.23.X
- Others:

**Comment by jichenjc** [comment]
this is valid request
you are requesting latest CPO release (master) or previous released version?

**Comment by ialidzhikov** [comment]
It would be great if you can do it for release-1.22 and release-1.23 branches.
