### ISSUE TITLE
[all] migrate from golint to golangci-lint

### ISSUE THREAD

**Issue by chrigl** [kubernetes/cloud-provider-openstack#1853]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind feature

**What happened**:

We are using `golint` to lint the project which [is deprecated](https://github.com/golang/lint/blob/master/README.md).

 > NOTE: Golint is https://github.com/golang/go/issues/38968. There's no drop-in replacement for it, but tools such as [Staticcheck](https://staticcheck.io/) and go vet should be used instead.

We should migrate our linting to `staticcheck`.

**What you expected to happen**:

**How to reproduce it**:

**Anything else we need to know?**:

**Environment**:
- openstack-cloud-controller-manager(or other related binary) version:
- OpenStack version:
- Others:

**Comment by jichenjc** [comment]
@chrigl are you working on this ?

**Comment by chrigl** [comment]
Turns out...

The golint checks never run for quite a while now. In `hacks/verify-golint.sh` a list of files is provided by [`go test ...`](https://github.com/kubernetes/cloud-provider-openstack/blob/master/hack/verify-golint.sh#L63) returned a wrong list. In return, `golint` ran against non-existing files. Unfortunately the exit code of `golint` in this case is still 0, and the output of stderr was redirected to `/dev/null`. 

As a result, the code base contains a whole lot of lint failures.
