### ISSUE TITLE
[occm] Unable to use Loadbalancer Classes in Helm Chart

### ISSUE THREAD

**Issue by shaardie** [kubernetes/cloud-provider-openstack#1856]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:

Due to the helper Script in the Helm Chart, it is not possible to create Loadbalancer Classes as own Sections in the `cloudConfig`. 

**What you expected to happen**:

That I can define my own Loadbalancer Classes in the Helm Chart.

**How to reproduce it**:

Try to define Loadbalancer Class in the Helm Chart `cloudConfig`

**Anything else we need to know?**:
Wouldn't it be easier to skip the whole templating stuff and simply putting the content of `cloudConfig` into the secret?

Something like:

```yaml
cloudConfig: |-
    [Global]
    auth-url=...
    application-credential-id=...
    ...
    [LoadBalancer]
    network=...
    subnet-id=...
    ...
    [LoadBalancerClass "ipv6"]
    network-id=...
    ...
```

**Comment by zakthan** [comment]
I have the exact same issue
I have prepared this PR for that:
https://github.com/kubernetes/cloud-provider-openstack/pull/1950
It worked for me

**Comment by Lirt** [comment]
Fix for this issue was merged in https://github.com/kubernetes/cloud-provider-openstack/pull/1953.

**Comment by shaardie** [comment]
As far as I understood it, this is already fixed with https://github.com/kubernetes/cloud-provider-openstack/pull/1953. So closing is okay.
