### ISSUE TITLE
latest tags not updated in CI

### ISSUE THREAD

**Issue by zetaab** [kubernetes/cloud-provider-openstack#1880]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:

1.24.0 release is released. However, the CI pipeline does not include updating `latest` tags.

**What you expected to happen**:

We should have way to update latest tag

**Anything else we need to know?**:

The problem with CI pipeline is that, if we include updating `latest` tag in CI. What will happen if we make hotfix to old release and re-run CI pipeline. It will tag (really) old release as `latest`. We should have way to detect which semver is really the latest.

**Comment by zetaab** [comment]
latest tags currently tagged with https://github.com/zetaab/cloud-provider-openstack/commit/2a5c3b5d7e4b04b62d0a1a26a8977f66d3149099 

note! it tags only amd64 version of the image.

**Comment by chrigl** [comment]
Do we want latest to be latest-release or e.g. the result of a nightly build?

**Comment by zetaab** [comment]
I think people would like to see latest-release(?)

**Comment by jichenjc** [comment]
>>>I think people would like to see latest-release(?)

+1
how does other project do this ? e.g we pull latest k8s seems pull latest k8s release instead of latest commit?
if so we can follow same pattern..
