### ISSUE TITLE
[OCCM] Support IPv4/IPv6 dual-stack services

### ISSUE THREAD

**Issue by rastislavs** [kubernetes/cloud-provider-openstack#1897]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind feature

**What happened**:
The OCCM does not support dual-stack (IPv4 + IPv6) clusters very well. This is a list of the existing issues:
- IPv4 or IPv6 VIP should be allocated based on the preference defined in service's `.spec.ipFamilies`
- for dual-stack services, both IPv4 and IPv6 load-balancers should be created
- floating IP should not be allocated for IPv6 VIP
- for IPv6 LB, the default `spec.loadBalancerSourceRanges` should be `::/0`
- LB member IP should be IPv4 / IPv6 based on the address family of the VIP
- security group rules should have etherType set based on the LB member address family
- OCCM should support LBs in different subnets (as there will be always 1 IPv4 and 1 IPv6 subnet at least)

**What you expected to happen**:
In a dual-stack k8s cluster, users can create both IPv4 and IPv6 LoadBalancer services and dual-stack LoadBalancer services.

**Comment by jichenjc** [comment]
I assume this will only be LB related, not Ingress parts, correct?
