### ISSUE TITLE
cinder-csi-plugin: gate failure 

### ISSUE THREAD

**Issue by jichenjc** [kubernetes/cloud-provider-openstack#1902]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
> /kind bug
> /kind feature

**What happened**:

https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/cloud-provider-openstack/1898/openstack-cloud-csi-cinder-e2e-test/1531482333746565120/build-log.txt

A pattern 

```
May 31 05:09:28.735: FAIL: "echo PymaVGuuyCbDj6LBtMWeRPL9dgJlDiFHDYT1ZTjD0Gylfb7tjBUgd092PaCn0zgDK3WH0mRVGyw14xAabOaCDw== | base64 -d | dd of=/mnt/volume1/file1.txt  bs=64 count=1" should succeed, but failed with error message "error dialing backend: EOF"
```

looks like this kind of error is random , as some pod with such POST action success ,so not sure what's the real problem here
**What you expected to happen**:

**How to reproduce it**:

**Anything else we need to know?**:

**Environment**:
- openstack-cloud-controller-manager(or other related binary) version:
- OpenStack version:
- Others:

**Comment by jichenjc** [comment]
@chrigl @zetaab not sure you know any k8s change recently that might lead to such error? 
it's weird that some POST action success but some are not ...

**Comment by zetaab** [comment]
No idea

**Comment by jichenjc** [comment]
we have 3 major components

k3s, cpo and k8s test,   seems we don't have too much change recently, 
creating https://github.com/kubernetes/cloud-provider-openstack/pull/1905 for 1.23 , see whether we see similiar issue

**Comment by jichenjc** [comment]
>>>Uninstalling k3s and bringing up a new k3

This is great ~
you are suspecting k3s lead to issue? e.g old k3s (maybe some patch recently) issue being fixed in new k3s?

**Comment by chrigl** [comment]
It is definitely related to k3s 1.23.7-rc1. For now, I will pin it to 1.23.6.
We must work on k3s anyways, because 1.24.0 won't support docker any more. I will create a task.
