### ISSUE TITLE
Allow to synchronize Keystone projects with k8s namespaces

### ISSUE THREAD

**Issue by Fedosin** [kubernetes/cloud-provider-openstack#192]
To improve integration between keystone and k8s it's recommended to add a possibility to synchronize projects/namespaces.

In other words, if the user belongs to the project in Keystone, then when attempting to authenticate in Kubernetes using [k8s-keystone-auth](https://github.com/kubernetes/cloud-provider-openstack/blob/master/docs/using-keystone-webhook-authenticator-and-authorizer.md), a k8s namespace with the same name as the project id will automatically be created for him.

/kind feature

**Comment by lingxiankong** [comment]
Thanks for tracking this, @Fedosin
