### ISSUE TITLE
[occm] Add option to disable tls-container-ref validation

### ISSUE THREAD

**Issue by dshatohin** [kubernetes/cloud-provider-openstack#1929]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind feature

**What happened**:

We have switched backend for octavia listeners certificates store away from barbican to custom one.

Now we're using just **UUID** for our certificates, so we can't use annotation `loadbalancer.openstack.org/default-tls-container-ref` anymore.
Such annotation:

```yaml
annotations:
  loadbalancer.openstack.org/default-tls-container-ref: "f9d0276a-25c1-4ab6-82f2-1152fcccb6cd"
```

leads to error:

```plain
controller.go:307] error processing service default/test (will retry): failed to ensure load balancer: failed to get tls container "f9d0276a-25c1-4ab6-82f2-1152fcccb6cd": Resource not found
event.go:291] "Event occurred" object="default/test" kind="Service" apiVersion="v1" type="Warning" reason="SyncLoadBalancerFailed" message="Error syncing load balancer: failed to ensure load balancer: failed to get tls container \"f9d0276a-25c1-4ab6-82f2-1152fcccb6cd\": Resource not found"
```

There is validation process for that in [`pkg/openstack/loadbalancer.go`](https://github.com/kubernetes/cloud-provider-openstack/blob/a3fcece254263d51b1292026ee1a93adce0cd870/pkg/openstack/loadbalancer.go#L1573-L1579).

**What you expected to happen**:

I'm expecting to be able to specify any string in `default-tls-container-ref` annotation, and don't get any validation errors.

For example, official [terraform-provider-openstack](https://registry.terraform.io/providers/terraform-provider-openstack/openstack/latest/docs/resources/lb_listener_v2#default_tls_container_ref) and [python-octaviaclient](https://docs.openstack.org/python-octaviaclient/pike/usage/osc/v2/load-balancer.html#cmdoption-loadbalancer-listener-create-default-tls-container-ref) do not have any validation and we're able to use this tools for creating listeners with `TERMINATED_HTTPS` and our custom certificate store.

**How to reproduce it**:

Try to specify anything in `loadbalancer.openstack.org/default-tls-container-ref` exept valid barbican container ref url.

**Anything else we need to know?**:

It would be great to have config option for `cloud.conf`, e.g. `validate-tls-container-ref`:

```ini
[LoadBalancer]
validate-tls-container-ref=false
```

I've tried to build **OCCM** without validation check and it works, but implement good solution would be hard for me.

**Environment**:
- openstack-cloud-controller-manager(or other related binary) version: v1.22.0 (or any version)
- OpenStack version:
- Others:

**Comment by jichenjc** [comment]
@dshatohin do you want to work on this  :)

**Comment by dshatohin** [comment]
@jichenjc tbh I do but not very confident in my golang skills.
But in the past I have some expirience with such kind of tasks.
So lets try, it would be great to help

**Comment by jichenjc** [comment]
@dshatohin thanks :) ,let us know anything we can help~

**Comment by jichenjc** [comment]
>>>We have switched backend for octavia listeners certificates store away from barbican to custom one.

Give another thought, so you haven't setup barbican in your openstack ,correct? 
if so , we should avoid check here at all with option `Barbican exist`?

**Comment by dshatohin** [comment]
@jichenjc, yes, we are switching to our own secret manager backend.
I like `container-store` field idea, thank you for suggestion - would implement this.

I'll make a PR next week (at least I hope so).
