### ISSUE TITLE
Label to classify issues by component

### ISSUE THREAD

**Issue by aglitke** [kubernetes/cloud-provider-openstack#193]
I would like to scrub github issues in this repo to identify which pertain to the standalone cinder provisioner.  In my own repo I would use a label "standalone-cinder-provisioner" or something.  Could we add this label or is there a better way to achieve this?

**Comment by dims** [comment]
Done. added `component/standalone-cinder-provisioner` is that ok?

**Comment by aglitke** [comment]
Thank you!!!
