### ISSUE TITLE
[cinder-csi-plugin] btrfs-volumes not mountable by cinder-csi-plugin

### ISSUE THREAD

**Issue by kllex** [kubernetes/cloud-provider-openstack#1934]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug

**What happened**:
I created a StorageClass specifying btrfs as fsType in the parameters section and created a PVC (and thus a PV) using this StorageClass. When trying to mount that PV in a pod I get an error message from the Kubelet failing to mount the PV due to a binary missing in it's $PATH.

**What you expected to happen**:
The PV (with btrfs on it) is mounted to the pod successfully.

**How to reproduce it**:

1.) Deploy a StorageClass:
```bash
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: cinder-csi-btrfs
allowVolumeExpansion: true
parameters:
  fsType: btrfs
provisioner: cinder.csi.openstack.org
reclaimPolicy: Delete
```

2.) Deploy a PVC:
```bash
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-btrfs
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: cinder-csi-btrfs
  volumeMode: Filesystem
```

3.) Create a deployment where the PV is mounted:
```bash
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-btrfs
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: nginx-btrfs
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: nginx-btrfs
    spec:
      containers:
      - image: nginx:alpine
        imagePullPolicy: IfNotPresent
        name: nginx
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /usr/share/nginx/html
          name: www
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: www
        persistentVolumeClaim:
          claimName: test-btrfs
```

Error message in the events looks like this:
```bash
Message:             MountVolume.MountDevice failed for volume "pvc-<some-uuid>" : rpc error: code = Internal desc = format of disk "/dev/disk/by-id/<some-id-path>" failed: type:("btrfs") target:("/var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-<same-uuid>/globalmount") options:("defaults") errcode:(executable file not found in $PATH) output:()
```

**Anything else we need to know?**:
The problem lies in the docker-image of the cinder-csi-plugin missing the **btrfs-tools** debian package. kubectl-exec'ing into it and installing the btrfs-tools deb-package via apt fixes the problem.

I'm guessing adding the package to the RUN line of the file "cluster/images/cinder-csi-plugin/Dockerfile.build" in this git-repo will fix the problem permanently?!

**Environment**:
- cinder-csi-plugin version: v1.23.0
- kubernetes version: v1.23.6

**Comment by jichenjc** [comment]
>>>The problem lies in the docker-image of the cinder-csi-plugin missing the btrfs-tools debian package. kubectl-exec'ing into it and installing the btrfs-tools deb-package via apt fixes the problem.

then we might suffer a situation that we need install multiple tools in the image which is something not that reasonable?
how about we doc this and customer who want to run brtfs can use following 

from CPO-CSI 
RUN install brtfs tools 

then he get a new image and the new image is eligible to be used? 
thoughts?

**Comment by kllex** [comment]
> then we might suffer a situation that we need install multiple tools in the image which is something not that reasonable?
yes ... probably one tool for every supported filesystem. One could argue that *btrfs* is not any other filesystem as more and more linux distributions are switching to it as the default filesystem.

> how about we doc this and customer who want to run brtfs can use following
> 
> from CPO-CSI RUN install brtfs tools
> 
> then he get a new image and the new image is eligible to be used? thoughts?
In our use-case this image is controlled by a 3rd-party operator (kubermatic) which is not easily changed so having it in upstream would be much easier for us. If this is not feasible we will have to resort to rebuilding the image ourselves and try to inject it in the appropriate place.

**Comment by jichenjc** [comment]
>>>One could argue that btrfs is not any other filesystem as more and more linux distributions are switching to it as the default filesystem.

ok, this seems reasonable, install a couple of tools (brtfs / xfs/ ext4) seems do no harm to the ecosystem
so I think it should be ok to include such

do you mind create a patch for this?

**Comment by kllex** [comment]
yes sure, I'll give it a try

**Comment by kllex** [comment]
thank you ! :)
