### ISSUE TITLE
`not found` checks for LoadBalancers do not cover all possible cases

### ISSUE THREAD

**Issue by ialidzhikov** [kubernetes/cloud-provider-openstack#1935]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug

**What happened**:
Recently with https://github.com/kubernetes/cloud-provider-openstack/pull/1913 we addressed https://github.com/kubernetes/cloud-provider-openstack/issues/1912. It seems that this is not enough to address all possible cases for LoadBalancer deletion that does not exists.

The issue I see is that in the `GetLoadBalancer` func (and in other places) we have 2 different ways to fetch the LoadBalancer - by ID, if its `loadbalancer.openstack.org/load-balancer-id` is set; otherwise by name:

https://github.com/kubernetes/cloud-provider-openstack/blob/38938aeb216dc58adebb2367f79b84988ca80b72/pkg/openstack/loadbalancer.go#L674-L684

The problem I see is that both of the ways different `not found` errors:
- `openstackutil.GetLoadbalancerByID` func returns a error that can be checked with the `cpoerrors.IsNotFound(err)` func
- `getLoadbalancerByName` returns `cpoerrors.ErrNotFound` that is not covered by `cpoerrors.IsNotFound(err)`

https://github.com/kubernetes/cloud-provider-openstack/blob/38938aeb216dc58adebb2367f79b84988ca80b72/pkg/util/errors/errors.go#L42-L58

The `cpoerrors.IsNotFound(err)` func currently checks only for gophercloud errors (returned by the OpenStack API) and does not check for `cpoerrors.ErrNotFound`.

**What you expected to happen**:
Non-existing LoadBalancers to be properly ignored in all cases.

**How to reproduce it**:
1. Create a LoadBalancer that fails to be created. For example with LB class set to a non-existing class (loadbalancer.openstack.org/class=foo).

2. Make sure that as expected the LoadBalancer fails to be created with:

```
  Warning  SyncLoadBalancerFailed  4s (x3 over 19s)  service-controller  Error syncing load balancer: failed to ensure load balancer: invalid loadbalancer class "foo"
```

3. Delete the Service

4. Make sure that the deletion fails with:

```
  Warning  SyncLoadBalancerFailed  3s                 service-controller      Error syncing load balancer: failed to check if load balancer exists before cleanup: failed to find object
```

**Anything else we need to know?**:

**Environment**:
- openstack-cloud-controller-manager(or other related binary) version: v1.24.2
- OpenStack version:
- Others:

**Comment by jichenjc** [comment]
agree it's reasonable bug to be fixed @ialidzhikov do you want to address this with a new PR?
we probabally should add `cpoerrors.ErrNotFound.` into checklist

**Comment by ialidzhikov** [comment]
@jichenjc I see that you backported the corresponding fix to release-1.24 with https://github.com/kubernetes/cloud-provider-openstack/pull/1943. Is it possible to cut a new patch release for OCCM 1.24 to allow end users to consume this fix? Thanks in advance!

**Comment by jichenjc** [comment]
@ialidzhikov v1.24.3 released, please check , thanks

**Comment by ialidzhikov** [comment]
Thank you very much!
