### ISSUE TITLE
[cinder-csi-plugin] blkid missing in v1.23.x image

### ISSUE THREAD

**Issue by waipeng** [kubernetes/cloud-provider-openstack#1938]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:
It looks like the blkid command is not in v1.23.x images, although they are in v1.21, v1.22 and v1.24?

**What you expected to happen**:
blkid should be there

**How to reproduce it**:
$ docker run -it k8scloudprovider/cinder-csi-plugin:v1.21.0 which blkid
/sbin/blkid
$ docker run -it k8scloudprovider/cinder-csi-plugin:v1.22.0 which blkid
/sbin/blkid
$ docker run -it k8scloudprovider/cinder-csi-plugin:v1.23.3 which blkid
$ docker run -it k8scloudprovider/cinder-csi-plugin:v1.24.2 which blkid
/sbin/blkid

**Comment by jichenjc** [comment]
I don't know what happened .. but you are right ,there is no such file exist

however, If I manual rebuild cinder image, I can see it exist 

```
Successfully built dd14c00f2719
Successfully tagged build-cinder-csi-plugin-amd64:latest
docker create --name build-cinder-csi-plugin-amd64 build-cinder-csi-plugin-amd64
01d5a1fa86035f463281290b8b2fcf23dbee5002f85a57e365a66159f6ad24d2
docker export build-cinder-csi-plugin-amd64 > /tmp/tmp.dT7sjcfpxB/cinder-csi-plugin/rootfs.tar
build image k8scloudprovider/cinder-csi-plugin-amd64
docker build --build-arg ALPINE_ARCH=amd64 --build-arg ARCH=amd64 --build-arg DEBIAN_ARCH=amd64 --pull -t k8scloudprovider/cinder-csi-plugin-amd64:v1.23.3 /tmp/tmp.dT7sjcfpxB/cinder-csi-plugin
Sending build context to Docker daemon  209.8MB
Step 1/6 : ARG DEBIAN_ARCH=amd64
Step 2/6 : FROM k8s.gcr.io/build-image/debian-base-${DEBIAN_ARCH}:v2.1.3
v2.1.3: Pulling from build-image/debian-base-amd64
Digest: sha256:dc06e242160076b72bd75135fb3dd0a9e91f386b2d812ec10cbf9e65864c755d
Status: Image is up to date for k8s.gcr.io/build-image/debian-base-amd64:v2.1.3
 ---> 3882d22b389f
Step 3/6 : ARG ARCH=amd64
 ---> Using cache
 ---> 7d3b3f4eae45
Step 4/6 : LABEL name="cinder-csi-plugin"       license="Apache Version 2.0"       maintainers="Kubernetes Authors"       description="Cinder CSI Plugin"       architecture=$ARCH       distribution-scope="public"       summary="Cinder CSI Plugin"       help="none"
 ---> Using cache
 ---> 904981a6df09
Step 5/6 : ADD rootfs.tar /
 ---> 8fec43aabbc9
Step 6/6 : CMD ["/bin/cinder-csi-plugin"]
 ---> Running in a6f330b06cde
Removing intermediate container a6f330b06cde
 ---> 14b1cb37d9a1
[Warning] One or more build-args [ALPINE_ARCH] were not consumed
Successfully built 14b1cb37d9a1
Successfully tagged k8scloudprovider/cinder-csi-plugin-amd64:v1.23.3
rm -rf /tmp/tmp.dT7sjcfpxB/cinder-csi-plugin
docker rm build-cinder-csi-plugin-amd64
build-cinder-csi-plugin-amd64
docker rmi build-cinder-csi-plugin-amd64
Untagged: build-cinder-csi-plugin-amd64:latest
Deleted: sha256:dd14c00f2719bda4d31076f627ac5a0a6a21687b95b800ec4a16dc092b65386a
Deleted: sha256:c58e5a9907db75022dcc740de3170e5065bcd40b35cd3ed67fad9f08dae01b54
Deleted: sha256:c581f42dae0092c99b1544412a855d78b3cfd972432dcab876c7f5ba78938e59
Deleted: sha256:f1a3446fc8e22b021d588a882596396c32be8580638da49fb0ee96612b6f0c67


root@jjtest1:~/go/src/github.com/cloud-provider-openstack# docker run -it 14b1cb37d9a1 ls /sbin/blkid
/sbin/blkid
```

do you mind rebuild the image your self as workaround for now?

**Comment by waipeng** [comment]
Thanks for the prompt reply! I may be able to build the image manually. I'm thinking of the options available; I have a few questions, hope you can help.

1. Will v1.24.x image work with a 1.23 kubernetes cluster?
2. Are the v1.23 images basically unusable now because k8s needs `blkid` to figure out the fstype? https://github.com/kubernetes/kubernetes/blob/v1.23.8/staging/src/k8s.io/mount-utils/mount_linux.go#L487
3. Is this something on your TODO list to fix it in next version of the v1.23 branch?

**Comment by jichenjc** [comment]
yes, I have no idea why it pass CI ,but less likely caused by cinder code , more like a build process got some problem (I checked 1.23.0 has this blkid , so might be some patch issue or env issue ...)

probably create a 1.23.4 release later on after find more clue
it should not be

**Comment by jichenjc** [comment]
I created a 1.23.4-rc1 , please check whether it works for you ,if ok, will release 1.23.4
```
# docker run -it k8scloudprovider/cinder-csi-plugin:v1.23.4-rc1 which blkid
Unable to find image 'k8scloudprovider/cinder-csi-plugin:v1.23.4-rc1' locally
v1.23.4-rc1: Pulling from k8scloudprovider/cinder-csi-plugin
4ba180b702c8: Already exists
487ff67c1a30: Pull complete
Digest: sha256:9d55dea7578c87b2f38d91c0cadb4155e0b8168fa793058a4c8ffba413984545
Status: Downloaded newer image for k8scloudprovider/cinder-csi-plugin:v1.23.4-rc1
/sbin/blkid
```

**Comment by pawcykca** [comment]
Image 1.23.4-rc1 looks ok - missing binaries from /sbin are available again.

**Comment by waipeng** [comment]
Looks good to me too. Thanks for the work!
