### ISSUE TITLE
[cinder-csi-plugin] Register is not working if node isn't running on openstack

### ISSUE THREAD

**Issue by IDerr** [kubernetes/cloud-provider-openstack#1947]
/kind bug

**What happened**:  
I want to use cinder-csi on my baremetal cluster not managed by openstack and I have a lot of prints during register of the instance 
```
E0722 10:14:12.878811       1 main.go:122] Registration process failed with error: RegisterPlugin error -- plugin registration failed with err: rpc error: code = Internal desc = [NodeGetInfo] unable to retrieve instance id of node error fetching http://169.254.169.254/openstack/latest/meta_data.json: Get "http://169.254.169.254/openstack/latest/meta_data.json": dial tcp 169.254.169.254:80: i/o timeout, restarting registration container.
```
I don't have any metadata server, but I should be able to bypass the registration process by using either an hardcoded value or another type of value 
The PV is working and usable

**What you expected to happen**:
Bypass the registration process

**How to reproduce it**:
Install cinder-csi on a baremetal cluster without metadata server and register a pvc

**Comment by jichenjc** [comment]
I don't know the meaning of `register` as this new case is brand new to me ,can you point me where's use case or detailed info?

anyway, https://github.com/kubernetes/cloud-provider-openstack/blob/master/pkg/csi/cinder/nodeserver.go#L462 is the code reported your error, we actually have 2 ways `metadata and config drive` to obtain such info
https://github.com/kubernetes/cloud-provider-openstack/blob/master/docs/cinder-csi-plugin/using-cinder-csi-plugin.md#metadata has the detail .. 

so might need know your use case and please check above doc and see whether it's helpful

**Comment by IDerr** [comment]
Hello @jichenjc 

I'll explain more clearly, I want to consume data from cinder on a non openstack machine (no nova-metadata available or anything) (https://github.com/kubernetes/cloud-provider-openstack/blob/ac77d5e7b252e96cfab460dd6ed4fe6ef7e1d364/pkg/util/metadata/metadata.go#L270)
So I don't have either config-drive or metadata service, I've seen that in manila csi, we can specify the nodeID as a parameter of the cli
https://github.com/kubernetes/cloud-provider-openstack/blob/ac77d5e7b252e96cfab460dd6ed4fe6ef7e1d364/manifests/manila-csi-plugin/csi-controllerplugin.yaml#L83

Is it possible to have the same feature for cinder csi ?

Thanks for your work !

**Comment by jichenjc** [comment]
ok, understand ,so you want to have a way to bypass that process .. I am not manila expert so I don't know the reason why manila use a nodeid (guess that's the only way to give that param to make CSI happy)

basically, we can let the nodeID be the first option to make your use case pass (which is ,first check nodeID, then metadata/config drive) ,but I doubt whether add nodeID only can really satisfy your use case ...
can you make your only image by hard code the NodeGetInfo part to see if just hard code the nodeID, then everything is ok?

**Comment by IDerr** [comment]
Yeah, in fact it's not possible, cinder needs to attach the disk to the compute so it's not possible to use external hardware not managed by openstack, my issue is not relevant

Thanks a lot for your help
