### ISSUE TITLE
Improvements for k8s-keystone-auth

### ISSUE THREAD

**Issue by openstacker** [kubernetes/cloud-provider-openstack#195]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind feature

**What happened**:

**What you expected to happen**:
In a perfect world, I would like to see:
1. k8s-keystone-auth can be run either standalone or as pod
2. k8s-keystone-auth can accept both policy file or configMap
3. Policies can be updated and effected on-the-fly
4. If k8s-keystone-auth is running as pod, it can work on worker node.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- openstack-cloud-controller-manager version:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:
  This is related to Magnum/k8s-keystone-auth integration.

**Comment by lingxiankong** [comment]
all the issues will be solved with the PR
