### ISSUE TITLE
[octavia-ingress-controller] listener protocol HTTPS instead of TERMINATED_HTTPS

### ISSUE THREAD

**Issue by edouardpagnier** [kubernetes/cloud-provider-openstack#1962]
/kind feature

**What happened**:
When I create an ingress with spec.tls section configured, the controller creates an loadbalancer with a listener protocol TERMINATED_HTTPS.
Seems to come from here:
https://github.com/kubernetes/cloud-provider-openstack/blob/master/pkg/ingress/controller/openstack/octavia.go#L358

**What you expected to happen**:
I would like to be able to chose the listener protocol to be HTTPS instead of TERMINATED_HTTPS

**Anything else we need to know?**:
According to OpenStack doc (https://docs.openstack.org/api-ref/load-balancer/v2/index.html?expanded=create-pool-detail#protocol-combinations-listener-pool), if the listener protocol is TERMINATED_HTTPS, the pool protocol cannot be HTTPS, meaning we can't do end to end https.

Hopefully I missed something, and what I want is already implemented.

**Environment**:
- openstack-cloud-controller-manager(or other related binary) version: octavia-ingress-controller:latest
- OpenStack version: OVH Openstack (don't know the version they use)

**Comment by jichenjc** [comment]
I am guessing that's just because no use case of HTTPS at that time, @lingxiankong might confirm
anyway, do you want to add a configuration item and update it ?
