### ISSUE TITLE
[cinder-csi-plugin] Version 3.34 is not supported by the API.

### ISSUE THREAD

**Issue by fstarkenberg** [kubernetes/cloud-provider-openstack#1967]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
/kind bug

**What happened**:
When going from v1.22.1 to 1.23.0 I can no longer provision volumes.
```
Events:
  Type     Reason              Age                From                                                                                                                  Message
  ----     ------              ----               ----                                                                                                                  -------
  Normal   Provisioning        11s (x7 over 75s)  cinder.csi.openstack.org_openstack-cinder-csi-controllerplugin-65df4ccb4f-5q7wq_e6f1c3dd-eeb8-475d-8ae5-0d4e363fa087  External provisioner is provisioning volume for claim "default/task-pv-claim"
  Warning  ProvisioningFailed  11s (x7 over 75s)  cinder.csi.openstack.org_openstack-cinder-csi-controllerplugin-65df4ccb4f-5q7wq_e6f1c3dd-eeb8-475d-8ae5-0d4e363fa087  failed to provision volume with StorageClass "csi-cinder-sc-delete": rpc error: code = Internal desc = Failed to get volumes: Expected HTTP response code [200 204 300] when accessing [GET https://my.domain.com:8776/v3/1a7fabaaae77433c95a7b06a9a7a93c2/volumes/detail?name=pvc-159daa3c-c5ba-403c-b523-0a505297d7bc], but got 406 instead
{"computeFault": {"message": "Version 3.34 is not supported by the API. Minimum is 3.0 and maximum is 3.0.", "code": 406}}
  Normal  ExternalProvisioning  7s (x7 over 85s)  persistentvolume-controller  waiting for a volume to be created, either by external provisioner "cinder.csi.openstack.org" or manually created by system administrator
```

**What you expected to happen**:
Provision volume in Cinder on versions before Train

**How to reproduce it**:
Use v1.23.0 or newer on an Openstack cloud pre Train version (?)

**Anything else we need to know?**:
Related to issue #1487 which was fixed in PR #1488  

From what I gather Cinder removed the `query_volume_filters` option in Train and in that PR we started passing the microversion of Cinder to fix it. But this breaks functionality on Openstack releases before Train.

Not sure which Openstack versions can be expected to work since Train is quite old and I'm on an even older version.

**Environment**:
- openstack-cloud-controller-manager(or other related binary) version: >1.23.0
- OpenStack version: Mitaka (yes I know its old)
- Others:

**Comment by jichenjc** [comment]
I admit we didn't list the supported version of openstack too much( we should do so)
instead, we only listed the API version 

now ,with older openstack we expect them to upgrade (and I knew some might be hard)
so I can accept a workaround that we distinguish w/ and w/o microversion code like following
and the MICROVERSION is by default yes, so you can change to false at your case, 

if SUPPORT_MICRO:
    use microversion 
else:
    use older one

do you want to make the change your self? Thanks

**Comment by Jonher937** [comment]
> I admit we didn't list the supported version of openstack too much( we should do so) instead, we only listed the API version
> 
> now ,with older openstack we expect them to upgrade (and I knew some might be hard) so I can accept a workaround that we distinguish w/ and w/o microversion code like following and the MICROVERSION is by default yes, so you can change to false at your case,
> 
> if SUPPORT_MICRO: use microversion else: use older one
> 
> do you want to make the change your self? Thanks

I have pushed a PR for this issue, if you could take a look and run the test-cases that would be great.
Thank you
