### ISSUE TITLE
[occm] Helm Chart has wrong Service Account Name

### ISSUE THREAD

**Issue by shaardie** [kubernetes/cloud-provider-openstack#1973]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
/kind bug
> /kind feature

**What happened**:
ServiceAccount name in the Helm Chart is `openstack-cloud-controller-manager`, but according to the logs occm is using `cloud-controller-manager`.

**What you expected to happen**:

ServiceAccount should either be named `cloud-controller-manager` or occm should use `openstack-cloud-controller-manager`

**How to reproduce it**:

I encountered this during an update of an load balancer service where I go the following error:

```
E0829 10:57:36.377475       1 controller.go:310] error processing service namespace/service (will retry): failed to ensure load balancer: failed to patch service object namespace/service: services "service" is forbidden: User "system:serviceaccount:kube-system:cloud-controller-manager" cannot patch resource "services" in API group "" in the namespace "namespace"
```

**Anything else we need to know?**:

**Environment**:
- openstack-cloud-controller-manager(or other related binary) version: current master (35aea9f3cb0cf19a2b9273ca7fc23de52f5cb049)
- OpenStack version: 
- Others:

**Comment by jichenjc** [comment]
is this related to https://github.com/kubernetes/cloud-provider-openstack/issues/1722 ? 
I remember we had a fix for it already..

**Comment by shaardie** [comment]
Ah, my bad. Thanks for the explanation. My problem was exactly what was fixed in https://github.com/kubernetes/cloud-provider-openstack/pull/1802. I just assumed it was the service account name. I will close this issue again.
