### ISSUE TITLE
{manila-csi-plugin}  kubelet not expose kubelet_volume_stats_capacity_bytes metrics

### ISSUE THREAD

**Issue by lw8008** [kubernetes/cloud-provider-openstack#1998]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> /kind bug

**What happened**:
we want to enable PVC utilization monitor in Prometheus, but i found kubelet not expose kubelet_volume_stats_capacity_bytes for Manila PVCs, but if i'm using other type of CSI, I can see the data exposed.

**What you expected to happen**:
Wondering if i should enable some configure in manila-csi-plugin to make it expose the metrics?

**How to reproduce it**:
Could u pls check your side, whether the data exposed or not.

**Anything else we need to know?**:
K8s 1.23 (Rancher RKE bootstrap)

**Environment**:
- openstack-cloud-controller-manager(or other related binary) version:
- OpenStack version:
- Others:

**Comment by jichenjc** [comment]
don't know whether it's CSI general metrics or CPO CSI need handle it , do you know whether 
other CSI provide this inside their repo ? 

And if you check OCCM `grep metrics * -r` in pkg folder, you can find other components like OCCM does provide metrics..

**Comment by gman0** [comment]
Hi @lw8008, please check you're using a recent version of the driver. NodeGetVolumeStats was added to manila-csi in v1.23 release.

**Comment by lw8008** [comment]
@gman0 thanks, using the latest images it works.
