### ISSUE TITLE
[occm] No external Network detected for Floating IP creation

### ISSUE THREAD

**Issue by MaysaMacedo** [kubernetes/cloud-provider-openstack#2015]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:

When multiple External Networks are available in the cluster, the occm attempts to get the first external Network that has any IPv4 Subnet. However, if the Network is not shared, the tenant is not able to list and filter the IPv4 Subnets of that Network, resulting in no Network detection and no Floating IP created, even when the Network is valid to be used (external with IPv4 subnet, but not shared).

**What you expected to happen**:

Attempt to use any external Network that has IPv4 Subnet or any Network that has Subnets that no details could be gathered about.

**How to reproduce it**:

Create an external network accessible to the tenant with Subnets not accessible to tenant

**Comment by jichenjc** [comment]
>>>
