### ISSUE TITLE
Provide container images for patch releases

### ISSUE THREAD

**Issue by sphr2k** [kubernetes/cloud-provider-openstack#2019]
I would like to suggest that in future, public container images should be made available for patch releases. Otherwise, the benefit of backports such as #1831 e.g. is very limited, because Kubernetes vendors such as KubeOne will usually not provide their own images.

/kind feature

**Comment by jichenjc** [comment]
we do actually, e.g https://github.com/kubernetes/cloud-provider-openstack/releases we have 1.25.3 as we patch time to time
I think it's because 1.22 is relatively old so we didn't do that

**Comment by sphr2k** [comment]
Thanks for the feedback. I think it would still be worth it, most companies don't run the most recent version. 1.22 is still widely used.

**Comment by jichenjc** [comment]
check this https://github.com/kubernetes/cloud-provider-openstack/releases/tag/v1.22.2
```
# docker pull k8scloudprovider/cinder-csi-plugin-amd64:1.22.2
1.22.2: Pulling from k8scloudprovider/cinder-csi-plugin-amd64
4ba180b702c8: Already exists
2a91c75677be: Pull complete
Digest: sha256:9da6479a1596ea606e6860d736e3006e47a88b621ef2983504f67d8d250fd918
Status: Downloaded newer image for k8scloudprovider/cinder-csi-plugin-amd64:1.22.2
docker.io/k8scloudprovider/cinder-csi-plugin-amd64:1.22.2
```

**Comment by jichenjc** [comment]
I will see what I can do here. really sorry I forgot the `v` :(

**Comment by jichenjc** [comment]
check this 

```
# docker pull k8scloudprovider/cinder-csi-plugin-amd64:v1.22.2
v1.22.2: Pulling from k8scloudprovider/cinder-csi-plugin-amd64
4ba180b702c8: Already exists
4ecfe1a3f43f: Pull complete
Digest: sha256:ae525fa4ae0c42364908f9e1989150b175daba19642ffb308b88d359ebc6556b
Status: Downloaded newer image for k8scloudprovider/cinder-csi-plugin-amd64:v1.22.2
docker.io/k8scloudprovider/cinder-csi-plugin-amd64:v1.22.2
```
