### ISSUE TITLE
[occm] Kubelet fails to get instance ID from cloud provider - multiple results where only one expected

### ISSUE THREAD

**Issue by rgaduput** [kubernetes/cloud-provider-openstack#2038]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:
We are using Rancher to create RKE cluster on OpenStack, since Rancher allows to create same node group prefix in different clusters, sometime we happen to create them. In those cases we observed that though servers are created fine in Openstack (even with duplicate names), RKE is deployed and most of the components are up except the `kubelet`, `kubelet` starts to fail with below exceptions
```
I1117 15:16:44.283120   18063 nodeinfomanager.go:401] Failed to publish CSINode: nodes "os-provider-t-master1" not found
E1117 15:16:44.305302   18063 kubelet.go:2466] "Error getting node" err="node \"os-provider-t-master1\" not found"
E1117 15:16:44.324891   18063 kubelet.go:1425] "Kubelet failed to get node info" err="failed to get instance ID from cloud provider: multiple results where only one expected"
```

**What you expected to happen**:

Why is the duplicate node/server name is a problem for `oocm`, Why can't it directly use uuid of the Openstack instance ?
Looking at the code, it does get uuid either from `metadataService`, `configDrive`  [https://github.com/kubernetes/cloud-provider-openstack/blob/master/pkg/util/metadata/metadata.go#L149](url) [https://github.com/kubernetes/cloud-provider-openstack/blob/master/pkg/util/metadata/metadata.go#L192](url) or even directly by reading `/var/lib/cloud/data/instance-id` [https://github.com/kubernetes/cloud-provider-openstack/blob/master/pkg/openstack/instances.go#L524](url), so we are wondering why do we need to use `getServerByName` [https://github.com/kubernetes/cloud-provider-openstack/blob/master/pkg/openstack/instances.go#L538](url) and not the already available uuid.

Appreciate any clarification about this.

**How to reproduce it**:
Create 2 clusters with same node group name from Rancher on Openstack

**Anything else we need to know?**:

**Environment**:
- openstack-cloud-controller-manager(or other related binary) version: 1.23
- OpenStack version: 
- Others:

**Comment by jichenjc** [comment]
are you having 2 node name with same name and in turn same name in openstack side? 

kubelet calls cloud-provider (CPO rely on it),their inteface
https://github.com/kubernetes/cloud-provider/blob/master/cloud.go#L177
use nodeName as param and from CAPO perspective we need get ID for it ,if you give 2 name
then ID will not be able to know which one to reply 

in your case, can you create multiple tenants for different cluster so only the desired tenant cluster should be returned

**Comment by jichenjc** [comment]
>>>You meant to say for each rancher Kubernets cluster we should try and create different Openstack tenant ?

if there is exactly same name ... you can create multiple clusters in one openstack tenant if they have different name.
as mentioned, those APIs are designed across all cloud providers, I guess if you switch to external cloud provider you will have same restrictions for all clouds

**Comment by rgaduput** [comment]
Ok understood, unfortunately its not an option for us to create different Openstack tenants.
since we are talking about hundreds of clusters creation + Rancher does not really know/flag that there is a same node group name being used.

**Comment by jichenjc** [comment]
>>>Rancher does not really know/flag that there is a same node group name being used.

do you think block them to be created if same name will be helpful?
I am think whether we can block the creation so we won't have this reported issue

**Comment by rgaduput** [comment]
sure that would be help too. But is that even possible currently to block duplications ?
