### ISSUE TITLE
[cinder-csi-plugin] Wrong `DevicePath` returned to `VolumeAttachment.status.attachmentMetadata`.

### ISSUE THREAD

**Issue by VVvKamper** [kubernetes/cloud-provider-openstack#2047]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:
Because of known misbehaviour in cinder (see #1065 #150) `controllerserver` reports wrong `DevicePath` to `csi-attacher` in `ControllerPublishVolumeResponse`.  

**What you expected to happen**:
One of the following:
1. `DevicePath` is set to the right device path.
2. `DevicePath` is not set  or there is note on this behaviour in the docs.

**How to reproduce it**:
I don't know exact steps to reproduce but on my system it happens quite often. Possibly one can find steps to reproduce in previous mentioned issues.

**Anything else we need to know?**:
I read the CSI spec but didn't find any good solution for this problem. 
One idea could be to update `VolumeAttachment` from the `nodecontroller`, but design doc requires `VolumeAttachment` to be owned by `csi-attacher` and that no other entities should update it. 
Another solution could be to `controllerserver` request real device path from `nodecontroller` but as i understand `nodecontroller` listens only on unix socket so is not available from the `controllerserver`. And i don't know any way for `nodecontroller` to communicate real device path to the `controllerserver`.

I'll be happy to make a PR for this bug if you can guide me to appropriate solution.

**Environment**:
- cinder-csi-plugin version: `docker.io/k8scloudprovider/cinder-csi-plugin-amd64:v1.24.0`
- OpenStack version: Nova - Stein, Cinder - Wallaby
- Others:

**Comment by VVvKamper** [comment]
unfortunately we can't change version of openstack because we receive it from our cloud provider. but as i see by your link and in relevant issues in openstack issue tracker there was no progress on this issue.

do you know any possible solution for this in case  we can't rely on openstack?. can we somehow communicate device path from `nodecontroller` to `controllerserver` ?

**Comment by jichenjc** [comment]
I reviewed #1065 again and with comment
https://github.com/kubernetes/cloud-provider-openstack/issues/1065#issuecomment-627898467
I think the issue I talked above not exist any more (sorry remember wrong stuff)
except the NodeExpandVolume case but I think you are not using it?

looks like this is the function get the DevicePath
https://github.com/kubernetes/cloud-provider-openstack/blob/master/pkg/csi/cinder/nodeserver.go#L576

and I tried to produce this in #1065 also not able to reproduce
so can you confirm you are using Expand case ? (see #1065 for detailed discussion)

**Comment by VVvKamper** [comment]
I'm not using expand case. The problem is with `ControllerPublishVolume` method (in [this line](https://github.com/kubernetes/cloud-provider-openstack/blob/master/pkg/csi/cinder/controllerserver.go#L225)). This method reports to `csi-attacher` and after that it publishes wrong device path in the `VolumeAttachment` resource. 
For example:

```yaml
apiVersion: storage.k8s.io/v1
kind: VolumeAttachment
metadata:
  annotations:
    csi.alpha.kubernetes.io/node-id: e8db4dbf-12e5-46c3-9d29-08d46dd21708
  creationTimestamp: "2022-09-20T04:39:50Z"
  finalizers:
  - external-attacher/cinder-csi-openstack-org
  name: csi-e0c2d695e8a71b5d7f413488433bff8988656e095036bc6ad9743db5b420ba6d
  resourceVersion: "2760435477"
  uid: 0e8a0141-85f3-4813-992b-2bbe3783e3c7
spec:
  attacher: cinder.csi.openstack.org
  nodeName: k8s-node-default-043
  source:
    persistentVolumeName: pvc-d71380c1-7686-4128-96cd-691017957cd2
status:
  attached: true
  attachmentMetadata:
    DevicePath: /dev/sdi
```

Here you can see that device path is reported as `/dev/sdi` but on the server i can check that real path is `/dev/sdg`. I can see it in the `lsblk` output:

```
sdg       8:96   0    1G  0 disk /var/lib/kubelet/pods/578f2dbd-0eb5-40e0-817c-404a7e798750/volumes/kubernetes.io~csi/pvc-d71380c1-7686-4128-96cd-691017957cd2/mount
                                 /var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-d71380c1-7686-4128-96cd-691017957cd2/globalmount
```

It's the single place left in the code where we use openstack to determine device path. Expand case is working fine because of your old fix - no problem with it.

My use case is that i want to build io usage metrics for pvc's and for that i want to join `node_exporter` (like `node_disk_io_time_seconds_total `) metrics (that has `device` label) with `kube-state-metrics` metrics (`kube_volumeattachment_status_attachment_metadata` has `metadata_device_path` and `volumeattachment` and there is some other metrics that allows me to get pvc name from `device` and `node` labels).

I have a workaround right now to make own exporter that will export info metric with volume name and corresponding device, but still i think i'll be better to fix it here or at least document this behaviour, that you can't trust `attachmentMetadata` in the `VolumeAttachment` resource.

**Comment by jichenjc** [comment]
>>>, but still i think i'll be better to fix it here or at least document this behaviour, that you can't trust attachmentMetadata in the VolumeAttachment resource.

ok , please submit the PR if you have solution , I think we should take it 

the use case doesn't matter, but `DevicePath: /dev/sdi` should align with `lsblk` output per your comments
so please help if you have any solution, thanks :)
