### ISSUE TITLE
[occm] (helm chart) `cloud-controller-manager` serviceaccount has no clusterrolebinding

### ISSUE THREAD

**Issue by euven** [kubernetes/cloud-provider-openstack#2049]
/kind bug

**What happened**:
Using `--use-service-account-crredentials` (as is default in the chart), I'm seeing the following in the logs:

```
I1202 01:58:51.386134       1 event.go:294] "Event occurred" object="test/nginx-ingress-nginx-ingress" fieldPath="" kind="Service" apiVersion="v1" type="Warning" reason="SyncLoadBalancerFailed" message="Error syncing load balancer: failed to ensure load balancer: failed to patch service object test/nginx-ingress-nginx-ingress: services \"nginx-ingress-nginx-ingress\" is forbidden: User \"system:serviceaccount:kube-system:cloud-controller-manager\" cannot patch resource \"services\" in API group \"\" in the namespace \"test\""
```
Should the roles stuff in the [manifests](https://github.com/kubernetes/cloud-provider-openstack/tree/master/manifests/controller-manager) folder be part of the chart, or am I misunderstanding how this works?

When I set `--use-service-account-credentials=false` via `controllerExtraArgs`, things seem to work as expected.

**What you expected to happen**:
No permission errors in the logs

**How to reproduce it**:
Install the helm chart with values:
```
    image:
      tag: v1.24.5
```

**Comment by jichenjc** [comment]
I am wondering whether your namespace is incorrect or other manual things handled wrong

https://github.com/kubernetes/cloud-provider-openstack/blob/master/charts/openstack-cloud-controller-manager/templates/clusterrole.yaml#L36 is the role that defined and there is a rolebinding that helps grant the actions, maybe you can check whether there's something wrong there

the option you provided seems reltaed to 
https://github.com/kubernetes/cloud-provider/blob/master/options/options.go#L187
so likely it will create a client that allow Anonym access which not something we desire to though it can solve your current issue

**Comment by euven** [comment]
Thanks for taking a look @jichenjc.

The namespace I'm installing this into is `kube-system`.

> https://github.com/kubernetes/cloud-provider-openstack/blob/master/charts/openstack-cloud-controller-manager/templates/clusterrole.yaml#L36 is the role that defined and there is a rolebinding that helps grant the actions, maybe you can check whether there's something wrong there

Note the serviceaccount there is `system:openstack-cloud-controller-manager`, which *does* get used, and works, when you set `--use-service-account-credentials=false`.
The issue seems to arise when you set `--use-service-account-credentials=true`: `system:serviceaccount:kube-system:cloud-controller-manager` seems to be used then *not*  `system:openstack-cloud-controller-manager`). While `system:serviceaccount:kube-system:cloud-controller-manager` does exist, there seems to be no clusterrolebinding, hence asking if the relevant things in [manifests](https://github.com/kubernetes/cloud-provider-openstack/tree/master/manifests/controller-manager) should be part of the chart, if `--use-service-account-credentials=true` is used?

**Comment by jichenjc** [comment]
ok, this reminds me https://github.com/kubernetes/cloud-provider-openstack/issues/1722

can you help check this issue?

**Comment by zifeo** [comment]
@jichenjc Got same issue with 1.25.0, same solution. Isn't #1755 missing the `openstack-` part?

**Comment by jichenjc** [comment]
>>>Got same issue with 1.25.0, same solution. Isn't https://github.com/kubernetes/cloud-provider-openstack/pull/1755 missing the openstack- part?

um.. the fix is there for long time .. so if it's a 1.25 potential fix, then it's a new issue :(

**Comment by namsral** [comment]
Had a similar issue after updating the openstack-cloud-controller-manager chart from 1.3.0 to 1.4.0

New services backed by load-balancers would not get an external IP because the serviceaccount _cloud-controller-manage_ did not have the proper privileges to patch the service object.

Error:

```sh
Warning  SyncLoadBalancerFailed  2m30s (x2 over 5m11s)  service-controller  Error syncing load balancer: failed to ensure load balancer: failed to patch service object istio-ingress/istio-ingressgateway: services "istio-ingressgateway" is forbidden: User "system:serviceaccount:kube-system:cloud-controller-manager" cannot patch resource "services" in API group "" in the namespace "istio-ingress"
```

My temporary workaround:

```sh
% kubectl apply -f - <<EOF
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: system:cloud-controller-manager
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:openstack-cloud-controller-manager
subjects:
- kind: ServiceAccount
  name: cloud-controller-manager
  namespace: kube-system
EOF
```

**Comment by yankcrime** [comment]
We've started hitting consistently as well with `v1.25.0` (since that's the latest version deployed via the Helm chart).  The workaround suggested by @namsral does the trick.

**Comment by lukasmrtvy** [comment]
@namsral 
the error comes from service-controller ( kube-controller-manager ) which is using "system:serviceaccount:kube-system:cloud-controller-manager" user.

Helm chart has slightly different ClusterRoleBinding and RBAC ( https://github.com/kubernetes/cloud-provider-openstack/blob/master/charts/openstack-cloud-controller-manager/templates/clusterrolebinding.yaml ) "system:serviceaccount:kube-system:openstack-cloud-controller-manager" 

I am not familiar with how it is working with the external cloud provider. @jichenjc
