### ISSUE TITLE
fix manila gate skip cases

### ISSUE THREAD

**Issue by jichenjc** [kubernetes/cloud-provider-openstack#2061]
**Is this a BUG REPORT or FEATURE REQUEST?**:

https://github.com/kubernetes/cloud-provider-openstack/pull/2052 skipped some test cases due to manila issue
https://github.com/kubernetes/cloud-provider-openstack/pull/2060 is testing it 

we should track the issue here @gman0 @ramineni FYI

> Uncomment only one, leave it on its own line: 
>
> /kind bug
> /kind feature

**What happened**:

**What you expected to happen**:

**How to reproduce it**:

**Anything else we need to know?**:

**Environment**:
- openstack-cloud-controller-manager(or other related binary) version:
- OpenStack version:
- Others:

**Comment by jichenjc** [comment]
/kind bug

@gman0 please check #2060 , it's failing

**Comment by gman0** [comment]
Testing this locally (with cephfs backend) worked fine.

**Comment by gman0** [comment]
Deployed Manila with NFS backend in devstack stable/zed. Manually snapshotting, creating a PVC from the snapshot and checking files works fine too. I'll try to set up e2e environment and run the tests there.

**Comment by gman0** [comment]
```bash
log_dir="/tmp/manila-csi-e2e"

mkdir -p ${log_dir}

go test -v \
    ./cmd/tests/manila-csi-e2e-suite/manila_csi_e2e_suite_test.go \
    --ginkgo.v \
    --ginkgo.noColor \
    --ginkgo.progress \
    --ginkgo.skip="\[Disruptive\]|\[sig-storage\]\s+\[manila-csi-e2e\]\s+CSI\s+Volumes\s+\[Driver:\s+nfs.manila.csi.openstack.org\]\s+\[Testpattern:\s+Dynamic\s+PV\s+\(default\s+fs\)\]\s+provisioning\s+should\s+provision\s+storage\s+with\s+any\s+volume\s+data\s+source\s+\[Serial\]" \
    --ginkgo.focus="\[manila-csi-e2e\]" \
    -report-dir ${log_dir} \
    -timeout=0 | tee "${log_dir}/manila-csi-e2e.log"
```

```
Ran 34 of 157 Specs in 1447.034 seconds
SUCCESS! -- 34 Passed | 0 Failed | 0 Pending | 123 Skipped
You're using deprecated Ginkgo functionality:
=============================================
  --ginkgo.noColor is deprecated, use --ginkgo.no-color instead
  Learn more at: https://onsi.github.io/ginkgo/MIGRATING_TO_V2#changed-command-line-flags

To silence deprecations that can be silenced set the following environment variable:
  ACK_GINKGO_DEPRECATIONS=2.4.0

--- PASS: Test (1447.04s)
PASS
ok  	command-line-arguments	1447.077s
```

I'm trying to figure out what is different in my env and the CI. The tests are passing.

**Comment by gman0** [comment]
@ramineni @jichenjc I don't have a lot of time to work on this now in between the holidays, but so far I haven't been able to reproduce this error. It seems there's an issue with the CI job, not the snapshotting functionality itself. When is the deadline for the release? I'm ok with releasing and fixing the CI later.

**Comment by jichenjc** [comment]
>>>not the snapshotting functionality itself. When is the deadline for the release? I'm ok with releasing and fixing the CI later.

I don't think we are at rush to fix this and given local test passed and CI gate might have env issue
I think we can release 1.26.0 given even though this might be an issue it should be rare case and less likely happen all the time

**Comment by ramineni** [comment]
+1 , if we there is no breaking of functionality , then we are good with release. CI can be fixed later . Please update the remarks in issue as well. Thanks.
