### ISSUE TITLE
Request new container build of cinder-provisioner to be pushed to docker

### ISSUE THREAD

**Issue by aglitke** [kubernetes/cloud-provider-openstack#207]
Hi.  There have been several recent fixes and enhancements to the cinder-provisioner.  Can someone trigger a build to update cinder-provisioner:latest to the current state of the code?  Thanks!

**Comment by dims** [comment]
Done! please see https://hub.docker.com/r/k8scloudprovider/cinder-provisioner/tags/

thanks,
Dims

/close
