### ISSUE TITLE
[occm] Add support for server groups (schedulerHints) to allow anti-affinity for nodes

### ISSUE THREAD

**Issue by svogt** [kubernetes/cloud-provider-openstack#2086]
**FEATURE REQUEST**:

/kind feature

**What happened**:

Rancher provisioned K3S cluster with the occm installed bootet multiple nodes on the same compute instance. When that one crashed, the cluster was disfunctional due to only one control node being left intact.

**What you expected to happen**:

Distribute the created instance over different compute nodes (server group with anti-affinity or soft-anti-affinity)

**How to reproduce it**:

Let OCCM create Nova instances and check that they have no server group attached to it ;)

**Anything else we need to know?**:

**Environment**:
- openstack-cloud-controller-manager(or other related binary) version: 1.4.0
- OpenStack version: Currently Wallaby

**Comment by svogt** [comment]
Reference to the relevant documentation in gophercloud: http://gophercloud.io/docs/compute/#schedulerhints

**Comment by jichenjc** [comment]
>>>Rancher provisioned K3S cluster with the occm installed bootet multiple nodes on the same compute instance.

is this k3s startup process need handle? OCCM is a daemon that handle *each* node (represented by one openstack VM)
so what's need to be done from OCCM perspective?

**Comment by zetaab** [comment]
this issue is perhaps in wrong place, occm does not handle any virtual machine provisioning

**Comment by jichenjc** [comment]
>>>this issue is perhaps in wrong place, occm does not handle any virtual machine provisioning

that's exactly my question ...

**Comment by svogt** [comment]
Sorry for the late response, didn't see the comments.
I thought that this is the place where new instances are created: https://github.com/kubernetes/cloud-provider-openstack/blob/master/pkg/openstack/instancesv2.go ? 

/remove-lifecycle stale

**Comment by jichenjc** [comment]
>>>I thought that this is the place where new instances are created: https://github.com/kubernetes/cloud-provider-openstack/blob/master/pkg/openstack/instancesv2.go ?

no, the OCCM is daemon and NOT for the VM creation, the VM created outside, e.g (only one sample) https://github.com/kubernetes-sigs/cluster-api-provider-openstack then become a node and OCCM you pointed will be a container (like a daemon) handle the sync and other management actions
