### ISSUE TITLE
[occm] Add ability to override single endpoint

### ISSUE THREAD

**Issue by dabeck** [kubernetes/cloud-provider-openstack#2091]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind feature

**What happened**:
Our cloud provider does not offer full support for the octavia API but has a _octavia-proxy_ in place that is able to serve as octavia-api. Unfortunately we must set a special endpoint for the octavia api. This is already possible with the openstack-cli. In `clouds.yaml` I just set `load_balancer_endpoint_override: https://octavia.api.url/v2.0`.

**What you expected to happen**:
My expectation is to add the exact same property to the `clouds.yaml` mounted by occm and it uses the proper endpoint.

**Anything else we need to know?**:

**Environment**:
- octavia-proxy: https://github.com/opentelekomcloud-infra/octavia-proxy
- openstack-cloud-controller-manager(or other related binary) version: v1.26.0
- OpenStack version: open-telekom-cloud

**Comment by kayrus** [comment]
Is it an option for you to specify a new endpoint type in keystone services catalog?

**Comment by dabeck** [comment]
@kayrus Thank you for your answer. Unfortunately I'm not that familiar with configuring openstack itself as we're using a managed environment of a cloud provider I think this might not be possible at all. 
Then I'll have a look at gophercloud.

**Comment by dabeck** [comment]
@kayrus I just found that there is already something implemented here: https://github.com/gophercloud/utils/blob/7c693d7efe477e3b859a36be77a5f272f2334e0b/terraform/auth/config.go#L245
