### ISSUE TITLE
[occm] - RKE cluster dont create pods

### ISSUE THREAD

**Issue by GMoraesGarcia** [kubernetes/cloud-provider-openstack#2093]
- openstack-cloud-controller-manager(or other related binary) version:
- OpenStack version: Ussuri
- RKE1
- kubectl apply:
    ```
     kubectl apply -f https://raw.githubusercontent.com/kubernetes/cloud-provider-openstack/master/manifests/controller- 
     manager/cloud-controller-manager-roles.yaml
     kubectl apply -f https://raw.githubusercontent.com/kubernetes/cloud-provider-openstack/master/manifests/controller- 
     manager/cloud-controller-manager-role-bindings.yaml
     kubectl apply -f https://raw.githubusercontent.com/kubernetes/cloud-provider-openstack/master/manifests/controller-manager/openstack-cloud-controller-manager-ds.yaml
```
Hello, i was build cluster kubernetes using RKE1 i follow all the steps to create a clound.conf and deploy occm
but pods wasnt create, i follow some steps to edit a deamon[]( https://openmetal.io/docs/manuals/kubernetes-guides/installing-the-kubernetes-openstack-cloud-controller-manager)  but dont work

occm is realy compatible with RKE1?

Thanks!!

**Comment by rramo012** [comment]
I wrote the OpenMetal guide you referenced and I'm happy to help if I can.

The issue we had while testing was that our control nodes were deployed with the label `controlplane`. However, the DaemonSet is configured to deploy the OCCM pods on the nodes with the label `control-plane`.

Which naming convention do your master nodes use for the label `node-role.kubernetes.io`? 

`kubectl get nodes --show-labels`

**Comment by GMoraesGarcia** [comment]
Hello, thanks for your answer!

One of labels was wrong, i already change and re-run the occm
but dont work.
here is the labels:
`control-plane   Ready    control-plane,etcd   27d   v1.25.5   beta.kubernetes.io/arch=amd64,beta.kubernetes.io/os=linux,kubernetes.io/arch=amd64,kubernetes.io/hostname=control-plane,kubernetes.io/os=linux,node-role.kubernetes.io/control-plane=true,node-role.kubernetes.io/etcd=true
worker-node-1   Ready    worker               12d   v1.25.5   beta.kubernetes.io/arch=amd64,beta.kubernetes.io/os=linux,kubernetes.io/arch=amd64,kubernetes.io/hostname=worker-node-1,kubernetes.io/os=linux,node-role.kubernetes.io/worker=true
worker-node-2   Ready    worker               12d   v1.25.5   beta.kubernetes.io/arch=amd64,beta.kubernetes.io/os=linux,kubernetes.io/arch=amd64,kubernetes.io/hostname=worker-node-2,kubernetes.io/os=linux,node-role.kubernetes.io/worker=true
`
and now the `kubectl edit daemonset/openstack-cloud-controller-manager -n kube-system` is true just with 'control-plane'

**Comment by rramo012** [comment]
Looks like the node selector within the daemon set should be `node-role.kubernetes.io/control-plane: "true"` for your pods to deploy.

If that's not working, I would check the taints on your control nodes. The daemon set is configured to tolerate the taints below. If you have any other taints on your control nodes, you may need to update the tolerations.

	 - key: node.cloudprovider.kubernetes.io/uninitialized
	 value: "true"
	 effect: NoSchedule
	 - key: node-role.kubernetes.io/master
	 effect: NoSchedule
	 - key: node-role.kubernetes.io/control-plane
	 effect: NoSchedule

**Comment by GMoraesGarcia** [comment]
The taints in control node and tolerations in deamonset is equals, i try restart deamonset after updates but still not working

**Comment by GMoraesGarcia** [comment]
I will try recreate the cluster, can i do something else? or that is all  i have to pay attention to?

**Comment by rramo012** [comment]
It's the only thing I can think of, just make sure the node-selector and tolerations are aligned. You may also want to try `node-role.kubernetes.io/control-plane: ""` if your updating your control node labels. It looks like that is the label which the tolerations are targeting.

**Comment by GMoraesGarcia** [comment]
With a new cluster works, thanks a lot!!

**Comment by framctr** [comment]
I have the same issue. I wrote on [ServerFault](https://serverfault.com/questions/1130802/rke-openstack-cloud-provider-without-scheduled-pods), but found no solutions. I created a new cluster but it does not work.... I also added the toleration:
```yaml
    tolerations:
    - key: node-role.kubernetes.io/controlplane
      value: "true"
      effect: NoSchedule
```

**Comment by framctr** [comment]
As described on ServerFault, I found the solution. I will add it here.

Ok, I figured out how to solve this issue.

The problem is that I created the control plane nodes with both the roles `controlplane` _and_ `etcd`. As described in the [SUSE support website](https://www.suse.com/support/kb/doc/?id=000020116), by looking at the taints we can see that not only there is `node-role.kubernetes.io/controlplane=true:NoSchedule`, but also `node-role.kubernetes.io/etcd=true:NoExecute` which prevents any pod to be scheduled:
```
kubectl get node k8s-master -o custom-columns=NAME:.metadata.name,TAINTS:.spec.taints
NAME                    TAINTS
k8s-master              [map[effect:NoSchedule key:node-role.kubernetes.io/controlplane value:true] map[effect:NoExecute key:node-role.kubernetes.io/etcd value:true]]
```

By adding the following tolerations in the `openstack-cloud-controller-manager` `DaemonSet`, pods are scheduled correctly:
```
spec:
  ...
    spec:
      nodeSelector:
        node-role.kubernetes.io/controlplane: "true"
      tolerations:
      ...
      - key: node-role.kubernetes.io/controlplane
        value: "true"
        effect: NoSchedule
      - key: node-role.kubernetes.io/etcd
        value: "true"
        effect: NoExecute
```
