### ISSUE TITLE
[occm] No deterministc way of providing Node addresses

### ISSUE THREAD

**Issue by MaysaMacedo** [kubernetes/cloud-provider-openstack#2096]
**What happened**:

We have been relying on the node-ip flag of Kubelet to specify the IPs the Nodes Addresses would contain. However, the external cloud provider does not support dual-stack addresses defined in the node-ip. The following error happens:

`kubelet exited: failed to run Kubelet: dual-stack --node-ip \"....\" not supported when using a cloud provider"`

While there is a [KEP](https://github.com/kubernetes/enhancements/pull/3706) that will add support for that, it would be beneficial to instead rely on the provisioner of the resources to identify, which addresses the Nodes should use. 
CCM already provides [two options ](https://github.com/kubernetes/cloud-provider-openstack/blob/master/docs/openstack-cloud-controller-manager/using-openstack-cloud-controller-manager.md#networking) that at first glance made sense to use, but seems to have drawbacks:

- internal-network-name: This options uses the name of a Network to filter the addresses to provide. This becomes problematic because OpenStack allows to have multiple Networks with the same name in the cluster, so we could end up exposing Networks on the Node that are not meant to.
- address-sort-order: Seems to only specify a preferable order of addresses to use and does really exclude addresses that are not meant to be exposed.

Are those drawbacks of those options valid? If yes, would it make sense to add support to only provide addresses from the Server's interfaces that are marked with a certain tag?

**What you expected to happen**:
CCM provides a deterministic way to define the addresses the Nodes should use.

**How to reproduce it**:

Deploy a dual-stack cluster with Kubelet not defining any node-ip and the Nodes having multiple interfaces attached.

**Comment by zetaab** [comment]
is this really bug or feature? In my opinion its missing feature

**Comment by mdbooth** [comment]
I also think this is a feature.

Whatever solution we settle on we expect to develop and test it ourselves. We'd like to discuss what folks are currently doing and what solutions others may have already come up with for the same problem.

**Comment by MaysaMacedo** [comment]
cancel /kind bug

**Comment by dulek** [comment]
@MaysaMacedo: This thing sounds like something that got fixed?

**Comment by MaysaMacedo** [comment]
This would be a nice improvement to have, but we decided to remain using node-ip from kubelet. So I will be closing this bug.

**Comment by MaysaMacedo** [comment]
pushed wrong button

**Comment by MaysaMacedo** [comment]
Looks like I'm not allowed to close as not planned, so I will let someone else handle it.
