### ISSUE TITLE
unexpected directory layout while running make

### ISSUE THREAD

**Issue by RdL87** [kubernetes/cloud-provider-openstack#210]
**Is this a BUG REPORT or FEATURE REQUEST?**:

 /kind bug

**What happened**:

After gave the make k8s-keystone-auth command, during the dep ensure phase i receive the following error:

CGO_ENABLED=0 GOOS=linux go build \
	-ldflags "-w -s -X 'main.version=b4f24944-dirty'" \
	-o k8s-keystone-auth \
	cmd/k8s-keystone-auth/main.go
unexpected directory layout:
	import path: github.com/golang/glog
	root: /home/dilallo/go/src
	dir: /home/dilallo/go/src/k8s.io/cloud-provider-openstack/vendor/github.com/golang/glog
	expand root: /home/dilallo/go/src
	expand dir: /home/dilallo/go/src/k8s.io/cloud-provider-openstack/vendor/github.com/golang/glog
	separator: /
Makefile:88: recipe for target 'k8s-keystone-auth' failed
make: *** [k8s-keystone-auth] Error 1

My GO version go1.10.3 linux/amd64

**Comment by mrhillsman** [comment]
@RdL87 i am not seeing an issue currently, here's my output:

```shell
root@cloud-provider-openstack:/usr/local/lib/go/src/k8s.io/cloud-provider-openstack# make -j6 k8s-keystone-auth
pip install Mercurial
Collecting Mercurial
  Downloading https://files.pythonhosted.org/packages/12/e7/46894628ed3d6b0ae1e324523b09fdb8a90f0720bebe43cab88e0ea91b39/mercurial-4.6.1.tar.gz (6.4MB)
    100% |████████████████████████████████| 6.4MB 4.3MB/s
Building wheels for collected packages: Mercurial
  Running setup.py bdist_wheel for Mercurial ... done
  Stored in directory: /root/.cache/pip/wheels/03/67/cd/64e70d0fb8e4ac88f2f6ffdaeba34b67eb8b899eb11f37c53a
Successfully built Mercurial
Installing collected packages: Mercurial
Successfully installed Mercurial-4.6.1
curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  4594  100  4594    0     0  15816      0 --:--:-- --:--:-- --:--:-- 15786
ARCH = amd64
OS = linux
Will install into /usr/local/lib/go/bin
Fetching https://github.com/golang/dep/releases/latest..
Release Tag = v0.4.1
Fetching https://github.com/golang/dep/releases/tag/v0.4.1..
Fetching https://github.com/golang/dep/releases/download/v0.4.1/dep-linux-amd64..
Setting executable permissions.
Moving executable to /usr/local/lib/go/bin/dep
dep ensure
CGO_ENABLED=0 GOOS=linux go build \
	-ldflags "-w -s -X 'main.version=6ecf8d7c'" \
	-o k8s-keystone-auth \
	cmd/k8s-keystone-auth/main.go
root@cloud-provider-openstack:/usr/local/lib/go/src/k8s.io/cloud-provider-openstack# uname -a
Linux cloud-provider-openstack 4.15.0-23-generic #25-Ubuntu SMP Wed May 23 18:02:16 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
root@cloud-provider-openstack:/usr/local/lib/go/src/k8s.io/cloud-provider-openstack# cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.4 LTS"
root@cloud-provider-openstack:/usr/local/lib/go/src/k8s.io/cloud-provider-openstack#
```

**Comment by RdL87** [comment]
@mrhillsman i repeated the same procedure many times yesterday and always got that error. Today, i did the same and everything works. I don't know if it is the case to investigate what happened. Doing some research i found sometimes this kind of error is related to go version or to git packet you're installing. But i checked both and nothing changed fro m yesterday to now.

**Comment by mrhillsman** [comment]
@RdL87 i am not sure unfortunately, afaik we did not make any code changes and we are not seeing any build failures for the jobs related to k8s-keystone-auth binary which can be seen [here](http://status.openlabtesting.org/t/openlab/builds.html?job_name=cloud-provider-openstack-acceptance-test-keystone-authentication-authorization)

the failures there are a result of some refactoring and not related to the error you experienced.

**Comment by RdL87** [comment]
@mrhillsman Maybe it has been an error on my side. I will investigate it so it could help someone who fell in the same situation.
