### ISSUE TITLE
[cinder-csi-plugin]  - MountVolume.MountDevice failed for volume

### ISSUE THREAD

**Issue by GMoraesGarcia** [kubernetes/cloud-provider-openstack#2115]
Hello, i have some issues during volume mount, could you  help?

kubernetes deploy: RKE

my SC:
```
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: csi-sc-cinder
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: cinder.csi.openstack.org
parameters:
  availability: nova
allowVolumeExpansion: true
volumeBindingMode: Immediate

```
csi-cinder-nodeplugin - log:
```
csi-cinder-nodeplugin-ldjzs cinder-csi-plugin 2023-02-20T02:47:31.360297931-03:00 W0220 05:47:31.359104       1 nodeserver.go:589] Couldn't get device path from mount: Failed to find device for the volumeID: "b59ffd99-2fe0-41b9-bd12-01924e0b4875" within the alloted time
csi-cinder-nodeplugin-ldjzs cinder-csi-plugin 2023-02-20T02:47:31.360371037-03:00 I0220 05:47:31.359327       1 nodeserver.go:594] Trying to get device path from metadata service
csi-cinder-nodeplugin-ldjzs cinder-csi-plugin 2023-02-20T02:47:31.740921627-03:00 E0220 05:47:31.738764       1 metadata.go:251] Could not retrieve device metadata for volumeID: "b59ffd99-2fe0-41b9-bd12-01924e0b4875"
csi-cinder-nodeplugin-ldjzs cinder-csi-plugin 2023-02-20T02:47:31.740942593-03:00 E0220 05:47:31.738794       1 nodeserver.go:597] Couldn't get device path from metadata service: could not retrieve device metadata for volumeID: "b59ffd99-2fe0-41b9-bd12-01924e0b4875"
csi-cinder-nodeplugin-ldjzs cinder-csi-plugin 2023-02-20T02:47:31.740947470-03:00 E0220 05:47:31.738809       1 utils.go:92] [ID:25391] GRPC error: rpc error: code = Internal desc = Unable to find Device path for volume: couldn't get device path from metadata service: could not retrieve device metadata for volumeID: "b59ffd99-2fe0-41b9-bd12-01924e0b4875"
```
Pod describe:
```
Warning  FailedMount  18m (x1250 over 2d6h)    kubelet  MountVolume.MountDevice failed for volume "pvc-e891cd25-0853-427f-9f16-f0c075a06e30" : rpc error: code = Internal desc = Unable to find Device path for volume: couldn't get device path from metadata service: could not retrieve device metadata for volumeID: "b59ffd99-2fe0-41b9-bd12-01924e0b4875"
  Warning  FailedMount  8m51s (x1127 over 2d6h)  kubelet  Unable to attach or mount volumes: unmounted volumes=[export], unattached volumes=[export kube-api-access-8sh5n]: timed out waiting for the condition
  Warning  FailedMount  4m20s (x309 over 2d6h)   kubelet  Unable to attach or mount volumes: unmounted volumes=[export], unattached volumes=[kube-api-access-8sh5n export]: timed out waiting for the condition
```

**Comment by zetaab** [comment]
many times when we see similar issues the problem is in openstack side, which means that openstack is unable to attach the volume in host itself. Devices is somehow out of sync and thing that will help is that we will just recreate the node

**Comment by GMoraesGarcia** [comment]
But i saw in openstack and the was created and attached in node

**Comment by zetaab** [comment]
please execute
`ls /dev/vd*|grep -e "/dev/vd[a-z]*$"|wc -l`
`ls /dev/disk/by-id/virtio-*|grep -e "/dev/disk/by-id/virtio-[a-z0-9-]"|wc -l`

in node

**Comment by GMoraesGarcia** [comment]
My volumes partitions is with '/sd*' not '/vd*' and
is 'scsi' not 'virtio'

is a problem?

i execute these command and value here ` ls /dev/disk/by-id/scsi-*|grep -e "/dev/disk/by-id/scsi-[a-z0-9-]"|wc -l ` still same

thanks

**Comment by jichenjc** [comment]
the code error is actually looking for /dev/vd* or /dev/sd* that attached by cinder/nova, the reason is due to udev the given info from API side is not trustable 

did you check whether the volume is attached to your VM?e.g if you create a VM (or use your existing VM) and search what's attached through some command like `lsblk` is might provide you what's the block device looks like then you can search for the attached volume location ,with that, search where's the softlink in /dev/disk/by-id/* then we will know what's the link format
if it's a missing in CPO we can add such logic ...

**Comment by GMoraesGarcia** [comment]
i getter, here is some prints, but in openstack all volumes created using csi plugin are attached in node
![Screenshot from 2023-02-22 20-16-14](https://user-images.githubusercontent.com/56097604/220785556-477ffa81-5c2d-478e-9a70-b948e4d7b9a1.png)
![Screenshot from 2023-02-22 20-16-32](https://user-images.githubusercontent.com/56097604/220785601-6f439fa6-5558-48b4-aadc-d991056b2fb7.png)
![Screenshot from 2023-02-22 20-17-11](https://user-images.githubusercontent.com/56097604/220785629-070daac0-953a-47be-ba53-f8630e7c0ae7.png)

**Comment by jichenjc** [comment]
ok, you do have the mount path 
scsi-0QEMU_QEMU_HARDDISK_3ebxxxx which is the exact  CPO is looking for in the system
so this become weird .. are you able to make the trace level >=5 by modifying the node plugin pod --v flag
so we can get more logs to know which patch rejected the check operations?

**Comment by gcezaralmeida** [comment]
@GMoraesGarcia, any news about this issue? How did you solve it?
