### ISSUE TITLE
[manila]: fix e2e tests

### ISSUE THREAD

**Issue by kayrus** [kubernetes/cloud-provider-openstack#2142]
/kind bug

**What happened**:

Manila functional tests are failing with a python dependency problem:

```
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
```

Example: https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/cloud-provider-openstack/2141/openstack-cloud-csi-manila-e2e-test-release-126/1631577047371354112

**What you expected to happen**:

Manila tests should pass without errors

**How to reproduce it**:

Submit a PR

**Comment by zetaab** [comment]
this issue does not fix the manila tests, see https://github.com/kubernetes/cloud-provider-openstack/pull/2108#issuecomment-1435650268

**Comment by gouthampacha** [comment]
With pr #2244, we'll address the tests executing; but we have a test failure, and may still need pr #2065. Please keep this issue open until then..

**Comment by gouthampacha** [comment]
fixed with #2244 and failing test was skipped with #2254 - this isn't a CSI driver issue, a bug has been reported against openstack/manila: https://bugs.launchpad.net/manila/+bug/2020816

**Comment by kayrus** [comment]
https://bugs.launchpad.net/manila/+bug/2020816 is in progress now

**Comment by dulek** [comment]
Pretty sure this is solved by now.
