### ISSUE TITLE
[all]: push images job fails

### ISSUE THREAD

**Issue by kayrus** [kubernetes/cloud-provider-openstack#2143]
/kind bug

**What happened**:

push images job fails: https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/cloud-provider-openstack-push-images/1631431436202414080

**What you expected to happen**:

push images should work without issues

**How to reproduce it**:

See recent commits status: https://github.com/kubernetes/cloud-provider-openstack/commits/master

**Comment by jichenjc** [comment]
will this help ? https://github.com/kubernetes/cloud-provider-openstack/pull/2139

**Comment by mdbooth** [comment]
Let's find out! Somebody needs to push something.

**Comment by mdbooth** [comment]
No, it's still broken:

```
docker buildx build --output type=registry \
	--build-arg VERSION=v20230307-v1.26.0-26-g42d28be2 \
	--tag gcr.io/k8s-staging-provider-openstack/openstack-cloud-controller-manager:v20230307-v1.26.0-26-g42d28be2 \
	--platform linux/amd64,linux/arm,linux/arm64,linux/ppc64le,linux/s390x \
	--target openstack-cloud-controller-manager \
	.
unknown flag: --output
```

Does that image have an old docker version? This works locally and in GH actions. If only this were easier to test ☹️

**Comment by mdbooth** [comment]
I feel good about that fix. Unfortunately I can't test it end to end, but I'm now reasonably confident it will successfully build an image.

I don't know how the docker secrets are passed to the image so I haven't been able to test that. If it's going to fail again my guess it will be because we're not pushing the images correctly, but afaict we're not doing anything wildly different to the AWS cloudbuild I've been cribbing from.

**Comment by mdbooth** [comment]
Ok, we're making progress! This failed due to permissions:

https://storage.googleapis.com/kubernetes-jenkins/logs/cloud-provider-openstack-push-images/1633111925283885056/build-log.txt
```
#51 ERROR: failed to push gcr.io/k8s-staging-provider-openstack/openstack-cloud-controller-manager:v1.26.0-28-g2a5f397f: failed to authorize: failed to fetch anonymous token: unexpected status: 401 Unauthorized
```

**Comment by mdbooth** [comment]
k8s discussion: https://kubernetes.slack.com/archives/CCK68P2Q2/p1678200584361389

**Comment by mdbooth** [comment]
It wasn't, but https://github.com/kubernetes/test-infra/pull/28959 could be the one.

**Comment by mdbooth** [comment]
Fixed! But I don't think I can

/close
