### ISSUE TITLE
[occm] Non attached pools are left on PENDING_CREATE provisioning state when being created with an LB single-create-call

### ISSUE THREAD

**Issue by tobiasgiese** [kubernetes/cloud-provider-openstack#2165]
/kind bug

**What happened**:

tracking issue for https://storyboard.openstack.org/#!/story/2010426

**What you expected to happen**:

Creating a load balancer with the OVN Provider the pools/listeners/health monitors are stuck in `PENDING_CREATE`

**How to reproduce it**:

<details>
<summary>YAML</summary>

```yaml
apiVersion: v1
kind: Service
metadata:
  annotations:
    loadbalancer.openstack.org/keep-floatingip: "true"
  creationTimestamp: "2023-03-12T19:58:57Z"
  finalizers:
  - service.kubernetes.io/load-balancer-cleanup
  labels:
    caas-e2e: "true"
    random: "480"
    test: ccm
  name: ccm-lb-518
  namespace: ccm-5376
  resourceVersion: "5609"
  uid: 443df4d8-0494-481a-8223-ad4fd02b11cc
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 192.168.98.109
  clusterIPs:
  - 192.168.98.109
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 34157
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    caas-e2e: "true"
    random: "480"
    test: ccm
  sessionAffinity: None
  type: LoadBalancer
```

</details>

**Comment by jichenjc** [comment]
I quickly read https://storyboard.openstack.org/#!/story/2010426 but seems it's pure Octavia tracking
anything need to be handled in CPO ?

**Comment by tobiasgiese** [comment]
@jichenjc It's possible that we don't have to do anything in CPO.
Slack thread for reference: https://kubernetes.slack.com/archives/C0LSA3T7C/p1678454543460209

**Comment by dulek** [comment]
I think the upstream issue is fixed and there are even backports done. I'm going to close this.

/close
