### ISSUE TITLE
usage of helm chart versions in cloud-provider-openstack

### ISSUE THREAD

**Issue by zetaab** [kubernetes/cloud-provider-openstack#2175]
helm chart versions are not used like should in this project. That is why I am doing issue about this and I propose new way of managing versions in Charts. The problem is that we are doing changes to charts and we are not increasing the chart version. Also the second issue is that we have same version in two different branches, then we are doing changes to both without modifying version. This leads to situation that basically none will understand from which helm chart the content is coming from.

This repository contains 3 helm charts:
- cinder-csi-plugin
- manila-csi-plugin
- openstack-cloud-controller-manager

Currently the helm charts are released only from release branches https://github.com/kubernetes/cloud-provider-openstack/blob/master/.github/workflows/release.yaml#L6 However, I propose another change: we could start doing helm chart releases also from master. Master will contain always the latest manifests, but it might be that people cannot use those if they have really old Kubernetes version. Then they should use older helm chart version.

### cinder-csi-plugin

| branch       | current version | new version |
| ------------ | ----------------| ------------|
| master       | 2.3.2           | 2.27.0-alpha.0      |
| release-1.26 | 2.3.0           | 2.26.0      |
| release-1.25 | 2.3.0           | 2.25.0      |
| release-1.24 | 2.2.1           | 2.24.0      |

### manila-csi-plugin

| branch       | current version | new version |
| ------------ | ----------------| ------------|
| master       | 1.6.0           | 2.27.0-alpha.0      |
| release-1.26 | 1.6.0           | 2.26.0      |
| release-1.25 | 1.6.0           | 2.25.0      |
| release-1.24 | 1.5.0           | 2.24.0      |

### openstack-cloud-controller-manager

| branch       | current version | new version |
| ------------ | ----------------| ------------|
| master       |  1.5.0          | 2.27.0-alpha.0      |
| release-1.26 |  1.4.0          | 2.26.0      |
| release-1.25 |  1.4.0          | 2.25.0      |
| release-1.24 |  1.3.0          | 2.24.0      |

So how does it work:
- the version format is 2.[kubeminor].[helmpatch]
- in case of master the format is always 2.[kubeminor].0-alpha.[helmpatch] and when master is moved to release branch, then the format is 2.[kubeminor].[helmpatch] (and starts from 2.[kubeminor].0)
- helmpatch is just number that is increase **ALWAYS** if any changes is done to that specific chart. If the version number is not increased, the helm chart cannot be published -> the changes are not going anywhere. **NOTE!** this includes the appVersion change in helm chart, it means **ALWAYS** if any modifications are coming to file -> increase the helm chart version
- Always when we make new release branch (like release-1.27 next time), the helm chart minor version should be increased in master (2.28.0-alpha.0)
- We start doing helm charts also from master, to get latest and coolest features delivered to users.

cc @jichenjc @nikParasyr @brtknr @eumel8 @morremeyer

**Comment by morremeyer** [comment]
Hey @zetaab, thanks for mentioning the chart maintainers here. Just as a short note from my side, I won't be participating in this discussion since I haven't been working with OpenStack since mid 2021 and am no longer contributing here.

Thanks for making me aware that I'm still listed as chart maintainer, I've PR'd my removal in #2176.

**Comment by zetaab** [comment]
please check the PRs that I opened

**Comment by zetaab** [comment]
another option is that we will stop doing helm chart releases from release branches, and do that only from master branch

**Comment by eumel8** [comment]
The first approach makes sense to me.

**Comment by nikParasyr** [comment]
Haven't worked extensively on cpo but the first approach makes sense. Much clearer which versions to use and a bit more consistent than the current setup

**Comment by zetaab** [comment]
so lets go with that, there are 3 PRs that needs to be still approved
