### ISSUE TITLE
using csi driver with cinder api v2

### ISSUE THREAD

**Issue by morteza1131** [kubernetes/cloud-provider-openstack#2187]
/kind bug

**What happened**:
when using csi driver in kubernetes 1.25.5 with openstack newton and cinder api v2, I got this error:

`No suitable endpoint could be found in the service catalog
`

my cloud.conf:
```
[Global]
      auth-url = http://site:5000/v3/
      username = username
      password = MYPASSWORD
      domain-name  = default
      tenant-name = tenant1
      region = region1
      os-endpoint-type = public
```

**What you expected to happen**:
working fine

**How to reproduce it**:
install with helm chart

**Anything else we need to know?**:

**Environment**:
- openstack-cloud-controller-manager(or other related binary) version:
- OpenStack version:
- Others:

Is this driver work with api v2 of cinder?
how can I fix the issue

**Comment by jichenjc** [comment]
please check

https://github.com/kubernetes/cloud-provider-openstack/blob/master/docs/cinder-csi-plugin/using-cinder-csi-plugin.md#driver-config

cinder v3 is required
