### ISSUE TITLE
Create lb failed use octavia-ingress-controller

### ISSUE THREAD

**Issue by kongdengyuan** [kubernetes/cloud-provider-openstack#2201]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 

**What happened**:
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: octavia-ingress-controller-config
  namespace: kube-system
data:
  config: |
    cluster-name: octavia-ingress-controller-manger
    openstack:
      auth-url: ${AUTH_URL}
      domain-name:  ${DOMAIN_NAME}
      username:  ${USER}
      #user-id: 
      password:  ${PASSWORD}
      project-id:  ${PROJECT_ID}
      region:  ${REGION}

    octavia:
      subnet-id: 3c0ca8a2-fc35-4e9a-b460-0103424c0f9c
      # floating-network-id: a75e0bf8-9bbe-4ae7-9cd0-e18ca8f08ad3
      floating-network-id: 4abec84b-4ba9-4739-8e44-f45709addbb8
      #provider: amphora

INFO   [2023-04-18T08:42:39Z] creating ingress                              ingress=default/test-octavia-ingress
E0418 08:42:39.579598      11 controller.go:528] failed to create openstack resources for ingress default/test-octavia-ingress: error creating loadbalancer {kube_ingress_octavia-ingress-controller-manger_default_test-octavia-ingress Kubernetes ingress test-octavia-ingress in namespace default from cluster octavia-ingress-controller-manger  3c0ca8a2-fc35-4e9a-b460-0103424c0f9c     <nil>   octavia [] [] []}: Bad request with: [POST https://xxxx/v2.0/lbaas/loadbalancers], error message: {"faultcode": "Client", "faultstring": "Provider 'octavia' is not enabled.", "debuginfo": null}
I0418 08:42:39.579743      11 event.go:285] Event(v1.ObjectReference{Kind:"Ingress", Namespace:"default", Name:"test-octavia-ingress", UID:"bbade83e-da51-4960-adb3-f10dbb34ae3d", APIVersion:"networking.k8s.io/v1", ResourceVersion:"6201960", FieldPath:""}): type: 'Warning' reason: 'Failed' Failed to create openstack resources for ingress default/test-octavia-ingress: error creating loadbalancer {kube_ingress_octavia-ingress-controller-manger_default_test-octavia-ingress Kubernetes ingress test-octavia-ingress in namespace default from cluster octavia-ingress-controller-manger  3c0ca8a2-fc35-4e9a-b460-0103424c0f9c     <nil>   octavia [] [] []}: Bad request with: [POST https://xxxx/v2.0/lbaas/loadbalancers], error message: {"faultcode": "Client", "faultstring": "Provider 'octavia' is not enabled.", "debuginfo": null}

##  Change config.yaml  add provider: amphora still failed

 
INFO   [2023-04-18T08:50:39Z] creating ingress                              ingress=default/test-octavia-ingress
E0418 08:50:40.565434      11 controller.go:528] failed to create openstack resources for ingress default/test-octavia-ingress: error creating loadbalancer {kube_ingress_octavia-ingress-controller-manger_default_test-octavia-ingress Kubernetes ingress test-octavia-ingress in namespace default from cluster octavia-ingress-controller-manger  3c0ca8a2-fc35-4e9a-b460-0103424c0f9c     <nil>   amphora [] [] []}: Bad request with: [POST https://xxxx/v2.0/lbaas/loadbalancers], error message: {"faultcode": "Client", "faultstring": "Provider 'amphora' is not enabled.", "debuginfo": null}
I0418 08:50:40.565520      11 event.go:285] Event(v1.ObjectReference{Kind:"Ingress", Namespace:"default", Name:"test-octavia-ingress", UID:"0553af01-1618-4c5b-8e8a-b74dc1e117b5", APIVersion:"networking.k8s.io/v1", ResourceVersion:"6203077", FieldPath:""}): type: 'Warning' reason: 'Failed' Failed to create openstack resources for ingress default/test-octavia-ingress: error creating loadbalancer {kube_ingress_octavia-ingress-controller-manger_default_test-octavia-ingress Kubernetes ingress test-octavia-ingress in namespace default from cluster octavia-ingress-controller-manger  3c0ca8a2-fc35-4e9a-b460-0103424c0f9c     <nil>   amphora [] [] []}: Bad request with: [POST https://xxxxx/v2.0/lbaas/loadbalancers], error message: {"faultcode": "Client", "faultstring": "Provider 'amphora' is not enabled.", "debuginfo": null}

**What you expected to happen**:
Create ingress + lb success 

**How to reproduce it**:

**Anything else we need to know?**:
company local cloud provider

ingress.yaml 
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: test-octavia-ingress
  annotations:
    kubernetes.io/ingress.class: "openstack"
    octavia.ingress.kubernetes.io/internal: "false"
spec:
  defaultBackend:
    service:
      name: default-http-backend
      port:
        number: 80
  tls:
    - secretName: k8s-tls-secret
  rules:
    - host: test.k8s.com
      http:
        paths:
        - path: /ping
          pathType: Exact
          backend:
            service:
              name: webserver
              port:
                number: 8080

**Environment**:
- openstack-cloud-controller-manager(or other related binary) version:
- OpenStack version: 6.0.0
- Kubernetes: 1.26

**Comment by zetaab** [comment]
like the error says 

> "Provider 'amphora' is not enabled."

default provider is amphora and it seems that your openstack setup does not have amphora enabled.

You need to find out what kind of providers your cloud do have. Does it have octavia either?

**Comment by kongdengyuan** [comment]
Thanks for your quickly response @zetaab 
From cloud provider introduction: 
Load Balancer as a Service (LBaaS)
Load balancers
The load balancer occupies an octavia network port and has an IP address assigned from a subnet. The subnet
has to be selected during the creation process. Afterwards it's not changeable anymore. The choosen subnet is typically an internal one which IP's are not routed to the outside.

I thinks LB is octavia.  
I try to use octavia and ampora both failed.

**Comment by dulek** [comment]
@kongdengyuan: `openstack loadbalancer provider list` should get you a list of supported provider names. You should be able to use one of them.

In general I believe we shouldn't really do this, but instead just leave the provider unset: https://github.com/kubernetes/cloud-provider-openstack/blob/297a3fcb55c3ddd3f9cb4ac1f1bb3208f7f5e3bf/pkg/ingress/controller/openstack/octavia.go#L294-L299

**Comment by kongdengyuan** [comment]
@dulek thanks for your update. 
 openstack loadbalancer provider list
+-------------+---------------------+
| name        | description         |
+-------------+---------------------+
| noop_driver | 'The No-Op driver.' |
| f5          | 'F5 BigIP driver.'  |
| F5Networks  | 'F5 BigIP driver'   |
+-------------+---------------------+

maybe my cloud platform  is not support octavia.

**Comment by mdbooth** [comment]
It has octavia, just not the amphora provider. Presumably you want to specify either `f5` or `F5Networks`, but @dulek can confirm.

**Comment by dulek** [comment]
Yup, looks like only F5 provider is available and I'm guessing that's what it is: https://github.com/sapcc/octavia-f5-provider-driver. At a glance it supports health monitors and L7 policies, so it might actually work with ingress-controller, but you may be the first one to test this.

**Comment by mdbooth** [comment]
@kongdengyuan Does this resolve your issue?

**Comment by kongdengyuan** [comment]
Thanks for your quickly response  @dulek @mdbooth  
I will try .
