### ISSUE TITLE
[Manila-CSI-Plugin] How to prevent plugin to send parameter nfs-shareClient 0.0.0.0/0

### ISSUE THREAD

**Issue by tintin-63** [kubernetes/cloud-provider-openstack#2202]
**Is this a BUG REPORT or FEATURE REQUEST?**:
> /kind feature

**What happened**:
When using Manila-CSI-Plugin NFS, the default behavior is to send nfs-shareClient 0.0.0.0/0 to openstack manila plugin and this creates an access/permission config change in our NFS server storage backend.

**What you expected to happen**:
We would like to know if there is a way to configure Manila-CSI-Plugin storage class to not send any nfs-shareClient list to openstack manila plugin so the manila openstack access-list is empty for the share created by CSI Manila plugin i.e.

Instead of:

host1:~> manila access-list 082f8726-3cd8-47bf-ab38-fce6a81514ad
+--------------------------------------+-------------+-----------+--------------+--------+------------+----------------------------+------------+
| id                                   | access_type | access_to | access_level | state  | access_key | created_at                 | updated_at |
+--------------------------------------+-------------+-----------+--------------+--------+------------+----------------------------+------------+
| 9791bd6d-71aa-449c-aad2-2ad8310dbd2d | ip          | 0.0.0.0/0 | rw           | active | None       | 2023-03-30T05:31:13.000000 | None       |
+--------------------------------------+-------------+-----------+--------------+--------+------------+----------------------------+------------+

We would like to have an empty access-list in openstack for the share created by Manila-CSI-Plugin:

host1:~> manila access-list 082f8726-3cd8-47bf-ab38-fce6a81514ad
+----+-------------+-----------+--------------+-------+------------+------------+------------+
| id | access_type | access_to | access_level | state | access_key | created_at | updated_at |
+----+-------------+-----------+--------------+-------+------------+------------+------------+
+----+-------------+-----------+--------------+-------+------------+------------+------------+

**How to reproduce it**:
N/A

**Anything else we need to know?**:
N/A

**Environment**:
- openstack-cloud-controller-manager(or other related binary) version:
  v1.25.3-5-ae26c257
- OpenStack version:  Kolla
- Others: K8s version v1.25.3

Best Regards

**Comment by gouthampacha** [comment]
Hi @tintin-63, 

What's the use case of doing this? You can [customize "nfsShareClient"](https://github.com/kubernetes/cloud-provider-openstack/blob/master/docs/manila-csi-plugin/using-manila-csi-plugin.md#controller-service-volume-parameters) to match specific node/s. Any reason not to use it at all?

**Comment by kayrus** [comment]
/remove-lifecycle stale

@tintin-63 how are you going to use NFS shares, when they don't have an `access_to`? BTW, are you aware that you can define a custom storage class with `nfs-shareClient: 255.255.255.255/32` and your share won't be accessible?

**Comment by gouthampacha** [comment]
/remove-lifecycle rotten

I think we haven't done this because of lack of time.. but, this issue is still relevant
