### ISSUE TITLE
[cinder-csi-plugin] Cannot pull cinder-csi-plugin image from registry.k8s.io

### ISSUE THREAD

**Issue by amanning9** [kubernetes/cloud-provider-openstack#2206]
/kind bug

**What happened**:
The cinder-csi-plugin image currently fails to pull from registry.k8s.io.

Therefore, applying the latest version of the helm chart (2.27.0) with the default version of this image (1.27.0 at time of writing) is failing.

**What you expected to happen**:
Image to be available at location from helm chart!

**How to reproduce it**:
`docker pull registry.k8s.io/provider-os/cinder-csi-plugin:v1.27.0`

**Anything else we need to know?**:
~~I've tried pulling a number of different versions from registry.k8s.io and as far as I can tell no tags work.~~ v1.26.2 works OK.
The old `docker pull docker.io/k8scloudprovider/cinder-csi-plugin` location does still appear to work, however.

**Comment by mdbooth** [comment]
Looks like we haven't promoted it in https://github.com/kubernetes/k8s.io/blob/main/k8s.gcr.io/images/k8s-staging-provider-os/images.yaml

@zetaab Do you have a PR? Also, I wonder if we should update the release docs to do the image promotion before publishing a release?

**Comment by mdbooth** [comment]
https://github.com/kubernetes/k8s.io/pull/5145

**Comment by amanning9** [comment]
Works for me, thanks very much!
