### ISSUE TITLE
[occm] Reuse Load Balancer by load-balancer-address Annotation

### ISSUE THREAD

**Issue by seanschneeweiss** [kubernetes/cloud-provider-openstack#2207]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind feature

**What happened**:

As a user I would like to re-use load balancers for services by specifying the floating IP to not rely on the load balancer id - as it changes on recreation.

Support for multiple services using a single load balancer was added in #1648 ([docs](https://github.com/kubernetes/cloud-provider-openstack/blob/master/docs/openstack-cloud-controller-manager/expose-applications-using-loadbalancer-type-service.md#sharing-load-balancer-with-multiple-services)).
Reusing a load balancer works by adding the annotation 
`loadbalancer.openstack.org/load-balancer-id` 
to a new service.

The PR #2097 added the annotation
`loadbalancer.openstack.org/load-balancer-address` 
to expose the external IP address used by the load balancer.

Upon recreation of a load balancer (e.g. maintenance, failure) the load balancer ID might change.
That could cause a reconciliation failure when services defined the annotation `loadbalancer.openstack.org/load-balancer-id`  with a non-existing ID.
(I haven't tested the behavior yet, just assuming.)

Would you find it feasible to also allow reusing load balancers by using the floating IP, i.e. `loadbalancer.openstack.org/load-balancer-address` annotation?

**What you expected to happen**:

Users can create a second service and set the `loadbalancer.openstack.org/load-balancer-address` annotation to reuse an existing load balancer.
This should have the same behavior as defining `loadbalancer.openstack.org/load-balancer-id`.

**How to reproduce it**:

**Anything else we need to know?**:

Is there any reason why we should favor the load balancer ID over the address?

**Environment**:
- openstack-cloud-controller-manager(or other related binary) version: v1.27.0
- OpenStack version: Ussuri 3.14

<sub>Sean Schneeweiss <sean.schneeweiss@mercedes-benz.com>, Mercedes-Benz Tech Innovation GmbH, [Provider Information](https://github.com/mercedes-benz/foss/blob/master/PROVIDER_INFORMATION.md)</sub>

**Comment by mdbooth** [comment]
@dulek An actual user for shared LBs 👆

**Comment by dulek** [comment]
> @dulek An actual user for shared LBs point_up_2

Yeah, I'm thinking about this for an hour now. ;)

**Comment by zetaab** [comment]
load-balancer-id will always change, if the lb is recreated somehow. LoadBalancer Address can be problem as well, if the floating ips is deleted together with loadbalancer. In that case it might be that you cannot reserve the same ip address anymore. (in many cases we are using keep-floating-ip annotation in lbs)

**Comment by seanschneeweiss** [comment]
The initial motivation for us to provide shared load balancers was to save on floating IP addresses. In a classic ipv4 environment, IPs can be rare.
For cloud providers such as OpenStack by OVH, it might be cost saving to re-use floating IPs and load balancers. 
Sharing load balancers from a provider view safes resources for Amphora VMs - this might be interesting in smaller OpenStack installations or even very large ones.

I don't really see the risk of accidentally exposing a service on a FIP that we were not supposed to - especially, if specifically defining the floating IP in the service.

Another reason for sharing load balancers by defining the floating IP: deprecation of service.spec.loadBalancerIP
https://github.com/kubernetes/kubernetes/blob/bb878608686a6276cefec3f51bee5d79b0c8c393/staging/src/k8s.io/api/core/v1/types.go#L4713-L4721
```go
        // Only applies to Service Type: LoadBalancer.
	// This feature depends on whether the underlying cloud-provider supports specifying
	// the loadBalancerIP when a load balancer is created.
	// This field will be ignored if the cloud-provider does not support the feature.
	// Deprecated: This field was under-specified and its meaning varies across implementations.
	// Using it is non-portable and it may not support dual-stack.
	// Users are encouraged to use implementation-specific annotations when available.
	// +optional
	LoadBalancerIP string `json:"loadBalancerIP,omitempty" protobuf:"bytes,8,opt,name=loadBalancerIP"`
```

cloud-provider-openstack anyway requires some work on the deprecation of `service.spec.loadBalancerIP` and should favor `implementation-specific annotations`. So we could match that requirement with ` loadbalancer.openstack.org/load-balancer-address`.

**Comment by seanschneeweiss** [comment]
@zetaab 
Agree on 
> In that case it might be that you cannot reserve the same ip address anymore. (in many cases we are using keep-floating-ip annotation in lbs)

We set `keep-floating-ip` annotation by default to `true` and release unused FIPs after a 14 day grace period.
However, upstream OCCM defaults to `false` and this could of course lead to failed reconciliations due to FIP allocation.

From our experience at least we can say, that sharing by load balancer address / floating IP was proven by our users to be an acceptable behavior for the last three years.
Surely there is room for improvement, and we should think about another annotation "key" that we can use for identifying shared load balancers. Something independent of the infrastructure.

**Comment by seanschneeweiss** [comment]
Maybe my assumption is wrong. `loadbalancer.openstack.org/load-balancer-address` refers to either an IP address (floating IP) or hostname.
I guess there are use cases, where the hostname is re-used across multiple load balancers making this annotation unavailable for load balancer sharing. So for this to work we have to introduce a new annotation, e.g. `loadbalancer.openstack.org/load-balancer-ip`.
Or is it feasible to use `loadbalancer.openstack.org/load-balancer-address` to identify which services share a load balancer?

I guess we should decide which identifier to use. I either prefer IP address or a completely independent identifier.
As `svc.spec.loadBalancerIP` is deprecated, we anyway need a replacement for specifying the floating IP.
So my suggestions would be to go with `loadbalancer.openstack.org/load-balancer-ip`?

Any thoughts?
