### ISSUE TITLE
[cinder-csi-plugin] - panic: version string "openstack-cinder-csi-2.27.0" doesn't match expected regular expression: "^v(\d+\.\d+\.\d+)"

### ISSUE THREAD

**Issue by andrebassi** [kubernetes/cloud-provider-openstack#2209]
Is this a BUG REPORT or FEATURE REQUEST?:

/kind bug

What happened:
When we installed the latest version of the manifests folder for cinder from that repository, i get error:
panic: version string "openstack-cinder-csi-2.27.0" doesn't match expected regular expression: "^v(\d+\.\d+\.\d+)"

goroutine 1 [running]:
k8s.io/component-base/metrics.parseVersion({{0x0, 0x0}, {0x0, 0x0}, {0x1a09cf0, 0x1b}, {0x17b95e8, 0xb}, {0x0, 0x0}, ...})
	k8s.io/component-base@v0.27.1/metrics/version_parser.go:47 +0x274
k8s.io/component-base/metrics.newKubeRegistry({{0x0, 0x0}, {0x0, 0x0}, {0x1a09cf0, 0x1b}, {0x17b95e8, 0xb}, {0x0, 0x0}, ...})
	k8s.io/component-base@v0.27.1/metrics/registry.go:363 +0x119
k8s.io/component-base/metrics.NewKubeRegistry()
	k8s.io/component-base@v0.27.1/metrics/registry.go:377 +0x78
k8s.io/component-base/metrics/legacyregistry.init()
	k8s.io/component-base@v0.27.1/metrics/legacyregistry/registry.go:30 +0x1d

What you expected to happen:
That the container with the cinder plugin worked correctly.
The version being compared is 2.27.0, but isn't it 1.27.0?

How to reproduce it:
Apply the recently updated manifests from the cinder-csi manifests folder in that repository.

Anything else we need to know?:
The error starts after changing the registry of the image

Environment:
K8s version v1.22.3

Best Regards,

Bassi

**Comment by mdbooth** [comment]
The logs from the image build are in https://storage.googleapis.com/kubernetes-jenkins/logs/cloud-provider-openstack-push-images/1648412422563696640/artifacts/build.log

We can see:
```
+ make push-multiarch-images REGISTRY=gcr.io/k8s-staging-provider-os VERSION=openstack-cinder-csi-2.27.0
docker buildx build --output type=registry \
	--build-arg VERSION=openstack-cinder-csi-2.27.0 \
	--tag gcr.io/k8s-staging-provider-os/openstack-cloud-controller-manager:openstack-cinder-csi-2.27.0 \
	--platform linux/amd64,linux/arm,linux/arm64,linux/ppc64le,linux/s390x \
	--target openstack-cloud-controller-manager \
	.
```

That's presumably the immediate cause of this issue. Still looking into why this might have come about.

**Comment by mdbooth** [comment]
Image pushing job was triggered by this branch definition:
https://github.com/kubernetes/test-infra/blob/d3dda8ef3a00e3cdb987188c45c547dd178c4f4d/config/jobs/image-pushing/k8s-staging-provider-os.yaml#L10-L18

```yaml
      branches:
        # For publishing canary images.
        - ^master$
        - ^release-
        # For publishing tagged images. Those will only get built once, i.e.
        # existing images are not getting overwritten. A new tag must be set to
        # trigger another image build. Images are only built for tags that follow
        # the semver format (regex from https://semver.org/#is-there-a-suggested-regular-expression-regex-to-check-a-semver-string).
        - ^v(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(?:-((?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\.(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\+([0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*))?$
```

**Comment by mdbooth** [comment]
We can see this commit has multiple tags:

```
> git show v1.27.0
commit 309df4c792b9c1817df1f82077d51c73eb4e26e3 (tag: v1.27.0, tag: show, tag: openstack-manila-csi-2.27.0, tag: openstack-cloud-controller-manager-2.27.0, tag: openstack-cinder-csi-2.27.0, origin/release-1.27)
Merge: 8e9d2dfcc 3effc85d1
Author: Jesse Haka <haka.jesse@gmail.com>
Date:   Tue Apr 18 22:44:31 2023 +0300

    Merge pull request #2203 from zetaab/bumpbversions

    update tags
```

Although the prow job should only have been triggered by the v1.27.0 tag, I wonder if something further down the stack picked a different one when populating [_GIT_TAG in cloudbuild.yaml](https://github.com/kubernetes/cloud-provider-openstack/blob/e8d89e587d20de620944484151efb021ee51688a/cloudbuild.yaml#L35-L37).

**Comment by mdbooth** [comment]
That will be it. The prow job executes gcr.io/k8s-staging-test-infra/image-builder, which does this: https://github.com/kubernetes/test-infra/blob/d3dda8ef3a00e3cdb987188c45c547dd178c4f4d/images/builder/main.go#L94-L107
```go
func getVersion() (string, error) {
	cmd := exec.Command("git", "describe", "--tags", "--always", "--dirty")
	output, err := cmd.Output()
	if err != nil {
		return "", err
	}
	validTagRegexp, err := regexp.Compile("[^-_.a-zA-Z0-9]+")
	if err != nil {
		return "", err
	}
	sanitizedOutput := validTagRegexp.ReplaceAllString(string(output), "")
	t := time.Now().Format("20060102")
	return fmt.Sprintf("v%s-%s", t, sanitizedOutput), nil
}
```

Running this locally suggests that this is the problem:
```
(master)> git worktree add ../cloud-provider-openstack-v1.27.0 v1.27.0
(master)> cd ../cloud-provider-openstack-v1.27.0/
((openstack-cinder-csi-2.27.0))> git describe --tags --always --dirty
openstack-cinder-csi-2.27.0
```

**Comment by mdbooth** [comment]
@zetaab I think we're going to have to respin this release with a new tag. The workaround for the above will be to *only* tag the commit with `v1.27.1` so there's no possibility for error.

Additionally we should probably take this to the test-infra folks to see if this is a known thing so we can avoid it in the future.

**Comment by mdbooth** [comment]
I've asked the question in #testing-ops: https://kubernetes.slack.com/archives/C7J9RP96G/p1682094038500629

**Comment by mdbooth** [comment]
Update: we think the additional tags were added automatically by https://github.com/helm/chart-releaser which is called by https://github.com/kubernetes/cloud-provider-openstack/blob/e8d89e587d20de620944484151efb021ee51688a/.github/workflows/release.yaml#L23-L26

**Comment by zetaab** [comment]
yeah the helm/chart-releaser-action is the problem. If the same commit contains multiple tags (one made by us manually, and others made by helm/chart-releaser-action, we do have issue). 

The process currently goes something like:

1. I did `git tag v1.27.0 && git push` manually
2. it will trigger github actions helm/chart-releaser-action to use same tag
3. chart-releaser-action makes new tag for the same latest commit
4. cloudbuild will use cinder-csi-2.27.0 tag instead of v1.27.0

![image](https://user-images.githubusercontent.com/22482503/233697146-a2fcf40d-79d3-4be0-96f0-3e3599ee2810.png)

```
 cloud-provider-openstack [master] % git checkout v1.27.0
Note: switching to 'v1.27.0'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by switching back to a branch.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -c with the switch command. Example:

  git switch -c <new-branch-name>

Or undo this operation with:

  git switch -

Turn off this advice by setting config variable advice.detachedHead to false

HEAD is now at 309df4c7 Merge pull request #2203 from zetaab/bumpbversions
 cloud-provider-openstack [tags/openstack-cinder-csi-2.27.0] % git describe --tags --always --dirty
openstack-cinder-csi-2.27.0
```

that is where the tags is currently coming from. No idea how we could fix this with cloudbuild WITHOUT making the helm releases to build manually.

The process could go that we will call helm chart releaser manually after the cloudbuild is executed

**Comment by zetaab** [comment]
seems that #2211 did not solve this, new try in https://github.com/kubernetes/cloud-provider-openstack/pull/2214

**Comment by zetaab** [comment]
@andrebassi 1.27.1 is out, could you try does it help solve this issue?
