### ISSUE TITLE
Volume gets attached to wrong VM when behind proxy cinder-csi-plugin

### ISSUE THREAD

**Issue by lullen** [kubernetes/cloud-provider-openstack#2217]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug

**What happened**:
I created a volume and tried to attach it to one pod but it tried to attach it to a machine in another project that acts as a proxy for all our outgoing requests. I don't know how it works behind the scene but since the request to the openstack api comes from our proxy, I guess that it thinks that it's the one doing the request. So question is how I can tell the openstack api that there is an proxy involved?

I get the folllowing error:
`AttachVolume.Attach failed for volume "pvc-ef7afed3-07ae-4478-b995-83240963ed97" : rpc error: code = NotFound desc = [ControllerPublishVolume] Instance 67cf04ca-9b1a-4c4b-85e0-33f0e9dc5d9b not found`

**What you expected to happen**:
Disk to get attached to the machine requesting the volume

**Environment**:
- openstack-cloud-controller-manager(or other related binary) version: 1.6.2

**Comment by jichenjc** [comment]
>>> So question is how I can tell the openstack api that there is an proxy involved?

openstack API don't know which proxy VM it's work on, it's only operate on VM that it told to work on

**Comment by lullen** [comment]
How does it get told which VM to work on? I tried to look in the code but couldn't find it out.

**Comment by jichenjc** [comment]
>>>How does it get told which VM to work on? I tried to look in the code but couldn't find it out.

https://github.com/kubernetes/cloud-provider-openstack/blob/master/pkg/csi/cinder/controllerserver.go#L211
volume attached here, and request's NodeID comes from the pod located node ..

**Comment by lullen** [comment]
I found out what the issue was.
I called `curl -v http://169.254.169.254/openstack/2020-10-14/meta_data.json`
and got the following response, fortigate is our proxy.
```
{"uuid": "67cf04ca-9b1a-4c4b-85e0-33f0e9dc5d9b", "hostname": "fortigate.openstacklocal", "name": "fortigate", "launch_index": 0, "availability_zone": "nova"}
```
When I added the hardcoded metadata service ip (169.254.169.254) to the no_proxy env variable and then it returned the correct server

**Comment by mdbooth** [comment]
/reopen

I wonder if we should explicitly ignore proxy configurations in metadata requests. They're only going to result in hair loss.

**Comment by mdbooth** [comment]
Another thing is that we should avoid metadata requests where possible, and I think it's possible in this case. At the very least we know that instance id isn't going to change during a single invocation of the cinder CSI driver, so we could cache it on startup. If we can also initially get it from Node.Spec.ProviderID object instead of OpenStack that would be even better.

**Comment by mdbooth** [comment]
@stephenfin Am I right in thinking that pulling back all metadata (i.e. [`http://169.254.169.254/openstack/%s/meta_data.json`](https://github.com/kubernetes/cloud-provider-openstack/blob/e8d89e587d20de620944484151efb021ee51688a/pkg/util/metadata/metadata.go#L42-L43)) is considerably more expensive for Nova than pulling only the required metadata when only a single value is needed? That is, does Nova itself only construct the single value, or is it also constructing everything before throwing away the bits it doesn't need?

**Comment by pierreprinetti** [comment]
I would be interested in looking into this battery of problems.

If I understand correctly, in this thread these problems have been mentioned:
* calls to the Metadata service should not honour proxy settings (and in particular, HTTP_PROXY env vars)
* calls to the Metadata service to fetch the instance ID could be memoized, as Instance ID is not expected to change
* calls to the Metadata service to fetch the instance ID could be scoped to only fetch the instance ID, in the expectation that a narrowly-scoped call is less expensive for the backend.

Is there any related topic that I have failed to parse?

---

Incidentally, I happen to be a maintainer of the [Gophercloud](https://github.com/gophercloud/gophercloud) library. Do you think that Gophercloud could/should provide an API for interrogating the Nova metadata? If bypassing proxy settings for Metadata calls is a universally valid solution, then we could do that to Gophercloud.

**Comment by dulek** [comment]
> I would be interested in looking into this battery of problems.
> 
> If I understand correctly, in this thread these problems have been mentioned:
> 
> * calls to the Metadata service should not honour proxy settings (and in particular, HTTP_PROXY env vars)
> * calls to the Metadata service to fetch the instance ID could be memoized, as Instance ID is not expected to change
> * calls to the Metadata service to fetch the instance ID could be scoped to only fetch the instance ID, in the expectation that a narrowly-scoped call is less expensive for the backend.
> 
> Is there any related topic that I have failed to parse?

I think Matt's suggestion to defer to Node object when getting this info makes sense too.

> Incidentally, I happen to be a maintainer of the [Gophercloud](https://github.com/gophercloud/gophercloud) library. Do you think that Gophercloud could/should provide an API for interrogating the Nova metadata? If bypassing proxy settings for Metadata calls is a universally valid solution, then we could do that to Gophercloud.

**Comment by mdbooth** [comment]
@pierreprinetti I do think this would be a good fit for gophercloud now you've said it, or at least a gophercloud-adjacent library given that it's a different API. Probably not very complicated but it could collect good practise for accessing the metadata service, e.g. ignoring proxy settings.

Depending on prioritisation of this issue, I guess we could wait for that in CPO?

**Comment by stephenfin** [comment]
> Incidentally, I happen to be a maintainer of the [Gophercloud](https://github.com/gophercloud/gophercloud) library. Do you think that Gophercloud could/should provide an API for interrogating the Nova metadata? If bypassing proxy settings for Metadata calls is a universally valid solution, then we could do that to Gophercloud.

I wouldn't personally put this in `openstacksdk` and I don't think it belongs in Gophercloud. The metadata service isn't really an API: it's a link-local address and therefore only accessible from inside the guest itself and, as an API, it has entirely different versioning constraints from other APIs (including Nova's API). A separate library in the gophercloud organization would make far more sense to me.

With that said, I see that the AWS Go library [includes support for the EC2 metadata service](https://docs.aws.amazon.com/sdk-for-go/api/aws/ec2metadata/) so my suggestions are not the final word on the matter.

**Comment by stephenfin** [comment]
> @stephenfin Am I right in thinking that pulling back all metadata (i.e. [`http://169.254.169.254/openstack/%s/meta_data.json`](https://github.com/kubernetes/cloud-provider-openstack/blob/e8d89e587d20de620944484151efb021ee51688a/pkg/util/metadata/metadata.go#L42-L43)) is considerably more expensive for Nova than pulling only the required metadata when only a single value is needed? That is, does Nova itself only construct the single value, or is it also constructing everything before throwing away the bits it doesn't need?

afaik, there's no way to pull back a single bit of data, at least not using the `/openstack` versions of the metadata service. The `/ec2` version do allow you do this but nova [constructs the whole metadata response in advance](https://github.com/openstack/nova/blob/27.0.0/nova/api/metadata/base.py#L307) so it's no advantage.

**Comment by pierreprinetti** [comment]
@stephenfin Thank you as always for your insights.

WRT Gophercloud: it may be a good idea to implement that separately. I had thought about gophercloud/utils as a staging step, but indeed a new repo also makes sense, since that's something special that will only be called from inside a cluster.

Anyway, I will code a solution to the main issue reported here (proxy bypass) right inside this repository, to allow for backports.

**Comment by jichenjc** [comment]
>>>calls to the Metadata service to fetch the instance ID could be memoized, as Instance ID is not expected to change
calls to the Metadata service to fetch tthe instance ID could be scoped to only fetch the instance ID, in the expectation that a narrowly-scoped call is less expensive for the backend.

@mdbooth seems we only focus on proxy settings in this issue/PR, should we open a new one for enhancement to track?

**Comment by pierreprinetti** [comment]
I have opened https://github.com/kubernetes/cloud-provider-openstack/issues/2224 to track the optimisation opportunity around redundant calls to the Nova metadata service.

Our resident expert @stephenfin ruled out the opportunity of reducing the scope of the call to the service itself.
