### ISSUE TITLE
[octavia-ingress-controller] timeout too low when creating LBs

### ISSUE THREAD

**Issue by sorrison** [kubernetes/cloud-provider-openstack#2222]
/kind bug

**What happened**:
When creating an ingress it fails as LB is in PENDING_CREATE status, this times out after I think 154 seconds based on 
19 attempts increasing wait by factor of 1.2 starting at 1 second. In our cloud a load balancer can take around 5 minutes sometimes to provision.

**What you expected to happen**:
The timeout needs to allow for envs that take longer for LBs to provision

**How to reproduce it**:
Create an ingress in an openstack env when LBs are slower to create

**Anything else we need to know?**:

**Environment**:
Using octavia Zed

**Comment by jichenjc** [comment]
@sorrison do you want to submit a PR for this?

**Comment by jichenjc** [comment]
>>>waitLoadbalancerActiveSteps = 19
	waitLoadbalancerActiveSteps = 23

seems this value need code change, @dulek do you think we make it a config variable in configmap will help in the future ?
e.g different user might have different env so this value may vary?

**Comment by mdbooth** [comment]
The other problem in this code is that it's blocking[^1].

[^1]: https://github.com/openshift/cloud-provider-openstack/blob/0eacab836b290551a6e058f7c6adb55747f1b591/pkg/ingress/controller/openstack/octavia.go#L311-L312

This ties up an entire thread just waiting for a single LB to be created. Ideally we would not wait here and instead return from the reconciler and wait to be called again. This would allow LBs to be created in parallel. This would also mean there would be no good reason we couldn't wait forever, as long as we have exponential backoff between retries. We'd probably still want a configurable hard ceiling on that, though.
