### ISSUE TITLE
[octavia-ingress-controller] make timeout value configuable

### ISSUE THREAD

**Issue by jichenjc** [kubernetes/cloud-provider-openstack#2229]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
> /kind bug
> /kind feature

**What happened**:
see https://github.com/kubernetes/cloud-provider-openstack/issues/2222#issuecomment-1530756259

**What you expected to happen**:

**How to reproduce it**:

**Anything else we need to know?**:

**Environment**:
- openstack-cloud-controller-manager(or other related binary) version:
- OpenStack version:
- Others:

**Comment by jichenjc** [comment]
1st follow up of https://github.com/kubernetes/cloud-provider-openstack/issues/2222

**Comment by dulek** [comment]
Looks like solved by #2235?

**Comment by jichenjc** [comment]
yes, it's solved
