### ISSUE TITLE
[octavia-ingress-controller] LB creation is blocking

### ISSUE THREAD

**Issue by jichenjc** [kubernetes/cloud-provider-openstack#2230]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
> /kind bug
> /kind feature

**What happened**:

https://github.com/kubernetes/cloud-provider-openstack/issues/2222#issuecomment-1531372274

@mdbooth FYI

**What you expected to happen**:

**How to reproduce it**:

**Anything else we need to know?**:

**Environment**:
- openstack-cloud-controller-manager(or other related binary) version:
- OpenStack version:
- Others:

**Comment by mdbooth** [comment]
/retitle [octavia-ingress-controller] LB creation is blocking

**Comment by dulek** [comment]
/remove-lifecycle stale

This is still a valid observation. It would however require us to spearhead changes to the LoadBalancer interface.
