### ISSUE TITLE
 [occm] Helm Template double Annotation

### ISSUE THREAD

**Issue by NicoJDE** [kubernetes/cloud-provider-openstack#2231]
**Is this a BUG REPORT or FEATURE REQUEST?**:

 /kind bug

**What happened**:

When i try to install the Helm Chart with Flux i got following Error:  

`✗ HelmRelease reconciliation failed: Helm install failed: error while running post render on files: map[string]interface {}(nil): yaml: unmarshal errors:
  line 34: mapping key "annotations" already defined at line 26`

This Errors occurs because in the Deamonset Template the Annotations is doubled. 

**Environment**:
- Helm Chart Version: 0.27.1

**Comment by simonostendorf** [comment]
The problem is this line https://github.com/kubernetes/cloud-provider-openstack/blob/master/charts/openstack-cloud-controller-manager/templates/daemonset.yaml#L24. That was edited in this PR https://github.com/kubernetes/cloud-provider-openstack/pull/2079.

**Comment by simonostendorf** [comment]
I will try to fix this soon and start a PR.
