### ISSUE TITLE
[Octavia-ingress-controller] CI not exist?

### ISSUE THREAD

**Issue by jichenjc** [kubernetes/cloud-provider-openstack#2247]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
> /kind bug
/kind feature

**What happened**:

seems no CI for ingress controller? no e2e for https://github.com/kubernetes/cloud-provider-openstack/pull/2246

checked original CI and still not find it , so not sure someone early than me know the history 
https://github.com/theopenlab/openlab-zuul-jobs/tree/master/playbooks

@dulek @mdbooth FYI

**What you expected to happen**:

**How to reproduce it**:

**Anything else we need to know?**:

**Environment**:
- openstack-cloud-controller-manager(or other related binary) version:
- OpenStack version:
- Others:

**Comment by jichenjc** [comment]
we have tests/e2e/cloudprovider/test-lb-service.sh file but I think it's for OCCM/LB only test

**Comment by dulek** [comment]
> we have tests/e2e/cloudprovider/test-lb-service.sh file but I think it's for OCCM/LB only test

Indeed it seems so.

**Comment by dulek** [comment]
/remove-lifecycle stale

Yes, we're still missing a CI here.
