### ISSUE TITLE
[occm]: CPO components version is always empty

### ISSUE THREAD

**Issue by kayrus** [kubernetes/cloud-provider-openstack#2251]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:

The `cloud-provider-openstack/pkg/version` package `Version` var is not maintained during the build. However it's widely used by OCCM components.

**What you expected to happen**:

The `Version` must be maintained:

```
$ ./manila-csi-plugin --fwdendpoint a --nodeid b --share-protocol-selector NFS 2>&1 | grep version
I0522 13:18:26.916284   37086 driver.go:128] Driver version: 0.9.0@v1.27.0-alpha.0-38-g0fee9d61
I0522 13:18:26.916288   37086 driver.go:129] CSI spec version: 1.2.0
```

**How to reproduce it**:

```sh
make build
$ ./manila-csi-plugin --fwdendpoint a --nodeid b --share-protocol-selector NFS 2>&1 | grep version
I0522 12:55:39.349141   32934 driver.go:128] Driver version: 0.9.0@
I0522 12:55:39.349162   32934 driver.go:129] CSI spec version: 1.2.0
```

**Environment**:
- openstack-cloud-controller-manager(or other related binary) version: n/a
- OpenStack version: n/a
- Others: n/a

**Comment by mdbooth** [comment]
@zetaab This would also be an argument for fixing the tag detection in the cloudbuild.
