### ISSUE TITLE
[occm] Wait for ACTIVE load balancer, when updating health monitors

### ISSUE THREAD

**Issue by seanschneeweiss** [kubernetes/cloud-provider-openstack#2267]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:

Load Balancer reconciliation doesn't wait for load balancer to be ACTIVE when updating the health monitor.

**What you expected to happen**:

When creating or deleting health monitors, we wait for the load balancer to show a provisioning status ACTIVE:
`WaitActiveAndGetLoadBalancer`
https://github.com/kubernetes/cloud-provider-openstack/blob/fd113d2b1d8f5b578ec84c9a9681a7f71ff48fcc/pkg/util/openstack/loadbalancer.go#L681-L709

For the update case, this seems to be missing:
https://github.com/kubernetes/cloud-provider-openstack/blob/fd113d2b1d8f5b578ec84c9a9681a7f71ff48fcc/pkg/util/openstack/loadbalancer.go#L670-L679

**How to reproduce it**:

**Anything else we need to know?**:

Would you consider this a bug?

**Environment**:
- openstack-cloud-controller-manager(or other related binary) version: v1.26.2

<sub>Sean Schneeweiss <sean.schneeweiss@mercedes-benz.com>, Mercedes-Benz Tech Innovation GmbH, [Provider Information](https://github.com/mercedes-benz/foss/blob/master/PROVIDER_INFORMATION.md)</sub>

**Comment by dulek** [comment]
Okay, so this may affect a situation when the health monitor is updated and then immediately the listener is deleted here: https://github.com/kubernetes/cloud-provider-openstack/blob/06f3d8cd62e16001626bb9aa710d9399606b3c7f/pkg/openstack/loadbalancer.go#L1991

It's minor (will fix itself on another reconciliation), but a bug nevertheless.
