### ISSUE TITLE
Can not build image csi, cloud controller manager

### ISSUE THREAD

**Issue by tranthang2404** [kubernetes/cloud-provider-openstack#2269]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
> /kind bug
> /kind feature

**What happened**:

I cann't build image from makefile, someone can help me to write down here some commands to build this images 

**What you expected to happen**:

**How to reproduce it**:

**Anything else we need to know?**:

**Environment**:
- openstack-cloud-controller-manager(or other related binary) version:
- OpenStack version:
- Others:

**Comment by tranthang2404** [comment]
oh sorry, I can build it with command: `make build-local-image-cinder-csi-plugin` , readme file is out date

**Comment by mdbooth** [comment]
Docs bugs are still bugs! We should fix that. We should review image building make commands in:
* docs/cinder-csi-plugin/using-cinder-csi-plugin.md
* docs/developers-guide.md
* docs/manila-csi-plugin/developers-csi-manila.md

/reopen
/assign

**Comment by FavourEva** [comment]
@mdbooth I'll be taking over of this issue if that's alright with you!

**Comment by FavourEva** [comment]
@kayrus @jichenjc @dulek To address the documentation issue, when attempting to build the single Docker image (cinder-csi-plugin), the command does not works as expected from the Makefile. However, when attempting to build all the images at once, the build process runs without errors, but the Docker images don't appear in the Docker runtime. Although I can locate the executable files, I'm unable to test or run the application. I'm currently unsure about the next steps or how to proceed. Please do you have any suggestion on how I can go about this?

**Comment by dulek** [comment]
@FavourEva: `make build-local-image-cinder-csi-plugin` works on my env and I can see the image, see below. `make image-cinder-csi-plugin` that is in the docs is outdated. The point of this task is to update image build commands to the ones that work.

```
REPOSITORY                                             TAG                              IMAGE ID       CREATED          SIZE
registry.k8s.io/provider-os/cinder-csi-plugin          v1.27.0-alpha.0-119-g23291097d   8bdb70cc00fd   24 seconds ago   61.9MB
```

**Comment by FavourEva** [comment]
> make build-local-image-cinder-csi-plugin
It works on mine as well now. Thanks @dulek 
``` ubuntu@devstack2:~/cloud-provider-openstack$ sudo docker images
REPOSITORY                                      TAG       IMAGE ID       CREATED          SIZE
registry.k8s.io/provider-os/cinder-csi-plugin   1.27.0    b6d0ee34cd53   15 seconds ago   61.9MB ```
