### ISSUE TITLE
[cinder-csi-plugin] Volume list pagination problem 

### ISSUE THREAD

**Issue by vhurtevent** [kubernetes/cloud-provider-openstack#2295]
/kind bug

**What happened**:

In an OpenStack project with more than 1000 volumes provisioned and managed by cinder-csi-plugin, csi-attacher can't get a complete list of volumes.  The volumes listed over the 1000th item, which seems to be the Cinder limit of entries, are not retrieved using pagination.
With volume attachments missing, csi-attacher logs about VolumeAttachment mismatch between VA inside the Kubernetes cluster and volumes attachments from ListVolumes call (Cinder API /v3/<project_id>/volumes/detail).

The log message is like :

```
W0712 20:27:50.523603       1 csi_handler.go:181] VA csi-680a07f59b9c51a6f20c9cf6953cc2afc817a063c5c9c63103a25e462f3098d6 for volume f478bf0e-c12f-4f74-b6af-263e69fd2bc6 has attached status true but actual state false. Adding back to VA queue for forced reprocessing
```

In projects with several thousands of volumes, there are lots of VA mismatches, logs are very heavy and we suspect the VA queue for reprocessing is consuming too much requests to Kube API and Cinder API.

Cinder API ends its JSON answer with next item marker to start with for the next query. Although cinder-csi-plugin seems to implement pagination (https://github.com/kubernetes/cloud-provider-openstack/blob/master/pkg/csi/cinder/openstack/openstack_volumes.go#L79), only the first 1000 items are successfully retrieved from Cinder API.

**What you expected to happen**:

The Cinder API pagination is correctly used by cinder-csi-plugin and csi-attacher gets complete volume attachments list when calling ListVolumes.

**How to reproduce it**:

I searched in : 
- cinder-csi-plugin repo
- external-attacher repo
- and Go CSI lib : https://github.com/container-storage-interface/spec/tree/master/lib/go

how to set max_entries to lower than 1000 to test pagination and reproduce in a small setup, without success.

**Environment**:
- Kubernetes : 1.21
- CSI Cinder Plugin 1.27.1
- OpenStack version: RedHat OpenStack 16.2

**Comment by kayrus** [comment]
@vhurtevent can you run controller with `--v=10` and collect some API debug logs? I wonder whether this is a Cinder or a Gophercloud issue.

**Comment by kayrus** [comment]
`ListVolumes` is called from the https://github.com/rexray/gocsi `csc` tool, e.g. https://github.com/c445/cloud-provider-openstack/blob/master/docs/using-cinder-csi-plugin.md#list-volumes

Doesn't look like your issue is caused by bad pagination, unless you have a custom environment that uses `csc`.

**Comment by jichenjc** [comment]
csc is a tool, but not used in cinder-csi-plugin now
so do you have a full log of such query? CPO CSI seems just use the cinder API .. doubt whether some edge case not handle well ..so more logs will be helpful as @kayrus mentioned..

**Comment by vhurtevent** [comment]
Hi @jichenjc and @kayrus 

as I understand, CSC tool is not used, it's gophercloud and I don't find way to specify max_entries which could help to reproduce in a smaller setup.

I tried to prepare debug logs (attached) without confidential information.

In cinder-csi-plugin logs from its startup : 
- line 227 : GRPC call: /csi.v1.Controller/ListVolumes
- line 229 : OpenStack Request URL: GET https://openstack-api-url:13776/v3/project-uuid/volumes/detail
then a long JSON response with exactly 1000 items (the OpenStack project holds 1253 volumes at the time of debug)
it ends line 44348 with the next page URL with a marker containing the last (1000th) volume listed.

```
I0713 06:47:37.683880       1 client.go:128]   "volumes_links": [
I0713 06:47:37.683881       1 client.go:128]     {
I0713 06:47:37.683883       1 client.go:128]       "href": "https://openstack-api-url:13776/v3/project-uuid/volumes/detail?marker=a30c3053-b146-4acb-9280-fdc5732f2058",
I0713 06:47:37.683885       1 client.go:128]       "rel": "next"
I0713 06:47:37.683888       1 client.go:128]     }
I0713 06:47:37.683891       1 client.go:128]   ]
```
The ListVolumes requests ends line 44355 with the GRPC response to csi-attacher without retrieving the remaining volumes from the marker returned by Cinder API.

If I look to csi-attacher at the same time, when receiving the GRPC response to ListVolumes call, there is also this message : 

```
connection.go:201] GRPC error: <nil>
```

I tried to understand how pagination is done, but it's unclear for me how it's done between gophercloud, cinder-csi-plugin and csi-attacher, but I'm wondering if cinder-csi-plugin shouldn't return the next token (marker) to trigger a new GRPC ListVolume call from this marker.

Or cinder-csi-plugin doesn't paginate itself correctly to get the complete volume list.


- Gophercloud : https://github.com/gophercloud/gophercloud/blob/master/openstack/blockstorage/v3/volumes/requests.go#L159
- Cinder-csi-plugin : https://github.com/kubernetes/cloud-provider-openstack/blob/master/pkg/csi/cinder/openstack/openstack_volumes.go#L85
- External-attacher : https://github.com/kubernetes-csi/external-attacher/blob/218282a8805bd741dfe75b0be83fe84ff7bf18ef/pkg/attacher/lister.go#L39
- CSI Golang lib : https://github.com/container-storage
[cinder-csi-plugin.log](https://github.com/kubernetes/cloud-provider-openstack/files/12037693/cinder-csi-plugin.log)
-interface/spec/blob/b01039c563108173c6743aa1410ec11fde7c24fe/lib/go/csi/csi.pb.go#L2440

**Comment by dulek** [comment]
There has to be a bug in either gophercloud or our implementation of pagination here. First of all I'm pretty sure `EachPage()` shouldn't be used. We don't want gophercloud to go over all the pages in increments of 1000. We want just one page of 1000 elements.

[1] https://github.com/kubernetes/cloud-provider-openstack/blob/master/pkg/csi/cinder/openstack/openstack_volumes.go#L85-L107

**Comment by vhurtevent** [comment]
Hi @dulek, if I understand pagination is implemented a several levels, resulting in only one and first page results to csi-attacher ?

**Comment by dulek** [comment]
As `EachPage()` is used, I'd expect this will always return the *last* page only. Would that explain what you're seeing?

**Comment by vhurtevent** [comment]
No, I'm seeing the first 1000 volumes being correctly returned to csi-attacher

**Comment by dulek** [comment]
Ah, we're returning `False` from the `EachPage()` function, so it should stop iterating immediately and return the first one. This would have to be evaluated more closely to find the actual issue.

**Comment by kayrus** [comment]
I nailed the source of the `ListVolumes` request down to https://github.com/kubernetes-csi/external-attacher/blob/218282a8805bd741dfe75b0be83fe84ff7bf18ef/pkg/attacher/lister.go#L44

I made a custom build of the v3.5.0 tag with the hardcoded `MaxEntries: 2`, and here is what I see:

```
0713 11:43:30.381990       1 connection.go:183] GRPC call: /csi.v1.Controller/ListVolumes
I0713 11:43:30.382003       1 connection.go:184] GRPC request: {"max_entries":2,"starting_token":"f9576f04-162c-4d69-a09b-47e4601f35fe"}
I0713 11:43:30.486769       1 connection.go:186] GRPC response: {"entries":[{"status":{"published_node_ids":["a7471306-3a4d-4a0f-8edf-6b84d94c466e"]},"volume":{"capacity_bytes":214748364800,"volume_id":"66b59eae-e277-491b-bbbb-64d5cb53c7c4"}}]
```

So it tries to list max 2 entries without switching to the next page.

**Comment by kayrus** [comment]
@vhurtevent which csi-attacher tag are you using?

**Comment by vhurtevent** [comment]
Hello @kayrus,

my setup is made with latest tag manifests : https://github.com/kubernetes/cloud-provider-openstack/blob/v1.27.1/manifests/cinder-csi-plugin/cinder-csi-controllerplugin.yaml

- registry.k8s.io/provider-os/cinder-csi-plugin:v1.27.1
- registry.k8s.io/sig-storage/csi-attacher:v4.2.0

When I try to query volumes/detail with CURL : 

```
curl -s -H "X-Auth-Token: xxxxxxxxxxxxxxxxx" "https://openstack-api-url:13776/v3/754a8b03bc764cfe9c475089e5353292/volumes/detail" | jq ".[] | length"
1000
```

```
curl -s -H "X-Auth-Token: xxxxxxxxxxxxxxxxx" "https://openstack-api-url:13776/v3/754a8b03bc764cfe9c475089e5353292/volumes/detail?marker=fa2d3318-e5cd-4bc3-8a9e-b4e404c5d86a" | jq ".[] | length"  
258
```

Using the marker in the logs, at the time of capture : 

```
curl -s -H "X-Auth-Token: xxxxxxxxxxxxxxxxx" "https://openstack-api-url:13776/v3/754a8b03bc764cfe9c475089e5353292/volumes/detail?marker=a30c3053-b146-4acb-9280-fdc5732f2058" | jq ".[] | length"
252
```

These queries are made without maxEntries (or limit in cinder API context) parameter, therefore it's Cinder which paginates the results 1000 by 1000 not the client. Maybe it's a lead ?

**Comment by vhurtevent** [comment]
Using a custom build of external-attacher with maxEntries hardcoded to 500 or 1000 could help debug this last point ?
@kayrus how/where do you fixed hardcoded maxEntries in external-attacher, could you share the code ?

**Comment by kayrus** [comment]
@vhurtevent 

```diff
diff --git a/pkg/attacher/lister.go b/pkg/attacher/lister.go
index 004c92e4..4b9e866f 100644
--- a/pkg/attacher/lister.go
+++ b/pkg/attacher/lister.go
@@ -42,6 +42,7 @@ func (a *CSIVolumeLister) ListVolumes(ctx context.Context) (map[string]([]string
        tok := ""
        for {
                rsp, err := a.client.ListVolumes(ctx, &csi.ListVolumesRequest{
+                       MaxEntries:    2,
                        StartingToken: tok,
                })
                if err != nil 
```

Then build an image using:

```
$ make container
$ docker tag csi-attacher:latest kayrus/csi-attacher:test1
$ docker push kayrus/csi-attacher:test1
```

I can also suggest you to add this log into csi-controller:

```diff
diff --git a/pkg/csi/cinder/controllerserver.go b/pkg/csi/cinder/controllerserver.go
index 21a72706..514bd6f8 100644
--- a/pkg/csi/cinder/controllerserver.go
+++ b/pkg/csi/cinder/controllerserver.go
@@ -313,6 +313,8 @@ func (cs *controllerServer) ListVolumes(ctx context.Context, req *csi.ListVolume
 
                ventries = append(ventries, &ventry)
        }
+
+       klog.V(4).Infof("ListVolumes: next token: %s", nextPageToken)
        return &csi.ListVolumesResponse{
                Entries:   ventries,
                NextToken: nextPageToken,
```

**Comment by dulek** [comment]
Looks like it's true that Cinder will limit the size of a list to 1000 by default [^1]. Moreover some [^2] drivers [^3] limit page size their own too. So this is a good lead!

I think the solution would be to use that info and only request maximum of 1000 volume pages  in the cinder-csi-plugin. If CSI wants more we need to make multiple requests there (controlling when we're actually stopping iterations of `EachPage()`).

[^1]:  https://opendev.org/openstack/cinder/src/commit/40a33360ade30abb1656aa3762051a0d96c76186/cinder/api/common.py#L40-L42
[^2]: https://opendev.org/openstack/cinder/src/commit/40a33360ade30abb1656aa3762051a0d96c76186/cinder/volume/drivers/sandstone/constants.py#L21
[^3]: https://opendev.org/openstack/cinder/src/commit/8930f3f32302ff937b8e0ea2c387b1ffcbece286/cinder/volume/drivers/dell_emc/powermax/iscsi.py#L524

**Comment by kayrus** [comment]
@dulek from what I see in k8s source code, there should be no issues even when cinder artificially limits the output to 1000 entries. Let's wait for @vhurtevent results with extra logs to understand what is the root cause

**Comment by vhurtevent** [comment]
Thank you @kayrus, I hope I could test it this afternoon.

**Comment by vhurtevent** [comment]
I think I got good news ! 

I followed your tips @kayrus and fixed maxEntries=500

logs attached : 

[csi-attacher_with-hardcoded-maxentries-500.log](https://github.com/kubernetes/cloud-provider-openstack/files/12040535/csi-attacher_with-hardcoded-maxentries-500.log)

Volume list are correctly paginated with 500 item pages and csi-attacher get back the complete 1258 volumes.
No more message like `VA has attached status true but actual state false. Adding back to VA queue for forced reprocessing` in csi-atttacher logs.

**Comment by kayrus** [comment]
@vhurtevent I'd like to get extra logs (e.g. #2296 PR) without the 500 limit... Can you also provide them?

**Comment by vhurtevent** [comment]
Here the logs with extras from @kayrus 

```
I0713 15:40:49.228245      12 utils.go:91] [ID:21] GRPC call: /csi.v1.Controller/ListVolumes
I0713 15:40:49.228264      12 utils.go:92] [ID:21] GRPC request: {}
I0713 15:40:49.228393      12 controllerserver.go:283] ListVolumes: called with &csi.ListVolumesRequest{MaxEntries:0, StartingToken:"", XXX_NoUnkeyedLiteral:struct {}{}, XXX_unrecognized:[]uint8(nil), XXX_sizecache:0} request
I0713 15:40:49.228521      12 client.go:128] OpenStack Request URL: GET https://openstack-api-url:13776/v3/project-uuid/volumes/detail
I0713 15:40:49.228616      12 client.go:128] OpenStack Request Headers:
I0713 15:40:49.228622      12 client.go:128] Accept: application/json
I0713 15:40:49.228624      12 client.go:128] User-Agent: cinder-csi-plugin/v1.27.0-alpha.0-58-g0b113b03 gophercloud/v1.4.0
I0713 15:40:49.228626      12 client.go:128] X-Auth-Token: ***
I0713 15:40:55.373811      12 client.go:128] OpenStack Response Code: 200
I0713 15:40:55.373883      12 client.go:128] OpenStack Response Headers:
I0713 15:40:55.373904      12 client.go:128] Content-Type: application/json
I0713 15:40:55.373906      12 client.go:128] Date: Thu, 13 Jul 2023 15:40:49 GMT
I0713 15:40:55.373908      12 client.go:128] Openstack-Api-Version: volume 3.0
I0713 15:40:55.373910      12 client.go:128] Server: Apache
I0713 15:40:55.373912      12 client.go:128] Vary: OpenStack-API-Version,Accept-Encoding
I0713 15:40:55.373915      12 client.go:128] X-Compute-Request-Id: req-249c5dff-6377-4afb-8936-904b3dff7cde
I0713 15:40:55.373919      12 client.go:128] X-Openstack-Request-Id: req-249c5dff-6377-4afb-8936-904b3dff7cde
I0713 15:40:55.477816      12 client.go:128] OpenStack Response Body: {
                                                ....
                                                .... 1000 volumes here
                                                ....
I0713 15:40:55.704932      12 client.go:128]   "volumes_links": [
I0713 15:40:55.704936      12 client.go:128]     {
I0713 15:40:55.704939      12 client.go:128]       "href": "https://openstack-api-url:13776/v3/project-uuid/volumes/detail?marker=fa2d3318-e5cd-4bc3-8a9e-b4e404c5d86a",
I0713 15:40:55.704942      12 client.go:128]       "rel": "next"
I0713 15:40:55.704946      12 client.go:128]     }
I0713 15:40:55.704949      12 client.go:128]   ]
I0713 15:40:55.704952      12 client.go:128] }
I0713 15:40:55.925269      12 controllerserver.go:319] ListVolumes: completed with 1000 entries and "" next token
```

**Comment by kayrus** [comment]
o_O `ListVolumes: completed with 1000 entries and "" next token` - this is very weird...
Let me check what the heck if going one

**Comment by kayrus** [comment]
Nailed it! :)

```diff
diff --git a/pkg/csi/cinder/openstack/openstack_volumes.go b/pkg/csi/cinder/openstack/openstack_volumes.go
index 79372196..083908e6 100644
--- a/pkg/csi/cinder/openstack/openstack_volumes.go
+++ b/pkg/csi/cinder/openstack/openstack_volumes.go
@@ -96,11 +96,11 @@ func (os *OpenStack) ListVolumes(limit int, startingToken string) ([]volumes.Vol
                }
 
                if nextPageURL != "" {
-                       queryParams, err := url.ParseQuery(nextPageURL)
+                       pageURL, err := url.Parse(nextPageURL)
                        if err != nil {
                                return false, err
                        }
-                       nextPageToken = queryParams.Get("marker")
+                       nextPageToken = pageURL.Query().Get("marker")
                }
 
                return false, nil
```

**Comment by vhurtevent** [comment]
Hi @kayrus !

It's great you found the root cause :)

Could you work on a fix & PR in the next days ? How could I help ?

**Comment by kayrus** [comment]
@vhurtevent the fix was submitted last week in #2296. It waits for a merge.

**Comment by jichenjc** [comment]
it's merged ,can you help revisit this issue with the fix? @vhurtevent

**Comment by vhurtevent** [comment]
Hello @jichenjc,

I applied the fix through a build from master branch on a cluster where I got the VolumeAttachment mismatch, and all is ok now.

Thank you for you work !

As I tested with my own build, is there already a automatic build from master ?
Is there a release planned soon ?

**Comment by jichenjc** [comment]
I think we can have a backport to 1.27 branch then have a 1.27.x release . thoughts @kayrus ?
@vhurtevent will 1.27 be good enough for you?

**Comment by kayrus** [comment]
I'm not against the backport. However the release of olde versions is a manual task according to @zetaab

**Comment by jichenjc** [comment]
we should release time to time on older release .. so backport such issue seems valid to me 
I can try to release a new one (did it long time ago :(

**Comment by kayrus** [comment]
let me try the cherry-pick bot...

**Comment by dulek** [comment]
> @jichenjc for some reason all backports fail with CI tests

I backported #2283 to stable branches, let's see if it helps.
