### ISSUE TITLE
[manila-csi-plugin]: code cleanup

### ISSUE THREAD

**Issue by kayrus** [kubernetes/cloud-provider-openstack#2298]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind feature

**What happened**:

Manila CSI code has some legacy code, which is not used due to... legacy.

**What you expected to happen**:

Unused code should be removed.

**How to reproduce it**:

n/a

**Anything else we need to know?**:

n/a

**Environment**:
- openstack-cloud-controller-manager(or other related binary) version:
- OpenStack version:
- Others:

**Comment by jichenjc** [comment]
@gman0 not sure you are still working on this , FYI
