### ISSUE TITLE
Using k8s-keystone-auth with OpenStack Application Credentials

### ISSUE THREAD

**Issue by RdL87** [kubernetes/cloud-provider-openstack#232]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind feature

**What happened**:

The k8s-keystone-auth component requires some values to be set from the user in the OS env.

**What you expected to happen**:

It should be very useful in order to simplify the user experience adding support also to the Application Credentials (https://docs.openstack.org/keystone/queens/user/application_credentials.html) OpenStack authentication.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- openstack-cloud-controller-manager version:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by RdL87** [comment]
@zioproto @Fedosin @lingxiankong @dims @attardi

**Comment by lingxiankong** [comment]
I'm not sure it's a valid feature request to cloud-provider-openstack. Actually, although you are using OS env variables when using kubectl, what the k8s api service receives is keystone token, also send the token to k8s-keystone-auth service. Both k8s and k8s-keystone-auth don't care about how the token is generated(either using the traditional way or using application credentials)

**Comment by dims** [comment]
@lingxiankong this could be for the credentials present in the cloud.conf, not the one passed in by a user

**Comment by lingxiankong** [comment]
Still not sure i fully understand the feature request. The k8s-keystone-auth just needs the keystone service URL, it doesn't use cloud.conf or user ENV.

**Comment by dims** [comment]
ah sorry, i mis-understood. let's wait for clarification

**Comment by zioproto** [comment]
@RdL87 can you provide an example configuration for an Openstack client using Application Credentials ?

**Comment by lingxiankong** [comment]
@RdL87 that's why I said this feature request has nothing to do with k8s-keystone-auth service, you need to propose the PR to kubectl

**Comment by kfox1111** [comment]
Are they likely to accept any changes now that external auth plugins are a thing? https://kubernetes.io/docs/reference/access-authn-authz/authentication/#client-go-credential-plugins

If not, maybe cloud-provider-openstack should host a plugin?

**Comment by dims** [comment]
we do have one - https://github.com/kubernetes/cloud-provider-openstack/pull/126/commits

**Comment by attardi** [comment]
@lingxiankong  This does not require a change to kubectl. kubectl invokes the kube API authentication, which will pass it to the webhook (in our case invoking the k8s-authentication-auth service), passing it the token present in the  .kube/config file. See how Guard does it with other Authenticators:

    https://appscode.com/products/guard/0.2.1/guides/

There are pictures clearly illustrating the architecture, for example in:
    https://appscode.com/products/guard/0.2.1/guides/authenticator/github/

**Comment by lingxiankong** [comment]
However, because we already have `client-keystone-auth` in this repo, i think we could implement this feature there.

**Comment by kfox1111** [comment]
@lingxiankong +1

**Comment by RdL87** [comment]
@lingxiankong tell me how i could be helpful for this purpose. 
@zioproto i'll do asap

**Comment by RdL87** [comment]
@zioproto I need to setu up a Queens O~S deployment before trying it since it is supported only starting from that version.

**Comment by attardi** [comment]
You do not need Queens, but you need version > 3.15 of python-keystoneclient, from https://github.com/openstack/python-keystoneclient.git):

>>> from keystoneauth1.identity import v3
>>> from keystoneauth1 import session
>>> from keystoneclient.v3 import client
>>> auth = v3.Password(auth_url=AUTH_URL,
                   username=USERNAME,
                   user_domain_name=USER_DOMAIN_NAME,
                   password=PASSWD,
                   project_name=PROJECT,
                   project_domain_name=PROJECT_DOMAIN_NAME)
>>> sess = session.Session(auth=auth)
>>> keystone = client.Client(session=sess)
>>> app_cred = keystone.application_credentials.create(
name='kubernetes').to_dict()
>>> from pprint import pprint
>>> pprint(app_cred)
{u'description': None,
 u'expires_at': None,
 u'id': u'25ddda21938d4a34873fe93a8772430d',
 u'links': {u'self': u'https://keystone-staging.cloud.garr.it:5000/v3/users/6472b10817ac41369993fa59709992a5/application_credentials/25ddda21938d4a34873fe93a8772430d'},
 u'name': u'k8s',
 u'project_id': u'ceb24e8ffaf14110a40956ef0028196b',
 u'roles': [{u'domain_id': None,
             u'id': u'f3e6d744b88e4b56a1c56bc15581f1c4',
             u'name': u'Member'},
            {u'domain_id': None,
             u'id': u'ce72aae022d24301a38b0894584066e1',
             u'name': u'Admin'}],
 u'secret': u'0CRvHIRDhi-dJGfuGevaBsX9_s6i0BA2txIpmW3Ks0Avf9IuIAZQ9Ln9vbZPtUj7pEPZ0RCyvHrvjXMMMXjAww',
 u'unrestricted': False}
>>> token = app_cred['secret']

**Comment by attardi** [comment]
Application Credentials can be obtained from the dashboard through this completed Blueprint, upcoming in Rocky,

https://blueprints.launchpad.net/horizon/+spec/application-credentials

**Comment by zioproto** [comment]
PR to have gophercloud supporting application credentials to authenticate is here https://github.com/gophercloud/gophercloud/pull/1224

What is the most elegant way to build the client-keystone-auth against the patched version of gophercloud to test it ?

**Comment by lingxiankong** [comment]
@zioproto In your own environment, you can specify the branch name in the 'constraint' in `Gopkg.toml`, then run 'dep ensure'

**Comment by zioproto** [comment]
@lingxiankong the problem is that the code goes into `vendor/github.com/zioproto/` instead of `vendor/github.com/gophercloud/` and this breaks the build.

**Comment by lingxiankong** [comment]
@zioproto I'm not sure if the way bellow works but I remember I did the similar thing before. Go to gophercloud folder in the vendor directory, add your own repo as remote (git remote add xxx xxx), fetch and checkout into your branch.

**Comment by zioproto** [comment]
I found the solution thanks to Dims! I patched the `Gopkg.toml` with this:
```
[[constraint]]
  name = "github.com/gophercloud/gophercloud"
  branch = "application_credential"
  source = "https://github.com/zioproto/gophercloud"
```
