### ISSUE TITLE
Aug 14 03:24:53 5net-k8s-master-1 kubelet[138676]: E0814 03:24:53.932541  138676 run.go:74] "command failed" err="failed to run Kubelet: bad --node-ip \"<HIDDEN but DUAL STACK NODE IP's>\": dual-stack not supported in this configuration"

### ISSUE THREAD

**Issue by noelashford** [kubernetes/cloud-provider-openstack#2322]
I run a dual stack K8S instance (needed for the project i do) I also need to consume open stack resource - why does this config tell me that by enabling external provider i now can not have  dual stack? I am on 1.27.4

Aug 14 03:24:53 5net-k8s-master-1 kubelet[138676]: Flag --cloud-provider has been deprecated, will be removed in 1.25 or later, in favor of removing cloud provider code from Kubelet.
Aug 14 03:24:53 5net-k8s-master-1 kubelet[138676]: Flag --container-runtime-endpoint has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/>
Aug 14 03:24:53 5net-k8s-master-1 kubelet[138676]: Flag --pod-infra-container-image has been deprecated, will be removed in a future release. Image garbage collector will get sandbox image information from CRI.
Aug 14 03:24:53 5net-k8s-master-1 kubelet[138676]: I0814 03:24:53.919896  138676 server.go:199] "--pod-infra-container-image will not be pruned by the image garbage collector in kubelet and should also be set in the remote runtime"
Aug 14 03:24:53 5net-k8s-master-1 kubelet[138676]: I0814 03:24:53.924142  138676 server.go:415] "Kubelet version" kubeletVersion="v1.27.4"
Aug 14 03:24:53 5net-k8s-master-1 kubelet[138676]: I0814 03:24:53.924367  138676 server.go:417] "Golang settings" GOGC="" GOMAXPROCS="" GOTRACEBACK=""
Aug 14 03:24:53 5net-k8s-master-1 kubelet[138676]: I0814 03:24:53.924631  138676 server.go:837] "Client rotation is on, will bootstrap in background"
Aug 14 03:24:53 5net-k8s-master-1 kubelet[138676]: I0814 03:24:53.926063  138676 certificate_store.go:130] Loading cert/key pair from "/var/lib/kubelet/pki/kubelet-client-current.pem".
Aug 14 03:24:53 5net-k8s-master-1 kubelet[138676]: I0814 03:24:53.927063  138676 dynamic_cafile_content.go:157] "Starting controller" name="client-ca-bundle::/etc/kubernetes/pki/ca.crt"
Aug 14 03:24:53 5net-k8s-master-1 kubelet[138676]: I0814 03:24:53.929134  138676 server.go:662] "--cgroups-per-qos enabled, but --cgroup-root was not specified.  defaulting to /"
Aug 14 03:24:53 5net-k8s-master-1 kubelet[138676]: I0814 03:24:53.929423  138676 container_manager_linux.go:266] "Container manager verified user specified cgroup-root exists" cgroupRoot=[]
Aug 14 03:24:53 5net-k8s-master-1 kubelet[138676]: I0814 03:24:53.929578  138676 container_manager_linux.go:271] "Creating Container Manager object based on Node Config" nodeConfig={RuntimeCgroupsName: SystemCgroupsName: KubeletCgroupsName: KubeletOOMScoreAdj:-999 Containe>
Aug 14 03:24:53 5net-k8s-master-1 kubelet[138676]: I0814 03:24:53.929730  138676 topology_manager.go:136] "Creating topology manager with policy per scope" topologyPolicyName="none" topologyScopeName="container"
Aug 14 03:24:53 5net-k8s-master-1 kubelet[138676]: I0814 03:24:53.929830  138676 container_manager_linux.go:302] "Creating device plugin manager"
Aug 14 03:24:53 5net-k8s-master-1 kubelet[138676]: I0814 03:24:53.929952  138676 state_mem.go:36] "Initialized new in-memory state store"
Aug 14 03:24:53 5net-k8s-master-1 kubelet[138676]: E0814 03:24:53.932541  138676 run.go:74] "command failed" err="failed to run Kubelet: bad --node-ip \"<HIDDEN but DUAL STACK NODE IP's>\": dual-stack not supported in this configuration"

`apiVersion: kubeadm.k8s.io/v1beta3
kind: ClusterConfiguration
networking:
  dnsDomain: cluster.local
  podSubnet: 10.244.0.0/16,fc00:db8:42:0::/56
  serviceSubnet: 10.96.0.0/16,fc00:db8:42:1::/112
clusterName: 5Net
controllerManager:
  extraArgs:
    cloud-provider: "external"
apiServer:
  extraArgs:
    cloud-provider: "external"

apiVersion: kubeadm.k8s.io/v1beta3
kind: InitConfiguration
localAPIEndpoint:
  advertiseAddress: 172.19.5.220
  bindPort: 6443
nodeRegistration:
  kubeletExtraArgs:
    node-ip: <HIDDEN but DUAL STACK NODE IP's>
    cloud-provider: "external"`

**Comment by mdbooth** [comment]
@MaysaMacedo Are you able to answer?

**Comment by MaysaMacedo** [comment]
@noelashford Looks like you might be missing setting `--feature-gates=CloudDualStackNodeIPs=true` in kubelet and external cloud provider. That is part of the requirements to have node-ip working with dual-stack https://kubernetes.io/docs/concepts/services-networking/dual-stack/#configure-ipv4-ipv6-dual-stack

**Comment by noelashford** [comment]
Confirmed - I added this to my config.

---
apiVersion: kubelet.config.k8s.io/v1beta1
cgroupDriver: systemd
featureGates:
  CloudDualStackNodeIPs: true
kind: KubeletConfiguration


Worked fine
