### ISSUE TITLE
dual-stack not supported in this configuration, requeuing

### ISSUE THREAD

**Issue by noelashford** [kubernetes/cloud-provider-openstack#2328]
```
root@5net-k8s-master-1:~/kubernetes# kubectl logs -n kube-system openstack-cloud-controller-manager-mfvmp
2023/08/19 03:34:33 Running command:
Command env: (log-file=, also-stdout=false, redirect-stderr=true)
Run from directory:
Executable path: /bin/openstack-cloud-controller-manager
Args (comma-delimited): /bin/openstack-cloud-controller-manager,--v=1,--cluster-name=kubernetes,--cloud-config=/etc/config/cloud.conf,--cloud-provider=openstack,--use-service-account-credentials=true,--bind-address=127.0.0.1
2023/08/19 03:34:33 Now listening for interrupts
I0819 03:34:34.448017      10 serving.go:348] Generated self-signed cert in-memory
I0819 03:34:35.052972      10 serving.go:348] Generated self-signed cert in-memory
W0819 03:34:35.053034      10 client_config.go:618] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
I0819 03:34:35.548197      10 controllermanager.go:167] Version: v1.27.1
I0819 03:34:35.552365      10 requestheader_controller.go:169] Starting RequestHeaderAuthRequestController
I0819 03:34:35.552820      10 secure_serving.go:210] Serving securely on 127.0.0.1:10258
I0819 03:34:35.553071      10 leaderelection.go:245] attempting to acquire leader lease kube-system/cloud-controller-manager...
I0819 03:34:35.553305      10 tlsconfig.go:240] "Starting DynamicServingCertificateController"
I0819 03:34:35.553387      10 configmap_cafile_content.go:202] "Starting controller" name="client-ca::kube-system::extension-apiserver-authentication::client-ca-file"
I0819 03:34:35.553652      10 shared_informer.go:311] Waiting for caches to sync for client-ca::kube-system::extension-apiserver-authentication::client-ca-file
I0819 03:34:35.553891      10 shared_informer.go:311] Waiting for caches to sync for RequestHeaderAuthRequestController
I0819 03:34:35.554070      10 configmap_cafile_content.go:202] "Starting controller" name="client-ca::kube-system::extension-apiserver-authentication::requestheader-client-ca-file"
I0819 03:34:35.554177      10 shared_informer.go:311] Waiting for caches to sync for client-ca::kube-system::extension-apiserver-authentication::requestheader-client-ca-file
I0819 03:34:35.603684      10 leaderelection.go:255] successfully acquired lease kube-system/cloud-controller-manager
I0819 03:34:35.604355      10 event.go:307] "Event occurred" object="kube-system/cloud-controller-manager" fieldPath="" kind="Lease" apiVersion="coordination.k8s.io/v1" type="Normal" reason="LeaderElection" message="5net-k8s-master-1_a9962bc1-a0d4-4d7e-9161-a2f9ffa3061d became leader"
I0819 03:34:35.616123      10 openstack.go:484] Setting up informers for Cloud
I0819 03:34:35.616192      10 controllermanager.go:317] Starting "cloud-node"
I0819 03:34:35.617834      10 controllermanager.go:336] Started "cloud-node"
I0819 03:34:35.617969      10 controllermanager.go:317] Starting "cloud-node-lifecycle"
I0819 03:34:35.617865      10 node_controller.go:161] Sending events to api server.
I0819 03:34:35.618194      10 node_controller.go:170] Waiting for informer caches to sync
I0819 03:34:35.619760      10 controllermanager.go:336] Started "cloud-node-lifecycle"
I0819 03:34:35.619909      10 controllermanager.go:317] Starting "service"
I0819 03:34:35.619851      10 node_lifecycle_controller.go:113] Sending events to api server
I0819 03:34:35.626461      10 openstack.go:365] Claiming to support LoadBalancer
I0819 03:34:35.626626      10 controllermanager.go:336] Started "service"
I0819 03:34:35.626689      10 controllermanager.go:317] Starting "route"
I0819 03:34:35.626716      10 controller.go:229] Starting service controller
I0819 03:34:35.626820      10 shared_informer.go:311] Waiting for caches to sync for service
I0819 03:34:35.654644      10 shared_informer.go:318] Caches are synced for client-ca::kube-system::extension-apiserver-authentication::requestheader-client-ca-file
I0819 03:34:35.654697      10 shared_informer.go:318] Caches are synced for RequestHeaderAuthRequestController
I0819 03:34:35.655828      10 shared_informer.go:318] Caches are synced for client-ca::kube-system::extension-apiserver-authentication::client-ca-file
W0819 03:34:35.726647      10 openstack.go:468] Error initialising Routes support: router-id not set in cloud provider config
W0819 03:34:35.726818      10 core.go:111] --configure-cloud-routes is set, but cloud provider does not support routes. Will not configure cloud provider routes.
W0819 03:34:35.726898      10 controllermanager.go:324] Skipping "route"
I0819 03:34:35.819313      10 node_controller.go:427] Initializing node 5net-k8s-master-1 with cloud provider
I0819 03:34:35.826993      10 shared_informer.go:318] Caches are synced for service
E0819 03:34:36.255037      10 node_controller.go:236] error syncing '5net-k8s-master-1': failed to get node modifiers from cloud provider: provided node ip for node "5net-k8s-master-1" is not valid: failed to parse node IP "<IPV4 IP HIDDEN>,<IPV6 IP HIDDEN>": dual-stack not supported in this configuration, requeuing
.........

```

My Current Init config is as follows:

```
---
apiVersion: kubeadm.k8s.io/v1beta3
kind: ClusterConfiguration
networking:
  podSubnet: 10.244.0.0/16,fc00:db8:42:0::/56
  serviceSubnet: 10.96.0.0/16,fc00:db8:42:1::/112
clusterName: 5Net
controllerManager:
  extraArgs:
    cloud-provider: external
apiServer:
  extraArgs:
    cloud-provider: external
---
apiVersion: kubelet.config.k8s.io/v1beta1
cgroupDriver: systemd
featureGates:
  CloudDualStackNodeIPs: true
kind: KubeletConfiguration

---
apiVersion: kubeadm.k8s.io/v1beta3
kind: InitConfiguration
localAPIEndpoint:
  advertiseAddress: <IPV4 IP HIDDEN>
  bindPort: 6443
nodeRegistration:
  kubeletExtraArgs:
    node-ip: <IPV4 IP HIDDEN>,<IPV6 IP HIDDEN>
    cloud-provider: external
```

I feel as if requirements are met?

https://kubernetes.io/docs/concepts/services-networking/dual-stack/#configure-ipv4-ipv6-dual-stack 

What am i missing ?

**Comment by MaysaMacedo** [comment]
@noelashford Besides adding `CloudDualStackNodeIPs: true` to kubelet, the cloud controller manager also needs to have the feature gate enabled. Probably in one of the args of the CCM container the following could be added: `--feature-gates=CloudDualStackNodeIPs=true` .

**Comment by noelashford** [comment]
args:
            - /bin/openstack-cloud-controller-manager
            - --v=1
            - --cluster-name=$(CLUSTER_NAME)
            - --cloud-config=$(CLOUD_CONFIG)
            - --cloud-provider=openstack
            - --use-service-account-credentials=true
            - --bind-address=127.0.0.1
            - --feature-gates=CloudDualStackNodeIPs=true

Seems to have worked - now it is asking for a router ID for the LB I believe. 

W0823 03:02:44.710707      10 openstack.go:468] Error initialising Routes support: router-id not set in cloud provider config
W0823 03:02:44.710727      10 core.go:111] --configure-cloud-routes is set, but cloud provider does not support routes. Will not configure cloud provider routes.
W0823 03:02:44.710733      10 controllermanager.go:324] Skipping "route"
I0823 03:02:44.805427      10 node_controller.go:427] Initializing node 5net-k8s-master-1 with cloud provider
I0823 03:02:44.812115      10 shared_informer.go:318] Caches are synced for service
I0823 03:02:45.325190      10 node_controller.go:496] Successfully initialized node 5net-k8s-master-1 with cloud provider

Should i provide dual router ID's - if so, how - the LB will have IP6 & IPv4 in upstream Octavia. Any idea on how to provide two routers to the config ?

**Comment by noelashford** [comment]
Also, wondering about the Dual Subnet's to that point... ?  Is there documentation somewhere on what a dual stack cloud.cfg should look like?

**Comment by noelashford** [comment]
Warning  SyncLoadBalancerFailed  6s               service-controller  Error syncing load balancer: failed to ensure load balancer: error creating loadbalancer kube_service_kubernetes_default_hostname-server: error creating loadbalancer {"name":"kube_service_kubernetes_default_hostname-server","description":"Kubernetes external service default/hostname-server from cluster kubernetes","vip_subnet_id":"8b6071a9-a19b-40f0-acea-0dd773e948b1","provider":"amphora","listeners":[{"protocol":"TCP","protocol_port":80,"name":"listener_0_kube_service_kubernetes_default_hostname-server","default_pool":{"lb_algorithm":"ROUND_ROBIN","protocol":"TCP","name":"pool_0_kube_service_kubernetes_default_hostname-server","members":[{"address":"172.19.5.235","protocol_port":30919,"name":"5net-k8s-worker-1","subnet_id":"f98de447-6357-41bb-971e-fa21b1721a0c"},{"address":"172.19.5.203","protocol_port":30919,"name":"5net-k8s-worker-2","subnet_id":"f98de447-6357-41bb-971e-fa21b1721a0c"}]},"connection_limit":-1,"timeout_client_data":50000,"timeout_member_data":50000,"timeout_member_connect":5000,"timeout_tcp_inspect":0,"allowed_cidrs":["0.0.0.0/0"],"tags":["kube_service_kubernetes_default_hostname-server"]}],"tags":["kube_service_kubernetes_default_hostname-server"]}: Bad request with: [POST https://192.168.5.99:9876/v2.0/lbaas/loadbalancers], error message: {"faultcode": "Client", "faultstring": "Validation failure: CIDR 0.0.0.0/0 IP version incompatible with VIP 2606:8180:5001:4001::cc IP version.", "debuginfo": null}
  Normal   EnsuringLoadBalancer    1s (x2 over 8s)  service-controller  Ensuring load balancer

I have tried with both subnets on one line and a comma, two lines (the above shows) - how do i create a dual stack octavia / amphora config wise in cloud.yaml ?

**Comment by noelashford** [comment]
So - I got it to spin up an amphora network using network-id (w a Dual Stack network) and floating-network-id but the IP is only ipv4 ?! not sure why

**Comment by MaysaMacedo** [comment]
@noelashford It looks like cloud provider does not support routes, according to the logs. That specific error doesn't seem to be problematic to CCM as is `Skipping "route"`.

Is there anything specific that you're trying to achieve and it's not working?

**Comment by noelashford** [comment]
As per another ticket I opened up, my end goal is that I can spin up dual
stack (ipv6/ipv4) Octavia LB (which isn't working correct for me as per
that ticket) plus CSI & barbican support  (encrypted volume support would
be helpful)

**Comment by dulek** [comment]
You won't be able to spin up a dual stack Octavia LB at the moment, we're preventing that at the moment. With Octavia now allowing multiple VIPs per LB [2] it might now be possible to be implemented. Is this something you might be interested in working on?

[1] https://github.com/kubernetes/cloud-provider-openstack/blob/fe71c9f0cfe57c9b39df5ff2c5a961caefe1f6bf/pkg/openstack/loadbalancer.go#L1553-L1557
[2] https://opendev.org/openstack/octavia/commit/8c793f2e8ff7857a97cc68a4706bdcdfdff1fde5

**Comment by noelashford** [comment]
I am happy to test it out etc / work with you

**Comment by kayrus** [comment]
@noelashford IMO you've opened a can of worms with the dual stack :) I believe that more and more issues will be discovered, especially with IPv6 support. Be prepared for the possibility that this situation may persist for a while. It's also hard to obtain a working OpenStack environment that supports IPv6, for example I don't have one.

**Comment by noelashford** [comment]
@dulek How do we proceed to test this out - says the MR was submitted but i assume not merged into master? Happy to help test this out for you

**Comment by dulek** [comment]
> @dulek How do we proceed to test this out - says the MR was submitted but i assume not merged into master? Happy to help test this out for you

What MR? I don't think anyone had started looking into enabling dual stack LBs in cloud-provider-openstack yet. Unfortunately at the moment it's not on top of my priorities either. That's why I asked if you're interested in working to write a PR. If so, I'm happy to help on #provider-openstack on Kubernetes Slack.

**Comment by noelashford** [comment]
Let me look into what's needed and get back to you

**Comment by dulek** [comment]
Closing this in favor of #1937.
