### ISSUE TITLE
cinder-csi-plugin: Helm Chart: add optional metrics and Prometheus Operator values

### ISSUE THREAD

**Issue by desaintmartin** [kubernetes/cloud-provider-openstack#2350]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
> /kind bug
/kind feature

**What happened**:

https://github.com/kubernetes/cloud-provider-openstack/pull/2077 introduced metrics support for cinder-csi-plugin. It would be neat to allow automatic scraping (through Prometheus Operator's ServiceMonitor ?)

It is already possible to enable metrics through extraArgs.

Would a Pull Request to add an optional ServiceMonitor and automatically add http-endpoint arg acceptable?

**Environment**:
- openstack-cloud-controller-manager(or other related binary) version: master
- OpenStack version: -
- Others: -

**Comment by jichenjc** [comment]
@desaintmartin thanks for the great PR, do you think it's reasonable to add this for other (e.g OCCM) so we can benefit the function for all projects?

**Comment by desaintmartin** [comment]
Actually, [occm](https://github.com/kubernetes/cloud-provider-openstack/blob/master/charts/openstack-cloud-controller-manager/values.yaml#L79) already has a ServiceMonitor (although I chose to implement a PodMonitor instead to avoid creating a useless Service)!

Regarding manila-csi-plugin, I haven't checked much if there is a metrics component, but there is no similar `http-endpoint` flag or any obvious metrics flag / server.
