### ISSUE TITLE
[occm] Support get OS instance ID from instance metadata

### ISSUE THREAD

**Issue by jeffyjf** [kubernetes/cloud-provider-openstack#2357]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind feature

**What happened**:

Now, occm support two ways to get the info of OS instance which associated with k8s node:
* First, get instance ID from `node.Spec.ProviderID`, and then query instance info from OS use the instance ID.
* If `node.Spec.ProviderID` is not set, occm try to query OS instance according to the k8s node's name.

But, In some deploy cases the k8s node's name not equal to the node's hostname and then it's not equal to the OS instance's name. In these cases, the occm will report error: `instance not found`.

**What you expected to happen**:

When `node.Spec.ProviderID` is not set, occm  try to get OS instance id from OS instance's metadata. And use this id to get OS instance info.

**How to reproduce it**:

Deploy k8s cluster in openstack VM and set the kubelet node name not equal to the instance's name. And then startup occm, occm will report `instance not found` in it's log message.

**Anything else we need to know?**:

**Environment**:
- openstack-cloud-controller-manager(or other related binary) version: latest
- OpenStack version: ussuri
- Others:

**Comment by mdbooth** [comment]
The most robust way to solve this is to pass the providerID to kubelet on startup. Look for `providerID` in this configuration doc: https://kubernetes.io/docs/reference/config-api/kubelet-config.v1beta1/

You can populate this on the node itself before kubelet starts using instance metadata. With this parameter kubelet will set providerID on the node directly, which means occm will always be able to match it.

We could potentially use other heuristics in occm but they'd be just that: heuristics. You're always going to be able to break this. For example, you can pass an arbitrary hostname to kubelet. occm will never be able to match this in general. I personally favour documenting the approach of passing providerID to kubelet. I'd also like to get it into our default templates in CAPO.

**Comment by jeffyjf** [comment]
@monotek Thank you for your comments. I already know this proposal of the issue is immature. The occm run as control-plane, It can not get the node's metadata correctly. I agree with you that we just use some heuristics right now.

Additonally, I am a newbies of kubernetes, I note that  you mentioned CAPO but I don't know what it is. Cloud you provide more informations ablout it? Thank you very much.

**Comment by mdbooth** [comment]
> @monotek Thank you for your comments. I already know this proposal of the issue is immature. The occm run as control-plane, It can not get the node's metadata correctly. I agree with you that we just use some heuristics right now.
> 
> Additonally, I am a newbies of kubernetes, I note that you mentioned CAPO but I don't know what it is. Cloud you provide more informations ablout it? Thank you very much.

CAPO is cluster-api-provider-openstack: https://github.com/kubernetes-sigs/cluster-api-provider-openstack. It's a provider for [cluster-api](https://github.com/kubernetes-sigs/cluster-api) which can install and manage kubernetes.

**Comment by jeffyjf** [comment]
@mdbooth Thanks very much.

> I'd also like to get it into our default templates in CAPO.

If you haven't started this work yet. Could you leave it to me, I want to try it.

**Comment by jeffyjf** [comment]
@mdbooth I found CAPO already added `provider-id` to cluster-template.yaml.

**Comment by mdbooth** [comment]
I completely forgot we already did that 😅
