### ISSUE TITLE
What is the release concept?

### ISSUE THREAD

**Issue by cwrau** [kubernetes/cloud-provider-openstack#2364]
**What happened**:
I've been waiting on https://github.com/kubernetes/cloud-provider-openstack/pull/2237 to be released, the PR has been merged more than 4 months ago and there has been [1 release since then](https://github.com/kubernetes/cloud-provider-openstack/releases/tag/openstack-cloud-controller-manager-2.27.3) which didn't include this fix.

**What you expected to happen**:
I expected that the next release after the merge would include this fix.

Is this a mistake? Or what is the concept here? 

(kinda related https://github.com/kubernetes-sigs/cluster-api-provider-openstack/discussions/1676)

**Comment by dulek** [comment]
The fix is included in [v1.28.0](https://github.com/kubernetes/cloud-provider-openstack/releases/tag/v1.28.0). It was never backported to the release-1.27 branch, so it haven't landed in any other release. If you need it in 1.27.x please create a backport and I'll happily accept it.

**Comment by cwrau** [comment]
> The fix is included in [v1.28.0](https://github.com/kubernetes/cloud-provider-openstack/releases/tag/v1.28.0). It was never backported to the release-1.27 branch, so it haven't landed in any other release. If you need it in 1.27.x please create a backport and I'll happily accept it.

Mh, ok, is there a reason for that?

And is there documentation on how to do the backporting?

**Comment by dulek** [comment]
> > The fix is included in [v1.28.0](https://github.com/kubernetes/cloud-provider-openstack/releases/tag/v1.28.0). It was never backported to the release-1.27 branch, so it haven't landed in any other release. If you need it in 1.27.x please create a backport and I'll happily accept it.
> 
> Mh, ok, is there a reason for that?
> 
> And is there documentation on how to do the backporting?

No reason, it wasn't requested. I don't think we have docs about backporting patches, but it is done by cherry-picking commits to the release branch and creating a PR against that branch. Please pay attention to version charts correctly: https://github.com/kubernetes/cloud-provider-openstack/blob/master/docs/developers-guide.md#helm-charts

**Comment by dulek** [comment]
I'm going to close this as resolved.

**Comment by dulek** [comment]
Well, the backports cannot be done automagically. Some fixes are not backportable, some are not fulfilling the criteria to be important enough to get backported, some issues are not affecting older code. I believe a manual, human assessment is needed in most cases. Obviously the issue in question was totally worth a backport and we've overlooked that, but this is just an indicator of how important community feedback and participation is to make sure these problems are found and dealt with.
