### ISSUE TITLE
[occm] add `max_retries_down` octavia health monitor parameter

### ISSUE THREAD

**Issue by kayrus** [kubernetes/cloud-provider-openstack#2371]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
> /kind bug
/kind feature

**What happened**:

Octavia supports `max_retries_down` optional parameter for the health monitor.

**What you expected to happen**:

There should be a way to configure `max_retries_down` for the health monitor using service annotation, e.g.

```yaml
    annotations:
        loadbalancer.openstack.org/health-monitor-max-retries-down: "1"
```

**How to reproduce it**:

n/a

**Anything else we need to know?**:

See https://docs.openstack.org/api-ref/load-balancer/v2/?expanded=create-health-monitor-detail#create-health-monitor

> `max_retries_down`: The number of allowed check failures before changing the operating status of the member to ERROR. A valid value is from 1 to 10. The default is 3.

See also #2148 

@dulek since this feature appears to be critical (service downtime risk), I suggest to backport it to `>= 1.26` releases as well.

**Environment**:
- openstack-cloud-controller-manager(or other related binary) version:
- OpenStack version:
- Others:

**Comment by dulek** [comment]
@kayrus: How does this help with #2148? It helps you stabilize the health monitor in case a bunch of errors is returned? But it doesn't help with new nodes being spawned that are considered healthy for a moment and can get some traffic while still not hosting service pods? It also won't help with a case when a pod gets removed from a node, right?

**Comment by kayrus** [comment]
@dulek it doesn't help, but I'd like to link these issues for the future.

**Comment by dulek** [comment]
> > How does this help with #2148?
> 
> @dulek it doesn't help, but I'd like to link these issues for the future.
> 
> > It also won't help with a case when a pod gets removed from a node, right?
> 
> this should help, at least the DOWN timeout will be decreased. I'm planning to add some documentation for `externalTrafficPolicy: Local` best practices later.

Oh, the default's 3, you can set it to 1. All right, now I get this!
