### ISSUE TITLE
[octavia-ingress-controller] TLS Secrets container not found

### ISSUE THREAD

**Issue by CoryClough** [kubernetes/cloud-provider-openstack#2376]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
 /kind bug
> /kind feature

**What happened**:
octavia-ingress-controller fails to delete the loadblancer when using TLS. The Barbican API logs have two calls to delete the same secret. The first call directly from the Kubernetes master node successfully deletes the secret. However, there is a second call from the Openstack controller node that fails (404) as it has already been deleted,. The loadbalancer is stuck in PENDING_DELETE, and any attempts to delete the loadbalancer afterwards fail because it cannot find the secret. 

It appears ingress-controller is calling Barbican API directly to delete secret. Then, Octavia worker attempts to get secret in order to delete loadbalancer .etc. but the secret no longer exists. 

I'm having no issues deleting TLS loadbalancers using Openstack cli as long as I haven't already attempted to delete with octavia-ingress-controller. 

**What you expected to happen**:
octavia-ingress-controller to use Octavia API to delete Barbican secret and loadbalancer --cascade with a single API call 

**How to reproduce it**:
Create an ingress controller with tls secret and try deleting it using kubectl delete ingress.

**Anything else we need to know?**:

```
[Thu Sep 28 09:47:29.600879 2023] [wsgi:error] [pid 995:tid 140651612644928] [remote 192.168.10.231:14426] 2023-09-28 09:47:29.600 995 INFO barbican.api.middleware.context [None req-6a84bfd7-cd86-4480-ab89-b4c0960dd66f 2f6d1fbf140249c1adead9f002090264 ede09487f43a477d94280a75a4d63495 - - default default] Begin processing request req-6d980b62-c1b5-4aba-affb-0fbd3e88743f\x1b[00m
[Thu Sep 28 09:47:29.615866 2023] [wsgi:error] [pid 995:tid 140651612644928] [remote 192.168.10.231:14426] 2023-09-28 09:47:29.615 995 INFO barbican.api.controllers.secrets [None req-bb4dd7f4-1ec0-4ab3-955b-780e347b4433 2f6d1fbf140249c1adead9f002090264 ede09487f43a477d94280a75a4d63495 - - default default] Retrieved secret list for project: ede09487f43a477d94280a75a4d63495\x1b[00m
[Thu Sep 28 09:47:29.616969 2023] [wsgi:error] [pid 995:tid 140651612644928] [remote 192.168.10.231:14426] 2023-09-28 09:47:29.616 995 INFO barbican.api.middleware.context [None req-bb4dd7f4-1ec0-4ab3-955b-780e347b4433 2f6d1fbf140249c1adead9f002090264 ede09487f43a477d94280a75a4d63495 - - default default] Processed request: 200 OK - GET http://controller:9311/v1/secrets?secret_type=opaque\x1b[00m
192.168.10.231 - - [28/Sep/2023:09:47:29 -0500] "GET /v1/secrets?secret_type=opaque HTTP/1.1" 200 762 "-" "octavia-ingress-controller/ gophercloud/2.0.0"
[Thu Sep 28 09:47:29.620792 2023] [wsgi:error] [pid 993:tid 140651595859520] [remote 192.168.10.231:14426] 2023-09-28 09:47:29.620 993 INFO barbican.api.middleware.context [None req-288db6a4-e396-4a95-8975-0385cb8edc71 2f6d1fbf140249c1adead9f002090264 ede09487f43a477d94280a75a4d63495 - - default default] Begin processing request req-88cc8765-dda0-40c3-ab9c-3cd9df999031\x1b[00m
[Thu Sep 28 09:47:29.671903 2023] [wsgi:error] [pid 993:tid 140651595859520] [remote 192.168.10.231:14426] 2023-09-28 09:47:29.671 993 INFO barbican.api.controllers.secrets [None req-d9773350-0398-4bbb-9671-b896c2177fbe 2f6d1fbf140249c1adead9f002090264 ede09487f43a477d94280a75a4d63495 - - default default] Deleted secret for project: ede09487f43a477d94280a75a4d63495\x1b[00m
[Thu Sep 28 09:47:29.690886 2023] [wsgi:error] [pid 993:tid 140651595859520] [remote 192.168.10.231:14426] 2023-09-28 09:47:29.690 993 INFO barbican.api.middleware.context [None req-d9773350-0398-4bbb-9671-b896c2177fbe 2f6d1fbf140249c1adead9f002090264 ede09487f43a477d94280a75a4d63495 - - default default] Processed request: 204 No Content - DELETE http://controller:9311/v1/secrets/97ff9c5f-a439-43af-9fcd-99ebfda62e68\x1b[00m
192.168.10.231 - - [28/Sep/2023:09:47:29 -0500] "DELETE /v1/secrets/97ff9c5f-a439-43af-9fcd-99ebfda62e68 HTTP/1.1" 204 231 "-" "octavia-ingress-controller/ gophercloud/2.0.0"
[Thu Sep 28 09:47:30.661813 2023] [wsgi:error] [pid 994:tid 140651537110592] [remote 192.168.10.220:37922] 2023-09-28 09:47:30.661 994 INFO barbican.api.middleware.context [None req-eafc3fda-2a9c-4a5e-9c0e-4d9c5f6e149b 2f6d1fbf140249c1adead9f002090264 ede09487f43a477d94280a75a4d63495 - - default default] Begin processing request req-dc2d1573-d056-4ad0-ad32-7a7800a249b5\x1b[00m
[Thu Sep 28 09:47:30.672336 2023] [wsgi:error] [pid 994:tid 140651537110592] [remote 192.168.10.220:37922] 2023-09-28 09:47:30.672 994 INFO barbican.api.middleware.context [None req-8754e332-ad78-42f8-96a4-7f5e0e8d4688 2f6d1fbf140249c1adead9f002090264 ede09487f43a477d94280a75a4d63495 - - default default] Processed request: 404 Not Found - GET http://controller:9311/v1/secrets/97ff9c5f-a439-43af-9fcd-99ebfda62e68\x1b[00m


```

**Environment**:
- octavia-ingerss-controller version: latest
- OpenStack version: 6.0.0
- Others: Ubuntu 22.04 on ESXi 7.3

**Comment by kayrus** [comment]
@CoryClough Which `octavia-ingerss-controller` version are you using? According to barbican server logs the user agent is set to `octavia-ingress-controller/`, when the recent version should show a proper release. See 9ea1c3861c496719dcd254f3abfb893378d9b70b

Anyway, try to test the #2378 fix and let me know if it solves the issue.

**Comment by CoryClough** [comment]
@kayrus Do I need to install the entire project? I only copied the yaml files and followed these instructions https://github.com/kubernetes/cloud-provider-openstack/blob/master/docs/octavia-ingress-controller/using-octavia-ingress-controller.md

**Comment by kayrus** [comment]
@CoryClough run the compilation and then put the binary into your own docker image.

**Comment by CoryClough** [comment]
@kayrus  Thanks. I will try that. So this image doesn't include the latest binaries? docker.io/k8scloudprovider/octavia-ingress-controller:latest

**Comment by kayrus** [comment]
@CoryClough no, the docker.io is not supported for a while, since they introduced non-free storage plan.

**Comment by CoryClough** [comment]
@kayrus understood. Thank you for your help!

**Comment by CoryClough** [comment]
@kayrus  #2378 appears to have fixed the issue in my environment.

**Comment by kayrus** [comment]
@CoryClough nice to hear this.
