### ISSUE TITLE
use secrets to specify the openstack auth info

### ISSUE THREAD

**Issue by dims** [kubernetes/cloud-provider-openstack#24]
_From @dims on January 15, 2018 20:13_

will need this fixed first: https://github.com/dims/openstack-cloud-controller-manager/issues/8

_Copied from original issue: dims/openstack-cloud-controller-manager#13_

**Comment by dims** [comment]
https://github.com/kubernetes/kubernetes/pull/61295

**Comment by celebdor** [comment]
Why should it support the auth info in env vars? Could we not just have the K8s secret mounted into a containerized openstack cloud provider?

**Comment by dims** [comment]
@celebdor if the binary is running in a pod or daemonset, we can just inject secrets (or configmap) as env vars for the binary to pick up.
