### ISSUE TITLE
[tests] Add unit tests for the loadbalancer.go functions

### ISSUE THREAD

**Issue by sakshi-1505** [kubernetes/cloud-provider-openstack#2400]
/kind feature

**What happened**:

The cloud-provider-openstack code most related to this project lives in [loadbalancer.go](https://github.com/kubernetes/cloud-provider-openstack/blob/master/pkg/openstack/loadbalancer.go) which is lacking almost all unit tests. This task is to write tests for all of the functions there. Please note that it is untrivial to create tests for methods using gophercloud library, so calling the OpenStack APIs.

**List of Tests**:
- [x] getSecurityGroupName
- [x] getListenerProtocol
- [x] GetLoadBalancerName
- [x] nodeAddressForLB
- [x] getStringFromServiceAnnotation
- [x] getIntFromServiceAnnotation
- [x] getBoolFromServiceAnnotation
- [x] buildMonitorCreateOpts
- [x] buildPoolCreateOpt
- [x] buildBatchUpdateMemberOpts
- [x] buildListenerCreateOpt
- [x] getMemberSubnetID
- [x] getSubnetID
- [x] getNetworkID
- [x] checkListenerPorts
- [x] updateServiceAnnotations
- [x] createLoadBalancerStatus
- [ ] GetLoadBalancerSourceRanges

**Comment by FavourEva** [comment]
I am currently working on these functions: 
getBoolFromServiceAnnotation
buildBatchUpdateMemberOpts
buildListenerCreateOpt
updateServiceAnnotations

**Comment by sakshi-1505** [comment]
Working on getSecurityGroupName,GetLoadBalancerSourceRanges,getSubnetId

**Comment by dulek** [comment]
@sakshi-1505: I think `getSecurityGroupName()` is being done here: https://github.com/kubernetes/cloud-provider-openstack/pull/2389. A bunch of PRs that are already opened: https://github.com/kubernetes/cloud-provider-openstack/pulls?q=is%3Apr+is%3Aopen+test

**Comment by sakshi-1505** [comment]
Ugh, I had created a PR already for that https://github.com/kubernetes/cloud-provider-openstack/pull/2401. I will close the PR since I guess there is one already created but needs some more changes.

**Comment by sakshi-1505** [comment]
@dulek I guess there are multiple PRs created, out of which none is merged but those Prs occupy 50% of the function listed above. Do you think there is some other level 2 task I can pick? I have already built devstack on my local machine as was suggested in the Outreachy guide before I jumped on picking these issues.

**Comment by KingDaemonX** [comment]
I already open a PR for  
- getSecurity group name 
- Getloadbalancername
- nodeaddressforlb
- GetStringfromserviceannotation
- Updateserviceannotation 
- GetnetworkId
- GetMembersubnetId

**Comment by KingDaemonX** [comment]
And I am currently working on ‘Getloadbalancersourcerange’

**Comment by KingDaemonX** [comment]
> Ugh, I had created a PR already for that #2401. I will close the PR since I guess there is one already created but needs some more changes.

I already opened a PR for this : 
https://github.com/kubernetes/cloud-provider-openstack/pull/2389

**Comment by dulek** [comment]
@sakshi-1505: I'll try to find more functions that are lacking unit tests and allow writing tests fairly easily. The problem is that gophercloud is pretty hard to mock, so any functions actually making calls to OpenStack are problematic.

@KingDaemonX: I think it'll be better to make sure some of the functions can be worked on by the rest of the participants. You've definitely already proven your dedication and golang proficiency.

**Comment by KingDaemonX** [comment]
Okay!  I will drop this “Getloadbalancersourcerange” that isn’t in the PR and look into some other stuff

**Comment by sakshi-1505** [comment]
>@sakshi-1505: I'll try to find more functions that are lacking unit tests and allow writing tests fairly easily. The problem is that gophercloud is pretty hard to mock, so any functions actually making calls to OpenStack are problematic.

@dulek It's fine if there are not enough functions, I can try contributing to another issue.

> The problem is that gophercloud is pretty hard to mock, so any functions actually making calls to OpenStack are problematic.

How about we run a devstack & prefer to run integration tests for such functions instead of unit tests?

**Comment by majorchork** [comment]
Hello @dulek i'm currently working on
buildMonitorCreateOpts
buildPoolCreateOpt
getSubnetID

**Comment by sakshi-1505** [comment]
I am working on checkListernerPorts, createLoadBalancerStatus, GetLBSourceRanges.
