### ISSUE TITLE
[all] Investigate enabling of golangci-lint for the repo

### ISSUE THREAD

**Issue by sakshi-1505** [kubernetes/cloud-provider-openstack#2407]
**Is this a BUG REPORT or FEATURE REQUEST?**:

 /kind feature

**What happened**:

We have configuration rules for golangci but we are not using the tool in our pr-checks or commits to main.

**What you expected to happen**:

We should enable pr-checks for golangci-lint to have better code quality.

**Comment by sakshi-1505** [comment]
cc: @dulek

**Comment by dulek** [comment]
You mean `make check` doesn't run it? It think it does. Then there's a job checking that in CI too: https://github.com/kubernetes/test-infra/blob/7627101a17a5d04f4306f0ae56469f135a7bfa3b/config/jobs/kubernetes/cloud-provider-openstack/cloud-provider-openstack-config.yaml#L19-L20

**Comment by sakshi-1505** [comment]
Oh my fault, I was only looking at gh-actions check where as most of k8s repo use custom prow job.
