### ISSUE TITLE
[cinder-csi-plugin] Add metadata in creation of volume

### ISSUE THREAD

**Issue by Kortekaasy** [kubernetes/cloud-provider-openstack#2436]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
> /kind bug
/kind feature

**What happened**:
My cloud provider uses the metadata field in the [volume creation API call](https://docs.openstack.org/api-ref/block-storage/v3/#create-a-volume) to enable e.g. encrypted volumes. Looking at the documentation & source code, it doesn't look like it's possible at this moment to such metadata to a PVC. If this is really not possible at the moment, could anyone give me some pointers on where to start to add such functionality?

**Comment by kayrus** [comment]
See also #2327.

**Comment by jichenjc** [comment]
@kayrus I assume you are talking about https://github.com/kubernetes/cloud-provider-openstack/issues/2327#issuecomment-1735749569 ?  want to split the design of LB and CSI into different issue and can cross link 

https://github.com/kubernetes/cloud-provider-openstack/blob/master/pkg/csi/cinder/controllerserver.go#L107
is something we can refer to

**Comment by Kortekaasy** [comment]
I see that this is somewhat related to https://github.com/kubernetes/cloud-provider-openstack/issues/2327#issuecomment-1735749569, but I also see development has stagnated there. If I were to implement adding metadata to volume creation, could anyone give me some pointers?

**Comment by dulek** [comment]
> I see that this is somewhat related to [#2327 (comment)](https://github.com/kubernetes/cloud-provider-openstack/issues/2327#issuecomment-1735749569), but I also see development has stagnated there. If I were to implement adding metadata to volume creation, could anyone give me some pointers?

At a glance I'd say it's almost implemented at [1]. What you would need to add is to read some more annotations at [2] (and maybe [3], but ephemeral volumes might not need that?) and pass them to `properties` variable. On the implementation PR we'll probably spend some time figuring out how to properly name the annotation itself.

[1] https://github.com/kubernetes/cloud-provider-openstack/blob/e87f50614b96a6af6095660aa6a77457223b344b/pkg/csi/cinder/openstack/openstack_volumes.go#L66-L68
[2] https://github.com/kubernetes/cloud-provider-openstack/blob/e87f50614b96a6af6095660aa6a77457223b344b/pkg/csi/cinder/controllerserver.go#L105-L112
[3] https://github.com/kubernetes/cloud-provider-openstack/blob/e87f50614b96a6af6095660aa6a77457223b344b/pkg/csi/cinder/nodeserver.go#L130
