### ISSUE TITLE
[occm] service account `cloud-controller-manager` cannot patch service object

### ISSUE THREAD

**Issue by till** [kubernetes/cloud-provider-openstack#2440]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:

Installed the OCCM helm chart and wanted to provision an Octavia load  balancer (via the haproxy-ingress helm chart) but it's stuck in pending.

The error is:

```
Error syncing load balancer: failed to ensure load balancer: failed to patch service object haproxy-ingress/haproxy-ingress: services "haproxy-ingress" is forbidden: User "system:serviceaccount:kube-system:cloud-controller-manager" cannot patch resource "services" in API group "" in the namespace "haproxy-ingress"
```

Probably related: #1722

**What you expected to happen**:

A load balancer.

**How to reproduce it**:

Install the helm chart: `openstack-cloud-controller-manager`, version: `2.28.0`

**Anything else we need to know?**:

The helm chart creates a SA which is also used by the `openstack-cloud-controller` pod. This SA seems to have the correct CRB as far as I can tell.

When the pod starts, I see another SA created, `cloud-controller-manager`. This SA has no CRB to be able to patch the service object. I am not sure why this is created or when. It doesn't seem to come with the helm chart (see below) and I am not creating it anywhere else as far as I see.

Somewhat a side effect, the created SA (`cloud-controller-manager`) also blocks helm from doing updates to the OCCM:

> UPGRADE FAILED: rendered manifests contain a resource that already exists. Unable to continue with update: ServiceAccount "cloud-controller-manager" in namespace "kube-system" exists and cannot be imported into the current release: invalid ownership metadata; label validation error: missing key "app.kubernetes.io/managed-by": must be set to "Helm"; annotation validation error: missing key "meta.helm.sh/release-name": must be set to "openstack-cloud-controller-manager"; annotation validation error: missing key "meta.helm.sh/release-namespace": must be set to "kube-system"

**Comment by wwentland** [comment]
This should have been fixed in https://github.com/kubernetes/cloud-provider-openstack/pull/2332. The fix is, however, not yet in a stable release, but you can install a pre-release version with:

```
helm upgrade -n kube-system -i openstack-ccm cpo/openstack-cloud-controller-manager --version 2.29.0-alpha.2 --values openstack-ccm-values.yaml
```

**Comment by till** [comment]
@wwentland I'll give it a try. Is there a way to see all chart releases and changelogs somewhere? I searched with helm, it looks like what I installed was the latest available.

**Comment by wwentland** [comment]
> @wwentland I'll give it a try. Is there a way to see all chart releases and changelogs somewhere? I searched with helm, it looks like what I installed was the latest available.

That version is a pre-release and helm would not install it by default. I'm currently trying to get those changes backported, but for the time being you would have to specify the version explicitly.

Please note that you might have to delete the `cloud-controller-manager` service account in the `kube-system` namespace if it exists, as upgrading with helm would fail otherwise.


All releases can be found on https://github.com/kubernetes/cloud-provider-openstack/releases

**Comment by till** [comment]
> All releases can be found on https://github.com/kubernetes/cloud-provider-openstack/releases

So it seems like the actual OCCM `1.28.0` has a changelog there, but none of the other releases tell me much about what's going on. As in, is it safe to run the alphas for production?

Or can I mix the alpha helm chart with a (maybe) more stable `1.28.x` of the OCCM?

Sorry for asking so many question.

**Comment by wwentland** [comment]
> I don't see other tags with helm search either. That's what I was curious about.

You can include pre-releases by passing the `--devel` option to Helm similar to:

```
❯ helm search repo cloud-controller-manager --devel
NAME                                  	CHART VERSION 	APP VERSION	DESCRIPTION                                  
cpo/openstack-cloud-controller-manager	2.29.0-alpha.3	v1.28.0    	Openstack Cloud Controller Manager Helm Chart
```
> So it seems like the actual OCCM 1.28.0 has a changelog there, but none of the other releases tell me much about what's going on. As in, is it safe to run the alphas for production?

I would advise against running alpha/pre-releases in production, but it is important to keep in mind that this is primarily about the helm chart itself.

I'll see if we can get those helm chart changes backported, which should alleviate that concern.

**Comment by till** [comment]
Is there anything I can do to help?

Is there a way to review the changes to the helm chart. As in, to figure out how far away it is from a stable release?

**Comment by till** [comment]
@wwentland what needs to happen for the releases? The latest is still `2.28.0`. Was looking for a bump.

**Comment by wwentland** [comment]
> @wwentland what needs to happen for the releases? The latest is still 2.28.0. Was looking for a bump.

It looks fine here:

```
❯ helm repo update
Hang tight while we grab the latest from your chart repositories...
...Successfully got an update from the "cpo" chart repository

❯ helm search repo openstack-cloud-controller-manager
NAME                                  	CHART VERSION	APP VERSION	DESCRIPTION                                  
cpo/openstack-cloud-controller-manager	2.28.2       	v1.28.1    	Openstack Cloud Controller Manager Helm Chart
```

Which is https://github.com/kubernetes/cloud-provider-openstack/releases/tag/openstack-cloud-controller-manager-2.28.2 and what you want.

**Comment by wwentland** [comment]
@till I was wondering if you were able to get it to work with the new version? If so, we should probably close this issue.

**Comment by till** [comment]
Agree! Been meaning to, but Monday. I'll update by tomorrow.

**Comment by till** [comment]
Sorry, took longer than expected. All seems to be working now! Thanks @wwentland

**Comment by wwentland** [comment]
Amazing! Thank you for the follow-up, @till
