### ISSUE TITLE
[occm] loadbalancer doesn't honor the `spec.loadBalancerIP` on service update

### ISSUE THREAD

**Issue by kayrus** [kubernetes/cloud-provider-openstack#2443]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:

Documentation [says](https://github.com/kubernetes/cloud-provider-openstack/blob/master/docs/openstack-cloud-controller-manager/expose-applications-using-loadbalancer-type-service.md#creating-service-by-specifying-a-floating-ip):

> Sometimes it's useful to use an existing available floating IP rather than creating a new one, especially in the automation scenario. In the example below, 122.112.219.229 is an available floating IP created in the OpenStack Networking service.

>> NOTE: If 122.112.219.229 is not available, a new floating IP will be created automatically from the configured public network. If 122.112.219.229 is already associated with another port, the Service creation will fail.

However once I create a svc with no `spec.loadBalancerIP` defined, OCCM assigns the random FIP to a LB. If I want to change the FIP on the existing service by setting the `spec.loadBalancerIP`, the setting persists, but the actual FIP is not assigned.

**What you expected to happen**:

I expect OCCM to assign a new FIP once `spec.loadBalancerIP` is changed.

**How to reproduce it**:

* create a service without a FIP
* assign a  `spec.loadBalancerIP` to a desired value
* FIP is not changed

**Anything else we need to know?**:

https://github.com/kubernetes/cloud-provider-openstack/blob/ed517e1f07057cd439542c73bff12102d8849dde/pkg/openstack/loadbalancer.go#L1039-L1041

see also #2377, where this bug is seen more clearly.

**Environment**:
- openstack-cloud-controller-manager(or other related binary) version: master
- OpenStack version: ???
- Others: ???

**Comment by zetaab** [comment]
@kayrus spec.LoadbalancerIP is deprecated, see https://github.com/kubernetes/cloud-provider-gcp/issues/371

**Comment by zetaab** [comment]
and imo current code is working like expected. If your tenant has floating ip address that is specified, it will use that.

**Comment by yang-wang11** [comment]
Yes, I agree with @zetaab, if possible, we can adopt the new way of assigning the floating IP for LB. nevertheless, one thing I would like to clarify is that ["Field Service.Spec.LoadBalancerIP is deprecated, and it will not be deleted"](https://github.com/kubernetes/kubernetes/pull/117051).

I have verified the feature of updating the Octavia LB with a single floating IP, as described in the [documentation](https://docs.openstack.org/api-ref/load-balancer/v2/index.html#update-a-load-balancer). and the result is FIP of this LB has been changed.

I would like to propose fixing this issue to ensure consistency with the documentation. I've noticed that [the logic](https://github.com/kubernetes/cloud-provider-openstack/blob/92bde6cd95b42ff0cc8014e3b66e58fa95b7daf0/pkg/openstack/loadbalancer.go#L959) currently only allows newly created LBs to use the LoadBalancerIP. Perhaps we could consider a hot-fix similar to the method described below.

```go
if (floatIP == nil && loadBalancerIP != "") || (floatIP != nil && floatIP. FloatingIP != loadBalancerIP) {
    // check & attach the FloatingIP to LB
}
```

**Comment by dulek** [comment]
From my perspective it would be best to switch to the annotation first. It doesn't hurt to use the existing field, but note that very soon we'll be adding dual stack LBs support. There I'll advocate to ignore `spec.loadBalancerIP` existence completely and only use annotations.

**Comment by yang-wang11** [comment]
I believe the annotation approach mirrors the existing method(the same logic). For this issue, I intend to address it ASSP. 
Additionally, I'm aware @kayrus makes efforts to significantly refactor for the enhancement, maybe the support for dual stack LBs via annotation can be encompassed within that PR or later.

**Comment by jichenjc** [comment]
seems PR #2451 is intend to fix with older way while we actually want to use loadbalancer.openstack.org/floating-ip
are we good with temp fix first then go with the annotation ?

**Comment by yang-wang11** [comment]
@jichenjc, I've incorporated the annotation approach and adjusted the priority for compatibility purposes.

**Comment by jeffyjf** [comment]
I notice this PR #2451 introduce a new annotation `loadbalancer.openstack.org/floating-ip`, I like this change. But, It seems like similar with `service.beta.kubernetes.io/openstack-internal-load-balancer` in semantics. IMO, If a LB has FloatingIP it is external and vice versa. So, whether or not we should deprecate `service.beta.kubernetes.io/openstack-internal-load-balancer` after we introduced `loadbalancer.openstack.org/floating-ip`.  And I strongly suggest that we clarify the definition and relationship of `loadbalancer.openstack.org/floating-ip` and `service.beta.kubernetes.io/openstack-internal-load-balancer` and `service.spec.loadBalancerIP` firstly. It seems like a bit untidy now.

**Comment by zetaab** [comment]
@jeffyjf well if you look these annotations https://github.com/kubernetes/cloud-provider-openstack/blob/eeba48501bf743e3992093bd806a513ad103a347/pkg/openstack/loadbalancer.go#L69-L103 there are not many service.beta.kubernetes.io annotations. Which means that new ones will be using loadbalancer.openstack.org

**Comment by jeffyjf** [comment]
@zetaab I agree with you, I also think there are not many service.beta.kubernetes.io annotations.  I just think the annotation `service.beta.kubernetes.io/openstack-internal-load-balancer` is redundant after we introduce `loadbalancer.openstack.org/floating-ip`. Service has floating-ip means it is external and Service has no floating-ip means it is internal.

**Comment by zetaab** [comment]
it does not mean always that. When you create new loadbalancer and want to provision new floating ip, you do not need to define `loadbalancer.openstack.org/floating-ip` annotation. Only if someone wants to use existing ip `loadbalancer.openstack.org/floating-ip` is useful.

**Comment by dulek** [comment]
Yep, what Jesse says. All LBs are external in CPO by default. We cannot change that. We could probably make setting `loadbalancer.openstack.org/floating-ip=None` internal, but I don't exactly see that much value in the effort. Current code doing internal LBs is super complicated already due to shared LBs.

**Comment by jeffyjf** [comment]
Thanks @zetaab @dulek. I got it.

> Current code doing internal LBs is super complicated already due to shared LBs.

I really agree that.

**Comment by yang-wang11** [comment]
The annotation proposal from @kayrus has been revised. as follows:
```
loadbalancer.openstack.org/floatingip: designed for the dual stack
loadbalancer.openstack.org/floatingip-v4:   same as the spec.loadBalancerIP
```
from my perspective, if the intention is to utilize annotation for dual-stack support, maintaining a single, clear annotation should be considered for simplicity and to avoid confusion.

**Comment by zetaab** [comment]
and how would that work if I have dualstack setup and I specify also loadbalancer.openstack.org/floatingip-v4? Which annotation it should use?

**Comment by dulek** [comment]
/remove-lifecycle stale

Still valid to me.
