### ISSUE TITLE
Associate FIP with LB port via LoadBalancerIP attribute

### ISSUE THREAD

**Issue by ssfilatov** [kubernetes/cloud-provider-openstack#245]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> /kind feature

I'd like to be able to associate allocated floating IP address with k8s service.
We could extend cloudprovider so that when LoadBalancerIP is mentioned in service spec, first we try to GET it and then associate with the loadbalancer port. If we fail to either GET it floating IP with the port, we fall back to creating.

I can provide a patch for this if you think it's an okay behavior.

**Comment by lingxiankong** [comment]
I'm ok with this feature request, but I prefer to keep the svc pending if the provided IP address is invalid(either not found or getting error), and provide the information in the svc events.

**Comment by zetaab** [comment]
Currently this loadbalancerip can be used to allocate subnet ip from the openstack network. However, I am thinking is anyone using this feature and if yes, why? I am also thinking that we could use this LoadBalancerIP field to use ecisting floatingip and attach that to created lbaas. 

It is breaking change but IMO not that critical. @dims @anguslees any thoughts?

**Comment by zetaab** [comment]
Did I understand correctly: 

old behaviour (this will make ip address to openstack subnet):
annotation + loadbalancerip

new behaviour (this will try to attach floatingip from openstack tenant to lbaas):
loadbalancerip

**Comment by ssfilatov** [comment]
How does the new behaviour work if the annotation says that we use LB without external network?
Why don't we keep the old behaviour with the internal annotation and allocate FloatingIP otherwise

**Comment by zetaab** [comment]
one option is that we do not touch to LoadBalancerIP at all. Instead we just create new annotation like `loadbalancer.openstack.org/floatingip` which defines the floatingip address that it should use. It is backward compatible and does not break anything

**Comment by zetaab** [comment]
actually this is already trying to create new floatingip if you specify loadBalancerIP field https://github.com/kubernetes/kubernetes/blob/v1.11.1/pkg/cloudprovider/providers/openstack/openstack_loadbalancer.go#L973 . Example


```
kind: Service
apiVersion: v1
metadata:
  name: demoapp-lb2
spec:
  loadBalancerIP: "10.222.134.126"
  type: LoadBalancer
  selector:
    name: demoapp-test
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
```

However, at least in our openstack I do not have permissions to do it: is disallowed by policy rule (rule:create_floatingip and rule:create_floatingip:floating_ip_address)

So instead of always creating we should have also possibility to use existing IP which is in project already.
