### ISSUE TITLE
'unknown revision v0.0.0' errors caused by the 'k8s.io/kubernetes' dependency

### ISSUE THREAD

**Issue by ProbstDJakob** [kubernetes/cloud-provider-openstack#2490]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug

**What happened**:
When executing `go list -m all` multiple dependencies can not be resolved due to invalid versions. This command (with some additional flags) is used by JetBrain's GoLand to sync the dependencies and since the command fails, the IDE is not capable to resolve any dependency which results in a huge pile of errors per file.

**What you expected to happen**:
That the command completes successfully and prints out all modules.

**How to reproduce it**:
Clone the repository and execute the command `go list -m all`. This will produce the following errors:
```txt
go: k8s.io/cluster-bootstrap@v0.0.0: invalid version: unknown revision v0.0.0
go: k8s.io/dynamic-resource-allocation@v0.0.0: invalid version: unknown revision v0.0.0
go: k8s.io/endpointslice@v0.0.0: invalid version: unknown revision v0.0.0
go: k8s.io/kube-aggregator@v0.0.0: invalid version: unknown revision v0.0.0
go: k8s.io/kube-controller-manager@v0.0.0: invalid version: unknown revision v0.0.0
go: k8s.io/kube-proxy@v0.0.0: invalid version: unknown revision v0.0.0
go: k8s.io/kube-scheduler@v0.0.0: invalid version: unknown revision v0.0.0
go: k8s.io/legacy-cloud-providers@v0.0.0: invalid version: unknown revision v0.0.0
go: k8s.io/sample-apiserver@v0.0.0: invalid version: unknown revision v0.0.0
```

**Anything else we need to know?**:
The problem seems to be the dependency `k8s.io/kubernetes`. As described [here](https://github.com/kubernetes/kubernetes/issues/90358#issuecomment-617859364) (and discussed in more detail [here](https://github.com/kubernetes/kubernetes/issues/90358)) `k8s.io/kubernetes` should not be used as a dependency. Removing the dependency from the `go.mod` and executing the command again will result in a proper list of the modules (and the IDE is able to resolve the dependencies), but building the code will fail since some files depend on `k8s.io/kubernetes` (mostly tests).
This issue may be related to #1633 and #347

**Environment**:
- openstack-cloud-controller-manager(or other related binary) version:
- OpenStack version:
- Others:

**Comment by kayrus** [comment]
running a `go mod tidy` brings the `k8s.io/kubernetes` dependency back, since OCCM test code relies on the `k8s.io/kubernetes/test/e2e/...` packages.
Why do you need to run a `go list -m all` command?

**Comment by ProbstDJakob** [comment]
I do not need the command, but as I wrote JetBrain's GoLand executes the command to resolve the dependencies. Since the command fails, the error indicators on the right within a source file look like the red carpet since the IDE can not resolve the imports.

I know where the the `k8s.io/kubernetes` dependency is used, but I do not know how to replace it since the list provided at [the kubernetes repo](https://github.com/kubernetes/kubernetes/blob/master/staging/README.md) does not include any of the imported modules as far as I can tell (I usually do not program in go and I am new to the source code of k8s).

**Comment by ProbstDJakob** [comment]
I will look into it next week and open a PR, but what about the line in the `occm/main.go`? Is it safe to remove it or how should I handle that?

**Comment by kayrus** [comment]
The #2486 should fix this issue

**Comment by kayrus** [comment]
> Why do we even do that? I don't see that pattern in other cloud providers. Maybe this one can be removed.

> Is it safe to remove it or how should I handle that?

I don't know what does it do. It was added in https://github.com/kubernetes/cloud-provider-openstack/pull/234/commits/0c8a77402a87b7abd8d0173ec229966c09e67064#diff-c19a66ed1fb964264d7bd09434b6bdbb184644ff0e64154c88d69e10acc26f97R35
If someone has time to investigate this code line, please go ahead.

**Comment by dulek** [comment]
> > Why do we even do that? I don't see that pattern in other cloud providers. Maybe this one can be removed.
> 
> > Is it safe to remove it or how should I handle that?
> 
> I don't know what does it do. It was added in [0c8a774#diff-c19a66ed1fb964264d7bd09434b6bdbb184644ff0e64154c88d69e10acc26f97R35](https://github.com/kubernetes/cloud-provider-openstack/commit/0c8a77402a87b7abd8d0173ec229966c09e67064#diff-c19a66ed1fb964264d7bd09434b6bdbb184644ff0e64154c88d69e10acc26f97R35) If someone has time to investigate this code line, please go ahead.

@dims, maybe you have a clue why it was done?

**Comment by dulek** [comment]
@kayrus: Is this fixed…?

**Comment by ProbstDJakob** [comment]
Sorry for the late response. Yes it seems to work.
