### ISSUE TITLE
[csi-cinder-plugin] Support volume basic encryption

### ISSUE THREAD

**Issue by NotTheEvilOne** [kubernetes/cloud-provider-openstack#2524]
/kind feature

**What happened**:
Currently volumes can be encrypted if the required features are set up in OpenStack (and the Volume Type defined at the `StorageClass` is correct) but the user of an `csi-cinder-plugin` deployment does not know if the `PersistentVolume` is really encrypted or not from within k8s.

**What you expected to happen**:
This feature request is most likely one of two requesting support to set a parameter at the `StorageClass` to validate if volumes created are flagged as `encrypted` in the [API response](https://docs.openstack.org/api-ref/block-storage/v3/#create-a-volume).

**How to reproduce it**:
Create a `pvc` for a `storageclass` named `encryptedvolume` without the correct Volume Type (default `LUKS`) set. Volume will not be encrypted but handled correctly by the CSI driver. With the `encrypted` parameter set (if PR is accepted) an error will be showed that the volume should be encrypted but is not at the block storage layer.

**Anything else we need to know?**:
Another issue will be created that requests support "bring your own key" approach to both OpenStack and the CSI driver. It's part of an effort to enhance the encryption support in OpenStack and k8s as part of the [Sovereign Cloud Stack](https://scs.community). I'll reach out to OpenStack for that first and create another PR once support is implemented.

**Comment by medkbadri** [comment]
Hello,

Would a pull request be welcome for this issue?
