### ISSUE TITLE
[barbican-kms-plugin] Container broken in v1.28.1

### ISSUE THREAD

**Issue by GlassOfWhiskey** [kubernetes/cloud-provider-openstack#2531]
/kind bug

The `barbican-kms-plugin:v1.28.1` does not start as the inner command does not recognize the flags correctly. This is due to the fact that flags are parsed before they are declared in the `main.go` code. This behaviour has been solved by PR #2325  , but the fix has not been back-ported to v1.28.1.

**Comment by jichenjc** [comment]
https://github.com/kubernetes/cloud-provider-openstack/pull/2534

**Comment by dulek** [comment]
Do we want to make 1.28.2 now?

**Comment by stephenfin** [comment]
I already fixed this with a bugfix https://github.com/kubernetes/cloud-provider-openstack/pull/2467 so it should not have been necessary to backport the whole feature in https://github.com/kubernetes/cloud-provider-openstack/pull/2534. It looks like we never cut a release after my PR was merged :see_no_evil:

**Comment by dulek** [comment]
This should be fixed in 1.28.2.
