### ISSUE TITLE
[occm] Multi region support information

### ISSUE THREAD

**Issue by sebastienmusso** [kubernetes/cloud-provider-openstack#2543]
**Is this a BUG REPORT or FEATURE REQUEST?:**

/kind feature

**What happened**:
We are currently testing kubernetes deployment on several openstack clusters.
We deployed one occm by openstack and enabled OS_CCM_REGIONAL.
OCCM is mostly used for cloud-node and cloud-node-lifecycle services

**What you expected to happen**:
All seems to work as expected, az1 occm delete node with az1 prefix in providerID field as expected.
Node are added to the cluster with the right provider ID

**Anything else we need to know?**:
What is missing in order to consider this feature as GA ? 
is this testing case ? 
How could we help for this suject

**Environment**:
- openstack-cloud-controller-manager version: v1.29.0
- OpenStack version: Queen (17.6.0)
- Others: kubernetes 1.26.10 / 1.27.8

**Comment by dulek** [comment]
What makes you think this is not a supported thing? Anyway if you want to contribute to this feature, we certainly don't have a CI job testing it, so that sounds like a fair first step.

**Comment by sebastienmusso** [comment]
@dulek 
the "alpha" [https://github.com/kubernetes/cloud-provider-openstack/blob/master/docs/openstack-cloud-controller-manager/using-openstack-cloud-controller-manager.md](url)
make me think that

**Comment by dulek** [comment]
> @dulek the "alpha" in [occm doc](https://github.com/kubernetes/cloud-provider-openstack/blob/master/docs/openstack-cloud-controller-manager/using-openstack-cloud-controller-manager.md#multi-region-support-alpha) make me think that

Ah, here it is! Well, looks like nobody looked at this for 2 years, it should be out of alpha by this time, though I'm not sure how many installations do that and how production-proven it is.

My idea to move forward would probably be to ask about the feature on the #provider-openstack on the K8s Slack. As a next step let's also make it a general option and not just a hacky env var. Then I guess we can assume that we'll try fixing issues as we go. And obviously my CI remark still stays.

**Comment by sebastienmusso** [comment]
> 
Happy to ear that @dulek 

let me look at the CI process and maybe submit a pr (with doc up to date)
