### ISSUE TITLE
Overlapping load balancers when running multiple clusters in the same tenant

### ISSUE THREAD

**Issue by canori01** [kubernetes/cloud-provider-openstack#2571]
/kind bug

What happened:
I'm running a couple of RKE clusters with OpenStack integration in separate tenants each.
When I perform the Istio installation with one ingress gateway and kind: LoadBalancer on the k8s level, I'm getting a load balancer instance with the name "kube_service_kubernetes_istio-system_istio-ingressgateway" and IP from an external network, as expected.

However, when I perform the same Istio installation in different OpenStack tenant on different RKE cluster, I'm not able to create a load balancer instance under the same name, as when I do it so, the occm is trying to re-register the instance, currently running (same name, different UUID)

What you expected to happen:
Load balancers with the same name will be running in parallel.

How to reproduce it:
I assume it's a general issue with lb instances naming, so any service with the same name, configured in different RKE clusters, exposes services by using occm integration to OpenStack. In my case, the Istion instance is the blame.

Anything else we need to know?:

Environment:

OpenStack-cloud-controller-manager(or other related binary) version: Kubernetes v1.27.10
OpenStack version: Yoga

**Comment by dulek** [comment]
The RKE clusters have to set the `--cluster-name` option to a unique cluster identifier when running OCCM. This way the "kubernetes" part will be replaced with that value, and your LBs will not conflict.

As we've faced the same problem in OpenShift, I've recently wrote some code helping with a transition from default `--cluster-name=kubernetes` to the unique value. See #2552. If you'd like to discuss this approach further, please use #2241. I'm going to close this one.

**Comment by canori01** [comment]
That works. Thanks!
