### ISSUE TITLE
[cinder-csi-plugin] How to set my own description when creating a PV

### ISSUE THREAD

**Issue by Ketchup31** [kubernetes/cloud-provider-openstack#2573]
**Is this a BUG REPORT or FEATURE REQUEST?**: 

/kind feature

Hello,

I wish to know if it is possible to set my own desciption of the PV when I request a new volume instead of to have "Created by OpenStack Cinder CSI driver" in openstack volume description. 
I wish to fill this description with particular infos like a userID, timestamp and any usefull info for my app.

If it is not possible, do you intend to implement such feature, as we saw in the source code that "Created by OpenStack Cinder CSI driver" is hard coded.

Thank you for your support.

**Comment by dulek** [comment]
It's currently not possible. I don't think `description` field is semantically valid for the information you want to put there. Sounds like a job for tags, which was previously requested in #2436. It's a valid request in my opinion, but I'm not sure anyone with development resources is looking into this. If you're interested, I dropped a bunch of clues on how to implement that in #2436.

**Comment by jichenjc** [comment]
yes, I think @dulek already provide very good summary here 
https://github.com/kubernetes/cloud-provider-openstack/issues/2436#issuecomment-1999897682

@Ketchup31 do you want to submit PR for that?
