### ISSUE TITLE
Compatibility Matrix

### ISSUE THREAD

**Issue by mlkishkel** [kubernetes/cloud-provider-openstack#2593]
/kind feature

Hello!

Is there any compatibility matrix between cloud-provider-openstack and kubernetes ? Can I for example use 1.30 provider with 1.28 K8S ? Or there can be some some limitations ?

**Comment by jichenjc** [comment]
I don't think we have any such mix, why you don't use 1.28 CPO repo/images instead ?

**Comment by mlkishkel** [comment]
No, there is no problem with using 1.X provider with 1.X k8s. Just was curious can I get last version of provider (for example 1.30) and use it on all my clusters even older ones (1.27/1.28).

Thanks a lot for clarification!
