### ISSUE TITLE
[occm] Support `loadbalancer.openstack.org/flavor-name` instead of only `loadbalancer.openstack.org/flavor-id`

### ISSUE THREAD

**Issue by Sinscerly** [kubernetes/cloud-provider-openstack#2600]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind feature

**What happened**:

Reading the documentation for the cloud-provider-openstack I found it is possible to specify a loadbalancer flavor by id, although it would be handy and simpeler if it is possible to also create one by using the flavor name (if no flavor-id is specified).

**What you expected to happen**:

That a loadbalancer flavor is selected based on the name when the annotation `loadbalancer.openstack.org/flavor-name` is used

**Comment by dulek** [comment]
I think Octavia allows to have multiple flavors using the same name. We could probably just fail when there is more than one flavor of such a name, but that's increasing the complexity of debugging a bit.

Anyway I'm not totally opposed to this.

**Comment by Sinscerly** [comment]
Hi @dulek

It is indeed possible to have the same flavor although an OpenStack admin creates those, so I would guess that the change of having duplicated is not that high. Failing the creation of the loadbalancer would be a good idea then or to fallback to the default by not setting any of the config (so using not the name as none could be found).

**Comment by zetaab** [comment]
at least in our openstack, these flavors are not visible for normal users. How to solve this issue?

**Comment by Sinscerly** [comment]
> at least in our openstack, these flavors are not visible for normal users. How to solve this issue?

Do you currently provide them with an ID? Then a name would make it easier.

**Comment by zetaab** [comment]
yes, we provide them with id. I do not see how `name` could make it easier from the api perspective. https://docs.openstack.org/api-ref/load-balancer/v2/#create-a-load-balancer takes `flavor_id` NOT `flavor_name`. So it means that somehow `name` should first be converted to `id`, and at least we do not have API which provides this information.

**Comment by zetaab** [comment]
Right, I did not know about that endpoint. Seems to work for me as well. So it should be open for normal openstack users as well.
