### ISSUE TITLE
Kubernetes nodes lose InternalIP and ExternalIP temporarily

### ISSUE THREAD

**Issue by stieler-it** [kubernetes/cloud-provider-openstack#280]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**: InternalIP and ExternalIP are lost for some nodes (in our case: 2 of 5 are broken). I am not sure if this is related to the cloud provider.

```
>kubectl describe node intern-master1
...
Addresses:
  Hostname:  intern-master1

>kubectl describe node intern-worker1
...
Addresses:
  InternalIP:  10.0.0.15
  ExternalIP:  (hidden)
  Hostname:    intern-worker1
```

This leads to problems, e.g. when trying to create an L4 load balancer:
`Error creating load balancer (will retry): failed to ensure load balancer for service gitlab/gitlab-nginx-ingress-controller: error getting address for node intern-master1: no address found for host`

**What you expected to happen**: I expect both InternalIP and ExternalIP not to change if infrastructure doesn't change

**How to reproduce it (as minimally and precisely as possible)**: I can't tell it just "happened". Last week it worked, today it doesn't.

**Anything else we need to know?**: I saw a similar bug report here https://github.com/Azure/acs-engine/issues/3503

**Environment**:
- openstack-cloud-controller-manager version: N/A
- OS (e.g. from /etc/os-release): RancherOS v1.4.0
- Kernel (e.g. `uname -a`): Linux intern-worker1 4.14.32-rancher2 #1 SMP Fri May 11 11:30:31 UTC 2018 x86_64 GNU/Linux
- Install tools: Rancher 2.0.x with RKE
- Others: Kubernetes: Client v1.11.2, Server v1.11.1

**Comment by stieler-it** [comment]
After starting new nodes a few days ago that should replace the corrupt nodes, I now noticed that the state has changed.

master1 had no internal IP two days ago, now shows it again
master2 was started two days ago, now has lost its IP addresses
master3 was started two days ago and still has its IP addresses

So transitions in all directions seem to be possible. Maybe a failing refresh task?

**Comment by stieler-it** [comment]
I just got the information from someone else that they did not experience this issue with K8S 1.10.5 but after upgrading to 1.11.1.

**Comment by stieler-it** [comment]
Looks like there might have been changes to the OpenStack cloud provider with K8S 1.11.x: https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG-1.11.md#sig-openstack

**Comment by desaintmartin** [comment]
Experiencing this as well, after switching to 1.11.3 (and from iptables to ipvs).

**Comment by desaintmartin** [comment]
I experience a related issue since upgrading to 1.11 (1.10.x -> 1.11.3).

I get repeating logs on a few machines (interestingly, only about ~1/3 of nodes of the cluster)
`Sep 26 08:45:57 kubernetesnode16 kubelet[29922]: W0926 08:45:57.215477   29922 kubelet_node_status.go:1114] Failed to set some node status fields: failed to get node address from cloud provider that matches ip: 51.38.44.227`

That seems to cause some intermittent network outage within the cluster (kubedns on this machine is sometimes inaccessible).

Restarting kubelet solves the problem (temporarily? Let's see).

It looks like this is the same cause, this is why I post here instead of creating a new issue.

**Comment by alexandrem** [comment]
They might have fixed this bug https://github.com/kubernetes/kubernetes/pull/65226

Haven't tested the new code yet.

**Comment by mitchellmaler** [comment]
A workaround would be to use the configdrive and setup the metadata search to only search using that. This way it won't use the api and fail.

**Comment by openstacker** [comment]
We have same issue with clould-provier-openstack and k8s v1.11.2

**Comment by openstacker** [comment]
@mitchellmaler Hi Mitchell, would you mind explaining more details about the workaround? Are you talking about this
`[Metadata]search-order=configDrive`

in cloud-config? Thanks.

**Comment by mitchellmaler** [comment]
@openstacker I tried that and I thought it was working but after a few days I had the same issue. 
Was premature :)

**Comment by stieler-it** [comment]
We upgraded to K8s v1.11.5 a few days ago and the bug seems to be gone.

**Comment by bosatsu** [comment]
New to kubernetes, but I believe I may be seeing this issue as well in `v1.12.3`:

```
$ kubectl get nodes -o wide
NAME            STATUS   ROLES    AGE   VERSION   INTERNAL-IP     EXTERNAL-IP   OS-IMAGE                KERNEL-VERSION               CONTAINER-RUNTIME
p3dk8sautoing   Ready    node     72m   v1.12.3   <none>          <none>        CentOS Linux 7 (Core)   3.10.0-862.14.4.el7.x86_64   docker://18.6.1
p3dk8sautomon   Ready    node     72m   v1.12.3   10.33.106.138   <none>        CentOS Linux 7 (Core)   3.10.0-862.14.4.el7.x86_64   docker://18.6.1
p3dk8sautomtr   Ready    master   73m   v1.12.3   <none>          <none>        CentOS Linux 7 (Core)   3.10.0-862.14.4.el7.x86_64   docker://18.6.1
p3dk8sautowkr   Ready    node     72m   v1.12.3   10.33.108.118   <none>        CentOS Linux 7 (Core)   3.10.0-862.14.4.el7.x86_64   docker://18.6.1
```

```
Jan 02 11:40:56 p3dk8sautomtr kubelet[10488]: I0102 11:40:56.885054   10488 setters.go:72] Using node IP: "10.33.88.37"
Jan 02 11:40:56 p3dk8sautomtr kubelet[10488]: W0102 11:40:56.885105   10488 kubelet_node_status.go:463] Failed to set some node status fields: failed to get node address from cloud provider that matches ip: 10.33.88.37
Jan 02 11:41:06 p3dk8sautomtr kubelet[10488]: I0102 11:41:06.900189   10488 setters.go:72] Using node IP: "10.33.88.37"
Jan 02 11:41:06 p3dk8sautomtr kubelet[10488]: W0102 11:41:06.900273   10488 kubelet_node_status.go:463] Failed to set some node status fields: failed to get node address from cloud provider that matches ip: 10.33.88.37
```

Let me know if there is any additional output that would help to confirm or refute.

**Comment by prein** [comment]
I'm experiencing this in v1.11.5
