### ISSUE TITLE
Cinder provisioner doesn't work on VMware Integrated OpenStack (VIO)

### ISSUE THREAD

**Issue by praseodym** [kubernetes/cloud-provider-openstack#281]
/kind bug

The external Cinder provisioner doesn't work on VMware Integrated OpenStack (VIO), whereas the Kubernetes in-tree OpenStack cloud provider [handles this platform just fine](https://github.com/kubernetes/kubernetes/blob/3a8a7114fa22bd687302d31548bb393e2de9f0cd/pkg/cloudprovider/providers/openstack/openstack_volumes.go#L475-L501). The external cloud provider logs ["Unsupported persistent volume type: VMDK"](https://github.com/kubernetes/cloud-provider-openstack/blob/5bbf82c0054af6ad87b061fe9355bfe5a1b71f9a/pkg/volume/cinder/provisioner/mapper.go#L45) and never manages to mount the volume.

**Environment**:
- openstack-cloud-controller-manager version: 0.2.0
- Platform: VMware Integrated OpenStack (VIO) / ESXi
- OS (e.g. from /etc/os-release): Ubuntu 18.04.1
- Install tools: kubeadm

**Comment by alcheagle** [comment]
I am getting a similar error, with a different fs: ``Unable to create volume mapper: Unsupported persistent volume type: nfs``

**Comment by sbueringer** [comment]
We're currently running Cinder CSI 1.0.1 together with cloud-controller-manager build from master in March and this works for us (with VIO 4.x).

Is the issue still there? (I'm just interested because the issue might be caused by another VIO/OpenStack version and we're migrating to VIO 5 soon)

**Comment by praseodym** [comment]
@sbueringer haven’t tested but I have no indication that VIO 5 would be using something else than VMDK-based volumes for Cinder.

**Comment by sbueringer** [comment]
We're running VIO4 & VIO5 in production with Kubernetes 1.13 and the CSI Cinder plugin (all with VMDKs). No issues whatsoever. I would close this issue here until more evidence shows up

**Comment by praseodym** [comment]
@sbueringer thanks for the update! I don’t have any recent evidence against this so I agree with closing this issue.
