### ISSUE TITLE
client-keystone-auth: using a wrong password will return a wrong error message

### ISSUE THREAD

**Issue by zioproto** [kubernetes/cloud-provider-openstack#285]
This is a bug report.
/kind bug

**What happened**:

Using `./client-keystone-auth` with correct credential will return the following JSON:
```
{
	"apiVersion": "client.authentication.k8s.io/v1alpha1",
	"kind": "ExecCredential",
	"status": {
		"token": "secret",
		"expirationTimestamp": "2018-09-13T09:48:51Z"
	}
}
```

However if there is a typo in the password the following json is returned:
```
{
	"apiVersion": "client.authentication.k8s.io/v1alpha1",
	"kind": "ExecCredential",
	"spec": {
		"response": {
			"code": 401,
			"header": {},
		},
	}
}
```
When this is returned to `kubectl` the user see this error message:
```
$ kubectl get pods
No resources found.
Unable to connect to the server: getting credentials: decoding stdout: couldn't get version/kind; json parse error: invalid character '}' looking for beginning of object key string
```

**What you expected to happen**:

The user should a meaningfull error, like `Authorization failed`

**How to reproduce it (as minimally and precisely as possible)**:

Try to authenticate with a wrong password of your keystone user.

**Comment by tipabu** [comment]
Should be resolved by https://github.com/kubernetes/cloud-provider-openstack/commit/8341f8ee68ad8aacf62e0e39ca8507d98e36ce11 (wherein we start using a `errRespTemplate` that's valid JSON).
