### ISSUE TITLE
Add Features in Cinder CSI Driver 

### ISSUE THREAD

**Issue by adisky** [kubernetes/cloud-provider-openstack#301]
/kind feature

**What happened**:
With CSI v0.3.0 New Plugin Capabilties are added including Snapshot and Topology API, This features needs to be included in Cinder CSI driver.

Following CSI Interface are not implemented in cinder csi driver
 **Identity Service** 
 **Controller Service** 
    - ListVolumes, GetCapacity, ValidateVolumeCapabilities , ControllerGetCapabilities, CreateSnapshot, 
       DeleteSnapshot, ListSnapshots 
 **Node Service** 
    - NodeStageVolume , NodeUnstageVolume , NodeGetVolumeStats , NodeGetCapabilities

We need to check which interface we can implement, if not possible to implement we can atleast add them with default implementation.

https://github.com/container-storage-interface/spec/blob/master/spec.md

**Comment by adisky** [comment]
I am working on this.

**Comment by jichenjc** [comment]
ok, I don't know you are working on this :) as I am trying to try CSI functions and find some missing parts
so I will keep an eye on this and find something that you are not working to wok

**Comment by adisky** [comment]
@jichenjc  No problem, we can work on this together :), just mention here (I will also) when you start working on a particular feature, so that it does not conflict

**Comment by jichenjc** [comment]
I made some changes to create snapshot and seems it works, need add UT ...
so record here to avoid conflict :)

**Comment by ramineni** [comment]
I'm working on topology support

**Comment by jichenjc** [comment]
ControllerExpandVolume need to be added as well..
