### ISSUE TITLE
Failed to find suitable endpoint from service catalog

### ISSUE THREAD

**Issue by xlucas** [kubernetes/cloud-provider-openstack#312]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**: When I try to run the nginx example for the cinder CSI plugin, volume provisionning fails with the given error in the csi-provisionner container of the csi-provisioner-cinderplugin statefulset:

```
I1002 16:50:19.335338       1 controller.go:1167] scheduleOperation[provision-default/csi-pvc-cinderplugin[3ecb435b-c663-11e8-bace-fa163e19759e]]
E1002 16:50:19.692558       1 controller.go:895] Failed to provision volume for claim "default/csi-pvc-cinderplugin" with StorageClass "csi-sc-cinderplugin": rpc error: code = Unknown desc = No suitable endpoint could be found in the se
rvice catalog.
E1002 16:50:19.693439       1 goroutinemap.go:150] Operation for "provision-default/csi-pvc-cinderplugin[3ecb435b-c663-11e8-bace-fa163e19759e]" failed. No retries permitted until 2018-10-02 16:50:20.193333785 +0000 UTC m=+77.968082186 (
durationBeforeRetry 500ms). Error: "rpc error: code = Unknown desc = No suitable endpoint could be found in the service catalog."
I1002 16:50:21.355575       1 leaderelection.go:198] stopped trying to renew lease to provision for pvc default/csi-pvc-cinderplugin, task failed
```

The nginx pod being stuck in this state:

```
Events:
  Type     Reason            Age                From               Message
  ----     ------            ----               ----               -------
  Warning  FailedScheduling  0s (x11 over 12s)  default-scheduler  pod has unbound PersistentVolumeClaims (repeated 2 times)
```

And the associated persistent volume claim stays in the pending state:

```
NAME                   STATUS    VOLUME    CAPACITY   ACCESS MODES   STORAGECLASS          AGE
csi-pvc-cinderplugin   Pending                                       csi-sc-cinderplugin   22m
```

**What you expected to happen**:

The volume should be properly provisionned.

**How to reproduce it (as minimally and precisely as possible)**:

1. Create `cloud-config` with
```ini
[Global]
region=<region>
username=<username>
password=<password>
auth-url=<auth_v3_url>
domain-name=<domain-name>

[BlockStorage]
bs-version=v2
```
2. `kubectl --namespace=kube-system create configmap cloud-config --from-file=cloud-config`
3. `kubectl apply -f manifests/controller-manager/openstack-cloud-controller-manager-ds.yaml`
4. `base64 -w0 < cloud-config`
5. Replace the result of the above command in `manifests/cinder-csi-plugin/csi-secret-cinderplugin.yaml`, `data.cloud.conf` field.
6. `kubectl apply -f manifests/cinder-csi-plugin`
7. `kubectl apply -f examples/cinder-csi-plugin`

**Anything else we need to know?**: 
- I've tried multiple combinations within the `[Global]` section of the cloud-config to no avail (v2/v3, with or without the tenant-name/tenant-id, domain-name/domain-id...)
- I've made sure nodes can join the provider's openstack services and can successfully list catalog services by running `python-openstackclient` on the underlying VMs using the same exact information than `cloud-config`.
- I've verified both secrets and configmaps volumes are properly mounted with the right content by running `kubectl exec <cloud-controller-manager-ds> cat /etc/cloud/cloud-config` and `kubectl exec <cinder-csi-provisionner-pod> cinder cat /etc/config/cloud.conf`. 

**Environment**:
- kubernetes: 1.11.3
- openstack-cloud-controller-manager version: 0.2.0
- OS (e.g. from /etc/os-release): Debian 9
- Kernel (e.g. `uname -a`): `Linux master-0 4.9.0-7-amd64 #1 SMP Debian 4.9.110-3+deb9u1 (2018-08-03) x86_64 GNU/Linux`

**Comment by dims** [comment]
cc @aglitke

**Comment by wzrdtales** [comment]
Got the same problem, was trying on OVHs open stack.

When I do not configure the region it throws with:

```
  Warning    ProvisioningFailed    15m (x9 over 19m)     csi-cinderplugin csi-provisioner-cinderplugin-0 1c0795ab-c892-11e8-8592-0e8cee776ddd  Failed to provision volume with StorageClass "csi-sc-cinderplugin": rpc error: code = Unknown desc = Discovered 6 matching endpoints: []tokens.Endpoint{tokens.Endpoint{ID:"0cdd8515aab04536b48eba83d063149e", Region:"UK1", RegionID:"UK1", Interface:"public", URL:"https://compute.uk1.cloud.ovh.net/v2/0d41839fa6c048ddb109f8b170add8ff"}, tokens.Endpoint{ID:"12fe27a87117482eb4961f8e53471cc3", Region:"GRA5", RegionID:"GRA5", Interface:"public", URL:"https://compute.gra5.cloud.ovh.net/v2/0d41839fa6c048ddb109f8b170add8ff"}, tokens.Endpoint{ID:"249ce50b948f4d8399feed677d34fd3e", Region:"SBG3", RegionID:"SBG3", Interface:"public", URL:"https://compute.sbg3.cloud.ovh.net/v2/0d41839fa6c048ddb109f8b170add8ff"}, tokens.Endpoint{ID:"4600007ec2a045b3a40529cd34791ffa", Region:"DE1", RegionID:"DE1", Interface:"public", URL:"https://compute.de1.cloud.ovh.net/v2/0d41839fa6c048ddb109f8b170add8ff"}, tokens.Endpoint{ID:"4dc5ebfd88bb4f57ae92818d594aa6dd", Region:"BHS3", RegionID:"BHS3", Interface:"public", URL:"https://compute.bhs3.cloud.ovh.net/v2/0d41839fa6c048ddb109f8b170add8ff"}, tokens.Endpoint{ID:"f44cd8bba9f44162a22d387ec9adfb53", Region:"WAW1", RegionID:"WAW1", Interface:"public", URL:"https://compute.waw1.cloud.ovh.net/v2/0d41839fa6c048ddb109f8b170add8ff"}}
```

If I enter the region it throws with

```
  Warning    ProvisioningFailed    12s                   csi-cinderplugin csi-provisioner-cinderplugin-0 d1297eb0-c894-11e8-8da7-a2d56253265a  Failed to provision volume with StorageClass "csi-sc-cinderplugin": rpc error: code = Unknown desc = No suitable endpoint could be found in the service catalog.
```

The URLs of OVH are those:

```

Displaying 10 items
--

Cloudformation | https://cloudformation.de1.cloud.ovh.net/v1
Compute | https://compute.de1.cloud.ovh.net/v2/0d41839fa6c048ddb109f8b170add8ff
Identity | https://auth.cloud.ovh.net/
Image | https://image.compute.de1.cloud.ovh.net/
Network | https://network.compute.de1.cloud.ovh.net/
Object Store | https://storage.de1.cloud.ovh.net/v1/AUTH_0d41839fa6c048ddb109f8b170add8ff
Orchestration | https://orchestration.de1.cloud.ovh.net/v1/0d41839fa6c048ddb109f8b170add8ff
Volume | https://volume.compute.de1.cloud.ovh.net/v1/0d41839fa6c048ddb109f8b170add8ff
Volumev2 | https://volume.compute.de1.cloud.ovh.net/v2/0d41839fa6c048ddb109f8b170add8ff
Workflowv2 | https://workflow.de1.cloud.ovh.net/v2

**Comment by xlucas** [comment]
Ok so after digging this a bit it appears even though the cloud-controller-manager handles the `bs-version` in `cloud-config`, the cinder CSI plugin retrieves the volume service its own way. As a consequence, all entries from `cloud-config` that aren't Openstack credentials are ignored (in particular, this means the `[BlockStorage]` section of the configuration is not looked at) and it [always try to find the `volumev3`](https://github.com/kubernetes/cloud-provider-openstack/blob/master/pkg/csi/cinder/openstack/openstack.go#L155) endpoint, which isn't available on OVH Cloud.

**Comment by jianglingxia** [comment]
The issue has fixed with modify the bs-version v 2 to v 3？I occure the problem that the pv can not created and the same logs @xlucas

**Comment by dricoco** [comment]
Hello,
I'm running into this issue too, 

I've tried
[BlockStorage]
bs-version=v2 or v3 or auto

I have a cinder v3 endpoint created :

| db2878b3ee9448d29a99e0e62ffe7af5 | RegionOne | cinderv3     | volumev3        | True    | admin     | http://controller:8776/v3/%(project_id)s      |
| dc05d3af2b324955b4d0c63552d3d6cc | RegionOne | cinderv3     | volumev3        | True    | public    | http://Y.Y.Y.Y.Y:8776/v3/%(project_id)s  |
| 8b7339665b7b4aa1aa9939a71ae14b2d | RegionOne | cinderv3     | volumev3        | True    | internal  | http://controller:8776/v3/%(project_id)s      |

How can I launch the pods with a -v3 to get mode debug using klog?
