### ISSUE TITLE
Use standard clouds.yaml file as config file

### ISSUE THREAD

**Issue by flaper87** [kubernetes/cloud-provider-openstack#323]
/kind feature

We're currently migrating the `cluster-api-provider-openstack` config format from a custom implementation to using `clouds.yaml`, which is a known format in the OpenStack community.

https://github.com/kubernetes-sigs/cluster-api-provider-openstack/issues/16

Just like in the `cluster-api-provider-openstack` case, it'd be great if we could port the `cloud-provider-openstack` config format to use `clouds.yaml`. This would not only make both projects consistent but it'd also bring in a known format in the openstack community making the deployment of this provider easier to operators.

We could port the implementation that we're working on into `cloud-provider-openstack` and then ventor it in `cluster-api-provider-openstack` making the former a dependency for the latter.

**Comment by chaosaffe** [comment]
/assign @iamemilio
@iamemilio is now a member

**Comment by chaosaffe** [comment]
Apparently @iamemilio only joined @kubernetes-sigs
xref: https://github.com/kubernetes/org/issues/189

**Comment by iamemilio** [comment]
Upstream Reference: https://github.com/kubernetes/cloud-provider-openstack/issues/323
