### ISSUE TITLE
csi-nodeplugin-cinderplugin can't find instance-id

### ISSUE THREAD

**Issue by pblaas** [kubernetes/cloud-provider-openstack#325]
> /kind bug
/kind feature

**What happened**:
While deploying `https://github.com/kubernetes/cloud-provider-openstack/tree/master/manifests/cinder-csi-plugin`

csi-nodeplugin-cinderplugin keeps crashing due to not able to find specific content.
```
I1012 11:04:30.120752       1 connection.go:140] GRPC error: rpc error: code = Unknown desc = open /var/lib/cloud/data/instance-id: no such file or directory
E1012 11:04:30.120773       1 main.go:159] rpc error: code = Unknown desc = open /var/lib/cloud/data/instance-id: no such file or directory
```

**What you expected to happen**:
/var/lib/cloud/data/instance-id should be filled with proper information from the OpenStack metadata service.

**How to reproduce it (as minimally and precisely as possible)**:
Deploy the cinder-csi-plugin on kubernetes on an OpenStack Ocata platform.

**Anything else we need to know?**:
There was a short discussion on the slack channel:
`https://kubernetes.slack.com/archives/C0LSA3T7C/p1539342540000100`

**Environment**:
- openstack-cloud-controller-manager version: Latest
- OS (e.g. from /etc/os-release): 
```
NAME="Container Linux by CoreOS"
ID=coreos
VERSION=1745.7.0
VERSION_ID=1745.7.0
BUILD_ID=2018-06-14-0909
```
- Kernel (e.g. `uname -a`): `Linux k8s-k8scluster-node10 4.14.48-coreos-r2 #1 SMP Thu Jun 14 08:23:03 UTC 2018 x86_64 Intel Core Processor (Broadwell) GenuineIntel GNU/Linux`

- Install tools: `https://github.com/pblaas/nagoya`
- Others:

**Comment by pblaas** [comment]
My current work arround:  `curl http://169.254.169.254/2009-04-04/meta-data/instance-id > /var/lib/cloud/data/instance-id`

**Comment by jichenjc** [comment]
/var/lib/cloud/data/instance-id seems created by cloud-init ,but we can't assume it always there or always correct path...

likely it's because we assume this file always existing in CSI but it's not,
in cloud provider seems readInstanceID will fall through to metadata service but CSI code branch didn't

**Comment by adisky** [comment]
@jichenjc yes, we have discussed same on sig-openstack slack channel, I am adding fix to fetch instance-id from metadata service as a fallback option.
