### ISSUE TITLE
Missing RBAC rules on the openstack-cloud-controller-manager daemonset manifest 

### ISSUE THREAD

**Issue by pblaas** [kubernetes/cloud-provider-openstack#327]
/kind feature

**What happened**:
Deploying the daemonset of the openstack-cloud-controller-manager `https://github.com/kubernetes/cloud-provider-openstack/tree/master/manifests/controller-manager`  on a cluster with RBAC enabled won't render a usable k8s cluster due to the fact the taints are not removed from the nodes by the cloud controller manager due to missing RBAC permissions.

**What you expected to happen**:
The daemon set manifest  should be completed with required RBAC rules.

**How to reproduce it (as minimally and precisely as possible)**:
Deploy the daemonset manifest `https://github.com/kubernetes/cloud-provider-openstack/blob/master/manifests/controller-manager/openstack-cloud-controller-manager-ds.yaml` on a kubernetes cluster with RBAC enabled.

**Anything else we need to know?**:

**Environment**:
- openstack-cloud-controller-manager version: latest

**Comment by dims** [comment]
@pblaas seen this? https://github.com/kubernetes/cloud-provider-openstack/tree/master/cluster/addons/rbac

**Comment by pblaas** [comment]
@dims no sorry i've missed that. Thanks for pointing it out.
