### ISSUE TITLE
Cinder CSI Raw block volume support

### ISSUE THREAD

**Issue by adisky** [kubernetes/cloud-provider-openstack#341]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind feature

**What you expected to happen**:
CSI Raw block volume support has been added in v1.11 as alpha feature, we should add same support to cinder csi driver

**Comment by ramineni** [comment]
I'll work on this

**Comment by ramineni** [comment]
In progress , https://github.com/kubernetes/cloud-provider-openstack/pull/563
