### ISSUE TITLE
Docs error in Loadbalancers example README.MD

### ISSUE THREAD

**Issue by adsl123gg** [kubernetes/cloud-provider-openstack#346]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
> /kind bug

**What happened**:
use cloud-provider-openstack/examples/loadbalancers/internal-http-nginx.yaml to create **internal** loadbalancer failed, cloud-provider-openstack create a **external** loadbalancer.

**What you expected to happen**:
use cloud-provider-openstack/examples/loadbalancers/internal-http-nginx.yaml to create **INTERNAL** loadbalancer successfully.

**How to reproduce it (as minimally and precisely as possible)**:
when you run k8s and cloud-provider-openstack successful, run "kubectl create -f examples/loadbalancers/internal-http-nginx.yaml"

**REASON:**
the code in openstack_loadbalancer.go assume LB is external, it read service annotation "service.beta.kubernetes.io/openstack-internal-load-balancer" to create internal or external LB. But the internal-http-nginx.yaml and external-http-nginx.yaml use annotations in pos, not service, so the yaml file should be changed to below content.
`---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: internal-http-nginx-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
---
kind: Service
apiVersion: v1
metadata:
  name: internal-http-nginx-service
  annotations:
    service.beta.kubernetes.io/openstack-internal-load-balancer: "true"
spec:
  selector:
    app: nginx
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    targetPort: 80`

**Comment by brtknr** [comment]
I may have a similar issue when i run `cloud-provider-openstack/examples/loadbalancers/internal-http-nginx.yaml`, but I get this error:

>  Error creating load balancer (will retry): failed to ensure load balancer for service pangeo/internal-http-nginx-service: error creating loadbalancer adbdec19efbfa11e8aca3246e9648913: error creating loadbalancer {adbdec19efbfa11e8aca3246e9648913 Kubernetes external service adbdec19efbfa11e8aca3246e9648913 ilab    <nil>  }: Invalid request due to incorrect syntax or missing required parameters.
