### ISSUE TITLE
Add feature for scale cluster worker node in openstack

### ISSUE THREAD

**Issue by adsl123gg** [kubernetes/cloud-provider-openstack#352]
/kind feature

Now cloud-provider-openstack can provide Loadbalance/PersistentVolume/router for k8s, but if k8s want to scale up worker nodes, now cloud-provider-openstack can do nothing. As we all know, openstack can provide VM, so why not provide VMs to k8s for cloud-provider-openstack. I think it's a very useful function, and also there are a project called [machine-controller](https://github.com/kubermatic/machine-controller), which has implement the function of asking openstack VMs and let the VMs join k8s cluster, so we can integrate the machine-controller project with cloud-provider-openstack.

main function for this feature:
add/delete/update worker nodes to k8s cluster from openstack

**Comment by dims** [comment]
@adsl123gg we are working on such stuff here : https://github.com/kubernetes-sigs/cluster-api-provider-openstack 

Also see https://github.com/kubernetes-sigs/cluster-api

Hope you can join the work there

**Comment by adsl123gg** [comment]
@dims as I know, there are two ways to autoscale k8s nodes in cloud provider(such as openstack, AWS), first is cloud provider autoscale cluster nodes according to k8s resource utilizing, in this situation, cloud provider know k8s is running in cloud, cloud provider is initiator. Then the second way is k8s ask VM from cloud provider and then the VMs join k8s, in this situation, k8s is initiator and cloud provider doesn't know k8s is running on it.
so how about cluster-api project, what's it position? 
Also there is another project https://github.com/kubernetes/autoscaler, it implement auto scale function with the first way.

**Comment by dims** [comment]
You should read all the materials for cluster-api as its a still early stage, auto scaling based on utilization will hopefully be a part of it.

for kubernetes/autoscaler, there has been talk but not much work, please see https://github.com/kubernetes/autoscaler/pull/1226

**Comment by adsl123gg** [comment]
@dims for kubernetes/autoscaler, there is a more detail discussions in https://github.com/kubernetes/autoscaler/issues/734, from what ricolin say, I think they want to create another openstack component project to auto scale k8s.

**Comment by adsl123gg** [comment]
@dims after using cluster-api-provider-openstack and reading the materials of cluster-api, I this cluster-api aiming to do autoscale in cloud provider position, from the architecture diagram in https://github.com/kubernetes-sigs/cluster-api, cluster-api has several components such as bootstrapping CLI, upgrade trigger and autoscaling,  as we can see from the diagram, the initiator is cluster-api, not k8s cluster, although autoscaling is not finish. If you're working on autoscaling in cluster-api-provider-openstack, so what's your thinking to finish autoscaling?

**Comment by chaosaffe** [comment]
@adsl123gg [`cluster-api`](https://github.com/kubernetes-sigs/cluster-api) is responsible for handling the cluster lifecycle, including creation and destruction of control plane (master) and worker nodes. 
[`cluster-autoscaler`](https://github.com/kubernetes/autoscaler/tree/master/cluster-autoscaler) is responsible for determining when the cluster needs to add or remove worker nodes, which it could do in conjunction with `cluster-api` by modifying `MachineDeployment`s, `MachineSet`s or by creating and destroying `Machine` resources. 

The intent of `cluster-api` is to encapsulate the provider-specific (i.e. OpenStack) details, and enable tooling such as `cluster-autoscaler` to manage cluster resources in an abstracted, provider-agnostic manner.

A generalised workflow for autoscaling using `cluster-api` would be:
1. Autoscaler determines more nodes are required to handle current workloads.
2. Autoscaler increases a specified `MachineDeployment` replica count to satisfy the required number of work loads.
3. Cluster API _MachineDeploymentController_ is informed of the change in replicas via the `watch` mechanism.
4. Cluster API _MachineDeploymentController_ scales the current `MachineSet` as indicated by the `MachineDeployment`.
5. Cluster API _MachineSetController_ is informed of the change in replicas via the `watch` mechanism.
6. Cluster API _MachineSetController_ creates `Machine`s from the `MachineSet``spec.template` to satisfy the number of requested replicas.

_Note that steps 1-6 are provider-agnostic and have no interaction with the provider (i.e. OpenStack)_

7. Cluster API _Provider_ (i.e. [Cluster-API Provider Openstack](https://github.com/kubernetes-sigs/cluster-api-provider-openstack)) is informed of the newly created `Machine`s via the `watch` mechanism.
8. Cluster API _Provider_ interacts with the OpenStack APIs to create the requested `Machine`s, and to configure them to become worker nodes.
9. Cluster API _Provider_, once the `Machine` has joined the cluster as a `Node`, sets a reference between the `Machine` and the `Node`.

Downscaling a cluster will occur in a similar fashion, with the `MachineDeployment` replica count being decremented, `Machine` objects being deleted, and Cluster-API _Provider_ triggering deletion of the applicable resources via the Provider (i.e. OpenStack APIs)

As the above indicates, this follows a very similar patter to how the [Horizontal Pod Autoscaler](https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale/) behaves, allowing the HPA to be pod-agnostic.
