### ISSUE TITLE
Use OpenStack metadata service to acquire instance ID

### ISSUE THREAD

**Issue by ainmosni** [kubernetes/cloud-provider-openstack#372]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind feature

**What happened**:
Currently, when setting up the provider on a machine with a hostname that differs from the name in OpenStack the provider can't find the instance ID. The provider should use the [metadata service](https://docs.openstack.org/nova/rocky/user/metadata-service.html)  to acquire this ID to make this process more reliable.

Note that `/var/lib/cloud/data` is less reliable, as operating systems like container Linux have moved away from cloud-init.

**Comment by mape90** [comment]
The cloud provider actually never uses the metadata when it adds new node. If node joins with cloud-provider=external that node will not sets its ProviderID. Then the cloud provider uses the only info that is has from node that is its name. And if that name isn't 1:1 with name in Openstack then the node will be deleted from cluster. If you set kubelet argument --provider-id="openstack:///<id_of_vm>" then name based search will not be done and your node can have what ever name for your nodes. Problem here is that you need to get that id.

**Comment by ainmosni** [comment]
Is there a reason why it doesn't query the metadata service if the name doesn't match? It seems that would be a more reliable way to acquire the ID.

**Comment by jichenjc** [comment]
I think first try metadata/config drive then cloud init (/var/lib/cloud/xxx) make sense

And I am curious why change hostname will have some effect, as the instance-id will be the identifier of the node ?

**Comment by ainmosni** [comment]
@jichenjc Yeah, that's what confused me as well, that behaviour made me assume that it didn't check the metadata at all. The configured hostname should (IMHO of course) not have any effect on it being able to find its instance-id.

**Comment by jichenjc** [comment]
ok, let me submit a PR for the order on checking metadata first and see anyone has any comments
