### ISSUE TITLE
Use OpenStack metadata service to acquire instance ID in cinder CSI plugin

### ISSUE THREAD

**Issue by ainmosni** [kubernetes/cloud-provider-openstack#373]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind feature

**What happened**:
The cinder CSI plugin currently acquires its instanceID from `/var/lib/cloud/data/instance-id`. This path will not always be available (Container Linux moved from cloud-config to ignition, which does not write that file). To make this more reliable, the plugin should use the [metadata service](https://docs.openstack.org/nova/rocky/user/metadata-service.html).

This issue is related to #372 but for a different component.

**Comment by adisky** [comment]
@ainmosni It first tries to get from cloud-init, then from metadata servicehttps://github.com/kubernetes/cloud-provider-openstack/pull/331

**Comment by ainmosni** [comment]
@adisky I see, my bad. I thought it only relied on the cloud-init.
