### ISSUE TITLE
Document migration from internal to external cloud provider

### ISSUE THREAD

**Issue by ainmosni** [kubernetes/cloud-provider-openstack#374]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind feature

**What happened**:
Currently, there's no documentation on how to migrate from the OpenStack cloudprovider that's integrated in the controller-manager. As there are a few potential pitfalls, having a "tutorial" style document would be quite useful and would increase the adoption of the external cloud provider.

Some things that this should include:
* Prerequisite steps to take before migrating.
* Differences in behaviour between the external and internal providers.
  * For example, the internal provider changes the node name (if it differs from the OpenStack name) while the external one doesn't.
* Order of the installation of components, and apiserver/controller-manager/kubelet configuration changes.
* Steps to verify that the migration was successful.

**Comment by alvaroaleman** [comment]
IMHO this is definitely something that is needed, there are quite a few ppl that have existing clusters and re-creating them is not always a feasible option.

**Comment by adisky** [comment]
@alvaroaleman you are encouraged to write doc for migration :), we are lack of contributors maintaining this project, and most of us(who contributes) directly started cluster with external provider so it is difficult for use to write migration docs.

**Comment by thcdrt** [comment]
Hello, that would be great to have such a documentation. :)
It's exactly what I would need, see issue #825 .

Thomas
