### ISSUE TITLE
[Cinder CSI] Race condition in volume deletion between attacher and provisioner

### ISSUE THREAD

**Issue by mape90** [kubernetes/cloud-provider-openstack#381]
/kind bug
**What happened**:
When volumes are deleted. Both detaching and deletion are executed same time. This causes race condition where volume can be deleted before detacher found out that it was detached. 
After this the detaching will never succeed and `VolumeAttachment` is forever try to detach the volume.

**What you expected to happen**:
If we are detaching volume and we do not find the volume it should be quite safe to assume that it isn't attached to the host VM.

**How to reproduce it (as minimally and precisely as possible)**:
Create big deployment with multiple pods with volumes and delete them. Looping this should eventually cause this problem. Also if volume is long time in detaching state (over 1min timer that `WaitDiskDetached` is waiting) and is finally detached it might be that provisioner deletes it before attacher retries to detach it.

**Anything else we need to know?**:
One solution could be to catch 404 error from `os.GetVolume(volumeID)` and then assume that volume is detached if we get that error while detaching.

**Environment**:
csi-attacher:v0.3.0
csi-provisioner:v0.3.1
cinder-csi-plugin:v0.3.0

**Comment by dims** [comment]
@mape90 is this specifically openstack related or do you think that this will happen for all CSI impls?

cc @adisky @flaper87

**Comment by mape90** [comment]
I think this is generic for all CSI plugins. As external-provisioner will not check if volume is still having VolumeAttachment with attached status. 

It also seems that AWS EBS CSI has fixed this issue with the solution I proposed. As they just return success if volume isn't found:
```
if err == cloud.ErrNotFound {
	glog.V(4).Info("DeleteVolume: volume not found, returning with success")
	return &csi.DeleteVolumeResponse{}, nil
}
```
It most likely would be possible to implement something in external-provisioner level. So that it would check if the PV has VolumeAttachment. However then there is still the case when someone deleted manually the volume on backend. So simplest way to solve this would be to succeed always when we are deleting or detaching something and we can not find. As that is anycase the intended behavior.

**Comment by adisky** [comment]
@mape90 Delete should not be executed before attach complete
as mentioned here
https://github.com/kubernetes/community/blob/master/contributors/design-proposals/storage/container-storage-interface.md#attaching-and-detaching
"the PersistentVolume referenced by VolumeAttachment so the PV cannot be deleted while the volume is attached", so ideally delete should not happen before detach.
please log the issue in external-provisioner also.

**Comment by adisky** [comment]
I did not anything in cinder driver that should cause it, you should log issue to external-provisioner as well

**Comment by mape90** [comment]
The failure happens when detaching takes a long time and Attacher is polling in function 'WaitDiskDetached'. Then during one of those wait phases the volume might get detached and then provisioner might delete it before attacher checks it state again. After this all request to get any data about this volume will return ErrNotFound. And as current implementation do not handle this case it will fail forever.

What happens:
Delete PV
-> Attacher sends detach command to Openstack for this volume
-> Volume gets in detaching state
-> Attacher polls the volume state (gets that it is still in detaching state)
-> Attacher "sleeps"
-> Volume gets detached in backend
-> Provisioner tries to delete volume and succeed as volume is in available state. (Volume is deleted in backend)
-> Attacher wakes from sleep and tries to get volume state.
-> Fails as it gets ErrNotFound
-> Detaching will never succeed as the volume is already deleted form backend.

**Comment by jichenjc** [comment]
ok ,thanks for the detailed info
so the key cause here is provisioner and attacher do the job concurrently... and during sleep time the provisioner deleted the volume, that make sense but curious on Provisioner/Attacher  do the job at same time, anyway, will try to submit a fix and see folks' opinion
