### ISSUE TITLE
add csi-manila

### ISSUE THREAD

**Issue by gman0** [kubernetes/cloud-provider-openstack#394]
With CSI 1.0 out, we can start drafting some initial implementation for csi-manila using the "proxy architecture" as discussed offline. If there's no current work in progress by somebody else, I'll be glad to get this one started.

I don't have a PR ready yet but till then it would be great if we got the dependencies for 1.0 in (https://github.com/kubernetes/cloud-provider-openstack/issues/365).

cc @hogepodge @flaper87 

/kind feature

**Comment by hogepodge** [comment]
Please feel free to get this one started. Thanks!

**Comment by tombarron** [comment]
Note the great work in https://github.com/kubernetes/cloud-provider-openstack/pull/536

**Comment by gman0** [comment]
Done in #536
