### ISSUE TITLE
Add client-keystone-auth to release assets

### ISSUE THREAD

**Issue by lingxiankong** [kubernetes/cloud-provider-openstack#395]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind feature

**What happened**: 
client-keystone-auth binary is missing from the release.

**What you expected to happen**:
Include client-keystone-auth binary in the release

**How to reproduce it (as minimally and precisely as possible)**:
N/A

**Anything else we need to know?**:
N/A

**Comment by lingxiankong** [comment]
/remove-lifecycle stale

We still need this.

**Comment by adisky** [comment]
/close 
we have client-keystone-auth binary in release v1.15
