### ISSUE TITLE
Support for sssd in client-keystone-auth

### ISSUE THREAD

**Issue by strigazi** [kubernetes/cloud-provider-openstack#406]
/kind feature

client-keystone-auth should support authentication with sssd.

OS_PROJECT_DOMAIN_ID=default
OS_IDENTITY_PROVIDER=sssd
OS_PROJECT_NAME=<NAME>
OS_MUTUAL_AUTH=<OPTION>
OS_IDENTITY_API_VERSION=3
OS_AUTH_TYPE=v3fedkerb
OS_PROTOCOL=kerberos
OS_AUTH_URL=<URL>

**Comment by dims** [comment]
cc @lbragstad
