### ISSUE TITLE
TCP listener prevents application of HTTP rules

### ISSUE THREAD

**Issue by netcho** [kubernetes/cloud-provider-openstack#412]
The hard coded protocol type of TCP makes haproxy inside amphorae to neglect L7 HTTP rules. Here's the line
https://github.com/kubernetes/cloud-provider-openstack/blob/cc82c7f119cd63e857c47c34796a272cc967cf02/pkg/ingress/controller/openstack/octavia.go#L395

My suggestion would be to change it to HTTP as for now Ingress only supports HTTP/HTTPS and discuss TCP loadbalancing capabilities of Octavia can be used through annotations in the Ingress resource itself

**Comment by lingxiankong** [comment]
@netcho hi, thanks for reporting this issue. Could you please provide your pod/service/ingress manifest files you were testing with?

**Comment by netcho** [comment]
`apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: console-ingress
  annotations:
    kubernetes.io/ingress.class: openstack
spec:
  rules:
  - http:
      paths:
      - path: /
        backend:
          serviceName: frontend
          servicePort: 80
      - path: /api
        backend:
          serviceName: backend
          servicePort: 80`

Here it is. I forgot to mention that I recreated the loadbalancer manually changing the protocol to HTTP and it worked as expected.

**Comment by lingxiankong** [comment]
hi @netcho, could you please use the image lingxiankong/openstack-ingress-controller:0.0.1(containing the PR 419) for your testing and make sure it works for you now?
