### ISSUE TITLE
Enable usage of OpenStack Application Credentials

### ISSUE THREAD

**Issue by chrigl** [kubernetes/cloud-provider-openstack#421]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind feature

**What happened**:

Currently when configuring components like the `openstack-cloud-controller-manager` with a `cloud.conf`, one is only able to use the owners OpenStack User and Password.

From version 3.10 (included in the Queens release), OpenStack Keystone supports Application Credentials (also see #232 and https://developer.openstack.org/api-ref/identity/v3/index.html#application-credentials).

It would be nice to be able to configure Application Credentials in `cloud.conf` over using real users password. 

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- openstack-cloud-controller-manager version:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by chrigl** [comment]
gophercloud already supports this, and this is already used in `client-keystone-auth` (https://github.com/kubernetes/cloud-provider-openstack/blob/master/cmd/client-keystone-auth/main.go#L114).

It would just be nice to have this ability in the controller as well, to not sprinkle around "real" credentials everywhere.

**Comment by jichenjc** [comment]
ok, will take a look and see how we can utilize that, thanks for the info

**Comment by chrigl** [comment]
Just for the record: @jichenjc implemented this in #426 😄
