### ISSUE TITLE
csi-cinder plugin manifest examples do not work

### ISSUE THREAD

**Issue by woodne** [kubernetes/cloud-provider-openstack#423]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
/kind bug
> /kind feature

**What happened**:

When installing the cinder-csi plugin, after creating a storage class and a PVC, the provisioner gives errors about no OS_AUTH_URL being defined.

**What you expected to happen**:

It pulls the cloud config settings from the cloud config secret

**How to reproduce it (as minimally and precisely as possible)**:

- Bootstrap a cluster with 1.13.1
- follow the instructions for installing the cinder-csi plugin
- create a storage class 
```
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: csi-sc-cinderplugin
  annotations:
    storageclass.beta.kubernetes.io/is-default-class: "true"
provisioner: csi-cinderplugin```
- create a pvc that uses this storage class
- see the logs for the `kubectl logs csi-provisioner-cinderplugin-0`

example:
$ kubectl logs -n kube-system csi-provisioner-cinderplugin-0 cinder                               
I0109 15:54:37.781015       1 driver.go:49] Driver: cinder.csi.openstack.org version: 0.3.0
I0109 15:54:37.781116       1 driver.go:80] Enabling controller service capability: LIST_VOLUMES
I0109 15:54:37.781125       1 driver.go:80] Enabling controller service capability: CREATE_DELETE_VOLUME
I0109 15:54:37.781129       1 driver.go:80] Enabling controller service capability: PUBLISH_UNPUBLISH_VOLUME
I0109 15:54:37.781132       1 driver.go:80] Enabling controller service capability: CREATE_DELETE_SNAPSHOT
I0109 15:54:37.781136       1 driver.go:80] Enabling controller service capability: LIST_SNAPSHOTS
I0109 15:54:37.781140       1 driver.go:92] Enabling volume access mode: SINGLE_NODE_WRITER
I0109 15:54:37.781275       1 server.go:108] Listening for connections on address: &net.UnixAddr{Name:"/csi/csi.sock", Net:"unix"}
E0109 15:55:50.355211       1 utils.go:100] GRPC error: Missing environment variable [OS_AUTH_URL]
E0109 15:55:50.359424       1 utils.go:100] GRPC error: Missing environment variable [OS_AUTH_URL]
E0109 15:56:05.365802       1 utils.go:100] GRPC error: Missing environment variable [OS_AUTH_URL]
E0109 15:57:05.376952       1 utils.go:100] GRPC error: Missing environment variable [OS_AUTH_URL]
E0109 15:59:05.387402       1 utils.go:100] GRPC error: Missing environment variable [OS_AUTH_URL]
```

**Anything else we need to know?**:

**Environment**:
- openstack-cloud-controller-manager version: 
- OS (e.g. from /etc/os-release):"Ubuntu 18.04.1 LTS"
- Kernel (e.g. `uname -a`): 4.15.0-33-generic
- Install tools: 
- Others:

**Comment by woodne** [comment]
@adisky this was indeed my fault. I messed up creating the secret and changed it to `cloud.config: base64secret` instead of `cloud.conf`.

It does seem like there could have been some useful logs about the cloud config file not being present.

**Comment by adisky** [comment]
@woodne you can create a seperate issue/PR for logs, I am closing this.
