### ISSUE TITLE
Add CRD and deployment for csi snapshot

### ISSUE THREAD

**Issue by adisky** [kubernetes/cloud-provider-openstack#424]
Add CRD and Deployment yaml's for CSI Snapshot

**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind feature

**What happened**:
Snapshot Support Implemented by following PR in Cinder CSI.
 [csi] add snapshot support #344 
- We need to add CRD's to use the snapshot functionality, and deployment file for external-snapshotter
- Update Document and CI

**Comment by jichenjc** [comment]
Thanks for open this
I searched manifests/cinder-csi-plugin and didn't find CRD for volume, so can you point me where to add CRD etc ? Thanks
