### ISSUE TITLE
Use docker tags in git tags

### ISSUE THREAD

**Issue by johscheuer** [kubernetes/cloud-provider-openstack#431]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
> /kind bug

/kind feature

**What happened**:

Currently all manifest files use the `latest` tags (even on the branches and tags) e.g. https://github.com/kubernetes/cloud-provider-openstack/blob/1.13.1/manifests/controller-manager/openstack-cloud-controller-manager-ds.yaml#L39 which means as a user I get an undefined (and probably not working) state of the manifest file.

**What you expected to happen**:

All manifests should use the according docker tag for the git tags/releases otherwise the manifest in the tag are pretty useless (since flags can be changed)

**How to reproduce it (as minimally and precisely as possible)**:
-

**Anything else we need to know?**:

This should be integrated in the releases process.

**Comment by jichenjc** [comment]
I guess this is for stable(released) branch ?  when you try stable branch use :lastest can lead to issue?
maybe kustomiz can be considered here or something else or use git tags seems not so good...? 
this is more operator focused area?

**Comment by adisky** [comment]
@johscheuer Agreed, There can be two options to solve this, one is tag it with the release, and update tag after the release in manifests, another option is to keep multiple manifests file corresponds to each release and a separate master file.

**Comment by adisky** [comment]
one more option is keeping  two manifests one is developer manifests which points to the master and another one which corresponds to the last stable release.

**Comment by adisky** [comment]
@jichenjc True, I think best to have developer manifest and one pointing to last stable release

**Comment by ramineni** [comment]
@adisky @jichenjc shouldn't we have manifest corresponding to that release , like before making 1.1x release , we need to update the manifests to use 1.1x tag instead of latest, so whoever downloads that release will have correct version of cinder-csi-plugin being used . And always master should have latest in manifests file IMO

**Comment by jichenjc** [comment]
this seems similar to adisky's comments? usually this update manifest should be done after release and only tag in the released branch...

**Comment by adisky** [comment]
@ramineni Agreed we will seperate developer and release manifests from this release(1.15),an issue can be filed to track this

**Comment by ramineni** [comment]
I suppose we can close this now, as from 1.15 release this has been taken care of.

**Comment by johscheuer** [comment]
Thanks!
