### ISSUE TITLE
Unable to schedule pods on the host, failing with error Error fetching by NodeName: failed to find object

### ISSUE THREAD

**Issue by ramineni** [kubernetes/cloud-provider-openstack#435]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
/kind bug
> /kind feature

**What happened**:
Pods are unable to get schedules on host , status is always in Pending state
NAME                             READY   STATUS    RESTARTS   AGE
csi-attacher-cinderplugin-0      0/2     Pending   0          19m
csi-provisioner-cinderplugin-0   0/2     Pending   0          19m
ccm log shows This node 127.0.0.1 is still tainted. Will not process.
So initialization of the node got failed with error
I0111 04:33:20.444205   27150 openstack_instances.go:80] NodeAddresses(127.0.0.1) called
E0111 04:33:20.803434   27150 node_controller.go:419] NodeAddress: Error fetching by providerID: ProviderID "testvm" didn't match expected format "openstack:///InstanceID" Error fetching by NodeName: failed to find object
I0111 04:33:23.070378   27150 openstack_instances.go:46] openstack.Instances() called
**What you expected to happen**:
Pods to get scheduled and to be in Running state
**How to reproduce it (as minimally and precisely as possible)**:
Follow steps in 
https://github.com/kubernetes/cloud-provider-openstack/blob/master/docs/getting-started-provider-dev.md
https://github.com/kubernetes/cloud-provider-openstack/blob/master/docs/using-cinder-csi-plugin.md

**Anything else we need to know?**:
The Error got fixed by setting environment variable export HOSTNAME_OVERRIDE=$(hostname) , before starting cluster. Doc needs to be updated for the same.

**Environment**:
- openstack-cloud-controller-manager version:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by jichenjc** [comment]
this should be closed due to https://github.com/kubernetes/cloud-provider-openstack/pull/429/commits/4c778e7404a295ff5ca21a37735edc1d4d3e09be?
