### ISSUE TITLE
defaultMetadataVersion used is quite old, update to latest version

### ISSUE THREAD

**Issue by ramineni** [kubernetes/cloud-provider-openstack#437]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
/kind bug
> /kind feature

**What happened**:
defaultMetadataVersion used in code is quite old, need to use the latest version to be in sync with latest developements in metadata service.
https://github.com/kubernetes/cloud-provider-openstack/blob/master/pkg/csi/cinder/openstack/openstack_metadata.go#L11

**What you expected to happen**:
use latest version instead
**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- openstack-cloud-controller-manager version:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by jichenjc** [comment]
maybe use 'latest' should be fine ?

also pkg/cloudprovider/providers/openstack/metadata.go has similar stuffs

**Comment by ramineni** [comment]
@jichenjc yes, thats my thought also, im not sure if there is any reason for using the old version, so thought would wait for couple of comments , else would raise the PR for the same.

**Comment by adisky** [comment]
/close
https://github.com/kubernetes/cloud-provider-openstack/pull/448
