### ISSUE TITLE
Barbican as a Kubernetes KMS provider

### ISSUE THREAD

**Issue by dims** [kubernetes/cloud-provider-openstack#44]
Similar to https://github.com/Azure/kubernetes-kms

background research:
- https://kubernetes.io/docs/tasks/administer-cluster/encrypt-data/
- https://github.com/kubernetes/kubernetes/pulls?utf8=%E2%9C%93&q=is%3Apr+++EncryptionConfig+
- https://github.com/kubernetes/kubernetes/pulls?utf8=%E2%9C%93&q=is%3Apr+++experimental-encryption-provider-config

**Comment by dims** [comment]
Will need gophercloud to support Barbican API first?

**Comment by dklyle** [comment]
Yes, gophercloud does not have Barbican support yet. But it's on the radar. So adding it should be welcomed.

**Comment by JAORMX** [comment]
@dims seems so. There isn't support there yet.

**Comment by JAORMX** [comment]
Trying to get either time to get into this or time from someone from my team to do this. We definitely are interested but lack capacity at the moment.

**Comment by adisky** [comment]
Barbican support in gopher cloud has been added
https://github.com/gophercloud/gophercloud/pull/1059
@dims @dklyle @JAORMX  Is anybody working on it, if not i am interested to work on it??

**Comment by JAORMX** [comment]
@adisky that's awesome! Please, if you can start working on it it would be greatly appreciated :)

**Comment by adisky** [comment]
@JAORMX Thanks, I am starting to work on it
@dims Thanks for the reference

**Comment by vakwetu** [comment]
@adisky  -- As we discussed, the encrypt/decrypt functionality is not in barbican API, but you can store the DEK in barbican and the barbican UUID in etcd.

Of course, we can try to do better by adding encrypt/decrypt to barbican.  Here is a spec -- please feel free to comment as we go through the design.  https://review.openstack.org/598389

**Comment by vakwetu** [comment]
@adisky @dims @JAORMX  - There is another intriguing possible direction on this -- https://github.com/enj/citadel

You could use citadel with the command "openstack secret get --payload <kek_uuid>  for instance,

**Comment by adisky** [comment]
@vakwetu Thanks for the specs in Barbican, I have started writing the plugin, I am using the same approach to store DEK in barbican and barbican uuid in etcd, When the specs gets implemented on barbican side we will store encrypted DEK in etcd as other KMS plugins are doing.
