### ISSUE TITLE
cinder-csi-plugin: Volume does not contain any information of the cluster and pv

### ISSUE THREAD

**Issue by lingxiankong** [kubernetes/cloud-provider-openstack#450]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind feature

**What happened**:
The volumes created by cinder-csi-plugin doesn't have any information e.g. the cluster name, the reclaim policy, etc. which are important for the resource management of cloud provider.

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- openstack-cloud-controller-manager version:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by jichenjc** [comment]
Also , please update snapshot as well... volume and snapshot should be in same category

**Comment by openstacker** [comment]
@jichenjc Yes, that's a good point. Snapshot will have the same issue.
