### ISSUE TITLE
Cluster-autoscaler support for OpenStack cloud provider

### ISSUE THREAD

**Issue by dims** [kubernetes/cloud-provider-openstack#46]
Track work in https://github.com/kubernetes/autoscaler/issues/734 and serve as a redirect for anyone looking for the support here in this repo

**Comment by zetaab** [comment]
https://github.com/kubernetes/kops/issues/3566#issuecomment-372634804 there was some talk about autoscaling in kops. Instead of implementing this thing to kops, we could make cluster-autoscaler to all purposes and then just deploy auto-scaler pod/service to kops installed cluster.

**Comment by ricolin** [comment]
I already start my work on  kubernetes/autoscaler#734
And I'm plan to work for kubernetes/kops#3566 as well
Let's discuss in PTG to figure out a plan for all

**Comment by zetaab** [comment]
@ricolin I have tried to plan how that thing should be implemented to kops. However, I have no idea how I should implement autoscalinggroups to kops. Also I have no idea can cloud-init be used like launch control things in aws (bash script which will install everything to machines).

**Comment by ricolin** [comment]
@zetaab are you in PTG now?

**Comment by zetaab** [comment]
nah
