### ISSUE TITLE
Run CSI Sanity Tests against cinder CSI driver

### ISSUE THREAD

**Issue by adisky** [kubernetes/cloud-provider-openstack#469]
**What happened**:
We should run CSI Sanity tests against cinder csi driver
https://github.com/kubernetes-csi/csi-test

**Comment by kiwik** [comment]
Hi @adisky , you can try to add a new job to cover this testing scenario in OpenLab, refer to https://github.com/theopenlab/openlab-zuul-jobs/tree/master/playbooks/cloud-provider-openstack-acceptance-test-csi-cinder
