### ISSUE TITLE
Periodic CI job in OpenStack foundation infrastructure

### ISSUE THREAD

**Issue by dims** [kubernetes/cloud-provider-openstack#47]
Can we test external cloud provider with kubespray in OpenStack infra?

cc @pabelanger

**Comment by pabelanger** [comment]
I think we can, right now the kubespray job is just running on openstack-dev/sandbox and to wrap it up and move it into openstack-zuul-jobs for projects to use.

What we'd really need is some instructions on how the cloud provider would be installed with kubespray, I don't really know how that would work.

**Comment by bogdando** [comment]
https://github.com/kubernetes-incubator/kubespray/blob/c2a46e4aa30c51bea96cdf3fc780245903aaa350/docs/openstack.md is all is needed to install kubespray with openstack provider AFAIK

**Comment by dims** [comment]
@bogdando @pabelanger i've added a request in kubespray as well - https://github.com/kubernetes-incubator/kubespray/issues/2642
