### ISSUE TITLE
Security group doesn't work when using Octavia

### ISSUE THREAD

**Issue by lingxiankong** [kubernetes/cloud-provider-openstack#490]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug

**What happened**:
With the configuration:
```
[LoadBalancer]
use-octavia=yes
subnet-id=7e5398da-a77a-4d5a-a2ae-f1273132f869
manage-security-groups=true
```
The service can't be accessed as expected, the security group on the worker node is not correctly configured.

**What you expected to happen**:
The service could be accessed as expected.

**How to reproduce it (as minimally and precisely as possible)**:
- CPO is running with the above configuration
- Create a LoadBalancer type service
- Access the service using external IP address.

**Anything else we need to know?**:
When using Octavia, the security group rule should allow traffic coming from Octavia amphorae.

**Environment**:
- openstack-cloud-controller-manager version:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by irozzo-1A** [comment]
@lingxiankong Could you please clarify if the documentation below is still relevant (https://github.com/kubernetes/cloud-provider-openstack/blob/4d3577878d0b74880e860cc5416e162775102884/docs/openstack-cloud-controller-manager/using-openstack-cloud-controller-manager.md#load-balancer):

> manage-security-groups If the Neutron security groups should be managed separately. Default: false

> This option is not supported for Octavia. The worker nodes and the Octavia amphorae are usually in the same subnet, so it's sufficient to config the port security group rules manually for worker nodes, to allow the traffic coming from the the subnet IP range to the node port range(i.e. 30000-32767).

My understanding is that this PR was intended to address this exact point, an I missing something?

**Comment by lingxiankong** [comment]
@ironcladlou sorry for the confusion this has caused. Actually, we (my cloud) have tested the config option `manage-security-groups` a lot in our cloud after this PR merged. However, we realized:

1. Basically the whole process worked but except for some edge cases, e.g. the octavia mgmt subnet has extended and the octavia amphorae has been failed over (either due to maintenance or repair).
2. We (my cloud) finally decided to set security group rules for the subnet IP range of the work nodes outside of openstack-cloud-controller-manager (in the orchestrator layer of our own k8s-as-a-service)
3. However, this feature can still be used in non-production environments for simple use cases, but in the documentation we (the upstream) decided to not recommend using that option with Octavia. We didn't remove the code as maybe in the future there is room for improvements.

**Comment by irozzo-1A** [comment]
Thx for the clarification @lingxiankong !
