### ISSUE TITLE
csi cinder plugin can not dynamic create pv 

### ISSUE THREAD

**Issue by jianglingxia** [kubernetes/cloud-provider-openstack#497]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
> /kind bug
> /kind feature

**What happened**:
the attacher provisioner and node-plugin pod running then create the storageclass and pvc but the pv can not dynamic create 
the pod running :
[root@host-101-101-101-134 csi]# kubectl get po --all-namespaces -w                                                       
NAMESPACE     NAME                                READY     STATUS    RESTARTS   AGE
kube-system   csi-attacher-cinderplugin-0         2/2       Running   0          18h
kube-system   csi-nodeplugin-cinderplugin-6l6mw   2/2       Running   1          18h
kube-system   csi-provisioner-cinderplugin-0      2/2       Running   0          2h
kube-system   kube-flannel-wd54d                  2/2       Running   1          1d

the storageclass and pvc use the web yaml:
https://github.com/kubernetes/cloud-provider-openstack/blob/master/manifests/cinder-csi-plugin/csi-provisioner-cinderplugin.yaml

and the pvc logs:
Events:
  Type     Reason                Age                From                                                                                  Message
  ----     ------                ----               ----                                                                                  -------
  Normal   Provisioning          6m (x11 over 1h)   csi-cinderplugin_csi-provisioner-cinderplugin-0_acde092b-3576-11e9-8591-0a58ac10000a  External provisioner is provisioning volume for claim "default/csi-pvc-cinderplugin"
  Warning  ProvisioningFailed    6m (x11 over 1h)   csi-cinderplugin_csi-provisioner-cinderplugin-0_acde092b-3576-11e9-8591-0a58ac10000a  failed to provision volume with StorageClass "csi-sc-cinderplugin": rpc error: code = Unknown desc = No suitable endpoint could be found in the service catalog.
  Normal   ExternalProvisioning  3m (x343 over 1h)  persistentvolume-controller                                                           waiting for a volume to be created, either by external provisioner "csi-cinderplugin" or manually created by system administrator

i use curl to get the instance 
[root@host-101-101-101-134 csi]# curl -X GET  'http://169.254.169.254/openstack/2012-08-10/meta_data.json'
{"availability_zone": "nova", "hostname": "storage.novalocal", "launch_index": 0, "uuid": "a2006d12-99dc-46ef-89bc-5ce3266413b6", "name": "storage"}

the cinder-plugin container is :
[root@host-101-101-101-134 csi]# kubectl exec -it csi-provisioner-cinderplugin-0 -n kube-system -c cinder /bin/bash       
[root@csi-provisioner-cinderplugin-0 /]# env
CSI_ATTACHER_CINDERPLUGIN_PORT=tcp://10.254.73.13:12345
HOSTNAME=csi-provisioner-cinderplugin-0
KUBERNETES_PORT_443_TCP_PORT=443
KUBERNETES_PORT=tcp://10.254.0.1:443
CSI_PROVISIONER_CINDERPLUGIN_PORT_12345_TCP_ADDR=10.254.248.149
CSI_PROVISIONER_CINDERPLUGIN_PORT=tcp://10.254.248.149:12345
KUBERNETES_SERVICE_PORT=443
CLUSTER_NAME=kubernetes
CLOUD_CONFIG=/etc/config/cloud.conf
KUBERNETES_SERVICE_HOST=10.254.0.1
CSI_PROVISIONER_CINDERPLUGIN_PORT_12345_TCP=tcp://10.254.248.149:12345
CSI_ENDPOINT=unix://csi/csi.sock

and the cloud.conf is 
[root@host-101-101-101-134 csi]# cat cloud.conf 
[Global]
auth-url=http://10.2.11.1:5000/v2.0/
username=storage1
password=storage1
region=RegionOne
tenant-id=d8f6da95565d443e92a80537c554f83b

**What you expected to happen**:
can create pv
**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:k8s v1.13
- openstack-cloud-controller-manager version:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by ramineni** [comment]
@jianglingxia could do query 
`openstack endpoint list` from the node where you are running k8s cluster and could you paste output

**Comment by jianglingxia** [comment]
[root@178_ctl ~(keystone_admin)]# openstack endpoint list
+----------------------------------+-----------+--------------+----------------+
| ID                               | Region    | Service Name | Service Type   |
+----------------------------------+-----------+--------------+----------------+
| 2e21a8bdf70f424f80f6e19f80a74d91 | RegionOne | cinder       | volume         |
| 1c40a32654f74a5a88fa34307d4a55fa | RegionOne | keystone     | identity       |
| 4d644aa9b7364949acd862a7e6f639ff | RegionOne | camelliav1   | camelliav1     |
| 30493624fb89445b8ab864625af51fed | RegionOne | glance       | image          |
| 5caf8372407b4b57952fdd5912d17273 | RegionOne | neutron      | network        |
| 2e6eb4b483d74e8d9974edeabbcf7a8f | RegionOne | heat         | orchestration  |
| 7bdfd90b0a854ce29b205b0ee049c83b | RegionOne | nova_ec2     | ec2            |
| 72962a2729ad4a439d844d0d624b5cfe | RegionOne | heat-cfn     | cloudformation |
| 9855b2f3c67246ca939fc55a70a3764b | RegionOne | nova         | compute        |
| 1bffa89a12a24a1c92e59fc8ed11a534 | RegionOne | novav3       | computev3      |
| 47187899f61b47729ed3b3411b7f3adf | RegionOne | ceilometer   | metering       |
| ff7a64ac49fc435caccea0aaf514fadf | RegionOne | cinderv2     | volumev2       |
| 1fc1055f166948f0a84dd02e8682c65d | RegionOne | ironic       | baremetal      |
+----------------------------------+-----------+--------------+----------------+

**Comment by adisky** [comment]
/close 
It seems @jianglingxia does and have cinder V3 endpoint, and CSI only supports V3
@jianglingxia If you want v2 support initiate discussion here or it better to upgrade cinder to v3
https://github.com/kubernetes/cloud-provider-openstack/pull/213
