### ISSUE TITLE
Support ca-file option when using csi

### ISSUE THREAD

**Issue by ramineni** [kubernetes/cloud-provider-openstack#498]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
/kind bug
> /kind feature

**What happened**:
Currently, when creating Openstack instance in csi, ca-file option is not considered. This should be supported 
**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- openstack-cloud-controller-manager version:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by darcyllingyan** [comment]
Hi @ramineni ,
The ca-file isn't supported now in CSI? 
I see in the doc **./cloud-provider-openstack/docs/provider-configuration.md** said, the cloud-config supports the ca-file:
##### Global Optional Parameters
* `ca-file`: Used to specify the path to your custom CA file.

Whether the bug means the request even I support the ca-file in the cloud-config(when created the csi secret yaml), it doesn't take effect?

Thanks

**Comment by adisky** [comment]
@darcyllingyan CSI has different code path for reading conf(as CSI and cloud-controller-manager are independent), it does not support ca-file

**Comment by ramineni** [comment]
@darcyllingyan ya . as @adisky mentioned, we have different code paths for csi, right now its not taking into effect.

**Comment by darcyllingyan** [comment]
Hi @adisky , @ramineni ,
Thanks very much for the information.
Seems the issue has been opened and whether there is a target date when it will be supported? As now in our project we need the ca-file to connect to Openstack to request the volume.

which part code should be modified to support the ca-file, the csi-provisioner? node-driver-registrar or others?
Thanks

**Comment by ramineni** [comment]
@darcyllingyan https://github.com/kubernetes/cloud-provider-openstack/pull/500 , still a work in progress patch, looking into it. you can expect it to be completed by next week

**Comment by darcyllingyan** [comment]
@ramineni ,
Thanks very much for the inforrmation.
I will have a try next week when it's ready.

Thanks
Darcy

**Comment by darcyllingyan** [comment]
Hi @adisky , @ramineni ,
I have another question.
Now the newest release is v1.13.1 which is published in 4 Jan 2019.
Now the release has 108 commits gap to master, so do you know when the next release is published?

Thank
Darcy

**Comment by ramineni** [comment]
@darcyllingyan next release would be planned in March (around 25th ) I suppose

**Comment by ramineni** [comment]
@darcyllingyan #500 this PR might solve your issue. Could you check?
