### ISSUE TITLE
bulid the cloud-provider-openstack print error with the "sigs.k8s.io/sig-storage-lib-external-provisioner/controller"

### ISSUE THREAD

**Issue by jianglingxia** [kubernetes/cloud-provider-openstack#522]
**Is this a BUG REPORT or FEATURE REQUEST?**:
 /kind bug

**What happened**:

i clone the cloud-provider-openstack code and bulid the rbd.go then log error :can't load package: package github.com/kubernetes-sigs/sig-storage-lib-external-provisioner/controller: code in directory /media/B/src/github.com/kubernetes-sigs/sig-storage-lib-external-provisioner/controller expects import "sigs.k8s.io/sig-storage-lib-external-provisioner/controller"

i see the web https://github.com/kubernetes-sigs/sig-storage-lib-external-provisioner/blob/master/controller/controller.go code import package :"sigs.k8s.io/sig-storage-lib-external-provisioner/controller/metrics"

and use go get also error:

[root@LIN-FE325E0FEA1 github.com]# go get github.com/kubernetes-sigs/sig-storage-lib-external-provisioner/controller
can't load package: package github.com/kubernetes-sigs/sig-storage-lib-external-provisioner/controller: code in directory /media/B/src/github.com/kubernetes-sigs/sig-storage-lib-external-provisioner/controller expects import "sigs.k8s.io/sig-storage-lib-external-provisioner/controller"

use go get then my dir dynamic create the sigs.k8s.io  dir 

[root@LIN-FE325E0FEA1 vendor]# ls
bitbucket.org  cloud.google.com  golang.org  google.golang.org  go.uber.org  LICENSE  sigs.k8s.io  vendor.json
BUILD          github.com        gonum.org   gopkg.in           k8s.io       OWNERS   vbom.ml
[root@LIN-FE325E0FEA1 vendor]# pwd
/media/B/src/vendor

@ramineni said @jianglingxia delete the vendor dir and build again i do it but many code dependecy the vendor dir

**What you expected to happen**:
i want the code can build and running, i test is that i modify the github.com/kubernetes-sigs/sig-storage-lib-external-provisioner/controller to "sigs.k8s.io/sig-storage-lib-external-provisioner/controller"
and build normal 
**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- openstack-cloud-controller-manager version: master branch
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by jianglingxia** [comment]
/assign @ramineni 
thanks for your review!

**Comment by jianglingxia** [comment]
#468

**Comment by jichenjc** [comment]
I think I asked simliar question in slack channel a few days before ... and rm vendor and Gopkg.lock rebuild solved that problem

**Comment by jianglingxia** [comment]
thanks for your reply!@jichenjc
i do it with your advice rm vendor but not found the Gopkg.lock  and then the error is :

 code in directory /media/B/src/github.com/kubernetes-sigs/sig-storage-lib-external-provisioner/controller expects import "sigs.k8s.io/sig-storage-lib-external-provisioner/controller"
../../../util/mount/mount_linux.go:33:2: cannot find package "golang.org/x/sys/unix" in any of:
	/usr/local/go/src/golang.org/x/sys/unix (from $GOROOT)
	/media/B/src/golang.org/x/sys/unix (from $GOPATH)
../volumeservice/connection.go:32:2: cannot find package "gopkg.in/gcfg.v1" in any of:

**Comment by jianglingxia** [comment]
can somebody help? i rm the vendor but the error always exist

main.go:24:2: code in directory /media/B/src/github.com/kubernetes-sigs/sig-storage-lib-external-provisioner/controller expects import "sigs.k8s.io/sig-storage-lib-external-provisioner/controller"
错误: 进程退出代码 1.

**Comment by ramineni** [comment]
@jianglingxia are u using master branch GoPkg.lock only?

**Comment by jianglingxia** [comment]
@ramineni  i have send you message in slack ,thanks
i fetch the master branch and build the main.go main.go:24:2: code in directory /media/B/src/github.com/kubernetes-sigs/sig-storage-lib-external-provisioner/controller expects import "sigs.k8s.io/sig-storage-lib-external-provisioner/controller"
i have remove the vendor
and the master branch have the Gopkg.lock and Gopkg.toml

**Comment by ramineni** [comment]
@jianglingxia as discussed on slack , build failing because you are using different tool to build which might not take into account Gopkg.lock file , and fetching the master of sig-storage-lib-external-provisioner .
As `make build` is succeeding , can i close this bug now?

**Comment by jianglingxia** [comment]
yeah, in your support and i have build success and i close the pr!thanks
