### ISSUE TITLE
Standalone-cinder Missing Secret

### ISSUE THREAD

**Issue by opal-labs** [kubernetes/cloud-provider-openstack#534]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:
Volume created by the standalone cinder provisioner fails to mount a pod due to a missing secret. 

**What you expected to happen**:
The pod to mount the volume.

**How to reproduce it (as minimally and precisely as possible)**:
I may be missing a step or doing something wrong, but on a bare metal kubernetes cluster I created a standalone-cinder-provisioner according to [this manifest](https://github.com/kubernetes/cloud-provider-openstack/blob/master/manifests/provisioner/deployment.yaml) trying to get [the example](https://github.com/kubernetes/cloud-provider-openstack/blob/master/examples/persistent-volume-provisioning/cinder/cinder-full.yaml) to work. The volume is being created in cinder, the pv shows as bound and the pvc shows as bound, but the pod fails to mount with `MountVolume.NewMounter initialization failed for volume "pvc-ee1eaa6e-45ad-11e9-af69-fa163e32930b" : Couldn't get secret default/standard-cephx-secret err: secrets "standard-cephx-secret" not found`. It looks like it's failing on step 13 of [the documentation](https://github.com/kubernetes/cloud-provider-openstack/blob/master/docs/using-cinder-standalone-provisioner.md).

**Anything else we need to know?**:
Kubernetes cluster is on VMs in OVH, talking to OVH cinder. According to #254 I need to create this secret manually, but I don't know if that's true or what's supposed to be in it since the provisioner has the required information to create the volume in the first place. 

**Environment**:
- k8scloudprovider/cinder-provisioner:latest
- Ubuntu 18.04.2 LTS

**Comment by silverbackdan** [comment]
I'd also like clarification on this if possible. I don't think I am wanting or needing to use Ceph right now. Was adding the standalone cinder plugin along with the csi controller plugin and csi node plugin the right thing to do, and is ceph required for the cinder standalone plugin?
