### ISSUE TITLE
latest on docker.io is version 0.2

### ISSUE THREAD

**Issue by dricoco** [kubernetes/cloud-provider-openstack#537]
/kind bug

**What happened**:
pulled cinder docker.io/k8scloudprovider/cinder-csi-plugin:latest and got version 0.2
**What you expected to happen**:
got the latest version of cinder-csi
**How to reproduce it (as minimally and precisely as possible)**:
this is a followup on closed issue #514 
I think a some moment on docker the latest version is the good one and at some other it's 0.2.
I wanted to exclude any kubernetes config bug so I just ran 

> docker run -i -t docker.io/k8scloudprovider/cinder-csi-plugin:latest  /bin/sh                                                                 [153/4618]
Unable to find image 'k8scloudprovider/cinder-csi-plugin:latest' locally
latest: Pulling from k8scloudprovider/cinder-csi-plugin
840caab23da4: Pull complete
56767d3c5823: Pull complete
707da695f2f7: Pull complete
Digest: sha256:d1f0feac6356b0a52b93ff6889b7b2bd63ae75112ec0a95f41e7027f20dcada7
Status: Downloaded newer image for k8scloudprovider/cinder-csi-plugin:latest

and then inside the container 

> /bin/cinder-csi-plugin  --nodeid=$(NODE_ID) --cloud-config=$(CLOUD_CONFI) --endpoint=zer
sh: NODE_ID: command not found
sh: CLOUD_CONFI: command not found
I0318 19:49:55.657173      39 driver.go:49] Driver: csi-cinderplugin version: 0.2.0

as you can see the csi cinderplugin version is not good.

**Comment by danielraad** [comment]
I just ran into this bug as well, I also tried with `imagePullPolicy: Always` to rule out local image cache.

**Comment by dricoco** [comment]
yes I tried it also with imagePullPolicy: Always, worked once this afternoon, and now got the 0.2 again

**Comment by danielraad** [comment]
@dricoco it seems that :latest was updated shortly after you created this issue and it is now working for me.

**Comment by dricoco** [comment]
image had been rebuilt 24 mn ago and it seems to be the right one on docker.io

**Comment by adisky** [comment]
pulling latest should always be on version 1.0.0, will check while this is happening meanwhile i will push a 1.0.0 image also

**Comment by danielraad** [comment]
@adisky fyi I just pulled `csi-cinderplugin version: 0.2.0` again from :latest

**Comment by adisky** [comment]
@danielraad I still not pushed 1.0.0, while doing this i found cinder-csi image is heavier, wait for this two PR's to get merged, then will push https://github.com/kubernetes/cloud-provider-openstack/pull/538
https://github.com/kubernetes/cloud-provider-openstack/pull/543

**Comment by dricoco** [comment]
thanks @adisky !

**Comment by ramineni** [comment]
@dricoco I tried the same , pulling latest version from docker.io gives me 1.0.0 version only

**Comment by dricoco** [comment]
that depends of the moment you are pulling it. But will be fixed when @adisky can tag a 1.0.0 release

**Comment by ramineni** [comment]
@dricoco tried just now.. @adisky you are also facing same issue with latest image?

**Comment by adisky** [comment]
@ramineni I have not checked, I just think a 1.0.0 tag should be available, latest is for CI and developers

**Comment by ramineni** [comment]
@adisky +1 on adding 1.0.0. tag, but the current latest image should also according to master, we should get that checked, I did pull the image , it is 1.0.0 only , could you check the same , if its according to master we can mark this bug as invalid

**Comment by adisky** [comment]
@ramineni sure, will check

**Comment by dricoco** [comment]
Just wondering, how long does it usually take for PR to be merged when test are ok ?

**Comment by ramineni** [comment]
@dricoco @adisky  14 mins ago one image is pushed which is 0.2.0 , I think some other job might be pushing this image with latest tag which is wrong, will check

**Comment by adisky** [comment]
@ramineni something fishy here
cc @kiwik @mrhillsman

**Comment by mrhillsman** [comment]
@adisky @ramineni file bug for jobs at https://github.com/theopenlab/openlab/issues/new/choose

**Comment by kiwik** [comment]
Looks it's root reason, see my comment https://github.com/theopenlab/openlab/issues/223#issuecomment-475535175

**Comment by ramineni** [comment]
@dricoco this should be fixed now, https://github.com/theopenlab/openlab-zuul-jobs/pull/478 could you check . so that we can close this issue?

**Comment by adisky** [comment]
CSI image for v1.14 (supporting CSI 1.0.0) is released and available on dockerhub, closing this issue, and the issue in latest image has also been resolved thanks to @mrhillsman @ramineni 
/close
