### ISSUE TITLE
enable log 

### ISSUE THREAD

**Issue by dricoco** [kubernetes/cloud-provider-openstack#539]
> /kind feature

**What happened**:
I have to debug communication between the pod and my openstack. I cannot pass -v4 or -v5 to the kubernetes manifest

```
# kubectl exec -it csi-provisioner-cinderplugin-0 -n kube-system -c cinder -- /bin/sh

sh-4.2# /bin/cinder-csi-plugin
Error: required flag(s) "cloud-config", "endpoint", "nodeid" not set
Usage:
  Cinder [flags]

Flags:
      --cloud-config string     CSI driver cloud config
      --cluster string          The identifier of the cluster that the plugin is running in.
      --endpoint string         CSI endpoint
  -h, --help                    help for Cinder
      --httptest.serve string   if non-empty, httptest.NewServer serves on this address and blocks
      --nodeid string           node id
```

**What you expected to happen**:
I expected that -v would be available in the flags

**How to reproduce it (as minimally and precisely as possible)**:
Just launch the manifest and check /bin/cinder-csi-plugin inside one of the pods

**Comment by dricoco** [comment]
the flags were available with version 0.2.0

>  /bin/cinder-csi-plugin --cloud-config zedez --endpoint zfezfze
> Error: required flag(s) "nodeid" not set
> Usage:
>   Cinder [flags]
> 
> Flags:
>       --alsologtostderr                  log to standard error as well as files
>       --cloud-config string              CSI driver cloud config
>       --endpoint string                  CSI endpoint
>   -h, --help                             help for Cinder
>       --httptest.serve string            if non-empty, httptest.NewServer serves on this address and blocks
>       --log_backtrace_at traceLocation   when logging hits line file:N, emit a stack trace (default :0)
>       --log_dir string                   If non-empty, write log files in this directory
>       --logtostderr                      log to standard error instead of files (default true)
>       --nodeid string                    node id
>       --stderrthreshold severity         logs at or above this threshold go to stderr (default 2)
>   -v, --v Level                          log level for V logs
>       --vmodule moduleSpec               comma-separated list of pattern=N settings for file-filtered logging
> 
> required flag(s) "nodeid" not setsh-4.2# /bin/cinder-csi-plugin --cloud-config zedez --endpoint zfezfze --nodeid string
> I0319 10:01:37.968814      16 driver.go:49] Driver: csi-cinderplugin version: 0.2.0
>

**Comment by ramineni** [comment]
@dricoco I have observed that too , may be recent packages update caused this , need to have look at it.

**Comment by dricoco** [comment]
if I check the example here 
https://github.com/kubernetes/klog/blob/master/examples/coexist_glog/coexist_glog.go
and
https://github.com/kubernetes/cloud-provider-openstack/blob/v0.2.0/cmd/cinder-csi-plugin/main.go

looks we are missing some little parts
```
import : 
	"github.com/golang/glog"
```

```
flag.Set("alsologtostderr", "true")
flag.Parse()
```
