### ISSUE TITLE
Please document how to setup local development environment

### ISSUE THREAD

**Issue by oz123** [kubernetes/cloud-provider-openstack#544]
/kind bug

**What happened**:
The documentation in `cloud-provider-openstack/docs/getting-started-provider-dev.md`
refers to a script in `./hack/local-up-cluster.sh`. However, this script does not exist. 

**What you expected to happen**:
I can find the script and setup a development environment.

**How to reproduce it (as minimally and precisely as possible)**:
Checkout the current master branch, see that  `./hack/local-up-cluster.sh` does not exist.

**Comment by adisky** [comment]
@oz123 ./hack/local-up-cluster.sh is a script to create local k8s cluster, it is here
https://github.com/kubernetes/kubernetes/blob/master/hack/local-up-cluster.sh

**Comment by oz123** [comment]
@adisky the documentation `getting-started-provider-dev.md` says:

> Start your cluster with the hack/local-up-cluster.sh with the proper environment variable set to enable the external cloud 

For a new comer,  `cluster` could be one of two: either a kubernetes cluster or openstack cluster.

As already a member of k8s one might know about the location you pointed to. I believe this should be improved in the readme.

**Comment by adisky** [comment]
About Openstack cloud, it is stated here
https://github.com/kubernetes/cloud-provider-openstack/blob/master/docs/getting-started-provider-dev.md#openstack-cloud
still if you feel to have more clarity, feel free to create a PR directly
