### ISSUE TITLE
k8s-keystone-auth: Policy setting improvement

### ISSUE THREAD

**Issue by lingxiankong** [kubernetes/cloud-provider-openstack#550]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind feature

**What happened**:
The authorization policy setting is too complex and not flexible, especially for the fine-grained controls for the resource.

**What you expected to happen**:
I'd propose the following setting format:
```JSON
[
  {
    "match": {
      "role": ["member"],
      "project": ["demo"]
    },
    "resource_permissions": [
      {"*.service": ["*"]},
      {"*.pod": ["get", "list", "watch"]},
      {"!kube-system.*": ["get", "list", "watch"]},
      {"*.*": ["get", "list", "watch"]},
      {"*.!secret": ["get", "list", "watch"]}
    ],
    "nonresource_permissions": [
      {"/healthz": ["get"]}
    ]
  },
  {...}
]
```

- The key in `resource_permissions` is in the format of `<namespace>.<resource>`
- `*` means all the namespaces or resources are allowed.
- `!` means all the namespaces or resources except the following one are allowed.
- The policy is whitelist and the config orders in `resource_permissions` matters.
- resource_permissions and nonresource_permissions can't be both used at the same time(same with the current behavior).

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- openstack-cloud-controller-manager version:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by lingxiankong** [comment]
There are some differences between the issue description and the actual implementation. The docs/using-keystone-webhook-authenticator-and-authorizer.md is the source of truth.

**Comment by dixudx** [comment]
@lingxiankong Thanks for proposing a v2 policy settings.

Before we move on, I have a few questions,

> The key in resource_permissions is in the format of <namespace>.<resource>

1. What about cluster-scoped resources? The format will be `.<resource>` ?
2. `.` has special meanings in regex. Better not use it. So why not having them into two parts?

> {"*.pod": ["get", "list", "watch"]}

Are the verbs here case sensitive?

> The policy is whitelist and the config orders in resource_permissions matters.

I know the limitations here due to the defined formats. But this will make users hard to maintain, especially when more regex expressions are used.

> the following setting format

The format here is quite different from current RBAC policy formats. I am not saying RBAC is perfect, that we should follow all that RBAC is doing now. But at least for Kubernetes users, maintaining two different formats of policies is painful.

The defined format here is only suitable for experienced users or administrators. While RBAC is more friendly to users.

**Comment by lingxiankong** [comment]
> @lingxiankong Thanks for proposing a v2 policy settings.
> 
> Before we move on, I have a few questions,
> 
>  The key in resource_permissions is in the format of .
> 
> 1. What about cluster-scoped resources? The format will be `.<resource>` ?

Have you tried to do some testing using the image I provided for cluster scoped resources? You will find the answer by yourself.

> 2. `.` has special meanings in regex. Better not use it. So why not having them into two parts?

I've already replied in the PR, I agree with you that `/` may be better.

> 
>  {"*.pod": ["get", "list", "watch"]}
> 
> Are the verbs here case sensitive?

I think so, should be mentioned in the doc.

> 
>  The policy is whitelist and the config orders in resource_permissions matters.
> 
> I know the limitations here due to the defined formats. But this will make users hard to maintain, especially when more regex expressions are used.

On the contrary, our operators are very happy with this solution. The k8s-keystone-auth is usually used in managed k8s as a service in the openstack based cloud. The users of k8s-keystone-auth are either the cloud operator or the cluster admin who are assumed to be experienced users.

@dixudx If you have a better idea or preferred solution, you are welcome to propose commits for this issue, I am very happy to ask our operators to review and test. Otherwise, I think it's better to follow the approach that has positive feedback of the real users.
