### ISSUE TITLE
client-keystone-auth: can no longer setup KUBECONFIG file with 'kubectl config ...' command

### ISSUE THREAD

**Issue by gwaines** [kubernetes/cloud-provider-openstack#583]
/kind bug

**What happened**:
With OLD version of client-keystone-auth, one could use 

kubectl --kubeconfig=/etc/kubernetes/admin.conf config set-credentials openstackuser --auth-provider=openstack

to update the KUBECONFIG file with the following lines ... to enable use of client-keystone-auth:
          -name openstackuser
            user:
               auth-provider:
                   config: {}
                   name: openstack

With the NEW version of client-keystone-auth, there does NOT seem to be any 'kubectl config ...' options for setting up the NEW lines required in the KUBECONFIG file.
e.g.
             - name: openstackuser
                user: 
                     exec:
                          command: "/etc/kubernetes/client-keystone-auth"
                          apiVersion: "client.authentication.k8s.io/v1beta1"

**What you expected to happen**:

Expected a command option like 

kubectl --kubeconfig=/etc/kubernetes/admin.conf config set-credentials openstackuser --command="/etc/kubernetes/client-keystone-auth"

... in order to enable client-keystone-auth in the KUBECONFIG file ... writing the appropriate lines.

**How to reproduce it (as minimally and precisely as possible)**:

% kubectl config set-credentials

.... shows the help and valid options.
Only valid options listed are:

Options:
      --auth-provider='': Auth provider for the user entry in kubeconfig
      --auth-provider-arg=[]: 'key=value' arguments for the auth provider
      --embed-certs=false: Embed client cert/key for the user entry in kubeconfig
      --password='': password for the user entry in kubeconfig
      --username='': username for the user entry in kubeconfig

**Anything else we need to know?**:

**Environment**:

- openstack-cloud-controller-manager version:
client-keystone-auth being used is 1.13.1 
‘kubectl’ @ Kubernetes 1.13.5 

- OS (e.g. from /etc/os-release):
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

- Kernel (e.g. `uname -a`):
Linux controller-1 3.10.0-957.1.3.el7.1.tis.x86_64 #1 SMP PREEMPT Wed Mar 13 09:48:27 EDT 2019 x86_64 x86_64 x86_64 GNU/Linux

- Install tools:
kubeadm

- Others:

**Comment by dims** [comment]
/assign @Fedosin 

Mike, can you please take a look?

**Comment by dims** [comment]
cc @lbragstad

**Comment by hogepodge** [comment]
cc @adisky

**Comment by adisky** [comment]
@gwaines  --kubeconfig file is a parent command option, you can still use it with  
> kubectl config set-credentials
do you want to report something else?? if so, please add the error output also.

**Comment by gwaines** [comment]
The issue is not that there is an error on the 'kubectl config set-credentials' command.

The issue is that there does not seem to be an option to setup the the 'openstackuser' User in the KUBECONFIG file as required by the new version of client-keystone-auth.

I.e. what is the exact 'kubectl config set-credentials ...' command syntax for adding the 'openstackuser' User in KUBECONFIG file, for the new version of client-keystone-auth ?

i.e. the 'kubectl config set-credentials ...' command to insert the following lines in KUBECONFIG file ?
     - name: openstackuser
        user:
          exec:
              command: "/etc/kubernetes/client-keystone-auth"
              apiVersion: "client.authentication.k8s.io/v1beta1"

**Comment by lingxiankong** [comment]
I'm wondering if it is a feature request to kubectl?  Here https://github.com/kubernetes/kubernetes/pull/73230

**Comment by gwaines** [comment]
Yeah this looks like what I'm looking for :-) 

So it looks like
- this feature is coded,
- this is targeted for kubernetes v1.15, 
- 'dims' just recently asked for the feature to be reviewed,
- so we are just waiting on the appropriate reviewers to approve ?
... then this will be available in Kubernetes v1.15 .

Am I reading the linked feature status correctly ?

**Comment by lingxiankong** [comment]
@gwaines I think you are right :-)

**Comment by hogepodge** [comment]
Thanks for raising this @gwaines

**Comment by lingxiankong** [comment]
@gwaines, given it's actually not a cloud-provider-openstack related issue, do you mind we close it for now?

**Comment by gwaines** [comment]
Yeah I'm fine with closing.
