### ISSUE TITLE
CinderCSI : PVC stays pending

### ISSUE THREAD

**Issue by dricoco** [kubernetes/cloud-provider-openstack#585]
**Is this a BUG REPORT or FEATURE REQUEST?**:
 /kind bug

**What happened**:
Tried to create a Pod as per the documentation nginx.yaml. the PVC stays pending

**What you expected to happen**:
PVC get bound

**How to reproduce it (as minimally and precisely as possible)**:
Following the doc
**Anything else we need to know?**:

>  kubectl describe pvc csi-pvc-cinderplugin2
Name:          csi-pvc-cinderplugin2
Namespace:     default
StorageClass:  csi-sc-cinderplugin
Status:        Pending
Volume:
Labels:        <none>
Annotations:   kubectl.kubernetes.io/last-applied-configuration:
                 {"apiVersion":"v1","kind":"PersistentVolumeClaim","metadata":{"annotations":{},"name":"csi-pvc-cinderplugin2","namespace":"default"},"spec...
               volume.beta.kubernetes.io/storage-provisioner: csi-cinderplugin
               volume.kubernetes.io/selected-node: secure-k8s-coreos22-q4gu3uehwhsl-minion-0
Finalizers:    [kubernetes.io/pvc-protection]
Capacity:
Access Modes:
VolumeMode:    Filesystem
Events:
  Normal     WaitForFirstConsumer   14m (x2 over 14m)    persistentvolume-controller                                                           waiting for first consumer to be created before binding
  Normal     Provisioning           14m                  csi-cinderplugin_csi-provisioner-cinderplugin-0_be2b49e7-5aed-11e9-9ed6-0a580a641d09  External provisioner is provisioning volume for claim "default/csi-pvc-cinderplugin2"
  Normal     ProvisioningSucceeded  13m                  csi-cinderplugin_csi-provisioner-cinderplugin-0_be2b49e7-5aed-11e9-9ed6-0a580a641d09  Successfully provisioned volume pvc-172d6eb1-5af7-11e9-a473-fa163e4ef924
  Normal     ExternalProvisioning   4m5s (x43 over 14m)  persistentvolume-controller                                                           waiting for a volume to be created, either by external provisioner "csi-cinderplugin" or manually created by system administrator

> kubectl logs csi-provisioner-cinderplugin-0 -n kube-system csi-provisioner
W0409 18:41:30.508361       1 controller.go:489] "fstype" is deprecated and will be removed in a future release, please use "csi.storage.k8s.io/fstype" instead
I0409 18:41:32.001129       1 controller.go:666] successfully created PV {GCEPersistentDisk:nil AWSElasticBlockStore:nil HostPath:nil Glusterfs:nil NFS:nil RBD:nil ISCSI:nil Cinder:nil CephFS:nil FC:nil Flocker:nil FlexVolume:nil AzureFile:nil VsphereVolume:nil Quobyte:nil AzureDisk:nil PhotonPersistentDisk:nil PortworxVolume:nil ScaleIO:nil Local:nil StorageOS:nil CSI:&CSIPersistentVolumeSource{Driver:cinder.csi.openstack.org,VolumeHandle:0d9c5244-04eb-41b2-b9f4-d47a9d619399,ReadOnly:false,FSType:ext4,VolumeAttributes:map[string]string{storage.kubernetes.io/csiProvisionerIdentity: 1554831268445-8081-csi-cinderplugin,},ControllerPublishSecretRef:nil,NodeStageSecretRef:nil,NodePublishSecretRef:nil,}}
I0409 18:41:32.001353       1 controller.go:1026] provision "default/csi-pvc-cinderplugin2" class "csi-sc-cinderplugin": volume "pvc-172d6eb1-5af7-11e9-a473-fa163e4ef924" provisioned
I0409 18:41:32.001610       1 controller.go:1040] provision "default/csi-pvc-cinderplugin2" class "csi-sc-cinderplugin": trying to save persistentvolume "pvc-172d6eb1-5af7-11e9-a473-fa163e4ef924"
I0409 18:42:02.004480       1 controller.go:1052] provision "default/csi-pvc-cinderplugin2" class "csi-sc-cinderplugin": failed to save persistentvolume "pvc-172d6eb1-5af7-11e9-a473-fa163e4ef924": Timeout: request did not complete within requested timeout 30s
I0409 18:42:12.004785       1 controller.go:1040] provision "default/csi-pvc-cinderplugin2" class "csi-sc-cinderplugin": trying to save persistentvolume "pvc-172d6eb1-5af7-11e9-a473-fa163e4ef924"
I0409 18:42:12.025887       1 controller.go:1044] provision "default/csi-pvc-cinderplugin2" class "csi-sc-cinderplugin": persistentvolume "pvc-172d6eb1-5af7-11e9-a473-fa163e4ef924" already exists, reusing
I0409 18:42:12.026085       1 controller.go:1088] provision "default/csi-pvc-cinderplugin2" class "csi-sc-cinderplugin": succeeded
I0409 18:42:12.026320       1 event.go:221] Event(v1.ObjectReference{Kind:"PersistentVolumeClaim", Namespace:"default", Name:"csi-pvc-cinderplugin2", UID:"172d6eb1-5af7-11e9-a473-fa163e4ef924", APIVersion:"v1", ResourceVersion:"10133", FieldPath:""}): type: 'Normal' reason: 'ProvisioningSucceeded' Successfully provisioned volume pvc-172d6eb1-5af7-11e9-a473-fa163e4ef924
I0409 18:49:35.734722       1 controller.go:926] provision "default/csi-pvc-cinderplugin2" class "csi-sc-cinderplugin": started
I0409 18:49:35.742912       1 controller.go:935] provision "default/csi-pvc-cinderplugin2" class "csi-sc-cinderplugin": persistentvolume "pvc-172d6eb1-5af7-11e9-a473-fa163e4ef924" already exists, skipping

the kube controller manager is looping on : 

> kubectl logs kube-controller-manager-secure-k8s-coreos22-q4gu3uehwhsl-master-0 -n kube-system
I0409 18:57:51.699957       1 event.go:221] Event(v1.ObjectReference{Kind:"PersistentVolumeClaim", Namespace:"default", Name:"csi-pvc-cinderplugin2", UID:"172d6eb1-5af7-11e9-a473-fa163e4ef924", APIVersion:"v1", ResourceVersion:"
10133", FieldPath:""}): type: 'Normal' reason: 'ExternalProvisioning' waiting for a volume to be created, either by external provisioner "csi-cinderplugin" or manually created by system administrator   

I don't see any communication problem between openstack and K8s, the volume are created on openstack

**Environment**:
- openstack-cloud-controller-manager version: latest
- OS (e.g. from /etc/os-release): coreos
- Kernel (e.g. `uname -a`): 4.19.25-coreos
- Install tools: magnum
- Others:

**Comment by dricoco** [comment]
service account are created :
 
> kubectl get serviceaccount -n kube-system     
NAME              SECRETS   AGE                         
coredns           1         19m                                               
csi-attacher      1         19m                                                                                                                                              
csi-nodeplugin    1         19m                                                                   
csi-provisioner   1         19m                         
csi-snapshotter   1         19m                                                               
default           1         19m                                           

clusterrole also

> kubectl get clusterrole -n kube-system
NAME                          AGE                       
csi-nodeplugin                19m                                              
external-attacher-runner      19m                                                                               
external-provisioner-runner   19m                                                    
external-snapshotter-runner   19m

**Comment by ramineni** [comment]
@dricoco could you share the yaml files of pod and pvc and storage class , you are using WaitForFirstConsumer option i suppose?

**Comment by dricoco** [comment]
@ramineni 
for the storage class :

> secure-k8s-coreos23-c2wb5tqgf5rn-master-0 cinder # cat storageclass.yaml
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: csi-sc-cinderplugin
provisioner: csi-cinderplugin
parameters:
  fsType: ext4
  availability: nova
volumeBindingMode: WaitForFirstConsumer

**Comment by dricoco** [comment]
for the pod, straight copy paste from the doc : 

`---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: csi-pvc-cinderplugin
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: csi-sc-cinderplugin

---
apiVersion: v1
kind: Pod
metadata:
  name: nginx 
spec:
  containers:
  - image: nginx
    imagePullPolicy: IfNotPresent
    name: nginx
    ports:
    - containerPort: 80
      protocol: TCP
    volumeMounts:
      - mountPath: /var/lib/www/html
        name: csi-data-cinderplugin 
  volumes:
  - name: csi-data-cinderplugin
    persistentVolumeClaim:
      claimName: csi-pvc-cinderplugin
readOnly: false`

**Comment by dricoco** [comment]
ok finally found the issue.
you shall not have Initializers in admissioncontrol.

Got inspired by this issue https://github.com/kubernetes/cloud-provider-vsphere/issues/135#issuecomment-464245608

if you are using this in conjunction with the cloud controller I still need the initializer.yaml file that is provided in the manifest for the cloud controller.

/close
