### ISSUE TITLE
cinder - alpine - udevadm not present in image

### ISSUE THREAD

**Issue by dricoco** [kubernetes/cloud-provider-openstack#592]
/kind bug
**What happened**:
I found in the cinder nodeplugin that udevadm was no where to be found
**What you expected to happen**:
exec udevadm
**How to reproduce it (as minimally and precisely as possible)**:
udevadm is present in the code :

cloud-provider-openstack% grep -r udevadm *

> pkg/volume/cinder/cinder_util.go:	cmdSettle := executor.Command("udevadm", argsSettle...)
> pkg/volume/cinder/cinder_util.go:		klog.Errorf("error running udevadm settle %v\n", errSettle)
> pkg/volume/cinder/cinder_util.go:	cmd := executor.Command("udevadm", args...)
> pkg/volume/cinder/cinder_util.go:		klog.Errorf("error running udevadm trigger %v\n", err)
> pkg/csi/cinder/mount/mount.go:	cmd := executor.Command("udevadm", args...)
> pkg/csi/cinder/mount/mount.go:		klog.V(3).Infof("error running udevadm trigger %v\n", err)

simple fix is to add the eudev package in the Dockerfile for the image : 
cluster/images/cinder-csi-plugin/Dockerfile

> cat cluster/images/cinder-csi-plugin/Dockerfile
> FROM alpine:3.7
> LABEL maintainers="Kubernetes Authors"
> LABEL description="Cinder CSI Plugin"
> 
> 
> RUN apk add --no-cache ca-certificates e2fsprogs **eudev**
> 
> ADD cinder-csi-plugin /bin/
> 
> CMD ["/bin/cinder-csi-plugin"]
>

**Comment by adisky** [comment]
@dricoco CSI code is not located here  _pkg/volume/cinder/cinder_util.go_, it is located in
_/pkg/csi/cinder_, it does not require _eudev_
/close

**Comment by dricoco** [comment]
my pod "csi-nodeplugin-cinderplugin-g82dm" was logging udevadm errors until I added this package so maybe it's not required by the code in csi, but to have the example of the doc working it's probably necessary.

**Comment by adisky** [comment]
@dricoco which example doc??

**Comment by dricoco** [comment]
I'm sorry I don't have the log anymore, but
if I grep again, I can see here :

> pkg/csi/cinder/mount/mount.go:	cmd := executor.Command("udevadm", args...)
> pkg/csi/cinder/mount/mount.go:		klog.V(3).Infof("error running udevadm trigger %v\n", err)

that it's using also udevadm on this part of the code. Sorry for the wrong grep

**Comment by adisky** [comment]
@dricoco there is no problem adding udevadm to docker file, it's just we have not faced any problem till now, if you are still able to reproduce the issue feel free to propose the PR

**Comment by dricoco** [comment]
sure will :)

**Comment by dricoco** [comment]
@adisky just did https://github.com/kubernetes/cloud-provider-openstack/pull/616

**Comment by adisky** [comment]
/close 
Refer https://github.com/kubernetes/cloud-provider-openstack/pull/616
