### ISSUE TITLE
reopen PR 543

### ISSUE THREAD

**Issue by dricoco** [kubernetes/cloud-provider-openstack#593]
/kind bug
Please reopen
https://github.com/kubernetes/cloud-provider-openstack/pull/543 as it is not working, I'll provide a new PR

**What happened**:
-v is not recognized by the executable
**What you expected to happen**:
Should see logs when using -v=5

**Comment by ramineni** [comment]
@dricoco it works fine for me .. i have checked with latest code, what is the error you are facing

**Comment by dricoco** [comment]
same than before, I just had to change for :

> 
> //func init() {
> //}
> 
> func main() {
> 
>   flag.Set("logtostderr", "true")

in main.go to have it working

**Comment by adisky** [comment]
@dricoco I am not able to reproduce 
 Its working with the latest code, Please recheck with the latest code
