### ISSUE TITLE
Dirver name change (935b358) broke upgradebility.

### ISSUE THREAD

**Issue by mape90** [kubernetes/cloud-provider-openstack#597]
**What happened**:
Driver name change from csi-cinderplugin to cinder.csi.openstack.org broke upgradebility. As old volumes will not be handled by updated plugin as its name is different.

**What you expected to happen**:
There should be flag to change the plugin name so that existing deployments would have upgrade path by keeping the old name.

**How to reproduce it (as minimally and precisely as possible)**:
Deploy plugin with any version before commit 935b358  and upgrade it to that version or later. Before upgrade you should create PVs. Then after upgrade those PVs will not be handled by any entity!

/kind bug

**Comment by dims** [comment]
cc @ramineni @adisky

**Comment by adisky** [comment]
@mape90 we have changed the name per CSI specs, As a workaround you can try to deploy two instances of cinder csi driver.
