### ISSUE TITLE
Support to the provider network type.

### ISSUE THREAD

**Issue by seungkyua** [kubernetes/cloud-provider-openstack#602]
/kind feature

**What happened**:
When deploying on OpenStack with provider network, the floating ip attached to vms.

**What you expected to happen**:
In case of using provider network, you don't need to add floating ip to vms. 

**How to reproduce it (as minimally and precisely as possible)**:
When you create cluster, it fails attaching floating ip. 

**Anything else we need to know?**:

**Environment**:
- OpenStack version : Pike
- openstack-cloud-controller-manager version: 
- OS (e.g. from /etc/os-release): Ubuntu 16.04 LTS
- Kernel (e.g. `uname -a`): Linux k1-master01 4.4.0-87-generic #110-Ubuntu SMP Tue Jul 18 12:55:35 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
- Install tools: 
- Others:

**Comment by lingxiankong** [comment]
@seungkyua hi, could you please describe more about the issue? What the command you were running? What functionality are your referring to?

**Comment by jichenjc** [comment]
I have same question... @seungkyua please provide more info on what's wrong there
I guess something like Loadbalancer has mandatory request on floating ip but others should not ...
