### ISSUE TITLE
Add support for mixed protocol loadbalancers 

### ISSUE THREAD

**Issue by grahamhayes** [kubernetes/cloud-provider-openstack#603]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind feature

**What you expected to happen**:

It should be possible to use a single IP to direct traffic to both UDP and TCP with a single Service of Type=Loadbalancer. 

Issue for kubernetes side: kubernetes/kubernetes#23880 
PR for enabling all Cloud Provider Interfaces: kubernetes/kubernetes#75831

When this PR merges we should update the OpenStack provider to provision UDP ports on octavia load balancers (where the deployed version of Octavia supports it).

**Comment by lingxiankong** [comment]
thanks grahamhayes for sync those information here, it should be easy for CPO to implement once the PR is merged.

**Comment by JrCs** [comment]
It's seems that in rocky and using octavia, we can use an haproxy that can loadbalance UDP traffic.
Can cloud-provider-openstack be upgrade to allow the creation of LB with UDP as protocol ?

**Comment by kayrus** [comment]
@grahamhayes @JrCs try the https://github.com/kayrus/ingress-terraform
I haven't tested the UDP support, since I don't have octavia, in theory it should work. If you have questions, feel free to contact me.
