### ISSUE TITLE
[CSI] Keystone token expires during long lasting request.

### ISSUE THREAD

**Issue by mape90** [kubernetes/cloud-provider-openstack#615]
**What happened**:
Attaching and detaching fails when token expires just after request is made.

This happens because gophercloud only reauthenticates when token is expired and it gets 401 as result. This causes problems because older Openstacks uses user token for their internal requests. With newer openstacks (i.e Pike) this will not happen as they generate service token for those long lasting requests so that expiration of user token will not cause failures. 
( More info https://github.com/gophercloud/gophercloud/issues/459 )

**What you expected to happen**:
For at least attach and detach commands should generate new token so that it would not expire during Openstack is making attach or detach. 

Something like this might work.
```
provider, err := CreateOpenStackProvider()
if err != nil {
   return err
}
err = volumeattach.Delete(provider.(*OpenStack).compute, instanceID, volume.ID).ExtractErr()
```
It is a bit hack as we only need new compute client and nothing else. 

Best fix would be that we would have way to get new compute client for those long lasting requests. For example we could store the openstack client in openstack struct and then it would have function to create new clients on demand. Or we could just scrap the reusing of clients and create new client every time we need to communicate to the openstack.

**How to reproduce it (as minimally and precisely as possible)**:
Have a older openstack and run attaching and detaching over long period of time so that there commands hit the token expiration. 

**Anything else we need to know?**:
Most likely snapshot functions will have this same issue as it might take a long time to complete them.

/kind bug

**Comment by jichenjc** [comment]
Just to confirm, the problem only occurs < openstack PIke release(no service token phase), correct?

**Comment by mape90** [comment]
This can actually happen in any openstack version, as not even the newer ones force the usage of service tokens. Quite many vendors even specifically set it off. It is only that in Pike or higher versions is is possible to fix this with configuring nova and cinder to use service tokens.

**Comment by kayrus** [comment]
@mape90 can you reproduce the issue with the new gophercloud version? https://github.com/gophercloud/gophercloud/pull/1746

**Comment by mape90** [comment]
I have not seen this issue for long time. So I think we can close this and if we see similar issues I can open new ticket.

**Comment by mape90** [comment]
Actually this is still relevant as old openstacks still use user token for their internal authentication. So new gophercloud will not help as is is designed to only reauthenticate when token expires. 

Only safe way to fix this is to make new client for every detach action. So that they will have long lasting token. This might also be optional thing so that only when you are working with old openstack cluster you would need this option and in other systems you would not need to create these extra clients as openstack would not be reusing these user tokens.
