### ISSUE TITLE
Security groups destroyed after removing a Service

### ISSUE THREAD

**Issue by GeertJohan** [kubernetes/cloud-provider-openstack#628]
I suspect the openstack cloud controller manager of destroying security groups when a Service of type LoadBalancer is removed. All rules from all security groups attached to master and node instances are removed, breaking the complete cluster.

I have encountered this on multiple occasions with when the openstack-cloud-controller-manager was running with `manage-security-groups=true` in the cloud config secret. Whereas the problem never occurred when that parameter wasn't set. N=6, but it's the only possible system that could do this. Apart from my local environment and the openstack-cloud-controller-manager, no system or user has the credentials to modify the security groups in open stack. I'm pretty sure I didn't remove the rules myself.

I'm running multiple k8s clusters, each on a separate openstack acount. They are created using  terraform and kubespray. Nodes are all running CoreOS. I'm not using Octavia (it's not supported by my openstack provider).
The controller is installed manually, using these manifests: https://github.com/kubernetes/cloud-provider-openstack/tree/master/manifests/controller-manager (kubespray only supports the deprecated built-in cloud-controller-manager, which I've disabled / "external")

**Comment by jichenjc** [comment]
maybe you can provide some info on the version of cloud controller you are using ? as seems we have some security group fix but not sure whether it's related..

and `manage-security-groups` seems used in octaviaConfig.ManageSecurityGroups and you mentioned you didn't use octavia...

**Comment by GeertJohan** [comment]
I'm using `docker.io/k8scloudprovider/openstack-cloud-controller-manager:latest`, I don't know which exact version I used. The last occurence of  this issue was on wednesday 29th using a fresh install, so presumably the most recent "latest" docker tag at that time. I haven't had `manage-security-groups` enabled since then.

I don't think I'm using octavia, no. Afaik it's LBaaS V2, as I still have to use `neutron lbaas-loadbalancer-list` (and friends) to inspect the loadbalancer.
openstack-cloud-controller-manager did set security groups on the loadbalancers when `manage-security-groups` was set, so even without octavia it seems to be active. The security groups it created worked fine. It only goes berserk on de security groups when the first Service of type LoadBalancer is removed.

I can try again if needed?

**Comment by lingxiankong** [comment]
@GeertJohan I did some security group improvement before for octavia based load balancer, and I've never tested the sg functions for neutron-lbaas given it has been deprecated since Queens. It's highly likely that the sg functions for neutron-lbaas is not working as expected.

**Comment by kciredor** [comment]
I'm afraid this issue has hit me as well just now. Ofcourse I can relate to octavia vs neutron-lbaas (the latter being deprecated). The real issue here is that out of 3 OpenStack-as-a-Service providers in .NL, 2 of them are on neutron-lbaas, only 1 is on octavia. Which is likely not a .NL specific thing.

Honestly I think neutron-lbaas needs some love. It works great for me when it works. But when it hits you with empty security groups cleared, all of a sudden, everything breaks down...

(For me there was no trigger at all, the cluster was not being worked on, just serving).

**Comment by kciredor** [comment]
Think I found it. Seems to have nothing to do with neutron-lbaas(v2) vs octavia btw.

Looking at https://github.com/kubernetes/kubernetes/blob/master/pkg/cloudprovider/providers/openstack/openstack_loadbalancer.go#L1560 if you add extra logging to dump opts.SecGroupID and opts. RemoteGroupID you'll notice this is actually the node security group and the loadbalancer security group that is/should be deleted.

So far so good.

Yet if you dump secGroupRules you'll quickly notice that these rules are not part of the filter that was given to getSecurityGroupRules at all. Looks like inside that method the call to rules.List(client, opts) does not properly apply the opts filter. Which ends up in gopherclient.

What makes this even more interesting to me is that the entire block of code starting from 'Delete the rules in the Node Security Group' seems unnescessary. Nothing has been created in the node security group, everything worked fine and was accessible, so why upon deletion of the lb should it start touching the node security group?

**Comment by piwi91** [comment]
Please remove the lifecycle label because this is still an issue. Unfortunately, I don't have much time to contribute to this project at the moment.
