### ISSUE TITLE
Add CI jobs for Manila CSI Driver

### ISSUE THREAD

**Issue by adisky** [kubernetes/cloud-provider-openstack#630]
/kind Feature

**What happened**:

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- openstack-cloud-controller-manager version:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by adisky** [comment]
cc @gman0

**Comment by gman0** [comment]
@adisky yes, CI tests are in the plan

**Comment by gman0** [comment]
@adisky can you assign me please?

**Comment by adisky** [comment]
@gman0 Please apply for k8s community membership
https://github.com/kubernetes/community/blob/master/community-membership.md

**Comment by gman0** [comment]
xref for csi-sanity tests https://github.com/kubernetes/cloud-provider-openstack/issues/714

**Comment by gman0** [comment]
xref for Zuul acceptance job https://github.com/theopenlab/openlab-zuul-jobs/pull/624
