### ISSUE TITLE
[Cinder CSI] GetMaxVolLimit returns always max value.

### ISSUE THREAD

**Issue by mape90** [kubernetes/cloud-provider-openstack#633]
**What happened**:
The function GetMaxVolLimit will always return max value when nodeserver calls it. 

This happens because nodeserver never calls function CreateOpenStackProvider what would imitialize cfg global variable. 

**What you expected to happen**:
GetMaxVolLimit should return the value defined in configuration.

**How to reproduce it (as minimally and precisely as possible)**:
Set cloud-clonfig value "node-volume-attach-limit" to 1-255 and it will be 256.

**Anything else we need to know?**:

Easiest fix would be just add check to the GetMaxVolLimit function if global variable cfg is initialized. 

For example something like this:
```
func GetMaxVolLimit() int64 {
  var err error
  if cfg.Global.AuthUrl == "" {
    cfg, _, err = GetConfigFromFile(configFile)
    if err != nil {
      klog.Errorf("Couldn't load config file!")
    }
  }
  if cfg.BlockStorage.NodeVolumeAttachLimit > 0 && cfg.BlockStorage.NodeVolumeAttachLimit <= 256 {
    return cfg.BlockStorage.NodeVolumeAttachLimit
  }
  return maxVol
}
```
Variable `cfg.Global.AuthUrl` is used to check initialization status as you can not have functional CSI it that value have not been initialized. 

**Environment**:
Cinder CSI master

/kind bug

**Comment by adisky** [comment]
@mape90 Thanks for reporting the bug, looking at the issue.

**Comment by adisky** [comment]
IMO, it is better to add `GetMaxVolLimit` in` IOOpenStack  interface`, and add ` bsopts` in `OpenStack` struct
```
type OpenStack struct {
    compute  *gophercloud.ServiceClient
    blockstorage  *gophercloud.ServiceClient
    bsopts  BlockStorageOpts
}
```
and then add cloud in nodeserver
``` 
type nodeServer struct {
	Driver   *CinderDriver
	Mount    mount.IMount
	Metadata openstack.IMetadata
        Cloud  openstack.IOpenStack
}
```

**Comment by adisky** [comment]
There are two pros of above approach
1. We might get the same problem with other config parameters we add in `BlockStorageOpts`, it will solve that issue also.
2. It might be possible we remove this parameter in future and directly take the value from Cinder API call (as they are adding some config related to it)

**Comment by adisky** [comment]
@mape90 Feel Free to propose PR  and discuss the solution.

**Comment by mape90** [comment]
Yes giving openstack interface would solve this issue nicely. But I do not think it would be possible to remove the parameter as there will be old openstacks that do not have that API implemented. Also nodes might have some own volumes attached to them that are reducing the quota. For examble if you use cinder as root volume or attach some "local" volumes to the nodes. So for these cases you always need possibility to change the NodeVolumeAttachLimit.

**Comment by adisky** [comment]
I am not saying we will not entirely remove the parameter, it can be a fallback option, prefered one will be value from cinder, even if you leave this case, considering the first pros, i think we should do it via interface.
> Yes giving openstack interface would solve this issue nicely. But I do not think it would be possible to remove the parameter as there will be old openstacks that do not have that API implemented. Also nodes might have some own volumes attached to them that are reducing the quota. For examble if you use cinder as root volume or attach some "local" volumes to the nodes. So for these cases you always need possibility to change the NodeVolumeAttachLimit.
