### ISSUE TITLE
[Cinder CSI] Volumes deleted outside k8s can not be removed from k8s

### ISSUE THREAD

**Issue by mape90** [kubernetes/cloud-provider-openstack#634]
**What happened**:
If volume is deleted in backend side cinder csi will hang forever in volume detaching and deletion. Same will happen to the snapshots. 

**What you expected to happen**:
If request is to delete or detach volume we should succeed if volume do not exists in backend side. As whole point of these commands are to get ride of the volumes and if it has already been deleted the tasks is already done. 

**How to reproduce it (as minimally and precisely as possible)**:
Delete volume manually in openstack. And then try to delete it in k8s.

**Anything else we need to know?**:
This affects controllerserver functions DeleteVolume, ControllerUnpublishVolume and DeleteSnapshot.

It could be fixed by adding check `cpoerrors.IsNotFound(err)`.

This could be fixed on controllerserver.go size or in openstack_volumes.go. 
In openstack_volumes.go you would need to fix functions:
DeleteVolume
```
func (os *OpenStack) DeleteVolume(volumeID string) error {
  used, err := os.diskIsUsed(volumeID)
  if err != nil {
    if cpoerrors.IsNotFound(err) {
      return nil
    }
    return err
  }
  ...
```
DetachVolume
```
func (os *OpenStack) DetachVolume(instanceID, volumeID string) error {
  volume, err := os.GetVolume(volumeID)
  if err != nil {
    if cpoerrors.IsNotFound(err) {
      return nil
    }
    return err
  }
  ...
```
WaitDiskDetached
```
func (os *OpenStack) WaitDiskDetached(instanceID string, volumeID string) error {
  backoff := wait.Backoff{
    Duration: diskDetachInitDelay,
    Factor:   diskDetachFactor,
    Steps:    diskDetachSteps,
  }
	
  err := wait.ExponentialBackoff(backoff, func() (bool, error) {
    attached, err := os.diskIsAttached(instanceID, volumeID)
    if err != nil{
      if cpoerrors.IsNotFound(err) {
        return true, nil
      }
      return false, err
    }
    return !attached, nil
  })
```
DeleteSnapshot
```
func (os *OpenStack) DeleteSnapshot(snapID string) error {
  err := snapshots.Delete(os.blockstorage, snapID).ExtractErr()
  if err != nil {
    if cpoerrors.IsNotFound(err) {
      return nil
    }
    klog.V(3).Infof("Failed to delete snapshot: %v", err)
  }
  return err
}
```

/kind bug

**Comment by adisky** [comment]
@mape90 +1 It is aligned with the CSI Specs,
Please Propose PR for the same.

**Comment by jichenjc** [comment]
+1 to the change or I can submit one as it's pretty easy now

**Comment by jichenjc** [comment]
@mape90 @adisky some comments from @ramineni here, according to 
https://github.com/container-storage-interface/spec/blob/master/spec.md#controllerunpublishvolume-errors, seems it's right that we can't change the condition to safely ignore the spec's suggestion, 
then the original behavior is correct or we can suggest to change the spec?

**Comment by adisky** [comment]
@jichenjc we can suggest spec changes until it is a very major issue, its better to address the issue aligned with specs, we can ignore not found error in case of delete volume but from ControllerUnPublishVolume we need to return error in case volume not found, however if volume is not attached to given node we can reply ok, and do not return any error

**Comment by jichenjc** [comment]
@adisky yes, I fully understand we need follow spec.... just want to make everyone on same page as the stuffs suggested in the original bug is a little different to the review comments

**Comment by adisky** [comment]
@jichenjc Thanks for understanding, lets follow the review comments :)
