### ISSUE TITLE
Extend OpenStack Application Credentials support

### ISSUE THREAD

**Issue by kayrus** [kubernetes/cloud-provider-openstack#640]
It's a follow-up for the #232 and a prerequisite for the https://github.com/gardener/gardener/issues/584

Application credentials have to be supported by:
* Cinder (block storage)
* Manila (nfs, share fs)
* Barbican (kms)
* LBaaS (ingress)

**Comment by adisky** [comment]
@kayrus Are you interested in doing this??

**Comment by kayrus** [comment]
@adisky for sure I am, since I created the issue. Why do you ask?

**Comment by adisky** [comment]
@kayrus it is better to assign issue, if you are working on it, (assigning is only possible if you are a member of k8s org) otherwise just write " I am working on this", we do this so as two people do not start working on same thing.

**Comment by kayrus** [comment]
Related #426

**Comment by kayrus** [comment]
@adisky I'll probably work on this issue. The openstack logic is a little bit complicated, and there is a lot of duplicate logic, which is already covered in https://github.com/gophercloud/utils/tree/master/openstack/clientconfig. I'd like to remove this logic from the cloud provider and use existing function from the https://github.com/gophercloud/utils/tree/master/openstack/clientconfig, since it is well tested and works with special cases

**Comment by adisky** [comment]
@kayrus Thanks for working on this, yes we are aware that there is lot of duplicated logic
we are happy to have it refactored :)

**Comment by kayrus** [comment]
@adisky it doesn't mean that the #731 is abandoned ;) One thing after another

**Comment by kayrus** [comment]
@adisky could you please clarify what is the reason to use similar code in:

https://github.com/kubernetes/cloud-provider-openstack/blob/6788416f43938c8cf45159f678d276baa388eb02/pkg/volume/cinder/volumeservice/connection.go#L58
https://github.com/kubernetes/cloud-provider-openstack/blob/6788416f43938c8cf45159f678d276baa388eb02/pkg/share/manila/shareoptions/openstackoptions.go#L77
https://github.com/kubernetes/cloud-provider-openstack/blob/6788416f43938c8cf45159f678d276baa388eb02/pkg/flexvolume/cinder_client.go#L45
https://github.com/kubernetes/cloud-provider-openstack/blob/6788416f43938c8cf45159f678d276baa388eb02/pkg/csi/manila/options/openstackoptions.go#L25
https://github.com/kubernetes/cloud-provider-openstack/blob/6788416f43938c8cf45159f678d276baa388eb02/pkg/csi/cinder/openstack/openstack.go#L80
https://github.com/kubernetes/cloud-provider-openstack/blob/6788416f43938c8cf45159f678d276baa388eb02/pkg/ingress/config/config.go#L42
https://github.com/kubernetes/cloud-provider-openstack/blob/6788416f43938c8cf45159f678d276baa388eb02/pkg/autohealing/config/config.go#L85
https://github.com/kubernetes/cloud-provider-openstack/blob/6788416f43938c8cf45159f678d276baa388eb02/pkg/kms/barbican/barbican.go#L22

Why don't they use the OpenStack logic from the `pkg/cloudprovider/providers/openstack/openstack.go`?

**Comment by kayrus** [comment]
nm, I covered my last question within #735

**Comment by adisky** [comment]
@kayrus the reason behind this is, all the plugins are not developed here, at very initial stage they are developed independently and later contributed here

**Comment by kayrus** [comment]
Fixed by #735
