### ISSUE TITLE
Support configuring lb-provider via a Service object annotation

### ISSUE THREAD

**Issue by dshcherb** [kubernetes/cloud-provider-openstack#665]
/kind feature

lb-provider configuration allows selecting an LBaaSv2 or Octavia provider type at the cluster deployment stage, however, when multiple types are available in the cloud it may be desirable to multiplex between them for different Service objects via annotations.
https://kubernetes.io/docs/concepts/cluster-administration/cloud-providers/#load-balancer

This would be similar to the following PR for floating IP pools:
https://github.com/kubernetes/kubernetes/pull/49697

There is already a useful helper that was introduced in that PR to retrieve a value from an annotation https://git.io/fjrQk

**Comment by kayrus** [comment]
@dshcherb try the https://github.com/kayrus/ingress-terraform
I don't have octavia, therefore I cannot test the behavior. If you have questions, feel free to contact me.
