### ISSUE TITLE
Implement GET_VOLUME_STATS node capability 

### ISSUE THREAD

**Issue by ramineni** [kubernetes/cloud-provider-openstack#669]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
> /kind bug
/kind feature

**What happened**:
NodeGetVolumeStats capability is missing in nodeserver. https://github.com/container-storage-interface/spec/blob/master/spec.md#nodegetvolumestats , This issue is to track the same.

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- openstack-cloud-controller-manager version:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by adisky** [comment]
/priority critical-urgent
This needs to be implemented as soon as possible, as intree cinder driver supports metrics, we need to add support for CSI as well.
cc @chrigl @ramineni

**Comment by adisky** [comment]
/priority important-soon It seems the state of metrics is not clear for CSI and migration
https://github.com/orgs/kubernetes-csi/projects/13

**Comment by zuzzas** [comment]
I'll submit all the required changes tonight.
