### ISSUE TITLE
[CSI] Cinder CSI expandvolume feature 

### ISSUE THREAD

**Issue by jichenjc** [kubernetes/cloud-provider-openstack#677]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
> /kind bug
/kind feature

**What happened**:
https://github.com/container-storage-interface/spec/blob/ /spec.md#controllerexpandvolume  track this to be implemented through CSI cinder
**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- openstack-cloud-controller-manager version:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by ramineni** [comment]
@jichenjc Patch is already up for it here https://github.com/kubernetes/cloud-provider-openstack/issues/565

**Comment by jichenjc** [comment]
missed that ...sorry
