### ISSUE TITLE
Support 'trust-device-path' parameter in cinder csi

### ISSUE THREAD

**Issue by ramineni** [kubernetes/cloud-provider-openstack#679]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
> /kind bug
> /kind feature

**What happened**:
 In most scenarios the block device names provided by Cinder (e.g. /dev/vda) can not be trusted. Add a flag which toggles this behavior. Setting it to true results in trusting the block device names provided by Cinder. The default value of false results in the discovery of the device path based on its serial number and /dev/disk/by-id mapping and is the recommended approach.

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- openstack-cloud-controller-manager version:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by dricoco** [comment]
Hello,
I think I've got a bug right here with that issue.
If I'm rebooting my minion I've got all the pod volume mixed up :

before reboot : 
for exemple : 
/dev/sdn: UUID="17546616-a488-413f-accd-e777a50a2438" TYPE="ext4"
 is mounted on
/dev/sdn on /var/lib/kubelet/pods/fed6d37f-edb7-11ea-964f-fa163ed4e5ac/volumes/kubernetes.io~csi/pvc-fecff072-edb7-11ea-964f-fa163ed4e5ac/mount type ext4 (rw,relatime,data=ordered)

after reboot :
/dev/sdn: UUID="b6f39a52-cf4c-40ae-ab4e-ed153f5ae103" TYPE="ext4"

but still 
/dev/sdn on /var/lib/kubelet/pods/fed6d37f-edb7-11ea-964f-fa163ed4e5ac/volumes/kubernetes.io~csi/pvc-fecff072-edb7-11ea-964f-fa163ed4e5ac/mount type ext4 (rw,relatime,data=ordered)

so pods are broken. Where should I look for the code handling this ?

**Comment by dricoco** [comment]
just replying to myself, apparently mounting by disk Id was added in 1.15

**Comment by jichenjc** [comment]
@dricoco so you mean this is fixed?
