### ISSUE TITLE
validator to check openstack connection and functionality

### ISSUE THREAD

**Issue by dims** [kubernetes/cloud-provider-openstack#68]
Similar to https://github.com/cloudfoundry-incubator/cf-openstack-validator for Testing how CF uses OpenStack (fog based ruby code)

example output - http://paste.openstack.org/show/716654/

**Comment by gonzolino** [comment]
@dims do you already have a plan on how to implement this validator?
We are currently using cf-openstack-validator to test our cloud and would love a similar solution for k8s.

Do you envision a set of tests that call gophercloud functions in the same way as the openstack cloud-provider does? If yes, is there already a list what exactly should be tested? Or do we need to compile such a list based on the cloud-provider code?

**Comment by dims** [comment]
@gonzolino, we could be calling gophercloud directly and/or via openstack cloud-provider, i am open to mix and match. yes, we have compile a list of things we look for in an openstack cloud. 

One slightly related idea I was particularly interested in helping new end users figure out what they will have to specify in their cloud configuration file as i have scratched my head many a time on what exactly i need to set for one thing or another. They should be able to start with just their keystone credentials and get help figuring out the rest. 

I'd be very happy to consult if you or anyone want to take the lead :)
