### ISSUE TITLE
Bump driver version before each release 

### ISSUE THREAD

**Issue by ramineni** [kubernetes/cloud-provider-openstack#683]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
> /kind bug
> /kind feature

**What happened**:
We are maintaining same version of the csi driver each release unless there are major breaking changes . Shouldn't we bump the driver version for each release , may be minor version as we have some new features supported by the driver for each release.
It would be easier to debug/maintain also. Thoughts?

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- openstack-cloud-controller-manager version:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by ramineni** [comment]
@adisky @hogepodge wdyt?

**Comment by jichenjc** [comment]
does this mean we have to maintain several releases at same time and the sample/manifest effort will be increased as well? I like the idea though

**Comment by adisky** [comment]
@ramineni currently we are upgrading version with csi version and keeping it similar to csi version, however here we missed it https://github.com/kubernetes/cloud-provider-openstack/pull/523, 
Anyways There is no point keeping the version similar(It is like we are following the previous approach), we can have minor version increment with the release
