### ISSUE TITLE
Improve functional testing (e2e) for Cinder CSI

### ISSUE THREAD

**Issue by ramineni** [kubernetes/cloud-provider-openstack#690]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
> /kind bug
> /kind feature

**What happened**:
No functional testing happening on gate for various features like topology, snapshot, block volume etc. We need to add the same

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- openstack-cloud-controller-manager version:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by jichenjc** [comment]
I can add some as well... maybe the snapshot part as I contribute to that part a little bit :)

**Comment by ramineni** [comment]
@jichenjc sure, feel free to contribute on the same :)
