### ISSUE TITLE
Conformance test not required to run on every PR

### ISSUE THREAD

**Issue by adisky** [kubernetes/cloud-provider-openstack#699]
**Is this a BUG REPORT or FEATURE REQUEST?**:
We are running conformance tests one every PR, these tests are heavy and takes time to run.  we can skip these tests for all plugins and run only for ccm.

> Uncomment only one, leave it on its own line: 
>
> /kind bug
> /kind feature

**What happened**:

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- openstack-cloud-controller-manager version:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by adisky** [comment]
cc @dims @hogepodge @lingxiankong @ramineni ??

**Comment by hogepodge** [comment]
Strongly agree.

**Comment by ramineni** [comment]
@adisky agreed. If conformance tests only use cloud provider code https://github.com/kubernetes/cloud-provider-openstack/tree/master/pkg/cloudprovider , then we can skip running for all other plugins. May be we can make it some periodic run to make sure we are in sync with latest k8s code. wdyt?
