### ISSUE TITLE
cinder-csi-plugin does not have options for leader election

### ISSUE THREAD

**Issue by bgagnon** [kubernetes/cloud-provider-openstack#702]
Of all the containers in the pod template of the  `csi-cinder-controllerplugin` StatefulSet, `docker.io/k8scloudprovider/cinder-csi-plugin` is the  only one that does not appear to have options for leader election.

Isn't this a requirement to run in HA with a multi-replica Deployment?

**Comment by jichenjc** [comment]
/assign
I am not expert, but I can take a look, if I will not able to fix it, I will unassign myself :)

**Comment by jichenjc** [comment]
ok, I mostly figured this out, will submit a PR soon..

**Comment by jichenjc** [comment]
@adisky it shows to me that we are using RPC server here, while some other containers like external-provisioner is using controller, my search shows the leader election only applied to controller, so do we have any comments on whether we still can use leader election here?

**Comment by bgagnon** [comment]
@jichenjc if leader election is not necessary for this particular container, then the StatefulSet with replicas=1 should be replaced with a Deployment with appropriate leader election flags on the containers that support it.

The comments in the docs suggest that the StatefulSet is being used precisely to avoid having more than one pod at all times... this led me to believe that leader election is not yet supported.

**Comment by jichenjc** [comment]
ok, I will take another look at this and paste some comments if I have . thanks for the info~ @bgagnon

**Comment by jichenjc** [comment]
just for record, I think using CSI-lib https://github.com/kubernetes-csi/csi-lib-utils will be a good choice to include leader election stuff as manila CSI did, then in turn encounter some issue and need fix https://github.com/kubernetes-csi/csi-lib-utils/pull/32 first

**Comment by bgagnon** [comment]
@jichenjc any updates on this issue?

**Comment by jichenjc** [comment]
sorry, busy in other stuffs recently, I unassign myself and will continue to work on it later if someone is not going to work on it

**Comment by m-yosefpor** [comment]
I don't understand why do we need to add leader election flag to driver. Leader election (lease) in case of csi are only for controllers to avoid race condition when watching/updating resources on api server. However csi driver act only as a gRPC server and which serves requests by other csi controllers (the ones that already support leader election). Only the one controller which is leader calls its side-car driver.
