### ISSUE TITLE
Ability to specify which interface to use for the cloud provider

### ISSUE THREAD

**Issue by asomya** [kubernetes/cloud-provider-openstack#713]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind feature

**What happened**:
I couldn't specify which interface endpoints to use for the Openstack cloud provider. It defaults to the public interface from the gophercloud SDK.

**What you expected to happen**:
A way to specify which interface to use in the cloud provider config:
e.g.
interface=internal or interface=admin
keep public by default if not specified.

**How to reproduce it (as minimally and precisely as possible)**:
Start any cluster with the openstack cloud provider and turn on verbose logging to see the requests going to the public endpoint.

**Anything else we need to know?**:

**Environment**:
- openstack-cloud-controller-manager version: all
- OS (e.g. from /etc/os-release): all
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by asomya** [comment]
I would like to work on this, can someone please assign it to me?

**Comment by lingxiankong** [comment]
Hi @asomya, thanks for raising this issue, could you please add more information for this feature request, e.g. what's the problem with the current implementation, maybe add some logs you've seen? It will help us to know better about what we are going to enhance. Thanks!

**Comment by kayrus** [comment]
@lingxiankong it looks like @asomya is referring to the https://docs.openstack.org/security-guide/api-endpoints/api-endpoint-configuration-recommendations.html
User can specify the endpoint_type (e.g. `OS_ENDPOINT_TYPE`) and it can be used to determine the endpoint (https://github.com/gophercloud/gophercloud/blob/13466e32a4a33946a48a259784a7f1f470d78513/endpoint_search.go). I can take a look on this request.
