### ISSUE TITLE
Openstack LB SG not updating after port changes

### ISSUE THREAD

**Issue by infinitydon** [kubernetes/cloud-provider-openstack#724]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:
If a port is added to an existing k8s LB service, the SG is not updated to reflect the change thereby traffic to the new port will not be allowed (unless you manually update the SG yourself).

**How to reproduce it (as minimally and precisely as possible)**:

1.) Create new k8s service LB.

2.) Add another port to the service, check the SG if it add a new rule for the new port

You can also check the gist: 

https://gist.github.com/infinitydon/7d27767c6650520a5395703be1b1cf58#gistcomment-2998106

**Cloud-config:**

```
[LoadBalancer]
lb-version = "v2"
subnet-id = "c1509fca-1872-40b9-a7b5-5cc01d611d6f"
floating-network-id = "8bb661f5-76b9-45f1-9ef9-eeffcd025fe4"
lb-method = "ROUND_ROBIN"
manage-security-groups = true
```

**Environment**:
- openstack-cloud-controller-manager version: How to check this specifically? Cluster was installed with kubeadm
- OS (e.g. from /etc/os-release): **Ubuntu bionic**
- Kernel (e.g. `uname -a`): **4.15.0-55-generic**
- Install tools: kubeone (kubeadm v1.14.2)

_**N.B -- I tested this on other cloud providers like AWS and GCP, port changes are always reflected in the SG.**_

**Comment by lingxiankong** [comment]
@infinitydon are you using Octavia or Neutron-LBaaS?

**Comment by infinitydon** [comment]
@lingxiankong I am using Neutron-LBaaS

**Comment by lingxiankong** [comment]
Hi @infinitydon, please see my comments in https://github.com/kubernetes/cloud-provider-openstack/issues/628, currently we are lack of contributors who are using Neutron-LBaaS with openstack-cloud-controller-manager :-(

**Comment by infinitydon** [comment]
Can you confirm if Octavia is not affected with this issue? I currently don't have access to an octavia based deployment..

**Comment by lingxiankong** [comment]
@infinitydon https://github.com/kubernetes/cloud-provider-openstack/blob/master/docs/provider-configuration.md#load-balancer-optional-parameters

> When using Octavia, the worker nodes and the Octavia amphorae are usually in the same subnet, so it's sufficient to config the port security group rules manually for worker nodes, to allow the traffic coming from the the subnet IP range to the node port range(usually it is 30000-32767). As a result, manage-security-groups is not needed when using Octavia.

**Comment by infinitydon** [comment]
Ok.. But I will like to suggest that the feature should be looked at as this works very well with the public clouds, I have tested this on AWS, GCP, any update to a k8s LB service ports will trigger the appropriate changes in the security group that is associated with that LB.
