### ISSUE TITLE
Cinder Volumes Do Not Reattach On Node Shutdown

### ISSUE THREAD

**Issue by cwolfinger** [kubernetes/cloud-provider-openstack#737]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug

**What happened**:
Ran a deployment with a PV cinder volume.  Shutdown the node via Horizon console.  Pod was stuck in "Init" state waiting for the PV to attach.

**What you expected to happen**:
PV would detach from the shutdown node and reattached to the new node.

**How to reproduce it (as minimally and precisely as possible)**:
- Run a deployment with a PVC 
- Shutdown the node via Horizoon that has the deployment's pod running

**Anything else we need to know?**:
Example of hung pod:
```
test-686c498d6b-2d726                                 2/2     Terminating         0          179m    192.200.3.18    node2             <none>           <none>
test-686c498d6b-b7x2b                                 0/2     ContainerCreating   0          19m     <none>          node1             <none>           <none>
```

**Environment**:
- openstack-cloud-controller-manager version: 
```
docker.io/k8scloudprovider/cinder-csi-plugin:v1.15.0
quay.io/k8scsi/csi-attacher:v1.2.0
quay.io/k8scsi/csi-node-driver-registrar:v1.1.0	
quay.io/k8scsi/csi-provisioner:v1.3.0	
quay.io/k8scsi/csi-snapshotter:v1.2.0
```
OS (e.g. from /etc/os-release): 
```
NAME="Ubuntu"
VERSION="18.04.2 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.2 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
```
- Kernel (e.g. `uname -a`):
```
Linux master1 5.0.0-23-generic #24~18.04.1-Ubuntu SMP Mon Jul 29 16:12:28 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```
- Install tools:
kubeadm
- Others:

**Comment by mape90** [comment]
Logic for selecting when and where to attach volumes isn't managed by CSI driver. It is done by attacher-detacher-controller in kubernetes manager. (code is located in kubernetes core repo)

Also this behavior is intended as control loop can not know if node is down or if there is just net-split and volume would still be in use. 

If k8s logic would just forcefully detach volume and attach it to new node the data on volume might get corrupted.

In production environments you should never shutdown node before draining it. If node crashes it needs to be manually fixed or removed from cluster.

**Comment by horakmar** [comment]
Hello. I have the same problem.
After a node crash volumes stay in attached state (at least for Kubernetes, because Horizon says they are not attached to any node). How can I tell Kubernetes, to remove that node from cluster? It is removed automatically (kubectl get nodes doesn't show it). But volumes are not possible to reattach because of "already attached" state.
How to at least manually deattach volumes from dead/nonexistent node?

**Comment by mape90** [comment]
Seems like you have something broken in Openstack side. Horizon do not always show volume information correctly. So it is better to use cli as there you get actual data. I.e if server do not exist then horizon might not show any attachments on volume even volume might have attachments in it. So then the Cinder CSI will fail to attach as there is already attachments on the volume. 

If you have OS cloud provider and you just delete the vm it should find it out and delete it from cluster and openstack should detach all volumes attached to that node. So everything gets just scheduled to other nodes.

What you described is that node do not exit but volumes can not be attached to new nodes. So then might be that something failed in communication between nova and cinder.

To fix this only way is to use cinder cli to reset the state of volume. 
Following commands might help:
cinder reset-state --state available $id
cinder reset-state --attach-status detached $id

Kubernetes should never delete nodes. Only the openstack cloud provider might delete nodes if they do not exist any more.

**Comment by lingxiankong** [comment]
@mape90 thanks for the informative answer
