### ISSUE TITLE
Cinder CSI plugin with OIDC

### ISSUE THREAD

**Issue by xpivarc** [kubernetes/cloud-provider-openstack#744]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
> /kind bug
 /kind feature

**What happened**:
I would expect there is support to use cinder csi plugin with oidc and without openstack cloud controller. Am I missing something or is this feature coming ? 

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- openstack-cloud-controller-manager version:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by jichenjc** [comment]
the best search on oidc is openid connect..   can you elaborate on the question? Thanks

**Comment by adisky** [comment]
@xpivarc cinder csi plugin can be used without openstack cloud controller manager

**Comment by xpivarc** [comment]
@jichenjc In our private openstack we use federation auth. So to clear my question: Is there a way to use cinder csi plugin with generated app credentials from openstack. I only see the possibility to use name + passw (basic auth)

@adisky That's clear to me. I am interesting in auth capabilities.

**Comment by jichenjc** [comment]
https://github.com/kubernetes/cloud-provider-openstack/pull/426
not sure this is you are looking for 

sorry, I don't whether v3oidaccesstoken supported or not, @lingxiankong do you know about this?

**Comment by xpivarc** [comment]
@jichenjc Seems like it. Just to clarify. Does Cinder CSI plugin also support ApplicationCredential ? Seems like #640 is addressing this. Can you provide some docs or example cloud-config with ApplicationCredential ? Thanks

**Comment by jichenjc** [comment]
ok, my bad, I thought that fixed, I didn't notice the follow up patch

googled some doc might help :
https://object-storage-ca-ymq-1.vexxhost.net/swift/v1/6e4619c416ff4bd19e1c087f27a43eea/www-assets-prod/presentation-media/Enabling-Cloud-Native-Applications-with-Application-Credentials-in-Keystone.pdf
