### ISSUE TITLE
Octavia LB CI Job is failing

### ISSUE THREAD

**Issue by adisky** [kubernetes/cloud-provider-openstack#750]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug

**What happened**:
` cloud-provider-openstack-acceptance-test-lb-octavia ` is failing , It would be difficult for openlab team to provide octavia as a service, the job needs to be moved on devstack

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- openstack-cloud-controller-manager version:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by ramineni** [comment]
still not enabled
