### ISSUE TITLE
Octavia Ingress Controller Fails with latest

### ISSUE THREAD

**Issue by DJAyth** [kubernetes/cloud-provider-openstack#754]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
/kind bug
> /kind feature

**What happened**:
So a few months ago I started toying with the openstack provider, specifically the octavia ingress stuff as it would have been useful to us. I ended up having to drop it as our provider was on version Pike, which didn’t support bulk creation of members for LB’s. Well they updated the version to Queens which has that functionality, so I went back to it. After fixing an issue I had with auth, the statefulset made it past that, however, the pod for the ingress controller panics and crashes using the latest tag from docker hub.

**What you expected to happen**:
Expect stateful set to start and controller to be available.

**How to reproduce it (as minimally and precisely as possible)**:
Simply follow the instructions in https://github.com/kubernetes/cloud-provider-openstack/blob/master/docs/using-octavia-ingress-controller.md, using the latest tag for the image.

**Anything else we need to know?**:
Looked at the page for the image in Docker Hub and latest was updated 9 hours ago. So I changed the tag from latest to v1.15.0 and the controller comes online. The errors from the logs are as so:

`time="2019-09-10T14:47:58Z" level=info msg="Using config file" file=/etc/config/octavia-ingress-controller-config.yaml
W0910 14:47:58.803504 1 client_config.go:541] Neither --kubeconfig nor --master was specified. Using the inClusterConfig. This might not work.
E0910 14:47:59.414664 1 runtime.go:69] Observed a panic: &runtime.TypeAssertionError{_interface:(*runtime._type)(0x13a7360), concrete:(*runtime._type)(0x154c0a0), asserted:(*runtime._type)(0x154d720), missingMethod:""} (interface conversion: interface {} is *v1beta1.Ingress, not *v1beta1.Ingress (types from different packages))
goroutine 55 [running]:
k8s.io/cloud-provider-openstack/vendor/k8s.io/apimachinery/pkg/util/runtime.logPanic(0x13deec0, 0xc0006bb6e0)
/home/zuul/src/k8s.io/cloud-provider-openstack/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:65 +0x7b
k8s.io/cloud-provider-openstack/vendor/k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
/home/zuul/src/k8s.io/cloud-provider-openstack/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:47 +0x82
panic(0x13deec0, 0xc0006bb6e0)
/usr/local/go/src/runtime/panic.go:522 +0x1b5
k8s.io/cloud-provider-openstack/pkg/ingress/controller.NewController.func1(0x154c0a0, 0xc000279c80)
/home/zuul/src/k8s.io/cloud-provider-openstack/pkg/ingress/controller/controller.go:242 +0x3bc
k8s.io/cloud-provider-openstack/vendor/k8s.io/client-go/tools/cache.ResourceEventHandlerFuncs.OnAdd(...)
/home/zuul/src/k8s.io/cloud-provider-openstack/vendor/k8s.io/client-go/tools/cache/controller.go:196
k8s.io/cloud-provider-openstack/vendor/k8s.io/client-go/tools/cache.(*processorListener).run.func1.1(0xc000278a80, 0xc0002b64b0, 0x40b6a9)
/home/zuul/src/k8s.io/cloud-provider-openstack/vendor/k8s.io/client-go/tools/cache/shared_informer.go:642 +0x26d
k8s.io/cloud-provider-openstack/vendor/k8s.io/apimachinery/pkg/util/wait.ExponentialBackoff(0x989680, 0x3ff0000000000000, 0x3fb999999999999a, 0x5, 0x0, 0xc00048fe38, 0x42ac1f, 0xc0002b64e0)
/home/zuul/src/k8s.io/cloud-provider-openstack/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:284 +0x51
k8s.io/cloud-provider-openstack/vendor/k8s.io/client-go/tools/cache.(*processorListener).run.func1()
/home/zuul/src/k8s.io/cloud-provider-openstack/vendor/k8s.io/client-go/tools/cache/shared_informer.go:636 +0x79
k8s.io/cloud-provider-openstack/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0xc0006adf68)
/home/zuul/src/k8s.io/cloud-provider-openstack/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:152 +0x54
k8s.io/cloud-provider-openstack/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc00048ff68, 0xdf8475800, 0x0, 0x42b401, 0xc000086de0)
/home/zuul/src/k8s.io/cloud-provider-openstack/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:153 +0xf8
k8s.io/cloud-provider-openstack/vendor/k8s.io/apimachinery/pkg/util/wait.Until(...)
/home/zuul/src/k8s.io/cloud-provider-openstack/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88
k8s.io/cloud-provider-openstack/vendor/k8s.io/client-go/tools/cache.(*processorListener).run(0xc0002bd980)
/home/zuul/src/k8s.io/cloud-provider-openstack/vendor/k8s.io/client-go/tools/cache/shared_informer.go:634 +0x9c
k8s.io/cloud-provider-openstack/vendor/k8s.io/apimachinery/pkg/util/wait.(*Group).Start.func1(0xc0005a61b0, 0xc000360940)
/home/zuul/src/k8s.io/cloud-provider-openstack/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:71 +0x4f
created by k8s.io/cloud-provider-openstack/vendor/k8s.io/apimachinery/pkg/util/wait.(*Group).Start
/home/zuul/src/k8s.io/cloud-provider-openstack/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:69 +0x62
panic: interface conversion: interface {} is *v1beta1.Ingress, not *v1beta1.Ingress (types from different packages) [recovered]
panic: interface conversion: interface {} is *v1beta1.Ingress, not *v1beta1.Ingress (types from different packages)
goroutine 55 [running]:
k8s.io/cloud-provider-openstack/vendor/k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
/home/zuul/src/k8s.io/cloud-provider-openstack/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:54 +0x105
panic(0x13deec0, 0xc0006bb6e0)
/usr/local/go/src/runtime/panic.go:522 +0x1b5
k8s.io/cloud-provider-openstack/pkg/ingress/controller.NewController.func1(0x154c0a0, 0xc000279c80)
/home/zuul/src/k8s.io/cloud-provider-openstack/pkg/ingress/controller/controller.go:242 +0x3bc
k8s.io/cloud-provider-openstack/vendor/k8s.io/client-go/tools/cache.ResourceEventHandlerFuncs.OnAdd(...)
/home/zuul/src/k8s.io/cloud-provider-openstack/vendor/k8s.io/client-go/tools/cache/controller.go:196
k8s.io/cloud-provider-openstack/vendor/k8s.io/client-go/tools/cache.(*processorListener).run.func1.1(0xc000278a80, 0xc0002b64b0, 0x40b6a9)
/home/zuul/src/k8s.io/cloud-provider-openstack/vendor/k8s.io/client-go/tools/cache/shared_informer.go:642 +0x26d
k8s.io/cloud-provider-openstack/vendor/k8s.io/apimachinery/pkg/util/wait.ExponentialBackoff(0x989680, 0x3ff0000000000000, 0x3fb999999999999a, 0x5, 0x0, 0xc00006be38, 0x42ac1f, 0xc0002b64e0)
/home/zuul/src/k8s.io/cloud-provider-openstack/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:284 +0x51
k8s.io/cloud-provider-openstack/vendor/k8s.io/client-go/tools/cache.(*processorListener).run.func1()
/home/zuul/src/k8s.io/cloud-provider-openstack/vendor/k8s.io/client-go/tools/cache/shared_informer.go:636 +0x79
k8s.io/cloud-provider-openstack/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0xc0006adf68)
/home/zuul/src/k8s.io/cloud-provider-openstack/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:152 +0x54
k8s.io/cloud-provider-openstack/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc00006bf68, 0xdf8475800, 0x0, 0x42b401, 0xc000086de0)
/home/zuul/src/k8s.io/cloud-provider-openstack/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:153 +0xf8
k8s.io/cloud-provider-openstack/vendor/k8s.io/apimachinery/pkg/util/wait.Until(...)
/home/zuul/src/k8s.io/cloud-provider-openstack/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88
k8s.io/cloud-provider-openstack/vendor/k8s.io/client-go/tools/cache.(*processorListener).run(0xc0002bd980)
/home/zuul/src/k8s.io/cloud-provider-openstack/vendor/k8s.io/client-go/tools/cache/shared_informer.go:634 +0x9c
k8s.io/cloud-provider-openstack/vendor/k8s.io/apimachinery/pkg/util/wait.(*Group).Start.func1(0xc0005a61b0, 0xc000360940)
/home/zuul/src/k8s.io/cloud-provider-openstack/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:71 +0x4f
created by k8s.io/cloud-provider-openstack/vendor/k8s.io/apimachinery/pkg/util/wait.(*Group).Start
/home/zuul/src/k8s.io/cloud-provider-openstack/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:69 +0x62`

**Environment**:
- openstack-cloud-controller-manager version:
- OS (e.g. from /etc/os-release): ubuntu 18.04

**Comment by oomichi** [comment]
This issue is what I also am facing.

/cc @oomichi

**Comment by mikejoh** [comment]
@oomichi Thanks, not sure what i'm looking for after all.. This might be real long shot but in the stacktrace there's these two lines that caught my eye:
```
panic: interface conversion: interface {} is *v1beta1.Ingress, not *v1beta1.Ingress (types from different packages)
```
and
```
/home/zuul/src/k8s.io/cloud-provider-openstack/pkg/ingress/controller/controller.go:242 +0x3bc
```
In `controller.go` on line `242` the following happens:
https://github.com/kubernetes/cloud-provider-openstack/blob/23ac807a68fbf3eece678bb5977dcf64559568a9/pkg/ingress/controller/controller.go#L242
This was changed in PR [658](https://github.com/kubernetes/cloud-provider-openstack/pull/658) from `extensions/v1beta1` to `networking.k8s.io/v1beta1` since the former one will be deprecated in v1.18.

When searching for more info i found this issue: https://github.com/golang/go/issues/26094. As i said, this is a long shot, but could there be something in the issue above (and the fact that the API of Ingress was changed) that crashes the Ingress controller? Or could it be a combination of versions of different imported packages causing this?

Ping @lingxiankong, does this make any sense to you?

**Comment by lingxiankong** [comment]
@mikejoh thanks for the investigation! Yes, the L242 in `controller.go` looks suspicious, I'm using k8s v1.14.5, @oomichi is using v1.15.1, @DJAyth didn't mention his version. I will try to install v1.15.X and verify again.

**Comment by mikejoh** [comment]
@oomichi @DJAyth I have successfully built and started the Octavia Ingress controller using my fix in the PR above. It works as far as i can see and test, i have created, updated and deleted the Ingress objects and i can see it being reflected in the OpenStack environment as expected.

I have pushed this to an image here: https://hub.docker.com/r/mikejoh/octavia-ingress-controller, use the `master` tag. If you don't want to use this image you can build the `octavia-ingress-controller` yourselves using my fork and push it to your own registry and pull it from there.

**Comment by lingxiankong** [comment]
@mikejoh Nice! Thanks for the fix, I will review asap today.

**Comment by mikejoh** [comment]
@lingxiankong Great!

**Comment by oomichi** [comment]
Sorry for missing this issue, and thanks for fixing it @mikejoh and @lingxiankong !
