### ISSUE TITLE
Using cinder as storage class with cloud-provider-openstack

### ISSUE THREAD

**Issue by alijahnas** [kubernetes/cloud-provider-openstack#758]
I am trying to migrate from the in-tree cloud provider to the external cloud provider. I did the steps described here: https://github.com/kubernetes/cloud-provider-openstack/blob/master/docs/using-controller-manager-with-kubeadm.md

The openstack-cloud-controller-manager DS seems to run without errors. I then try to provision a cinder volume with provisioner: kubernetes.io/cinder
And even if I specify: `--cloud-provider=external` and `--external-cloud-volume-plugin=openstack`, it is still kube-controller-manager that does the provisioning.
Should I use another provisioner type?
What about loadbalancer? How does the API calls redirected to the external cloud controller?

Thanks

**Environment**:
- openstack-cloud-controller-manager version: latest
- OS (e.g. from /etc/os-release): Ubuntu 16.04.6
- Kernel (e.g. `uname -a`): 4.4.0-146-generic
- Install tools: Kubespray and https://github.com/kubernetes/cloud-provider-openstack/blob/master/docs/using-controller-manager-with-kubeadm.md
- Kubernetes version: v1.14.3

**Comment by zetaab** [comment]
We have been using CSI starting from 1.13 without any problems. Nowadays we have 1.15.3 installed in all clusters.

**Comment by alijahnas** [comment]
> 
> 
> @alijahnas please see https://github.com/kubernetes/cloud-provider-openstack/blob/master/docs/openstack-kubernetes-integration-options.md
> with `--external-cloud-volume-plugin` you use intree cinder driver.
> @lingxiankong there is no relation between ccm (intree/out of tree) and CSI, CSI driver can be installed on any cluster weather it is running ccm or not

Thanks for the info, I removed the flag  `--external-cloud-volume-plugin`. I have openstack-cloud-controller-manager running as a DS, and I create a storageclass with `provider: openstack.org/standalone-cinder` and create PVC, but I get this on the description:

`waiting for a volume to be created, either by external provisioner "openstack.org/standalone-cinder" or manually created by system administrator`

No response from openstack-cloud-controller-manager. What did I misconfigure? Thanks!

**Comment by alijahnas** [comment]
> 
> 
> We have been using CSI starting from 1.13 without any problems. Nowadays we have 1.15.3 with CSI installed in all clusters.

I tried to use the CSI driver, but I got /var/lib/kubelete/pods that tried to be mounted on / which crashed the machine. I used latest image, should I use 1.15.3 as you do or latest is just fine? Thanks

**Comment by oz123** [comment]
@alijahnas I think what @adisky means is that you need to run the ccm and csi to provision volumes.

@adisky, can you please clarify this sentence:

> @alijahnas it is recommended to use CSI driver as external provisioner is not maintained from long time. As i Know @zetaab team uses it

I think you are missing a comma which make a big difference in the meaning here. I don't understand what needs to be done to provision volume with CCM.
Currently, I (mis)understand that there are 3 ways to provision volumes:
1. the in tree cloud contoroller in the k/k repository
2. the external cloud controller  in this repository
3. CSI driver in this repository.

Is this correct?

**Comment by alijahnas** [comment]
@oz123 I would like to know too if it is possible to provision volumes only with the external cloud controller, without the in tree k/k implementation.
@zetaab what version of CSI driver you recommend to use? Latest or 1.15.3 ? Thanks

**Comment by adisky** [comment]
> @alijahnas I think what @adisky means is that you need to run the ccm and csi to provision volumes.
> 
> @adisky, can you please clarify this sentence:
> 
> > @alijahnas it is recommended to use CSI driver as external provisioner is not maintained from long time. As i Know @zetaab team uses it
> 
> I think you are missing a comma which make a big difference in the meaning here. I don't understand what needs to be done to provision volume with CCM.
> Currently, I (mis)understand that there are 3 ways to provision volumes:
> 
> 1. the in tree cloud contoroller in the k/k repository
> 2. the external cloud controller  in this repository
> 3. CSI driver in this repository.
> 
> Is this correct?

1. intree cinder driver
2. external cloud controller manager has no volume control loops, you have three options with external provider
   i) standalone cinder driver
   ii) Flex volume driver
   iii) CSI
 first are not maintained from long time, and flex will also deprecate, CSI is the community direction so better to use it.

**Comment by alijahnas** [comment]
@adisky thanks for the reply. So I'll try to use the CSI plugin then. Which version should I use? Because the latest tag is not working and is crashing. I also tried to use the 1.15 unsuccessfully... I also see that between the version 1.13 and 1.15, the container size dropped from 112MB to 9MB. What happened?
Can you point me to a configuration that is stable?
Thank!

**Comment by oz123** [comment]
@adisky 
> first two are not maintained from long time, and flex will also deprecate, 

By first two do you mean:
1 .intree cinder driver (is this the one k\k)
2.  standalone cinder driver (which one is this?)

Can you please confirm?

**Comment by adisky** [comment]
@oz123 first two in the sublist
i) standalone cinder driver
ii) Flex volume driver 

apart from this intree driver API not going to deprecate they will be migrated to CSI
https://github.com/kubernetes/enhancements/blob/master/keps/sig-storage/20190129-csi-migration.md

**Comment by adisky** [comment]
@alijahnas CSI latest one is working fine, we running it in CI
reason for container size is dropped as previously we used ubuntu as base image then alpine

**Comment by ramineni** [comment]
@alijahnas we use debian currently as base image, and as @adisky mentioned latest should work fine.

**Comment by adisky** [comment]
@alijahnas please refer version compatibility before deploying 
https://github.com/kubernetes/cloud-provider-openstack/blob/master/docs/using-cinder-csi-plugin.md#compatibility

**Comment by alijahnas** [comment]
Thanks @ramineni 
@adisky so I am trying to deploy using latest image, but I have the same error as: https://github.com/kubernetes/cloud-provider-openstack/issues/312 
The OpenStack over which I am using CSI driver has Cinder v3, but the credentials I am using don't allow me to get the service endpoints: You are not authorized to perform the requested action: identity:list_endpoints
I imagine that with an admin account on OpenStack it shoudl work fine, but how do you work with only a user account? Thanks

**Comment by alijahnas** [comment]
> 
> 
> Thanks @ramineni
> @adisky so I am trying to deploy using latest image, but I have the same error as: #312
> The OpenStack over which I am using CSI driver has Cinder v3, but the credentials I am using don't allow me to get the service endpoints: You are not authorized to perform the requested action: identity:list_endpoints
> I imagine that with an admin account on OpenStack it shoudl work fine, but how do you work with only a user account? Thanks

Sorry, in fact the OpenStack I was testing on doesn't support Cinder v3... Anything on Cinder v2 integration?

**Comment by adisky** [comment]
@alijahnas contribute to support :)

**Comment by adisky** [comment]
or you can use the intree volume plugin with external ccm using `--external-cloud-volume-plugin`
https://github.com/kubernetes/cloud-provider-openstack/blob/master/docs/openstack-kubernetes-integration-options.md, i have not used it but you can give a try, and most probably the in tree driver will get removed in v1.17 or v1.18

**Comment by alijahnas** [comment]
@adisky I'll see what I can do

**Comment by alijahnas** [comment]
@adisky 
is the port 12345 deployed here https://github.com/kubernetes/cloud-provider-openstack/blob/master/manifests/cinder-csi-plugin/cinder-csi-controllerplugin.yaml#L16 is used for anything? Thanks

**Comment by alijahnas** [comment]
@adisky FYI, I made a PR to deploy Cinder CSI with kubespray: https://github.com/kubernetes-sigs/kubespray/pull/5184

**Comment by adisky** [comment]
@alijahnas thanks for your efforts, its nice :)

**Comment by alijahnas** [comment]
What about the port 12345, it doesn't seem to listen to anything in particular...

**Comment by albertdb** [comment]
So, once the in-tree driver is removed and as long as the OpenStack provider doesn't offer Cinder v3 (so CSI driver is not an option), we would run out of options, isn't it?

**Comment by adisky** [comment]
@albertdb CSI driver offers V3 support

**Comment by albertdb** [comment]
> @albertdb CSI driver offers V3 support

But my Openstack provider does not.
