### ISSUE TITLE
Octavia: Failed to batch updating members for pool

### ISSUE THREAD

**Issue by oomichi** [kubernetes/cloud-provider-openstack#759]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:

During creating an Ingress resource (https://github.com/kubernetes/cloud-provider-openstack/blob/master/docs/using-octavia-ingress-controller.md#create-an-ingress-resource), octavia-ingress-controller fails to batch updating members from pool.
The following is log of octavia-ingress-controller:
```
time="2019-09-12T00:07:59Z" level=info msg="ingress created, will create openstack resources" ingress=default/test-octavia-ingress
time="2019-09-12T00:08:04Z" level=info msg="loadbalancer created" ID=0ba04bae-96c8-4c23-8b4a-57d0287288d8 name=kube_ingress_k8s-20190910_default_test-octavia-ingress
time="2019-09-12T00:09:00Z" level=info msg="listener created" lb=0ba04bae-96c8-4c23-8b4a-57d0287288d8 listenerName=kube_ingress_k8s-20190910_default_test-octavia-ingress
time="2019-09-12T00:09:04Z" level=info msg="pool created" lb=0ba04bae-96c8-4c23-8b4a-57d0287288d8 listenerID= pooID=665f8b4d-1bb7-431d-ab55-d0762d892bb7 poolName=38df6e716b70f28ecfa4508c7e5c21dc18b1b8cc97c610ab4111c3237507fbfb
E0912 00:09:05.380749       1 controller.go:449] failed to create openstack resources for ingress default/test-octavia-ingress: error batch updating members for pool 665f8b4d-1bb7-431d-ab55-d0762d892bb7: Bad request with: [PUT http://iaas-ctrl:9876/v2.0/lbaas/pools/665f8b4d-1bb7-431d-ab55-d0762d892bb7/members], error message: {"debuginfo": null, "faultcode": "Client", "faultstring": "Unknown attribute for argument member_: members"}
```
Then the 'ADDRESS' doesn't appear on the Ingress resource:
```
$ kubectl get ing
NAME                   HOSTS            ADDRESS   PORTS   AGE
test-octavia-ingress   api.sample.com             80      24h
```

**What you expected to happen**:

The `ADDRESS` of the Ingress resource is available.

**How to reproduce it (as minimally and precisely as possible)**:

I am reproducing this issue as the way of https://github.com/kubernetes/cloud-provider-openstack/blob/master/docs/using-octavia-ingress-controller.md#create-an-ingress-resource

**Anything else we need to know?**:

The captured packets between octavia-ingress-controller and Octavia is
```
PUT /v2.0/lbaas/pools/13754680-37fc-44e4-84d2-3f997d1e9759/members
HTTP/1.1
Host: iaas-ctrl:9876
User-Agent: gophercloud/2.0.0
Connection: close
Content-Length: 63
Accept: application/json
Content-Type: application/json
X-Auth-Token: gAAAAABderTmEn8kSl5_yuTP4089vH4VOzrMWuk0NU9L4qXjHgIVoopLPQvdtqeC7byAj8LDBGxe3WkV3LfAiaGUGhLNmwlmGfnSYMInxX9yKUvbq94EKpMkx90eNYoHKA3S7h4phsmmN3LUSMu_CHfU72sN5MtsNonYe2cS0JUllpUSQVx9ITA
Accept-Encoding: gzip

{"members":[{"address":"192.168.1.104","protocol_port":31818}]}
...
Date: Thu, 12 Sep 2019 21:13:21 GMT
Server: WSGIServer/0.1 Python/2.7.12
Content-Length: 108
Content-Type: application/json
x-openstack-request-id: req-9dd5fc4a-2c08-4ce2-ab2a-c282f39f3f89

{"debuginfo": null, "faultcode": "Client", "faultstring": "Unknown attribute for argument member_: members"}
```
The specified request body is `{"members":[{"address":"192.168.1.104","protocol_port":31818}]}` and that seems valid according to the official Octavia API document(https://docs.openstack.org/api-ref/load-balancer/v2/?expanded=batch-update-members-detail#batch-update-members)
Now I cannot find the reason of this issue, and am still digging.

**Environment**:
- openstack-cloud-controller-manager version: v1.15.0
- OS (e.g. from /etc/os-release): 18.04.2 LTS (Bionic Beaver)
- Kernel (e.g. `uname -a`): 4.15.0-46-generic
- Install tools: kubeadm
- Others:

**Comment by lingxiankong** [comment]
@oomichi any update?

**Comment by oomichi** [comment]
@lingxiankong I am still deploying Stein version of OpenStack on my environment.
That takes time, I am going to report the result after that.
(Hopefully I'd like to do it in this week)

**Comment by lingxiankong** [comment]
> @lingxiankong I am still deploying Stein version of OpenStack on my environment.
> That takes time, I am going to report the result after that.
> (Hopefully I'd like to do it in this week)

Sounds good, thanks

**Comment by oomichi** [comment]
I am reporting current status of this issue.
Now I've deployed Stein version of OpenStack IaaS which contains Octavia also from Ubuntu 18.04 LTS packages.
But I am facing Octavia issue which is different amphora version between the Ubuntu package and community branches which are not only master but also stable/stein.
The Ubuntu package is for v0.5 of amphora and the amphora driver touches the endpoint like `https://192.168.0.80:9443/0.5/info`.
And we need to build amphora image by hands from Octavia repository.
Now master branch's amphora version is v1.0 and the endpoint becomes `https://192.168.0.80:9443/1.0/info` since https://review.opendev.org/#/q/Idaccbcfa0126f1e26fbb3ad770c65c9266cfad5b
As you see, the patch is backported to stable/stein also.
So even if checking out stable/stein branch, the version mismatch still happens.
I am trying to use stable/rockey for building amphora image, but the image doesn't seem to work with Stein amphora driver.
So the best way I can think at this time is it is better to wait for Ubuntu packages based on the latest branch/stein and make the versions the same.
Anyways that takes more time, I'd like to close this issue now.
And I will report back if releasing these packages from Ubuntu.

/close

**Comment by lingxiankong** [comment]
thanks for the update
