### ISSUE TITLE
LB not working with externalTrafficPolicy set to Local

### ISSUE THREAD

**Issue by JrCs** [kubernetes/cloud-provider-openstack#763]
/kind bug

**What happened**:
If we create a service of Type LoadBalancer and ### externalTrafficPolicy with value **Local** the LB that will be create will not work as expected.

**What you expected to happen**:
Only LB traffic to nodes that have the pod running.

**How to reproduce it (as minimally and precisely as possible)**:
Create a service of type **LoadBalancer** with **externalTrafficPolicy** set to **Local**.

**Anything else we need to know?**:
When using **externalTrafficPolicy** with value **Local**, the LB that will be create must have only members (nodes) where the pod of the service we want to access is running.
In case of **externalTrafficPolicy** set to **Cluster**, the LB that will be create must have all the worker nodes as members.

**Environment**:
- openstack-cloud-controller-manager version: v1.15.0
- OS (e.g. from /etc/os-release): Container Linux by CoreOS 2191.4.1
- Kernel (e.g. `uname -a`): 4.19.66-coreos

**Comment by lingxiankong** [comment]
The current OCCM implementation(based on OpenStack) doesn't support this feature, as per https://kubernetes.io/docs/concepts/services-networking/service/#aws-nlb-support and https://kubernetes.io/docs/tasks/access-application-cluster/create-external-load-balancer/#preserving-the-client-source-ip, seems this feature implementation is different from cloud to cloud.

If your purpose of using this param is to preserve the client source IP, you can use `loadbalancer.openstack.org/x-forwarded-for: "true"` in the annotation of LoadBalancer type Service.

**Comment by bgagnon** [comment]
The option serves two mostly unrelated concerns:
* preserve the client ip
* remove nodes that do not have an endpoint from the load balancer rotation

The second point, according to docs:

> [...] if you’re running on Google Kubernetes Engine/GCE, setting the same `service.spec.externalTrafficPolicy` field to Local forces nodes without Service endpoints to **remove themselves from the list of nodes eligible** for loadbalanced traffic by **deliberately failing health checks**.

This feature is valuable in very large cluster running an ingress controller. In this scenario, every few nodes have the ingress proxy (nginx, envoy, etc.), so there's no gain in including them in the cloud load balancer.

If we take health check hint from GCE above, I believe this can be implemented similarly in Openstack.

**Comment by jichenjc** [comment]
/reopen 

reopen for bug track
