### ISSUE TITLE
Volume expansion fails when cinder is backed by Ceph (and likely other backends)

### ISSUE THREAD

**Issue by jborg** [kubernetes/cloud-provider-openstack#777]
> /kind bug

**What happened**:
1. Edit size of currently attached pvc.
2. kubectl describe pvc shows "Waiting for user to (re-)start a pod to finish file system resize of volume on node."
3. Restart corresponding pod to start the resize process (kubectl delete pod X)
4. The csi-controller successfully completes the extendVolume api call
5. The csi-nodeplugin successfully invokes resizeFS (unknowing that the new volume size is not yet visible to the node, so nothing happens)
6. The pod starts again
7. The volume filesystem size is still unchanged!

End result: Volume size extended but filesystem size left unchanged.

**What you expected to happen**:
The filesystem size in step 7 should correspond to the new volume size.

The underlying problem is that only some Openstack installations fully support live volume expansion. Some backends such as Ceph (rbd) will successfully accept ExpandVolume API calls on currently attached volumes (if the correct mv is given) but the new volume size will not be visible to the host node until the next time the volume is detached/atached again.

https://opendev.org/openstack/os-brick/src/branch/master/os_brick/initiator/connectors/rbd.py#L253

**How to reproduce it (as minimally and precisely as possible)**:
Attempt to extend the size of an currently attached pvc on an Openstack installation that uses a cinder backend that does not fully support live/online volume expansion (like ceph).

**Anything else we need to know?**:
The only workaround I can think of right now is to make NodeExpandVolume fail if the current volume size is smaller that the requested size. This way we make sure the filesystem is actually resized once the correct volume size is reported. But this fix is not very pretty since the user will need to figure out a way to safely detach and reattach the volume before the corresponding pods can start again.

**Environment**:
- openstack-cloud-controller-manager version: master as of today
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

RedHat OSP13 with Ceph backed cinder.

**Comment by kayrus** [comment]
@jborg could you please check, whether your issue is related to https://github.com/kubernetes/kubernetes/issues/82281? If yes, then, once this is merged, the cinder CSI plugin has to be updated: https://github.com/kayrus/cloud-provider-openstack/commit/31a75db2442ac7fbb1a13ccb4605a92671f5da1d

**Comment by jborg** [comment]
> @jborg could you please check, whether your issue is related to [kubernetes/kubernetes#82281](https://github.com/kubernetes/kubernetes/issues/82281)? If yes, then, once it fixed, the cinder CSI plugin has to be updated: [kayrus@31a75db](https://github.com/kayrus/cloud-provider-openstack/commit/31a75db2442ac7fbb1a13ccb4605a92671f5da1d)

I'm afraid not. Neither "/sys/block/sdb/device/rescan" or the "/sys/class/scsi_host/*/scan" thing seems to help. The only way I've found to make the new size visible when using Ceph is to actually detach and attache the volume.

As an experimental workaround I've added some code before https://github.com/kubernetes/cloud-provider-openstack/blob/master/pkg/csi/cinder/nodeserver.go#L343 that returns an error if the visible volume size is smaller than the one mentioned in NodeExpandVolumeRequest.
This way the actual resizefs call will wait until the volume has actually expanded.

This seems to work but unfortunately it's seems to be more difficult to get the volume detached than I expected. Simply deleting a statefulset pod is not enough. The volume seems to stay attached until a new pod has been screduled on the same node. I usually need to scale the statefulset to 0 before the volume is detached.

It would be better if kubernetes somehow explicitly detached/re-attached expanded volumes.

**Comment by kayrus** [comment]
@jborg do you have the `ExpandInUsePersistentVolumes` feature gate enabled in kube controller manager? What if you disable it?

**Comment by jborg** [comment]
> @jborg do you have the `ExpandInUsePersistentVolumes` feature gate enabled in kube controller manager? What if you disable it?

I've tested both but it didn't make much of a difference. If set to false the only difference is that I need to delete any running pod to get the process started. But in both cases the end result is the same.

If I understand this option correctly it only determines if k8s should wait until no running pod is associated with the volume before starting the expansion. My issue is not with running pods it is that volume expansions are not immediately visible,  only the next time the volume is attached. The lack of running pods is no guarantee that the volume is currently detached.

I'm not sure exactly what problem the current feature gates attempts to solve, but `ExpandAttachedVolumes=false` would have been a much more useful feature gate for me.
