### ISSUE TITLE
OpenStack API shows incorrect path for volume

### ISSUE THREAD

**Issue by zetaab** [kubernetes/cloud-provider-openstack#779]
**Is this a BUG REPORT or FEATURE REQUEST?**: BUG

> Uncomment only one, leave it on its own line: 
>
/kind bug

**What happened**: I am using CSI cinder driver. However, it seems that this do have same bug that most of the openstack tools. 

```
testvolume: MountVolume.MountDevice failed for volume "pvc-6140f0a9-cc04-4cad-8a3e-57debb68b713" : rpc error: code = Internal desc = Failed to ScanForAttach: Could not find attached Cinder disk /dev/vdd. Timeout waiting for mount paths to be created. 
```

![Screenshot 2019-09-25 at 9 32 00](https://user-images.githubusercontent.com/22482503/65575097-ac84d700-df77-11e9-94eb-5ff82d911de3.png)

So the problem is that openstack API says that the device location is `/dev/vdd`. However, that is not true. 

When I check volumes from instance:

```
ls /dev/vd*
/dev/vda  /dev/vda1  /dev/vdb  /dev/vdb1  /dev/vde  /dev/vdf  /dev/vdg
```

Volume ID for `pvc-6140f0a9-cc04-4cad-8a3e-57debb68b713` is `5c103aa8-fe0e-4682-97c1-9bc79cfbaadb`

```
ls /dev/disk/by-id/virtio-*
/dev/disk/by-id/virtio-5869c604-05c6-4333-8  /dev/disk/by-id/virtio-5c103aa8-fe0e-4682-9  /dev/disk/by-id/virtio-7e3ecd5b-f2a2-431d-a
```
As we can see the volume is attached to instance but openstack API device path does not match.

**What you expected to happen**: I expect that cinder CSI plugin should use `/dev/disk/by-id` paths when checking things from device. 

Related:
https://github.com/kopeio/etcd-manager/pull/253
https://github.com/kubernetes/kubernetes/issues/33128
https://github.com/kubernetes/kubernetes/pull/33270

**Comment by ramineni** [comment]
@zetaab Are you using latest image of cinder-csi plugin?

**Comment by zetaab** [comment]
Yep actually I noticed that v1.15 should fix this. Thanks, I am verifying
