### ISSUE TITLE
standalone-cinder-provisioner deployment create pod status CrashLoopBackOff not running

### ISSUE THREAD

**Issue by jianglingxia** [kubernetes/cloud-provider-openstack#78]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug
> Uncomment only one, leave it on its own line: 
 /kind bug

**What happened**:
I deploy a cluster in bare-metal enviroment,then create the deployment named standalone-cinder-provisioner,but created pod not running and status CrashLoopBackOff! is the image problem?
the image is me use :docker pull quay.io/external_storage/standalone-cinder-provisioner:latest
the deployment yaml:

apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: standalone-cinder-provisioner
  labels:
    app: standalone-cinder-provisioner
spec:
  replicas: 1
  selector:
    matchLabels:
      app: standalone-cinder-provisioner
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: standalone-cinder-provisioner
    spec:
      containers:
      - name: standalone-cinder-provisioner
        image: "quay.io/external_storage/standalone-cinder-provisioner:latest"
        imagePullPolicy: IfNotPresent
        env:
        - name: OS_CINDER_ENDPOINT
          value: http://10.1.101.1:8776/v2
        - name: OS_USERNAME
          value: k8s
        - name: OS_TENANT_NAME
          value: kubernetes

[root@localhost:/home/ubuntu/yaml-baremetal]$ kubectl get po
NAME                                             READY     STATUS             RESTARTS   AGE
standalone-cinder-provisioner-6797c5db6b-rtjqc   0/1       CrashLoopBackOff   19         1h

the kubelet log:

I0403 02:33:00.122888   20622 kuberuntime_manager.go:739] checking backoff for container "standalone-cinder-provisioner" in pod "standalone-cinder-provisioner-6797c5db6b-rtjqc_default(87835eee-3699-11e8-bfec-4c09b4b0c25b)"
I0403 02:33:00.122967   20622 kuberuntime_manager.go:749] Back-off 5m0s restarting failed container=standalone-cinder-provisioner pod=standalone-cinder-provisioner-6797c5db6b-rtjqc_default(87835eee-3699-11e8-bfec-4c09b4b0c25b)
E0403 02:33:00.122995   20622 pod_workers.go:182] Error syncing pod 87835eee-3699-11e8-bfec-4c09b4b0c25b ("standalone-cinder-provisioner-6797c5db6b-rtjqc_default(87835eee-3699-11e8-bfec-4c09b4b0c25b)"), skipping: failed to "StartContainer" for "standalone-cinder-provisioner" with CrashLoopBackOff: "Back-off 5m0s restarting failed container=standalone-cinder-provisioner pod=standalone-cinder-provisioner-6797c5db6b-rtjqc_default(87835eee-3699-11e8-bfec-4c09b4b0c25b)"

**What you expected to happen**:
the deployment created pod can running
**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:k8sv1.8.5
- openstack-cloud-controller-manager version:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by jianglingxia** [comment]
/assign @dims 
thanks

**Comment by dims** [comment]
@jianglingxia need more logs, you can use docker logs to get the actual container logs

**Comment by jianglingxia** [comment]
the docker log hint need the auth-url and cloud config ，but I think the sceneo no need the auth url

**Comment by dims** [comment]
@jianglingxia can you please paste the full logs from the container?

**Comment by dims** [comment]
i think we have covered all the issues here as PR(s). please reopen if you are still having a problem.

- https://github.com/kubernetes/cloud-provider-openstack/pull/85
- https://github.com/kubernetes/cloud-provider-openstack/pull/84

thanks,
Dims
