### ISSUE TITLE
Openstack Cloud Controller Manager cannot properly delete Internal Octavia LBaaS it previously deployed

### ISSUE THREAD

**Issue by dannyg28** [kubernetes/cloud-provider-openstack#794]
/kind bug

**What you expected to happen**:
Service is deployed with an internal-loadbalancer and traffic should be routed to service from Load balancer vip. Deleting service should delete load balancer.

**What happened**:
Load balancer is successfully deployed and traffic is routed successfully. However neither the service nor the load balancer are deleted. Following error is thrown out in the Openstack CLoud Controller Manager logs
 ``` I1007 17:36:45.849581       1 event.go:255] Event(v1.ObjectReference{Kind:"Service", Namespace:"kube-system", Name:"internal-http-nginx-service", UID:"d5c7527d-e928-11e9-90ce-fa163e81f8c4", APIVersion:"v1", ResourceVersion:"3040", FieldPath:""}): type: 'Warning' reason: 'SyncLoadBalancerFailed' Error syncing load balancer: failed to check if load balancer exists before cleanup: error getting floating ip for port b23d6ae7-a626-49d1-b309-2fbaea209804: failed to find object```

It seems to be trying to find a floating IP even tough the loadbalancer is an internal one that wouldn't have a floating ip

running `openstack loadbalancer delete --cascade`` successfully deletes the loadbalancer which then allows k8s to delete the service successfully.

**How to reproduce it (as minimally and precisely as possible)**:

Install a internal http loadbalancer like can be found here  https://github.com/kubernetes/cloud-provider-openstack/tree/master/examples/loadbalancers#internal-http-loadbalancer  

Deploy onto a tenant with no external network configured

**Anything else we need to know?**:
Load balancer cloud config is as follows
```
[LoadBalancer]
use-octavia=true
internal-lb=true
subnet-id="e26cb53a-7d23-4315-b81b-4b9e6fb1161e"
floating-network-id="3eafcf36-8c9a-4f9e-affa-48387faec0ad"
floating-subnet-id="5d0c7b4d-b857-45bb-b883-6334116302f5"
create-monitor=true
monitor-delay=5s
monitor-timeout=5s
monitor-max-retries=3
```

**Environment**:
- openstack-cloud-controller-manager version: latest
- Others: kubectl

**Comment by dannyg28** [comment]
After investigating more I've noticed that the Loadbalancer is deployed onto a network `5d6bb1c9-0cf9-42e5-a0db-4b035aefc7a1` whose id and network range is not  considered valid by the tenant. 

``` 
openstack loadbalancer list    [19/10/7| 4:16PM]
+--------------------------------------+-----------------------------------------------------------------+----------------------------------+--------------+---------------------+----------+
| id                                   | name                                                            | project_id                       | vip_address  | provisioning_status | provider |
+--------------------------------------+-----------------------------------------------------------------+----------------------------------+--------------+---------------------+----------+
| 0bbfab5e-23fb-411b-9d26-883029456b82 | kube_service_kubernetes_kube-system_internal-http-nginx-service | 028c6f9ee2f64797be8db259a881d23a | 10.150.92.19 | PENDING_CREATE      | octavia  |
```

```
openstack network list         [19/10/7| 4:17PM]
+--------------------------------------+---------------------------+--------------------------------------+
| ID                                   | Name                      | Subnets                              |
+--------------------------------------+---------------------------+--------------------------------------+
| 3eafcf36-8c9a-4f9e-affa-48387faec0ad | ext_net_10_150_32         | 5d0c7b4d-b857-45bb-b883-6334116302f5 |
| 95a5aad4-99e5-4150-bf89-50cc54726376 | rc-dns-net-10_150_96      | a25e9b1e-09d3-4e1b-9074-a5ef6608aaf2 |
| 95eddf5d-c340-48f0-ba5f-087ccf2c9431 | tenant-mgmt-dev-10_150_35 | 751f7a49-fb1e-465b-80f1-a792461b33c9 |
| a97866fa-67e6-45b9-ab2d-7d03969199cc | osadmin_10_150_33         | 9e4b09c1-2e87-4b8d-a3f8-991a402d547d |
```

I attempted to specify the correct network name in the cloud-config file  like so 
```
[Networking]
internal-network-name="tenant-mgmt-dev-10_150_35"
```
however that doesn't seemed to have helped at all

**Comment by lingxiankong** [comment]
@dannyg28 The LB VIP port IP address is allocated from the subnet ID configured which is `e26cb53a-7d23-4315-b81b-4b9e6fb1161e`, but I didn't see this subnet from your output.

**Comment by lingxiankong** [comment]
/assign 

I can confirm this bug.

**Comment by lingxiankong** [comment]
Hi @dannyg28, could you please test again using the image `lingxiankong/openstack-cloud-controller-manager:fix-internal-service`?

**Comment by dannyg28** [comment]
Hey @lingxiankong , just tested it and it looks to be working as expected! Thanks for taking a look at this so quickly

**Comment by lingxiankong** [comment]
@dannyg28 thanks for the feedback.
