### ISSUE TITLE
instanceIDFromProviderID should return instance if the input parameter providerId is InstanceID

### ISSUE THREAD

**Issue by MIBc** [kubernetes/cloud-provider-openstack#799]
/kind bug

**What happened**:
As the title describes, the situation may happen.
According to node-controller code: https://github.com/kubernetes/kubernetes/blob/dd5cb6426def7e0231aab61b7ef489d39c75b35c/pkg/controller/cloud/node_controller.go#L349

If the node.Spec.ProviderID is null when you forget setting "--cloud-provider=external" for kubelet. The  node-controller will use instance-id to check if instance is existed by `InstanceExistsByProviderID` function.  It will fail in  instanceIDFromProviderID , because it only allow the pattern "openstack:///instance-id".

**What you expected to happen**:
instanceIDFromProviderID can return instance-id, if providerid is `provider-name+instance-id` or "instance-id"

**How to reproduce it (as minimally and precisely as possible)**:
start a k8s cluster without set --cloud-provider=external

**Environment**:
- openstack-cloud-controller-manager version: master
- OS (e.g. from /etc/os-release): centos 7
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by MIBc** [comment]
Image that: k8s cluster is installed by user. User wants to use Lb service  after the k8s used for a while. He has to install cloud-provider, but it can not work fine because no instance-id could be found.

Actually, if instanceIDFromProviderID could return the right id, it would work.

**Comment by lingxiankong** [comment]
according to https://kubernetes.io/docs/tasks/administer-cluster/running-cloud-controller/#running-cloud-controller-manager, in order to use cloud controller manager, kubelet must run with `--cloud-provider=external`
