### ISSUE TITLE
Get creating vm as TargetNode, that cause TestRoutes case failed

### ISSUE THREAD

**Issue by kiwik** [kubernetes/cloud-provider-openstack#80]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug

**What happened**:
In unit test case TestRoutes, if the first vm in vm list is creating status, the vm do not allocate IP address yet, that will cause ErrNoAddressFound in following logic.

https://github.com/kubernetes/cloud-provider-openstack/blob/master/pkg/cloudprovider/providers/openstack/openstack_routes_test.go#L50

**What you expected to happen**:
Use running vm as TargetNode, for example: the vm that unit test is running in.

**How to reproduce it (as minimally and precisely as possible)**:
It happen in OpenLab integration tests, it is test result and log.
http://logs.openlabtesting.org/logs/77/77/f26a6e3b931cabf01e68eea02c93b64fd3d11908/cloud-provider-openstack-all/cloud-provider-openstack-unittest/3f9e57e/

**Anything else we need to know?**:
NA

**Environment**:
- openstack-cloud-controller-manager version: master

**Comment by dims** [comment]
/close

fixed!
