### ISSUE TITLE
Why is the Cinder CSI Controller Plugin a Statefulset?

### ISSUE THREAD

**Issue by afritzler** [kubernetes/cloud-provider-openstack#800]
/kind question

Why is the CSI controller plugin for cinder deployed as a statefulset and not as deployment [0]? Is there a reason for that?

Regards,
Andreas

[0] https://github.com/kubernetes/cloud-provider-openstack/blob/master/manifests/cinder-csi-plugin/cinder-csi-controllerplugin.yaml

**Comment by adisky** [comment]
@afritzler  you can use deployment also https://github.com/kubernetes/community/blob/master/contributors/design-proposals/storage/container-storage-interface.md#cluster-level-deployment

**Comment by afritzler** [comment]
Thanks @adisky!
