### ISSUE TITLE
Incompatible provisioner name when upgrading from release 1.15 to 1.16

### ISSUE THREAD

**Issue by GeorgFleig** [kubernetes/cloud-provider-openstack#802]
/kind bug

**What happened**:
I am running a kubernetes 1.15 cluster with the external openstack cloud provider and the CSI cinder plugin for storage provisioning.

I now want to upgrade to kubernetes 1.16 and thus also upgrade the CSI cinder plugin from the 1.15 branch to 1.16. I noticed the provisioner name changed from `csi-cinderplugin` to `cinder.csi.openstack.org` in https://github.com/kubernetes/cloud-provider-openstack/pull/624/files

An existing storage class cannot be updated so I deleted and recreated the storage class with the new provisioner name. However existing PVCs still contain the old provisioner and are not handled by the new one. This is a breaking change and I could not find any documentation on how to migrate my existing volumes.

**What you expected to happen**:

Either automatic handling of the old PVCs that used the old handler or documentation on how to migrate to the latest release.

**How to reproduce it (as minimally and precisely as possible)**:

Deploy plugin version release-1.15, create PVCs, upgrade to release-1.16. PVCs are not handled by the new version of the plugin. It does not matter whether you keep the existing storage class with the old provisioner or recreate the stroage class with the new provisioner name.

**Comment by adisky** [comment]
@GeorgFleig driver name is same cpo release v1.13, it was changed in v1.12, please check you should not get any error while upgrading from v1.15 to v1.16

**Comment by ramineni** [comment]
@adisky @GeorgFleig Its indeed changed , with external-provisoner removing --provisoner flag , https://github.com/kubernetes-csi/external-provisioner/blob/v1.1.1/CHANGELOG-1.1.md , so by default identifies provisoner uses the driver name

**Comment by GeorgFleig** [comment]
Thanks for your quick replies!

@ramineni so you're saying the `provisioner` name in annotations that changed recently from 1.15 to 1.16 does not matter for existing PVCs and PVs? Meaning for existing PVs only the `driver` name is relevant and that already changed to `cinder.csi.openstack.org` in 1.12. So my PVs shoud be handled correctly after the update to 1.16 even though the annotations still state `volume.beta.kubernetes.io/storage-provisioner: csi-cinderplugin`?

For a new PVC the provisioner name does matter and is updated by deleting the storage class and creating it with the correct name?

I will try to verify this again in my setup. I tried this yesterday and failed, therefore I opened the bug ticket.

**Comment by mape90** [comment]
The annotations is relevant for at least provisioner. Otherwise old volumes are not deleted. I didn't check if attacher worked or not.

But basically you need to recreate the StorageClass and then patch all PV:s that where managed by the old provisioner.
