### ISSUE TITLE
Keystone auth v2 do not work

### ISSUE THREAD

**Issue by mape90** [kubernetes/cloud-provider-openstack#803]
**What happened**:
In release 1.16 V2 keystone authentication stops working. 

**What you expected to happen**:
Support for V2 should not be removed as still there are openstacks that use v2 for their authentication. 

**How to reproduce it (as minimally and precisely as possible)**:
Define V2 authentication for auth_url.

**Anything else we need to know?**:
This was broken by commit https://github.com/kubernetes/cloud-provider-openstack/pull/733

Could be fixed by editing line 544 in pkg/cloudprovider/providers/openstack/openstack.go
from
`err = openstack.AuthenticateV3(provider, authOptsExt, gophercloud.EndpointOpts{})`
to
`err = openstack.Authenticate(provider, authOptsExt)`

/kind bug

**Comment by kayrus** [comment]
relates to https://github.com/kubernetes/cloud-provider-openstack/issues/569
