### ISSUE TITLE
[Cinder CSI] ExpandVolume will eventyally change Microversion to 3.42

### ISSUE THREAD

**Issue by mape90** [kubernetes/cloud-provider-openstack#804]
**What happened**:
As all CSI calls can be called simultaneously by multiple threads you should never modify global objects like os.blockstorage. As eventually some thread will fetch the temporary change as initial and then save it later. So then the "temporary" change will become permanent. 

If special client is needed it should be created for that call so that parallel calls would not mess up each others.

**Anything else we need to know?**:
It was implement in https://github.com/kubernetes/cloud-provider-openstack/pull/620
and "fixed" in https://github.com/kubernetes/cloud-provider-openstack/pull/786

/kind bug

**Comment by ramineni** [comment]
@mape90 I'm confused , as per issue description , it already says fixed in #786 , so what else is expected ?

**Comment by mape90** [comment]
@ramineni it is "fixed" because the fix do not actually fix anything. It fixes the problem when you only execute one resize action at time. However in real environments you will eventually have multiple simultaneous resize actions and each thread will modify the same object and that cause race condition where the temporary value is stored as initial. That fix just isn't thread safe.

Also as it changes global object it will have affect to all other actions that are done during that resize action. It could be fixed by just adding lock so that only one thread can access it by any time. However this defeats the purpose of having multiple threads.

So if that micro version change is needed it is safer to do it in own client object. It will have small performance hit as you need to reauthenticate  against the API but it would not them mess up any other actions that would be simultaneously be made.

**Comment by ramineni** [comment]
@mape90 Thanks for detail info. Got it.

**Comment by kayrus** [comment]
@mape90 thanks for the bug report, I totally missed this case.

from my point of view there can be at least four kinds of fix:
* set permanent minimal microversion during the initialization
* create a deep copy of the client during the resize action
* create a client from the global authed provider client for each resize action (`NewBlockStorageV3`)
* modify gophercloud to support calls with a microversion as a parameter

each of the solution have pros and cons. @ramineni , @mape90 do you have other suggestions?

**Comment by mape90** [comment]
@kayrus how the version is set initially for the client? Is just gophercloud hardcoded thing or is it determined during authentication? 
Also is is common that you can resize with this microversion, but then other calls will fail using this microversion? 

If it just everything works or nothing works then global override flag is best option as then behavior is deterministic. Then we could just check the microversion and report that resize isn't supported.

If openstack allows certain operations with this microversion and fails with others then separate global object is good option.

**Comment by kayrus** [comment]
@mape90 initially microversion is not set, because most of the standard operations don't require it. However it must be set for live resize operations. Also you have to remember that some later microversions can remove functionality, which was supported in earlier microversions.

Supported microversions can be checked during the client initialization, but unfortunately this feature is supported only for limited resource types in gophercloud.
