### ISSUE TITLE
Keystone auth: functional tests seem to be wrong

### ISSUE THREAD

**Issue by kayrus** [kubernetes/cloud-provider-openstack#809]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:

keystone auth tests seem don't work properly and it looks like they still use in-tree openstack auth plugin:

```
++ /home/zuul/src/k8s.io/kubernetes/cluster/kubectl.sh get pv
++ sed 1d
++ awk '{print $1}'
W1022 08:24:27.140561   17847 openstack.go:143] WARNING: in-tree openstack auth plugin is now deprecated. please use the "client-keystone-auth" kubectl/client-go credential plugin instead
W1022 08:24:27.142693   17847 openstack.go:143] WARNING: in-tree openstack auth plugin is now deprecated. please use the "client-keystone-auth" kubectl/client-go credential plugin instead
W1022 08:24:27.147036   17847 openstack.go:143] WARNING: in-tree openstack auth plugin is now deprecated. please use the "client-keystone-auth" kubectl/client-go credential plugin instead
error: You must be logged in to the server (Unauthorized)
+ pv_name=
+ [[ -n '' ]]
ok: Runtime: 0:00:05.248567
```

**What you expected to happen**:

keystone auth tests should use "client-keystone-auth" and catch errors.

**How to reproduce it (as minimally and precisely as possible)**:

See logs: https://logs.openlabtesting.org/logs/62/762/2690d59063b059b209335be24c260e1f550e5fdb/cloud-provider-openstack-acceptance-test-keystone-authentication-authorization/cloud-provider-openstack-acceptance-test-keystone-authentication-authorization/7d63261/

**Environment**:
- openstack-cloud-controller-manager version:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by lingxiankong** [comment]
k8s-keystone-auth function test has already been changed.
