### ISSUE TITLE
cannot get resource "csinodeinfos" in API group "csi.storage.k8s.io" at the cluster scope

### ISSUE THREAD

**Issue by zetaab** [kubernetes/cloud-provider-openstack#813]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug

**What happened**:

I am seeing stuff like 
```
I1025 08:04:47.498858       1 csi_handler.go:524] Can't get CSINodeInfo nodes-2-ea-ct-k8s-local: csinodeinfos.csi.storage.k8s.io "nodes-2-ea-ct-k8s-local" is forbidden: User "system:serviceaccount:volume:csi-cinder-controller-sa" cannot get resource "csinodeinfos" in API group "csi.storage.k8s.io" at the cluster scope
```

**What you expected to happen**:

I expect 1) add correct rbac rules 2) if this is not needed it should not call it

So are we missing some RBAC rules from example manifests?

**How to reproduce it (as minimally and precisely as possible)**:

install csi stuff to 1.15 and check logs after few days

**Anything else we need to know?**:

**Environment**:
- openstack-cloud-controller-manager version: 1.15
- OS (e.g. from /etc/os-release): debian buster
- Kernel (e.g. `uname -a`):
- Install tools: kops
- Others:

**Comment by ramineni** [comment]
@zetaab What is the version of external-attacher ? updating it to v1.1.0 or v1.1.1 should fix the issue.
Later version , 1.16 should have this issue fixed.

**Comment by oz123** [comment]
@zetaab you mentioned in slack you got this working already. Can you post here what have you done to get this working?

**Comment by zetaab** [comment]
@oz123 I did not get this working. It was another issue (calico between servers)

**Comment by zetaab** [comment]
@ramineni I do not have pod external-attacher? 

```
% kubectl get pod csi-cinder-controllerplugin-0 -o yaml|grep image
    image: quay.io/k8scsi/csi-attacher:v1.0.1
    imagePullPolicy: IfNotPresent
    image: quay.io/k8scsi/csi-provisioner:v1.0.1
    imagePullPolicy: IfNotPresent
    image: quay.io/k8scsi/csi-snapshotter:v1.0.1
    imagePullPolicy: Always
    image: docker.io/k8scloudprovider/cinder-csi-plugin:v1.15.0
    imagePullPolicy: IfNotPresent
    image: k8scloudprovider/cinder-csi-plugin:v1.15.0
    imageID: docker-pullable://k8scloudprovider/cinder-csi-plugin@sha256:56e53e73a3495fb7efe6680ee23f2e6ebde7c365b0f85c3c765b149316d70edd
    image: quay.io/k8scsi/csi-attacher:v1.0.1
    imageID: docker-pullable://quay.io/k8scsi/csi-attacher@sha256:6425af42299ba211de685a94953a5c4c6fcbfd2494e445437dd9ebd70b28bf8a
    image: quay.io/k8scsi/csi-provisioner:v1.0.1
    imageID: docker-pullable://quay.io/k8scsi/csi-provisioner@sha256:7d7d832832b536f32e899669a32d4fb75ab972da20c21a2bd6043eb498cf58e8
    image: quay.io/k8scsi/csi-snapshotter:v1.0.1
    imageID: docker-pullable://quay.io/k8scsi/csi-snapshotter@sha256:2668993c32cad68a5ce6f05ec26f6e6cdb9ae8460ec52ed0425aeaed0b588e23
```

**Comment by ramineni** [comment]
@zetaab image: quay.io/k8scsi/csi-attacher:v1.0.1 , this container is external-attacher sidecar.
https://github.com/kubernetes/cloud-provider-openstack/blob/release-1.15/manifests/cinder-csi-plugin/cinder-csi-controllerplugin.yaml#L38 , can u change the version to v1.1.0 and check ?

**Comment by ramineni** [comment]
@zetaab were you able to test this?

**Comment by oz123** [comment]
@zetaab closing the issue means that this works for you now?
