### ISSUE TITLE
Cannot expand volumes with Cinder version < 3.42

### ISSUE THREAD

**Issue by thcdrt** [kubernetes/cloud-provider-openstack#819]
**Is this a BUG REPORT or FEATURE REQUEST?**:
> /kind bug

**What happened**:
I can't resize a volume. I get the error: 
`{"computeFault":` {"message": "Version 3.42 is not supported by the API. Minimum is 3.0 and maximum is 3.15.", "code": `406}}`

**What you expected to happen**:
To resize the volume

**How to reproduce it (as minimally and precisely as possible)**:
Create a pvc of 2GB of spac, then resize it to 6GB.

**Anything else we need to know?**:
It worked on the same environment with the intree volume provider.
After some investigations I found out that the cinder version 3.42 is hardcoded in the code, to allow to resize volumes in usage.
I would like to have the same behavior that the intree system, which allow me to resize it, even if I have to stop the pod associated to release the volume to let it be resized.
Code is here: https://github.com/kubernetes/cloud-provider-openstack/blob/master/pkg/csi/cinder/openstack/openstack_volumes.go#L262

Is it possible to stop to force the 3.42 version ?

**Environment**:
- Openstack cinder version: 3.15

Thanks,
Thomas

**Comment by ramineni** [comment]
@thcdrt are you using offline volume resize? Online volume resize needs 3.42 .
I suppose we could stop restricting the behavior for offline resize.

**Comment by kayrus** [comment]
should be fixed in #808

**Comment by thcdrt** [comment]
@ramineni yes we use offline volume resize.
It would be great indeed !

**Comment by thcdrt** [comment]
@kayrus you PR LGTM, thank you very much. Do you know when it should be released approximately ?

**Comment by thcdrt** [comment]
I just saw that you merged your PR @kayrus. I tested the new cinder-csi-plugin and it's working like a charm now ! Thank you very much.
