### ISSUE TITLE
Remove loading config from Env variables

### ISSUE THREAD

**Issue by ramineni** [kubernetes/cloud-provider-openstack#823]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
> /kind bug
> /kind feature

**What happened**:
Even though by default we load config options through secret in csi , there is fallback option to load from env if any errors. https://github.com/kubernetes/cloud-provider-openstack/blob/master/pkg/csi/cinder/openstack/openstack.go#L118 ,

With this issue, https://github.com/kubernetes/kubernetes/issues/81117#issuecomment-551403749 , its not recommended to load passwords from env , so plan is to remove the option to load from env . This shouldn't break anyone, as its not explicit option supported . Thoughts?
**What you expected to happen**:
Use the by default supported option , using secret
**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- openstack-cloud-controller-manager version:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by ramineni** [comment]
cc @lingxiankong @zetaab @kayrus

**Comment by adisky** [comment]
cc @chrigl

**Comment by chrigl** [comment]
+1 for removing "load from env", and adding this prominently in the changelog... just in case.
