### ISSUE TITLE
Cinder CSI plugin can't authenticate with Openstack Identity API v2

### ISSUE THREAD

**Issue by celiawa** [kubernetes/cloud-provider-openstack#828]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
> /kind bug
> /kind feature

**What happened**:
Hi experts:

I'm using cinder csi 1.16.0,  below is the cloud.conf, and the log when starting the cinder-csi-plugin container. It failed to authenticate with the Identity v2 API. It reports error "Failed to GetOpenStackProvider: You must provide exactly one of DomainID or DomainName to authenticate by Username"  whether domain-name is set or not in the cloud.conf . 

This document says the csi support Identify v2 API.
https://github.com/kubernetes/cloud-provider-openstack/blob/master/docs/provider-configuration.md

[Global]
auth-url = https://10.10.10.10:13000/v2.0
username = "v2098_****"
password = "ChangeMe.*******"
tenant-id = dcad1779558047f9bfb2c47925b914ec
region = regionOne
domain-name = Default
ca-file = /etc/kubernetes/openstack-ca.crt

[BlockStorage]
bs-version = auto
ignore-volume-az = true

I1112 12:44:00.141996       1 openstack.go:110] InitOpenStackProvider configFile: /etc/config/cloud.conf
I1112 12:44:00.142881       1 openstack.go:227] AuthURL: https://10.10.10.10:13000/v2.0
I1112 12:44:00.142894       1 openstack.go:228] UserID: 
I1112 12:44:00.142898       1 openstack.go:229] Username: v2098_****
I1112 12:44:00.142901       1 openstack.go:230] TenantID: dcad1779558047f9bfb2c47925b914ec
I1112 12:44:00.142910       1 openstack.go:231] TenantName: 
I1112 12:44:00.142914       1 openstack.go:232] TrustID: 
I1112 12:44:00.142917       1 openstack.go:233] DomainID: 
I1112 12:44:00.142920       1 openstack.go:234] DomainName: Default
I1112 12:44:00.142923       1 openstack.go:235] TenantDomainID: 
I1112 12:44:00.142926       1 openstack.go:236] TenantDomainName: 
I1112 12:44:00.142929       1 openstack.go:237] UserDomainID: 
I1112 12:44:00.142932       1 openstack.go:238] UserDomainName: 
I1112 12:44:00.142935       1 openstack.go:239] Region: regionOne
I1112 12:44:00.142938       1 openstack.go:240] CAFile: /etc/kubernetes/openstack-ca.crt
I1112 12:44:00.142941       1 openstack.go:241] UseClouds: false
I1112 12:44:00.142973       1 openstack.go:242] CloudsFile: 
I1112 12:44:00.142979       1 openstack.go:243] Cloud: 
I1112 12:44:00.142984       1 openstack.go:244] ApplicationCredentialID: 
I1112 12:44:00.142989       1 openstack.go:245] ApplicationCredentialName: 
I1112 12:44:00.143003       1 openstack.go:80] Block storage opts: {0}
I1112 12:44:00.143096       1 openstack.go:508] Using user-agent cinder-csi-plugin/ gophercloud/2.0.0
W1112 12:44:00.144254       1 main.go:120] Failed to GetOpenStackProvider: You must provide exactly one of DomainID or DomainName to authenticate by Username

**What you expected to happen**:
Authenticate success with Identity API v2.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- openstack-cloud-controller-manager version: v1.16.0
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
Linux daniel-storage-02 3.10.0-957.10.1.el7.x86_64 #1 SMP Thu Feb 7 07:12:53 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
- Install tools:
- Others:

**Comment by kayrus** [comment]
should be fixed in #807

**Comment by kayrus** [comment]
@celiawa can you test whether master branch works for you?

**Comment by celiawa** [comment]
@kayrus  Thanks a lot for your response. I test with the master branch. It works. Can authenticate Identity API v2.
