### ISSUE TITLE
Can't create LB: Unknown attribute for argument listener_.listener: allowed_cidrs

### ISSUE THREAD

**Issue by JrCs** [kubernetes/cloud-provider-openstack#829]
> /kind bug

**What happened**:
Can't create new LB with the latest version of openstack-cloud-controller-manager

**What you expected to happen**:
Creation of a LB

**Anything else we need to know?**:
When openstack-cloud-controller-manager try to create a LB i have this error:
```
I1112 16:05:37.015121       1 event.go:255] Event(v1.ObjectReference{Kind:"Service", Namespace:"nginx-ingress", Name:"nginx-ingress-controller", UID:"ebde73a8-42a2-43a0-9411-9b44831c2e43", APIVersion:"v1", ResourceVersion:"1136997", FieldPath:""}): type: 'Warning' reason: 'SyncLoadBalancerFailed' Error syncing load balancer: failed to ensure load balancer: failed to update listener c0e0fbdb-bd5e-4e11-8278-02c8870e5b00 of loadbalancer c93ec53a-74a4-44ef-9c14-b3fbd4227481: Bad request with: [PUT http://opk.myorg:9876/v2.0/lbaas/listeners/c0e0fbdb-bd5e-4e11-8278-02c8870e5b00], error message: {"debuginfo": null, "faultcode": "Client", "faultstring": "Unknown attribute for argument listener_.listener: allowed_cidrs"}
```

**Environment**: k8s v1.16.2
- openstack-cloud-controller-manager version: latest container image
- OS (e.g. from /etc/os-release): Container Linux by CoreOS 2191.5.0 (Rhyolite)
- Kernel (e.g. `uname -a`): linux  4.19.68-coreos

**Comment by kayrus** [comment]
`allowed_cidrs` supported only in Octavia. Legacy Neutron LBaaS extension doesn't support this parameter.

**Comment by JrCs** [comment]
I'm using Octavia

**Comment by kayrus** [comment]
@JrCs can you share your cloud controller config?

**Comment by JrCs** [comment]
In my case i don't want to create LB with access control list

**Comment by JrCs** [comment]
Sure:

> [Global]
> region=CNP-HP-INTRA
> auth-url=http://opk.myorg:5000/v3
> username=myuser
> password=xxxxxxxxxx
> domain-name=Default
> tenant-name=myk8s
> 
> [Networking]
> public-network-name=my-network
> ipv6-support-disabled=true
> 
> [LoadBalancer]
> use-octavia=true
> subnet-id=4ebf4be3-e405-4544-b695-5328b5fd1060
> internal-lb=true
>

**Comment by kayrus** [comment]
@lingxiankong ^^

**Comment by lingxiankong** [comment]
@JrCs Hi, I'm still on holiday, cannot have access to my environment, will take a look at this issue once I'm back next week.

**Comment by kayrus** [comment]
@JrCs allowed CIDRs were added in OpenStack Train release: https://docs.openstack.org/releasenotes/octavia/train.html
Are you sure you're using the latest Octavia?

**Comment by JrCs** [comment]
No we are using Octavia from the Rocky series.  
It will be great to have compatibility with old Openstack Series.

**Comment by lingxiankong** [comment]
@JrCs Hi, since I don't have Rocky Octavia, could you please help to verify if the docker image `docker.io/lingxiankong/openstack-cloud-controller-manager:fix-update-listener` works for you?

**Comment by JrCs** [comment]
I think i need a new rbac manifest because i have this error:
```
 E1119 14:03:51.636387       1 leaderelection.go:331] error retrieving resource lock kube-system/cloud-controller-manager: leases.coordination.k8s.io "cloud-controller-manager" is forbidden: User "system: │
│ serviceaccount:kube-system:cloud-controller-manager" cannot get resource "leases" in API group "coordination.k8s.io" in the namespace "kube-system"
```

**Comment by JrCs** [comment]
I have update the `system:cloud-controller-manager` cluster role with:
```yaml
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - list
  - get
  - watch
  - create
  - patch
  - update
```
to deploy the controller.

I can now delete the service without error but when  i try to create a new service i have this errors:
```
I1119 14:23:59.008296       1 event.go:281] Event(v1.ObjectReference{Kind:"Service", Namespace:"default", Name:"toto", UID:"16accecd-bf45-44b8-b686-557a1b92ec8c", APIVersion:"v1", ResourceVersion:"68591", FieldPath:""}): type: 'Normal' reason: 'EnsuringLoadBalancer' Ensuring load balancer
E1119 14:24:59.499970       1 controller.go:254] error processing service default/toto (will retry): failed to ensure load balancer: failed to create listener for loadbalancer 999f2ba4-fe35-4d5c-abc3-537ddd9ba696: Bad request with: [POST http://cnp31opkintraapi.cer31.recouv:9876/v2.0/lbaas/listeners], error message: {"debuginfo": null, "faultcode": "Client", "faultstring": "Unknown attribute for argument listener_.listener: allowed_cidrs"}
I1119 14:24:59.500045       1 event.go:281] Event(v1.ObjectReference{Kind:"Service", Namespace:"default", Name:"toto", UID:"16accecd-bf45-44b8-b686-557a1b92ec8c", APIVersion:"v1", ResourceVersion:"68591", FieldPath:""}): type: 'Warning' reason: 'SyncLoadBalancerFailed' Error syncing load balancer: failed to ensure load balancer: failed to create listener for loadbalancer 999f2ba4-fe35-4d5c-abc3-537ddd9ba696: Bad request with: [POST http://cnp31opkintraapi.cer31.recouv:9876/v2.0/lbaas/listeners], error message: {"debuginfo": null, "faultcode": "Client", "faultstring": "Unknown attribute for argument listener_.listener: allowed_cidrs"}
```

**Comment by lingxiankong** [comment]
@JrCs I suspect there is some problem in gophercloud, I will dig into that

**Comment by lingxiankong** [comment]
@JrCs can you modify the occm log level to 4 and provide the related log?

```
      containers:
      - args:
        - /bin/openstack-cloud-controller-manager
        - --v=4 <== HERE
        - --cloud-config=/etc/cloud/cloud-config
```

**Comment by JrCs** [comment]
@lingxiankong: here's the logs: https://gist.github.com/JrCs/5df8010571ddebc22b764b8b655b5b12

**Comment by kayrus** [comment]
@lingxiankong does CCM allow to debug json requests/responses as well?

**Comment by lingxiankong** [comment]
@JrCs Please test again using `docker.io/lingxiankong/openstack-cloud-controller-manager:fix-update-listener`, there was another bug when checking feature support.

**Comment by lingxiankong** [comment]
> @lingxiankong does CCM allow to debug json requests/responses as well?

No idea, but you can change the code in gophercloud to print the info, or on openstack server side.

**Comment by JrCs** [comment]
@lingxiankong: it's works :ok_hand:.
Is it possible to release a new "stable" version like 1.6.1 ?

**Comment by lingxiankong** [comment]
> @lingxiankong: it's works 👌.
> Is it possible to release a new "stable" version like 1.6.1 ?

@JrCs we do have plan to make a minor version release in the next few days, please stay tuned :-)

> Also why do i need to add new RBAC (coordination.k8s.io) and where can i find/install it ?

TBH I've no idea because we always grant the occm cluster-admin role

**Comment by JrCs** [comment]
I don't know where my manifest came but in my case the controller is using serviceAccount: cloud-controller-manager

**Comment by JrCs** [comment]
@lingxiankong: the rbac manifest i used is from this repository: https://github.com/kubernetes/cloud-provider-openstack/tree/master/cluster/addons/rbac
Perhaps i can create a PR to update it ?

**Comment by lingxiankong** [comment]
@chrigl thanks for proposing the fix. @JrCs could you please also review that PR?

**Comment by JrCs** [comment]
@lingxiankong: done
