### ISSUE TITLE
Improve CSI Cinder Snapshot: add --force flag to create snapshots of in-use volumes

### ISSUE THREAD

**Issue by piwi91** [kubernetes/cloud-provider-openstack#832]
/kind feature

**What happened**:

The current implementation of snapshots only allows us to create snapshots of volumes which are not in-use.

**What you expected to happen**:

It is possible to use a --force flag to create snapshots of volumes which are attached to an instance as described in https://docs.openstack.org/python-openstackclient/pike/cli/command-objects/volume-snapshot.html

**How to reproduce it (as minimally and precisely as possible)**:

Create a snapshot of an in-use volume

**Comment by jichenjc** [comment]
https://github.com/container-storage-interface/spec/blob/master/spec.md
doesn't seems to support a force flag

from openstack side certainly we can add this flag into API call
but how to provide this flag is a question mark, we may not want to always add this flag

any comments @adisky

**Comment by vkamra** [comment]
@jichenjc - any reason to not always add this flag? Most use cases that leverage volume snapshots will target volumes that are in-use.

This will align the CSI driver behavior with other storage providers in the community.

**Comment by jichenjc** [comment]
um... another check, seems the doc is not correct ,the code in cinder seems described what you mentioned

```
        valid_status = ["available", "in-use"] if force else ["available"]

```

https://docs.openstack.org/api-ref/block-storage/v3/index.html?expanded=create-a-snapshot-detail#volume-snapshots-snapshots


force (Optional) | body | boolean | Indicates whether to backup, even if the volume is attached. Default is false. See valid boolean values
-- | -- | -- | --



so overall I think it's a reasonable request

**Comment by nitesh-sharma-trilio** [comment]
Hello Team,

What version of Cinder CSI will have this force snapshot option working ?

Thanks.

**Comment by jichenjc** [comment]
I am not sure we made release after the PR merged
@ramineni @lingxiankong do you know that? 

@nitesh-sharma-trilio use :latest image of CSI cinder should get you the feature

**Comment by ramineni** [comment]
@nitesh-sharma-trilio It will be part of next release 1.19. But ya , you could use latest image published to avail the feature for now.

**Comment by deshui123** [comment]
When is the next version expected

**Comment by jichenjc** [comment]
@ramineni @lingxiankong I didn't pay attention to CPO release schedule before
are we align with k8s release schedule so when there is k8s 1.19, we will have it at same time?

**Comment by lingxiankong** [comment]
> @ramineni @lingxiankong I didn't pay attention to CPO release schedule before
> are we align with k8s release schedule so when there is k8s 1.19, we will have it at same time?

Correct. But we are free to do patch release if there is critical bugfix e.g. `v1.19.0-cpo.1` rather than using the `latest` which is not recommended for production usage.
