### ISSUE TITLE
Cleanup documentation of CSIMigration as soon as possible

### ISSUE THREAD

**Issue by chrigl** [kubernetes/cloud-provider-openstack#836]
This is basically a reminder for me.

**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
> /kind bug
/kind documentation

**Todo**:

Remove caveat from documentation of #835 when https://github.com/kubernetes/kubernetes/issues/79043 is closed and deletion of pre-provisioned volumes actually works

**Comment by ramineni** [comment]
@chrigl Are you still working on this?
