### ISSUE TITLE
Update Gophercloud

### ISSUE THREAD

**Issue by ismacasti** [kubernetes/cloud-provider-openstack#848]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind feature

**What happened**:
A change was introduced in Gophercloud that could solve some problems we are facing while using openstack-cloud-provider.
**What you expected to happen**:
Gophercloud dependency gets updated to its current master.

**Anything else we need to know?**:
This change (https://github.com/gophercloud/gophercloud/issues/1764) would solve some problems we have in our environment. We would like openstack-cloud-provider to have those fixes.
**Environment**:
- openstack-cloud-controller-manager version: 1.16
- OS (e.g. from /etc/os-release): SLES 15.1
- Kernel (e.g. `uname -a`): 4.19

**Comment by kayrus** [comment]
relates to #790

**Comment by ismacasti** [comment]
Thanks!
