### ISSUE TITLE
Add ChangeLog file for release

### ISSUE THREAD

**Issue by oz123** [kubernetes/cloud-provider-openstack#858]
/kind feature

This repository is evolving very fast, and the migration to CCM is probably very painful for a lot of people. To ease the migration, and have better communication with users, I suggest adding a ChangeLog with the most important changes\bug fixes for each release.

**Comment by adisky** [comment]
@oz123 Thanks, we know the issue..I have already raise a PR to enable release notes automation.

**Comment by ramineni** [comment]
@adisky could we add link to the PR here , so we could track and close the issue when done

**Comment by adisky** [comment]
@ramineni sure
https://github.com/kubernetes/test-infra/pull/15419

**Comment by oz123** [comment]
This can be closed.

**Comment by oz123** [comment]
@adisky there is a release which followed the PR mentioned here, but I still don't see the release notes. Is this issue resolved really?

**Comment by ramineni** [comment]
@oz123 we will take care of it from this release, that's the reason kept the bug open.

**Comment by oz123** [comment]
Cool, it seemed like fetja is closing the issue so I wanted to make sure it's not forgotten.

I found this link:
https://relnotes.k8s.io/?areas=provider%2Fopenstack

Maybe this should be linked in a simple file called Changelog?

**Comment by ramineni** [comment]
@oz123 Those are currently changes for intree provider only not for external. For external its not generated yet, we will try to take care of it in the same way generated for intree. Will be taken care fro this release.
@lingxiankong is on it

**Comment by lingxiankong** [comment]
I have finally got a script working, so from this release (v1.18.0) we are going to use the `Release note` in the PR description to generate our release note, I've already added/modified the content for all the merged PRs since v1.17.0 as needed, so the output of my script is like the following:

```
## Changelog since v1.17.0

### Action Required

* openstack-cloud-controller-manager: Support OpenStack Octavia by default as load balancer implementation, Neutron-LBaaS has been deprecated in OpenStack since Queens release and no longer maintained in openstack-cloud-controller-manager. So it's strongly recommended to use Octavia if upgrade to the latest openstack-cloud-controller-manager docker image. (#977, @lingxiankong)

### Other notable changes

* cinder-csi-plugin: rescan-on-resize option added to scan and check new block device size before a filesystem resize. Applicable for VMWare hypervisors (#861, @kayrus)
* Support multi-arch images for all maintained services/binaries.  (#910, @ricolin)
* k8s-keystone-auth: Support mapping from Keystone roles to Kubernetes users/groups. (#953, @lingxiankong)
* cinder-csi-plugin: Cluster admin can define `search-order` in cloud configuration for node metadata information retrieval. (#920, @jichenjc)
* cinder-flexvolume-driver: The driver is deprecated from cloud-provider-openstack repo. (#937, @lingxiankong)
* octavia-ingress-controller: Support to create TLS Ingress. The TLS support requires OpenStack Barbican deployed in the cloud, TLS Ingress creation will fail if Barbican is not available. (#927, @lingxiankong)
* openstack-cloud-controller-manager: Delete the floating IP only if it is created dynamically by the cloud controller manager. (#930, @lingxiankong)
* manila-csi-plugin: bumped csi-provisioner to 1.4.0 and csi-snapshotter to 1.2.2 (#911, @gman0)
* cinder-csi-plugin: Support volume cloning. (#868, @ramineni)
* openstack-cloud-controller-manager: Support predictable and proper server IP addresses search order. (#884, @kayrus)
```

/cc @ramineni @chrigl

**Comment by ramineni** [comment]
@lingxiankong Awesome !! Thanks.
If we could categorize  the deprecation , features etc. would be good, from next release it can be taken care while adding in release note I suppose.

**Comment by lingxiankong** [comment]
> If we could categorize the deprecation , features etc. would be good, from next release it can be taken care while adding in release note I suppose.

That needs more customized pre-defined strings which may bring complexity, let's go with this way first and see if could get some feedback.

**Comment by lingxiankong** [comment]
See v1.18.0 release: https://github.com/kubernetes/cloud-provider-openstack/releases/tag/v1.18.0
