### ISSUE TITLE
Cinder CSI: wrong instanceID detection in OS with python based cloudinit

### ISSUE THREAD

**Issue by kayrus** [kubernetes/cloud-provider-openstack#859]
/kind bug

**What happened**:

Cinder CSI plugin detects invalid node ID:

```
I1202 13:49:57.542000       1 utils.go:79] GRPC call: /csi.v1.Identity/GetPluginInfo
I1202 13:49:57.542031       1 utils.go:80] GRPC request:
I1202 13:49:57.542113       1 identityserver.go:33] Using default GetPluginInfo
I1202 13:49:57.542119       1 utils.go:85] GRPC response: name:"cinder.csi.openstack.org" vendor_version:"1.1.0"
I1202 13:49:59.023895       1 utils.go:79] GRPC call: /csi.v1.Node/NodeGetInfo
I1202 13:49:59.023927       1 utils.go:80] GRPC request:
I1202 13:49:59.024432       1 mount.go:246] Got instance id from /var/lib/cloud/data/instance-id: i-0008fe64
I1202 13:49:59.298012       1 utils.go:85] GRPC response: node_id:"i-0008fe64" max_volumes_per_node:256 accessible_topology:<segments:<key:"topology.cinder.csi.openstack.org/zone" value:"region-3a" > >
```

OpenStack metadata service supports EC2 metadata API (e.g. `http://169.254.169.254/2009-04-04/meta-data/instance-id`), where nova [generates](https://github.com/openstack/nova/blob/56eac06561bc843dcf7497e8b7ac3027f62544c1/nova/api/metadata/base.py#L255) EC2 id, which doesn't have anything in common with a real OpenStack instance uuid. This EC2 id is used by python cloud-init and saved into the `/var/lib/cloud/data/instance-id`.

Legacy CCM code had an ability to define the [metadata order](https://github.com/kubernetes/cloud-provider-openstack/blob/f8ad69f78a71f945eef6c0858afecbe68f14c79d/docs/provider-configuration.md#metadata-optional-parameters), nevertheless it didn't use the `/var/lib/cloud/data/instance-id` file, but cloudinit drive, which is not really used in modern OpenStack deployments, therefore it always fell back to the [OpenStack metadata service](https://github.com/kubernetes/cloud-provider-openstack/blob/f8ad69f78a71f945eef6c0858afecbe68f14c79d/pkg/util/metadata/metadata.go#L42).

Cinder CSI doesn't have the order option and it [always reads](https://github.com/kubernetes/cloud-provider-openstack/blob/f8ad69f78a71f945eef6c0858afecbe68f14c79d/pkg/csi/cinder/nodeserver.go#L543) the `/var/lib/cloud/data/instance-id` file first, therefore it detects wrong instance ID.

This issue doesn't occur in CoreOS, because CoreOS [cloudinit](https://github.com/coreos/coreos-cloudinit) doesn't write the `/var/lib/cloud/data/instance-id` file.

**What you expected to happen**:

* instance ID code should be cleaned up. Probably it's worth removing the current [CSI code](https://github.com/kubernetes/cloud-provider-openstack/blob/f8ad69f78a71f945eef6c0858afecbe68f14c79d/pkg/csi/cinder/mount/mount.go#L240) and reuse the [CCM configdrive code](https://github.com/kubernetes/cloud-provider-openstack/blob/f8ad69f78a71f945eef6c0858afecbe68f14c79d/pkg/util/metadata/metadata.go#L104)
* add a `search-order` option to the Cinder CSI driver

**How to reproduce it (as minimally and precisely as possible)**:

I was able to reproduce it on a VM, which uses python based [cloudinit](https://cloudinit.readthedocs.io/en/latest/topics/dir_layout.html), e.g. CentOS, Ubuntu, SLES, etc.

**Anything else we need to know?**:

Probably this issue is somehow connected to the #856

So far I'm using the following hotfix:

```diff
diff --git a/pkg/csi/cinder/nodeserver.go b/pkg/csi/cinder/nodeserver.go
index 73ce3f3..3b7646c 100644
--- a/pkg/csi/cinder/nodeserver.go
+++ b/pkg/csi/cinder/nodeserver.go
@@ -539,17 +539,19 @@ func getAvailabilityZoneMetadataService(m openstack.IMetadata) (string, error) {
 }
 
 func getNodeID(mount mount.IMount, metadata openstack.IMetadata) (string, error) {
-       // First try to get instance id from mount provider
-       nodeID, err := getNodeIDMountProvider(mount)
+       // First try to get instance id from metadata service
+       klog.V(3).Infof("Trying to GetInstanceID from metadata service")
+       nodeID, err := getNodeIDMetdataService(metadata)
        if err == nil {
                return nodeID, nil
        }
+       klog.V(3).Infof("Failed to GetInstanceID from metadata service: %v", err)
 
-       klog.V(3).Infof("Trying to GetInstanceID from metadata service")
-       nodeID, err = getNodeIDMetdataService(metadata)
+       nodeID, err = getNodeIDMountProvider(mount)
        if err != nil {
-               klog.V(3).Infof("Failed to GetInstanceID from metadata service: %v", err)
+               klog.V(3).Infof("Failed to GetInstanceID from mount provider: %v", err)
                return "", err
        }
+
        return nodeID, nil
 }
```

**Environment**:
- openstack-cloud-controller-manager version: 1.16
- OS (e.g. from /etc/os-release): CentOS, Ubuntu, SLES

**Comment by kayrus** [comment]
Default CSI manifests in produce the following issues in CoreOS:

```
MountVolume.SetUp failed for volume "pods-cloud-data" : hostPath type check failed: /var/lib/cloud/data is not a directory
```

It's worth removing the `/var/lib/cloud/data` dir mount from the `cinder-csi-nodeplugin.yaml` manifest. It will also fix the invalid instance ID detection in `CentOS, Ubuntu, SLES`.

**Comment by ramineni** [comment]
I prefer adding the search-order option instead , removing this might break those if anyone using it as its still supported way.

**Comment by kayrus** [comment]
@ramineni I don't believe it can be used by anyone, because it is a ec2 id not an openstack uuid

**Comment by adisky** [comment]
@kayrus
`OpenStack metadata service supports EC2 metadata API (e.g. http://169.254.169.254/2009-04-04/meta-data/instance-id), where nova generates EC2 id, which doesn't have anything in common with a real OpenStack instance uuid. This EC2 id is used by python cloud-init and saved into the /var/lib/cloud/data/instance-id.`
cloud-init not always uses EC2 id, it default uses openstack instance id.
https://cloudinit.readthedocs.io/en/latest/topics/datasources/openstack.html
it default selects the openstack version, from cloud init docs
_"This list of urls will be searched for an OpenStack metadata service. The first entry that successfully returns a 200 response for <url>/openstack will be selected. (default: [‘http://169.254.169.254’])"_
In my local setup, it reads from /var/lib/cloud/data/instance-id, and it contains actual instance id.
So i will also not suggest for removal, please fix it with search order option.

**Comment by kayrus** [comment]
@adisky I don't mind about adding the search-order, but before adding it, I need to clarify details.
In my case I explicitly forced the openstack datasource for cloud-init, but it still uses ec2 identity. Thanks for letting me know that it works in other environments. It's worth to investigate on my side.

**Comment by celiawa** [comment]
We saw this issue very frequently, many of our nodes get the wrong nodeid.  So volume attach to these node with error " rpc error: code = NotFound desc = ControllerPublishVolume Instance not found". When this issue will be fixed. And can you please tell the workaround to let the node work. Thanks.

[root@vm-10-33-33-33 ~]# kubectl get no -o yaml|grep nodeid
      csi.volume.kubernetes.io/nodeid: '{"cinder.csi.openstack.org":"i-0003bf28"}'
      csi.volume.kubernetes.io/nodeid: '{"cinder.csi.openstack.org":"51f1b915-7c22-4ade-ac4f-3284039ddae9"}'
      csi.volume.kubernetes.io/nodeid: '{"cinder.csi.openstack.org":"89f0e407-3138-4316-a687-ae927dab59ac"}'
      csi.volume.kubernetes.io/nodeid: '{"cinder.csi.openstack.org":"i-0003bf31"}'
      csi.volume.kubernetes.io/nodeid: '{"cinder.csi.openstack.org":"i-0003bf34"}'
      csi.volume.kubernetes.io/nodeid: '{"cinder.csi.openstack.org":"i-0003bf37"}'
      csi.volume.kubernetes.io/nodeid: '{"cinder.csi.openstack.org":"i-0003bf3a"}'
      csi.volume.kubernetes.io/nodeid: '{"cinder.csi.openstack.org":"i-0003bf40"}'
      csi.volume.kubernetes.io/nodeid: '{"cinder.csi.openstack.org":"d4abe67d-8e76-4b88-8cdf-8f0b3d98d4ce"}'
      csi.volume.kubernetes.io/nodeid: '{"cinder.csi.openstack.org":"i-0003bf46"}'

**Comment by jichenjc** [comment]
not sure https://github.com/kubernetes/cloud-provider-openstack/pull/487 (not finished)
is related, will double check soon

**Comment by jichenjc** [comment]
in my environment the instance-id is uuid ,not the EC2 ID anyway

# cat /var/lib/cloud/data/instance-id
861f144f-09ae-45ae-8ccb-ba97c7288b0e

**Comment by jichenjc** [comment]
and to my understanding coreos doesn't use cloud-init at all (use ignition), so instance-id file doesn't fit at all, correct?

**Comment by kayrus** [comment]
@jichenjc old coreos used a go-based cloud-init: https://github.com/coreos/coreos-cloudinit

**Comment by jichenjc** [comment]
@kayrus but we anyway have to use ignition ? as my openshift experience told me coreos will be the future and ignition 2.3 is currently used version .. why are we still considering cloud-init now? thanks

**Comment by lingxiankong** [comment]
I also got `Got instance id from /var/lib/cloud/data/instance-id: b9f7763c-a31a-4814-a35a-5201f4ab7def` correctly in my fresh environement running on top of Ubuntu Bionic VM.

@jichenjc even in Fedora-CoreOS, sending request to metadata service could still work.

**Comment by jichenjc** [comment]
@lingxiankong agree, metadata is identical to all distro as meta service returned identical metadata 
I need further test and paste my further result here soon

**Comment by lingxiankong** [comment]
> Cinder CSI doesn't have the order option and it [always reads](https://github.com/kubernetes/cloud-provider-openstack/blob/f8ad69f78a71f945eef6c0858afecbe68f14c79d/pkg/csi/cinder/nodeserver.go#L543) the `/var/lib/cloud/data/instance-id` file first, therefore it detects wrong instance ID.

@kayrus this is not true in my environment, could you please provide more information? Otherwise, can we close this issue for now?

**Comment by jichenjc** [comment]
with my new fresh setting, I also get this ,

I0203 02:37:03.679176       1 mount.go:246] Got instance id from /var/lib/cloud/data/instance-id: 861f144f-09ae-45ae-8ccb-ba97c7288b0e
I0203 02:37:04.047810       1 utils.go:85] GRPC response: node_id:"861f144f-09ae-45ae-8ccb-ba97c7288b0e" max_volumes_per_node:256 accessible_topology:<segments:<key:"topology.cinder.csi.openstack.org/zone" value:"nova" > >

but I think we still need follow CCM code to add search order of metadata and add metadata service retrival method as well (not just from the cloud-init file) , thoughts? @kayrus @lingxiankong

**Comment by lingxiankong** [comment]
> but I think we still need follow CCM code to add search order of metadata and add metadata service retrival method as well (not just from the cloud-init file) , thoughts?

cinder-csi already has the code in place https://github.com/kubernetes/cloud-provider-openstack/blob/master/pkg/csi/cinder/nodeserver.go#L548-L562. But I agree we make use of `pkg/util/metadata/metadata.go` to keep consistency between binaries.

BTW, we should always use modules under `pkg/util/` rather than spreading the similar code in cloud-provider-openstack repo, e.g I'd rather prefer we remove `pkg/csi/cinder/openstack` and use `pkg/util/openstack` instead, so that we only maintain all the openstack related functions in one single place.

**Comment by jichenjc** [comment]
ok, looks like we already have such capability, thanks for pointing that out
then I believe the only left thing we need to do is to consolidate this ... will see whether I can restore my PR later on.. thanks

**Comment by kayrus** [comment]
the initial issue relates to a cloud-init bug: https://bugs.launchpad.net/nova/+bug/1834506
therefore order option would be nice

**Comment by jichenjc** [comment]
ok, I will add a search order first then see how much effort to refactory ...
