### ISSUE TITLE
Migrating StorageClass and PVs with Introduction of CSI

### ISSUE THREAD

**Issue by afritzler** [kubernetes/cloud-provider-openstack#869]
From reading the migration and concept document of CSI it is not clear to me how PVs and the StorageClass are being migrated at all.

Concider the following scenario: I am starting with a Kuberntes Cluster which has the OoT CCM in place however the `kube-controller-manager` has the `--external-cloud-volume-plugin` flag stil set to use OpenStack. Now I migrate the CSI, set all `cloud-provider` flags to `external`.

Now the question is: what happens with my PVs and how should I go about the `StorageClass`? Do I have to introduce a new StorageClass using the new CSI driver? I also set the `CSIMigration` feature gate on all relevant components. However from looking at the code, the only thing the migration feature gate is doing, is to taking over the calls for the old StorageClass driver reference to the new OoT CSI.

My expectation was, that with `CSIMigration` all PVs and StorageClasses associated to the intree driver will be migrated to the new CSI. However that seems not to be the case. 

Can somebody shed some light on how this is planned to be implemented in the future? I don't like the idea of having a new StorageClass in my cluster. Also migrating PVs manually to this new storage class is also cumbersome. 

/help

**Comment by lingxiankong** [comment]
Assume https://github.com/kubernetes/cloud-provider-openstack/blob/master/docs/migrate-to-ccm-with-csimigration.md could answer the question, if not, please re-open this issue.
