### ISSUE TITLE
external network identified as internal

### ISSUE THREAD

**Issue by yanndegat** [kubernetes/cloud-provider-openstack#88]
/kind feature

**What happened**:
public ipv4 node address identified as Internal 

**What you expected to happen**:
public ipv4 node address identified as External 

**How to reproduce it (as minimally and precisely as possible)**:
Don't name your openstack public network "public"
Create an instance with an IP on this network

**Comment by dims** [comment]
+1 @yanndegat want to help with a PR?

**Comment by yanndegat** [comment]
ok

**Comment by FengyunPan2** [comment]
+1
