### ISSUE TITLE
Add arm64 images to docker.io/k8scloudprovider

### ISSUE THREAD

**Issue by xin3liang** [kubernetes/cloud-provider-openstack#883]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind feature

**What happened**:
There is no openstack cloud provider images for arm64 arch on  docker.io/k8scloudprovider.

**What you expected to happen**:
As arm64 is becoming a more and more popular arch. Arm64 images should be built and put into docker.io/k8scloudprovider. 
So that the users and downstream project (such as magnum) can use them easily on arm64.

**How to reproduce it**:

**Anything else we need to know?**:

**Environment**:
- openstack-cloud-controller-manager version:
- OpenStack version: master (ussuri)
- Others:

**Comment by ricolin** [comment]
@xin3liang  are you plan to work on this or you wish others to?:)

**Comment by xin3liang** [comment]
> @xin3liang are you plan to work on this or you wish others to?:)

I'm happy to do this work if I know how to do it :-).
IMO, here are some things might needed to do:
1, Make [dockerfiles](https://github.com/kubernetes/cloud-provider-openstack/tree/master/cluster/images) can be built on other archs, such as arm64;
2, Some CI integration work might need to do, if images are pushed to docker.io/k8scloudprovider automatically by CI;
3, Add tests for other archs?

**Comment by ricolin** [comment]
@xin3liang I updated the patch out since that's happened to relate to some of my tasks. Please check the pull request.

**Comment by xin3liang** [comment]
> @xin3liang I updated the patch out since that's happened to relate to some of my tasks. Please check the pull request.

@ricolin That really great! Thanks for you work.

**Comment by lingxiankong** [comment]
Re-open this issue to track other tasks relating to CI jobs, etc.

**Comment by lingxiankong** [comment]
@ricolin Please re-use this issue for other tasks.

**Comment by ramineni** [comment]
@ricolin This seems to breaking the CI, https://logs.openlabtesting.org/logs/52/952/fdfdde5f8469461c67a4c76aac190af1db86d535/cloud-provider-openstack-e2e-test-csi-cinder/cloud-provider-openstack-e2e-test-csi-cinder/2854b4e/job-output.txt.gz

+ docker build -t docker.io/k8scloudprovider/cinder-csi-plugin:latest cluster/images/cinder-csi-plugin
2020-03-12 03:15:09.644392 | ubuntu-xenial-citynetwork | unable to prepare context: unable to evaluate symlinks in Dockerfile path: lstat /home/zuul/src/k8s.io/cloud-provider-openstack/cluster/images/cinder-csi-plugin/Dockerfile: no such file or directory

**Comment by ricolin** [comment]
> @ricolin This seems to breaking the CI, https://logs.openlabtesting.org/logs/52/952/fdfdde5f8469461c67a4c76aac190af1db86d535/cloud-provider-openstack-e2e-test-csi-cinder/cloud-provider-openstack-e2e-test-csi-cinder/2854b4e/job-output.txt.gz
> 
> * docker build -t docker.io/k8scloudprovider/cinder-csi-plugin:latest cluster/images/cinder-csi-plugin
>   2020-03-12 03:15:09.644392 | ubuntu-xenial-citynetwork | unable to prepare context: unable to evaluate symlinks in Dockerfile path: lstat /home/zuul/src/k8s.io/cloud-provider-openstack/cluster/images/cinder-csi-plugin/Dockerfile: no such file or directory

will update openlab-zuul-jobs asap

**Comment by ricolin** [comment]
> * cinder-csi-plugin

@ramineni https://github.com/theopenlab/openlab-zuul-jobs/pull/812

**Comment by ramineni** [comment]
@ricolin , need to update migration job as well, https://github.com/theopenlab/openlab-zuul-jobs/blob/master/playbooks/cloud-provider-openstack-multinode-csi-migration-test/pre.yaml#L213 , could you take care of it as well?

**Comment by ricolin** [comment]
> @ricolin , need to update migration job as well, https://github.com/theopenlab/openlab-zuul-jobs/blob/master/playbooks/cloud-provider-openstack-multinode-csi-migration-test/pre.yaml#L213 , could you take care of it as well?

for sure!

**Comment by ramineni** [comment]
@ricolin conformance jobs also failing , 2020-03-12 15:21:01.861069 | ubuntu-xenial-citynetwork | + docker push docker.io/k8scloudprovider/openstack-cloud-controller-manager:latest
2020-03-12 15:21:01.861169 | ubuntu-xenial-citynetwork | + tee /home/zuul/workspace/logs/kubernetes/image-build-upload.log
2020-03-12 15:21:01.927977 | ubuntu-xenial-citynetwork | The push refers to repository [docker.io/k8scloudprovider/openstack-cloud-controller-manager]
2020-03-12 15:21:01.928157 | ubuntu-xenial-citynetwork | An image does not exist locally with the tag: k8scloudprovider/openstack-cloud-controller-manager

I thought existing behavior is maintained , 2 binaries are built without architecture as well, is it correct?

**Comment by ricolin** [comment]
> docker push

Thanks to let me know, I think I know exactly what's going on, will update patch in following hours (will do this ASAP, since it indeed breaks the test)

**Comment by ramineni** [comment]
@ricolin Thanks, i have updated yesterday , https://github.com/theopenlab/openlab-zuul-jobs/pull/818 , but we have issue for old releases of e2e conformance , could you fix that? the change should be done only in case the branch is master, which i have missed.

**Comment by ricolin** [comment]
@ramineni  I update https://github.com/theopenlab/openlab-zuul-jobs/pull/820 to update the makefile targets in jobs. May I ask what kind of issue it's for old releases of e2e conformance?

**Comment by ramineni** [comment]
@xin3liang arm64 images are published now.
https://hub.docker.com/r/k8scloudprovider/openstack-cloud-controller-manager/tags?page=1&ordering=last_updated 

/close

**Comment by xin3liang** [comment]
> @xin3liang arm64 images are published now.
> https://hub.docker.com/r/k8scloudprovider/openstack-cloud-controller-manager/tags?page=1&ordering=last_updated
> 
> /close

Awesome! Thank you @ramineni  and all for fixing this issue :-)
