### ISSUE TITLE
kubernetes storage class using manila share

### ISSUE THREAD

**Issue by rushins** [kubernetes/cloud-provider-openstack#886]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
> /kind bug - no
> /kind feature - yes

**The binaries affected**:

- [ ] openstack-cloud-controller-manager
- [ ] cinder-csi-plugin
- [ ] k8s-keystone-auth
- [ ] client-keystone-auth
- [ ] octavia-ingress-controller
- [x] manila-csi-plugin - question.
- [ ] manila-provisioner
- [ ] magnum-auto-healer
- [ ] barbican-kms-plugin

**What happened**:
hi

I have question on manila-csi-plugin. Are they referring to make storage class in kubernetes using openstack manila share (NFS ) .

i have kubernetes cluster created from openstack instances  , have  manila share network in my openstack  and i can create manila shares.  i would like to see how i can make my manila share as kubernetes storage class using the following procedure outlined. https://github.com/kubernetes/cloud-provider-openstack/blob/master/docs/using-manila-csi-plugin.md

can someone guide me from the  manifests what are the changes and subsequent steps to create as well using helm chart .  i am reading this link but there is no where mentioned storage class but as "CSI" ?

can you clarify.

BR.
Rushi.

**Comment by gman0** [comment]
Please refer to example docs here https://github.com/kubernetes/cloud-provider-openstack/blob/master/examples/manila-csi-plugin/README.md . It covers deployment of csi-manila for NFS shares. You'll need to deploy the CSI NFS driver and csi-manila with NFS share protocol selector first.

If you're using the Helm chart, the defaults in  https://github.com/kubernetes/cloud-provider-openstack/blob/master/examples/manila-csi-plugin/helm-deployment/values.yaml should suffice. Deployment using barebone manifests is a bit more cumbersome, so helm is the recommended way.

If you have you run into any trouble or have any further questions we'll be glad to help.
