### ISSUE TITLE
Cinder CSI plugin noauth support

### ISSUE THREAD

**Issue by SriRamanujam** [kubernetes/cloud-provider-openstack#887]
**Is this a BUG REPORT or FEATURE REQUEST?**: feature request

/kind feature

**The binaries affected**:

- [ ] openstack-cloud-controller-manager
- [x] cinder-csi-plugin
- [ ] k8s-keystone-auth
- [ ] client-keystone-auth
- [ ] octavia-ingress-controller
- [ ] manila-csi-plugin
- [ ] manila-provisioner
- [ ] magnum-auto-healer
- [ ] barbican-kms-plugin

It would be nice if the CSI plugin supported using Cinder without Keystone, ie, noauth. cinder-provisioner supports it, apparently, but that's deprecated and I'd like to avoid using any deprecated code for my new clusters going forward.

**Comment by kayrus** [comment]
@SriRamanujam it doesn't seem possible to enable noauth for CSI driver, since it uses nova client as well.
