### ISSUE TITLE
[cinder-csi-plugin] pv will not be deleted when storage is block mode

### ISSUE THREAD

**Issue by jichenjc** [kubernetes/cloud-provider-openstack#902]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
/kind bug
> /kind feature

**The binaries affected**:

- [ ] openstack-cloud-controller-manager
- [x] cinder-csi-plugin
- [ ] k8s-keystone-auth
- [ ] client-keystone-auth
- [ ] octavia-ingress-controller
- [ ] manila-csi-plugin
- [ ] manila-provisioner
- [ ] magnum-auto-healer
- [ ] barbican-kms-plugin

**What happened**:

tried 2 times, simliar error:
```
root@jj-cloud-provider:~/go/src/github.com/cloud-provider-openstack# kubectl create -f examples/cinder-csi-plugin/block/block.yaml
persistentvolumeclaim/csi-pvc-cinderplugin created
pod/test-block created
Error from server (AlreadyExists): error when creating "examples/cinder-csi-plugin/block/block.yaml": storageclasses.storage.k8s.io "csi-sc-cinderplugin" already exists
(reverse-i-search)`create': kubectl -f examples/cinder-csi-plugin/snapshot/snapshotcreate.yaml ^Ceate
root@jj-cloud-provider:~/go/src/github.com/cloud-provider-openstack# kubectl get pods
NAME         READY   STATUS              RESTARTS   AGE
test-block   0/1     ContainerCreating   0          16s
root@jj-cloud-provider:~/go/src/github.com/cloud-provider-openstack# kc get pvc --all-namespaces
NAMESPACE   NAME                   STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS          AGE
default     csi-pvc-cinderplugin   Bound    pvc-5eba51bb-bfd8-42e4-9eab-7589527b1ee5   1Gi        RWO            csi-sc-cinderplugin   22s
root@jj-cloud-provider:~/go/src/github.com/cloud-provider-openstack# kc get pvc
NAME                   STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS          AGE
csi-pvc-cinderplugin   Bound    pvc-5eba51bb-bfd8-42e4-9eab-7589527b1ee5   1Gi        RWO            csi-sc-cinderplugin   26s
root@jj-cloud-provider:~/go/src/github.com/cloud-provider-openstack# kc get pv

root@jj-cloud-provider:~/go/src/github.com/cloud-provider-openstack# kubectl get pv
NAME                                       CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS        CLAIM                          STORAGECLASS          REASON   AGE
pvc-4c9fe14f-641a-45fd-88b5-1c3b4ec83174   1Gi        RWO            Delete           Terminating   default/csi-pvc-cinderplugin   csi-sc-cinderplugin            23m
pvc-5eba51bb-bfd8-42e4-9eab-7589527b1ee5   1Gi        RWO            Delete           Released      default/csi-pvc-cinderplugin   csi-sc-cinderplugin            91s
root@jj-cloud-provider:~/go/src/github.com/cloud-provider-openstack# kubectl delete pv pvc-5eba51bb-bfd8-42e4-9eab-7589527b1ee5
persistentvolume "pvc-5eba51bb-bfd8-42e4-9eab-7589527b1ee5" deleted

^C
root@jj-cloud-provider:~/go/src/github.com/cloud-provider-openstack# kubectl get pv
NAME                                       CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS        CLAIM                          STORAGECLASS          REASON   AGE
pvc-4c9fe14f-641a-45fd-88b5-1c3b4ec83174   1Gi        RWO            Delete           Terminating   default/csi-pvc-cinderplugin   csi-sc-cinderplugin            25m
pvc-5eba51bb-bfd8-42e4-9eab-7589527b1ee5   1Gi        RWO            Delete           Terminating   default/csi-pvc-cinderplugin   csi-sc-cinderplugin            3m9s


root@jj-cloud-provider:~/go/src/github.com/cloud-provider-openstack# kc describe pv
Name:            pvc-4c9fe14f-641a-45fd-88b5-1c3b4ec83174
Labels:          <none>
Annotations:     pv.kubernetes.io/provisioned-by: cinder.csi.openstack.org
Finalizers:      [external-attacher/cinder-csi-openstack-org]
StorageClass:    csi-sc-cinderplugin
Status:          Terminating (lasts 26m)
Claim:           default/csi-pvc-cinderplugin
Reclaim Policy:  Delete
Access Modes:    RWO
VolumeMode:      Block
Capacity:        1Gi
Node Affinity:   <none>
Message:
Source:
    Type:              CSI (a Container Storage Interface (CSI) volume source)
    Driver:            cinder.csi.openstack.org
    VolumeHandle:      f91991fe-ff24-429d-84b1-d0f78c8f728a
    ReadOnly:          false
    VolumeAttributes:      storage.kubernetes.io/csiProvisionerIdentity=1578984151545-8081-cinder.csi.openstack.org
Events:
  Type     Reason              Age                From                                                                                         Message
  ----     ------              ----               ----                                                                                         -------
  Warning  VolumeFailedDelete  26m (x6 over 27m)  cinder.csi.openstack.org_csi-cinder-controllerplugin-0_0a17f20a-3699-11ea-9953-0242ac110003  rpc error: code = Internal desc = DeleteVolume failed with error Cannot delete the volume "f91991fe-ff24-429d-84b1-d0f78c8f728a", it's still attached to a node

```

**What you expected to happen**:

the pv should be deleted when the pvc is delete

**How to reproduce it**:

**Anything else we need to know?**:

**Environment**:
- openstack-cloud-controller-manager version:
- OpenStack version:
- Others:

**Comment by jichenjc** [comment]
has following error: 

kubectl logs csi-cinder-nodeplugin-96s9z -n kube-system -c cinder-csi-plugin

E0116 05:19:10.975010       1 utils.go:83] GRPC error: rpc error: code = NotFound desc = Volume not mounted
E0116 05:19:11.681162       1 utils.go:83] GRPC error: rpc error: code = NotFound desc = Volume not mounted
E0116 05:19:12.841681       1 utils.go:83] GRPC error: rpc error: code = NotFound desc = Volume not mounted
E0116 05:19:15.075377       1 utils.go:83] GRPC error: rpc error: code = NotFound desc = Volume not mounted
E0116 05:19:19.347607       1 utils.go:83] GRPC error: rpc error: code = NotFound desc = Volume not mounted
E0116 05:19:27.507028       1 utils.go:83] GRPC error: rpc error: code = NotFound desc = Volume not mounted
E0116 05:19:43.672895       1 utils.go:83] GRPC error: rpc error: code = NotFound desc = Volume not mounted
E0116 05:20:15.872728       1 utils.go:83] GRPC error: rpc error: code = NotFound desc = Volume not mounted
E0116 05:21:20.328232       1 utils.go:83] GRPC error: rpc error: code = NotFound desc = Volume not mounted
E0116 05:23:23.493644       1 utils.go:83] GRPC error: rpc error: code = NotFound desc = Volume not mounted
E0116 05:25:26.243984       1 utils.go:83] GRPC error: rpc error: code = NotFound desc = Volume not mounted
E0116 05:27:29.470297       1 utils.go:83] GRPC error: rpc error: code = NotFound desc = Volume not mounted

**Comment by ramineni** [comment]
@jichenjc recently one PR got merged https://github.com/kubernetes/cloud-provider-openstack/pull/897 ,the above error is removed in that PR, could you update it to latest and check if you still see the error

**Comment by jichenjc** [comment]
yes, seems this fixed the problem :)

other than that, maybe use volumeCapability.GetBlock() is a better way.. will propose a minor change in addition to #897 
@ramineni thanks a lot for the info
