### ISSUE TITLE
PV stuck in Terminating when the volume in openstack is deleted.

### ISSUE THREAD

**Issue by celiawa** [kubernetes/cloud-provider-openstack#909]
/kind bug

In our environment, for somehow, the volume is deleted from the openstack dashboard.

The PV then hangs in terminating status. It can't be deleted.
[root@vm-10-33-33-73 plugins_registry]# kubectl get pv pvc-b26159c9-8c7d-4722-a7d5-8911489498ea
NAME                                       CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS        CLAIM                                               STORAGECLASS     REASON   AGE
pvc-b26159c9-8c7d-4722-a7d5-8911489498ea   3Gi        RWO            Delete           Terminating   prashant/datadir-test-p-belk-elasticsearch-data-1   cinder-az-nova            23h

cinder-csi reports the volume not found to k8s.
E0117 05:10:03.988153       1 utils.go:83] GRPC error: rpc error: code = NotFound desc = ControllerUnpublishVolume Volume not found

**What happened**:
The PV stuck in Terminating status.

**What you expected to happen**:
The PV shall be able to be deleted.

**How to reproduce it**:

**Anything else we need to know?**:

**Environment**:
cinder-csi-plugin: v1.16.0

**Comment by jichenjc** [comment]
I seems encountered this before, certainly can take a look at this

**Comment by jichenjc** [comment]
I gave a try and seems I cant reproduce at latest code
can you provide the steps you had this issue?

**Comment by celiawa** [comment]
@jichenjc Thanks very much for your attention. I'm sorry that I try to reproduced several times. I cant reproduce either. The ticket can be closed now.
