### ISSUE TITLE
[cinder-csi-plugin] metrics are not accessible

### ISSUE THREAD

**Issue by bgagnon** [kubernetes/cloud-provider-openstack#913]
/kind bug

**The binaries affected**:

- [x] cinder-csi-plugin

**What happened**:

Tried to access the metrics at `/metrics` for the cinder-csi-plugin controller and node plugins.

**What you expected to happen**:

Some prometheus metrics.

**Anything else we need to know?**:

Recent version of CSI sidecar containers expose Prometheus metrics on a configurable bind address, port and path (defaults to `/metrics`). This should also be provided for `cinder-csi-plugin`, the main container of the CSI Cinder Controller.

**Comment by jichenjc** [comment]
so the question is other side cars already exposed some metrics and cinder-csi-plugin doesn't have the output from /metrics?  if so what's the metrics are recommended? e.g some cinder info? @bgagnon

**Comment by bgagnon** [comment]
I'm not sure if _any_ metrics exist in memory at the moment. It's hard to tell without the `/metrics` handler registered. I think the following metrics would be relevant in the case of the Cinder CSI driver:

* basic Openstack API client metrics (counters for requests, errors)
* any other relevant CSI-related counters
* (maybe) gRPC metrics (eg. [grpc-ecosystem/go-grpc-prometheus](https://github.com/grpc-ecosystem/go-grpc-prometheus))

Since the CSI sidecars have some metrics, I think it's good for consistency if the "main" container has some as well.

**Comment by jichenjc** [comment]
um.. yes, maybe a framework first then check what can be added..

**Comment by jichenjc** [comment]
https://github.com/kubernetes-csi/external-snapshotter
has --metrics-address and --metrics-path param

vendor/github.com/kubernetes-csi/csi-lib-utils/metrics/metrics.go
but that's for CSI side car only, not sure it can be used directly, need further check

**Comment by HaveFun83** [comment]
any news here?
/remove-lifecycle rotten

**Comment by jichenjc** [comment]
I was wrong on above comments, it's not only related to snapshot but also related to others.
so need check CSI driver as well

**Comment by jichenjc** [comment]
/assign 
maybe we can refer to #1178

**Comment by MPV** [comment]
Would this help? https://github.com/kubernetes-csi/docs/issues/339
