### ISSUE TITLE
CSI provisioned volumes are missing "kubernetes.io/created-for" tags in Openstack

### ISSUE THREAD

**Issue by bgagnon** [kubernetes/cloud-provider-openstack#914]
/kind feature

**The binaries affected**:

- [x] cinder-csi-plugin

**What happened**:

Provisioning a CSI Cinder volume works, but it does not have any tags metadata that identify the PVC:

* `kubernetes.io/created-for/pvc/namespace`
* `kubernetes.io/created-for/pvc/name`
* `kubernetes.io/created-for/pv/name`

**What you expected to happen**:

I would expect the tags to be present. This is a regression from the in-tree openstack cloud controller manager.

**Anything else we need to know?**:

With CSI, we get a new tag called `cinder.csi.openstack.org/cluster`, which is useful, which means the support for tags is there, just maybe incomplete?

**Environment**:
- openstack-cloud-controller-manager version: v14.0.0

**Comment by bgagnon** [comment]
It looks like it is implemented for Manilla:
https://github.com/kubernetes/cloud-provider-openstack/blob/master/pkg/share/manila/share.go#L121

But not for Cinder.

**Comment by lingxiankong** [comment]
Hi @bgagnon you are right, the current cinder-csi-plugin implementation only includes the cluster name in the properties when creating a Cinder volume, that's the restriction of the CSI architecture, because the CSI driver can only see information coming from the controller.

However, I'd like to know the use cases you are asking for those tags, maybe we could find other solutions.

**Comment by bgagnon** [comment]
The use case is a multi-tenant Kubernetes cluster. For cost attribution (internal rebilling) and volume management, we'd like to quickly and reliably attribute volumes from Openstack to specific namespaces  and PVCs in specific clusters.

**Comment by lingxiankong** [comment]
@bgagnon I'm very glad I'm not the only one asking for features like what you said :-) please read more info here https://github.com/kubernetes-csi/external-provisioner/issues/170

**Comment by jichenjc** [comment]
@lingxiankong I read the link you provided, as lack of some background , I assume this PR requirement is doable or technically/arch prevent us to do so？

**Comment by lingxiankong** [comment]
@jichenjc changes should be made in external-provisioner, not cinder-csi-plugin

**Comment by jichenjc** [comment]
@lingxiankong got it ,thanks~, so should we close this issue?

**Comment by lingxiankong** [comment]
We could, but I'm ok we leave it as is, just in case one day external-provisioner could pass that information to cinder-csi.

**Comment by jichenjc** [comment]
@lingxiankong why manila can create this tag? seems arch is same why we can't do in cinder only is a question..

**Comment by lingxiankong** [comment]
I don't think https://github.com/kubernetes/cloud-provider-openstack/blob/master/pkg/share/manila/share.go#L121 is part of manila-csi-plugin, and based on my understanding, manila-csi-plugin doesn't interact with Cinder.

**Comment by jichenjc** [comment]
I understand it doesn't interact with cinder, the question is if manila plugin is able to impelement CSI with the tags, then it should be ok for cinder, but as you mentioned, the  https://github.com/kubernetes/cloud-provider-openstack/blob/master/pkg/share/manila/share.go#L121  is not part of manila plugin, then it's another topic ... need check manila code as well
