### ISSUE TITLE
CCM node instance type should always use flavor.original_name

### ISSUE THREAD

**Issue by bgagnon** [kubernetes/cloud-provider-openstack#916]
/kind bug

**The binaries affected**:

- [x] openstack-cloud-controller-manager

**What happened**:

Node label `node.kubernetes.io/instance-type` was set to `2004`, a flavor id.

**What you expected to happen**:

Node label `node.kubernetes.io/instance-type` should be `ug2.2xlarge`, the flavor name for id `2004`.

**How to reproduce it**:

Use the CCM against an Openstack Compute API that defaults to a micro-version older than 2.47.

**Anything else we need to know?**:

The instance type uses one of `name`, `id` or `original_name`, whichever is found first in the server response under the `flavor` object.

If the compute service defaults to a micro-version earlier than 2.47, only `flavor.id` will be included (eg. `"2004"`), which is not terribly useful to have as a node label in Kubernetes.

The client micro-version should be fixed to 2.47 to guarantee the presence of `flavor.original_name`.

**Environment**:
- openstack-cloud-controller-manager version: v1.14.0

**Comment by lingxiankong** [comment]
@bgagnon I appreciate the issues you submitted to this repo so far, but could you please use the template when creating issues?

**Comment by baurmatt** [comment]
I think this should be fixed with #1213
