### ISSUE TITLE
[occm] Support to use an existing loadbalancer for service type loadbalancer

### ISSUE THREAD

**Issue by hamzazafar** [kubernetes/cloud-provider-openstack#932]
/kind feature

**The binaries affected**:

- [x] openstack-cloud-controller-manager
- [ ] cinder-csi-plugin
- [ ] k8s-keystone-auth
- [ ] client-keystone-auth
- [ ] octavia-ingress-controller
- [ ] manila-csi-plugin
- [ ] manila-provisioner
- [ ] magnum-auto-healer
- [ ] barbican-kms-plugin

**What happened**:
There is a one-to-one mapping of k8s services and external loadbalancers. Creating a new loadbalancer in cloud for each k8s service can be costly for customers. [octavia-ingress-controller](https://github.com/kubernetes/cloud-provider-openstack/blob/08824aaabec43b3ede9a8af3e9aed897fa3bf054/docs/using-octavia-ingress-controller.md) already solves this problem by creating an external loadbalancer and setting some L7 policies to support multiple k8s services behind the same loadbalancer.

**Problem**
Not all octavia provider drivers support L7 policies.

**Solution**
Add support in OCCM to use an existing loadbalancer instead of creating a new one.

**Comment by hamzazafar** [comment]
User can create a loadbalancer using OpenStack CLI and then specify the ID of loadbalancer in an annotation while creating a k8s service. 

I'll be happy to provide a patch if there is interest in this feature

**Comment by rochaporto** [comment]
Adding here... the goal would be to add serviceType: LoadBalancer instances into existing load balancers, and handle the deletion in the same way (drop the members only, not the whole LB instance).

Looking at the code, is the best way to do this to:
1. try to refactor the ensureloadbalancer code
2. hook one more condition into both ensureloadbalancer and ensureloadbalancerdelete

**Comment by lingxiankong** [comment]
Hi, thanks for proposing this feature request. However, personally, it doesn't make sense for me to re-use load balancer in the cloud for k8s services. As mentioned in the description, if the end users have concerns about the cloud resources consumption, Ingress is what they should use.

**Comment by rochaporto** [comment]
@lingxiankong can you expand on why this doesn't make sense? It isn't just for optimizing resource usage, we have multiple use cases where services have endpoints in both VMs and Kubernetes clusters and need to share an external load balancer.

**Comment by lingxiankong** [comment]
> @lingxiankong can you expand on why this doesn't make sense? It isn't just for optimizing resource usage, we have multiple use cases where services have endpoints in both VMs and Kubernetes clusters and need to share an external load balancer.

Why Ingress is not an option? I would be happy to see more use cases to understand better about your requirements.

**Comment by rochaporto** [comment]
Ingress is an option but why not a serviceType LoadBalancer? Can you expand on why this doesn't make sense?

**Comment by lingxiankong** [comment]
Because if you are implementing this feature, you are re-creating the wheels. If Ingress is a valid option, is there any particular reason you want to create your own 'Ingress'?

**Comment by rochaporto** [comment]
I don't want to recreate Ingress, i want to have a serviceType: LoadBalancer - without an Ingress. This is supported already, the only request is to allow registering a member in an existing LoadBalancer.

https://kubernetes.io/docs/concepts/services-networking/service/#loadbalancer

We have multiple users relying on serviceType: LoadBalancer, and wanting to reuse the same setup on our private cloud and public clouds. Without an Ingress defined.

**Comment by hamzazafar** [comment]
[Similar Feature Request](https://github.com/kubernetes/cloud-provider-openstack/issues/933)

**Comment by brtknr** [comment]
This sounds like a useful feature. If a loadbalancer IP has already been allocated and if a different service can make use of a different port for the same IP, this makes perfect sense. A lot of our users in research computing have limited number of floating IPs and cannot rely on spinning out a floating IP for each service. Ingress is okay for relies on having a DNS server and only suitable for HTTP/S endpoints.

**Comment by lingxiankong** [comment]
> Ingress is okay for relies on having a DNS server and only suitable for HTTP/S endpoints.

This is a valid point.

**Comment by QcFe** [comment]
Hello. 
Is there any update on this? I saw there should be the annotation `loadbalancer.openstack.org/load-balancer-id` for LB services but it gets completely ignored. Also documentation says it should be automatically set for LB services but it doesn't for me.
