### ISSUE TITLE
[ manila-csi-plugin ] docker image is not up to date

### ISSUE THREAD

**Issue by tombarron** [kubernetes/cloud-provider-openstack#935]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
/kind bug
> /kind feature

**The binaries affected**:

- [ ] openstack-cloud-controller-manager
- [ ] cinder-csi-plugin
- [ ] k8s-keystone-auth
- [ ] client-keystone-auth
- [ ] octavia-ingress-controller
- [x ] manila-csi-plugin
- [ ] manila-provisioner
- [ ] magnum-auto-healer
- [ ] barbican-kms-plugin

**What happened**:

** docker pull k8scloudprovider/manila-csi-plugin:latest yields 'not found' and k8scloudprovider/manila-csi-plugin:v1.17.0 is a couple months old.**

**What you expected to happen**:  docker pull with latest tag will succeed and fetch a current image corresponding to cloud-provider-openstack source code.

**How to reproduce it**:

run docker pull image as indicated above

**Anything else we need to know?**:

Issue was originally noted here:  https://github.com/kubernetes/cloud-provider-openstack/issues/928#issuecomment-584573774

**Environment**:
- openstack-cloud-controller-manager version:
- OpenStack version:
- Others:

**Comment by ramineni** [comment]
@tombarron manila-csi-plugin seems to be missing here , need to be updated https://github.com/theopenlab/openlab-zuul-jobs/blob/master/playbooks/cloud-provider-openstack-acceptance-test-e2e-conformance/run.yaml#L170 here

**Comment by tombarron** [comment]
Thanks, @ramineni .  Submitted https://github.com/theopenlab/openlab/issues/467 and will fix in openlab-zuul-jobs.

**Comment by tombarron** [comment]
Fixed via theopenlab/openlab-zuul-jobs#795
