### ISSUE TITLE
[cinder-csi-plugin] Failing to delete PV after deattach failure

### ISSUE THREAD

**Issue by celiawa** [kubernetes/cloud-provider-openstack#944]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug

**The binaries affected**:
- [ ] cinder-csi-plugin

**What happened**:

When we do helm delete, after deleting pods, which also has hooks to delete the pvcs. Found that some PV stuck in Terminating status.

kubectl describe pv pvc-31d6cb9c-1ebd-421b-a13f-b5abf23ea007
Name: pvc-31d6cb9c-1ebd-421b-a13f-b5abf23ea007 
Labels: <none> 
Annotations: pv.kubernetes.io/provisioned-by: cinder.csi.openstack.org 
Finalizers: [external-attacher/cinder-csi-openstack-org] 
StorageClass: cinder-az-nova 
**Status: Terminating (lasts 6d11h)** 
Claim: mrnorton/datadir-mongocnf-cmgo-replica-1 
Reclaim Policy: Delete 
Access Modes: RWO 
VolumeMode: Filesystem 
Capacity: 1Gi 
Node Affinity: <none> 
Message: Source: Type: CSI (a Container Storage Interface (CSI) volume source) 
Driver: cinder.csi.openstack.org VolumeHandle: b12c4cc9-9c60-44b8-81ea-f09dd2b70c7c ReadOnly: false VolumeAttributes: storage.kubernetes.io/csiProvisionerIdentity=1579423079658-8081-cinder.csi.openstack.org 
Events: <none>

The attachment for this PV still exist with detach error.

[root@bcmt-sandbox3-3c2w2e-1912-1-control-01 ~]# kubectl get volumeattachment |grep pvc-31d6cb9c-1ebd-421b-a13f-b5abf23ea007 csi-bfe5b6f39e81fcf053d9542200844c6fe147276d7ad19438c37c92acc6eaf4cc cinder.csi.openstack.org pvc-31d6cb9c-1ebd-421b-a13f-b5abf23ea007 bcmt-sandbox3-3c2w2e-1912-1-worker-02 true 7d6h

[root@bcmt-sandbox3-3c2w2e-1912-1-control-01 ~]# kubectl describe volumeattachment csi-bfe5b6f39e81fcf053d9542200844c6fe147276d7ad19438c37c92acc6eaf4cc
Name: csi-bfe5b6f39e81fcf053d9542200844c6fe147276d7ad19438c37c92acc6eaf4cc
Namespace:
Labels:
Annotations: csi.alpha.kubernetes.io/node-id: 95fdffb9-035e-41b8-bb88-263c77e94f7a
API Version: storage.k8s.io/v1
Kind: VolumeAttachment
Metadata:
Creation Timestamp: 2020-02-05T20:11:21Z
Deletion Grace Period Seconds: 0
Deletion Timestamp: 2020-02-05T21:00:30Z
Finalizers:
external-attacher/cinder-csi-openstack-org
Resource Version: 31925915
Self Link: /apis/storage.k8s.io/v1/volumeattachments/csi-bfe5b6f39e81fcf053d9542200844c6fe147276d7ad19438c37c92acc6eaf4cc
UID: b8429920-5985-4b95-a4cc-7337a8d87ddb
Spec:
Attacher: cinder.csi.openstack.org
Node Name: bcmt-sandbox3-3c2w2e-1912-1-worker-02
Source:
Persistent Volume Name: pvc-31d6cb9c-1ebd-421b-a13f-b5abf23ea007
Status:
Attached: true
Attachment Metadata:
Device Path: /dev/vdi
Detach Error:
Message: rpc error: code = NotFound desc = ControllerUnpublishVolume Volume not found
Time: 2020-02-13T02:14:20Z
Events: `

From csi-attacher log, it failed to detach at 0205 21:00:35.73930. 
From csi-provisioner log, the pv is deleted at 0205 21:00:35.722111. Means it deleted before volume detach got success.

0205 21:00:30.785723 1 csi_handler.go:140] Starting detach operation for "csi-bfe5b6f39e81fcf053d9542200844c6fe147276d7ad19438c37c92acc6eaf4cc" I0205 21:00:30.785886 1 csi_handler.go:147] Detaching "csi-bfe5b6f39e81fcf053d9542200844c6fe147276d7ad19438c37c92acc6eaf4cc" I0205 21:00:35.719744 1 csi_handler.go:480] CSIHandler: processing PV "pvc-31d6cb9c-1ebd-421b-a13f-b5abf23ea007": VA "csi-bfe5b6f39e81fcf053d9542200844c6fe147276d7ad19438c37c92acc6eaf4cc" found I0205 21:00:35.729002 1 csi_handler.go:480] CSIHandler: processing PV "pvc-31d6cb9c-1ebd-421b-a13f-b5abf23ea007": VA "csi-bfe5b6f39e81fcf053d9542200844c6fe147276d7ad19438c37c92acc6eaf4cc" found I0205 21:00:35.739302 1 csi_handler.go:428] Saving detach error to "csi-bfe5b6f39e81fcf053d9542200844c6fe147276d7ad19438c37c92acc6eaf4cc" I0205 21:00:35.756415 1 controller.go:141] Ignoring VolumeAttachment "csi-bfe5b6f39e81fcf053d9542200844c6fe147276d7ad19438c37c92acc6eaf4cc" change I0205 21:00:35.756663 1 csi_handler.go:439] Saved detach error to "csi-bfe5b6f39e81fcf053d9542200844c6fe147276d7ad19438c37c92acc6eaf4cc" I0205 21:00:35.756689 1 csi_handler.go:99] Error processing "csi-bfe5b6f39e81fcf053d9542200844c6fe147276d7ad19438c37c92acc6eaf4cc": failed to detach: rpc error: code = NotFound desc = ControllerUnpublishVolume Volume not found I0205 21:00:36.756962 1 controller.go:175] Started VA processing "csi-bfe5b6f39e81fcf053d9542200844c6fe147276d7ad19438c37c92acc6eaf4cc"

I0205 21:00:35.722061 1 controller.go:1385] delete "pvc-31d6cb9c-1ebd-421b-a13f-b5abf23ea007": persistentvolume deleted I0205 21:00:35.722111 1 controller.go:1387] delete "pvc-31d6cb9c-1ebd-421b-a13f-b5abf23ea007": succeeded

I guess when we did helm delete, if first do "kubectl delete pod" and this triggers the volume detach. While it takes too much time to detach a volume. Then the post-delete jod do "kubectl delete pvc", then this trigger the volume to be deleted. 

**What you expected to happen**:
The pv is deleted.

**Environment**:
- cinder-csi-plugin: 1.16

**Comment by lingxiankong** [comment]
Hi, I believe the issue was fixed in release-1.17, please have a try.

/close
