### ISSUE TITLE
Allow for the CSI cinder driver to interact with nodes not managed by OpenStack

### ISSUE THREAD

**Issue by flaper87** [kubernetes/cloud-provider-openstack#95]
/kind feature

The CSI driver requires the Kubernetes cluster to be running in an OpenStack cloud. This expectation leaves out scenarios, where Kubernetes is not running as part of a tenant in an OpenStack managed VM.

It should be possible to refactor the plugin in a way that we can provide support for both, instance and BM, volume attachments either as part of an OpenStack tenant or not.

The goal is to support the following scenarios:

Kubernetes running side-by-side with OpenStack:
- 2 separate clouds (hardware) that can talk to each other.
- Kubernetes has access to the OpenStack cloud and wants to use Cinder for volume management

Kubernetes running inside an OpenStack VM:
- This is the scenario that is currently supported

Kubernetes running on a BM node as part of an OpenStack tenant:
- This may work with the current implementation but I haven't fully tested it.

It's possible that we may need some changes in the current CSI implementation to be able to gather more information about the target node in advance.See this issue for more info: https://github.com/container-storage-interface/spec/issues/216

That said, I believe this could be implemented, perhaps not in the most ideal way, with what we have today in gophercloud and the CPO implementation.

**Comment by flaper87** [comment]
I'm already working on this so, this can be assigned to me.

**Comment by j-griffith** [comment]
@flaper87 Glad to see you're looking at this!  I've played with it a bit (and I think a few others have as well).  Moving to the NodePublishVolume works well in this scneario, but there's an outstanding question of dealing with multiple data transport models.  What I mean here is that we have multiple possible transports: RBD, iSCSI, FC, ISER etc and some unique models within each of those.

It was suggested in this weeks CSI meeting that that requires a different driver for each topology which is not an option for Cinder IMO.  Sounds like you are already working on this and based on your comments so it would be interesting to see what you've come up with, like using the brick extension in cinderclient etc.

**Comment by flaper87** [comment]
>  like using the brick extension in cinderclient etc.

I think this is what would work best, for now. Reserve the node in the `ControllerPublishVolume` call and the let `NodePublishVolume` do the final attach using the brick extension in cinderclient. One problem is that the extension expects the volume to be available and I was hoping to be able to have the Controller reserve it.

Using `gophercloud` we can go as far as initializing the connection (I think) but there's a bunch of other ops done by os-brick that I would rather not replicate just yet.

> I raised the question of a golang connector lib at one point in the past, but I don't think we were far enough along to have any real thought around it. Might be worth raising/considering as a topic again.

I did the same and I think we won't be able to avoid this for much longer. Calling the brick extension in cinderclient from the plugin is fine as a first step but not super clean.

Another idea I'm playing with is to write the node part of the plugin in Python and just use the extension and os-brick from there. I'm not sure how people would feel about having Python code in this repo, though. Will file an issue for this

**Comment by j-griffith** [comment]
@flaper87 Gophercloud will in fact let us do the whole process without too much problem; it works well and we have quite a bit of work in place for most of this (at least iSCSI and FC and I'm sure RBD as well).  The Brick extension is handy for the local-attach because it just "does" everything.

I'm curious about why we'd need brick code in here to use that though?  Couldn't we just run cinderclient with the brick extension in a container with an "attach" entrypoint and just call that from the node server and be done?

**Comment by flaper87** [comment]
> Couldn't we just run cinderclient with the brick extension in a container with an "attach" entrypoint and just call that from the node server and be done?

Yes! this is what I meant with calling `cinderclient`, probably used the wrong words to express my thoughts.

I'll start pushing what I have, which is a very WIP implementation but at least we'll be able to iterate and discuss the implementation over a PR.

Thanks for the feedback

**Comment by Akrog** [comment]
@j-griffith This won't work for RBD, as OS-Brick is very specific to the OpenStack use case.
In OpenStack RBD volumes have 2 types of attachments, and none of them create a real device under /dev, so it won't work for the local attachment use case we are discussing.

OpenStack RBD attachment types are:

- Attaching to VMs: This is done by Nova using libvirt, so an RBD type of disk is added to the hypervisor without any host interaction.
- Reading/Writing data: In Cinder, when we do a local attachment of an RBD volume, what we really get is a file descriptor returned by librados.  This is internally used to transfer the data.  We never do a "dd" on an RBD disk or anything like it, as we don't have a real device to work with.
