### ISSUE TITLE
[cinder-csi-plugin] update snapshot side car to 2.x.x

### ISSUE THREAD

**Issue by jichenjc** [kubernetes/cloud-provider-openstack#951]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
> /kind bug
/kind feature

**The binaries affected**:

- [ ] openstack-cloud-controller-manager
- [x] cinder-csi-plugin
- [ ] k8s-keystone-auth
- [ ] client-keystone-auth
- [ ] octavia-ingress-controller
- [ ] manila-csi-plugin
- [ ] manila-provisioner
- [ ] magnum-auto-healer
- [ ] barbican-kms-plugin

**What happened**:
https://github.com/kubernetes-csi/external-snapshotter/releases
per above, we need add another side car container when upgrade to 2.0.0 snapshotter
docker pull quay.io/k8scsi/snapshot-controller:v2.0.0

this is tracking that action
**What you expected to happen**:

**How to reproduce it**:

**Anything else we need to know?**:

**Environment**:
- openstack-cloud-controller-manager version:
- OpenStack version:
- Others:

**Comment by lingxiankong** [comment]
A nit, please correct the format of 'The binaries affected'

**Comment by jichenjc** [comment]
the code merged
