### ISSUE TITLE
[k8s-keystone-auth] Improve CI

### ISSUE THREAD

**Issue by lingxiankong** [kubernetes/cloud-provider-openstack#954]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind feature

**The binaries affected**:

- [ ] openstack-cloud-controller-manager
- [ ] cinder-csi-plugin
- [x] k8s-keystone-auth
- [ ] client-keystone-auth
- [ ] octavia-ingress-controller
- [ ] manila-csi-plugin
- [ ] manila-provisioner
- [ ] magnum-auto-healer
- [ ] barbican-kms-plugin

**What happened**:
Currently, the k8s-keystone-auth CI job is defined in openlab code repo, which is not controlled by CPO community.

**What you expected to happen**:
Improve the CI for k8s-keystone-auth, we should maintain the test script in this repo instead of in openlab code repo.

**How to reproduce it**:

**Anything else we need to know?**:

**Environment**:
- openstack-cloud-controller-manager version:
- OpenStack version:
- Others:

**Comment by ramineni** [comment]
@lingxiankong Thanks for reporting this. This is much needed , I think we need to move all the test scripts into our repo instead of openlab. Could we make this issue generic, to track all CI jobs.

**Comment by lingxiankong** [comment]
@ramineni I'd prefer we track the tasks using different issues so we could have achievable task for each issue, instead of that a single issue keeps open for months if some service/binary may never get people interested.

However, I agree we should have a unified approach for how to define CI job scripts for each service/binary, just like what we did here https://github.com/kubernetes/cloud-provider-openstack/blob/master/tests/e2e/cloudprovider/test-lb-service.sh

**Comment by ramineni** [comment]
> @ramineni I'd prefer we track the tasks using different issues so we could have achievable task for each issue, instead of that a single issue keeps open for months if some service/binary may never get people interested.
> 
> However, I agree we should have a unified approach for how to define CI job scripts for each service/binary, just like what we did here https://github.com/kubernetes/cloud-provider-openstack/blob/master/tests/e2e/cloudprovider/test-lb-service.sh

@lingxiankong fine with me. Thanks.
