### ISSUE TITLE
[cinder-csi-plugin] Use multiattach cinder type to create pod will be failed.

### ISSUE THREAD

**Issue by LongDuncan** [kubernetes/cloud-provider-openstack#955]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind feature

**The binaries affected**:

- [ ] openstack-cloud-controller-manager
- [x] cinder-csi-plugin
- [ ] k8s-keystone-auth
- [ ] client-keystone-auth
- [ ] octavia-ingress-controller
- [ ] manila-csi-plugin
- [ ] manila-provisioner
- [ ] magnum-auto-healer
- [ ] barbican-kms-plugin

**What happened**:
When I set the cinder type has --property multiattach="<is> True", and then
I used the cinder-csi-plugin to create deployment pod with cinder volume will be failed.
`# kubectl describe po nginx-deployment-67d889fd7d-cv72f`

> Warning  FailedAttachVolume  8s (x7 over 40s)   attachdetach-controller  AttachVolume.Attach failed for volume "pvc-6e60eb8f-4e5b-43db-b91c-205b4c2f6476" : rpc error: code = Internal desc = ControllerPublishVolume Attach Volume failed with error failed to attach e547d18d-f200-412d-a5bb-2f6572e7a877 volume to b294ed65-dfd4-4fcc-825b-8419afa03214 compute: Bad request with: [POST http://10.144.208.21/compute/v2.1/servers/b294ed65-dfd4-4fcc-825b-8419afa03214/os-volume_attachments], error message: {"badRequest": {"code": 400, "message": "Multiattach volumes are only supported starting with compute API version 2.60."}}

**Anything else we need to know?**:
Do you have the roadmap for support cinder multiattach?
And is there has something limit to use?
Thanks.

**Environment**:
- openstack-cloud-controller-manager version: master
- OpenStack version: Stein
- Others: Kubernets: 1.17.3

**Comment by ramineni** [comment]
@LongDuncan support yet to be added, https://github.com/kubernetes/cloud-provider-openstack/issues/729  
/milestone 1.19

**Comment by LongDuncan** [comment]
@ramineni Thank you!

**Comment by lingxiankong** [comment]
Duplicate with #729
