### ISSUE TITLE
failed to ensure load balancer: failed to create listener

### ISSUE THREAD

**Issue by jopfeffe** [kubernetes/cloud-provider-openstack#960]
**Is this a BUG REPORT or FEATURE REQUEST?**:

kind bug

**The binaries affected**:

- [x] openstack-cloud-controller-manager
- [ ] cinder-csi-plugin
- [ ] k8s-keystone-auth
- [ ] client-keystone-auth
- [ ] octavia-ingress-controller
- [ ] manila-csi-plugin
- [ ] manila-provisioner
- [ ] magnum-auto-healer
- [ ] barbican-kms-plugin

**What happened**:

I tried to deploy a load-balancer. The load-balancer is created but the osccm is not able to add listeners.

The setup fails with the following error:
```
I0306 08:12:12.798328       1 event.go:255] Event(v1.ObjectReference{Kind:"Service", Namespace:"ingress-nginx", Name:"openstack-lb", UID:"xxx", APIVersion:"v1", ResourceVersion:"68480", FieldPath:""}): type: 'Normal' reason: 'EnsuringLoadBalancer' Ensuring load balancer
E0306 08:12:15.643095       1 service_controller.go:255] error processing service ingress-nginx/openstack-lb (will retry): failed to ensure load balancer: failed to create listener for loadbalancer xxx: json: cannot unmarshal bool into Go struct field Listener.insert_headers of type string
I0306 08:12:15.643177       1 event.go:255] Event(v1.ObjectReference{Kind:"Service", Namespace:"ingress-nginx", Name:"openstack-lb", UID:"xxx", APIVersion:"v1", ResourceVersion:"68480", FieldPath:""}): type: 'Warning' reason: 'SyncLoadBalancerFailed' Error syncing load balancer: failed to ensure load balancer: failed to create listener for loadbalancer xxx: json: cannot unmarshal bool into Go struct field Listener.insert_headers of type string
[...]
I0306 08:12:20.643393       1 event.go:255] Event(v1.ObjectReference{Kind:"Service", Namespace:"ingress-nginx", Name:"openstack-lb", UID:"xxx", APIVersion:"v1", ResourceVersion:"68482", FieldPath:""}): type: 'Normal' reason: 'EnsuringLoadBalancer' Ensuring load balancer
E0306 08:12:21.084858       1 service_controller.go:255] error processing service ingress-nginx/l1 (will retry): failed to ensure load balancer: error getting LB kube_service_kubernetes_ingress-nginx_openstack-lb listeners: json: cannot unmarshal bool into Go struct field Listener.insert_headers of type string
```

**What you expected to happen**:

LoadBalancer + listeteners are created. We evaluated the external osccm in 09/2019 and it worked back than and we are now about to migrate from the internal one. Btw: There is still no issue with the internal osccm.

**How to reproduce it**:

OSCCM config:

```
[Global]
auth-url    = https://iam.eu-de.otc.t-systems.com:443/v3
username    = xxx
password    = xxx
tenant-name = eu-de
domain-name = xxx
region      = eu-de

[LoadBalancer]
subnet-id           = xxx
floating-network-id = 0a2228f2-7f8a-45f1-8e09-9039e1d09975
create-monitor      = true
monitor-delay       = 5s
monitor-timeout     = 10s
monitor-max-retries = 3
use-octavia         = false
 ```

LB:
```
kind: Service
apiVersion: v1
metadata:
  name: openstack-lb
  namespace: ingress-nginx
  labels:
    app: openstack-lb
  annotations:
    service.beta.kubernetes.io/openstack-internal-load-balancer: "false"
spec:
  type: LoadBalancer
  externalTrafficPolicy: "Local"
  selector:
    app: ingress-nginx
  ports:
  - name: http
    port: 80
  - name: https
    port: 443
```

**Anything else we need to know?**:
-

**Environment**:
- openstack-cloud-controller-manager version: v1.16.0
- OpenStack version: Open Telekom Cloud (OpenStack Nova: 13.2.1-20190929164259)
- Others: Kubernetes v1.16.6

**Comment by lingxiankong** [comment]
@jopfeffe, That's weird, have you tried v1.17.0? Basically v1.17.0 should also work with v1.16 Kubernetes well.

**Comment by jopfeffe** [comment]
Yes, same error for v1.17.0 and older versions.

**Comment by jopfeffe** [comment]
We checked the API log. What we see there:
1. create LB request.
2. create listener request. The responds to the request contains the following "insert_headers" section:
```
     "listener": {
            "insert_headers": {
                "X-Forwarded-ELB-IP": false,
                "X-Forwarded-Host": true
            },
```
After that there seems to be no further interaction with the openstack API.

**Comment by jopfeffe** [comment]
Just had quick look at the gophercloud lb listerner code. 
https://github.com/gophercloud/gophercloud/blob/f14c8725b6c0d05e1ea8bf6435124b64bc54333f/openstack/loadbalancer/v2/listeners/requests.go#L133

`map[string]string` fails for the unquoted bool response. In our case it must be something like `map[string]bool`. But this seems to be no general solution.

This is just a guess. I'm no a go programmer...

**Comment by lingxiankong** [comment]
@jopfeffe Just noticed you have `use-octavia=false`, I am not sure neutron-lbaas supports the same API with Octavia.

**Comment by jopfeffe** [comment]
@lingxiankong I tested `use-octavia=true` and i got the following error:
```
E0310 07:41:03.061686       1 core.go:90] Failed to start service controller: the cloud provider does not support external load balancers
``` 
As said it worked in 09/2019. I had a look at the API logs - "insert_headers" was empty back then. I asked the Cloud provider whats going on there, but still no response.

**Comment by lingxiankong** [comment]
@jopfeffe That's probably because Octavia is not supported in your cloud provider, so they are still using Neturon-LBaaS which is not in the same support level as Octavia, becuase Neturon-LBaaS has been deprecated in OpenStack since Queens release(2018-02).

As a workaround, maybe you could try k8scloudprovider/openstack-cloud-controller-manager:v1.15.0

**Comment by jopfeffe** [comment]
I tested v1.15.0 with and without `use-octavia=true`. I got still the same result.

**Comment by timuthy** [comment]
We've been experiencing the same issue. I think this is related to a wrong type assumption: https://github.com/gophercloud/gophercloud/issues/1989

**Comment by eumel8** [comment]
@timuthy yeah, we puzzled that again together and build an image for that:

https://github.com/mcsps/cloud-provider-openstack/tree/release-1.18
mcsps/cloud-provider-opentelekomcloud:1.18 on docker hub

But that's ugly and a horror to maintain and we won't do this for 1.19 and further. For shure, that's not the place to maintain it here, so we asked also OTC support to step in, but without success.

There is a [cloud-provider-huaweicloud](https://github.com/kubernetes-sigs/cloud-provider-huaweicloud) in the wild, but a lot of features are missing and we weren't able to connect to the OTC.

**Comment by lingxiankong** [comment]
I'm pretty sure the issue is invalid for openstack-cloud-controller-manager, as I replied previously:

1. Make sure Octavia is deployed and enabled in your OpenStack cloud.
2. Make sure OCCM is using Octavia by setting `use-octavia=true`.
3. Make sure you can add load balancer/listener/pool/member etc. in your Octavia service. 

If you find anything else that OCCM should fix, please let us know.
