### ISSUE TITLE
failed to make cross in k8s when go version is 1.13

### ISSUE THREAD

**Issue by sxmatch** [kubernetes/cloud-provider-openstack#964]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**The binaries affected**:

- [ ] openstack-cloud-controller-manager
- [ ] cinder-csi-plugin
- [ ] k8s-keystone-auth
- [ ] client-keystone-auth
- [ ] octavia-ingress-controller
- [ ] manila-csi-plugin
- [ ] manila-provisioner
- [ ] magnum-auto-healer
- [ ] barbican-kms-plugin

**What happened**:
After "make build" in cloud provider openstack,  follow the instruction of getting-started to "make cross" in k8s.  Then, there is an error raised:

~/go/src/k8s.io/kubernetes$ make cross

Detected go version: go version go1.13 linux/amd64.
Kubernetes requires go1.13.4 or greater.
Please install go1.13.4 or later.

!!! [0310 03:30:18] Call tree:
!!! [0310 03:30:18]  1: hack/run-in-gopath.sh:31 kube::golang::setup_env(...)

Detected go version: go version go1.13 linux/amd64.
Kubernetes requires go1.13.4 or greater.
Please install go1.13.4 or later.

!!! [0310 03:30:18] Call tree:
!!! [0310 03:30:18]  1: ./hack/run-in-gopath.sh:31 kube::golang::setup_env(...)
Makefile.generated_files:535: recipe for target 'gen_bindata' failed
make[2]: *** [gen_bindata] Error 1
Makefile:544: recipe for target 'generated_files' failed
make[1]: *** [generated_files] Error 2
Makefile:505: recipe for target 'cross' failed
make: *** [cross] Error 1

**What you expected to happen**:
pass the "make cross" without error.

**How to reproduce it**:
Just make cross in k8s.

**Anything else we need to know?**:

**Environment**: ubuntu 18.04.3 LTS
- openstack-cloud-controller-manager version: latest
- OpenStack version: master
- Others: none

**Comment by lingxiankong** [comment]
It was introduced by https://github.com/kubernetes/kubernetes/pull/82809, so we should update the get started guide to mention that when installing golang.

@sxmatch Are you interested in fixing that in your PR https://github.com/kubernetes/cloud-provider-openstack/pull/961?

**Comment by sxmatch** [comment]
> It was introduced by [kubernetes/kubernetes#82809](https://github.com/kubernetes/kubernetes/pull/82809), so we should update the get started guide to mention that when installing golang.
> 
> @sxmatch Are you interested in fixing that in your PR #961?

sure, np, I will update it
