### ISSUE TITLE
[cinder-csi-plugin] update external snapshoter and provisioner 

### ISSUE THREAD

**Issue by jichenjc** [kubernetes/cloud-provider-openstack#968]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
> /kind bug
> /kind feature

**The binaries affected**:

- [ ] openstack-cloud-controller-manager
- [x ] cinder-csi-plugin
- [ ] k8s-keystone-auth
- [ ] client-keystone-auth
- [ ] octavia-ingress-controller
- [ ] manila-csi-plugin
- [ ] manila-provisioner
- [ ] magnum-auto-healer
- [ ] barbican-kms-plugin

**What happened**:

https://github.com/kubernetes-csi/external-snapshotter/releases
https://github.com/kubernetes-csi/external-provisioner/blob/release-1.5/CHANGELOG-1.5.md
has some incompatible changes, need address them then update our used container version

**What you expected to happen**:

**How to reproduce it**:

**Anything else we need to know?**:

**Environment**:
- openstack-cloud-controller-manager version:
- OpenStack version:
- Others:

**Comment by ramineni** [comment]
provisoner already updated to 1.6.0 and snapshotter is being tracked by https://github.com/kubernetes/cloud-provider-openstack/issues/951

So, closing this issue.

/close
