### ISSUE TITLE
LoadBalancer: Error updating load balancer with new hosts map

### ISSUE THREAD

**Issue by ivomarino** [kubernetes/cloud-provider-openstack#970]
/kind bug

**The binaries affected**:

- [X] openstack-cloud-controller-manager
- [ ] cinder-csi-plugin
- [ ] k8s-keystone-auth
- [ ] client-keystone-auth
- [ ] octavia-ingress-controller
- [ ] manila-csi-plugin
- [ ] manila-provisioner
- [ ] magnum-auto-healer
- [ ] barbican-kms-plugin

**What happened**:
When I try to allocate a LB I get the following error:
```
E0312 18:09:51.881145       1 controller.go:714] failed to check if load balancer exists for service default/loadbalanced-service: Resource not found
E0312 18:09:51.881262       1 controller.go:680] failed to update load balancer hosts for service default/loadbalanced-service: Resource not found
I0312 18:09:51.881321       1 event.go:281] Event(v1.ObjectReference{Kind:"Service", Namespace:"default", Name:"loadbalanced-service", UID:"62f7d88d-3bbe-4d09-95e3-e00d869d36b9", APIVersion:"v1", ResourceVersion:"3298", FieldPath:""}): type: 'Warning' reason: 'UpdateLoadBalancerFailed' Error updating load balancer with new hosts map[dev-cluster-pool1-6859d6dfc5-gch75:{}]: Resource not found
```
`kubectl get svc`:
```
loadbalanced-service          LoadBalancer   10.109.45.16    <pending>     80:31852/TCP   1s
```
Running:
`k8scloudprovider/openstack-cloud-controller-manager   v1.17.0`

**What you expected to happen**:

**How to reproduce it**:
```
kubectl run echoserver --image=gcr.io/google-containers/echoserver:1.10 --port=8080
applyed this then:
---
kind: Service
apiVersion: v1
metadata:
  name: loadbalanced-service
spec:
  selector:
    run: echoserver
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
```

**Environment**:
- openstack-cloud-controller-manager version: v1.17.0
- OpenStack version:
- Others:

**Comment by kayrus** [comment]
@ivomarino at first glance it looks like you didn't set the `use-octavia` [flag](https://github.com/kubernetes/cloud-provider-openstack/blob/master/docs/provider-configuration.md#load-balancer-optional-parameters) in cloud-config file. Please clarify which lbaas services are available in your environment.

**Comment by ivomarino** [comment]
Hi @kayrus, thanks for feedback, unfortunately the cluster does actually not provide `octavia`

**Comment by chrigl** [comment]
@ivomarino Hey. Do you maybe set the `use-octavia = true` config value? Btw... `use-octavia = true` is the new default since 5 days (https://github.com/kubernetes/cloud-provider-openstack/commit/ae0546ac492876b774442152ef92b02cf862fd88). You should definitely set it to false in your setup.

Does your openstack support neutron-lbaasv2? `openstack extension list | grep lbaasv2`
